:description: This section describes how to manage databases across clusters.
:page-role: new-2026.03 enterprise-edition not-on-aura
[[database-management]]
= Replicating databases across clusters

Preview Feature
[IMPORTANT]
====
The *cross-cluster database replication feature is offered AS-IS* as described in your agreement with Neo4j and should only be used for internal development purposes.

When this feature becomes generally available, you will need to upgrade to the latest Neo4j version (which may require downtime) to use the feature for non-development purposes.

During the Preview period, customers with active contracts may contact Neo4j Support through the standard support channels.
Please note that any cases related to the Preview feature will be classified as Severity 4 by default, in accordance with the link:https://neo4j.com/terms/support-terms/[Support Terms].
====

In 2026.03, cross-cluster database replication (CCDR) is introduced.
This provides the functionality for one database in a cluster to be replicated over to another cluster.
The original database is called _upstream_, while the database that replicates data is called the _replica_.
The replica continuously polls the upstream database for new transactions and applies them as soon as new transactions become available.

image::replication.svg[title="Schema of replicating a database across clusters", width="300"]

[[create-replica]]
== Create a replica database

The following procedure can be used to create a replica.

|===
| *Syntax* 3+m| internal.dbms.createReplicaDatabase(databaseName, numPrimaries, numSecondaries, {remote: upstreamDatabaseName, addresses: remoteAddresses})
| *Description* 3+a| Retrieve all available statistical data about the current database, in an anonymized form.
.6+| *Input arguments* | *Name* | *Type* | *Description*
| `databaseName` | `STRING` | The name of the replica in the current cluster. Note that the databaseName can be the same as that of the upstreamDatabaseName.
| `numPrimaries` | `INTEGER` | The number of replica primaries. These primaries will align with the mode constraints set on the server, but will not be writable because they are still replicas.
| `numSecondaries` | `INTEGER` | The number of replica secondaries.
| `upstreamDatabaseName` | `STRING` | The name of the upstream database in the remote cluster.
| `remoteAddresses` | `LIST<STRING>` | A list of the link:{neo4j-docs-base-uri}/operations-manual/current/configuration/configuration-settings/#config_dbms.cluster.endpoints[cluster endpoints] of the servers in the remote cluster.
| *Mode* 3+| WRITE
|===

[NOTE]
====
In the preview version, the `block` store format is only supported for the upstream and replica databases.
====

Let's assume you have two separate clusters running independently from each other: *Cluster A* and *Cluster B*. +
On *Cluster A*, the database `foo` is running and has three servers with cluster addresses: `server01.example.com:6000`, `server02.example.com:6000`, `server03.example.com:6000`.
// On *ClusterB*, the database `bar` is running.

To create a replica database `foo-replica` with three primaries and two secondaries on *Cluster B* that will replicate from the upstream database `foo` from *Cluster A*, run the following Cypher command:

[source, cypher]
----
CALL internal.dbms.createReplicaDatabase("foo-replica", 3, 2, {remote: "foo", addresses:["server01.example.com:6000","server02.example.com:6000","server03.example.com:6000"]});
----

All replica databases are *read-only*.
A replica database can have topology with primary and secondary copies that follow the servers' mode constraints.
However, both primaries and secondaries remain read-only.
//However, neither primaries nor secondaries accept write operations.

The command can only be executed successfully if the replica database is able to contact the servers of *Cluster A* and if the upstream database `foo` exists and is running.
If not, the command results in an error.

Verify that the `foo-replica` database is online on the desired number of servers, in the desired roles.
Note that the type is labelled as `replica`.

[source, cypher, role=noplay]
----
SHOW DATABASE foo-replica;
----

[queryresult]
----
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| name          | type      | aliases | access       | address          | role         | writer | requestedStatus | currentStatus | statusMessage | default | home  | constituents|
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "foo-replica" | "replica" | []      | "read-write" | "localhost:7687" | "primary"    | FALSE  | "online"        | "online"      | ""            | FALSE   | FALSE | []          |
| "foo-replica" | "replica" | []      | "read-write" | "localhost:7688" | "primary"    | FALSE  | "online"        | "online"      | ""            | FALSE   | FALSE | []          |
| "foo-replica" | "replica" | []      | "read-write" | "localhost:7689" | "primary"    | FALSE  | "online"        | "online"      | ""            | FALSE   | FALSE | []          |
| "foo-replica" | "replica" | []      | "read-write" | "localhost:7690" | "secondary"  | FALSE  | "online"        | "online"      | ""            | FALSE   | FALSE | []          |
| "foo-replica" | "replica" | []      | "read-write" | "localhost:7691" | "secondary"  | FALSE  | "online"        | "online"      | ""            | FALSE   | FALSE | []          |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

5 rows available after 3 ms, consumed after another 1 ms
----

[[promote-replica]]
== Promote a replica database

A replica database can be promoted to become a write-available database.
This can be useful in disaster recovery (DR) scenarios when the source cluster becomes unavailable.

|===
| *Syntax* 3+m| internal.dbms.promoteReplicaDatabase(replicaDatabaseName, numPrimaries, numSecondaries)
| *Description* 3+a| Retrieve all available statistical data about the current database, in an anonymized form.
.4+| *Input arguments* | *Name* | *Type* | *Description*
| `replicaDatabaseName` | `STRING` | The name of the replica in the current cluster which is going to be promoted.
| `numPrimaries` | `INTEGER` | The number of primaries. These primaries will align with the mode constraints set on the server, and will become writable.
| `numSecondaries` | `INTEGER` | The number of  replica secondaries.
| *Mode* 3+| WRITE
|===

[IMPORTANT]
====
Promotion is a one-way operation.
Once a replica is promoted, it cannot be re-attached to the original source.
To resume replication, you need to create a new replica.
====

On *Cluster B*, to promote the replica database `foo-replica` with three primaries and two secondaries, run the following Cypher command:

[source, cypher]
----
CALL internal.dbms.promoteReplicaDatabase('foo-replica', 3, 2);
----

Note that you can change the number of primaries and secondaries during this promotion.
In the current example, you kept the same number of primaries and secondaries when creating the replica.

Verify that the `foo-replica` database is online on the and has type `standard`.

[source, cypher, role=noplay]
----
SHOW DATABASE foo-replica;
----

[queryresult]
----
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| name          | type       | aliases | access       | address          | role         | writer | requestedStatus | currentStatus | statusMessage | default | home  | constituents|
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "foo-replica" | "standard" | []      | "read-write" | "localhost:7687" | "primary"    | TRUE   | "online"        | "online"      | ""            | FALSE   | FALSE | []          |
| "foo-replica" | "standard" | []      | "read-write" | "localhost:7688" | "primary"    | FALSE  | "online"        | "online"      | ""            | FALSE   | FALSE | []          |
| "foo-replica" | "standard" | []      | "read-write" | "localhost:7689" | "primary"    | FALSE  | "online"        | "online"      | ""            | FALSE   | FALSE | []          |
| "foo-replica" | "standard" | []      | "read-write" | "localhost:7690" | "secondary"  | FALSE  | "online"        | "online"      | ""            | FALSE   | FALSE | []          |
| "foo-replica" | "standard" | []      | "read-write" | "localhost:7691" | "secondary"  | FALSE  | "online"        | "online"      | ""            | FALSE   | FALSE | []          |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

5 rows available after 3 ms, consumed after another 1 ms
----

One of these primary databases is now also write-available as the `WRITER` equals to `TRUE`.


[[replication-metrics]]
== Replication metrics

Replicas are asynchronously replicating data from the upstream database.
Therefore, it is useful to track the replication lag between the upstream and replica database.
In order to do this, plot the xref:monitoring/metrics/reference.adoc#db-tx-metrics[`<prefix>.database.<db>.transaction.last_committed_tx_id`] metric for both the upstream and replica databases.
The difference between them is a signal of how much replication lag there is.

[[roles-and-permissions]]
== Roles and permissions

[IMPORTANT]
====
Permissions and roles are not copied over when replicating a database.
====

Permissions and role-based access control have to be set up separately on *Cluster A* and *Cluster B* as they cannot be copied over.
You should treat the two clusters as independent entities, with a database replicating between them.
Furthermore, the `system` database cannot be replicated.

Ensure that clusters are on the same Neo4j version.

[[inter-cluster-encryption]]
== Inter-cluster encryption

Firstly, ensure that each cluster is encrypted using link:{neo4j-docs-base-uri}/operations-manual/current/clustering/setup/encryption[intra-cluster encryption].
To ensure that both *Cluster A* and *Cluster B* can mutually authenticate, each cluster must trust the Certificate Authority (CA) that signs the other cluster’s certificates.

If clusters use different CAs, the CA certificate of *Cluster A* must be installed in the `trusted/` directory of *Cluster B*, and vice versa.

For example, here is one possible cert folder configuration:

[source, shell]
----
ClusterA

cluster/
├── private.key                 ← clusterA node private key
├── public.crt                  ← clusterA node certificate
├── trusted/
│   └── clusterB-ca.crt         ← CA that signs ClusterB node certs
└── revoked/


ClusterB

cluster/
├── private.key                 ← ClusterB node private key
├── public.crt                  ← ClusterB node certificate
├── trusted/
│   └── clusterA-ca.crt         ← CA that signs ClusterA node certs
└── revoked/
----


[[dr-scenario]]
== Disaster recovery scenario

It is recommended to set up two independent clusters in two different cloud regions.
The upstream database should be in the main cluster, and the replica database will be in a DR-cluster in another region.
If the main region has gone down, you can promote the replicating database in the DR-cluster and redirect data traffic to the promoted database.

[cols="a,a,a", grid=none, frame=none]
|===
|image::disaster-step-1.svg[width="250", title="Disaster"]
|image::disaster-step-2.svg[width="250", title="Promoting the replica database"]
|image::disaster-step-3.svg[width="250", title="Redirecting data traffic"]
|===

[[failback]]
== Failback

Failback is the process of restoring the main cluster back into operation after a DR scenario.
This is under the assumption that the promoted database is currently running in the DR-cluster.

To restore the previous source database, follow the steps:

. In the current example, the replica database's upstream is the promoted database `foo-replica` in the DR-cluster, *Cluster B* (see _Figure 3_). +
Create a replica database `foo` in the main cluster which is *Cluster A*.
+
image::recovery.svg[width=350, title="Recovery after a disaster"]
+
. Stop write operations on the promoted database `foo-replica` in *Cluster B*.
. Check the metrics to ensure that `tx_id` is exactly the same for both the promoted and replicating databases.
. Promote the replica database `foo` in *Cluster A*, meaning that this database starts serving write operations and becomes again the main database serving traffic.
. Stop the database `foo-replica` in the DR-cluster, and create a new replica `foo-new-replica` with the upstream pointing to the main database `foo` in the main cluster (see _Figure 5_).
+
image::replication-restored.svg[width=350, title="Restoring the upstream database in the main cluster"]



