:description: This section describes how to manage databases across clusters.
:page-role: new-2026.08 enterprise-edition not-on-aura cypher-25
[[database-management]]
= Replicating databases across clusters

[[ccdr-overview]]
== Overview

In 2026.08, cross-cluster database replication (CCDR) is officially released.
This provides the functionality for one database in a <<cluster>> to be replicated over to another cluster.
The original database is called _upstream_ or _source_, while the database that replicates data is called the _replica_.

There are two mechanisms for replicating databases across clusters:

* Replication via the network (see _Figure 1_).
* Replication via backups (see _Figure 2_).

Both mechanisms poll for new transactions/backups and apply them as soon as new transactions/backups become available.

image::replication.svg[title="Schema of replicating a database across clusters via the network", width="300"]

[[via-backups]]
image::replication-via-backups.svg[title="Schema of replicating a database across clusters via backups", width="350"]

The commands and procedures for creating and promoting replica databases are supported by Cypher 25.

All replica databases are *read-only*.
A replica database can have topology with primary and secondary copies that follow the servers' mode constraints.
However, both primaries and secondaries remain read-only.
Neither replica primaries nor replica secondaries accept write operations.

[NOTE]
====
Only standard databases can be used as upstream sources for cross-cluster database replication.
Composite databases and sharded property databases (SPD) are not supported as replication sources.
====

[[create-replica-via-the-network]]
== Creating a replica database via the network

This creation method is recommended when the two clusters are directly connected over the network.
Inter-cluster encryption and mutual trust between the clusters are also strongly recommended.

[[syntax-create-replica-db-via-network]]
.CREATE REPLICA DATABASE via the network connection
[source, syntax, role="noheader"]
----
CREATE REPLICA DATABASE name
[[SET] TOPOLOGY n PRIMAR{Y|IES} [m SECONDAR{Y|IES}]]
OPTIONS {replicaConfig: {remote: upstreamDatabaseName, addresses: remoteAddresses}}
[WAIT [n [SEC[OND[S]]]]|NOWAIT]
----

.`replicaConfig` for remote addresses
[options="header", width="100%", cols="2m,4a"]
|===
| Option | Description

| replicaConfig
|
Replica config of upstream details to pull from.

Type: `MAP`

Defines the upstream information for the replica to pull from.
Possible keys of this map include:

`remote`:: The name of the upstream database in a remote cluster.
`addresses`:: A list of xref:configuration/configuration-settings.adoc#config_dbms.cluster.endpoints[cluster endpoints] for the servers in the remote cluster.
Use this if there is a direct network connection between clusters. +
+
If the upstream cluster runs 2026.08 or later, there is no requirement that every remote server hosts the upstream database.
However, if the upstream runs a version earlier than 2026.08, every remote server in the `addresses` has to host the upstream database.
|===

[[create-replica-db-example]]
=== Example

Let's assume you have two separate clusters running independently from each other: *Cluster A* and *Cluster B*.

On *Cluster A*, the database `foo` is running and has three servers with cluster addresses: `server01.example.com:6000`, `server02.example.com:6000`, `server03.example.com:6000`.

On *Cluster B*, run the following command to create a replica database `foo-replica` (three primaries, two secondaries) that will replicate from the upstream database `foo` on *Cluster A*:

[source, cypher]
----
CREATE REPLICA DATABASE `foo-replica`
TOPOLOGY 3 PRIMARIES 2 SECONDARIES
OPTIONS {
  replicaConfig: {
    remote: "foo",
    addresses: [
      "server01.example.com:6000",
      "server02.example.com:6000",
      "server03.example.com:6000"
    ]
  }
};
----

The command can only be executed successfully if the replica database is able to contact the remote cluster endpoints listed in `addresses`.
If not, the command results in an error.

[TIP]
====
You can also create a replica database from a database backup using `seedURI`.
See xref:database-administration/standard-databases/seed-from-uri.adoc[] for details.

If a `seedURI` is specified, the initial seeding of the replica database is done from the `seedURI`:

[source, cypher, role=noplay]
----
CREATE REPLICA DATABASE `foo-replica`
TOPOLOGY 3 PRIMARIES 1 SECONDARY
OPTIONS {
  seedURI: "s3://myBucket/myBackup.backup",
  replicaConfig: {
    remote: "foo",
    addresses: [
      "server01.example.com:6000",
      "server02.example.com:6000",
      "server03.example.com:6000"
    ]
  }
};
----

After initial seeding, the replica pulls transactions from the upstream database using the servers listed in `addresses`.
====

By running the `SHOW DATABASES` command, you can verify that the `foo-replica` database is online on the desired number of servers, in the desired roles.
Note that the database type is `replica`, and the `options` column shows its configuration.

[source, cypher, role=noplay]
----
SHOW DATABASE `foo-replica` YIELD name, type, access, address, role, writer, options;
----

[queryresult]
----
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| name          | type      | access       | address          | role         | writer | options                                                                                                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "foo-replica" | "replica" | "read-only"  | "localhost:7687" | "primary"    | FALSE  | {replicaConfig: {remote: "foo", addresses: ["server01.example.com:6000", "server02.example.com:6000", "server03.example.com:6000"]}}  |
| "foo-replica" | "replica" | "read-only"  | "localhost:7688" | "primary"    | FALSE  | {replicaConfig: {remote: "foo", addresses: ["server01.example.com:6000", "server02.example.com:6000", "server03.example.com:6000"]}}  |
| "foo-replica" | "replica" | "read-only"  | "localhost:7689" | "primary"    | FALSE  | {replicaConfig: {remote: "foo", addresses: ["server01.example.com:6000", "server02.example.com:6000", "server03.example.com:6000"]}}  |
| "foo-replica" | "replica" | "read-only"  | "localhost:7690" | "secondary"  | FALSE  | {replicaConfig: {remote: "foo", addresses: ["server01.example.com:6000", "server02.example.com:6000", "server03.example.com:6000"]}}  |
| "foo-replica" | "replica" | "read-only"  | "localhost:7691" | "secondary"  | FALSE  | {replicaConfig: {remote: "foo", addresses: ["server01.example.com:6000", "server02.example.com:6000", "server03.example.com:6000"]}}  |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

5 rows available after 3 ms, consumed after another 1 ms
----

[[inter-cluster-encryption]]
=== Configuring inter-cluster encryption

Firstly, ensure that each cluster is encrypted using link:{neo4j-docs-base-uri}/operations-manual/current/clustering/setup/encryption[intra-cluster encryption].
To ensure that both *Cluster A* and *Cluster B* can mutually authenticate, each cluster must trust the Certificate Authority (CA) that signs the other cluster’s certificates.

If clusters use different CAs, the CA certificate of *Cluster A* must be installed in the `trusted/` directory of *Cluster B*, and vice versa.

For example, here is one possible certificate folder configuration:

[source, shell]
----
ClusterA

cluster/
├── private.key                 ← clusterA node private key
├── public.crt                  ← clusterA node certificate
├── trusted/
│   └── clusterB-ca.crt         ← CA that signs ClusterB node certs
└── revoked/


ClusterB

cluster/
├── private.key                 ← ClusterB node private key
├── public.crt                  ← ClusterB node certificate
├── trusted/
│   └── clusterA-ca.crt         ← CA that signs ClusterA node certs
└── revoked/
----

=== Recovery point objective (RPO)

Network replication streams transactions from the upstream database to the replica.
This provides a near-zero recovery point objective (RPO), subject to any asynchronous replication lag between the upstream and replica databases.

To configure a catchup interval, modify the xref:configuration/configuration-settings.adoc#config_db.cluster.catchup.pull_interval[`db.cluster.catchup.pull_interval`] setting, which defaults to one second (`1s`).

For details about monitoring replication lag, see <<replication-metrics, Monitoring replica databases>>.


[[create-replica-via-remote-backup-pulling]]
== Creating a replica database with remote backup pulling

Replication can also be done by retrieving backups through cloud object storage or a file system (see <<via-backups, _Figure 2_>>).
The advantage of this approach is that it eliminates the need for a direct network connection between the clusters.


[[create-replica-db-via-backups]]
.CREATE REPLICA DATABASE via remote backup pulling
[source, syntax, role="noheader"]
----
CREATE REPLICA DATABASE name
[[SET] TOPOLOGY n PRIMAR{Y|IES} [m SECONDAR{Y|IES}]]
OPTIONS {replicaConfig: {remote: upstreamDatabaseName, pullURI: backupURI}}
[WAIT [n [SEC[OND[S]]]]|NOWAIT]
----

.`replicaConfig` for pulling backups
[options="header", width="100%", cols="2m,4a"]
|===
| Option | Description

| replicaConfig
|
Replica configuration of upstream details to pull from.

Type: `MAP`

Defines the upstream information for the replica to pull from.
Possible keys of this map include:

`remote`:: The name of the upstream database in a remote cluster.
`pullURI`:: A URI from which the replica can pull backups when using backup pulling method.
Use this to replicate a database via cloud object storage or a file system, without requiring a direct network connection between clusters.
|===

[IMPORTANT]
====
The backup-producing process and the replica database need access to the object storage location used by `pullURI`.
Bucket permissions must be configured before the replica database is created.
For details, see xref:database-administration/standard-databases/seed-from-uri.adoc#cloud-seed-provider[`CloudSeedProvider`].
====

[[replica-initialization]]
=== Initialization of a replica

Initialization starts from a complete backup chain.
A complete backup chain contains a full backup and, optionally, some number of differential backups that follow it without gaps.
You have to create and push the complete backup chain to the bucket or file-system location used for replica initialization.

image::replica-backup-pulling-initialization.svg[title="Initializing a replica database from a complete backup chain", width="700"]

When only `pullURI` is specified, the complete backup chain must be available at `pullURI`.
The replica initializes its store from that backup chain.

To create a replica, run the following command:

[source, cypher]
----
CREATE REPLICA DATABASE `foo-replica`
TOPOLOGY 3 PRIMARIES 1 SECONDARY
OPTIONS {
  replicaConfig: {
    remote: "foo",
    pullURI: "s3://myBucket//"
  }
};
----

[TIP]
====
You can also create a replica database from a database backup using `seedURI`.
See xref:database-administration/standard-databases/seed-from-uri.adoc[] for details.

If a `seedURI` is also specified, the initial seeding of the replica database is done from the `seedURI`.:

[source, cypher, role=noplay]
----
CREATE REPLICA DATABASE `foo-replica`
TOPOLOGY 3 PRIMARIES 1 SECONDARY
OPTIONS {
  seedURI: "s3://myBucket/myBackup.backup",
  replicaConfig: {
    remote: "foo",
    pullURI: "s3://myBucket/"
  }
};
----

`pullURI` is used after initialization to pull differential backups.
====


[[replica-running]]
=== Running a replica

After initialization, a replica database consumes only differential backups from `pullURI`.
The differential backup chain must remain unbroken from the replica database's current point onward.

You are responsible for continuing to create and push differential backups from the upstream database to the `pullURI` location.

image::replica-backup-pulling-running.svg[title="Running a replica database by pulling differential backups", width="700"]

To view the replica configuration, yield the `options` column:

[source, cypher, role=noplay]
----
SHOW DATABASE `foo-replica` YIELD name, type, access, address, role, writer, options;
----

[queryresult]
----
+-------------------------------------------------------------------------------------------------------------------------------------------------+
| name          | type      | access      | address          | role        | writer | options                                                     |
+-------------------------------------------------------------------------------------------------------------------------------------------------+
| "foo-replica" | "replica" | "read-only" | "localhost:7687" | "primary"   | FALSE  | {replicaConfig: {remote: "foo", pullURI: "s3://myBucket/"}} |
| "foo-replica" | "replica" | "read-only" | "localhost:7688" | "primary"   | FALSE  | {replicaConfig: {remote: "foo", pullURI: "s3://myBucket/"}} |
| "foo-replica" | "replica" | "read-only" | "localhost:7689" | "primary"   | FALSE  | {replicaConfig: {remote: "foo", pullURI: "s3://myBucket/"}} |
| "foo-replica" | "replica" | "read-only" | "localhost:7690" | "secondary" | FALSE  | {replicaConfig: {remote: "foo", pullURI: "s3://myBucket/"}} |
+-------------------------------------------------------------------------------------------------------------------------------------------------+
----

=== Recovery point objective (RPO)

RPO is determined by the frequency of differential backup creation and transmission, combined with the replica pull interval.
A replica database checks for new differential backups at the interval configured by xref:configuration/configuration-settings.adoc#config_db.cluster.backup.pull_interval[`db.cluster.backup.pull_interval`], which defaults to 1 minute (`1m`).

To achieve a low RPO:

* Increase backup frequency: create and push differential backups more often.
* Reduce the pull interval if needed.
* Use <<create-replica-via-the-network, network replication>>, which streams transactions continuously and provides a near-zero RPO.

For example, with hourly differential backups and the default 1-minute pull interval, failover can result in up to one hour of data loss.
Increasing differential backup frequency to every 10 minutes while keeping the default 1-minute pull interval reduces potential data loss up to 10–15 minutes.
Note that the true RPO is dependent on time taken for the backup created, uploaded, pulled, and applied - and this is heavily dependent on workload.

As such it is important to implement observability tools to track the replication lag between the upstream and replica databases (see <<replication-metrics, Monitoring replica databases>>).
Growing lag often indicates a broken differential backup chain, which stops the replica from pulling new updates.
If this occurs, you must recreate the replica database from a complete backup chain before it can continue applying differential backups.

[[drivers-and-cypher-shell]]
== Accessing replica databases via drivers or Cypher Shell

Given that replica databases are read-only, you must ensure that the drivers either have "AccessMode" set to "READ", or are only doing `executeRead`.
Attempts to write to the replica database will fail.

Furthermore, when accessing the database via Cypher Shell, ensure that xref:cypher-shell.adoc#cypher-shell-access-mode[`--access-mode`] is also set to `read` when connecting.

[source, shell]
----
bin/cypher-shell --access-mode=read -a neo4j://localhost:7684 -d foo-replica
----

This is necessary because all our replicas are read-only.
Failure to do so would result in failure to find a `WRITE` server.

When accessing the database via the Neo4j Browser, ensure that the **Access mode** is set to **Read**.
This can be found in the link:https://neo4j.com/docs/browser/visual-tour/#_settings[Browser **Settings** drawer].


[[routing]]
== Setting up routing policies

Replica databases respect the built-in link:{neo4j-docs-base-uri}/operations-manual/current/clustering/multi-region-deployment/multi-data-center-routing/#builtin-routing-policies[routing policies].


Example 1::
+
For example, if you have no routing policies, querying the `CALL dbms.routing.getRoutingTable({}, "foo-replica");` returns all five servers you have as readers and no writers:
+
[source, shell]
----
+-------------------------------------------------------------------------------------------------------------------------------+
| ttl | servers                                                                                                                 |
+-------------------------------------------------------------------------------------------------------------------------------+
| 300 | [{addresses: ["localhost:7687", "localhost:7688", "localhost:7689", "localhost:7690", "localhost:7691"], role: "READ"}  |
+-------------------------------------------------------------------------------------------------------------------------------+
----

Example 2::
+
If you set `dbms.routing.reads_on_primaries_enabled=false` in the _neo4j.conf_ file to disable reads on primaries, the routing policy results in the following routing table where only the two replicas with secondary role are readers:
+
[source, shell]
----
+-------------------------------------------------------------------------+
| ttl | servers                                                           |
+-------------------------------------------------------------------------+
| 300 | [{addresses: ["localhost:7690", "localhost:7691"], role: "READ"}  |
+-------------------------------------------------------------------------+
----


[[roles-and-permissions]]
== Managing user roles and privileges

[IMPORTANT]
====
User privileges and roles are not copied over when replicating a database.
====

Permissions and role-based access control have to be set up separately on *Cluster A* and *Cluster B* as they cannot be copied over.
You should treat the two clusters as independent entities, with a standard database replicating between them.
Furthermore, the `system` database cannot be replicated.


[[replication-metrics]]
== Monitoring replica databases

Replicas asynchronously replicate data from the upstream database.
Therefore, it is important to track the replication lag between the upstream and the replica databases.
In order to do this, plot the xref:monitoring/metrics/reference.adoc#db-tx-metrics[`<prefix>.database.<db>.transaction.last_committed_tx_id`] metric for both the upstream and replica databases.
This difference effectively captures the lag between the upstream and the replica.

[[ccdr-versions-and-upgrades]]
== Versions and upgrades

[[ccdr-differing-versions]]
=== Differing versions upstream and downstream

The downstream cluster where the replica database is created must run Neo4j 2026.08 or later.
The upstream cluster can run Neo4j 2025.01 or later, but must not run a version later than the downstream cluster.

[[ccdr-upgrade-order]]
=== Upgrade order

When upgrading clusters that participate in cross-cluster database replication, upgrade the downstream cluster before the upstream cluster.

[[ccdr-upgrade-types]]
=== Upgrade types

When using <<create-replica-via-the-network, network-based replication>>, the server addresses specified in `replicaConfig.addresses` at replica creation time are fixed and cannot be changed afterwards.
The replica uses these exact addresses to connect to the upstream cluster.
This means that:

* *DNS-based upgrades* and *in-place rolling upgrades* are safe, because the server addresses remain the same.
* *New server rolling upgrades*, where new servers with different addresses replace the original ones, will cause replication to fail because the replica cannot discover the new addresses.

If you need to change the upstream addresses used by a replica, you must drop and recreate the replica database with the new addresses.


[[dr-scenario]]
== Disaster recovery scenario

It is recommended to set up two independent clusters in two different cloud regions.
If the main region has gone down, you can promote the replicating database in the disaster recovery cluster (DR-cluster) and redirect data traffic to the promoted database.

[cols="a,a,a", grid=none, frame=none]
|===
|image::disaster-step-1.svg[width="250", title="Disaster"]
|image::disaster-step-2.svg[width="250", title="Promoting the replica database"]
|image::disaster-step-3.svg[width="250", title="Redirecting data traffic"]
|===


[[promote-replica]]
=== Promoting a replica database

If the source cluster becomes unavailable, you can promote a replica database to accept writes.

[IMPORTANT]
====
Promotion is a one-way operation.
Once a replica is promoted, it cannot be re-attached to the original source.
To resume replication, you need to create a new replica.
====

Use the `dbms.promoteReplicaDatabase()` procedure to promote a replica database.
You can retain the current topology, or specify a new topology as part of the promotion.

[role=label--cypher-25]
.`dbms.promoteReplicaDatabase()`
|===
| *Syntax* 3+m| dbms.promoteReplicaDatabase(replicaDatabaseName, options)
| *Description* 3+a| Convert a replica database to a standard database while keeping the data it currently has.
.5+| *Input arguments* | *Name* | *Type* | *Description*
| `replicaDatabaseName` | `STRING` | The name of the replica in the current cluster which is going to be promoted.
| `options` | `MAP` | A map with optional topology settings for the promoted database. Use an empty map to retain the current topology.
| `primaries` | `INTEGER` | Optional key in `options`. The number of primaries for the promoted database. These primaries will align with the mode constraints set on the server, and will become writable.
| `secondaries` | `INTEGER` | Optional key in `options`. The number of secondaries for the promoted database.
| *Mode* 3+| WRITE
|===

On *Cluster B*, to promote the replica database `foo-replica` with the <<create-replica-db-example, existing topology which is three primaries and two secondaries>>, call the procedure with an empty options map:

[source, cypher]
----
CALL dbms.promoteReplicaDatabase('foo-replica', {});
----

You can also alter the replica's topology during promotion:

[source, cypher]
----
CALL dbms.promoteReplicaDatabase('foo-replica', {primaries: 3, secondaries: 4});
----

This will promote the replica database with three primaries and four secondaries.

The database becomes write-available.

Verify that the `foo-replica` database is online on the desired number of servers and has type `standard`.

[source, cypher, role=noplay]
----
SHOW DATABASE `foo-replica`;
----

[queryresult]
----
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| name          | type       | aliases | access       | address          | role         | writer | requestedStatus | currentStatus | statusMessage | default | home  | constituents|
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "foo-replica" | "standard" | []      | "read-write" | "localhost:7687" | "primary"    | TRUE   | "online"        | "online"      | ""            | FALSE   | FALSE | []          |
| "foo-replica" | "standard" | []      | "read-write" | "localhost:7688" | "primary"    | FALSE  | "online"        | "online"      | ""            | FALSE   | FALSE | []          |
| "foo-replica" | "standard" | []      | "read-write" | "localhost:7689" | "primary"    | FALSE  | "online"        | "online"      | ""            | FALSE   | FALSE | []          |
| "foo-replica" | "standard" | []      | "read-write" | "localhost:7690" | "secondary"  | FALSE  | "online"        | "online"      | ""            | FALSE   | FALSE | []          |
| "foo-replica" | "standard" | []      | "read-write" | "localhost:7691" | "secondary"  | FALSE  | "online"        | "online"      | ""            | FALSE   | FALSE | []          |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

5 rows available after 3 ms, consumed after another 1 ms
----

One of the primary databases is now write-available because the `writer` value is `TRUE`.
At this point, our routing tables will return both writers and readers as per a standard database.


[[failback]]
=== Failback

Failback is the process of restoring the main cluster back into operation after a DR scenario.
This is under the assumption that the promoted database is currently running in the DR-cluster.

To restore the previous source database, follow the steps:

. In the current example, the replica database's upstream is the promoted database `foo-replica` in the DR-cluster, *Cluster B* (see _Figure 8_). +
Create a replica database `foo` in the main cluster which is *Cluster A*.
+
image::recovery.svg[width=350, title="Recovery after a disaster"]
+
. Stop write operations on the promoted database `foo-replica` in *Cluster B*.
. Check the metrics to ensure that `tx_id` is exactly the same for both the promoted and replicating databases.
. Promote the replica database `foo` in *Cluster A*, meaning that this database starts serving write operations and becomes again the main database serving traffic.
. Stop and drop the database `foo-replica` in the DR-cluster.
Create a new replica `foo-new-replica` with the upstream pointing to the main database `foo` in the main cluster.
+
image::replication-restored.svg[width=350, title="Restoring the upstream database in the main cluster"]

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]

endif::[]
