[role=enterprise-edition]
[[causal-clustering-seed]]
= Seed a cluster
:description: How to seed a new Neo4j Causal Cluster with existing data. 

[[causal-clustering-seed-introduction]]
== Introduction

Regardless of whether you are just playing around with Neo4j or setting up a production environment, you likely have some existing data that you want to transfer into your xref:clustering/deploy.adoc[newly created Causal cluster].
Neo4j supports seeding a cluster from a database dump, a database backup, or from another data source (with the Import tool).
For more information about the different backup options and how to use the Neo4j Import tool, see xref:backup-restore/planning.adoc#backup-restore-options[Backup and restore options] and xref:tools/neo4j-admin.adoc[Neo4j Admin].

[NOTE]
====
The databases that you want to seed and the Neo4j cluster must be of the same version.
====


[[causal-clustering-seed-from-dump]]
== Seed a cluster from a database dump (offline)

If you have an existing Neo4j database that you want to use for your new cluster, use `xref:backup-restore/offline-backup.adoc[neo4j-admin dump]` to create an offline backup.
This could be an offline backup from a standalone Neo4j instance or a cluster member (e.g., an existing Read Replica).

[TIP]
====
This scenario is useful in disaster recovery where some servers have retained their data during a catastrophic event.
====

[CAUTION]
====
Moving files and directories manually in or out of a Neo4j installation is not recommended and considered unsupported.
====

. Create a new Neo4j Core-only cluster following the instructions in xref:clustering/deploy.adoc#causal-clustering-new-multi-machine-cluster[Configure a Core-only cluster].
. Delete the databases whose name conflicts with the ones in your seeds by using the Cypher command `DROP DATABASE <database-name` against the `system` database. +
The command is automatically routed to the leader and from there to the other cluster members.
+
[NOTE]
====
Dropping a database also deletes the users and roles associated with it.

If you cannot delete the database because Neo4j is not running or because your seeds include the `system` database (which cannot be dropped), you must run `neo4j-admin unbind`.

. Run xref:tools/unbind.adoc[`neo4j-admin unbind`] to turn the cluster members into standalone instances by removing their cluster state.
Otherwise, the store files you have (post restore) will be out of sync with the cluster state you have for that database, leading to logical corruption.
. Remove the store and transaction log files for the database in question.
The locations of these files may be xref:reference/configuration-settings.adoc#config_dbms.directories.logs[configured].
====
+
. Stop each cluster member.
. Use `neo4j-admin load` to seed each of the Core members in the cluster.
+
The examples assume that you are restoring one user database with the default name of `neo4j` and the `system` database, containing the replicated configuration state.
Modify the command line arguments to match your exact setup.
+
[source, shell]
----
neo4j-01$ ./bin/neo4j-admin load --from=/path/to/system.dump --database=system
neo4j-01$ ./bin/neo4j-admin load --from=/path/to/neo4j.dump --database=neo4j
----
+
[source, shell]
----
neo4j-02$ ./bin/neo4j-admin load --from=/path/to/system.dump --database=system
neo4j-02$ ./bin/neo4j-admin load --from=/path/to/neo4j.dump --database=neo4j
----
+
[source, shell]
----
neo4j-03$ ./bin/neo4j-admin load --from=/path/to/system.dump --database=system
neo4j-03$ ./bin/neo4j-admin load --from=/path/to/neo4j.dump --database=neo4j
----
+
. Start each cluster member.
+
[source, shell]
----
neo4j-01$ ./bin/neo4j start
----
+
[source, shell]
----
neo4j-02$ ./bin/neo4j start
----
+
[source, shell]
----
neo4j-03$ ./bin/neo4j start
----
+
The cluster forms and the replicated Neo4j DBMS deployment comes online.

[[causal-clustering-seed-from-backups]]
== Seed a cluster from a database backup (online)

If you have a running Neo4j database that you want to seed in a running cluster, use `xref:backup-restore/online-backup.adoc[neo4j-admin backup]` to create a database backup.
This could be a backup from a standalone Neo4j instance or another cluster member (e.g., an existing Read Replica).


You transfer that database backup to each core member and then use the `CREATE DATABASE` Cypher command to seed the cluster.
For more information on the `CREATE DATABASE` syntax and options, see link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/administration/databases/#administration-databases-create-database[Cypher Manual -> Creating databases].

[TIP]
====
These scenarios are useful when you want to restore a database in a running cluster.
====

[CAUTION]
====
Moving files and directories manually in or out of a Neo4j installation is not recommended and considered unsupported.
====

This example uses a user database called `movies1`.

. To be sure that the `movies1` database does not exist in the cluster, on one of the core members, use xref:tools/cypher-shell.adoc[Cypher Shell] and run `DROP DATABASE movies1`.
Use the `system` database to connect.
The command is automatically routed to the leader and from there to the other cluster members.
+
[source, cypher, role=noplay]
----
DROP DATABASE movies1;
----
+
[NOTE]
====
Dropping a database also deletes the users and roles associated with it.

If you cannot delete the database because Neo4j is not running or because your seeds include the `system` database (which cannot be dropped), you must run `neo4j-admin unbind`.

. Run xref:tools/unbind.adoc[`neo4j-admin unbind`] to turn the cluster members into standalone instances by removing their cluster state.
Otherwise, the store files you have (post restore) will be out of sync with the cluster state you have for that database, leading to logical corruption.
. Remove the store and transaction log files for the database in question.
The locations of these files may be xref:reference/configuration-settings.adoc#config_dbms.directories.logs[configured].
====
+
. Restore the database in each core member in the cluster.
+
[source, shell]
----
neo4j@core1$ ./bin/neo4j-admin restore --from=/path/to/movies1-backup-dir --database=movies1
----
+
[source, shell]
----
neo4j@core2$ ./bin/neo4j-admin restore --from=/path/to/movies1-backup-dir --database=movies1
----
+
[source, shell]
----
neo4j@core3$ ./bin/neo4j-admin restore --from=/path/to/movies1-backup-dir --database=movies1
----
+
However, restoring a database does not automatically create it.
. On one of the cluster members, run `CREATE DATABASE movies1` against the `system` database to create the `movies1` database.
The command is automatically routed to the leader and from there to the other cluster members.
+
[source, cypher, role=noplay]
----
CREATE DATABASE movies1;
----
+
[queryresult]
----
0 rows
ready to start consuming query after 701 ms, results consumed after another 0 ms
----
. Verify that the `movies1` database is online on all members.
+
[source, cypher, role=noplay]
----
SHOW DATABASES;
----
+
[queryresult]
----
+------------------------------------------------------------------------------------------+
| name     | address      | role       | requestedStatus | currentStatus | error | default |
+------------------------------------------------------------------------------------------+
| "neo4j"  | "core1:7687" | "leader"   | "online"        | "online"      | ""    | TRUE    |
| "neo4j"  | "core3:7687" | "follower" | "online"        | "online"      | ""    | TRUE    |
| "neo4j"  | "core2:7687" | "follower" | "online"        | "online"      | ""    | TRUE    |
| "movies1"| "core1:7687" | "leader"   | "online"        | "online"      | ""    | FALSE   |
| "movies1"| "core3:7687" | "follower" | "online"        | "online"      | ""    | FALSE   |
| "movies1"| "core2:7687" | "follower" | "online"        | "online"      | ""    | FALSE   |
| "system" | "core1:7687" | "follower" | "online"        | "online"      | ""    | FALSE   |
| "system" | "core3:7687" | "follower" | "online"        | "online"      | ""    | FALSE   |
| "system" | "core2:7687" | "leader"   | "online"        | "online"      | ""    | FALSE   |
+------------------------------------------------------------------------------------------+

9 rows available after 3 ms, consumed after another 1 ms
----

[[causal-clustering-seed-import]]
== Seed a cluster using the import tool

To create a cluster based on imported data, it is recommended to first import the data into a standalone Neo4j DBMS and then use an offline backup to seed the cluster.

. Import the data.
.. Deploy a standalone Neo4j DBMS.
.. Import the data using the xref:tools/neo4j-admin-import.adoc[import tool].
. Use `xref:backup-restore/offline-backup.adoc[neo4j-admin dump]` to create an offline backup of the `neo4j` database.
. Seed a new cluster using the instructions in xref:clustering/seed.adoc#causal-clustering-seed-from-dump[Seed a cluster from a database dump (offline)].
+
Skip the `system` database in this scenario since it is not needed.
