:description: This section provides a summary of server management Cypher syntax.
[role=enterprise-edition]
[[server-commands-reference]]
= Server commands reference

Servers can be added and managed using a set of Cypher administration commands executed against the `system` database.

When connected to the DBMS over `bolt`, administration commands are automatically routed to the `system` database.


[[server-management-syntax]]
== Server management command syntax

[NOTE]
====
More details about the syntax descriptions can be found xref:database-administration/syntax.adoc[here].
====

[cols="<15s,<85"]
|===
| Command
m| ENABLE SERVER

| Syntax
a|
[source, syntax, role=noheader]
----
ENABLE SERVER 'serverId' [OPTIONS "{" option: value[,...] "}"]
----

| Description
a| Adds a server that has been discovered to the cluster.
For more information see xref:clustering/servers.adoc#server-enabled-state[Enabled state].

| Required privilege
a| `GRANT SERVER MANAGEMENT`

(see xref:authentication-authorization/dbms-administration.adoc#access-control-dbms-administration-privilege-management[SERVER MANAGEMENT privileges])
|===

[cols="<15s,<85"]
|===
| Command
m| ALTER SERVER

| Syntax
a|
[source, syntax, role=noheader]
----
ALTER SERVER 'name' SET OPTIONS "{" option: value[,...] "}"
----

| Description
a| Changes the constraints for a server.
For more information see xref:clustering/servers.adoc#alter-server-options[Altering server options].

| Required privilege
a| `GRANT SERVER MANAGEMENT`

(see xref:authentication-authorization/dbms-administration.adoc#access-control-dbms-administration-privilege-management[SERVER MANAGEMENT privileges])
|===

[cols="<15s,<85"]
|===
| Command
m| RENAME SERVER

| Syntax
a|
[source, syntax, role=noheader]
----
RENAME SERVER 'name' TO 'newName'
----

| Description
a| Changes the name of a server.
For more information see xref:clustering/servers.adoc#_renaming_a_server[Renaming a server].

| Required privilege
a| `GRANT SERVER MANAGEMENT`

(see xref:authentication-authorization/dbms-administration.adoc#access-control-dbms-administration-privilege-management[SERVER MANAGEMENT privileges])
|===

[cols="<15s,<85"]
|===
| Command
m| REALLOCATE DATABASES

| Syntax
a|
[source, syntax, role=noheader]
----
[DRYRUN] REALLOCATE DATABASE[S]
----

| Description
a| Re-balances databases among the servers in the cluster.
For more information see xref:clustering/servers.adoc#_hosting_databases_on_added_servers[Hosting databases on added servers].

| Required privilege
a| `GRANT SERVER MANAGEMENT`

(see xref:authentication-authorization/dbms-administration.adoc#access-control-dbms-administration-privilege-management[SERVER MANAGEMENT privileges])
|===

[cols="<15s,<85"]
|===
| Command
m| DEALLOCATE DATABASES

| Syntax
a|
[source, syntax, role=noheader]
----
[DRYRUN] DEALLOCATE DATABASE[S] FROM SERVER[S] 'name'[, ...]
----

| Description
a| Removes all databases from the given servers.
For more information see xref:clustering/servers.adoc#_deallocating_databases_from_a_server[Deallocating databases from  server].

| Required privilege
a| `GRANT SERVER MANAGEMENT`

(see xref:authentication-authorization/dbms-administration.adoc#access-control-dbms-administration-privilege-management[SERVER MANAGEMENT privileges])
|===

[cols="<15s,<85"]
|===
| Command
m| DROP SERVER

| Syntax
a|
[source, syntax, role=noheader]
----
DROP SERVER 'name'
----

| Description
a| Removes a server not hosting any databases from the cluster.
For more information see xref:clustering/servers.adoc#_dropping_a_server[Dropping a server].

| Required privilege
a| `GRANT SERVER MANAGEMENT`

(see xref:authentication-authorization/dbms-administration.adoc#access-control-dbms-administration-privilege-management[SERVER MANAGEMENT privileges])
|===

[cols="<15s,<85"]
|===
| Command
m| SHOW SERVERS

| Syntax
a|
[source, syntax, role=noheader]
----
SHOW SERVER[S]
  [YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
  [WHERE expression]
  [RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----

| Description
a| Lists all servers visible to the cluster.
For more information see xref:clustering/servers.adoc#_listing_servers[Listing servers].

| Required privilege
a| `GRANT SHOW SERVERS`

(see xref:authentication-authorization/dbms-administration.adoc#access-control-dbms-administration-privilege-management[SERVER MANAGEMENT privileges])
|===

[[server-management-show-servers]]
== show servers

[role=not-on-aura]
[[server-management-enable-server]]
== Enabling servers

A server can be added to the cluster with the `ENABLE SERVER 'name'` command.
The servers initial name is its id.
The server must be in the `free` state to be added to the cluster.
If the server is already `enabled` and the command is executed with the same options specified nothing is changed.
In any other case trying to enable a server fails.

The possible options allowed when enabling a server are:






[[server-management-rename-server]]
== Renaming servers

[[server-management-reallocate]]
== Reallocate databases



[role=not-on-aura]
[[server-management-deallocate]]
== Deallocate databases

A server can be set to not host any databases with `DEALLOCATE DATABASES FROM SERVER 'name'`, in preparation for removing the server from the cluster.
Either the id or name of the server can be used.
All databases that the server is hosting are moved to other servers.
The server changes state to `deallocating`.
A deallocated server cannot readily be enabled again.

Multiple servers can be deallocated at the same time, `DEALLOCATE DATABASES FROM SERVER 'server-1', 'server-2'`.
The command fails if there aren't enough servers available to move the databases to.

Using `DRYRUN DEALLOCATE DATABASES FROM 'server-1', 'server-2'` returns a view of how the databases would have been re-balanced if the command was executed without `DRYRUN`:

.Result
[options="header,footer", width="100%", cols="m,m,m,m,m,m"]
|===
|database|fromServerName|fromServerId|toServerName|toServerId|mode
| "db1" | "server-1" | "00000001-8c04-4731-a2fd-7b0289c511ce" | "server-4" | "00000002-5b91-43c1-8b25-5289f674563e" | "primary"
| "db1" | "server-2" | "00000000-7e53-427c-a987-24634c4745f3" | "server-5" | "00000003-0e98-44c8-9844-f0a4eb95b0d8" | "primary"
|===

[role=not-on-aura]
[[server-management-drop-server]]
== Drop server

When a server has been deallocated and is no longer hosting any databases it can be removed from the cluster with `DROP SERVER 'name'`.
Either the id or name of the server can be used.
As long as the server is running, it is listed when showing servers with the state `dropped`.
