:description: This section provides a summary of server management Cypher syntax.
[role=enterprise-edition]
[[server-commands-reference]]
= Server management command syntax

Servers can be added and managed using a set of Cypher administrative commands executed against the `system` database.

When connected to the DBMS over `bolt`, administrative commands are automatically routed to the `system` database.


[[server-management-syntax]]
== Server management command syntax

[NOTE]
====
More details about the syntax descriptions can be found on the page xref:database-administration/syntax.adoc#administration-syntax-reading[Database management command syntax -> Reading the administrative commands syntax].
====

=== Enable a server

[cols="<15s,<85"]
|===
| Command
m| ENABLE SERVER

| Syntax
a|
[source, syntax, role=noheader]
----
ENABLE SERVER 'serverId' [OPTIONS "{" option: value[,...] "}"]
----

| Description
a| Adds a server that has been discovered to the cluster.
For more information see xref:clustering/servers.adoc#server-enabled-state[Enabled state].

| Required privilege
a| `GRANT SERVER MANAGEMENT`

(see xref:authentication-authorization/dbms-administration/dbms-privilege-management-privileges.adoc[SERVER MANAGEMENT privileges])
|===


=== List servers

[cols="<15s,<85"]
|===
| Command
m| SHOW SERVERS

| Syntax
a|
[source, syntax, role=noheader]
----
SHOW SERVER[S]
  [YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
  [WHERE expression]
  [RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----

| Description
a| Lists all servers visible to the cluster.
For more information see xref:clustering/servers.adoc#_listing_servers[Listing servers].

| Required privilege
a| `GRANT SHOW SERVERS`

(see xref:authentication-authorization/dbms-administration/dbms-server-management-privileges.adoc[SERVER MANAGEMENT privileges])
|===


=== Alter server's options

[cols="<15s,<85"]
|===
| Command
m| ALTER SERVER

| Syntax
a|
[source, syntax, role=noheader]
----
ALTER SERVER 'name' SET OPTIONS "{" option: value[,...] "}"
----

| Description
a| Changes the constraints for a server.
For more information see xref:clustering/servers.adoc#alter-server-options[Altering server options].

| Required privilege
a| `GRANT SERVER MANAGEMENT`

(see xref:authentication-authorization/dbms-administration/dbms-server-management-privileges.adoc[SERVER MANAGEMENT privileges])
|===

=== Rename a server

[cols="<15s,<85"]
|===
| Command
m| RENAME SERVER

| Syntax
a|
[source, syntax, role=noheader]
----
RENAME SERVER 'name' TO 'newName'
----

| Description
a| Changes the name of a server.
For more information see xref:clustering/servers.adoc#_renaming_a_server[Renaming a server].

| Required privilege
a| `GRANT SERVER MANAGEMENT`

(see xref:authentication-authorization/dbms-administration/dbms-server-management-privileges.adoc[SERVER MANAGEMENT privileges])
|===


=== Remove a server

[cols="<15s,<85"]
|===
| Command
m| DROP SERVER

| Syntax
a|
[source, syntax, role=noheader]
----
DROP SERVER 'name'
----

| Description
a| Removes a server not hosting any databases from the cluster.
For more information see xref:clustering/servers.adoc#_dropping_a_server[Dropping a server].

| Required privilege
a| `GRANT SERVER MANAGEMENT`

(see xref:authentication-authorization/dbms-administration/dbms-privilege-management-privileges.adoc[SERVER MANAGEMENT privileges])
|===


=== Reallocate databases in a cluster

[cols="<15s,<85"]
|===
| Command
m| REALLOCATE DATABASES

| Syntax
a|
[source, syntax, role=noheader]
----
[DRYRUN] REALLOCATE DATABASE[S]
----

| Description
a| Re-balances databases among the servers in the cluster.
For more information see xref:clustering/servers.adoc#_hosting_databases_on_added_servers[Hosting databases on added servers].

Note that is a cluster-level command, not a server-level command.

| Required privilege
a| `GRANT SERVER MANAGEMENT`

(see xref:authentication-authorization/dbms-administration/dbms-privilege-management-privileges.adoc[SERVER MANAGEMENT privileges])
|===


=== Deallocate databases from a server

[cols="<15s,<85"]
|===
| Command
m| DEALLOCATE DATABASES

| Syntax
a|
[source, syntax, role=noheader]
----
[DRYRUN] DEALLOCATE DATABASE[S] FROM SERVER[S] 'name'[, ...]
----

| Description
a| Removes all user databases from the given servers.
For more information see xref:clustering/servers.adoc#_deallocating_databases_from_a_server[Deallocating databases from  server].

| Required privilege
a| `GRANT SERVER MANAGEMENT`

(see xref:authentication-authorization/dbms-administration/dbms-privilege-management-privileges.adoc[SERVER MANAGEMENT privileges])
|===

