[[manage-databases-queries]]
= Queries
:description: Examples of Cypher queries and commands that can be used to create and manage multiple active databases. 

[TIP]
====
For detailed information on Cypher administrative commands, see link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/administration[Cypher Manual -> Administration].
====

[NOTE]
====
All commands and example queries in this section are run in xref:tools/cypher-shell.adoc[the Neo4j Cypher Shell command-line interface (CLI)].

Note that the `cypher-shell` queries are not case-sensitive but must end with a semicolon.
====

[[manage-databases-queries-show-database]]
== Show the status of a specific database

.`SHOW DATABASE`
====
[source, cypher]
----
neo4j@system> SHOW DATABASE neo4j;
----

[queryresult]
----
+-----------------------------------------------------------------------------------------------+
| name    | address          | role         | requestedStatus | currentStatus | error | default |
+-----------------------------------------------------------------------------------------------+
| "neo4j" | "localhost:7687" | "standalone" | "online"        | "online"      | ""    | TRUE    |
+-----------------------------------------------------------------------------------------------+

1 row available after 100 ms, consumed after another 6 ms
----
====


[[manage-databases-queries-show-databases]]
== Show the status of all databases

.`SHOW DATABASES`
====
[source, cypher]
----
neo4j@system> SHOW DATABASES;
----

[queryresult]
----
+------------------------------------------------------------------------------------------------+
| name     | address          | role         | requestedStatus | currentStatus | error | default |
+------------------------------------------------------------------------------------------------+
| "neo4j"  | "localhost:7687" | "standalone" | "online"        | "online"      | ""    | TRUE    |
| "system" | "localhost:7687" | "standalone" | "online"        | "online"      | ""    | FALSE   |
+------------------------------------------------------------------------------------------------+

2 rows available after 5 ms, consumed after another 1 ms
----
====

Switching between `online` and `offline` states is achieved using the xref:manage-databases/queries.adoc#manage-databases-queries-start-database[`START DATABASE`] and xref:manage-databases/queries.adoc#manage-databases-queries-stop-database[`STOP DATABASE`] commands.


[[manage-databases-queries-show-default-databases]]
== Show the status of the default database

The config setting xref:reference/configuration-settings.adoc#config_dbms.default_database[`dbms.default_database`] defines which database is created and started by default when Neo4j starts.
The default value of this setting is `neo4j`.

.`SHOW DEFAULT DATABASE`
====
[source, cypher]
----
neo4j@system> SHOW DEFAULT DATABASE;
----

[queryresult]
----
+-------------------------------------------------------------------------------------+
| name    | address          | role         | requestedStatus | currentStatus | error |
+-------------------------------------------------------------------------------------+
| "neo4j" | "localhost:7687" | "standalone" | "online"        | "online"      | ""    |
+-------------------------------------------------------------------------------------+

1 row available after 57 ms, consumed after another 2 ms

----
====

You can change the default database by using xref:reference/configuration-settings.adoc#config_dbms.default_database[`dbms.default_database`], and restarting the server.

[NOTE]
====
In Community Edition, the default database is the only database available, other than the `system` database.
====

[role=enterprise-edition]
[[manage-databases-queries-create-database]]
== Create a database

.`CREATE DATABASE`
====
[source, cypher]
----
neo4j@system> CREATE DATABASE sales;
----

[queryresult]
----
0 rows available after 108 ms, consumed after another 0 ms
----

[source, cypher]
----
neo4j@system> SHOW DATABASES;
----

[queryresult]
----
+------------------------------------------------------------------------------------------------+
| name     | address          | role         | requestedStatus | currentStatus | error | default |
+------------------------------------------------------------------------------------------------+
| "neo4j"  | "localhost:7687" | "standalone" | "online"        | "online"      | ""    | TRUE    |
| "system" | "localhost:7687" | "standalone" | "online"        | "online"      | ""    | FALSE   |
| "sales"  | "localhost:7687" | "standalone" | "online"        | "online"      | ""    | FALSE   |
+------------------------------------------------------------------------------------------------+

3 rows available after 4 ms, consumed after another 1 ms
----
====

[role=enterprise-edition]
[[manage-databases-queries-switch-database]]
== Switch a database

.`:use <database-name>`
====
[source, cypher]
----
neo4j@system> :use sales
neo4j@sales>
----
====

[[manage-databases-queries-replace-database]]
== Create or replace a database

.`CREATE OR REPLACE DATABASE`
====

[source, cypher]
----
neo4j@sales> match (n) return count(n) as countNode;
----

[queryresult]
----
+-----------+
| countNode |
+-----------+
| 115       |
+-----------+

1 row available after 12 ms, consumed after another 0 ms
----

[source, cypher]
----
neo4j@system> CREATE OR REPLACE DATABASE sales;
----

[queryresult]
----
0 rows available after 64 ms, consumed after another 0 ms
----

[source, cypher]
----
neo4j@system> SHOW DATABASES;
----

[queryresult]
----
+------------------------------------------------------------------------------------------------+
| name     | address          | role         | requestedStatus | currentStatus | error | default |
+------------------------------------------------------------------------------------------------+
| "neo4j"  | "localhost:7687" | "standalone" | "online"        | "online"      | ""    | TRUE    |
| "system" | "localhost:7687" | "standalone" | "online"        | "online"      | ""    | FALSE   |
| "sales"  | "localhost:7687" | "standalone" | "online"        | "online"      | ""    | FALSE   |
+------------------------------------------------------------------------------------------------+

3 rows available after 2 ms, consumed after another 2 ms
----

[source, cypher]
----
neo4j@system> :use sales
neo4j@sales> match (n) return count(n) as countNode;
----

[queryresult]
----
+-----------+
| countNode |
+-----------+
| 0         |
+-----------+

1 row available after 15 ms, consumed after another 1 ms
----

====

[[manage-databases-queries-stop-database]]
== Stop a database

.`STOP DATABASE`
====
[source, cypher]
----
neo4j@system> STOP DATABASE sales;
----

[queryresult]
----
0 rows available after 18 ms, consumed after another 6 ms
----

[source, cypher]
----
neo4j@system> SHOW DATABASES;
----

[queryresult]
----
+------------------------------------------------------------------------------------------------+
| name     | address          | role         | requestedStatus | currentStatus | error | default |
+------------------------------------------------------------------------------------------------+
| "neo4j"  | "localhost:7687" | "standalone" | "online"        | "online"      | ""    | TRUE    |
| "system" | "localhost:7687" | "standalone" | "online"        | "online"      | ""    | FALSE   |
| "sales"  | "localhost:7687" | "standalone" | "offline"       | "offline"     | ""    | FALSE   |
+------------------------------------------------------------------------------------------------+

3 rows available after 2 ms, consumed after another 1 ms
----

[source, cypher]
----
neo4j@system> :use sales
----

[queryresult]
----
Unable to get a routing table for database 'sales' because this database is unavailable
neo4j@sales[UNAVAILABLE]>

----

====


[[manage-databases-queries-start-database]]
== Start a database

.`START DATABASE`
====
[source, cypher]
----
neo4j@sales[UNAVAILABLE]> :use system
neo4j@system> START DATABASE sales;
----

[queryresult]
----
0 rows available after 21 ms, consumed after another 1 ms
----

[source, cypher]
----
neo4j@system> SHOW DATABASES;
----

[queryresult]
----
+------------------------------------------------------------------------------------------------+
| name     | address          | role         | requestedStatus | currentStatus | error | default |
+------------------------------------------------------------------------------------------------+
| "neo4j"  | "localhost:7687" | "standalone" | "online"        | "online"      | ""    | TRUE    |
| "system" | "localhost:7687" | "standalone" | "online"        | "online"      | ""    | FALSE   |
| "sales"  | "localhost:7687" | "standalone" | "online"        | "online"      | ""    | FALSE   |
+------------------------------------------------------------------------------------------------+

3 rows available after 2 ms, consumed after another 1 ms
----

====

[role=enterprise-edition]
[[manage-databases-queries-drop-database]]
== Drop or remove a database

.`DROP DATABASE`
====
[source, cypher]
----
neo4j@system> DROP DATABASE sales;
----

[queryresult]
----
0 rows available after 82 ms, consumed after another 1 ms
----

[source, cypher]
----
neo4j@system> SHOW DATABASES;
----

[queryresult]
----
+------------------------------------------------------------------------------------------------+
| name     | address          | role         | requestedStatus | currentStatus | error | default |
+------------------------------------------------------------------------------------------------+
| "neo4j"  | "localhost:7687" | "standalone" | "online"        | "online"      | ""    | TRUE    |
| "system" | "localhost:7687" | "standalone" | "online"        | "online"      | ""    | FALSE   |
+------------------------------------------------------------------------------------------------+

2 rows available after 6 ms, consumed after another 0 ms
----
====
