:description: Page lists changes in Neo4j 2026 series. Here you can find changes made to procedures, configurations settings, metrics, and `neo4j-admin` commands.

//Check Mark
:check-mark: icon:check[]


[[removals-deprecations-2026]]
= Changes, deprecations, and removals in Neo4j 2026.x


== Deprecations in Neo4j 2026.x

This section lists all the Neo4j Server features deprecated in the 2026 series, including replacements where applicable.

For deprecations in Cypher language, see link:{neo4j-docs-base-uri}/cypher-manual/current/deprecations-additions-removals-compatibility/[Cypher manual -> Deprecations, additions, and compatibility].

=== Operating systems

Neo4j 2026.01::

CentOS Stream 8.x is deprecated as of 2026.01.

This operating system will continue to be supported along with the next LTS release in 2026, but new releases after the 2026 LTS will no longer support this platform.
It is recommended to upgrade to a supported OS version before the next LTS release.

=== Linux distributions

System V (SysV) init scripts, located in _/etc/rc.d/init.d/_ or _/etc/init.d_, are included with the Neo4j package installation.
Starting with 2026.01, they are considered deprecated and will be removed in a future release.

All currently supported Linux distributions use `systemd` not SysV init scripts by default.

== Changes in Neo4j 2026.x

The section covers changes to Neo4j server functionality across different areas.

=== Cypher Shell

For details, refer to xref:cypher-shell.adoc[].

Neo4j 2026.01::

A new parameter `--debug` is added as an alias for the `--log` option.
