:description: Page lists changes and non-breaking removals in Neo4j 2025-2026 series. Here you can find changes made to procedures, configurations settings, metrics, and `neo4j-admin` commands, cypher shell, and more.

//Check Mark
:check-mark: icon:check[]

= Changes and removals

The section covers changes to Neo4j server functionality since 5.26 LTS across different areas per version, as well as non-breaking removals.

== Cypher default version

Neo4j 2026.02::

Starting from Neo4j 2026.02, the distributed _neo4j.conf_ *explicitly sets* `db.query.default_language=CYPHER_25`.
As a result, new deployments using the provided configuration file default to Cypher 25 for newly created databases.
For details, see xref:configuration/cypher-version-configuration.adoc[Configure the Cypher default version].

== Neo4j-admin import commands

Neo4j 2025.12::

The default value of the `--bad-tolerance=<num>` option is changed from `1000` to `-1`, meaning unlimited.
For details, see xref:import.adoc[].

[role=label--enterprise-edition]
== Neo4j-admin backup command

Neo4j 2025.10::

The `--include-metadata=none|all|users[=user1,user2]|roles` option is changed to allow filtering users when performing a database backup.
Previously, if you specified `users` with `--include-metadata`, the backup file would include commands to create the users that can use the database and their role assignments.
Starting from 2025.10, you can define a list of specific users (e.g., `users=alice,bob,charlie`), which means only those users are included in the backup.
For details, refer to xref:backup-restore/online-backup.adoc[].

[role=label--enterprise-edition]
== Neo4j-admin copy command

Neo4j 2025.01::

The functionality of the `--from-pagecache=<size>` option is changed. +
Instead of specifying how much cache to allocate when reading the source, now you can control the maximum amount of off-heap memory used for the copy operation, both for reading and writing.
By configuring the off-heap memory value, you can impact the cache allocation as well. +
To reflect this change, a new name was added to the option: `--max-off-heap-memory=<size>`. +
For details, refer to the xref:backup-restore/copy-database.adoc#off-heap-memory-control[Improving the performance].


== Cypher Shell

For details, refer to xref:cypher-shell.adoc[].

Neo4j 2025.08::

A new argument `disable` is added to the `--history` option.

Neo4j 2025.06::

The default value of the `--error-format` option is changed from `legacy` to `gql`.

Neo4j 2026.01::

A new parameter `--debug` is added as an alias for the `--log` option.

[[configuration-settings-changes]]
== Configuration settings

Neo4j 2025.12::

label:enterprise[Enterprise Edition] xref:configuration/configuration-settings.adoc#config_initial.server.allowed_databases[`initial.server.allowed_databases`] and xref:configuration/configuration-settings.adoc#config_initial.server.denied_databases[`initial.server.denied_databases`] support database name patterns (wildcards), and the minimum length is reduced from `3` to `1`.

Neo4j 2025.06::

label:enterprise[Enterprise Edition] The following metrics are removed from the default value of the xref:configuration/configuration-settings.adoc#config_server.metrics.filter[`server.metrics.filter`]:
+
* cluster.internal.discovery.memberset.left
* cluster.internal.discovery.crdt.gossip_id_data.size
* cluster.internal.discovery.crdt.server_data.size
* cluster.internal.discovery.crdt.database_data.size
* cluster.internal.discovery.crdt.leader_data.size
* cluster.internal.discovery.crdt.total_merge_operations
* cluster.internal.discovery.crdt.total_update_operations
* cluster.internal.discovery.gossip.incoming_queue_size
* cluster.internal.discovery.gossip.total_received_data
* cluster.internal.discovery.gossip.total_sent_data
* cluster.internal.discovery.gossip.uncontactable_members_exist


Neo4j 2025.03::

label:enterprise[Enterprise Edition] The default value of the xref:configuration/configuration-settings.adoc#config_server.metrics.filter[`server.metrics.filter`] is changed.
+
The included *neo4j.count* metrics class replaces the deprecated *ids_in_use* metrics. +
For more information, see xref:monitoring/metrics/reference.adoc#db-data-count-metrics[Monitoring -> Metrics reference] and the tables _Database data count metrics_ and _Database data metrics_ respectively.


[[ssl-framework-changes]]
== SSL framework

Neo4j 2025.10::

The Java 21 default cipher suites that use insecure CBC-based ciphers are removed from Neo4j:

* TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
* TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
* TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
* TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
+
However, you still can use them by explicitly specifying their configuration and referencing them in your setup.


[[procedures-changes]]
== Procedures

Neo4j 2025.12::
label:cypher-25[]

* The `dbms.setDefaultAllocationNumbers()` procedure accepts an additional input parameter: `propertyShardReplicas`.
* The `dbms.showTopologyGraphConfig()` procedure includes `propertyShardReplicas` in its returned results.