= Data integrity and maintenance
:description:

[[transaction-logging]]
== Transaction logging

The transaction logs record all write operations in the database.
They are the "source of truth" in scenarios where the database needs to be recovered.
The transaction logs can be used to provide differential backups, as well as for cluster operations.
For any given configuration, at least the latest non-empty transaction log is kept.

Each database keeps its own directory with _transaction logs_.
The root directory where the transaction log folders are located is configured by xref:configuration/configuration-settings.adoc#config_server.directories.transaction.logs.root[`server.directories.transaction.logs.root`].

[NOTE]
====
The transaction log has nothing to do with log monitoring.
====


The transaction logs record all write operations in the database.
This includes additions or modifications to data, as well as the addition or modification of any indexes or constraints.

* The transaction logs are the "source of truth" in scenarios where the database needs to be recovered.

* The transaction logs are used for providing differential backups, as well as for cluster operations.

* For any given configuration, at least the latest non-empty transaction log will be kept.

An overview of configuration settings for transaction logging:

[cols="3", options="header"]
|===
| The _transaction log_ configuration
| Default value
| Description

| xref:configuration/configuration-settings.adoc#config_server.directories.transaction.logs.root[`server.directories.transaction.logs.root`]
| `transactions`
| Root location where Neo4j will store transaction logs for configured databases.

| xref:configuration/configuration-settings.adoc#config_db.tx_log.preallocate[`db.tx_log.preallocate`]
| `true`
| Specify if Neo4j should try to preallocate logical log file in advance.

| xref:configuration/configuration-settings.adoc#config_db.tx_log.rotation.retention_policy[`db.tx_log.rotation.retention_policy`]
| `2 days`
a|
Make Neo4j keep the logical transaction logs for being able to back up the database.
Can be used for specifying the threshold to prune logical logs after.

| xref:configuration/configuration-settings.adoc#config_db.tx_log.rotation.size[`db.tx_log.rotation.size`]
| `250M`
a|
Specifies at which file size the logical log will auto-rotate.
Minimum accepted value is `128K` (128 KiB).

|===


The retention and rotation policies for the Neo4j transaction logs, and how to configure them.


[[transaction-logging-log-location]]
== Log location

By default, transaction logs for a database are located at  _<neo4j-home>/data/transactions/<database-name>_.
Each database keeps its own directory with transaction logs.

The root directory where those folders are located is configured by xref:configuration/configuration-settings.adoc#config_server.directories.transaction.logs.root[`server.directories.transaction.logs.root`].
For maximum performance, it is recommended to configure transaction logs to be stored on a dedicated device.


[[transaction-logging-log-rotation]]
== Log rotation

Log rotation is configured using the parameter xref:configuration/configuration-settings.adoc#config_db.tx_log.rotation.size[`db.tx_log.rotation.size`].
By default, log switches happen when log sizes surpass 250 MB.


[[transaction-logging-log-retention]]
== Log retention

[WARNING]
====
Manually deleting transaction log files is not supported.
====

You can control the number of transaction logs that Neo4j keeps using the parameter xref:configuration/configuration-settings.adoc#config_db.tx_log.rotation.retention_policy[`db.tx_log.rotation.retention_policy`].
It is set to `2 days` by default, which means Neo4j keeps logical logs that contain any transaction committed within 2 days.
The configuration is dynamic, so if you need to update it, you do not have to restart Neo4j for the change to take effect.

Other possible values are:

* `true` or `keep_all` -- keep transaction logs indefinitely.
+
[NOTE]
====
This option is not recommended due to the effectively unbounded storage usage.
Old transaction logs cannot be safely archived or removed by external jobs since safe log pruning requires knowledge about the most recent successful checkpoint.
====

* `false` or `keep_none` -- keep only the most recent non-empty log.
+
Log pruning is called only after checkpoint completion to ensure at least one checkpoint and points to a valid place in the transaction log data.
In reality, this means that all transaction logs created between checkpoints will be kept for some time, and only after a checkpoint, the pruning strategy will remove them.
For more details on how to speed up checkpointing, see xref:configuration/transaction-logs.adoc#transaction-logging-log-pruning[Log pruning].
To force a checkpoint, run the procedure xref:reference/procedures.adoc#procedure_db_checkpoint[`call db.checkpoint()`].
+
[NOTE]
====
This option is not recommended in production Enterprise Edition environments, as <<differential-backup, differential backups>> rely on the presence of the transaction logs since the last backup.
====

* `<number><optional unit> <type>` where valid units are `k`, `M`, and `G`, and valid types are `files`, `size`, `txs`, `entries`, `hours`, and `days`.
+
.Types that can be used to control log retention
[options="header",cols="<15,<60,<25"]
|============================================

| Type
| Description
| Example

| files
| The number of the most recent logical log files to keep.
| "10 files"

| size
| Max disk size to allow log files to occupy.
| "300M size" or "1G size".

| txs
| The number of transactions to keep.
| "250k txs" or "5M txs".

| hours
| Keep logs that contain any transaction committed within N hours from the current time.
| "10 hours"

| days
| Keep logs that contain any transaction committed within N days from the current time.
| "50 days"

|============================================
+
.Configure log retention policy
====
This example shows some different ways to configure the log retention policy.

* Keep transaction logs indefinitely:
+
[source, properties, role="noheader"]
----
db.tx_log.rotation.retention_policy=true
----
+
or
+
[source, properties, role="noheader"]
----
db.tx_log.rotation.retention_policy=keep_all
----

* Keep only the most recent non-empty log:
+
[source, properties, role="noheader"]
----
db.tx_log.rotation.retention_policy=false
----
+
or
+
[source, properties, role="noheader"]
----
db.tx_log.rotation.retention_policy=keep_none
----

* Keep logical logs that contain any transaction committed within 30 days:
+
[source, properties, role="noheader"]
----
db.tx_log.rotation.retention_policy=30 days
----

* Keep logical logs that contain any of the most recent 500 000 transactions:
+
[source, properties, role="noheader"]
----
db.tx_log.rotation.retention_policy=500k txs
----
====

== Checkpointing

Checkpointing is the process of flushing all pending page updates from the page cache to the store files.
This is necessary for ensuring that the number of transactions that require being replayed during recovery is kept to a reasonable number, mostly to reduce recovery time after an improper shutdown.
Regardless of the existence of checkpoints, database operations remain safe, since all transactions not confirmed to have had their changes persisted to storage will be replayed on the next database startup.
However, that is dependent on the existence of the set of changes these transactions consist of, information that is kept in the transaction logs.
Keeping the list of non-applied transactions long (the interval between checkpoints is large) will result in the accumulation of transaction logs since they are necessary for recovery.
Checkpointing introduces a special “Checkpointing” entry in the transaction log which marks the last transaction at which checkpointing happened.
This is used to determine which transaction logs are no longer necessary since all the transactions they contain have been safely persisted in the store files.

The process of removing transaction logs that are no longer necessary for recovery is called pruning.
From the above description, it is apparent that pruning is dependent on checkpointing, in the sense that checkpointing determines which logs can be pruned or, put differently when pruning can happen since if a checkpoint doe not take place the set of prune-able transaction log files cannot have changed.
This dependency is expressed through the triggering of pruning (which may or may not include a check for their existence, as discussed below) whenever checkpointing happens.
This relationship is invariant and applies to the entirety of the discussion that follows.

Triggering of checkpointing (and pruning) events
Checkpointing, which is the driving event for pruning, can be triggered in a few different ways.

The simplest method, called "periodic", checks by default every 15 minutes whether there are changes pending flushing (i.e. transactions that have not been checkpointed yet). If so, it performs a checkpoint and subsequently triggers a log prune. Note that no checkpointing being performed imples no pruning happens. This is the default behaviour and the only one available in community edition.

In the enterprise edition, there are two additional checkpointing policies. The simplest is called "continuous" and, as the name implies, it constantly checks if a checkpoint is possible (that is, if any transactions committed since the last successful checkpoint) and if so, it performs it. Pruning is triggered immediately after it completes, just like in the periodic policy.

The third and final checkpointing policy is "volumetric". It checks every 10 seconds if any logs are available for pruning and, if so, it triggers a checkpoint and subsequently it prunes the logs. This policy appears to invert the control between checkpointing and pruning, but in reality it only changes the criteria for when checkpointing must happen. Instead of relying on a time trigger, as the previous two, it relies on a pruning check. Pruning will still happen after checkpointing has occured, as with the other two policies. Nevertheless, since the check depends on the existence of prunable transaction log files, this policy depends on pruning configuration, as described in the next session.

The policy to be used is controlled by the setting dbms.checkpoint and it defaults to "periodic".

[[transaction-logging-log-pruning]]
== Log pruning

Transaction log pruning refers to the safe and automatic removal of old, unnecessary transaction log files.
The transaction log can be pruned when one or more files fall outside of the configured retention policy.

Two things are necessary for a file to be removed:

* The file must have been rotated.
* At least one checkpoint must have happened in a more recent log file.

Observing that you have more transaction log files than you expected is likely due to checkpoints either not happening frequently enough, or taking too long.
This is a temporary condition and the gap between the expected and the observed number of log files will be closed on the next successful checkpoint.
The interval between checkpoints can be configured using:

[cols="3", options="header"]
|===
| Checkpoint configuration
| Default value
| Description

| xref:configuration/configuration-settings.adoc#config_db.checkpoint.interval.time[`db.checkpoint.interval.time`]
| `15m`
| Configures the time interval between checkpoints.

| xref:configuration/configuration-settings.adoc#config_db.checkpoint.interval.tx[`db.checkpoint.interval.tx`]
| `100000`
| Configures the transaction interval between checkpoints.
|===


If your goal is to have the least amount of transaction log data, it can also help to speed up the checkpoint process itself.
The configuration parameter xref:configuration/configuration-settings.adoc#config_db.checkpoint.iops.limit[`db.checkpoint.iops.limit`] controls the number of IOs per second the checkpoint process is allowed to use.
Setting the value of this parameter to `-1` allows unlimited IOPS, which can speed up checkpointing.

[NOTE]
====
Disabling the IOPS limit can cause transaction processing to slow down a bit.
For more information, see xref:performance/disks-ram-and-other-tips.adoc#performance-checkpoint-iops-limit[Checkpoint IOPS limit].
====
