:description: Page lists all deprecated features in Neo4j server features, including replacements where applicable. Here you can find deprecations in procedures, configurations settings, metrics, `neo4j-admin` commands, and more.
= Current deprecations

This section lists all current deprecations in Neo4j server features, ordered alphabetically, including replacements where applicable.
Deprecated features are only removed immediately after a long-term support (LTS) release.

For deprecations in Cypher language, see link:{neo4j-docs-base-uri}/cypher-manual/current/deprecations-additions-removals-compatibility/[Cypher manual -> Deprecations, additions, and compatibility].

== Cluster

2025.05::

The load balancing framework and the `dbms.routing.load_balancing.plugin=server_policies` configuration setting are deprecated.
See xref:clustering/load-balancing.adoc#mdc-load-balancing-framework[Load balancing framework] for more information.

== Configuration settings

.See all deprecated configuration settings
[%collapsible]
====
[options=header, cols="3m,1,1,2"]
|===
| Name
| Community Edition
| Enterprise Edition
| Comment

| xref:configuration/configuration-settings.adoc#config_dbms.routing.load_balancing.plugin[`dbms.routing.load_balancing.plugin`]
|
| {check-mark}
| label:deprecated[Deprecated in 2025.05]

| xref:configuration/configuration-settings.adoc#config_server.db.query_cache_size[`server.db.query_cache_size`]
| {check-mark}
| {check-mark}
| label:deprecated[Deprecated in 5.7]

| xref:configuration/configuration-settings.adoc#config_dbms.security.oidc.-provider-.auth_params[`dbms.security.oidc.<provider>.auth_params`]
|
| {check-mark}
| label:dynamic[] label:deprecated[Deprecated in 5.0.0]

| xref:configuration/configuration-settings.adoc#config_dbms.security.oidc.-provider-.client_id[`dbms.security.oidc.<provider>.client_id`]
|
| {check-mark}
| label:dynamic[] label:deprecated[Deprecated in 5.19]
|===
====

== Java API

Neo4j 5.26::

The server-side Notification API and the `getNotifications()` method of the Result Core API are deprecated.

== Neo4j Helm charts

Neo4j 5.26::

The MinIO (an AWS S3-compatible object storage API) support for Non-TLS/SSL endpoints in the _neo4j/neo4j-admin_ Helm charts is deprecated and replaced by s3Endpoint.
See xref:kubernetes/operations/backup-restore.adoc[Backup and restore] for more information.

== Neo4j error codes messages

Neo4j 2025.04::

Using the error messages programmatically is deprecated.
Because error messages might change in a future release, please parse or use GQLSTATUS error codes in your application code.
For details, see link:https://neo4j.com/docs/status-codes/current/errors/gql-errors/[Status Codes for Errors & Notifications -> List of GQLSTATUS error codes].

== Logging

Neo4j 2025.05::

The `failureReason` column of the JSON format query log is deprecated in favor of the `errorInfo` column.
For details, refer to xref:monitoring/logging.adoc#_json_format_log_entries[Logging -> JSON format log entries for log type query].

[role=label--enterprise]
== Metrics

.See all deprecated metrics
[%collapsible]
====
[options=header, cols="3,3"]
|===
| Name
| Comment

|xref:monitoring/metrics/reference.adoc#raft-metrics[`<prefix>.cluster.raft.tx_retries`] label:deprecated[Deprecated in 2025.02]
|The metric will be removed in a future release.

2+| xref:monitoring/metrics/reference.adoc#db-data-metrics[Database data metrics] label:deprecated[Deprecated in 5.15]
|`<prefix>.ids_in_use.relationship_type`|
|`<prefix>.ids_in_use.property`|
|`<prefix>.ids_in_use.relationship`|If you want to have a rough metric of how big your graph is, use xref:monitoring/metrics/reference.adoc#db-data-count-metrics[`<prefix>.neo4j.count.relationship`] instead.
|`<prefix>.ids_in_use.node`|If you want to have a rough metric of how big your graph is, use xref:monitoring/metrics/reference.adoc#db-data-count-metrics[`<prefix>.neo4j.count.node`] instead.
|===
====



== Neo4j-admin tool

.See all deprecated commands
[%collapsible]
====
[options=header, cols="3m,1,1,3"]
|===
| Name
| Community Edition
| Enterprise Edition
| Comment

| link:{neo4j-docs-base-uri}/operations-manual/5/backup-restore/aggregate[`neo4-admin database aggregate-backup`]
|
| {check-mark}
| label:deprecated[Deprecated in 2025.01] +
Replaced by xref:backup-restore/aggregate.adoc[`neo4j-admin backup aggregate`]
|===
====

.See all deprecated command options
[%collapsible]
====
[options=header, cols="3m,2,3"]
|===
| Command
| Option
| Comment

| link:{neo4j-docs-base-uri}/operations-manual/current/database-administration/standard-databases/migrate-database[`neo4-admin database migrate`]
| `--page-cache` label:deprecated[Deprecated in 2025.04]
| The option is deprecated and replaced by the `--max-off-heap-memory` option.
|===
====

== Operating systems

Neo4j 2026.01::

* CentOS Stream 8.x. +
This operating system will continue to be supported along with the next LTS release in 2026, but new releases after the 2026 LTS will no longer support this platform.
It is recommended to upgrade to a supported OS version before the next LTS release.

* System V (SysV) init scripts in Neo4j Linux distributions. +
The SysV init scripts are located in _/etc/rc.d/init.d/_ or _/etc/init.d_.
All currently supported Linux distributions use `systemd` by default, not SysV init scripts.

Neo4j 2025.10::

The following Linux distributions are deprecated:

* Red Hat Enterprise Linux 8.x
* Debian 11.x
* Windows Server 2022
* MacOS 13 Ventura
* MacOS 14 Sonoma
+
These operating systems will continue to be supported along with the next LTS release in 2026, but new releases after the 2026 LTS will no longer support these platforms.
It is recommended to upgrade to a supported OS version before the next LTS release.

== Procedures

.See all deprecated procedures
[%collapsible]
====
[options=header, cols="3m,1,1,3"]
|===
| Name
| Community Edition
| Enterprise Edition
| Comment

| xref:procedures.adoc#procedure_dbms_cluster_recreateDatabase[`dbms.cluster.recreateDatabase()`]
|
| {check-mark}
| label:deprecated[Deprecated in 2025.04] +
Replaced by xref:procedures.adoc#procedure_dbms_recreateDatabase[`dbms.recreateDatabase()`]

| xref:procedures.adoc#procedure_dbms_quarantineDatabase[`dbms.quarantineDatabase()`] label:admin-only[]
|
| {check-mark}
| label:deprecated[Deprecated in 2025.01] +
label:removed[Removed in Cypher 25] +
Replaced by xref:procedures.adoc#procedure_dbms_unquarantineDatabase[`dbms.unquarantineDatabase()`]

| xref:procedures.adoc#procedure_db_index_vector_createNodeIndex[`db.index.vector.createNodeIndex()`]
| {check-mark}
| {check-mark}
| label:deprecated[Deprecated in 5.26] +
label:removed[Removed in Cypher 25] +
Replaced by the Cypher command `CREATE VECTOR INDEX`.
For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/current/indexes/semantic-indexes/vector-indexes/#create-vector-index[Cypher Manual → Create a vector index].

| xref:procedures.adoc#procedure_dbms_cluster_uncordonServer[`dbms.cluster.uncordonServer()`]
|
| {check-mark}
| label:deprecated[Deprecated in 5.23]. +
label:removed[Removed in Cypher 25] +
Before Neo4j 5.23, the procedure can be run only with an admin privilege. +
Replaced by xref:clustering/server-syntax.adoc#server-management-syntax[`ENABLE SERVER`].

| xref:procedures.adoc#procedure_dbms_cluster_routing_getRoutingTable[`dbms.cluster.routing.getRoutingTable()`]
| {check-mark}
| {check-mark}
| label:deprecated[Deprecated in 5.21]. +
Replaced by: xref:procedures.adoc#procedure_dbms_routing_getRoutingTable[`dbms.routing.getRoutingTable()`].

| xref:procedures.adoc#procedure_cdc_current[`cdc.current()`] label:beta[]
|
| {check-mark}
| label:deprecated[Deprecated in 5.17] +
Replaced by: xref:procedures.adoc#procedure_db_cdc_current[`db.cdc.current()`]

| xref:procedures.adoc#procedure_cdc_earliest[`cdc.earliest()`] label:beta[]
|
| {check-mark}
| label:deprecated[Deprecated in 5.17] +
Replaced by: xref:procedures.adoc#procedure_db_cdc_earliest[`db.cdc.earliest()`]

| xref:procedures.adoc#procedure_cdc_query[`cdc.query()`] label:beta[] label:admin-only[]
|
| {check-mark}
| label:deprecated[Deprecated in 5.17] +
Replaced by: xref:procedures.adoc#procedure_db_cdc_query[`db.cdc.query()`]

| xref:procedures.adoc#procedure_db_create_setVectorProperty[`db.create.setVectorProperty()`] label:beta[]
| {check-mark}
| {check-mark}
| label:deprecated[Deprecated in 5.13] +
label:removed[Removed in Cypher 25] +
Replaced by: xref:procedures.adoc#procedure_db_create_setNodeVectorProperty[`db.create.setNodeVectorProperty()`]

| xref:procedures.adoc#procedure_dbms_upgrade[`dbms.upgrade()`] label:admin-only[]
| {check-mark}
| {check-mark}
| label:deprecated[Deprecated in 5.9] +
label:removed[Removed in Cypher 25]

| xref:procedures.adoc#procedure_dbms_upgradeStatus[`dbms.upgradeStatus()`] label:admin-only[]
| {check-mark}
| {check-mark}
| label:deprecated[Deprecated in 5.9] +
label:removed[Removed in Cypher 25]

| xref:procedures.adoc#procedure_dbms_cluster_readReplicaToggle[`dbms.cluster.readReplicaToggle()`] label:admin-only[]
|
| {check-mark}
| label:deprecated[Deprecated in 5.6] +
label:removed[Removed in Cypher 25] +
Replaced by: xref:procedures.adoc#procedure_dbms_cluster_secondaryReplicationDisable[`dbms.cluster.secondaryReplicationDisable()`].
|===
====

== Seed providers

Neo4j 5.26::

`S3SeedProvider` is replaced by the `CloudSeedProvider`.
For more information, see xref:database-administration/standard-databases/seed-from-uri.adoc#s3-seed-provider[Seed from URI].

== Store formats

Neo4j 5.23::

`standard` and `high_limit` formats are deprecated starting from Neo4j 5.23.
See xref:database-internals/store-formats.adoc#format-deprecations[Store formats -> Format deprecations] for more information.