[[operations-manual]]
= The Neo4j Operations Manual
:neo4j-buildnumber: {neo4j-version}
:download-center-uri: https://neo4j.com/deployment-center/
:upgrade-current-uri: https://neo4j.com/docs/upgrade-migration-guide/current/
:lucene-version: 5_4_0
:lucene-version-printed: 5.4.0
:lucene-base-uri: http://lucene.apache.org/core/{lucene-version}

:console: 0

This is the Neo4j Operations Manual, which includes all the operational details and instructions for installing and deploying Neo4j in a self-hosted environment or in the cloud.

The manual covers the series of Neo4j 5, including the long-term support release *5.26*.

[NOTE]
====
For all information on *upgrading and migrating Neo4j*, see link:{upgrade-current-uri}[the Neo4j Upgrade and Migration Guide].

*Neo4j AuraDB* is a fully managed Neo4j database, hosted in the cloud and requires no installation.
For more information, see the link:https://neo4j.com/aura/[AuraDB product page] and link:https://neo4j.com/docs/aura/current/[AuraDB documentation].
====

== Documentation updates for Neo4j 5.x

* Restructured chapter on clustering.
+
The new clustering infrastructure decouples servers from databases, improving scalability and cloud-readiness.
As such, the documentation has been restructured and rewritten.
For a detailed description and instructions on how to set up clustering, see xref:clustering/index.adoc[Clustering].

* Composite databases.
+
Fabric technology is used to improve the setting and management of sharded and federated databases with dynamic compositions of databases.
A new surface to administer Fabric databases, named Composite databases, is new in 5.0.
Configuration settings have been removed and Composite databases are now administered via Cypher commands.
For more information, see the new chapter on xref:database-administration/composite-databases/concepts.adoc[Composite databases], which replaces the _Fabric_ chapter from previous versions.

* `neo4j-admin` refresh.
+
All admin functionalities have been consolidated into a single tool, and all commands have been grouped by scope.
There is an optional neo4j-admin conf file and individual conf files for each command so that there is more control over values provided for each command.
Improved features, more control, and a consistent set of arguments for the database administrator. +
See xref:tools/neo4j-admin/index.adoc[Neo4j Admin and Neo4j CLI] for details.

* A major overhaul of backup and restore.
+
The new backup subsystem provides:

** Full and differential backup to an immutable file, and aggregation to compile a chain of backups into a full backup.
** Differential backup reduces storage requirements and provides point-in-time restore on timestamps or transaction IDs.
** A new backup API for backup management and operability and target multiple URIs in a single backup command to support clusters in Neo4j 5.x.

* Incremental offline import.
+
The `neo4j-admin database import` command can now add more data to existing databases. +
xref:tools/neo4j-admin/neo4j-admin-import.adoc[Import chapter] has been updated.
You can find more details there.

* Log4j integration completion.
+
The logging framework is fully integrated with Log4j, providing more functionality and better control of all the database logs. +
Configuration settings are located in the `<NEO4J_HOME>/conf` folder in the _user-logs.xml_ used for _neo4j.log_ and _server-logs.xml_ used for _debug.log_, _security.log_, _http.log_, and _query.log_.
Query log uses the same format as _neo4j.log_. +
Users are able to use/modify Log4j XML files. +
See xref:monitoring/logging.adoc[the section on the logging mechanisms in Neo4j] for more details.

* Updates in the *Cypher Shell* section.

** Cypher Shell supports impersonation.
+
Cypher Shell users can impersonate other users via `--impersonate` or the command `:impersonate` (requires `IMPERSONATE` privileges). +
Visit xref:tools/cypher-shell.adoc[Cypher Shell page] for more details.

** Cypher Shell logging.
+
New option `--log` is introduced to enable Java Driver logging to the specified file.
When users report problems with Java Driver/Bolt, now they can use Cypher Shell to try and replicate the issue without having to edit the client app that uses the driver. +
You can find more information in the xref:tools/cypher-shell.adoc[Cypher Shell section].

* Immutable privileges.
+
Immutable privileges are useful for restricting the actions of users who themselves are able to administer privileges.
Starting with Neo4j 5.26, immutable roles are also available. +
Cloud operators can use sidecar design pattern to control RBAC-based permissions. +
For more information, see xref:authentication-authorization/immutable-roles-privileges.adoc[Immutable roles and privileges].

* Changes to Neo4j indexes
** The B-tree index type has been removed.
** New Range and Point index types are available now.
** Neo4j 5.1 introduces an improved index provider, `text-2.0`, for enhanced performance.
New Text indexes will use the `text-2.0` provider by default.
**  Full-text indexes can now index lists of strings.
+
See xref:performance/index-configuration.adoc[Index configuration] for more details.

ifdef::backend-pdf[]
include::license.adoc[leveloffset=+1]
endif::[]

ifdef::backend-html5[(C) {copyright}]
ifndef::backend-pdf[]

Documentation license: link:{common-license-page-uri}[Creative Commons 4.0]
endif::[]
ifdef::backend-pdf[]
(C) {copyright}

Documentation license: <<license, Creative Commons 4.0>>
endif::[]