[[introduction]]
= Introduction
:description: This section provides a brief overview of the Neo4j editions, versioning, Cypher language, interaction, and capabilities. 
:description: Introduction to Neo4j, ACID-compliant, property graph, community edition, enterprise edition, Neo4j Aura.
:keywords: neo4j, edition, version, acid, cluster, node, relationship, property

:semver-uri: https://semver.org/
:aura-uri: https://neo4j.com/cloud/aura/
:bloom-uri: https://neo4j.com/bloom/
:download-center-drivers: https://neo4j.com/download-center/#drivers
:download-center-desktop: https://neo4j.com/download-center/#desktop
:download-center-cyphershell: https://neo4j.com/download-center/#cyphershell
:download-center-bloom: https://neo4j.com/download-center/#bloom
:wiki-acid-uri: https://en.wikipedia.org/wiki/ACID
:bolt-protocol-uri: https://neo4j-drivers.github.io/
:github-neo4j-neo4j-java-driver: https://github.com/neo4j/neo4j-java-driver
:github-neo4j-neo4j-javascript-driver: https://github.com/neo4j/neo4j-javascript-driver
:github-neo4j-neo4j-dotnet-driver: https://github.com/neo4j/neo4j-dotnet-driver
:github-neo4j-neo4j-python-driver: https://github.com/neo4j/neo4j-python-driver
:github-neo4j-neo4j-go-driver: https://github.com/neo4j/neo4j-go-driver
:github-spring-projects-spring-data-neo4j: https://github.com/spring-projects/spring-data-neo4j


//Check Mark
:check-mark: icon:check[]

//Cross Mark
:cross-mark: icon:times[]


Neo4j is the world’s leading graph database.
The architecture is designed for optimal management, storage, and traversal of nodes and relationships.
The graph database takes a property graph approach, which is beneficial for both traversal performance and operations runtime.
Neo4j offers dedicated memory management and memory-efficient operations.

Neo4j is scalable and can be deployed as a standalone server or across multiple machines in a fault-tolerant cluster for production environments.
Other features for production applications include hot backups and extensive monitoring.

There are two editions of Neo4j to choose from, the <<community-edition, _Community Edition_>> and the <<enterprise-edition, _Enterprise Edition_>>.
The Enterprise Edition includes all that Community Edition has to offer, plus extra enterprise requirements such as backups, clustering, and failover capabilities.


[[community-edition]]
== Community Edition

The Community Edition is a fully functional edition of Neo4j, suitable for single-instance deployments.
It has full support for key Neo4j features, such as ACID-compliant transactions, Cypher, and programming APIs.
It is ideal for learning Neo4j, do-it-yourself projects, and applications in small workgroups.


[[enterprise-edition]]
== Enterprise Edition

The Enterprise Edition extends the functionality of Community Edition to include key features for performance and scalability, such as a clustering architecture and online backup functionality.
Additional security features include role-based access control and LDAP support, for example, Active Directory.
It is the choice for production systems with requirements for scale and availability, such as commercial solutions and critical internal solutions.

[[versioning]]
== Versioning

Neo4j uses semantic versioning (link:{semver-uri}[Semantic Versioning Specification 2.0.0]).
Given a version number `MAJOR.MINOR.PATCH`, the increment is based on:

* `MAJOR` version - incompatible API changes towards previous `MAJOR` version.
* `MINOR` version - functionality in a backward-compatible manner.
* `PATCH` release - backward-compatible bug fixes.

Neo4j’s fully managed cloud service link:{aura-uri}[Neo4j Aura] uses only `MAJOR` versioning.


== Cypher

Cypher is a declarative query language for graphs.
Neo4j uses the property graph approach, where relationships are stored alongside the data in the model, and not computed at query time.
Cypher is a powerful, graph-optimized query language that understands, and takes advantage of, these stored connections.
When trying to find patterns or insights in data, Cypher queries are often much simpler and easier to write than massive SQL JOINs.
Since Neo4j does not have tables, there are no JOINs to worry about.

For more details, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/introduction/[The Neo4j Cypher Manual -> Introduction].


== Interaction

The recommended way of programmatically interacting with the database is either through the official Neo4j Drivers, or through using the link:{neo4j-docs-base-uri}/java-reference/{page-version}/javadocs/[Neo4j Java API].
Neo4j provides an link:{wiki-acid-uri}[ACID]-compliant transactional backend for your applications.


[[intro-drivers]]
=== The official Neo4j Drivers

The official Neo4j Drivers interacts with Neo4j via the link:{bolt-protocol-uri}[Bolt protocol ({bolt-protocol-uri})].

* link:{github-neo4j-neo4j-java-driver}[Neo4j Java Driver]
+
For Spring-powered applications there is also link:{github-spring-projects-spring-data-neo4j}[Spring Data Neo4j].
* link:{github-neo4j-neo4j-javascript-driver}[Neo4j JavaScript Driver]
* link:{github-neo4j-neo4j-python-driver}[Neo4j Python Driver]
* link:{github-neo4j-neo4j-dotnet-driver}[Neo4j .NET Driver]
* link:{github-neo4j-neo4j-go-driver}[Neo4j Go Driver]


[NOTE]
====
See the link:{download-center-drivers}[Neo4j Download Center - Drivers] for more links.
====


=== Other tools

* xref:tools/cypher-shell.adoc[Neo4j Cypher Shell] - Command line tool for Cypher queries. link:{download-center-cyphershell}[Neo4j Download Center - Cypher Shell].
* link:https://neo4j.com/docs/browser-manual/current/[Neo4j Browser] - Interact with Neo4j, create Cypher queries, and basic visualization capabilities.
* link:https://neo4j.com/docs/desktop-manual/current/[Neo4j Desktop] - Developer IDE or Management Environment for Neo4j instances. link:{download-center-desktop}[Neo4j Download Center - Neo4j Desktop].
* link:{bloom-uri}[Neo4j Bloom] - Explore and visualize graph data. link:{download-center-bloom}[Neo4j Download Center - Neo4j Bloom].


[[edition-details]]
== Neo4j feature details


=== Neo4j key features

.Key features
[cols="<60,^20,^20",frame="topbot",options="header"]
|===
| Feature
| Community Edition
| Enterprise Edition

a| link:https://www.gnu.org/licenses/quick-guide-gplv3.html[Open source under GPLv3]
|{check-mark}
|

^s| Native Graph
|
|

| Property graph model
| {check-mark}
| {check-mark}

| Native graph processing & storage
| {check-mark}
| {check-mark}

a| Standard and Aligned store format (link:https://neo4j.com/docs/operations-manual/current/tools/neo4j-admin/neo4j-admin-store-info/#neo4j-admin-store-standard[34 Billion Nodes & Relationships])
| {check-mark}
| {check-mark}

a| High_limit (link:https://neo4j.com/docs/operations-manual/current/tools/neo4j-admin/neo4j-admin-store-info/#neo4j-admin-store-high-limit[1 Quadrillion Nodes & Relationships])
| 
| {check-mark}

| ACID-compliant transactions
| {check-mark}
| {check-mark}

| Cypher graph query language
| {check-mark}
| {check-mark}

| _Slotted_ Cypher runtime
| {check-mark}
| {check-mark}

| _Pipelined_ Cypher runtime (faster)
| 
| {check-mark}

| Listing and terminating running queries
| 
| {check-mark}

| High-performance caching
| {check-mark}
| {check-mark}

| Cost-based query optimizer
| {check-mark}
| {check-mark}

^s| Clients and APIs
|
|

| Cypher Client
| {check-mark}
| {check-mark}

| Neo4j Browser with syntax highlighting
| {check-mark}
| {check-mark}

| Bolt Protocol
| {check-mark}
| {check-mark}

| Language drivers for C#, Go, Java, JavaScript & Python footnote:sepinstall[Must be downloaded and installed separately.]
| {check-mark}
| {check-mark}

| High-performance native API
| {check-mark}
| {check-mark}

a| APOC 450+ link:https://neo4j.com/docs/apoc/5/[Core Procedures and Functions]
| {check-mark}
| {check-mark}

| Support for Neo4j Graph Data Science Community Edition footnote:sepinstall[]
| {check-mark}
| {check-mark}

| Support for Neo4j Graph Data Science Enterprise Edition footnote:sepinstall[]
| 
| {check-mark}

^s| Indexes and constraints
|
|

| Fast writes via native label indexes
| {check-mark}
| {check-mark}

| Composite indexes
| {check-mark}
| {check-mark}

| Full-text node & relationship indexes
| {check-mark}
| {check-mark}

| Property uniqueness constraints
| {check-mark}
| {check-mark}

| Property existence constraints
|
| {check-mark}

| Property type constraints
|
| {check-mark}

| Node and relationship key constraints
| 
| {check-mark}

^s| Security
|
|

| Role-based access control
| 
| {check-mark}

| Sub-graph access control
| 
| {check-mark}

| LDAP and Active Directory integration
| 
| {check-mark}

| Kerberos security option
| 
| {check-mark}

^s| Data management
|
|

| Offline import
| 
| {check-mark}

| Offline incremental import
| 
| {check-mark}

| Auto-reuse of space
| {check-mark}
| {check-mark}

| Store copy
| 
| {check-mark}

| Offline backup (dump)
| {check-mark}
| {check-mark}

^s| Scale and availability
|
|

| Online back-up and restore
| 
| {check-mark}

| Multiple databases (beyond the `system` and default databases)
| 
| {check-mark}

| Autonomous clustering
| 
| {check-mark}

| Composite databases
| 
| {check-mark}

^s| Monitoring and management
|
|

| Endpoints and metrics for monitoring via Prometheus
| 
| {check-mark}

| Neo4j Operations Manager
| 
| {check-mark}

|===
