:description: This section describes commands for managing and administering a Neo4j DBMS.
:page-aliases: tools/neo4j-admin/index.adoc
[[neo4j-admin]]
= Neo4j Admin and Neo4j CLI

[[neo4j-admin-introduction]]
== Introduction

`neo4j-admin` and `neo4j` are command-line tools for managing and administering a Neo4j DBMS.
Both are installed as part of the product and can be executed with a number of commands.
The `neo4j` commands are equivalent to the most important commands in the `neo4j-admin` server category.

Both `neo4j-admin` and `neo4j` commands support the <<help-command, `--help`>> option, which prints the command's usage and options, and the <<version-command, `--version`>> option, which prints the version of the command.
All admin command options can also be provided in a file and passed to the command using the `@` prefix.
This is useful when the command line becomes too long to manage.
For example, `neo4j-admin database import full @/path/to/your/<args-filename> mydb`.
For more information, see link:https://picocli.info/#AtFiles[Picocli -> AtFiles] official documentation.

[NOTE]
====
All admin commands must be invoked with the same user as Neo4j runs as.
This guarantees that Neo4j will have full rights to start and work with the database files you use.
====

== The `neo4j-admin` tool

The `neo4j-admin` command-line tool is located in the xref:configuration/file-locations.adoc[_bin_] directory.

=== General synopsis

`neo4j-admin` has the following general synopsis:

`neo4j-admin [category] [command] [subcommand]`

=== `neo4j-admin` commands per category

All administration commands, except for `help` and `version`, are organized into the following three categories:

* `dbms` - DBMS-wide (for single and clustered environments) administration tasks
* `server` - server-wide administration tasks
* `database` - database-specific administration tasks
* `backup` - backup-specific tasks

[[neo4j-admin-commands]]
.Available commands per category
[options="header", cols="25,30a,50a"]
|===
| Category
| Command
| Description
.3+| `dbms`
| `set-default-admin`
| Sets the default admin user when no roles are present.

| `set-initial-password`
| Sets the initial password of the initial admin user (`neo4j`).

For details, see xref:configuration/set-initial-password.adoc[Set an initial password].

| `unbind-system-db`
| Removes and archives the cluster state of the `system` database so the instance can rebind to a new cluster state of the `system` database.

.13+| `server`

| `console`
| Starts DBMS server in the console.

| `get-id`
| Displays the server ID of an instance.
The server ID can be used to specify a server in Cypher commands.

| `license`
| Accept the license agreement. Possible options are `--accept-commercial` for the link:https://legal.neo4j.com/[commercial] or `--accept-evaluation` for the link:https://neo4j.com/terms/enterprise_us/[evaluation license].
This command must be run before starting the Neo4j Enterprise Edition.
Starting from Neo4j 2025.04, when using an evaluation license, the command prints information about the days remaining in the trial period.
If the evaluation license has expired, the command prints a warning with the number of days since the license expired.
`neo4j-admin server license` also logs information about license status in the _neo4j.log_ file on startup.

| `memory-recommendation`
| Prints recommendations for Neo4j heap and page cache memory usage.

For details, see xref:configuration/neo4j-admin-memrec.adoc[].

| `migrate-configuration`
| Migrates server configuration from the previous major version.

For details, see xref:configuration/migrate-configuration.adoc[].

| `report`
| Produces a ZIP/TAR of the most common information needed for remote assessments.

For details, see xref:monitoring/neo4j-admin-report.adoc[].

| `restart`
| Restarts the server daemon.

| `start`
| Starts the server as a daemon.

| `status`
| Gets the status of the server.

| `stop`
| Stops the server daemon.

| `unbind`
| Removes cluster state data from a stopped Neo4j server.

For details, see xref:clustering/unbind.adoc[].

| `validate-config`
| Performs configuration validation without starting the server.

For details, see xref:configuration/validate-config.adoc[].

| `windows-service`
| A command whose subcommands can be used to install, uninstall, and update Neo4j as a Windows service.

.11+| `database`

| `aggregate-backup` label:deprecated[Deprecated in 2025.01]
| Aggregates a chain of backup artifacts into a single artifact.

For details, see xref:backup-restore/aggregate.adoc[].

Replaced by `neo4j-admin backup aggregate`.

| `backup`
| Performs an online backup from a running Neo4j enterprise server.

| `check`
| Checks the consistency of a database.

For details, see xref:backup-restore/consistency-checker.adoc[].

| `copy`
| Copies a database and optionally applies filters.

For details, see xref:backup-restore/copy-database.adoc[].

| `dump`
| Dumps a database into a single-file archive.

For details, see xref:backup-restore/offline-backup.adoc[].

| `import`
| Imports a collection of CSV files.

For details, see xref:import.adoc[].

| `info`
| Prints information about a Neo4j database store.

For details, see xref:database-internals/neo4j-admin-store-info.adoc[].

| `load`
| Loads a database from an archive created with the `dump` command.

For details, see xref:backup-restore/restore-dump.adoc[].

| `migrate`
| Migrates a database from one store format to another or between versions of the same format.

For details, see xref:database-administration/standard-databases/migrate-database.adoc[].

| `restore`
| Restores a backed up database.

For details, see xref:backup-restore/restore-backup.adoc[].

| `upload`
| Pushes a local database to a Neo4j Aura instance.

For details, see xref:database-administration/standard-databases/upload-to-aura.adoc[].

.2+| `backup`

|`inspect`
| Lists the metadata stored in the header of backup files.

For details, see xref:backup-restore/inspect.adoc[].

|`aggregate` label:new[Introduced in 2025.01]
|Aggregates a chain of backup artifacts into a single artifact.

For details, see xref:backup-restore/aggregate.adoc[].
|===

== The `neo4j` tool

The `neo4j` command-line tool is located in the xref:configuration/file-locations.adoc[_bin_] directory.

=== General synopsis

`neo4j` has the following general synopsis:

`neo4j [command]`

=== `neo4j` commands

The command is an alias for the most important commands in the `neo4j-admin server` category.

.Equivalence between `neo4j` and `neo4j-admin` commands
[options="header", cols="25,25a"]
|===
| `neo4j` command
| Equivalent `neo4j-admin` command

| `neo4j console`
| `neo4j-admin server console`

| `neo4j restart`
| `neo4j-admin server restart`

| `neo4j start`
| `neo4j-admin server start`

| `neo4j status`
| `neo4j-admin server status`

| `neo4j stop`
| `neo4j-admin server stop`

| `neo4j windows-service`
| `neo4j-admin server windows-service`

|===

[[version-command]]
== Version command

Version can be obtained by invoking the `version` command, `--version` command option, or its short alternative `-V`, on the root level of both  `neo4j` and `neo4j-admin` commands.
For example, `neo4j --version`, `neo4j-admin -V`, `neo4j-admin version`, or `neo4j version`.

[[help-command]]
== Help command

Help can be obtained by invoking the `help` command, `--help` command option, or its short alternative `-h`, with both `neo4j` and `neo4j-admin` commands.
`--help` and `-h` options can be invoked on any level, namely root, category, command, and subcommand.
For example, `neo4j --help`, `neo4j [command] -h`, `neo4j-admin -h`, `neo4j-admin [category] --help`, or `neo4j-admin [category] [command] [subcommand] -h`.

The help command can be invoked on any level except the last one, which means command-level for commands that do not have subcommands or subcommand level for commands with subcommands.
The help command also accepts a parameter.
For example, `neo4j help`, `neo4j-admin help`, `neo4j-admin [category] help`, `neo4j-admin help [category]`, `neo4j help [command]`, or `neo4j-admin [category] [command ] help [subcommand]`.

== Limitations

When using both a multi-value option and a positional parameter, the multi-value option is "greedy" and pulls in the next positional parameter via its convertor.
This is a limitation of the underlying library, Picocli, and is not specific to Neo4j Admin.
See link:https://picocli.info/#_variable_arity_options_and_positional_parameters[Picocli -> Variable Arity Options and Positional Parameters] official documentation for more information.

== Configuration

Administration operations use the configuration specified in the _neo4j.conf_ file.
Sharing configuration between the DBMS and its administration tasks makes sense as most settings are the same.
In some cases, however, it is better to override some settings specified in _neo4j.conf_ by configuring the tasks (instead of updating the config settings in the _neo4j.conf_ file) because administration tasks generally use fewer resources than the DBMS.
For instance, if the page cache of your DBMS is configured to a very high value in _neo4j.conf_, and you want to override this because the admin tasks like backup do not need so much memory, you provide configuration for the admin tasks instead of updating the page cache setting in the _neo4j.conf_ file.

There are several options for overriding settings specified in the _neo4j.conf_ file using administration tasks:

* `--additional-config` option -- almost all administration commands support the `--additional-config` option, which you can use to provide a path (full path, local path, or symlinks) to a file with additional configuration.
The file format should be the same as _neo4j.conf_ (or _neo4j-admin.conf_).
The file must be readable by the user running the admin command.
* _neo4j-admin.conf_ -- a configuration file located in the same directory as the `neo4j.conf` file, which you can use to provide administration-task-specific settings.
* Some commands also support a command-specific configuration file. Such files are also looked for in the same directory as the _neo4j.conf_ file.
The following table lists command-specific configuration files:
+
.Command-specific configuration files
[options="header", cols="25,25a"]
|===
| Command
| Configuration file

| `neo4j-admin database backup`
| `neo4j-admin-database-backup.conf`

| `neo4j-admin database check`
| `neo4j-admin-database-check.conf`

| `neo4j-admin database copy`
| `neo4j-admin-database-copy.conf`

| `neo4j-admin database dump`
| `neo4j-admin-database-dump.conf`

| `neo4j-admin database import`
| `neo4j-admin-database-import.conf`

| `neo4j-admin database load`
| `neo4j-admin-database-load.conf`

| `neo4j-admin database migrate`
| `neo4j-admin-database-migrate.conf`

| `neo4j-admin database restore`
| `neo4j-admin-database-restore.conf`

|===

All four configuration sources are optional and settings for administration commands are resolved from them with the following descending priority:

. `--additional-config` option
. command-specific configuration file
. `neo4j-admin.conf`
. `neo4j.conf`

[NOTE]
====
The commands for launching the DBMS, `neo4j start` and `neo4j console`, must be configured only in the _neo4j.conf_ file.
====

== Environment variables

Neo4j Admin can also use the following environment variables:

[options="header", cols="1m,3a"]
|===
| Environment variable
| Description

| NEO4J_DEBUG
| Set to anything to enable debug output.

| NEO4J_HOME
| Neo4j home directory.

| NEO4J_CONF
|Path to the directory that contains _neo4j.conf_.

| HEAP_SIZE
| Set JVM maximum heap size during command execution.
Takes a number and a unit, for example, 512m.

| JAVA_OPTS
| Additional JVM arguments.
|===

If set, `HEAP_SIZE` and `JAVA_OPTS` override all relevant settings specified in the configuration file.

[[neo4j-admin-exit-codes]]
== Exit codes

When `neo4j` and `neo4j-admin` finish as expected, they exit with code `0`.
A non-zero exit code means something undesired happened during command execution.

.Exit codes
[options="header", cols="1m,3a"]
|===
| Exit code
| Description

| `0`
| Successful execution.

| 1
| The command failed to execute.

| 3
| The command failed to execute because the database is not running.

| 64
| The command was invoked with incorrect options/parameters. See the printed usage for details.

| 70
| An exception was thrown, not handled otherwise.
|===

The non-zero exit code can contain further information about the error, for example, see the `backup` command's xref:backup-restore/online-backup.adoc#backup-command-exit-codes[exit codes].

== Command-line completion

From 5.4 onwards, Neo4j supports command-line completion.

* For Unix-based systems, the tab completion applies to the `neo4j` and `neo4j-admin` command line interfaces in terminals such as Bash and ZSH.
* For RPM and DEB packaged installations, the necessary files are automatically installed in `bash-completion`.
* For tarball installations, the files are located in the _bin/completion/_ directory with detailed instructions for manual installation.
