[role=enterprise-edition]
[[aggregate-backup]]
= Aggregate a database backup chain
:description: This section describes how to aggregate a backup chain into a single backup.

[[aggregate-backup-command]]
== Command

The aggregate command turns a xref:backup-restore/online-backup.adoc#backup-chain[a chain of backup artifacts] into a single xref:backup-restore/online-backup.adoc#backup-artifact[full backup artifact].

image:backup-chain-aggregation.svg[title="Backup chain aggregation",role="middle"]

The benefits of aggregating a backup chain are notably:

* Reduces the size of backup artifacts in a given backup folder.
* Keeps the recovery time objective (RTO) low by generating a single backup artifact ready to be restored.
As part of the aggregation, transactions contained in the differential backups are applied to the store contained in the full backup artifact.
This operation is called _recovery_ and can be costly.
* Reduces the risk of losing chain’s links.


[[aggregate-backup-syntax]]
=== Syntax

[source,role=noheader]
----
neo4j-admin database aggregate-backup [-h] [--expand-commands]
                                      [--verbose] [--keep-old-backup[=true|false]]
                                      [--parallel-recovery[=true|false]]
                                      [--additional-config=<file>]
                                      --from-path=<path> [<database>]
----

=== Description

Aggregates a chain of backup artifacts into a single artifact.

[[aggregate-backup-command-parameters]]
=== Parameters

.`neo4j-admin database aggregate-backup` parameters
[options="header", cols="1m,3a"]
|===
| Parameter
| Description

|[<database>]
|Name of the database for which to aggregate the artifacts. Can contain `*` and `?` for globbing.
|===


[[aggregate-backup-command-options]]
=== Options

.`neo4j-admin database aggregate-backup` options
[options="header", cols="5m,6a,4m"]
|===
| Option
| Description
| Default

|--additional-config=<file>
|Configuration file with additional configuration.
|

| --expand-commands
| Allow command expansion in config value evaluation.
|

|--from-path=<path>
|Accepts either a path to a single artifact file or a folder containing backup artifacts.

When a file is supplied, the _<database>_ parameter should be omitted.
The option to supply a file is only available from Neo4j 5.2 onwards.
|

|-h, --help
|Show this help message and exit.
|

|--keep-old-backup[=true\|false]
|If set to true, the old backup chain is not removed.
|false

|--parallel-recovery[=true\|false]
|Allow multiple threads to apply pulled transactions to a backup in parallel.
For some databases and workloads, this may reduce aggregate times significantly.
Note: this is an EXPERIMENTAL option.
Consult Neo4j support before use.
|false

|--verbose
|Enable verbose output.
|
|===

[NOTE]
====
As of Neo4j 5.19, the `--from-path=<path>` option can also load backup artifacts from AWS S3 URIs.
Neo4j uses link:https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html[default AWS credentials] to access AWS S3 URIs.
For an example of how to use this option, see <<aggregate-backup-aws-s3-example>>.
====


[[aggregate-backup-example]]
== Examples

=== Aggregating a backup chain located in a given folder

The following is an example of how to perform aggregation of a set of backups located in a given folder for the `neo4j` database:

[source,shell]
----
bin/neo4j-admin database aggregate-backup --from-path=/mnt/backups/ neo4j
----
The command first looks inside the `/mnt/backups/` directory for a backup chain for the database `neo4j`. If found, it is then aggregated into a single backup artifact.

=== Aggregating a backup chain identified using a given backup file

The following is an example of how to perform aggregation of a set of backups identified using a given backup file for the `neo4j` database:

[source,shell]
----
bin/neo4j-admin database aggregate-backup --from-path=/mnt/backups/neo4j-2022-10-18T13-00-07.backup
----
The command checks the `/mnt/backups/` directory for a backup chain including the file _neo4j-2022-10-18T13-00-07.backup_, for the database `neo4j`.
If found, it is then aggregated into a single backup artifact.
This option is only available in Neo4j 5.2 and later.

[[aggregate-backup-aws-s3-example]]
=== Aggregating a backup chain located in an AWS S3 storage

The following is an example of how to perform aggregation of a set of backups located in a given folder in an AWS S3 storage.

include::partial$/aws-s3-overrides.adoc[]

include::partial$/aws-s3-credentials.adoc[]

. Then, use the following command to aggregate the backup chain located in the given folder in the AWS S3 storage:
+
[source,shell]
----
bin/neo4j-admin database aggregate-backup --from-path=s3://mnt/backups/ neo4j
----
