[role=enterprise-edition]
[[aggregate-backup]]
= Aggregate a database backup chain
:description: This section describes how to aggregate a backup chain into a single backup and recover a full backup.

[[aggregate-backup-command]]
== Command

The aggregate command turns a xref:backup-restore/online-backup.adoc#backup-chain[a chain of backup artifacts] into a single xref:backup-restore/online-backup.adoc#backup-artifact[full backup artifact].

image:backup-chain-aggregation.svg[title="Backup chain aggregation",role="middle"]

The benefits of aggregating a backup chain are notably:

* Reduces the size of backup artifacts in a given backup folder.
* Keeps the recovery time objective (RTO) low by generating a single backup artifact ready to be restored.
As part of the aggregation, transactions contained in the differential backups are applied to the store contained in the full backup artifact.
This operation is called _recovery_ and can be costly.
* Reduces the risk of losing chain’s links.
* Some commands, like consistency check, cannot run against a backup chain or a full backup that is not recovered.
Aggregating produces an artifact they can work against.


[role=label--changed-2025.01]
[[aggregate-backup-syntax]]
=== Syntax

[source,role=noheader]
----
neo4j-admin backup aggregate [-h] [--expand-commands]
                                      [--verbose] [--keep-old-backup[=true|false]]
                                      [--parallel-recovery[=true|false]]
                                      [--additional-config=<file>] --from-path=<path>
                                      [--temp-path=<path>] [<database>]
----

[NOTE]
====
In Neo4j 2025.01, the name `neo4j-admin database aggregate-backup` is deprecated.
It is recommended to use the new command name, `neo4j-admin backup aggregate`.
====


=== Description

Aggregates a chain of backup artifacts into a single artifact.

[[aggregate-backup-command-parameters]]
=== Parameters

.`neo4j-admin backup aggregate` parameters
[options="header", cols="1m,3a"]
|===
| Parameter
| Description

|[<database>]
|Name of the database for which to aggregate the artifacts. Can contain * and ? for globbing.
|===


[[aggregate-backup-command-options]]
=== Options

.`neo4j-admin backup aggregate` options
[options="header", cols="5m,6a,4m"]
|===
| Option
| Description
| Default

|--additional-config=<file>footnote:[See xref:neo4j-admin-neo4j-cli.adoc#_configuration[Neo4j Admin and Neo4j CLI -> Configuration] for details.]
|Configuration file with additional configuration.
|

| --expand-commands
| Allow command expansion in config value evaluation.
|

|--from-path=<path>
|Accepts either a path to a single artifact file or a folder containing backup artifacts.

When a file is supplied, the _<database>_ parameter should be omitted.
It is possible to aggregate backup artifacts from AWS S3 buckets, Google Cloud storage buckets, and Azure buckets using the appropriate URI as the path.
|

|-h, --help
|Show this help message and exit.
|

|--keep-old-backup[=true\|false]
|If set to true, the old backup chain is not removed.
|false

|--parallel-recovery[=true\|false]
|Allow multiple threads to apply pulled transactions to a backup in parallel.
For some databases and workloads, this may reduce aggregate times significantly.
Note: this is an EXPERIMENTAL option.
Consult Neo4j support before use.
|false

|--temp-path=<path>
|Provide a path to a temporary empty directory for storing backup files until the command is completed. The files will be deleted once the command is finished.
|

|--verbose
|Enable verbose output.
|
|===



[NOTE]
====
The `--from-path=<path>` option can also load backup artifacts from AWS S3 buckets, Google Cloud storage buckets, and Azure buckets.
For more information, see <<aggregate-backup-cloud-storage>>.
====

[NOTE]
====
The `--temp-path` option addresses potential issues related to disk space when performing backup-related commands, especially when cloud storage is involved.

If `--temp-path` is not set, a temporary directory is created inside the directory specified by the `--from-path` option.

If you don't provide the `--from-path` option or if your provided path points to a cloud storage bucket, a temporary folder is created inside the current working directory for Neo4j.
This fallback option can cause issues because the local filesystem (or the partition where Neo4j is installed) may not have enough free disk to accommodate the intermediate computation.

Therefore, it is strongly recommended to provide a `--temp-path` option.
====


[[aggregate-backup-example]]
== Examples

=== Aggregating a backup chain located in a given folder

The following is an example of how to perform aggregation of a set of backups located in a given folder for the `neo4j` database:

[source,shell]
----
bin/neo4j-admin backup aggregate --from-path=/mnt/backups/ neo4j
----
The command first looks inside the `/mnt/backups/` directory for a backup chain for the database `neo4j`. If found, it is then aggregated into a single backup artifact.

=== Aggregating a backup chain identified using a given backup file

The following is an example of how to perform aggregation of a set of backups identified using a given backup file for the `neo4j` database:

[source,shell]
----
bin/neo4j-admin backup aggregate --from-path=/mnt/backups/neo4j-2022-10-18T13-00-07.backup
----
The command checks the `/mnt/backups/` directory for a backup chain including the file _neo4j-2022-10-18T13-00-07.backup_, for the database `neo4j`.
If found, it is then aggregated into a single backup artifact.

[[aggregate-backup-cloud-storage]]
=== Aggregating a backup chain located in a cloud storage

In Neo4j 2025.03, new cloud integration settings are introduced to provide better support for deployment and management in cloud ecosystems.
For details, refer to xref:configuration/configuration-settings.adoc#_cloud_storage_integration_settings[Configuration settings -> Cloud storage integration settings].

The following examples show how to perform aggregation of a set of backups located in a cloud storage.

[.tabbed-example]
=====
[role=include-with-AWS-S3]
======

include::partial$/aws-s3-overrides.adoc[]

include::partial$/aws-s3-credentials.adoc[]

. Then, use the following command to aggregate the backup chain located in a given folder in your AWS S3 bucket.
The example assumes that you have a backup chain located in the `myBucket/myDirectory` folder  identifiable by the file `myBackup.backup`:
+
[source,shell]
----
bin/neo4j-admin backup aggregate --from-path=s3://myBucket/myDirectory/myBackup.backup mydatabase
----
======

[role=include-with-Google-cloud-storage]
======

include::partial$/gcs-credentials.adoc[]

. Then, use the following command to aggregate the backup chain located in a given folder in your Google storage bucket.
The example assumes that you have a backup chain located in the `myBucket/myDirectory` folder  identifiable by the file `myBackup.backup`:
+
[source,shell]
----
bin/neo4j-admin backup aggregate --from-path=gs://myBucket/myDirectory/myBackup.backup mydatabase
----
======

[role=include-with-Azure-cloud-storage]
======

include::partial$/azb-credentials.adoc[]

. Then, use the following command to aggregate the backup chain located in a given folder in your Azure blob storage container.
The example assumes that you have a backup chain located with a `myStorageAccount/myContainer/myDirectory` folder identifiable by the file `myBackup.backup`:
+
[source,shell]
----
bin/neo4j-admin backup aggregate --from-path=azb://myStorageAccount/myContainer/myDirectory/myBackup.backup mydatabase
----
======
=====


[[aggregate-unrecovered-full-backup]]
=== Aggregating an unrecovered full backup

To check if a full backup is in a recovered state, run the `neo4j-admin backup inspect` command:

[source,shell]
----
bin/neo4j-admin backup inspect /mnt/backups/neo4j-2025-09-10T08-14-56.backup
----

The output will include the `RECOVERED` column.
If it shows `false`, the backup is not yet recovered:

[output]
----
|                                                 FILE | DATABASE |                          DATABASE ID |          TIME (UTC) | FULL | COMPRESSED | LOWEST TX | HIGHEST TX | STORE ID HASH | RECOVERED |
| file:///mnt/backups/neo4j-2025-09-10T08-14-56.backup |    neo4j | 4e98fab8-6ae6-46cc-84c0-61ee8a8db60a | 2025-09-10T08:14:56 | true |       true |         1 |          3 |    -116350002 |     false |
----

If your full backup is not recovered, you have to aggregate it first.
Run the following command:

[source,shell]
----
bin/neo4j-admin backup aggregate --from-path=/mnt/backups/neo4j-2025-09-10T08-14-56.backup --keep-old-backup=true
----

This command will:

* Generate a new, recovered backup alongside the existing one.
* Preserve the original backup file (due to `--keep-old-backup=true`).

After aggregation, you can run consistency checker against the recovered backup and/or restore it.


