[role=enterprise-edition]
[[aggregate-backup]]
= Aggregate a database backup chain
:description: This section describes how to aggregate a backup chain into a single backup. 

[[aggregate-backup-command]]
== Command

The aggregate command turns a xref:backup-restore/online-backup.adoc#backup-chain[backup chain] into a single xref:backup-restore/online-backup.adoc#backup-artifact[full backup artifact].

image:backup-chain-aggregation.svg[title="Backup chain aggregation",role="middle"]

The benefits of aggregating a backup chain are notably:

* Reduces the size of backup artifacts in a given backup folder.
* Keeps the recovery time objective (RTO) low by generating a single backup artifact ready to be restored.
As part of the aggregation, transactions contained in the differential backups are applied to the store contained in the full backup artifact.
This operation is called _recovery_ and can be costly.
* Reduces the risk of losing chain’s links.


[[aggregate-backup-syntax]]
=== Syntax

[source,role=noheader]
----
neo4j-admin database aggregate-backup   --from-path=<path>
                                        [--keep-old-backup[=true|false]]
                                        [--parallel-recovery[=true|false]]
                                        [--verbose]
                                        [--expand-commands]
                                        [--additional-config=<file>]
                                        <database>
----

[[aggregate-backup-command-options]]
=== Options

[options="header",cols="m,m,a"]
|===
| Option
| Default
| Description

| --from-path
|
| Directory where the backup artifacts are located.

| --keep-old-backup
| false
| If set to true, the old backup chain is not removed.

| --parallel-recovery
| false
| Allow multiple threads to apply pulled transactions to a backup in parallel.
For some databases and workloads this may reduce aggregate times significantly.
[NOTE]
====
`parallel-recovery` is an experimental option.
Consult Neo4j support before use.
====
| --verbose
|
| Enable verbose output.

| --expand-commands
|
| Allow command expansion in config value evaluation.

| --additional-config
|
| Configuration file to provide additional or override the existing configuration settings in the _neo4j.conf_ file.
|===

[[aggregate-backup-command-parameters]]
=== Parameters

[options="header",cols="m,m,a"]
|===
| Parameter
| Default
| Description

| <database>
| neo4j
| Name of the database for which to aggregate the artifacts.
Can contain `*` and `?` for globbing.

|===

[[aggregate-backup-example]]
== Example

.An example of how to perform aggregation of a set of backups located in a given folder for the `neo4j` database.
[source,shell]
----
bin/neo4j-admin database aggregate-backup --from-path=/mnt/backups/ neo4j
----
The command first looks inside the `/mnt/backups/` directory for a backup chain for the database `neo4j`. If found, it is then aggregated into a single backup artifact.