[role=enterprise-edition]
[[aggregate-backup]]
= Aggregate a database backup chain
:description: This section describes how to aggregate a backup chain into a single backup.

[[aggregate-backup-command]]
== Command

The aggregate command turns a xref:backup-restore/online-backup.adoc#backup-chain[a chain of backup artifacts] into a single xref:backup-restore/online-backup.adoc#backup-artifact[full backup artifact].

image:backup-chain-aggregation.svg[title="Backup chain aggregation",role="middle"]

The benefits of aggregating a backup chain are notably:

* Reduces the size of backup artifacts in a given backup folder.
* Keeps the recovery time objective (RTO) low by generating a single backup artifact ready to be restored.
As part of the aggregation, transactions contained in the differential backups are applied to the store contained in the full backup artifact.
This operation is called _recovery_ and can be costly.
* Reduces the risk of losing chain’s links.


[[aggregate-backup-syntax]]
=== Syntax

[source,role=noheader]
----
neo4j-admin database aggregate-backup [-h] [--expand-commands]
                                      [--verbose] [--keep-old-backup[=true|false]]
                                      [--parallel-recovery[=true|false]]
                                      [--additional-config=<file>] --from-path=<path>
                                      [--temp-path=<temp-path>] [<database>]
----

=== Description

Aggregates a chain of backup artifacts into a single artifact.

[[aggregate-backup-command-parameters]]
=== Parameters

.`neo4j-admin database aggregate-backup` parameters
[options="header", cols="1m,3a"]
|===
| Parameter
| Description

|[<database>]
|Name of the database for which to aggregate the artifacts. Can contain `*` and `?` for globbing.
|===


[[aggregate-backup-command-options]]
=== Options

.`neo4j-admin database aggregate-backup` options
[options="header", cols="5m,6a,4m"]
|===
| Option
| Description
| Default

|--additional-config=<file>
|Configuration file with additional configuration.
|

| --expand-commands
| Allow command expansion in config value evaluation.
|

|--from-path=<path>
|Accepts either a path to a single artifact file or a folder containing backup artifacts.

When a file is supplied, the _<database>_ parameter should be omitted.
The option to supply a file is only available from Neo4j 5.2 onwards.
|

|-h, --help
|Show this help message and exit.
|

|--keep-old-backup[=true\|false]
|If set to true, the old backup chain is not removed.
|false

|--parallel-recovery[=true\|false]
|Allow multiple threads to apply pulled transactions to a backup in parallel.
For some databases and workloads, this may reduce aggregate times significantly.
Note: this is an EXPERIMENTAL option.
Consult Neo4j support before use.
|false

|--temp-path=<path>
|Use the provided folder as a temporary folder. Please, provide an existing and empty folder because its content will be deleted once the command has completed.
|

|--verbose
|Enable verbose output.
|
|===

[NOTE]
====
The `--from-path=<path>` option can also load backup artifacts from AWS S3 buckets (from Neo4j 5.19) and Google Cloud storage buckets (from Neo4j 5.21).
For more information, see <<aggregate-backup-cloud-storage>>.
====


[[aggregate-backup-example]]
== Examples

=== Aggregating a backup chain located in a given folder

The following is an example of how to perform aggregation of a set of backups located in a given folder for the `neo4j` database:

[source,shell]
----
bin/neo4j-admin database aggregate-backup --from-path=/mnt/backups/ neo4j
----
The command first looks inside the `/mnt/backups/` directory for a backup chain for the database `neo4j`. If found, it is then aggregated into a single backup artifact.

=== Aggregating a backup chain identified using a given backup file

The following is an example of how to perform aggregation of a set of backups identified using a given backup file for the `neo4j` database:

[source,shell]
----
bin/neo4j-admin database aggregate-backup --from-path=/mnt/backups/neo4j-2022-10-18T13-00-07.backup
----
The command checks the `/mnt/backups/` directory for a backup chain including the file _neo4j-2022-10-18T13-00-07.backup_, for the database `neo4j`.
If found, it is then aggregated into a single backup artifact.
This option is only available in Neo4j 5.2 and later.

[[aggregate-backup-cloud-storage]]
=== Aggregating a backup chain located in a cloud storage

The following examples show how to perform aggregation of a set of backups located in a cloud storage.

[.tabbed-example]
=====
[.include-with-AWS-S3]
======

include::partial$/aws-s3-overrides.adoc[]

include::partial$/aws-s3-credentials.adoc[]

. Then, use the following command to aggregate the backup chain located in a given folder in your AWS S3 bucket.
The example assumes that you have a backup chain located in the `myBucket/myDirectory` folder  identifiable by the file `myBackup.backup`:
+
[source,shell]
----
bin/neo4j-admin database aggregate-backup --from-path=s3://myBucket/myDirectory/myBackup.backup mydatabase
----
======

[.include-with-Google-cloud-storage]
======

include::partial$/gcs-credentials.adoc[]

. Then, use the following command to aggregate the backup chain located in a given folder in your Google storage bucket.
The example assumes that you have a backup chain located in the `myBucket/myDirectory` folder  identifiable by the file `myBackup.backup`:
+
[source,shell]
----
bin/neo4j-admin database aggregate-backup --from-path=gs://myBucket/myDirectory/myBackup.backup mydatabase
----
======
=====