[role=enterprise-edition]
[[inspect-backup]]
= Inspect the metadata of a database backup file.
:description: This section describes how to inspect the metadata of backup files. Metadata are information like the database name, the backup compression, the transaction range that the backup contains etc..

[[inspect-backup-command]]
== Command

The inspect command lists the metadata stored in the header of backup files. Those metadata are notably used to define how backups are connected to constitute xref:backup-restore/online-backup.adoc#backup-chain[backup chains]. A backup chain is a sequence of one or more backup(s) logically connected. The order of the sequence guarantees that when replayed (see xref:backup-restore/restore-backup.adoc[restore] or xref:backup-restore/aggregate.adoc[aggregate]), the store and the transaction data are consumed in a consistent fashion.


The metadata are

* *Database*: database name of the database fragment that the backup contains.
* *Database id*: a unique identifier used to distinguish databases (even with same name)
* *Time*: time the backup was taken
* *Full*: indicates whether the backup is a full backup (i.e. initial backup containing the store files) or a differential backup (i.e. subsequent backup containing only transactions to be applied to the store files)
* *Compressed*: indicates whether the backup data inside the backup file are compressed or not
* *Lowest transaction id*: when the backup is full, this value is always 1 and when it is a differential backup the value corresponds to the first transaction id the backup starts with
* *Highest transaction id*: similarly, this value indicates the last transaction id stored in the backup file.








[[inspect-backup-syntax]]
=== Syntax

[source,role=noheader]
----
neo4j-admin backup inspect [-h] [--empty] [--expand-commands] [--latest-backup] [--latest-chain] [--show-metadata]
                           [--verbose] [--additional-config=<file>] [--database=<database>] [--format=<value>]
                           <backup-path>
----

=== Description

Command to read the backup metadata.

[[inspect-backup-command-parameters]]
=== Parameters

.`neo4j-admin backup inspect` parameters
[options="header", cols="1m,3a"]
|===
| Parameter
| Description

|[<backup-path>]
|Path denoting either a directory where backups are stored or a single backup to inspect.
|===

[NOTE]
====
The `<backup-path>` parameter can also inspect backup from AWS S3 buckets (from Neo4j 5.19), Google Cloud storage buckets (from Neo4j 5.21), and Azure buckets (from Neo4j 5.24).


====
[[inspect-backup-command-options]]
=== Options

.`neo4j-admin backup inspect` options
[options="header", cols="5m,6a,4m"]
|===
| Option
| Description
| Default

|--additional-config=<file>
|Configuration file with additional configuration.
|

| --expand-commands
| Allow command expansion in config value evaluation.
|

|-h, --help
|Show this help message and exit.
|

| --latest-backup
| Show only the latest backup.
| false

| --latest-chain
| List the full backup chain ending with the latest downloaded backup.
| false

| --show-metadata
| Show the backup metadata.
| false

| --database
| Name of the database to inspect.
|

| --format
| Format of the output of the command. Possible values are: 'JSON, TABULAR'.
| TABULAR

| --empty
| Includes empty backups.
| false

|--verbose
|Enable verbose output.
|
|===


[[aggregate-backup-example]]
== Examples

Given a folder `/backups` containing a set of database backups:

[source,shell]
----
/backups
├── london-2024-10-07T16-03-51.backup
├── london-2024-10-07T16-04-05.backup
├── malmo-2024-10-07T16-00-07.backup
├── malmo-2024-10-07T16-00-19.backup
├── malmo-2024-10-07T16-00-34.backup
├── malmo-2024-10-07T16-00-44.backup
├── malmo-2024-10-07T16-00-50.backup
├── malmo-2024-10-07T16-01-08.backup
├── malmo-2024-10-07T16-01-24.backup
└── neo4j-2024-10-07T16-05-37.backup
----

=== Listing the metadata of the backup files.

The following command list the backup files name along with their respective metadata.

[source,shell]
----
./bin/neo4j-admin backup inspect /backups --show-metadata --empty

|                                              FILE | DATABASE |                          DATABASE ID |          TIME (UTC) |  FULL | COMPRESSED | LOWEST TX | HIGHEST TX |
|  file:///backups/neo4j-2024-10-07T16-05-37.backup |    neo4j | 7dcb1d0c-4374-4476-b8ae-d3c3f124683f | 2024-10-07T16:05:37 |  true |       true |         1 |          3 |
|  file:///backups/malmo-2024-10-07T16-01-24.backup |    malmo | 62d1820c-3ac6-4b15-a0b3-bf7e7becc8d0 | 2024-10-07T16:01:24 |  true |       true |         1 |          8 |
|  file:///backups/malmo-2024-10-07T16-01-08.backup |    malmo | 62d1820c-3ac6-4b15-a0b3-bf7e7becc8d0 | 2024-10-07T16:01:08 |  true |       true |         1 |          7 |
|  file:///backups/malmo-2024-10-07T16-00-50.backup |    malmo | 62d1820c-3ac6-4b15-a0b3-bf7e7becc8d0 | 2024-10-07T16:00:50 | false |       true |         0 |          0 |
|  file:///backups/malmo-2024-10-07T16-00-44.backup |    malmo | 62d1820c-3ac6-4b15-a0b3-bf7e7becc8d0 | 2024-10-07T16:00:44 | false |       true |         7 |          7 |
|  file:///backups/malmo-2024-10-07T16-00-34.backup |    malmo | 62d1820c-3ac6-4b15-a0b3-bf7e7becc8d0 | 2024-10-07T16:00:34 | false |       true |         6 |          6 |
|  file:///backups/malmo-2024-10-07T16-00-19.backup |    malmo | 62d1820c-3ac6-4b15-a0b3-bf7e7becc8d0 | 2024-10-07T16:00:19 | false |       true |         0 |          0 |
|  file:///backups/malmo-2024-10-07T16-00-07.backup |    malmo | 62d1820c-3ac6-4b15-a0b3-bf7e7becc8d0 | 2024-10-07T16:00:07 |  true |       true |         1 |          5 |
| file:///backups/london-2024-10-07T16-04-05.backup |   london | d4dae73c-dfef-4d28-88cd-fe6cc88ddca1 | 2024-10-07T16:04:05 | false |       true |         6 |          6 |
| file:///backups/london-2024-10-07T16-03-51.backup |   london | d4dae73c-dfef-4d28-88cd-fe6cc88ddca1 | 2024-10-07T16:03:51 |  true |       true |         1 |          5 |
----

[NOTE]
====
In the example above the `--empty` option is used to include the empty backups. An empty backup is created when a database is backed up but there is no new data. Empty backups are simply used to record the backup history.
====

=== Listing the latest backups

Using the `--latest-backup` option, only lists for each databse the last backups that have been performed.

[source,shell]
----
./bin/neo4j-admin backup inspect /backups --show-metadata --latest-backup

|                                              FILE | DATABASE |                          DATABASE ID |          TIME (UTC) |  FULL | COMPRESSED | LOWEST TX | HIGHEST TX |
|  file:///backups/neo4j-2024-10-07T16-05-37.backup |    neo4j | 7dcb1d0c-4374-4476-b8ae-d3c3f124683f | 2024-10-07T16:05:37 |  true |       true |         1 |          3 |
|  file:///backups/malmo-2024-10-07T16-01-24.backup |    malmo | 62d1820c-3ac6-4b15-a0b3-bf7e7becc8d0 | 2024-10-07T16:01:24 |  true |       true |         1 |          8 |
| file:///backups/london-2024-10-07T16-04-05.backup |   london | d4dae73c-dfef-4d28-88cd-fe6cc88ddca1 | 2024-10-07T16:04:05 | false |       true |         6 |          6 |
----

=== Inspecting backup chains

As described before, a backup chain corresponds to a sequence of one or more backup(s) logically connected by their transaction ids. The option `--latest-chain` can be used to inspect the chains of a given database.

[source,shell]
----
./bin/neo4j-admin backup inspect /backups --show-metadata --latest-chain --database=london

|                                              FILE | DATABASE |                          DATABASE ID |          TIME (UTC) |  FULL | COMPRESSED | LOWEST TX | HIGHEST TX |
| file:///backups/london-2024-10-07T16-04-05.backup |   london | d4dae73c-dfef-4d28-88cd-fe6cc88ddca1 | 2024-10-07T16:04:05 | false |       true |         6 |          6 |
| file:///backups/london-2024-10-07T16-03-51.backup |   london | d4dae73c-dfef-4d28-88cd-fe6cc88ddca1 | 2024-10-07T16:03:51 |  true |       true |         1 |          5 |
----

In the example above, the option `--database` is required because the command needs to know for which database it should find the backup chain. The result returned is a chain of size two where,

* the first backup is a full backup containing the store files within the transaction range [1,5] and,
* the second backup is a differential backup containing only the subsequent modifications to the store files. Those modifications are materialised by a sequence of transactions to apply. Its range is [6,6].


=== Inspecting a backup chain ending with a given backup

Sometimes a user might be interested in a backup chain ending with a specific backup. This can be find as follow:

[source,shell]
----
./bin/neo4j-admin backup inspect /backups/london-2024-10-07T16-04-05.backup  --show-metadata --latest-chain

|                                              FILE | DATABASE |                          DATABASE ID |          TIME (UTC) |  FULL | COMPRESSED | LOWEST TX | HIGHEST TX |
| file:///backups/london-2024-10-07T16-04-05.backup |   london | d4dae73c-dfef-4d28-88cd-fe6cc88ddca1 | 2024-10-07T16:04:05 | false |       true |         6 |          6 |
| file:///backups/london-2024-10-07T16-03-51.backup |   london | d4dae73c-dfef-4d28-88cd-fe6cc88ddca1 | 2024-10-07T16:03:51 |  true |       true |         1 |          5 |
----

[NOTE]
====
In this specific case, the `--database` option is not needed because the database identifier is part of the metadata stored in the header of the backup file `london-2024-10-07T16-04-05.backup`.
====












