:description: This section describes how to back up an offline database.
[[offline-backup]]
= Back up an offline database

[CAUTION]
====
Remember to xref:backup-restore/planning.adoc[plan your backup] carefully and to back up each of your databases, including the `system` database.
====


[[offline-backup-command]]
== Command

A Neo4j database can be backed up in offline mode using the `dump` command of `neo4j-admin`.
If the database is hosted in a cluster, make sure that the database is stopped on the server you are connected to.


[[offline-backup-command-usage]]
=== Usage

The `neo4j-admin database dump` command can be used for performing a full backup of an **offline** database.
It dumps a database into a single-file archive, called _<database>.dump_.
Alternatively, `neo4j-admin database dump` can stream dump to standard output, enabling the output to be piped to another program, for example to `neo4j-admin database load`.

The command can be run only locally from an online or an offline Neo4j DBMS.

It does not support SSL/TLS.


[[offline-command-syntax]]
=== Syntax

[source,role=noheader]
----
neo4j-admin database dump   [--verbose]
                            [--expand-commands]
                            [--overwrite-destination[=true|false]]
                            [--to-path=<path> | --to-stdout]
                            <database>
----

<database> --  Name of the database to dump.
Can contain `*` and `?` for globbing.

[[offline-backup-command-options]]
=== Options

[options="header",cols="m,m,a"]
|===
| Option
| Default
| Description

| --verbose
|
| Enable verbose output.

| --expand-commands
|
| Allow command expansion in config value evaluation.

| --overwrite-destination
| false
| Overwrite any existing dump file in the destination folder.

| --to-path
|
| Destination for the database dump.
It must point to an existing directory.

| --to-stdout
|
| Use standard output as the destination for the database dump.
|===


[[offline-backup-example]]
== Example

The following is an example of how to create a dump of the default database `neo4j` using the `neo4j-admin database dump` command.
The target directory _/dumps/neo4j_ must exist before running the command and the database must be offline.

[source,shell]
----
bin/neo4j-admin database dump neo4j --to-path=/dumps/neo4j
----

[NOTE]
====
`neo4j-admin database dump` cannot be applied to xref:composite-databases/index.adoc[composite databases].
It must be run directly on the databases that are part of a composite database.
====
