:description: This section describes how to back up an offline database.
[[offline-backup]]
= Back up an offline database

[CAUTION]
====
Remember to xref:backup-restore/planning.adoc[plan your backup] carefully and back up each of your databases, including the `system` database.
====


[[offline-backup-command]]
== Command

The `neo4j-admin database dump` command can be used for performing a full backup of an **offline** database.
It dumps only the database contents into a single-file archive, called _<database>.dump_, and stores it in the xref:configuration/file-locations.adoc#data[_<NEO4J_HOME>/data_] directory.

Check the target directory permissions before running the `neo4j-admin database dump` command.
The target directory must never be world-readable or world-executable.
Even if files inside are restricted, a world-executable directory can leak structure.
For more information, see xref:configuration/file-locations.adoc#_security_considerations[File permissions].

Note that the `neo4j-admin database dump` command **does not** support backing up users and roles metadata.

Alternatively, `neo4j-admin database dump` can stream dump to standard output, enabling the output to be piped to another program, for example to `neo4j-admin database load`.

If the database is hosted in a cluster, make sure that the database is stopped on the server you are connected to.
The command can be run only locally from an online or an offline Neo4j DBMS on Enterprise Edition.
On Community Edition, the command can be run only on an offline Neo4j DBMS.
It does not support SSL/TLS.


[[offline-command-syntax]]
=== Syntax

[source,role=noheader]
----
neo4j-admin database dump [-h] [--expand-commands]
                          [--verbose] [--overwrite-destination[=true|false]]
                          [--additional-config=<file>]
                          [--split-archive-part-size=<splitsize>] [--to-path=<path> | --to-stdout]
                          <database>
----

=== Description

Dump a database into a single-file archive.
The archive can be used by the load command.
`<to-path>` should be a directory (in which case a file called _<database>.dump_ will be created), or `--to-stdout` can be supplied to use standard output.
If neither `--to-path` or `--to-stdout` is supplied `server.directories.dumps.root` setting will be used as a destination.
It is not possible to dump a database that is mounted in a running Neo4j server.

=== Parameters

.`neo4j-admin database dump` parameters
[options="header", cols="1m,3a"]
|===
| Parameter
| Description

|<database>
|Name of the database to dump. Can contain * and ? for globbing.
 Note that * and ? have special meaning in some shells and might need to be escaped or used with quotes.
|===

[[offline-backup-command-options]]
=== Options

The `neo4j-admin database dump` command has the following options:

.`neo4j-admin database dump` options
[options="header", cols="5m,6a,4m"]
|===
| Option
| Description
| Default

|--additional-config=<file>footnote:[See xref:neo4j-admin-neo4j-cli.adoc#_configuration[Neo4j Admin and Neo4j CLI -> Configuration] for details.]
|Configuration file with additional configuration.
|

|--expand-commands
|Allow command expansion in config value evaluation.
|

| -h, --help
|Show this help message and exit.
|

| --overwrite-destination[=true\|false]
|Overwrite any existing dump file in the destination folder.
|false

|--split-archive-part-size=<splitsize>
|label:new[Introduced in 2026.09] Splits the resulting dump artifact into multiple files of the specified size. The size can be specified in bytes or with a unit suffix (e.g. `5G`, `100g`, `1TiB`). The minimum split size is `1GiB`. If not specified the default value of `0` means the dump is not split and is written as a single file.
|0

|--to-path=<path>
|Destination folder of a database dump.
It is possible to dump databases into AWS S3 buckets, Google Cloud storage buckets, and Azure buckets using the appropriate URI as the path.
|

|--to-stdout
|Use standard output as the destination for the database dump.
|

|--verbose
|Enable verbose output.
|
|===

[NOTE]
====
The `--to-path=<path>` option can also dump databases into AWS S3 buckets, Google Cloud storage buckets, and Azure buckets.
For more information, see <<offline-backup-cloud-storage>>.
====

[[offline-backup-example]]
== Examples

The following examples show how to dump a database using the `neo4j-admin database dump` command.
The command creates a file called _database.dump_ where `database` is the database specified in the command.

[NOTE]
====
`neo4j-admin database dump` cannot be applied to xref:scalability/composite-databases/concepts.adoc[Composite databases].
It must be run directly on the databases that are associated with that Composite database.
====

=== Dump the default database `neo4j` to a local directory

You can use the following command to create a dump of the default database `neo4j` in a local directory.
The target directory must exist before running the command and the database must be offline.

[source, shell, role="nocopy"]
----
bin/neo4j-admin database dump neo4j --to-path=/full/path/to/dumps
----

[role=enterprise-edition]
[[offline-backup-cloud-storage]]
=== Dump a database to a folder located in a cloud storage

In Neo4j 2025.03, new cloud integration settings are introduced to provide better support for deployment and management in cloud ecosystems.
For details, refer to xref:configuration/configuration-settings.adoc#cloud-storage-integration-settings[Configuration settings -> Cloud storage integration settings].

The following examples show how to dump a database to a cloud storage bucket using the `--to-path` option.

[.tabbed-example]
=====
[role=include-with-AWS-S3]
======

include::partial$/aws-s3-overrides.adoc[]

include::partial$/aws-s3-credentials.adoc[]

. Run `neo4j-admin database dump` command to dump your database into your AWS S3 bucket:
+
[source, shell, role="nocopy"]
----
bin/neo4j-admin database dump mydatabase --to-path=s3://myBucket/myDirectory/
----
======

[role=include-with-Google-cloud-storage]
======

include::partial$/gcs-credentials.adoc[]

. Run `neo4j-admin database dump` command to dump your database into your Google bucket:
+
[source,shell]
----
bin/neo4j-admin database dump mydatabase --to-path=gs://myBucket/myDirectory/
----
======

[role=include-with-Azure-cloud-storage]
======

include::partial$/azb-credentials.adoc[]

. Run `neo4j-admin database dump` command to dump your database into your Azure container:
+
[source,shell]
----
bin/neo4j-admin database dump mydatabase --to-path=azb://myStorageAccount/myContainer/myDirectory/
----
======
=====


[role=label--new-2026.09 enterprise-edition]
[[split-dump-archive]]
=== Split a dump archive into multiple files

Starting with Neo4j 2026.09, you can split the dump archive created by `neo4j-admin database dump` into multiple files using the `--split-archive-part-size` option.

Run the following command to split the backup into parts of up to 5 GB:

[source, shell]
----
neo4j-admin database dump \
    --to-path=/path/to/dump \
    --split-archive-part-size=5G mydatabase
----

The `--split-archive-part-size` option defines the maximum size of each split part.
The size can be specified in bytes or with a unit suffix, such as `5G`, `100g`, or `1TiB`.

The minimum split size is `1GiB`.
If the option is not specified, or is set to `0`, the dump is written as a single file.

When splitting is enabled, the dump is written as a set of files in the same directory:

* _file.dump_
* _file.dump.1_
* _file.dump.2_
* ...

The first file (_.dump_) is a metadata file that contains information about the split archive, such as its ID and the number of files.
The remaining files contain the dump data.

You must keep all files belonging to a split archive in the same location.
If you move some of the files, all files for that dump artifact must be moved together.

When loading a split archive, specify the first file (_.dump_) as the dump artifact, in the same way as for an unsplit dump.

You can also configure a default split size using the xref:configuration/configuration-settings.adoc#config_server.split_archive.part_size[`server.split_archive.part_size` setting].
This is useful when you regularly run `neo4j-admin` commands and want to use the same split size without specifying `--split-archive-part-size` for every command.

For example:

[source,properties]
----
server.split_archive.part_size=5GiB
----

When `server.split_archive.part_size` is configured, `neo4j-admin database dump` uses that value by default.

If both `server.split_archive.part_size` and `--split-archive-part-size` are specified, the command-line option overrides the setting's value.

Both the `server.split_archive.part_size` setting and the `--split-archive-part-size` option default to `0`, which disables splitting.

For both the configuration setting and the command-line option, a non-zero value must be at least 1GiB.
Values smaller than 1GiB cause the command to fail.


ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]

endif::[]
