:description: This section describes how to back up an offline database.
[[offline-backup]]
= Back up an offline database

[CAUTION]
====
Remember to xref:backup-restore/planning.adoc[plan your backup] carefully and back up each of your databases, including the `system` database.
====


[[offline-backup-command]]
== Command

The `neo4j-admin database dump` command can be used for performing a full backup of an **offline** database.
It dumps only the database content into a single-file archive, called _<database>.dump_, and stores it in the xref:configuration/file-locations.adoc#data[_<NEO4J_HOME>/data_] directory.
Note that the `neo4j-admin database dump` command **does not** support backing up users and roles metadata.

Alternatively, `neo4j-admin database dump` can stream dump to standard output, enabling the output to be piped to another program, for example to `neo4j-admin database load`.

If the database is hosted in a cluster, make sure that the database is stopped on the server you are connected to.
The command can be run only locally from an online or an offline Neo4j DBMS on Enterprise Edition.
On Community Edition, the command can be run only on an offline Neo4j DBMS.
It does not support SSL/TLS.


[[offline-command-syntax]]
=== Syntax

[source,role=noheader]
----
neo4j-admin database dump [-h] [--expand-commands]
                          [--verbose] [--overwrite-destination[=true|false]]
                          [--additional-config=<file>]
                          [--to-path=<path> | --to-stdout]
                          <database>
----

=== Description

Dump a database into a single-file archive.
The archive can be used by the load command.
`<to-path>` should be a directory (in which case a file called _<database>.dump_ will be created), or `--to-stdout` can be supplied to use standard output.
If neither `--to-path` or `--to-stdout` is supplied `server.directories.dumps.root` setting will be used as a destination.
It is not possible to dump a database that is mounted in a running Neo4j server.

=== Parameters

.`neo4j-admin database dump` parameters
[options="header", cols="1m,3a"]
|===
| Parameter
| Description

|<database>
|Name of the database to dump. Can contain * and ? for globbing.
 Note that * and ? have special meaning in some shells and might need to be escaped or used with quotes.
|===

[[offline-backup-command-options]]
=== Options

The `neo4j-admin database dump` command has the following options:

.`neo4j-admin database dump` options
[options="header", cols="5m,6a,4m"]
|===
| Option
| Description
| Default

|--additional-config=<file>footnote:[See xref:neo4j-admin-neo4j-cli.adoc#_configuration[Neo4j Admin and Neo4j CLI -> Configuration] for details.]
|Configuration file with additional configuration.
|

|--expand-commands
|Allow command expansion in config value evaluation.
|

| -h, --help
|Show this help message and exit.
|

| --overwrite-destination[=true\|false]
|Overwrite any existing dump file in the destination folder.
|false

|--to-path=<path>
|Destination folder of a database dump.
It is possible to dump databases into AWS S3 buckets, Google Cloud storage buckets, and Azure buckets using the appropriate URI as the path.
|

|--to-stdout
|Use standard output as the destination for the database dump.
|

|--verbose
|Enable verbose output.
|
|===

[NOTE]
====
The `--to-path=<path>` option can also dump databases into AWS S3 buckets, Google Cloud storage buckets, and Azure buckets.
For more information, see <<offline-backup-cloud-storage>>.
====

[[offline-backup-example]]
== Examples

The following examples show how to dump a database using the `neo4j-admin database dump` command.
The command creates a file called _database.dump_ where `database` is the database specified in the command.

[NOTE]
====
`neo4j-admin database dump` cannot be applied to xref:scalability/composite-databases/concepts.adoc[Composite databases].
It must be run directly on the databases that are associated with that Composite database.
====

=== Dump the default database `neo4j` to a local directory

You can use the following command to create a dump of the default database `neo4j` in a local directory.
The target directory must exist before running the command and the database must be offline.

[source, shell, role="nocopy"]
----
bin/neo4j-admin database dump neo4j --to-path=/full/path/to/dumps
----

[role=enterprise-edition]
[[offline-backup-cloud-storage]]
=== Dump a database to a folder located in a cloud storage

In Neo4j 2025.03, new cloud integration settings are introduced to provide better support for deployment and management in cloud ecosystems.
For details, refer to xref:configuration/configuration-settings.adoc#_cloud_storage_integration_settings[Configuration settings -> Cloud storage integration settings].

The following examples show how to dump a database to a cloud storage bucket using the `--to-path` option.

[.tabbed-example]
=====
[role=include-with-AWS-S3]
======

include::partial$/aws-s3-overrides.adoc[]

include::partial$/aws-s3-credentials.adoc[]

. Run `neo4j-admin database dump` command to dump your database into your AWS S3 bucket:
+
[source, shell, role="nocopy"]
----
bin/neo4j-admin database dump mydatabase --to-path=s3://myBucket/myDirectory/
----
======

[role=include-with-Google-cloud-storage]
======

include::partial$/gcs-credentials.adoc[]

. Run `neo4j-admin database dump` command to dump your database into your Google bucket:
+
[source,shell]
----
bin/neo4j-admin database dump mydatabase --to-path=gs://myBucket/myDirectory/
----
======

[role=include-with-Azure-cloud-storage]
======

include::partial$/azb-credentials.adoc[]

. Run `neo4j-admin database dump` command to dump your database into your Azure container:
+
[source,shell]
----
bin/neo4j-admin database dump mydatabase --to-path=azb://myStorageAccount/myContainer/myDirectory/
----
======
=====
