[[offline-backup]]
= Back up an offline database
:description: This section describes how to back up an offline database. 

[CAUTION]
====
Remember to xref:backup-restore/planning.adoc[plan your backup] carefully and to back up each of your databases, including the `system` database.
====


[[offline-backup-command]]
== Command

A Neo4j database can be backed up in offline mode using the `dump` command of `neo4j-admin`.

[[offline-backup-command-usage]]
=== Usage

The `neo4j-admin dump` command can be used for performing a full backup of an **offline** database.
It dumps a database into a single-file archive, called _<database>.dump_.
The command can be run only locally from an online or an offline Neo4j DBMS.
It does not support SSL/TLS.

[[offline-command-syntax]]
=== Syntax

[source,role=noheader]
----
neo4j-admin dump --database=<database>
                 --to=<destination-path>
                 [--verbose]
----

[[offline-backup-command-options]]
=== Options

[options="header"]
|===
| Option       | Default | Description
| `--database` | `neo4j` | Name of the database to dump.
| `--to`       |         | Destination (file or folder) of database dump.
| `--verbose`  |         | Enable verbose output.
|===


[[offline-backup-example]]
== Example

The following is an example of how to create a dump of the default database `neo4j`, called _neo4j-<timestamp>.dump_, using the `neo4j-admin dump` command.
The target directory _/dumps/neo4j_ must exist before running the command and the database must be offline.

[source,shell]
----
bin/neo4j-admin dump --database=neo4j --to=/dumps/neo4j/neo4j-<timestamp>.dump
----
