:description: This section describes how to back up an offline database.
[[offline-backup]]
= Back up an offline database

[CAUTION]
====
Remember to xref:backup-restore/planning.adoc[plan your backup] carefully and back up each of your databases, including the `system` database.
====


[[offline-backup-command]]
== Command

The `neo4j-admin database dump` command can be used for performing a full backup of an **offline** database.
It dumps a database into a single-file archive, called _<database>.dump_, and stores it in the xref:configuration/file-locations.adoc#data[_<NEO4J_HOME>/data_] directory.
Alternatively, `neo4j-admin database dump` can stream dump to standard output, enabling the output to be piped to another program, for example to `neo4j-admin database load`.

If the database is hosted in a cluster, make sure that the database is stopped on the server you are connected to.
The command can be run only locally from an online or an offline Neo4j DBMS.
It does not support SSL/TLS.

[[offline-command-syntax]]
=== Syntax

[source,role=noheader]
----
neo4j-admin database dump [-h] [--expand-commands]
                          [--verbose] [--overwrite-destination[=true|false]]
                          [--additional-config=<file>]
                          [--to-path=<path> | --to-stdout]
                          <database>
----

=== Description

Dump a database into a single-file archive.
The archive can be used by the load command.
`<to-path>` should be a directory (in which case a file called _<database>.dump_ will be created), or `--to-stdout` can be supplied to use standard output.
If neither `--to-path` or `--to-stdout` is supplied `server.directories.dumps.root` setting will be used as a destination.
It is not possible to dump a database that is mounted in a running Neo4j server.

=== Parameters

.`neo4j-admin database dump` parameters
[options="header", cols="1m,3a"]
|===
| Parameter
| Description

|<database>
|Name of the database to dump. Can contain `\*` and `?` for globbing.
 Note that `*` and `?` have special meaning in some shells and might need to be escaped or used with quotes.
|===

[[offline-backup-command-options]]
=== Options

The `neo4j-admin database dump` command has the following options:

.`neo4j-admin database dump` options
[options="header", cols="5m,6a,4m"]
|===
| Option
| Description
| Default

|--additional-config=<file>
|Configuration file with additional configuration.
|

|--expand-commands
|Allow command expansion in config value evaluation.
|

| -h, --help
|Show this help message and exit.
|

| --overwrite-destination[=true\|false]
|Overwrite any existing dump file in the destination folder.
|false

|--to-path=<path>
|Destination folder of a database dump.
|

|--to-stdout
|Use standard output as the destination for the database dump.
|

|--verbose
|Enable verbose output.
|
|===

[NOTE]
====
As of Neo4j 5.19, the `--to-path=<path>` option can also dump databases to AWS S3 URIs.
For more information, see <<offline-backup-aws-s3-example>>.
====

[[offline-backup-example]]
== Examples

=== Dump the default database `neo4j` to a local directory

The following is an example of how to create a dump of the default database `neo4j` using the `neo4j-admin database dump` command.
The target directory _/dumps/neo4j_ must exist before running the command and the database must be offline.

[source, shell, role="nocopy"]
----
bin/neo4j-admin database dump <database> --to-path=/full/path/to/dumps/
----

The command creates a file called _<database>.dump_ where `<database>` is the database specified in the command.

[[offline-backup-aws-s3-example]]
=== Dump a database to a folder located in an AWS S3 storage

_This feature is available from Neo4j 5.19._

To dump a database to an AWS S3 storage, you can use the `--to-path` option with an S3 URI.
For example, use the following steps.

include::partial$/aws-s3-overrides.adoc[]

include::partial$/aws-s3-credentials.adoc[]

. Run `neo4j-admin database dump` command to dump your database to an AWS S3 storage:
+
[source, shell, role="nocopy"]
----
bin/neo4j-admin database dump <database> --to-path=s3://myBucket/myDirectory/
----

[NOTE]
====
`neo4j-admin database dump` cannot be applied to xref:database-administration/composite-databases/manage-composite-databases.adoc[Composite databases].
It must be run directly on the databases that are associated with that Composite database.
====