[role=enterprise-edition]
[[prepare-restore]]
= Prepare a database for restoring
:description: This section describes how to apply the latest transactions pulled at the backup time but not yet applied to the store. 

[[prepare-restore-command]]
== Command

If the `--prepare-restore` option is disabled when you xref:backup-restore/online-backup.adoc[back up your database], your store may not contain the latest transactions pulled at backup time.
In this case, you have to run the  `--neo4j-admin prepare-restore` command to apply those transactions to the store, before you can restore your data.

[[prepare-restore-syntax]]
=== Syntax

[source,role=noheader]
----
neo4j-admin prepare-restore --target=<path>[,<path>...]...
                            [--verbose]
                            [--expand-commands]
                            [--parallel-recovery]
----

[[prepare-restore-options]]
=== Options

[options="header",cols="m,m,a"]
|===
| Option
| Default
| Description

| --target
|
| A path to the backup that is going to be prepared for restoring.
A path can contain asterisks or question marks in the last subpath but must not contain commas.
Multiple paths are separated by a comma.

| --verbose
|
| Enable verbose output.

| --expand-commands
|
| Allow command expansion in config value evaluation.

| --parallel-recovery
| false
| Allow multiple threads to apply transactions to a backup in parallel.
For some databases and workloads, this may reduce execution times significantly.
[NOTE]
====
`parallel-recovery` is an experimental option.
Consult Neo4j support before use.
====
|===


[[prepare-restore-example]]
== Example

The following is an example of preparing your database backup, created in the section xref:backup-restore/online-backup.adoc#online-backup-example[Back up an online database], for restoring, using the `neo4j-admin prepare-restore` command.

[source,shell]
----
bin/neo4j-admin prepare-restore --target=/mnt/backups/neo4j
----
