:description: This section describes how to restore a database backup or an offline database in a live Neo4j deployment.
[role=enterprise-edition]
[[restore-backup]]
= Restore a database backup

[[restore-backup-command]]
== Command

A database backup or an *offline* database can be restored using the `restore` command of `neo4j-admin`.
You must create the database (using `CREATE DATABASE` against the `system` database) after the restore operation finishes, unless you are replacing an existing database.
`neo4j-admin restore` must be invoked as the `neo4j` user to ensure the appropriate file permissions.
For more information, see xref:manage-databases/configuration.adoc#manage-databases-administration[Administrative commands].

[NOTE]
====
If the `--prepare-restore` option is disabled when backing up your database, you must first perform the `neo4j-admin prepare-restore` command before you can restore your database.
This is to apply the latest transactions pulled at the backup time but not yet applied to the store.
For more information, see xref:backup-restore/prepare-restore.adoc[Prepare a database for restoring].
====

[[restore-backup-syntax]]
=== Syntax

[source,role=noheader]
----
neo4j-admin restore  --from=<path>[,<path>...]
                    [--verbose]
                    [--expand-commands]
                    [--database=<database>]
                    [--force]
                    [--move]
                    [--to-data-directory=<path>]
                    [--to-data-tx-directory=<path>]
----

[[restore-backup-command-options]]
=== Options

[options="header",cols="m,m,a"]
|===
| Option
| Default
| Description

| --from
|
| A path or multiple paths to the database backup(s) for restore.
A path can contain asterisks or question marks in the last subpath but must not contain commas.
Commas are used to separate multiple paths.

| --verbose
|
| Enables verbose output.

| --expand-commands
|
| Allows command expansion in config value evaluation.

| --database
| neo4j
| Name for the restored database.

| --force
|
| Replaces an existing database.

| --move
|
| Moves the backup files to the destination, rather than copying.
This makes the restoring process faster and with no need for extra disk space.
However, for this procedure to work properly, backup and database files must be on the same filesystem.
In case they are not, the command will only copy the files and delete the backup, resulting in no performance benefits.

| --to-data-directory
|
| Base directory for databases.
Usage of this option is only allowed if the `--from` parameter points to one directory.

| --to-data-tx-directory
|
| Base directory for transaction logs.
Usage of this option is only allowed if the `--from` parameter points to one directory.
|===

[[restore-backup-example]]
== Example

The following is an example of how to perform an online restore of the database backup created in the section xref:backup-restore/online-backup.adoc#online-backup-example[Back up an online database], using the `neo4j-admin restore` command.

[source,shell]
----
bin/neo4j-admin restore --from=/mnt/backups/neo4j --database=neo4j --force
----

[NOTE]
====
Unless you are replacing an existing database, you must create the database (using `CREATE DATABASE` against the `system` database) after the restore operation finishes.
====

If you have backed up a database with the option `--include-metadata`, you can manually restore the users and roles metadata.

From the _<neo4j-home>_ directory, you run the Cypher script _data/databases/databasename/tools/metadata_script.cypher_, which the `neo4j-admin restore` command outputs, using xref:tools/cypher-shell.adoc[Cypher Shell]:

*Using `cat` (UNIX)*
[source, shell, role=nocopy noplay]
----
cat data/databases/databasename/tools/metadata_script.cypher | bin/cypher-shell -u user -p password -a ip_address:port -d system --param "database => 'databasename'"
----

*Using `type` (Windows)*
[source, shell, role=nocopy noplay]
----
type data\databases\databasename\tools\metadata_script.cypher | bin\cypher-shell.bat -u user -p password -a ip_address:port -d system --param "database => 'databasename'"
----

[TIP]
====
For a detailed example on how to back up and restore a database in a Causal cluster, see xref:tutorial/causal-backup-restore-db.adoc[Back up and restore a database in Causal Cluster].
====

[NOTE]
====
`neo4j-admin restore` cannot be applied to the xref:fabric/introduction.adoc#fabric-fabric-concepts[Fabric virtual database].
It must be run directly on the databases that are part of the Fabric setup.
====
