:description: This section describes how to restore a database backup or an offline database in a live Neo4j deployment.
[role=enterprise-edition]
[[restore-backup]]
= Restore a database backup

[[restore-backup-command]]
== Command

A database backup artifact (full or differential) can be restored within the same or to a later Neo4j version using the `restore` command of `neo4j-admin`.

[NOTE]
====
Restoring a database backup to a previous Neo4j version is not supported.
====

You must create the database (using `CREATE DATABASE` against the `system` database) after the restore operation finishes, unless you are replacing an existing database.
`neo4j-admin database restore` must be invoked as the `neo4j` user to ensure the appropriate file permissions.
For more information, see xref:manage-databases/configuration.adoc#manage-databases-administration[Administrative commands].

[NOTE]
====
When restoring a backup chain, the transaction log contained in the differential backup artifacts must first be replayed.
This recovery operation is resource intensive and can be decoupled from the restore operation by using the xref:backup-restore/aggregate.adoc[aggregate] command.
====

[[restore-backup-syntax]]
=== Syntax

[source,role=noheader]
----
neo4j-admin database restore [-h] [--expand-commands]
                             [--verbose] [--overwrite-destination[=true|false]]
                             [--additional-config=<file>]
                             --from-path=<path>[,<path>...]
                             [--restore-until=<recovery-criteria>]
                             [--to-path-data=<path>] [--to-path-txn=<path>]
                             [<database>]
----

=== Parameters

.`neo4j-admin database restore` parameters
[options="header", cols="1m,3a"]
|===
| Parameter
| Description

|<database>
|Name of the database after restore. Usage of this parameter is only allowed if the `--from-path` option points to a path to a single artifact.
|===


[[restore-backup-command-options]]
=== Options

.`neo4j-admin database restore` options
[options="header", cols="5m,6a,4m"]
|===
| Option
| Description
| Default

|--additional-config=<file>
|Configuration file with additional configuration or override the existing configuration settings in the _neo4j.conf_ file.
|

|--expand-commands
|Allow command expansion in config value evaluation.
|

|--from-path=<path>[,<path>...]
|A single path or a comma-separated list of paths pointing to a backup artifact file.
An artifact file can be 1) a full backup, in which case it is restored directly or, 2) a differential backup, in which case the command tries first to find in the folder a backup chain ending at that specific differential backup and then restores that chain.
|

|-h, --help
|Show this help message and exit.
|

|--overwrite-destination[=true\|false]
|If an existing database should be replaced.
This option is not safe on a cluster since clusters have additional state that would be inconsistent with restored database.
In a cluster, restore to a new database to avoid this problem.
|false

|--restore-until=<recovery-criteria>
| Differential backup artifacts contain transaction logs that can be replayed and applied to stores contained in full backup artifacts when restoring a backup chain.
The database applies logs until the recovery predicate is satisfied.
Currently supported predicates are: `<transactionID>` and `<timestamp>`.

- to restore a database up to a transaction ID, the required transaction predicate should look like `--restore-until=123`, where 123 is a provided transaction ID.
The restore recovers transaction logs up to - but not including - transaction 123.

- to restore a database up to a specific date, the required date predicate should look like `--restore-until=2023-05-01 10:15:30`, where 2023-05-01 10:15:30 is a UTC date and time.
The restore recovers transactions that were committed before the provided date.
|

| --to-path-data=<path>
|Base directory for databases.
Usage of this option is only allowed if the `--from-path` parameter points to one directory.
|

|--to-path-txn=<path>
|Base directory for transaction logs.
Usage of this option is only allowed if the `--from-path` parameter points to one directory.
|

|--verbose
|Enable verbose output.
|
|===

[[restore-backup-example]]
== Examples

.Restore a database backup
====

. Restore a database backup created in the section xref:backup-restore/online-backup.adoc#online-backup-example[Back up an online database]. The backup artifact is located in the `/path/to/mybackups` directory.
The database is restored to a new database, for example, `mydatabase`.
If you want to replace an existing database, add the option `--overwrite-destination=true` to the restore command.
+
[source,shell]
----
bin/neo4j-admin database restore --from-path=/path/to/backups/neo4j-2023-05-05T11-26-38.backup mydatabase
----

. Unless you are replacing an existing database, create the new database using `CREATE DATABASE` against the `system` database.
+
[source,cypher, role="noplay"]
----
CREATE DATABASE mydatabase
----

====

.Restore data up to a specific date
====
Restore a database backup created in the section xref:backup-restore/online-backup.adoc#online-backup-example[Back up an online database], but restore only the data up to a specific date.
The backup artifacts are located in the `/path/to/mybackups` directory.

[NOTE]
Restoring data up to a specific date is only possible after you drop the existing database.

. Log in to the Neo4j using `cypher-shell`:
+
[source,shell]
----
bin/cypher-shell -u neo4j -p password
----
. Change the active database to `system`:
+
[source,cypher, role="noplay"]
----
:use system;
----
. Stop the database that requires the restore:
+
[source,cypher, role="noplay"]
----
STOP DATABASE databasename;
----
. Drop the database that requires the restore:
+
[source,cypher, role="noplay"]
----
DROP DATABASE databasename;
----
+
Do not exit the `cypher-shell` session.

. In a different `shell` terminal, inspect the backup artifacts in the _/path/to/mybackups_ directory:
+
[source,shell, role="noplay"]
----
bin/neo4j-admin database backup --inspect-path=/path/to/mybackups
----
+
The output of the command should look similar to the following:
+
[source,shell, role="noplay"]
----
|                                                   FILE | DATABASE |                          DATABASE ID |                TIME |  FULL | COMPRESSED | LOWEST TX | HIGHEST TX |
| file:///path/to/mybackups/neo4j-2023-06-29T14-46-27.backup |    neo4j | c8368b24-55e2-474d-bb41-75657f5bfcde | 2023-06-29T13:46:27 |  true |       true |         1 |         11 |
| file:///path/to/mybackups/neo4j-2023-06-29T14-50-45.backup |    neo4j | c8368b24-55e2-474d-bb41-75657f5bfcde | 2023-06-29T13:50:45 | false |       true |        12 |         14 |
| file:///path/to/mybackups/neo4j-2023-06-29T14-51-33.backup |    neo4j | c8368b24-55e2-474d-bb41-75657f5bfcde | 2023-06-29T13:51:33 | false |       true |        15 |         18 |
----
+
The output shows that the backup artifacts are part of a backup chain.
The first artifact is a full backup, and the other two are differential backups.
The `LOWEST TX` and `HIGHEST TX` columns show the transaction IDs of the first and the last transaction in the backup artifacts.

. Restore data up to a specific date:
+
[source,shell, role="noplay"]
----
bin/neo4j-admin database restore --from-path=/path/to/mybackups/neo4j-2023-06-29T14-50-45.backup --restore-until="2023-06-29 13:50:45"
----
+
The `--from-path=` argument must contain the path to either a full or a differential backup artifact.
If you want to restore several databases at once, you can specify a comma-separated list of paths to backup artifacts.
The `--restore-until=` argument must contain a UTC date and time.
The restore recovers transactions that were committed before the provided date.
+
[NOTE]
If you know the transaction ID of the last transaction that was committed before the date you want to restore to, you can use the `--restore-until=` argument with the transaction ID instead of the date.
For example, `--restore-until=123`.

. Using `cypher-shell`, recreate the database that you dropped using `CREATE DATABASE` against the `system` database, for example:
+
[source,cypher, role="noplay"]
----
CREATE DATABASE databasename;
----

====

If you have backed up a database with the option `--include-metadata`, you can manually restore the users and roles metadata.

From the _<neo4j-home>_ directory, you run the Cypher script _data/scripts/databasename/restore_metadata.cypher_, which the `neo4j-admin database restore` command outputs, using xref:tools/cypher-shell.adoc[Cypher Shell]:

*Using `cat` (UNIX)*
[source, shell, role=nocopy noplay]
----
cat data/scripts/databasename/restore_metadata.cypher | bin/cypher-shell -u user -p password -a ip_address:port -d system --param "database => 'databasename'"
----

*Using `type` (Windows)*
[source, shell, role=nocopy noplay]
----
type data\scripts\databasename\restore_metadata.cypher | bin\cypher-shell.bat -u user -p password -a ip_address:port -d system --param "database => 'databasename'"
----
