:description: This section describes how to restore a database backup or an offline database in a live Neo4j deployment.
[role=enterprise-edition]
[[restore-backup]]
= Restore a database backup

[[restore-backup-command]]
== Command

A database backup artifact can be restored within the same or to a later Neo4j version using the `restore` command of `neo4j-admin`.

[NOTE]
====
Restoring a database backup to a previous Neo4j version is not supported.
====

You must create the database (using `CREATE DATABASE` against the `system` database) after the restore operation finishes, unless you are replacing an existing database.
`neo4j-admin database restore` must be invoked as the `neo4j` user to ensure the appropriate file permissions.
For more information, see xref:manage-databases/configuration.adoc#manage-databases-administration[Administrative commands].

[NOTE]
====
When restoring a backup chain, the transaction log contained in the differential backup artifacts need first to be replayed.
This recovery operation is resource intensive and can be decoupled from the restore operation by using the xref:backup-restore/aggregate.adoc[aggregate] command.
====

[[restore-backup-syntax]]
=== Syntax

[source,role=noheader]
----
neo4j-admin database restore [-h] [--expand-commands]
                             [--verbose] [--overwrite-destination[=true|false]]
                             [--additional-config=<file>]
                             --from-path=<path>[,<path>...]
                             [--restore-until=<recovery-criteria>]
                             [--to-path-data=<path>] [--to-path-txn=<path>]
                             [<database>]
----

=== Parameters

.`neo4j-admin database restore` parameters
[options="header", cols="1m,3a"]
|===
| Parameter
| Description

|<database>
|Name of the database after restore. Usage of this parameter is only allowed if the `--from-path` option points to a path to a single artifact.
|===


[[restore-backup-command-options]]
=== Options

.`neo4j-admin database restore` options
[options="header", cols="5m,6a,4m"]
|===
| Option
| Description
| Default

|--additional-config=<file>
|Configuration file with additional configuration or override the existing configuration settings in the _neo4j.conf_ file.
|

|--expand-commands
|Allow command expansion in config value evaluation.
|

|--from-path=<path>[,<path>...]
|A single path or a comma-separated list of paths pointing to a backup artifact file.
An artifact file can be 1) a full backup, in which case it is restored directly or, 2) a differential backup, in which case the command tries first to find in the folder a backup chain ending at that specific differential backup and then restores that chain.
|

|-h, --help
|Show this help message and exit.
|

|--overwrite-destination[=true\|false]
|If an existing database should be replaced.
This option is not safe on a cluster since clusters have additional state that would be inconsistent with restored database.
In a cluster, restore to a new database to avoid this problem.
|false

|--restore-until=<recovery-criteria>
| Differential backup artifacts contain transaction logs that can be replayed and applied to stores contained in full backup artifacts when restoring a backup chain.
The database applies logs until the recovery predicate is satisfied.
Currently supported predicates are: `<transaction>` and `<date>`.

- to restore a database up to a transaction id, the required transaction predicate should look like `--restore-until=123`, where 123 is a provided transaction id.
The restore recovers transaction logs up to - but not including - transaction 123.

- to restore a database up to a specific date, the required date predicate should look like `--restore-until=2023-05-01 10:15:30`, where n2023-05-01 10:15:30 is a UTC date.
The restore recovers transactions that were committed before the provided date.

[NOTE]
====
This option is only applicable to differential backups.
====
|

| --to-path-data=<path>
|Base directory for databases.
Usage of this option is only allowed if the `--from-path` parameter points to one directory.
|

|--to-path-txn=<path>
|Base directory for transaction logs.
Usage of this option is only allowed if the `--from-path` parameter points to one directory.
|

|--verbose
|Enable verbose output.
|
|===

[[restore-backup-example]]
== Example

The following is an example of how to perform an online restore of the database backup created in the section xref:backup-restore/online-backup.adoc#online-backup-example[Back up an online database], using the `neo4j-admin database restore` command.

[source,shell]
----
bin/neo4j-admin database restore --from-path=/mnt/backups/neo4j-2023-05-05T11-26-38.backup --overwrite-destination neo4j
----

[NOTE]
====
Unless you are replacing an existing database, you must create the database (using `CREATE DATABASE` against the `system` database) after the restore operation finishes.
====

If you have backed up a database with the option `--include-metadata`, you can manually restore the users and roles metadata.

From the _<neo4j-home>_ directory, you run the Cypher script _data/scripts/databasename/restore_metadata.cypher_, which the `neo4j-admin database restore` command outputs, using xref:tools/cypher-shell.adoc[Cypher Shell]:

*Using `cat` (UNIX)*
[source, shell, role=nocopy noplay]
----
cat data/scripts/databasename/restore_metadata.cypher | bin/cypher-shell -u user -p password -a ip_address:port -d system --param "database => 'databasename'"
----

*Using `type` (Windows)*
[source, shell, role=nocopy noplay]
----
type data\scripts\databasename\restore_metadata.cypher | bin\cypher-shell.bat -u user -p password -a ip_address:port -d system --param "database => 'databasename'"
----
