[role=enterprise-edition]
[[restore-backup]]
= Restore a database backup
:description: This section describes how to restore a database backup or an offline database in a live Neo4j deployment. 

[[restore-backup-command]]
== Command

A database backup or an *offline* database can be restored using the `restore` command of `neo4j-admin`.
You must create the database (using `CREATE DATABASE` against the `system` database) after the restore operation finishes, unless you are replacing an existing database.
`neo4j-admin restore` must be invoked as the `neo4j` user to ensure the appropriate file permissions.

For more information, see xref:manage-databases/configuration.adoc#manage-databases-administration[Administrative commands].

[[restore-backup-syntax]]
=== Syntax

[source,role=noheader]
----
neo4j-admin restore  --from=<path>[,<path>...]
                    [--verbose]
                    [--database=<database>]
                    [--force]
                    [--move]
                    [--to-data-directory=<path>]
                    [--to-data-tx-directory=<path>]
----

[[restore-backup-command-options]]
=== Options

[options="header"]
|===
| Option                   | Default | Description
| `--from`                 |         | Path or paths to the database backup that is going to be restored. Every path may contain asterisks or question marks in the last subpath. Multiple paths can be separated by a comma, but paths themselves must not contain commas.
| `--verbose`              |         | Enables verbose output.
| `--database`             | `neo4j` | Name for the restored database.
| `--force`                |         | Replaces an existing database.
| `--move`                 |         | Moves the backup files to the destination, rather than copying. This makes the restoring process faster and with no need for extra disk space. However, for this procedure to work properly, backup and database files must be on the same filesystem. In case they are not, the command will only copy the files and delete the backup, resulting in no performance benefits.
| `--to-data-directory`    |         | Base directory for databases. Usage of this option is only allowed if the `--from` parameter points to one directory.
| `--to-data-tx-directory` |         | Base directory for transaction logs. Usage of this option is only allowed if the `--from` parameter points to one directory.
|===

[[restore-backup-example]]
== Example

The following is an example of how to perform an online restore of the database backup created in the section xref:backup-restore/online-backup.adoc#online-backup-example[Back up an online database], using the `neo4j-admin restore` command.

[source,shell]
----
bin/neo4j-admin restore --from=/mnt/backups/neo4j --database=neo4j --force
----

[NOTE]
====
Unless you are replacing an existing database, you must create the database (using `CREATE DATABASE` against the `system` database) after the restore operation finishes.
====

If you have backed up a database with the option `--include-metadata`, you have to restore the users and roles metadata manually.

From the _<neo4j-home>_ directory, you run the Cypher script _data/scripts/databasename/restore_metadata.cypher_, which the `neo4j-admin restore` command outputs, using xref:tools/cypher-shell.adoc[Cypher Shell]:

*Using `cat` (UNIX)*
[source, shell, role=nocopy noplay]
----
cat data/scripts/databasename/restore_metadata.cypher | bin/cypher-shell -u user -p password -a ip_address:port -d system --param "database => 'databasename'"
----

*Using `type` (Windows)*
[source, shell, role=nocopy noplay]
----
type data\scripts\databasename\restore_metadata.cypher | bin\cypher-shell.bat -u user -p password -a ip_address:port -d system --param "database => 'databasename'"
----

[TIP]
====
For a detailed example on how to back up and restore a database in a Causal cluster, see xref:tutorial/causal-backup-restore-db.adoc[Back up and restore a database in Causal Cluster].
====

[NOTE]
====
`neo4j-admin restore` cannot be applied to the xref:fabric/introduction.adoc#fabric-fabric-concepts[Fabric virtual database].
It must be run directly on the databases that are part of the Fabric setup.
====
