:page-role: new-2025.12 enterprise-edition not-on-aura
[[validate-backup]]
= Validate a sharded property database backup
:description: This section describes how to validate a sharded property database backup using the neo4j-admin backup validate command.
:keywords: neo4j-admin, backup, validate, sharded property databases, sharding

When you back up a sharded property database, you create multiple backup chains—one for each shard.
The backup chains of the graph shard will have 1 full backup and 0 or more differential backups.
Whereas the property shard backup chains will have only 1 full backup, differential backups of property shards are not supported.
See xref:scalability/sharded-property-databases/admin-operations.adoc#backup-and-restore[Backup and restore] for more information on backing up sharded property databases.

To ensure that the backup chains are valid and can be used for restoration, you can use the `neo4j-admin backup validate` command.

[[validate-backup-command]]
== Command

The `neo4j-admin backup validate` command checks the integrity and consistency of the backup artifacts for a specified sharded property database.

[[validate-backup-syntax]]
=== Syntax

[source,role=noheader]
----
neo4j-admin backup validate [-h] [--expand-commands] [--verbose]
                            [--additional-config=<file>] --database=<database>
                            [--format=<value>] --from-path=<backup-path>
----


=== Description

Command to validate a collection of backups.

[[validate-backup-command-options]]
=== Options

.`neo4j-admin backup validate` options
[options="header", cols="5m,6a,4m"]
|===
| Option
| Description
| Default

|--additional-config=<file>footnote:[See xref:neo4j-admin-neo4j-cli.adoc#_configuration[Neo4j Admin and Neo4j CLI -> Configuration] for details.]
|Configuration file with additional configuration.
|

|--database=<database>
|Name of the database to validate.
|

| --expand-commands
| Allow command expansion in config value evaluation.
|

|--format=<value>
|Format of the output of the command. Possible values are: 'JSON, TABULAR'.
|TABULAR

|--from-path=<backup-path>
|Path denoting a directory to where backups are stored.
|

|-h, --help
|Show this help message and exit.
|

|--verbose
|Enable verbose output.
|

|===

[[validate-backup-example]]
== Example

To validate a backup for the database `foo` located at _s3://bucket/backups_, use the following command:

[source,shell]
----
bin/neo4j-admin backup validate --from-path=s3://bucket/backups --database="foo"
----

The output will indicate whether the backups are valid.
For example:

[result]
----
| DATABASE |                                                PATH | STATUS |
| foo-g000 | /bucket/backups/foo-g000-2025-06-11T21-04-42.backup |     OK |
| foo-p000 | /bucket/backups/foo-p000-2025-06-11T21-04-37.backup |     OK |
| foo-p001 | /bucket/backups/foo-p001-2025-06-11T21-04-40.backup |     OK |
----

If valid, the backups can be used to xref:scalability/sharded-property-databases/data-ingestion.adoc#creating-sharded-db-from-uri[seed a sharded property database].

For more examples and details, see xref:scalability/sharded-property-databases/admin-operations.adoc#backup-and-restore[Backup and restore].