:description: Running Docker Using Docker Compose
[[docker-compose-neo4j-standalone]
= Deploy a Neo4j standalone server using Docker Compose

You can deploy a Neo4j standalone server using Docker Compose.
In addition to storing the container configuration, Docker Compose can simplify the usage of secrets.

[[docker-compose-basic-authentication]]
== Deploy a Neo4j server with basic authentication

Before you start, verify that you have installed Docker Compose.
For more information, see the https://docs.docker.com/compose/install/[Install Docker Compose official documentation].

//. Create a configuration file, `neo4j.conf` make it readable and writable for the user (eg., `chmod 640 neo4j.conf`).
. Prepare your _docker-compose.yml_ file using the following example.
For more information, see the https://docs.docker.com/compose/compose-file/#service-configuration-reference[Docker Compose official Service configuration reference].
+
.Example of a _docker-compose.yml_ file
====

[source,yaml,subs="attributes+,+macros"]
----
services:
  neo4j:
    image: neo4j:{neo4j-version-exact}
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
----
====
. Deploy your Neo4j server by running `docker-compose up` from your project folder.
+
[source,shell,subs="attributes+,+macros"]
----
docker-compose up -d #<1>
----
<1> The `-d` flag starts the container in detached mode.

Similarly, you can mount volumes and configure environment variables.

. Mount logs, config, and plugins to the equivalent container mount points.
+
[source,yaml,subs="attributes+,+macros"]
----
services:
  neo4j:
    image: neo4j:{neo4j-version-exact}
    volumes:
        - /$HOME/neo4j/logs:/logs # <1>
        - /$HOME/neo4j/config:/config
        - /$HOME/neo4j/plugins:/plugins
    environment:
        - NEO4J_AUTH=neo4j/your_password # <2>
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
----
<1> Mounting the _neo4j/logs_ directory to a host local directory.
<2> Setting the `neo4j` username and password.

[role=label--recommended]
[[docker-compose-secrets]]
== Deploy a Neo4j server with Docker secrets

It is advisable not to store sensitive information, such as the database username and password, in the _docker-compose.yml_ file.
You can instead store your credentials in files and use them in your _docker-compose.yml_ file without exposing their values.

. Create a file, for example, _neo4j_auth.txt_, containing the username and password for the Neo4j server to be used as a Docker secret.
+
[source,text,subs="attributes"]
----
neo4j:your_password
----
. Prepare your _docker-compose.yml_ file using the following example.
+
.Example of a _docker-compose.yml_ file
====
[source,yaml,subs="attributes+,+macros"]
----
services:
  neo4j:
    image: neo4j:{neo4j-version-exact}
    volumes:
        - /$HOME/neo4j/logs:/logs
        - /$HOME/neo4j/config:/config
        - /$HOME/neo4j/plugin:/plugins
    environment:
        - NEO4J_AUTH_FILE=/run/secrets/neo4j_auth_file # <1>
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    secrets:
      - neo4j_auth_file #<4>
secrets:
  neo4j_auth_file: # <2>
    file: ./neo4j_auth.txt # <3>
----
<1> The file where the value for the `NEO4J_AUTH` environment variable can be found.
<2> Defining the secret named `neo4j_auth_file`
<3> Pointing to the `neo4j_auth.txt` file
<4> Using the secret in the `neo4j` service
====
. Deploy your Neo4j server by running `docker-compose up` from your project folder.
+
[source,shell,subs="attributes+,+macros"]
----
docker-compose up -d
----
[NOTE]
====
You can define any Neo4j variable as a secret in the same way by simply using the same variable name with the `_FILE` suffix.
====
[WARNING]

====
The secret value overrides the equivalent environment variable if they are both defined.
So, for example, if you also define an environment variable `NEO4J_AUTH=neo4j/your_other_password` in the `environment` section of the `neo4j` service, the value of `NEO4J_AUTH_FILE` will be the one used.
====