:description: Dump and load operations when running Neo4j in a Docker container.

[[docker-neo4j-dump]]
= Dump and load a Neo4j database (offline)

The xref:backup-restore/offline-backup.adoc[`neo4j-admin database dump`] and xref:backup-restore/restore-dump.adoc[`neo4j-admin database load`] commands can be run locally to dump and load an offline database.

The following are examples of how to dump and load the default `neo4j` database.
Because these commands are run on a stopped database, you have to launch a container for each operation (dump and load), with the `--rm` flag.

.Invoke `neo4j-admin database dump` to dump your database.
====
[source, shell, subs="attributes+,+macros"]
----
docker run --interactive --tty --rm \
   --volume=$HOME/neo4j/data:/data \  # <1>
   --volume=$HOME/neo4j/backups:/backups \  # <2>
   neo4j/neo4j-admin:{neo4j-version-exact} \
neo4j-admin database dump neo4j --to-path=/backups
----
<1> The volume that contains the database that you want to dump.
<2> The volume that will be used for the dumped database.
====

.Invoke `neo4j-admin database load` to load your data into the new database.
====
[source, shell, subs="attributes+,+macros"]
----
docker run --interactive --tty --rm \
    --volume=$HOME/neo4j/newdata:/data \ # <1>
    --volume=$HOME/neo4j/backups:/backups \ # <2>
    neo4j/neo4j-admin:{neo4j-version-exact} \
neo4j-admin database load neo4j --from-path=/backups
----
<1> The volume that will contain the database, into which you want to load the dumped data.
<2> The volume that stores the database dump.
====

Finally, you xref:docker/introduction.adoc#docker-image[launch a container] with the volume that contains the newly loaded database, and start using it.

.Launching a container from restored data
[source, shell, subs="attributes+,+macros"]
----
docker run --interactive --tty --rm \
    --volume=$HOME/neo4j/newdata:/data \ # <1>
    neo4j:{neo4j-version-exact}
----
<1> The volume containing the restored data
====

[NOTE]
For more information on the `neo4j-admin database dump and load` syntax and options, see xref:backup-restore/offline-backup.adoc#offline-backup-command-options[`neo4j-admin database dump`] and xref:backup-restore/restore-dump.adoc[`neo4j-admin database load`]. +
For more information on managing volumes, see https://docs.docker.com/storage/volumes/[the official Docker documentation].
====
