[[docker-overview]]
= Introduction
:description: An introduction to how Neo4j runs in a Docker container. 

The Neo4j Docker image, and instructions on how to start using it, can be found here: https://hub.docker.com/_/neo4j/.

[[docker-ports]]
== Ports

By default, the Docker image exposes three ports for remote access:

* `7474` for HTTP.
* `7473` for HTTPS.
* `7687` for Bolt.

Note that when Docker is used, Neo4j is configured automatically to allow remote access to the HTTP, HTTPS, and Bolt services.
This is different than the default Neo4j configuration, where the HTTP, HTTPS, and Bolt services do not allow remote connections.
For more information on configuring connections, see xref:configuration/connectors.adoc[Configure connectors].


[[docker-volumes]]
== Volumes

The Docker image also exposes the following volumes.
Directories on the host can be mounted using the `--volume` option.
See xref:configuration/file-locations.adoc[File locations] for details about the directories used by default in different Neo4j distributions.

* _/conf_
* _/data_
* _/import_
* _/logs_
* _/metrics_
* _/plugins_
* _/ssl_

It is often desirable to keep database and logs outside of the container.
The following command starts a container with ports for Bolt and HTTP published, and with the _/data_ and _/logs_ volumes mapped to directories on the host.

[source, shell, subs="attributes"]
----
docker run \
    --publish=7474:7474 --publish=7687:7687 \
    --volume=$HOME/neo4j/data:/data \
    --volume=$HOME/neo4j/logs:/logs \
    neo4j:{neo4j-version}
----

Point your browser at `+http://localhost:7474+` or `+http://$(docker-machine ip default):7474+` if on a remote machine.

All the volumes in this documentation are stored under `$HOME`.
If stored somewhere else, substitute the volume source with the full path to the mapped directory.

[NOTE]
--
By default Neo4j requires authentication and requires you to login with `neo4j/neo4j` at the first connection and set a new password.
You can set the password for the Docker container directly by specifying `--env NEO4J_AUTH=neo4j/<password>` in your run directive.
Alternatively, you can disable authentication by specifying `--env NEO4J_AUTH=none` instead.
--


[[docker-user]]
== Running Neo4j as a non-root user

For security reasons, Neo4j runs as the `neo4j` user inside the container.
You can specify which user to run as by invoking docker with the `--user` argument.
For example, the following runs Neo4j as your current user:

[source, shell, subs="attributes"]
----
docker run \
    --publish=7474:7474 --publish=7687:7687 \
    --volume=$HOME/neo4j/data:/data \
    --volume=$HOME/neo4j/logs:/logs \
    --user="$(id -u):$(id -g)" \
    neo4j:{neo4j-version}
----

[NOTE]
The folders that you want to mount must exist before starting Docker, otherwise Neo4j will fail to start due to permissions errors.

[[docker-offline-installation]]
== Offline installation of Neo4j Docker image

Docker provides the `docker save` command for downloading an image into a `.tar` package so that it can be used offline, or transferred to a machine without internet access.

This is an example command to save the `neo4j:{neo4j-version}` image to a `.tar` file:
[source, shell, subs="attributes"]
----
docker save -o neo4j-{neo4j-version}.tar neo4j:{neo4j-version}
----

To load a docker image from a `.tar` file created by `docker save`, use the `docker load` command.
For example:
[source, shell, subs="attributes"]
----
docker load --input neo4j-{neo4j-version}.tar
----

For complete instructions on using the `docker save` and `docker load` commands, refer to:

* https://docs.docker.com/engine/reference/commandline/save/[The official `docker save` documentation].
* https://docs.docker.com/engine/reference/commandline/load/[The official `docker load` documentation].

[[docker-edition]]
== Neo4j editions

Tags are available for both Community Edition and Enterprise Edition.
Version-specific Enterprise Edition tags have an `-enterprise` suffix, for example: `neo4j:{neo4j-version-exact}-enterprise`.
Community Edition tags have no suffix, for example `neo4j:{neo4j-version-exact}`.
The latest Neo4j Enterprise Edition release is available as `neo4j:enterprise`.


[[docker-enterprise-edition-license]]
=== Neo4j Enterprise Edition license

In order to use Neo4j Enterprise Edition you must accept the license agreement.

____
(C) Network Engine for Objects in Lund AB.  2021.  All Rights Reserved.
Use of this Software without a proper commercial license with Neo4j,
Inc. or its affiliates is prohibited.

Email inquiries can be directed to: licensing@neo4j.com

More information is also available at: https://neo4j.com/licensing/
____

To accept the license agreement set the environment variable `NEO4J_ACCEPT_LICENSE_AGREEMENT=yes`.

To do this you can use the following docker argument:

[source, shell]
----
--env NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
----
