:description: How to use persistent storage when using Neo4j in Docker.
[[docker-volumes]]
= Mounting Storage to Docker
// Mounting Docker Volumes
// persistent storage in docker

Storage, in the form of a folder on the host file system or a Docker volume, can be mounted to Docker containers on `docker run` in order to:

* persist data if the container is stopped
* get data in or out of the container

We provide a number of special mount points for storage to simplify using Neo4j in Docker.




For instructions on _how_ to mount storage to a Docker container, it is best to refer to the official Docker documentation:

* link:https://docs.docker.com/storage/bind-mounts/[mounting a folder as persistent storage]
* link:https://docs.docker.com/storage/volumes/[mounting a named volume as persistent storage]

In this documentation we mostly use folder mounts to demonstrate Neo4j Docker use, but named volume mounting is also supported.



[[docker-volumes-data]]
== The `/data` folder

Neo4j inside Docker stores database files in the `/data` folder.
By mounting storage to `/data`, any data written to neo4j will persist after the container is stopped.

Stopping the container and then restarting with the same folder mounted to `/data` will
start a new containerized Neo4j instance with the same data.

[CAUTION]
====
If Neo4j could not properly close down, it may have left data in a bad state, and is likely to fail on startup.
This is the same as if Neo4j was run outside a container and not closed properly.
====



.Two ways to mount storage to the `/data` mount point
====
.Mounting a folder to `/data`
[source, shell, subs="attributes"]
----
docker run -it --rm \
   --volume $HOME/neo4j/data:/data \
   neo4j:{neo4j-version-exact}
----
.Creating a named volume and mounting it to `/data`
[source, shell, subs="attributes"]
----
docker volume create neo4jdata #<1>
docker run -it --rm \
   --volume neo4jdata:/data \ #<2>
   neo4j:{neo4j-version-exact}
----
<1> Create a Docker volume named `neo4jdata`
<2> Mount the volume name `neo4jdata` to `/data`
====

[[docker-volumes-mount-points]]
== All Recognized Mount Points

The following table is a complete reference of the mount points recognized by the Neo4j Docker image, and file permissions.

All the listed mount points are *optional*. Neo4j will still run in Docker without any volumes mounted at all.
However, mounting storage to `/data` is considered essential for all but the most basic use-cases.

[WARNING]
====
Running containerized Neo4j without a `/data` mount *will* result in unrecoverable data loss if anything happens to the container.
====

.Mount points for the Neo4j container
[options="header", cols="1m,1,4"]
|===
| Mount point
| permissions required
| Description

| /data
| read, write
| The data store for the Neo4j database. See xref:#docker-volumes-data[]

| /logs
| read, write
| Output directory for Neo4j logs. By mounting storage to `/logs` the log files will be available outside the container. +
For more information about the Neo4j log files, see xref:monitoring/logging.adoc[Logging].

| /conf
| readfootnote:[Write permissions also required if using the `dump-config` feature.]
| Pass configuration files to Neo4j on start up. +
See xref:docker/configuration.adoc[Docker Configuration].

| /plugins
| readfootnote:[Write permissions also required if using the xref:docker/plugins.adoc#docker-plugins-caching[`NEO4J_PLUGINS` feature] to download and store plugins.]
| Allows you to install plugins in containerized Neo4j. +
See xref:docker/plugins.adoc[].

| /licenses
| read
| Provide licenses for Neo4j and any plugins by mounting the license folder here. +
See xref:docker/plugins.adoc#docker-plugins-licenses[Installing Plugin Licenses].

| /import
| read
| Make _csv_ and other importable files available to xref:docker/operations.adoc#docker-neo4j-import[neo4j-admin import].

| /ssl
| read
| Provide SSL certificates to Neo4j for message encryption. +
See xref:docker/security.adoc[]

| /metrics
| write
| Enterprise only. Output directory for metrics files.
See xref:monitoring/metrics/index.adoc[Metrics].
|===


[[docker-volumes-file-permissions]]
== File Permissions

For security reasons, by default Neo4j runs as the `neo4j` user inside the container.
This user has user ID 7474.
If `neo4j` needs read or write access to a mounted folder, but does not have it, the folder will be automatically re-owned to 7474.
This is a convenience feature so users do not have to worry about the finer details of file permissions in Docker and can get started more easily.
It does however mean that mounted folders will change ownership, and you may find you can no longer read your files without root access.


=== Docker `run` with `--user` flag

The `--user` flag to `docker run` forces Docker to run as the provided user.
In this situation, if that user does not have the required read or write access to any mounted folders then Neo4j will fail to start.
