[[docker-operations]]
= Docker specific operations
:description: How to use Neo4j tools when running Neo4j in a Docker container.

[[docker-neo4j-admin]]
== Use Neo4j Admin

The xref:tools/neo4j-admin/index.adoc[Neo4j Admin tool] can be run locally within a container using the following command:

[source, shell]
----
docker exec --interactive --tty <containerID/name> neo4j-admin <command>
----

To determine the container ID or name, run `docker ps` to list the currently running Docker containers.

For more information about the `neo4j-admin` commands, see xref:tools/neo4j-admin/index.adoc[Neo4j Admin tool].

[[docker-neo4j-import]]
== Use Neo4j Import

The xref:tools/neo4j-admin/neo4j-admin-import.adoc[Neo4j Import tool] can be run locally within a container using the following command:

[source, shell]
----
docker exec --interactive --tty <containerID/name> neo4j-admin import <options>
----

For more information about the `neo4j-admin import` syntax and options, see xref:tools/neo4j-admin/neo4j-admin-import.adoc#import-tool-syntax[Syntax] and xref:tools/neo4j-admin/neo4j-admin-import.adoc#import-tool-options[Options].

[discrete]
[[docker-import-prerequisites]]
=== Prerequisites

* Verify that you have created the folders that you want to mount as volumes to the Neo4j docker container.
* Verify that the CSV files that you want to load into Neo4j are formatted as per xref:tools/neo4j-admin/neo4j-admin-import.adoc#import-tool-header-format[CSV header format].
* Verify that you have added the CSV files to the folder that will be mounted to _/import_ in your container.

[discrete]
[[docker-import-example]]
=== Import CSV files into the Neo4j Docker container using the Neo4j import tool

This is an example of how to start a container with mounted volumes _/data_ and _/import_, to ensure the persistence of the data in them, and load the CSV files using the `neo4j-admin import` command.
You can add the flag `--rm` to automatically remove the container's file system when the container exits.

[source, shell, subs="attributes"]
----
docker run --interactive --tty --rm \
    --publish=7474:7474 --publish=7687:7687 \
    --volume=$HOME/neo4j/data:/data \
    --volume=$HOME/neo4j/import:/import \
    --user="$(id -u):$(id -g)" \
    neo4j:{neo4j-version-exact} \
neo4j-admin import --nodes=Movies=/import/movies_header.csv,/import/movies.csv \
--nodes=Actors=/import/actors_header.csv,/import/actors.csv \
--relationships=ACTED_IN=/import/roles_header.csv,/import/roles.csv
----

[[docker-neo4j-memrec]]
== Use Neo4j Admin for memory recommendations

The xref:tools/neo4j-admin/neo4j-admin-memrec.adoc[neo4j-admin memrec] command with the argument `--docker` outputs environmental variables that can be passed to a Neo4j docker container.
The recommended use is to save the generated environment variables to a file and pass the file to a docker container using the `--env-file` docker option.
The following example shows how `neo4j-admin memrec --docker` provides a memory recommendation in a docker-friendly format.

.Invoke `neo4j-admin memrec --docker`
====
[source, shell]
----
$neo4j-home> bin/neo4j-admin memrec --memory=16g --docker

...
...
...
# Based on the above, the following memory settings are recommended:
NEO4J_dbms_memory_heap_initial__size=5g
NEO4J_dbms_memory_heap_max__size=5g
NEO4J_dbms_memory_pagecache_size=7g
----
====

[[docker-cypher-shell]]
== Use Cypher Shell

The xref:tools/cypher-shell.adoc[Neo4j Cypher Shell tool] can be run locally within a container using the following command:

[source, shell]
----
docker exec --interactive --tty <containerID/name> cypher-shell <options>
----

For more information about the `cypher-shell` syntax and options, see xref:tools/cypher-shell.adoc#cypher-shell-syntax[Syntax].

[[docker-cypher-shell-example]]
=== Retrieve data from a database in a Neo4j Docker container

The following is an example of how to use the `cypher-shell` command to retrieve data from the `neo4j` database.

. Run a new container, mounting the same volume _/data_ as in the xref:docker/operations.adoc#docker-import-example[import example].
+
[source, shell, subs="attributes,specialchars"]
----
docker run --interactive --tty --name <containerID/name> \
    --publish=7474:7474 --publish=7687:7687 \
    --volume=$HOME/neo4j/data:/data \
    --user="$(id -u):$(id -g)" \
    neo4j:{neo4j-version-exact}
----

. Use the container ID or name to get into the container, and then, run the `cypher-shell` command and authenticate.
+
[source, shell]
----
docker exec --interactive --tty <containerID/name> cypher-shell -u neo4j -p <password>
----

. Retrieve some data.
+
[source, shell]
----
neo4j@neo4j> match (n:Actors)-[r]->(m:Movies) return n.name AS Actors, m.title AS Movies, m.year AS MovieYear;
+-------------------------------------------------------------+
| Actors               | Movies                   | MovieYear |
+-------------------------------------------------------------+
| "Keanu Reeves"       | "The Matrix Revolutions" | 2003      |
| "Keanu Reeves"       | "The Matrix Reloaded"    | 2003      |
| "Keanu Reeves"       | "The Matrix"             | 1999      |
| "Laurence Fishburne" | "The Matrix Revolutions" | 2003      |
| "Laurence Fishburne" | "The Matrix Reloaded"    | 2003      |
| "Laurence Fishburne" | "The Matrix"             | 1999      |
| "Carrie-Anne Moss"   | "The Matrix Revolutions" | 2003      |
| "Carrie-Anne Moss"   | "The Matrix Reloaded"    | 2003      |
| "Carrie-Anne Moss"   | "The Matrix"             | 1999      |
+-------------------------------------------------------------+

9 rows available after 61 ms, consumed after another 7 ms
----

[[docker-cypher-shell-script]]
=== Pass a Cypher script file to a Neo4j Docker container

There are different ways to pass a Cypher script file to a Neo4j Docker container, all of them using the Cypher Shell tool.

* Using the `--file` option of the `cypher-shell` command followed by the file name.
After the statements are executed `cypher-shell` shuts down.

* Using the `:source` command followed by the file name when in the Cypher interactive shell.

* Using the commands `cat` or `curl` with `cypher-shell` to pipe the contents of your script file into your container.

[NOTE]
====
To use the `--file` option or the `:source` command of Cypher Shell, the Cypher script file must be readable from inside the container, otherwise `cypher-shell` will not be able to open the file.
The folder containing the examples must be mounted to the container when the container is started.
====

The following are syntax examples of how to use these commands:

._example.cypher_ script
[source, shell]
----
match (n:Actors)-[r]->(m:Movies) return n.name AS Actors, m.title AS Movies, m.year AS MovieYear;
----

.Invoke `cypher-shell` with the `--file` option
[source, shell, subs="attributes"]
----
# Put the example.cypher file in the local folder ./examples.

# Start a Neo4j container and mount the ./examples folder inside the container:

docker run --rm \
--volume /path/to/local/examples:/examples \
--publish=7474:7474 \
--publish=7687:7687 \
--env NEO4J_AUTH=neo4j/<password> \
neo4j:{neo4j-version-exact}

# Run the Cypher Shell tool with the --file option passing the example.cypher file:

docker exec --interactive --tty <containerID/name> cypher-shell -u neo4j -p <password> --file /examples/example.cypher
----

.Use the `:source` command to run a Cypher script file
[source, shell, subs="attributes"]
----
# Put the example.cypher file in the local folder ./examples.

# Start a Neo4j container and mount the ./examples folder inside the container:

docker run --rm \
--volume /path/to/local/examples:/examples \
--publish=7474:7474 \
--publish=7687:7687 \
--env NEO4J_AUTH=neo4j/<password> \
neo4j:{neo4j-version-exact}

# Use the container ID or name to get into the container, and then, run the cypher-shell command and authenticate.

docker exec --interactive --tty <containerID/name> cypher-shell -u neo4j -p <password>

# Invoke the :source command followed by the file name.

neo4j@neo4j> :source example.cypher
----

.Invoke `curl` with Cypher Shell
[source, shell]
----
curl http://mysite.com/config/example.cypher | sudo docker exec --interactive <containerID/name> cypher-shell -u neo4j -p <password>
----

.Invoke `cat` with Cypher Shell
[source, shell]
----
cat example.cypher | sudo  docker exec --interactive  <containerID/name> cypher-shell -u neo4j -p <password>
----

.Example output
[source, shell, role="noheader"]
----
Actors, Movies, MovieYear
"Keanu Reeves", "The Matrix Revolutions", 2003
"Keanu Reeves", "The Matrix Reloaded", 2003
"Keanu Reeves", "The Matrix", 1999
"Laurence Fishburne", "The Matrix Revolutions", 2003
"Laurence Fishburne", "The Matrix Reloaded", 2003
"Laurence Fishburne", "The Matrix", 1999
"Carrie-Anne Moss", "The Matrix Revolutions", 2003
"Carrie-Anne Moss", "The Matrix Reloaded", 2003
"Carrie-Anne Moss", "The Matrix", 1999
----

These commands take the contents of the script file and pass it into the Docker container using Cypher Shell.
Then, they run a Cypher example, `LOAD CSV` dataset, which might be hosted somewhere on a server (with `curl`), create indexes, constraints, or do other administrative operations.

[[docker-procedures]]
== Install user-defined procedures

To install link:{neo4j-docs-base-uri}/java-reference/{page-version}/extending-neo4j/procedures#extending-neo4j-procedures[user-defined procedures], mount the _/plugins_ volume containing the jars.

[source, shell, subs="attributes"]
----
docker run --publish=7474:7474 --publish=7687:7687 --volume=$HOME/neo4j/plugins:/plugins neo4j:{neo4j-version-exact}
----

[[docker-neo4jlabs-plugins]]
== Configure Neo4j Labs plugins

The Neo4j Docker image includes a startup script which can automatically download and configure certain Neo4j plugins at runtime.

[NOTE]
====
This feature is intended to facilitate using Neo4j Labs plugins in development environments, but it is not recommended for use in production environments.

To use plugins in production with Neo4j Docker containers, see xref:docker/operations.adoc#docker-procedures[Install user-defined procedures].
====

The `NEO4JLABS_PLUGINS` environment variable can be used to specify the plugins to install using this method.
This should be set to a JSON-formatted list of supported plugins.

For example, to install the APOC plugin (`apoc`), you can use the Docker argument;

[source, argument, role=noheader]
----
--env NEO4JLABS_PLUGINS='["apoc"]'
----

and run the following command:

[source, shell, subs="attributes"]
----
docker run -it --rm \
  --publish=7474:7474 --publish=7687:7687 \
  --user="$(id -u):$(id -g)" \
  -e NEO4J_AUTH=none \
  --env NEO4JLABS_PLUGINS='["apoc"]' \
  neo4j:{neo4j-version-exact}
----

For example, to install the APOC plugin (`apoc`) and the Neo Semantics plugin (`n10s`), you can use the following Docker argument:

[source, argument, role=noheader]
----
--env NEO4JLABS_PLUGINS='["apoc", "n10s"]'
----

.Supported Neo4j Labs plugins
[options="header",cols="d,m,a"]
|===
|Name |Key  |Further information

| APOC
| `apoc`
| https://neo4j.com/labs/apoc/4.4/[APOC Full]

| APOC Core
| `apoc-core`
| https://neo4j.com/labs/apoc/4.4/[APOC Core]

| Bloom
| `bloom`
| link:{neo4j-docs-base-uri}/bloom-user-guide[Neo4j Bloom]

| Streams
| `streams`
| link:{neo4j-docs-base-uri}/kafka-streams[Neo4j Streaming Data Integrations User Guide]

| Graph Data Science
| `graph-data-science`
| link:{neo4j-docs-base-uri}/graph-data-science[Graph Data Science]

| Neo Semantics
| `n10s`
| https://neo4j.com/labs/nsmtx-rdf/
|===

[NOTE]
====
Running Bloom in a Docker container requires Neo4j Docker image 4.2.3-enterprise or later.
====
