[[docker-operations]]
= Docker specific operations
:description: This chapter describes various operations that are specific to running Neo4j in a Docker container. 


[[docker-procedures]]
== Using _/plugins_

To install user-defined procedures, provide a _/plugins_ volume containing the jars.

[source, shell, subs="attributes"]
----
docker run --publish=7474:7474 --publish=7687:7687 --volume=$HOME/neo4j/plugins:/plugins neo4j:{neo4j-version}
----

See link:{neo4j-docs-base-uri}/java-reference/{page-version}/extending-neo4j/procedures#extending-neo4j-procedures[Java Reference -> Procedures] for more details on procedures.


[[docker-cypher-shell]]
== Using Cypher Shell

The Neo4j Shell can be run locally within a container using a command like this:

[source, shell]
----
docker exec --interactive --tty <container> bin/cypher-shell
----

To determine the _<container>_, you can run `docker ps` to list the currently running Docker containers.
From the results, use the `CONTAINER ID` in place of _<container>_.

To pass a local file into Cypher Shell, you can run the following, again using the `CONTAINER ID` identified above to replace _<container>_:

[source, bash]
----
cat <local-file> | sudo docker exec --interactive <container> bin/cypher-shell -u <username> -p <password>
----

When you run the above, the contents of the _<local-file>_ will be passed into the Docker container.

It will then run `bin/cypher-shell`, and authenticate with the provided _<username>_ and _<password>_.

For more information on using Cypher Shell, see xref:tools/cypher-shell.adoc[Cypher Shell].


[[docker-upgrading]]
== Upgrading Neo4j on Docker

To enable upgrades, set `+NEO4J_dbms_allow__upgrade+` to `true`.
For more details on upgrading, see:

* xref:upgrade/deployment-upgrading.adoc[Single-instance upgrade]
* xref:upgrade/causal-cluster.adoc[Upgrade a Neo4j Causal Cluster]
// * <<ha-upgrade-guide, Upgrade a Neo4j HA cluster>>
