:description: How to use Neo4j tools when running Neo4j in a Docker container.
[[docker-operations]]
= Docker-specific operations

You can use the Neo4j tools when running Neo4j in a Docker container.

[[docker-neo4j-admin]]
== Use Neo4j Admin

The xref:neo4j-admin-neo4j-cli.adoc[`neo4j-admin` CLI] can be run locally within a container using the following command:

[source, shell]
----
docker exec --interactive --tty <containerID/name> neo4j-admin <category> <command>
----

To determine the container ID or name, run `docker ps` to list the currently running Docker containers.

For more information about the `neo4j-admin` commands, see xref:neo4j-admin-neo4j-cli.adoc[].

[[docker-neo4j-import]]
== Use Neo4j Import

The xref:import.adoc[Neo4j Import tool] can be run locally within a container using the following commands:

[source, shell]
----
docker exec --interactive --tty <containerID/name> neo4j-admin database import full <options>
----

and

[source, shell]
----
docker exec --interactive --tty <containerID/name> neo4j-admin database import incremental <options>
----

For more information about the commands' syntax and options, see xref:import.adoc#import-tool-full[Full import] and xref:import.adoc#import-tool-incremental[Incremental import].

[discrete]
[[docker-import-prerequisites]]
=== Prerequisites

* Verify that you have created the folders that you want to mount as volumes to the Neo4j docker container.
* Verify that the CSV files that you want to load into Neo4j are formatted as per xref:import.adoc#import-tool-header-format[CSV header format].
* Verify that you have added the CSV files to the folder that will be mounted to _/import_ in your container.

[discrete]
[[docker-import-example]]
=== Import CSV files into the Neo4j Docker container using the Neo4j import tool

This is an example of how to start a container with mounted volumes _/data_ and _/import_, to ensure the persistence of the data in them, and load the CSV files using the `neo4j-admin database import full` command.
You can add the flag `--rm` to automatically remove the container's file system when the container exits.

[source, shell, subs="attributes"]
----
docker run --interactive --tty --rm \
    --publish=7474:7474 --publish=7687:7687 \
    --volume=$HOME/neo4j/data:/data \
    --volume=$HOME/neo4j/import:/import \
    neo4j:{neo4j-version-exact} \
neo4j-admin database import full --nodes=Movies=/import/movies_header.csv,/import/movies.csv \
--nodes=Actors=/import/actors_header.csv,/import/actors.csv \
--relationships=ACTED_IN=/import/roles_header.csv,/import/roles.csv databasename
----

[[docker-neo4j-memrec]]
== Use Neo4j Admin for memory recommendations

The xref:configuration/neo4j-admin-memrec.adoc[neo4j-admin server memory-recommendation] command with the argument `--docker` outputs environmental variables that can be passed to a Neo4j docker container.
The following example shows how `neo4j-admin server memory-recommendation --docker` provides a memory recommendation in a docker-friendly format.

.Invoke `neo4j-admin server memory-recommendation --docker`
====
[source, shell]
----
bin/neo4j-admin server memory-recommendation --memory=16g --docker

...
...
...
# Based on the above, the following memory settings are recommended:
NEO4J_server_memory_heap_initial__size='5g'
NEO4J_server_memory_heap_max__size='5g'
NEO4J_server_memory_pagecache_size='7g'
#
# It is also recommended turning out-of-memory errors into full crashes,
# instead of allowing a partially crashed database to continue running:
NEO4J_server_jvm_additional='-XX:+ExitOnOutOfMemoryError'
#
...
...
----
====

[[docker-neo4j-admin-report]]
== Use Neo4j Admin report

The xref:monitoring/neo4j-admin-report.adoc[Neo4j Admin report tool] generates a report of the status of a running Neo4j database. +
In a containerized environment, its command `neo4j-admin server report` must be invoked using the script `neo4j-admin-report`.
This ensures that the reporter is running with all the necessary file permissions required to analyze the running Neo4j processes.
This script takes all the arguments of the `neo4j-admin server report` command.


[NOTE]
====
It is possible to use `docker exec` to run `neo4j-admin server report` directly inside the container, but the file permissions required to access running processes _and_ to write files to a mounted folder can be conflicting.

The `neo4j-admin-report` script is just a wrapper around `neo4j-admin server report` which automatically handles most permission problems.
====

.Example of getting a Neo4j report from a containerised Neo4j database
====
Start a Neo4j container and mount a folder for storing the reports.
[source, shell, subs="attributes+,+macros"]
----
docker run --interactive --tty --rm \
    --name=neo4j \
    --publish=7474:7474 --publish=7687:7687 \
    --volume=$HOME/neo4j/data:/data \
    --volume=$HOME/neo4j/reports:/reports \ # <1>
    neo4j:{neo4j-version-exact}
----
<1> The output folder for the reports.


Then, using `docker exec`, run the `neo4j-admin-report` wrapper script, specifying the output directory for the reports.

[source, shell, subs="attributes+,+macros"]
----
docker exec --interactive --tty <containerID/name> \
    neo4j-admin-report \
        --to-path=/reports \ # <1>
----
<1> If no `--to-path` option is specified, the reports will be written to `/tmp/reports`.

The `$HOME/neo4j/reports` folder should now contain a zip file of reports.
====



[[docker-cypher-shell]]
== Use Cypher Shell

The xref:cypher-shell.adoc[] can be run locally within a container using the following command:

[source, shell]
----
docker exec --interactive --tty <containerID/name> cypher-shell <options>
----

For more information about the `cypher-shell` syntax and options, see xref:cypher-shell.adoc[]#cypher-shell-syntax[Syntax].

[[docker-cypher-shell-example]]
=== Retrieve data from a database in a Neo4j Docker container

The following is an example of how to use the `cypher-shell` command to retrieve data from the `neo4j` database.

. Run a new container, mounting the same volume _/data_ as in the xref:docker/operations.adoc#docker-import-example[import example].
+
[source, shell, subs="attributes,specialchars"]
----
docker run --interactive --tty --name <containerID/name> \
    --publish=7474:7474 --publish=7687:7687 \
    --volume=$HOME/neo4j/data:/data \
    neo4j:{neo4j-version-exact}
----

. Use the container ID or name to get into the container, and then, run the `cypher-shell` command and authenticate.
+
[source, shell]
----
docker exec --interactive --tty <containerID/name> cypher-shell -u neo4j -p <password>
----

. Retrieve some data.
+
[source, shell]
----
neo4j@neo4j> match (n:Actors)-[r]->(m:Movies) return n.name AS Actors, m.title AS Movies, m.year AS MovieYear;
+-------------------------------------------------------------+
| Actors               | Movies                   | MovieYear |
+-------------------------------------------------------------+
| "Keanu Reeves"       | "The Matrix Revolutions" | 2003      |
| "Keanu Reeves"       | "The Matrix Reloaded"    | 2003      |
| "Keanu Reeves"       | "The Matrix"             | 1999      |
| "Laurence Fishburne" | "The Matrix Revolutions" | 2003      |
| "Laurence Fishburne" | "The Matrix Reloaded"    | 2003      |
| "Laurence Fishburne" | "The Matrix"             | 1999      |
| "Carrie-Anne Moss"   | "The Matrix Revolutions" | 2003      |
| "Carrie-Anne Moss"   | "The Matrix Reloaded"    | 2003      |
| "Carrie-Anne Moss"   | "The Matrix"             | 1999      |
+-------------------------------------------------------------+

9 rows available after 61 ms, consumed after another 7 ms
----

[[docker-cypher-shell-script]]
=== Pass a Cypher script file to a Neo4j Docker container

There are different ways to pass a Cypher script file to a Neo4j Docker container, all of them using the Cypher Shell tool.

* Using the `--file` option of the `cypher-shell` command followed by the file name.
After the statements are executed `cypher-shell` shuts down.

* Using the `:source` command followed by the file name when in the Cypher interactive shell.

* Using the commands `cat` or `curl` with `cypher-shell` to pipe the contents of your script file into your container.

[NOTE]
====
To use the `--file` option or the `:source` command of Cypher Shell, the Cypher script file must be readable from inside the container, otherwise `cypher-shell` will not be able to open the file.
The folder containing the examples must be mounted to the container when the container is started.
====

The following are syntax examples of how to use these commands:

._example.cypher_ script
[source, shell]
----
match (n:Actors)-[r]->(m:Movies) return n.name AS Actors, m.title AS Movies, m.year AS MovieYear;
----

.Invoke `cypher-shell` with the `--file` option
[source, shell, subs="attributes"]
----
# Put the example.cypher file in the local folder ./examples.

# Start a Neo4j container and mount the ./examples folder inside the container:

docker run --rm \
--volume /path/to/local/examples:/examples \
--publish=7474:7474 \
--publish=7687:7687 \
--env NEO4J_AUTH=neo4j/your_password \
neo4j:{neo4j-version-exact}

# Run the Cypher Shell tool with the --file option passing the example.cypher file:

docker exec --interactive --tty <containerID/name> cypher-shell -u neo4j -p <password> --file /examples/example.cypher
----

.Use the `:source` command to run a Cypher script file
[source, shell, subs="attributes"]
----
# Put the example.cypher file in the local folder ./examples.

# Start a Neo4j container and mount the ./examples folder inside the container:

docker run --rm \
--volume /path/to/local/examples:/examples \
--publish=7474:7474 \
--publish=7687:7687 \
--env NEO4J_AUTH=neo4j/your_password \
neo4j:{neo4j-version-exact}

# Use the container ID or name to get into the container, and then, run the cypher-shell command and authenticate.

docker exec --interactive --tty <containerID/name> cypher-shell -u neo4j -p <password>

# Invoke the :source command followed by the file name.

neo4j@neo4j> :source example.cypher
----

.Invoke `curl` with Cypher Shell
[source, shell]
----
curl http://mysite.com/config/example.cypher | sudo docker exec --interactive <containerID/name> cypher-shell -u neo4j -p <password>
----

.Invoke `cat` with Cypher Shell
[source, shell]
----
cat example.cypher | sudo  docker exec --interactive  <containerID/name> cypher-shell -u neo4j -p <password>
----

.Example output
[source, shell, role="noheader"]
----
Actors, Movies, MovieYear
"Keanu Reeves", "The Matrix Revolutions", 2003
"Keanu Reeves", "The Matrix Reloaded", 2003
"Keanu Reeves", "The Matrix", 1999
"Laurence Fishburne", "The Matrix Revolutions", 2003
"Laurence Fishburne", "The Matrix Reloaded", 2003
"Laurence Fishburne", "The Matrix", 1999
"Carrie-Anne Moss", "The Matrix Revolutions", 2003
"Carrie-Anne Moss", "The Matrix Reloaded", 2003
"Carrie-Anne Moss", "The Matrix", 1999
----

These commands take the contents of the script file and pass it into the Docker container using Cypher Shell.
Then, they run a Cypher example, `LOAD CSV` dataset, which might be hosted somewhere on a server (with `curl`), create indexes, constraints, or do other administrative operations.

