[[configuration-settings]]
= Configuration settings
:description: This page provides a complete reference to the Neo4j configuration settings.
:page-styles: hide-table-captions

This page provides a complete reference to the Neo4j configuration settings, which can be set in xref::/configuration/file-locations.adoc#file-locations[_neo4j.conf_].
Refer to xref:configuration/neo4j-conf.adoc#_configuration_settings[The neo4j.conf file] for details on how to use configuration settings.


== Dynamic configuration settings

Dynamic settings can be changed at runtime, without restarting the service.

Dynamic settings are labeled label:dynamic[].

[NOTE]
====
Changes to the configuration at runtime are not persisted.
To avoid losing changes when restarting Neo4j, make sure you update xref:configuration/file-locations.adoc[_neo4j.conf_] as well.

In a clustered environment, `CALL dbms.setConfigValue` affects only the server it is run against, and it is not propagated to other members.
If you want to change the configuration settings on all cluster members, you have to run the procedure against each of them and update their _neo4j.conf_ file.

Each member of the cluster has its own _neo4j.conf_ file.
It is recommended that the settings for a database are the same across all members of the cluster.
====

For more information on how to update dynamic configuration settings, see xref:configuration/dynamic-settings.adoc[Update dynamic settings].


== Checkpoint settings

Checkpointing is the process of flushing all pending page updates from the page cache to the store files.
This is done periodically and is used to recover the database in case of a crash.
The checkpoint settings control the frequency of checkpoints, and the amount of data that is written to disk in each checkpoint.
//For more information, see <<Checkpointing>>.
See also, <<Transaction log settings>>.

[[config_db.checkpoint]]
=== `db.checkpoint`

.db.checkpoint
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Configures the general policy for when checkpoints should occur.
Possible values are:

* `PERIODIC` (default)- it runs a checkpoint as per the interval specified by `<<config_db.checkpoint.interval.tx,db.checkpoint.interval.tx>>` and `<<config_db.checkpoint.interval.time,db.checkpoint.interval.time>>`.

* `VOLUME` -- it runs a checkpoint when the size of the transaction logs reaches the value specified by the `<<config_db.checkpoint.interval.volume,db.checkpoint.interval.volume>>` setting. By default, it is set to `250.00MiB`.

* `CONTINUOUS` (Enterprise Edition) -- it ignores `<<config_db.checkpoint.interval.tx,db.checkpoint.interval.tx>>` and `<<config_db.checkpoint.interval.time,db.checkpoint.interval.time>>` settings and runs the checkpoint process all the time.

* `VOLUMETRIC` (Enterprise Edition) -- it makes the best effort to checkpoint often enough so that the database does not get too far behind on deleting old transaction logs as specified in the `<<config_db.tx_log.rotation.retention_policy,db.tx_log.rotation.retention_policy>>` setting.
|Valid values
a|One of [PERIODIC, CONTINUOUS, VOLUME, VOLUMETRIC].
|Default value
m|+++PERIODIC+++
|===


[[config_db.checkpoint.interval.time]]
=== `db.checkpoint.interval.time`

.db.checkpoint.interval.time
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Configures the time interval between checkpoints.
The database does not checkpoint more often than the specified interval (unless checkpointing is triggered by a different event) but might checkpoint less often if performing a checkpoint takes longer time than the configured interval.
A checkpoint is a point in the transaction logs from which recovery starts.
Longer checkpoint intervals typically mean that recovery takes longer to complete in case of a crash.
On the other hand, a longer checkpoint interval can also reduce the I/O load that the database places on the system, as each checkpoint implies a flushing and forcing of all the store files.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++15m+++
|===


[[config_db.checkpoint.interval.tx]]
=== `db.checkpoint.interval.tx`

.db.checkpoint.interval.tx
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Configures the transaction interval between checkpoints.
The database does not checkpoint more often than the specified interval (unless checkpointing is triggered by a different event) but might checkpoint less often if performing a checkpoint takes longer time than the configured interval.
A checkpoint is a point in the transaction logs from which recovery starts.
Longer checkpoint intervals typically mean that recovery takes longer to complete in case of a crash.
On the other hand, a longer checkpoint interval can also reduce the I/O load that the database places on the system, as each checkpoint implies a flushing and forcing of all the store files.
The default is `100000` for a checkpoint every 100000 transactions.
|Valid values
a|An integer that is minimum `1`.
|Default value
m|+++100000+++
|===


[[config_db.checkpoint.interval.volume]]
=== `db.checkpoint.interval.volume`

.db.checkpoint.interval.volume
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Configures the volume of transaction logs between checkpoints.
The database does not checkpoint more often than the specified interval (unless checkpointing is triggered by a different event) but might checkpoint less often if performing a checkpoint takes longer time than the configured interval.
A checkpoint is a point in the transaction logs, which recovery would start from.
Longer checkpoint intervals typically mean that recovery takes longer to complete in case of a crash.
On the other hand, a longer checkpoint interval can also reduce the I/O load that the database places on the system, as each checkpoint implies a flushing and forcing of all the store files.
|Valid values
a|A byte size (valid multipliers are `B`, `KiB`, `KB`, `K`, `kB`, `kb`, `k`, `MiB`, `MB`, `M`, `mB`, `mb`, `m`, `GiB`, `GB`, `G`, `gB`, `gb`, `g`, `TiB`, `TB`, `PiB`, `PB`, `EiB`, `EB`) that is minimum `1.00KiB`.
|Default value
m|+++250.00MiB+++
|===


[role=label--dynamic]
[[config_db.checkpoint.iops.limit]]
=== `db.checkpoint.iops.limit`

label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.db.checkpoint.iops.limit
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Limit the number of IOs the background checkpoint process consumes per second.
This setting is advisory.
It is ignored in Neo4j Community Edition and is followed to best effort in Enterprise Edition.
An IO is, in this case, an 8 KiB (mostly sequential) write.
Limiting the write IO in this way leaves more bandwidth in the IO subsystem to service random-read IOs, which is important for the response time of queries when the database cannot fit entirely in memory.
The only drawback of this setting is that longer checkpoint times may lead to slightly longer recovery times in case of a database or system crash.
A lower number means lower IO pressure and, consequently, longer checkpoint times.
Set this to `-1` to disable the IOPS limit and remove the limitation entirely.
This lets the checkpointer flush data as fast as the hardware goes.
Removing or commenting out the setting sets the default value of `600`.
|Valid values
a|An integer.
|Default value
m|+++600+++
|===


== Cluster settings

The cluster settings are used to configure the behavior of a Neo4j cluster.
For more information, see also xref:clustering/settings.adoc[Clustering settings].


[role=label--enterprise-edition]
[[config_db.cluster.catchup.pull_interval]]
=== `db.cluster.catchup.pull_interval`

// label:enterprise-edition[Enterprise Edition]

.db.cluster.catchup.pull_interval
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The interval at which a secondary server fetches updates for a specific database from the primary server for that database.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++1s+++
|===


[role=label--enterprise-edition]
[[config_db.cluster.raft.apply.buffer.max_bytes]]
=== `db.cluster.raft.apply.buffer.max_bytes`

// label:enterprise-edition[Enterprise Edition]

.db.cluster.raft.apply.buffer.max_bytes
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The maximum number of bytes in the apply buffer. This parameter limits the amount of memory that can be consumed by the apply buffer. If the bytes limit is reached, buffer size will be limited even if max_entries is not exceeded.
|Valid values
a|A byte size (valid multipliers are `B`, `KiB`, `KB`, `K`, `kB`, `kb`, `k`, `MiB`, `MB`, `M`, `mB`, `mb`, `m`, `GiB`, `GB`, `G`, `gB`, `gb`, `g`, `TiB`, `TB`, `PiB`, `PB`, `EiB`, `EB`).
|Default value
m|+++1.00GiB+++
|===


[role=label--enterprise-edition]
[[config_db.cluster.raft.apply.buffer.max_entries]]
=== `db.cluster.raft.apply.buffer.max_entries`

// label:enterprise-edition[Enterprise Edition]

.db.cluster.raft.apply.buffer.max_entries
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The maximum number of entries in the raft log entry prefetch buffer.
|Valid values
a|An integer.
|Default value
m|+++1024+++
|===


[role=label--enterprise-edition]
[[config_db.cluster.raft.in_queue.batch.max_bytes]]
=== `db.cluster.raft.in_queue.batch.max_bytes`

// label:enterprise-edition[Enterprise Edition]

.db.cluster.raft.in_queue.batch.max_bytes
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Largest batch processed by RAFT in bytes.
|Valid values
a|A byte size (valid multipliers are `B`, `KiB`, `KB`, `K`, `kB`, `kb`, `k`, `MiB`, `MB`, `M`, `mB`, `mb`, `m`, `GiB`, `GB`, `G`, `gB`, `gb`, `g`, `TiB`, `TB`, `PiB`, `PB`, `EiB`, `EB`).
|Default value
m|+++8.00MiB+++
|===


[role=label--enterprise-edition]
[[config_db.cluster.raft.in_queue.max_bytes]]
=== `db.cluster.raft.in_queue.max_bytes`

// label:enterprise-edition[Enterprise Edition]

.db.cluster.raft.in_queue.max_bytes
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Maximum number of bytes in the RAFT in-queue.
|Valid values
a|A byte size (valid multipliers are `B`, `KiB`, `KB`, `K`, `kB`, `kb`, `k`, `MiB`, `MB`, `M`, `mB`, `mb`, `m`, `GiB`, `GB`, `G`, `gB`, `gb`, `g`, `TiB`, `TB`, `PiB`, `PB`, `EiB`, `EB`).
|Default value
m|+++2.00GiB+++
|===


[role="label--enterprise-edition label--deprecated-5.4"]
[[config_db.cluster.raft.leader_transfer.priority_group]]
=== `db.cluster.raft.leader_transfer.priority_group`

// label:enterprise-edition[Enterprise Edition] label:deprecated[Deprecated in 5.4]

.db.cluster.raft.leader_transfer.priority_group
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The name of a server_group whose members should be prioritized as leaders. This does not guarantee that the leader will always be a member of this group, but the cluster will attempt to transfer the leadership to such a member when possible. If a database is specified using `db.cluster.raft.leader_transfer.priority_group.<database>`, the specified priority group will apply to that database only. If no database is specified, that group will be the default and apply to all databases with no explicitly set priority group. Using this setting will disable leadership balancing.
|Valid values
a|A string identifying a server tag.
|Default value
m|++++++
|===


[role=label--enterprise-edition]
[[config_db.cluster.raft.leader_transfer.priority_tag]]
=== `db.cluster.raft.leader_transfer.priority_tag`

// label:enterprise-edition[Enterprise Edition]

.db.cluster.raft.leader_transfer.priority_tag
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The name of a server tag whose members should be prioritized as leaders. This does not guarantee that the leader will always be a member of this tag, but the cluster will attempt to transfer the leadership to such a member when possible. If a database is specified using `db.cluster.raft.leader_transfer.priority_tag`.<database>, the specified priority tag will apply only to that database. If no database is specified, that tag will be the default and apply to all databases with no explicitly set priority tag. Using this setting will disable leadership balancing.
|Valid values
a|A string identifying a server tag.
|Default value
m|++++++
|===


[role=label--enterprise-edition]
[[config_db.cluster.raft.log.prune_strategy]]
=== `db.cluster.raft.log.prune_strategy`

// label:enterprise-edition[Enterprise Edition]

.db.cluster.raft.log.prune_strategy
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|RAFT log pruning strategy that determines which logs are to be pruned. Neo4j only prunes log entries up to the last applied index, which guarantees that logs are only marked for pruning once the transactions within are safely copied over to the local transaction logs and safely committed by a majority of cluster members. Possible values are a byte size or a number of transactions (e.g., 200K txs).
|Valid values
a|A string.
|Default value
m|+++1g size+++
|===


[role=label--enterprise-edition]
[[config_db.cluster.raft.log_shipping.buffer.max_bytes]]
=== `db.cluster.raft.log_shipping.buffer.max_bytes`

// label:enterprise-edition[Enterprise Edition]

.db.cluster.raft.log_shipping.buffer.max_bytes
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The maximum number of bytes in the in-flight cache. This parameter limits the amount of memory that can be consumed by the cache. If the bytes limit is reached, cache size will be limited even if max_entries is not exceeded.
|Valid values
a|A byte size (valid multipliers are `B`, `KiB`, `KB`, `K`, `kB`, `kb`, `k`, `MiB`, `MB`, `M`, `mB`, `mb`, `m`, `GiB`, `GB`, `G`, `gB`, `gb`, `g`, `TiB`, `TB`, `PiB`, `PB`, `EiB`, `EB`).
|Default value
m|+++1.00GiB+++
|===


[role=label--enterprise-edition]
[[config_db.cluster.raft.log_shipping.buffer.max_entries]]
=== `db.cluster.raft.log_shipping.buffer.max_entries`

// label:enterprise-edition[Enterprise Edition]

.db.cluster.raft.log_shipping.buffer.max_entries
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The maximum number of entries in the in-flight cache. Increasing size requires more memory but might improve performance in high-load situations.
|Valid values
a|An integer.
|Default value
m|+++1024+++
|===


[role=label--enterprise-edition]
[[config_dbms.cluster.catchup.client_inactivity_timeout]]
=== `dbms.cluster.catchup.client_inactivity_timeout`

// label:enterprise-edition[Enterprise Edition]

.dbms.cluster.catchup.client_inactivity_timeout
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The catch-up protocol times out if the given duration elapses with no network activity. Every message received by the client from the server extends the timeout duration.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++10m+++
|===


[role=label--enterprise-edition]
[[config_dbms.cluster.discovery.endpoints]]
=== `dbms.cluster.discovery.endpoints`

// label:enterprise-edition[Enterprise Edition]

.dbms.cluster.discovery.endpoints
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|A comma-separated list of endpoints that a server should contact in order to discover other cluster members.
Typically, all members of the cluster, including the current server, should be specified in this list.
|Valid values
a|A comma-separated list where each element is a socket address in the format of `hostname:port`, `hostname`, or `:port`.
|Default value
m|
|===


[role=label--enterprise-edition]
[[config_dbms.cluster.discovery.log_level]]
=== `dbms.cluster.discovery.log_level`

// label:enterprise-edition[Enterprise Edition]

.dbms.cluster.discovery.log_level
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The level of middleware logging.
|Valid values
a|One of [DEBUG, INFO, WARN, ERROR, NONE].
|Default value
m|+++WARN+++
|===


[role=label--enterprise-edition]
[[config_dbms.cluster.discovery.resolver_type]]
=== `dbms.cluster.discovery.resolver_type`

// label:enterprise-edition[Enterprise Edition]

.dbms.cluster.discovery.resolver_type
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Configure the resolver type that the discovery service uses for determining who should be part of the cluster.
Valid values are `LIST`, `SRV`, `DNS`, and `K8S`:

`LIST`::
 A static configuration where `dbms.cluster.discovery.endpoints` must contain a list of the addresses of the cluster members.
`SRV` and `DNS`::
 A dynamic configuration where `dbms.cluster.discovery.endpoints` must point to a DNS entry containing the cluster members' addresses.
`K8S`::
 At least `dbms.kubernetes.service_port_name` must be set.  The addresses of the cluster members are queried dynamically from Kubernetes.
|Valid values
a|A string.
|Default value
m|+++LIST+++
|===


[role="label--enterprise-edition deprecated-5.7"]
[[conifg_]]
=== `dbms.cluster.discovery.type`

// label:enterprise-edition[Enterprise Edition] label:deprecated[Deprecated in 5.7]

.dbms.cluster.discovery.type
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|This setting has been replaced by `dbms.cluster.discovery.resolver_type`.
|Valid values
a|One of [DNS, LIST, SRV, K8S].
|Default value
m|+++LIST+++
|===


[[config_dbms.cluster.discovery.verification_timeout]]


[role=label--enterprise-edition]
[[config_dbms.cluster.minimum_initial_system_primaries_count]]
=== `dbms.cluster.minimum_initial_system_primaries_count`

// label:enterprise-edition[Enterprise Edition]

.dbms.cluster.minimum_initial_system_primaries_count
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Minimum number of machines initially required to form a clustered DBMS. The cluster is considered formed when at least this many members have discovered each other, bound together, and bootstrapped a highly available system database. As a result, at least this many of the cluster's initial machines must have `<<config_server.cluster.system_database_mode,server.cluster.system_database_mode>>` set to `PRIMARY`. +
NOTE: If `<<config_dbms.cluster.discovery.resolver_type,dbms.cluster.discovery.resolver_type>>` is set to `LIST` and `<<config_dbms.cluster.discovery.endpoints,dbms.cluster.discovery.endpoints>>` is empty, then the user is assumed to be deploying a standalone DBMS, and the value of this setting is ignored.
|Valid values
a|An integer that is minimum `1`.
|Default value
m|+++3+++
|===


[role=label--enterprise-edition label--dynamic label--new-5.17]
[[config_dbms.cluster.network.connect_timeout]]
=== `dbms.cluster.network.connect_timeout`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic] label:new[Introduced in 5.17]

.dbms.cluster.network.connect_timeout
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The maximum amount of time to wait for a network connection to be established.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++30s+++
|===


[role=label--enterprise-edition]
[[config_dbms.cluster.network.handshake_timeout]]
=== `dbms.cluster.network.handshake_timeout`

// label:enterprise-edition[Enterprise Edition]

.dbms.cluster.network.handshake_timeout
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Time out for protocol negotiation handshake.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++20s+++
|===


[role=label--enterprise-edition]
[[config_dbms.cluster.network.max_chunk_size]]
=== `dbms.cluster.network.max_chunk_size`

// label:enterprise-edition[Enterprise Edition]

.dbms.cluster.network.max_chunk_size
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Maximum chunk size allowable across a network by clustering machinery.
|Valid values
a|An integer that is in the range `4096` to `10485760`.
|Default value
m|+++32768+++
|===


[role=label--enterprise-edition]
[[config_dbms.cluster.network.supported_compression_algos]]
=== `dbms.cluster.network.supported_compression_algos`

// label:enterprise-edition[Enterprise Edition]

.dbms.cluster.network.supported_compression_algos
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Network compression algorithms that this instance will allow in negotiation as a comma-separated list. +
For incoming connections, the algorithms are listed in descending order of preference. An empty list implies no compression. +
For outgoing connections, this merely specifies the allowed set of algorithms and the preference of the remote peer will be used for making the decision. +
Allowable values: [Gzip, Snappy, Snappy_validating, LZ4, LZ4_high_compression, LZ_validating, LZ4_high_compression_validating]
|Valid values
a|A comma-separated list where each element is a string.
|Default value
m|++++++
|===


[role=label--enterprise-edition]
[[config_dbms.cluster.raft.binding_timeout]]
=== `dbms.cluster.raft.binding_timeout`

// label:enterprise-edition[Enterprise Edition]

.dbms.cluster.raft.binding_timeout
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The time allowed for a database on a Neo4j server to either join a cluster or form a new cluster with at least the quorum of the members available. The members are provided by `<<config_dbms.cluster.discovery.endpoints,dbms.cluster.discovery.endpoints>>` for the system database and by the topology graph for standard databases.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++1d+++
|===


[role=label--enterprise-edition]
[[config_dbms.cluster.raft.client.max_channels]]
=== `dbms.cluster.raft.client.max_channels`

// label:enterprise-edition[Enterprise Edition]

.dbms.cluster.raft.client.max_channels
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The maximum number of TCP channels between two nodes to operate the raft protocol. Each database gets allocated one channel, but a single channel can be used by more than one database.
|Valid values
a|An integer.
|Default value
m|+++8+++
|===


[role=label--enterprise-edition]
[[config_dbms.cluster.raft.election_failure_detection_window]]
=== `dbms.cluster.raft.election_failure_detection_window`

// label:enterprise-edition[Enterprise Edition]

.dbms.cluster.raft.election_failure_detection_window
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The rate at which leader elections happen. Note that due to election conflicts, it might take several attempts to find a leader. The window should be significantly larger than typical communication delays to make conflicts unlikely.
|Valid values
a|A duration-range <min-max> (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++3s-6s+++
|===


[role=label--enterprise-edition]
[[config_dbms.cluster.raft.leader_failure_detection_window]]
=== `dbms.cluster.raft.leader_failure_detection_window`

// label:enterprise-edition[Enterprise Edition]

.dbms.cluster.raft.leader_failure_detection_window
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The time window within which the loss of the leader is detected and the first re-election attempt is held. The window should be significantly larger than typical communication delays to make conflicts unlikely.
|Valid values
a|A duration-range <min-max> (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++20s-23s+++
|===


[role=label--enterprise-edition]
[[config_dbms.cluster.raft.leader_transfer.balancing_strategy]]
=== `dbms.cluster.raft.leader_transfer.balancing_strategy`

// label:enterprise-edition[Enterprise Edition]

.dbms.cluster.raft.leader_transfer.balancing_strategy
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Which strategy to use when transferring database leaderships around a cluster. Note that if a `leadership_priority_group` is specified for a given database, the value of this setting will be ignored for that database.
The following values are available:

* `equal_balancing` automatically ensures that each primary server holds the leader role for an equal number of databases.
* `no_balancing` prevents any automatic balancing of the leader role.
|Valid values
a|One of [NO_BALANCING, EQUAL_BALANCING].
|Default value
m|+++EQUAL_BALANCING+++
|===


[role=label--enterprise-edition]
[[config_dbms.cluster.raft.log.pruning_frequency]]
=== `dbms.cluster.raft.log.pruning_frequency`

// label:enterprise-edition[Enterprise Edition]

.dbms.cluster.raft.log.pruning_frequency
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|RAFT log pruning frequency.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++10m+++
|===


[role=label--enterprise-edition]
[[config_dbms.cluster.raft.log.reader_pool_size]]
=== `dbms.cluster.raft.log.reader_pool_size`

// label:enterprise-edition[Enterprise Edition]

.dbms.cluster.raft.log.reader_pool_size
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|RAFT log reader pool size.
|Valid values
a|An integer.
|Default value
m|+++8+++
|===


[role=label--enterprise-edition]
[[config_dbms.cluster.raft.log.rotation_size]]
=== `dbms.cluster.raft.log.rotation_size`

// label:enterprise-edition[Enterprise Edition]

.dbms.cluster.raft.log.rotation_size
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|RAFT log rotation size. The log will be rotated when it reaches this size.
|Valid values
a|A byte size (valid multipliers are `B`, `KiB`, `KB`, `K`, `kB`, `kb`, `k`, `MiB`, `MB`, `M`, `mB`, `mb`, `m`, `GiB`, `GB`, `G`, `gB`, `gb`, `g`, `TiB`, `TB`, `PiB`, `PB`, `EiB`, `EB`) that is minimum `1.00KiB`.
|Default value
m|+++250.00MiB+++
|===


[role=label--enterprise-edition]
[[config_dbms.cluster.raft.membership.join_max_lag]]
=== `dbms.cluster.raft.membership.join_max_lag`

// label:enterprise-edition[Enterprise Edition]

.dbms.cluster.raft.membership.join_max_lag
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Maximum amount of lag accepted for a new follower to join the Raft group.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++10s+++
|===


[role=label--enterprise-edition]
[[config_dbms.cluster.raft.membership.join_timeout]]
=== `dbms.cluster.raft.membership.join_timeout`

// label:enterprise-edition[Enterprise Edition]

.dbms.cluster.raft.membership.join_timeout
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Timeout for a new member to catch up.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++10m+++
|===


[role=label--enterprise-edition]
[[config_dbms.cluster.store_copy.max_retry_time_per_request]]
=== `dbms.cluster.store_copy.max_retry_time_per_request`

// label:enterprise-edition[Enterprise Edition]

.dbms.cluster.store_copy.max_retry_time_per_request
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Maximum retry time per request during store copy. Regular store files and indexes are downloaded in separate requests during store copy. This configures the maximum time failed requests are allowed to resend.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++20m+++
|===


[role=label--enterprise-edition label--new-5.10]
[[config_initial.dbms.automatically_enable_free_servers]]
=== `initial.dbms.automatically_enable_free_servers`

// label:enterprise-edition[Enterprise Edition] label:new[Introduced in 5.10]

.initial.dbms.automatically_enable_free_servers
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Automatically enable free servers.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


[role=label--enterprise-edition]
[[config_initial.dbms.database_allocator]]
=== `initial.dbms.database_allocator`

// label:enterprise-edition[Enterprise Edition]

.initial.dbms.database_allocator
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Name of the initial database allocator. After the creation of the DBMS, it can be set by running the `CALL dbms.setDatabaseAllocator()` procedure.
|Valid values
a|A string.
|Default value
m|+++EQUAL_NUMBERS+++
|===


[role=label--enterprise-edition]
[[config_initial.dbms.default_primaries_count]]
=== `initial.dbms.default_primaries_count`

// label:enterprise-edition[Enterprise Edition]

.initial.dbms.default_primaries_count
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The initial default number of primary servers for the standard databases. If the user does not specify the number of primaries in `CREATE DATABASE`, this value will be used unless overwritten by the `dbms.setDefaultAllocationNumbers` procedure.
|Valid values
a|An integer that is minimum `1` and is maximum `11`.
|Default value
m|+++1+++
|===


[role=label--enterprise-edition]
[[config_initial.dbms.default_secondaries_count]]
=== `initial.dbms.default_secondaries_count`

// label:enterprise-edition[Enterprise Edition]

.initial.dbms.default_secondaries_count
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The initial default number of secondary servers for standard databases. If the user does not specify the number of secondaries in `CREATE DATABASE`, this value will be used unless overwritten by the `dbms.setDefaultAllocationNumbers` procedure.
|Valid values
a|An integer that is minimum `0` and is maximum `20`.
|Default value
m|+++0+++
|===


[role=label--enterprise-edition]
[[config_initial.server.allowed_databases]]
=== `initial.server.allowed_databases`

// label:enterprise-edition[Enterprise Edition]

.initial.server.allowed_databases
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Names of the databases allowed on this server; all others are denied. Empty means all are allowed. This configuration can be overridden when enabling the server or altered at runtime without changing this setting. Exclusive with `server.initial_denied_databases`.
|Valid values
a|A comma-separated set where each element is a valid database name containing only alphabetic characters, numbers, dots, and dashes with a length between 3 and 63 characters, starting with an alphabetic character but not with the name `system`.
|Default value
m|++++++
|===


[role=label--enterprise-edition]
[[config_initial.server.denied_databases]]
=== `initial.server.denied_databases`

// label:enterprise-edition[Enterprise Edition]

.initial.server.denied_databases
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Names of the databases not allowed on this server. Empty means nothing is denied. This configuration can be overridden when enabling the server or altered at runtime without changing this setting. Exclusive with `server.initial_allowed_databases`.
|Valid values
a|A comma-separated set where each element is a valid database name containing only alphabetic characters, numbers, dots, and dashes with a length between 3 and 63 characters, starting with an alphabetic character but not with the name `system`.
|Default value
m|++++++
|===


[role=label--enterprise-edition]
[[config_initial.server.mode_constraint]]
=== `initial.server.mode_constraint`

// label:enterprise-edition[Enterprise Edition]

.initial.server.mode_constraint
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|An server can restrict itself to allow databases to be hosted only as primaries or secondaries. This setting is the default input for the `ENABLE SERVER` command - the user can overwrite it when executing the command.
|Valid values
a|One of [PRIMARY, SECONDARY, NONE].
|Default value
m|+++NONE+++
|===


[role=label--enterprise-edition]
[[config_server.tags]]
=== `initial.server.tags`

// label:enterprise-edition[Enterprise Edition]

.initial.server.tags
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|A list of tag names for the server used by the database allocation and when configuring load balancing and replication policies. This setting is the default input for the `ENABLE SERVER` command - the user can overwrite it when executing the command.
|Valid values
a|A comma-separated list where each element is a string identifying a server tag, which contains no duplicate items.
|Default value
m|++++++
|===


[role=label--enterprise-edition]
[[config_server.cluster.advertised_address]]
=== `server.cluster.advertised_address`

// label:enterprise-edition[Enterprise Edition]

.server.cluster.advertised_address
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Advertised hostname/IP address and port for the transaction shipping server.
|Valid values
a|A socket address in the format of `hostname:port`, `hostname`, or `:port` that is an accessible address. If missing, it is acquired from server.default_advertised_address.
|Default value
m|+++:6000+++
|===


[role=label--enterprise-edition label--dynamic label--deprecated-5.4]
[[config_server.cluster.catchup.connect_randomly_to_server_group]]
=== `server.cluster.catchup.connect_randomly_to_server_group`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic] label:deprecated[Deprecated in 5.4]

.server.cluster.catchup.connect_randomly_to_server_group
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Comma-separated list of groups to be used by the connect-randomly-to-server-group selection strategy. The connect-randomly-to-server-group strategy is used when the list of strategies (`<<config_server.cluster.catchup.upstream_strategy,server.cluster.catchup.upstream_strategy>>`) includes the value `connect-randomly-to-server-group`.
|Valid values
a|A comma-separated list where each element is a string identifying a server tag.
|Default value
m|++++++
|===


[role=label--enterprise-edition label--dynamic]
[[config_server.cluster.catchup.connect_randomly_to_server_tags]]
=== `server.cluster.catchup.connect_randomly_to_server_tags`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.server.cluster.catchup.connect_randomly_to_server_tags
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Comma-separated list of tags to be used by the connect-randomly-to-server-with-tag selection strategy. The connect-randomly-to-server-with-tag strategy is used when the list of strategies (`<<config_server.cluster.catchup.upstream_strategy,server.cluster.catchup.upstream_strategy>>`) includes the value `connect-randomly-to-server-with-tag`.
|Valid values
a|A comma-separated list where each element is a string identifying a server tag.
|Default value
m|++++++
|===


[role=label--enterprise-edition]
[[config_server.cluster.catchup.upstream_strategy]]
=== `server.cluster.catchup.upstream_strategy`

// label:enterprise-edition[Enterprise Edition]

.server.cluster.catchup.upstream_strategy
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|A descending-ordered list of strategies secondaries use to choose the upstream server from which to pull transactional updates. If none are valid or the list is empty, the default strategy is `typically-connect-to-random-secondary`.
|Valid values
a|A comma-separated list where each element is a string.
|Default value
m|++++++
|===


[role=label--enterprise-edition]
[[config_server.cluster.catchup.user_defined_upstream_strategy]]
=== `server.cluster.catchup.user_defined_upstream_strategy`

// label:enterprise-edition[Enterprise Edition]

.server.cluster.catchup.user_defined_upstream_strategy
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Configuration of a user-defined upstream selection strategy. The user-defined strategy is used when the list of strategies (`<<config_server.cluster.catchup.upstream_strategy,server.cluster.catchup.upstream_strategy>>`) includes the value `user_defined`.
|Valid values
a|A string.
|Default value
m|++++++
|===


[role=label--enterprise-edition]
[[config_server.cluster.listen_address]]
=== `server.cluster.listen_address`

// label:enterprise-edition[Enterprise Edition]

.server.cluster.listen_address
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Network interface and port for the transaction shipping server to listen on. Note that it is also possible to run the backup client against this port, so always limit access to it via the firewall and configure an SSL policy.
|Valid values
a|A socket address in the format of `hostname:port`, `hostname`, or `:port`. If missing, it is acquired from server.default_listen_address.
|Default value
m|+++:6000+++
|===


[role=label--enterprise-edition]
[[config_server.cluster.network.native_transport_enabled]]
=== `server.cluster.network.native_transport_enabled`

// label:enterprise-edition[Enterprise Edition]

.server.cluster.network.native_transport_enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Use native transport if available. Epoll for Linux or Kqueue for MacOS/BSD. If this setting is set to false, or if native transport is not available, Nio transport will be used.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[role=label--enterprise-edition]
[[config_server.cluster.raft.advertised_address]]
=== `server.cluster.raft.advertised_address`

// label:enterprise-edition[Enterprise Edition]

.server.cluster.raft.advertised_address
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Advertised hostname/IP address and port for the RAFT server.
|Valid values
a|A socket address in the format of `hostname:port`, `hostname`, or `:port` that is an accessible address. If missing, it is acquired from server.default_advertised_address.
|Default value
m|+++:7000+++
|===


[role=label--enterprise-edition]
[[config_server.cluster.raft.listen_address]]
=== `server.cluster.raft.listen_address`

// label:enterprise-edition[Enterprise Edition]

.server.cluster.raft.listen_address
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Network interface and port for the RAFT server to listen on.
|Valid values
a|A socket address in the format of `hostname:port`, `hostname`, or `:port`. If missing, it is acquired from server.default_listen_address.
|Default value
m|+++:7000+++
|===


[role=label--enterprise-edition]
[[config_server.cluster.system_database_mode]]
=== `server.cluster.system_database_mode`

// label:enterprise-edition[Enterprise Edition]

.server.cluster.system_database_mode
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Users must manually specify the mode for the system database on each server.
|Valid values
a|One of [PRIMARY, SECONDARY].
|Default value
m|+++PRIMARY+++
|===


[role=label--enterprise-edition]
[[config_server.discovery.listen_address]]
=== `server.discovery.listen_address`

// label:enterprise-edition[Enterprise Edition]

.server.discovery.listen_address
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Host and port to bind the cluster member discovery management communication.
|Valid values
a|A socket address in the format of `hostname:port`, `hostname`, or `:port`. If missing, it is acquired from server.default_listen_address.
|Default value
m|+++:5000+++
|===


[role=label--enterprise-edition label--deprecated-5.4]
[[config_server.groups]]
=== `server.groups`

// label:enterprise-edition[Enterprise Edition] label:deprecated[Deprecated in 5.4]

.server.groups
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|A list of tag names for the server used when configuring load balancing and replication policies.
|Valid values
a|A comma-separated list where each element is a string identifying a server tag.
|Default value
m|++++++
|Replaced by
m|initial.server.tags
|===

== Connection settings

Connection settings control the communication between servers and between a server and a client.
Neo4j provides support for Bolt, HTTP, and HTTPS protocols via connectors.
For more information about the connectors, see xref:configuration/connectors.adoc[Configure connectors].

When configuring the HTTPS or xref:/performance/bolt-thread-pool-configuration.adoc[Bolt], see also  <<_security_settings>> and xref:security/ssl-framework.adoc[SSL framework] for details on how to work with SSL certificates.


[[config_server.bolt.advertised_address]]
=== `server.bolt.advertised_address`

.server.bolt.advertised_address
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Advertised address for this connector.
|Valid values
a|A socket address in the format of `hostname:port`, `hostname`, or `:port` that is an accessible address. If missing, it is acquired from `server.default_advertised_address`.
|Default value
m|+++:7687+++
|===


[[config_server.bolt.connection_keep_alive]]
=== `server.bolt.connection_keep_alive`

.server.bolt.connection_keep_alive
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The maximum time to wait before sending a NOOP on connections waiting for responses from active ongoing queries.The minimum value is 1 millisecond.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`) that is minimum `1ms`.
|Default value
m|+++1m+++
|===


[[config_server.bolt.connection_keep_alive_for_requests]]
=== `server.bolt.connection_keep_alive_for_requests`

.server.bolt.connection_keep_alive_for_requests
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The type of messages to enable keep-alive messages for (ALL, STREAMING or OFF)
|Valid values
a|One of [ALL, STREAMING, OFF].
|Default value
m|+++ALL+++
|===


[[config_server.bolt.connection_keep_alive_probes]]
=== `server.bolt.connection_keep_alive_probes`

.server.bolt.connection_keep_alive_probes
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The total amount of probes to be missed before a connection is considered stale.The minimum for this value is 1.
|Valid values
a|An integer that is minimum `1`.
|Default value
m|+++2+++
|===


[[config_server.bolt.connection_keep_alive_streaming_scheduling_interval]]
=== `server.bolt.connection_keep_alive_streaming_scheduling_interval`

.server.bolt.connection_keep_alive_streaming_scheduling_interval
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The interval between every scheduled keep-alive check on all connections with active queries. Zero duration turns off keep-alive service.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`) that is minimum `0s`.
|Default value
m|+++1m+++
|===


[[config_server.bolt.enabled]]
=== `server.bolt.enabled`

.server.bolt.enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Enable the bolt connector.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[[config_server.bolt.listen_address]]
=== `server.bolt.listen_address`

.server.bolt.listen_address
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Address the connector should bind to.
|Valid values
a|A socket address in the format of `hostname:port`, `hostname`, or `:port`. If missing, it is acquired from server.default_listen_address.
|Default value
m|+++:7687+++
|===


[[config_server.bolt.ocsp_stapling_enabled]]
=== `server.bolt.ocsp_stapling_enabled`

.server.bolt.ocsp_stapling_enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Enable server OCSP stapling for bolt and http connectors.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


[role=label--new-5.4]
[[config_server.bolt.telemetry.enabled]]
=== `server.bolt.telemetry.enabled`

// label:introduced[Introduced in 5.4]

.server.bolt.telemetry.enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Enable the collection of driver telemetry.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===

[role=label--new-5.18]
[[config_server.bolt.enable_network_error_accounting]]
=== `server.bolt.enable_network_error_accounting`

.server.bolt.enable_network_error_accounting
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Enables accounting based reporting of benign errors within the Bolt stack (when enabled, benign errors are reported only when such events occur with unusual frequency.
Otherwise, all benign network errors will be reported
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===

[role=label--new-5.18]
[[config_server.bolt.network_abort_clear_window_duration]]
=== `server.bolt.network_abort_clear_window_duration`

.server.bolt.network_abort_clear_window_duration
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The duration for which network related connection aborts need to remain at a reasonable level before the error is cleared
|Valid values
a|A duration (Valid units are: ns, μs, ms, s, m, h and d; default unit is s) that is minimum `1s`.
|Default value
m|+++10m+++
|===

[role=label--new-5.18]
[[config_server.bolt.network_abort_warn_threshold]]
=== `server.bolt.network_abort_warn_threshold`

.server.bolt.network_abort_warn_threshold
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The maximum amount of network related connection aborts permitted within a given window before emitting log messages (a value of zero reverts to legacy warning behavior)
|Valid values
a|A long that is minimum `1`.
|Default value
m|+++2+++
|===

[role=label--new-5.18]
[[config_server.bolt.network_abort_warn_window_duration]]
=== `server.bolt.network_abort_warn_window_duration`

.server.bolt.network_abort_warn_window_duration
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The duration of the window in which network related connection aborts are sampled
|Valid values
a|A duration (Valid units are: ns, μs, ms, s, m, h and d; default unit is s) that is minimum `1s`.
|Default value
m|+++10m+++
|===


[[config_server.bolt.thread_pool_keep_alive]]
=== `server.bolt.thread_pool_keep_alive`

.server.bolt.thread_pool_keep_alive
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The maximum time an idle thread in the thread pool bound to this connector will wait for new tasks.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++5m+++
|===


[[config_server.bolt.thread_pool_max_size]]
=== `server.bolt.thread_pool_max_size`

.server.bolt.thread_pool_max_size
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The maximum number of threads allowed in the thread pool bound to this connector.
|Valid values
a|An integer.
|Default value
m|+++400+++
|===


[[config_server.bolt.thread_pool_min_size]]
=== `server.bolt.thread_pool_min_size`

.server.bolt.thread_pool_min_size
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The number of threads to keep in the thread pool bound to this connector, even if they are idle.
|Valid values
a|An integer.
|Default value
m|+++5+++
|===

[role=label--new-5.18]
[[config_server.bolt.thread_starvation_clear_window_duration]]
=== `server.bolt.thread_starvation_clear_window_duration`

.server.bolt.thread_starvation_clear_window_duration
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The duration for which unscheduled requests need to remain at a reasonable level before the error is cleared
|Valid values
a| A duration (Valid units are: ns, μs, ms, s, m, h and d; default unit is s) that is minimum `1s`.
|Default value
m|+++10m+++
|===

[role=label--new-5.18]
[[config_server.bolt.thread_starvation_warn_threshold]]
=== `server.bolt.thread_starvation_warn_threshold`

.server.bolt.thread_starvation_warn_threshold
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The maximum amount of unscheduled requests permitted during thread starvation events within a given window before emitting log messages
|Valid values
a|A long that is minimum `1`.
|Default value
m|+++2+++
|===

[role=label--new-5.18]
[[config_server.bolt.thread_starvation_warn_window_duration]]
=== `server.bolt.thread_starvation_warn_window_duration`

.server.bolt.thread_starvation_warn_window_duration
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The duration of the window in which unscheduled requests are sampled
|Valid values
a|A duration (Valid units are: ns, μs, ms, s, m, h and d; default unit is s) that is minimum `1s`.
|Default value
m|+++10m+++
|===

[[config_server.bolt.tls_level]]
=== `server.bolt.tls_level`

.server.bolt.tls_level
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Encryption level to require this connector to use.
|Valid values
a|One of [REQUIRED, OPTIONAL, DISABLED].
|Default value
m|+++DISABLED+++
|===

[role=label--new-5.18]
[[config_server.bolt.traffic_accounting_check_period]]
=== `server.bolt.traffic_accounting_check_period`

.server.bolt.traffic_accounting_check_period
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Amount of time spent between samples of current traffic usage (lower values result in more accurate reporting while incurring a higher performance penalty; a value of zero disables traffic accounting)
|Valid values
a|A duration (Valid units are: ns, μs, ms, s, m, h and d; default unit is s) that is 0s or is minimum `1m`.
|Default value
m|+++5m+++
|===

[role=label--new-5.18]
[[config_server.bolt.traffic_accounting_clear_duration]]
=== `server.bolt.traffic_accounting_clear_duration`

.server.bolt.traffic_accounting_clear_duration
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Time required to be spent below the configured traffic threshold in order to clear traffic warnings
|Valid values
a|A duration (Valid units are: ns, μs, ms, s, m, h and d; default unit is s) that is minimum `1m`.
|Default value
m|+++10m+++
|===

[role=label--new-5.18]
[[server.bolt.traffic_accounting_incoming_threshold_mbps]]
=== `server.bolt.traffic_accounting_incoming_threshold_mbps`

.server.bolt.traffic_accounting_incoming_threshold_mbps
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Maximum permitted incoming traffic within a configured accounting check window before emitting a warning (in Mbps)
|Valid values
a|A long that is minimum `1`.
|Default value
m|+++950+++
|===

[role=label--new-5.18]
[[server.bolt.traffic_accounting_outgoing_threshold_mbps]]
=== `server.bolt.traffic_accounting_outgoing_threshold_mbps`

.server.bolt.traffic_accounting_outgoing_threshold_mbps
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Maximum permitted outgoing traffic within a configured accounting check window before emitting a warning (in Mbps)
|Valid values
a|A long that is minimum `1`.
|Default value
m|+++950+++
|===

[[config_server.http.advertised_address]]
=== `server.http.advertised_address`

.server.http.advertised_address
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Advertised address for this connector.
|Valid values
a|A socket address in the format of `hostname:port`, `hostname`, or `:port` that is an accessible address. If missing, it is acquired from server.default_advertised_address.
|Default value
m|+++:7474+++
|===


[[config_server.http.enabled]]
=== `server.http.enabled`

.server.http.enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Enable the http connector.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[[config_server.http.listen_address]]
=== `server.http.listen_address`

.server.http.listen_address
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Address the connector should bind to.
|Valid values
a|A socket address in the format of `hostname:port`, `hostname`, or `:port`. If missing, it is acquired from server.default_listen_address.
|Default value
m|+++:7474+++
|===

[[config_server.http_enabled_modules]]
=== `server.http_enabled_modules`

.server.http_enabled_modules
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Defines the set of modules loaded into the Neo4j web server. The enterprise management endpoints are only available in the enterprise edition.
|Valid values
a|A comma-separated set where each element is one of [TRANSACTIONAL_ENDPOINTS, UNMANAGED_EXTENSIONS, BROWSER, ENTERPRISE_MANAGEMENT_ENDPOINTS, QUERY_API_ENDPOINTS].
|Default value
m|+++TRANSACTIONAL_ENDPOINTS,UNMANAGED_EXTENSIONS,BROWSER,ENTERPRISE_MANAGEMENT_ENDPOINTS+++
|===


[role=label--new-5.17]
[[config_server.http_enabled_transports]]
=== `server.http_enabled_transports`

// label:new[Introduced in 5.17]

.server.http_enabled_transports
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Defines the set of transports available on the HTTP server
|Valid values
a|A comma-separated set where each element is one of [HTTP1_1, HTTP2].
|Default value
m|+++HTTP1_1,HTTP2+++
|===


[[config_server.https.advertised_address]]
=== `server.https.advertised_address`

.server.https.advertised_address
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Advertised address for this connector.
|Valid values
a|A socket address in the format of `hostname:port`, `hostname`, or `:port` that is an accessible address. If missing, it is acquired from server.default_advertised_address.
|Default value
m|+++:7473+++
|===


[[config_server.https.enabled]]
=== `server.https.enabled`

.server.https.enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Enable the https connector.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


[[config_server.https.listen_address]]
=== `server.https.listen_address`

.server.https.listen_address
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Address the connector should bind to.
|Valid values
a|A socket address in the format of `hostname:port`, `hostname`, or `:port`. If missing, it is acquired from server.default_listen_address.
|Default value
m|+++:7473+++
|===


[[config_server.default_advertised_address]]
=== `server.default_advertised_address`

.server.default_advertised_address
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Default hostname or IP address the server uses to advertise itself.
|Valid values
a|A socket address in the format of `hostname:port`, `hostname`, or `:port` that has no specified port and is an accessible address.
|Default value
m|+++localhost+++
|===


[[config_server.default_listen_address]]
=== `server.default_listen_address`

.server.default_listen_address
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Default network interface to listen for incoming connections. To listen for connections on all interfaces, use "0.0.0.0".
|Valid values
a|A socket address in the format of `hostname:port`, `hostname`, or `:port` that has no specified port.
|Default value
m|+++localhost+++
|===


[role=label--enterprise-edition]
[[config_server.discovery.advertised_address]]
=== `server.discovery.advertised_address`

// label:enterprise-edition[Enterprise Edition]

.server.discovery.advertised_address
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Advertised cluster member discovery management communication.
|Valid values
a|A socket address in the format of `hostname:port`, `hostname`, or `:port` that is an accessible address. If missing, it is acquired from `server.default_advertised_address`.
|Default value
m|+++:5000+++
|===


[role=label--enterprise-edition]
[[config_server.routing.advertised_address]]
=== `server.routing.advertised_address`

// label:enterprise-edition[Enterprise Edition]

.server.routing.advertised_address
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The advertised address for the intra-cluster routing connector.
|Valid values
a|A socket address in the format of `hostname:port`, `hostname`, or `:port` that is an accessible address. If missing, it is acquired from `server.default_advertised_address`.
|Default value
m|+++:7688+++
|===


[[config_server.routing.listen_address]]
=== `server.routing.listen_address`

.server.routing.listen_address
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The address the routing connector should bind to.
|Valid values
a|A socket address in the format of `hostname:port`, `hostname`, or `:port`. If missing, it is acquired from server.default_listen_address.
|Default value
m|+++:7688+++
|===


[role=label--dynamic]
[[config_dbms.routing.client_side.enforce_for_domains]]
=== `dbms.routing.client_side.enforce_for_domains`

// label:dynamic[Dynamic]

.dbms.routing.client_side.enforce_for_domains
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Always use client side routing (regardless of the default router) for neo4j:// protocol connections to these domains. A comma separated list of domains. Wildcards (*) are supported.
|Valid values
a|A comma-separated set where each element is a string.
|Default value
m|++++++
|===


[[config_dbms.routing.default_router]]
=== `dbms.routing.default_router`

.dbms.routing.default_router
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Routing strategy for neo4j:// protocol connections.
Default is `CLIENT`, using client-side routing, with server-side routing as a fallback (if enabled).
When set to `SERVER`, client-side routing is short-circuited, and requests will rely on server-side routing (which must be enabled for proper operation, i.e. `<<config_dbms.routing.enabled,dbms.routing.enabled>>=true`).
Can be overridden by `<<config_dbms.routing.client_side.enforce_for_domains,dbms.routing.client_side.enforce_for_domains>>`.
|Valid values
a|One of [SERVER, CLIENT].
|Default value
m|+++CLIENT+++
|===


[[config_dbms.routing.driver.connection.connect_timeout]]
=== `dbms.routing.driver.connection.connect_timeout`

.dbms.routing.driver.connection.connect_timeout
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Socket connection timeout.
A timeout of zero is treated as an infinite timeout and will be bound by the timeout configured on the
operating system level.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++5s+++
|===


[[config_dbms.routing.driver.connection.max_lifetime]]
=== `dbms.routing.driver.connection.max_lifetime`

.dbms.routing.driver.connection.max_lifetime
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Pooled connections older than this threshold will be closed and removed from the pool.
Setting this option to a low value will cause a high connection churn and might result in a performance hit.
It is recommended to set maximum lifetime to a slightly smaller value than the one configured in network
equipment (load balancer, proxy, firewall, etc. can also limit maximum connection lifetime).
Zero and negative values result in lifetime not being checked.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++1h+++
|===


[[config_dbms.routing.driver.connection.pool.acquisition_timeout]]
=== `dbms.routing.driver.connection.pool.acquisition_timeout`

.dbms.routing.driver.connection.pool.acquisition_timeout
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Maximum amount of time spent attempting to acquire a connection from the connection pool.
This timeout only kicks in when all existing connections are being used and no new connections can be created because maximum connection pool size has been reached.
Error is raised when connection can't be acquired within configured time.
Negative values are allowed and result in unlimited acquisition timeout. Value of 0 is allowed and results in no timeout and immediate failure when connection is unavailable.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++1m+++
|===


[[config_dbms.routing.driver.connection.pool.idle_test]]
=== `dbms.routing.driver.connection.pool.idle_test`

.dbms.routing.driver.connection.pool.idle_test
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Pooled connections that have been idle in the pool for longer than this timeout will be tested before they are used again, to ensure they are still alive.
If this option is set too low, an additional network call will be incurred when acquiring a connection, which causes a performance hit.
If this is set high, no longer live connections might be used which might lead to errors.
Hence, this parameter tunes a balance between the likelihood of experiencing connection problems and performance
Normally, this parameter should not need tuning.
Value 0 means connections will always be tested for validity. No connection liveliness check is done by default.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|
|===


[[config_dbms.routing.driver.connection.pool.max_size]]
=== `dbms.routing.driver.connection.pool.max_size`

.dbms.routing.driver.connection.pool.max_size
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Maximum total number of connections to be managed by a connection pool.
The limit is enforced for a combination of a host and user. Negative values are allowed and result in unlimited pool. Value of 0is not allowed.
|Valid values
a|An integer.
|Default value
m|+++-1+++
|===


[[config_dbms.routing.driver.logging.level]]
=== `dbms.routing.driver.logging.level`

.dbms.routing.driver.logging.level
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Sets level for driver internal logging.
|Valid values
a|One of [DEBUG, INFO, WARN, ERROR, NONE].
|Default value
m|+++INFO+++
|===


[[config_dbms.routing.enabled]]
=== `dbms.routing.enabled`

.dbms.routing.enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Enable server-side routing in clusters using an additional bolt connector.
When configured, this allows requests to be forwarded from one cluster member to another, if the requests can't be satisfied by the first member (e.g. write requests received by a non-leader).
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[role=label--enterprise-edition]
[[config_dbms.routing.load_balancing.plugin]]
=== `dbms.routing.load_balancing.plugin`

// label:enterprise-edition[Enterprise Edition]

.dbms.routing.load_balancing.plugin
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The load balancing plugin to use.
|Valid values
a|A string that specified load balancer plugin exist..
|Default value
m|+++server_policies+++
|===


[role=label--enterprise-edition]
[[config_dbms.routing.load_balancing.shuffle_enabled]]
=== `dbms.routing.load_balancing.shuffle_enabled`

// label:enterprise-edition[Enterprise Edition]

.dbms.routing.load_balancing.shuffle_enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Vary the order of the entries in routing tables each time one is produced. This means that different clients should select a range of servers as their first contact, reducing the chance of all clients contacting the same server if alternatives are available. This makes the load across the servers more even.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[role=label--enterprise-edition]
[[config_dbms.routing.reads_on_primaries_enabled]]
=== `dbms.routing.reads_on_primaries_enabled`

// label:enterprise-edition[Enterprise Edition]

.dbms.routing.reads_on_primaries_enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Configure if the `dbms.routing.getRoutingTable()` procedure should include non-writer primaries as read endpoints or return only secondaries. +
NOTE: If there are no secondaries for the given database primaries are returned as read end points regardless the value of this setting. Defaults to true so that non-writer primaries are available for read-only queries in a typical heterogeneous setup.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.routing.reads_on_writers_enabled]]
=== `dbms.routing.reads_on_writers_enabled`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.routing.reads_on_writers_enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Configure if the `dbms.routing.getRoutingTable()` procedure should include the writer as read endpoint or return only non-writers (non writer primaries and secondaries). +
NOTE: Writer is returned as read endpoint if no other member is present all.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


[[config_dbms.routing_ttl]]
=== `dbms.routing_ttl`

.dbms.routing_ttl
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|How long callers should cache the response of the routing procedure `dbms.routing.getRoutingTable()`
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`) that is minimum `1s`.
|Default value
m|+++5m+++
|===


== Cypher settings

The Cypher settings affect the behavior of Cypher queries.
They can be used to tune the performance of Cypher queries or to restrict the kinds of queries that can be executed.
For more information, see xref:/performance/statistics-execution-plans.adoc[Statistics and execution plans].


[[config_dbms.cypher.forbid_exhaustive_shortestpath]]
=== `dbms.cypher.forbid_exhaustive_shortestpath`

.dbms.cypher.forbid_exhaustive_shortestpath
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|This setting is associated with performance optimization. Set this to `true` in situations where it is preferable to have any queries using the 'shortestPath' function terminate as soon as possible with no answer, rather than potentially running for a long time attempting to find an answer (even if there is no path to be found). For most queries, the 'shortestPath' algorithm will return the correct answer very quickly. However there are some cases where it is possible that the fast bidirectional breadth-first search algorithm will find no results even if they exist. This can happen when the predicates in the `WHERE` clause applied to 'shortestPath' cannot be applied to each step of the traversal, and can only be applied to the entire path. When the query planner detects these special cases, it will plan to perform an exhaustive depth-first search if the fast algorithm finds no paths. However, the exhaustive search may be orders of magnitude slower than the fast algorithm. If it is critical that queries terminate as soon as possible, it is recommended that this option be set to `true`, which means that Neo4j will never consider using the exhaustive search for shortestPath queries. However, please note that if no paths are found, an error will be thrown at run time, which will need to be handled by the application.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


[[config_dbms.cypher.forbid_shortestpath_common_nodes]]
=== `dbms.cypher.forbid_shortestpath_common_nodes`

.dbms.cypher.forbid_shortestpath_common_nodes
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|This setting is associated with performance optimization. The shortest path algorithm does not work when the start and end nodes are the same. With this setting set to `false` no path will be returned when that happens. The default value of `true` will instead throw an exception. This can happen if you perform a shortestPath search after a cartesian product that might have the same start and end nodes for some of the rows passed to shortestPath. If it is preferable to not experience this exception, and acceptable for results to be missing for those rows, then set this to `false`. If you cannot accept missing results, and really want the shortestPath between two common nodes, then re-write the query using a standard Cypher variable length pattern expression followed by ordering by path length and limiting to one result.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[[config_dbms.cypher.hints_error]]
=== `dbms.cypher.hints_error`

.dbms.cypher.hints_error
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Set this to specify the behavior when Cypher planner or runtime hints cannot be fulfilled. If true, then non-conformance will result in an error, otherwise only a warning is generated.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


[[config_dbms.cypher.lenient_create_relationship]]
=== `dbms.cypher.lenient_create_relationship`

.dbms.cypher.lenient_create_relationship
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Set this to change the behavior for Cypher create relationship when the start or end node is missing. By default this fails the query and stops execution, but by setting this flag the create operation is simply not performed and execution continues.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


[[config_dbms.cypher.min_replan_interval]]
=== `dbms.cypher.min_replan_interval`

.dbms.cypher.min_replan_interval
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The minimum time between possible Cypher query replanning events. After this time, the graph statistics will be evaluated, and if they have changed by more than the value set by <<config_dbms.cypher.statistics_divergence_threshold,dbms.cypher.statistics_divergence_threshold>>, the query will be replanned. If the statistics have not changed sufficiently, the same interval will need to pass before the statistics will be evaluated again. Each time they are evaluated, the divergence threshold will be reduced slightly until it reaches 10% after 7h, so that even moderately changing databases will see query replanning after a sufficiently long time interval.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++10s+++
|===


[[config_dbms.cypher.planner]]
=== `dbms.cypher.planner`

.dbms.cypher.planner
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Set this to specify the default planner for the default language version.
|Valid values
a|One of [DEFAULT, COST].
|Default value
m|+++DEFAULT+++
|===


[role=label--dynamic]
[[config_dbms.cypher.render_plan_description]]
=== `dbms.cypher.render_plan_description`

// label:dynamic[Dynamic]

.dbms.cypher.render_plan_description
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|If set to `true` a textual representation of the plan description will be rendered on the server for all queries running with `EXPLAIN` or `PROFILE`. This allows clients such as the neo4j browser and Cypher shell to show a more detailed plan description.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[[config_dbms.cypher.statistics_divergence_threshold]]
=== `dbms.cypher.statistics_divergence_threshold`

.dbms.cypher.statistics_divergence_threshold
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The threshold for statistics above which a plan is considered stale.

If any of the underlying statistics used to create the plan have changed more than this value, the plan will be considered stale and will be replanned. Change is calculated as `abs(a-b)/max(a,b)`.

This means that a value of `0.75` requires the database to quadruple in size before query replanning. A value of `0` means that the query will be replanned as soon as there is any change in statistics and the replan interval has elapsed.

This interval is defined by `<<config_dbms.cypher.min_replan_interval,dbms.cypher.min_replan_interval>>` and defaults to 10s. After this interval, the divergence threshold will slowly start to decline, reaching 10% after about 7h. This will ensure that long running databases will still get query replanning on even modest changes, while not replanning frequently unless the changes are very large.
|Valid values
a|A double that is in the range `0.0` to `1.0`.
|Default value
m|+++0.75+++
|===


[role=label--enterprise-edition label--new-5.13]
[[config_server.cypher.parallel.worker_limit]]
=== `server.cypher.parallel.worker_limit`

// label:enterprise-edition[Enterprise Edition] label:new[Introduced in 5.13]

.server.cypher.parallel.worker_limit
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a| Number of threads to allocate to Cypher worker threads for the parallel runtime.
If set to a positive number, that number of workers will be started.
If set to `0`, one worker will be started for every logical processor available to the Java Virtual Machine.

If set to a negative number, the total number of logical processors available on the server will be reduced by the absolute value of that number.
For example, if the server has 16 available processors and you set `server.cypher.parallel.worker_limit` to `-1`, the parallel runtime will have 15 threads available.

|Valid values
a| An integer.

|Default value
m|+++0+++
|===


== Database settings

Database settings affect the behavior of a Neo4j database, for example, the file watcher service, the database format, the database store files, and the database timezone.
They can be varied between each database but must be consistent across all configuration files in a cluster/DBMS.

[[config_db.filewatcher.enabled]]
=== `db.filewatcher.enabled`

.db.filewatcher.enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Allows the enabling or disabling of the file watcher service. This is an auxiliary service but should be left enabled in almost all cases.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[role=label--dynamic]
[[config_db.format]]
=== `db.format`

// label:dynamic[Dynamic]

.db.format
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Database format. This is the format that will be used for new databases. Valid values are `standard`, `aligned`, `high_limit` or `block`.
The `aligned` format is essentially the `standard` format with some minimal padding at the end of pages such that a single record will never cross a page boundary.
The `high_limit` and `block` formats are available for Enterprise Edition only.
Either `high_limit` or `block` is required if you have a graph that is larger than 34 billion nodes, 34 billion relationships, or 68 billion properties.
|Valid values
a|A string.
|Default value
m|+++aligned+++
|===


[[config_db.relationship_grouping_threshold]]
=== `db.relationship_grouping_threshold`

.db.relationship_grouping_threshold
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Relationship count threshold for considering a node to be dense.
|Valid values
a|An integer that is minimum `1`.
|Default value
m|+++50+++
|===


[[config_db.store.files.preallocate]]
=== `db.store.files.preallocate`

.db.store.files.preallocate
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Specify if Neo4j should try to preallocate store files as they grow.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[[config_db.temporal.timezone]]
=== `db.temporal.timezone`

.db.temporal.timezone
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Database timezone for temporal functions. All Time and DateTime values that are created without an explicit timezone will use this configured default timezone.
|Valid values
a|A string describing a timezone, either described by offset (e.g. `+02:00`) or by name (e.g. `Europe/Stockholm`).
|Default value
m|+++Z+++
|===


[role=label--enterprise-edition label--dynamic]
[[config_db.track_query_cpu_time]]
=== `db.track_query_cpu_time`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.db.track_query_cpu_time
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Enables or disables tracking of how much time a query spends actively executing on the CPU. Calling `SHOW TRANSACTIONS` will display the time, but not in the _query.log_. +
If you want the CPU time to be logged in the _query.log_, set `db.track_query_cpu_time=true`.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


== DBMS settings

The DBMS settings affect the Neo4j DBMS as a whole.
You can use them to set the default database, the DBMS timezone, a list of seed providers, and the maximum number of databases.
The DBMS settings must be consistent across all configuration files in a cluster/DBMS.


[[config_initial.dbms.default_database]]
=== `initial.dbms.default_database`

.initial.dbms.default_database
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Name of the default database (aliases are not supported). +
NOTE: This setting is not the same as `dbms.default_database`, which was used to set the default database in Neo4j 4.x and earlier versions.

The `initial.dbms.default_database` setting is meant to set the default database *before* the creation of the DBMS.
Once it is created, the setting is not valid anymore.

To set the default database, use the xref:/clustering/databases.adoc#cluster-default-database[`dbms.setDefaultDatabase()`] procedure instead.
====
|Valid values
a|A valid database name containing only alphabetic characters, numbers, dots, and dashes with a length between 3 and 63 characters, starting with an alphabetic character but not with the name system.
|Default value
m|+++neo4j+++
|===


[[config_dbms.db.timezone]]
=== `dbms.db.timezone`

.dbms.db.timezone
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Database timezone. Among other things, this setting influences the monitoring procedures.
|Valid values
a|One of [UTC, SYSTEM].
|Default value
m|+++UTC+++
|===


[role=label--enterprise-edition]
[[config_dbms.databases.seed_from_uri_providers]]
=== `dbms.databases.seed_from_uri_providers`

// label:enterprise-edition[Enterprise Edition]

.dbms.databases.seed_from_uri_providers
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Databases may be created from an existing _seed_ (a database backup or dump) stored at some source URI.
Different types of seed source are supported by different implementations of `com.neo4j.dbms.seeding.SeedProvider`.
There are two available values, the built-in `S3SeedProvider` and `URLConnectionSeedProvider`.
Seeds addressed with  `s3:` are supported by `S3SeedProvider` and seeds stored at `file`, `ftp`,`http`, and `https` URIs are supported by `URLConnectionSeedProvider`.
This list specifies enabled seed providers.
If a seed source (URI scheme) is supported by multiple providers in the list, the first matching provider will be used.
If the list is set to empty, the seed from URI functionality is effectively disabled.
See xref:/clustering/databases.adoc#cluster-seed-uri[Seed from URI] for more information.
|Valid values
a|A comma-separated list where each element is a string.
|Default value
m|+++S3SeedProvider+++
|===


[role=label--enterprise-edition]
[[config_dbms.max_databases]]
=== `dbms.max_databases`

// label:enterprise-edition[Enterprise Edition]

.dbms.max_databases
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The maximum number of databases.
|Valid values
a|A long that is minimum `2`.
|Default value
m|+++100+++
|===

[role=label--new-5.20]
[[config_dbms.usage_report.enabled]]
=== `dbms.usage_report.enabled`

.dbms.usage_report.enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Anonymous Usage Data reporting.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===

== Import settings

The import settings control the size of the internal buffer used by `LOAD CSV` and the escaping of quotes in CSV files.


[[config_db.import.csv.buffer_size]]
=== `db.import.csv.buffer_size`

.db.import.csv.buffer_size
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The size of the internal buffer in bytes used by `LOAD CSV`. If the csv file contains huge fields this value may have to be increased.
|Valid values
a|A long that is minimum `1`.
|Default value
m|+++2097152+++
|===


[[config_db.import.csv.legacy_quote_escaping]]
=== `db.import.csv.legacy_quote_escaping`

.db.import.csv.legacy_quote_escaping
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Selects whether to conform to the standard https://tools.ietf.org/html/rfc4180 for interpreting escaped quotation characters in CSV files loaded using `LOAD CSV`. Setting this to `false` will use the standard, interpreting repeated quotes '""' as a single in-lined quote, while `true` will use the legacy convention originally supported in Neo4j 3.0 and 3.1, allowing a backslash to include quotes in-lined in fields.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


== Index settings

The index settings control the fulltext index and the background index sampling (chunk size limit and sample size).
For more information, see xref:/performance/index-configuration.adoc[Index configuration].


[[config_db.index.fulltext.default_analyzer]]
=== `db.index.fulltext.default_analyzer`

.db.index.fulltext.default_analyzer
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The name of the analyzer that the full-text indexes should use by default.
|Valid values
a|A string.
|Default value
m|+++standard-no-stop-words+++
|===


[[config_db.index.fulltext.eventually_consistent]]
=== `db.index.fulltext.eventually_consistent`

.db.index.fulltext.eventually_consistent
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Whether or not full-text indexes should be eventually consistent by default or not.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


[[config_db.index.fulltext.eventually_consistent_index_update_queue_max_length]]
=== `db.index.fulltext.eventually_consistent_index_update_queue_max_length`

.db.index.fulltext.eventually_consistent_index_update_queue_max_length
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The _eventually consistent_ mode of the full-text indexes works by queueing up index updates to be applied later in a background thread. This newBuilder sets an upper bound on how many index updates are allowed to be in this queue at any one point in time. When it is reached, the commit process will slow down and wait for the index update applier thread to make some more room in the queue.
|Valid values
a|An integer that is in the range `1` to `50000000`.
|Default value
m|+++10000+++
|===


[[config_db.index_sampling.background_enabled]]
=== `db.index_sampling.background_enabled`

.db.index_sampling.background_enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Enable or disable background index sampling.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[[config_db.index_sampling.sample_size_limit]]
=== `db.index_sampling.sample_size_limit`

.db.index_sampling.sample_size_limit
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Index sampling chunk size limit.
|Valid values
a|An integer that is in the range `1048576` to `2147483647`.
|Default value
m|+++8388608+++
|===


[[config_db.index_sampling.update_percentage]]
=== `db.index_sampling.update_percentage`

.db.index_sampling.update_percentage
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Percentage of index updates of total index size required before sampling of a given index is triggered.
|Valid values
a|An integer that is minimum `0`.
|Default value
m|+++5+++
|===


== Logging settings

Neo4j has two different configuration files for logging, one for the _neo4j.log_, which contains general information about Neo4j, and one configuration file for all other types of logging via Log4j 2 (except _gc.log_ which is handled by the Java Virtual Machine(JVM).
For more information, see xref:/monitoring/logging.adoc[Logging].


[role=label--new-5.8 label--deprecated-5.12 label--dynamic]
[[config_db.logs.query.annotation_data_as_json_enabled]]
=== `db.logs.query.annotation_data_as_json_enabled`

// label:new[Introduced in 5.8] label:dynamic[Dynamic] label:deprecated[Deprecated in 5.12]

.db.logs.query.annotation_data_as_json_enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Log the annotation data as JSON strings instead of a Cypher map. This configuration has an effect only when the query log is in JSON format.
From 5.9, if `true`, it collapses the nested JSON objects in the query logger.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|Replaced by
a|<<config_db.logs.query.annotation_data_format,`db.logs.query.annotation_data_format`>>
|===


[role=label--new-5.12 label--dynamic]
[[config_db.logs.query.annotation_data_format]]
=== `db.logs.query.annotation_data_format`

// label:new[Introduced in 5.12] label:dynamic[Dynamic]

.db.logs.query.annotation_data_format
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The format to use for the JSON annotation data.

`CYPHER`:: Formatted as a Cypher map. E.g. `{foo: 'bar', baz: {k: 1}}`.
`JSON`:: Formatted as a JSON map. E.g. `{"foo": "bar", "baz": {"k": 1}}`.
`FLAT_JSON`:: Formatted as a flattened JSON map. E.g. `{"foo": "bar", "baz.k": 1}`.

This only have effect when the query log is in JSON format.
|Valid values
a|One of [CYPHER, JSON, FLAT_JSON].
|Default value
m|+++CYPHER+++
|===


[role=label--dynamic]
[[config_db.logs.query.early_raw_logging_enabled]]
=== `db.logs.query.early_raw_logging_enabled`

// label:dynamic[Dynamic]

.db.logs.query.early_raw_logging_enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Log query text and parameters without obfuscating passwords. This allows queries to be logged earlier before parsing starts.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


[role=label--dynamic]
[[config_db.logs.query.enabled]]
=== `db.logs.query.enabled`

// label:dynamic[Dynamic]

.db.logs.query.enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Log executed queries. Valid values are `OFF`, `INFO`, or `VERBOSE`.

`OFF`::  no logging.
`INFO`:: log queries at the end of execution, that take longer than the configured threshold, `<<config_db.logs.query.threshold,db.logs.query.threshold>>`.
`VERBOSE`:: log queries at the start and end of execution, regardless of `<<config_db.logs.query.threshold,db.logs.query.threshold>>`.

Log entries are written to the query log.

This feature is available in the Neo4j Enterprise Edition.
|Valid values
a|One of [OFF, INFO, VERBOSE].
|Default value
m|+++VERBOSE+++
|===


[role=label--dynamic]
[[config_db.logs.query.max_parameter_length]]
=== `db.logs.query.max_parameter_length`

// label:dynamic[Dynamic]

.db.logs.query.max_parameter_length
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Sets a maximum character length use for each parameter in the log. This only takes effect if `<<config_db.logs.query.parameter_logging_enabled,db.logs.query.parameter_logging_enabled>> = true`.
|Valid values
a|An integer.
|Default value
m|+++2147483647+++
|===


[role=label--dynamic]
[[config_db.logs.query.obfuscate_literals]]
=== `db.logs.query.obfuscate_literals`

// label:dynamic[Dynamic]

.db.logs.query.obfuscate_literals
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Obfuscates all literals of the query before writing to the log. Note that node labels, relationship types and map property keys are still shown. Changing the setting will not affect queries that are cached. So, if you want the switch to have an immediate effect, you must also call `CALL db.clearQueryCaches()`.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


[role=label--dynamic]
[[config_db.logs.query.parameter_logging_enabled]]
=== `db.logs.query.parameter_logging_enabled`

// label:dynamic[Dynamic]

.db.logs.query.parameter_logging_enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Log parameters for the executed queries being logged.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[role=label--dynamic]
[[config_db.logs.query.plan_description_enabled]]
=== `db.logs.query.plan_description_enabled`

// label:dynamic[Dynamic]

.db.logs.query.plan_description_enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Log query plan description table, useful for debugging purposes.
|Valid values
a|A boolean.
|Default value
m|false
|===


[role=label--dynamic]
[[config_db.logs.query.threshold]]
=== `db.logs.query.threshold`

// label:dynamic[Dynamic]

.db.logs.query.threshold
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|If the execution of a query takes more time than this threshold, the query is logged once completed - provided query logging is set to INFO. Defaults to 0 seconds, that is all queries are logged.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++0s+++
|===


[role=label--dynamic label--enterprise-edition]
[[config_db.logs.query.transaction.enabled]]
=== `db.logs.query.transaction.enabled`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.db.logs.query.transaction.enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Log the start and end of a transaction. Valid values are 'OFF', 'INFO', or 'VERBOSE'.
OFF:  no logging.
INFO: log the start and end of transactions that take longer than the configured threshold, <<config_db.logs.query.transaction.threshold,db.logs.query.transaction.threshold>>.
VERBOSE: log the start and end of all transactions.
Log entries are written to the query log.
|Valid values
a|One of [OFF, INFO, VERBOSE].
|Default value
m|+++OFF+++
|===


[role=label--dynamic]
[[config_db.logs.query.transaction.threshold]]
=== `db.logs.query.transaction.threshold`

// label:dynamic[Dynamic]

.db.logs.query.transaction.threshold
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|If the transaction is open for more time than this threshold, the transaction is logged once completed - provided transaction logging (<<config_db.logs.query.transaction.enabled,db.logs.query.transaction.enabled>>) is set to `INFO`. Defaults to 0 seconds (all transactions are logged).
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++0s+++
|===


[[config_dbms.logs.http.enabled]]
=== `dbms.logs.http.enabled`

.dbms.logs.http.enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Enable HTTP request logging.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


[[config_server.logs.config]]
=== `server.logs.config`

.server.logs.config
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Path to the logging configuration for debug, query, http and security logs.
|Valid values
a|A path. If relative, it is resolved from server.directories.neo4j_home.
|Default value
m|+++conf/server-logs.xml+++
|===


[[config_server.logs.debug.enabled]]
=== `server.logs.debug.enabled`

.server.logs.debug.enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Enable the debug log.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[[config_server.logs.gc.enabled]]
=== `server.logs.gc.enabled`

.server.logs.gc.enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Enable GC Logging.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


[[config_server.logs.gc.options]]
=== `server.logs.gc.options`

.server.logs.gc.options
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|GC Logging Options.
|Valid values
a|A string.
|Default value
m|+++-Xlog:gc*,safepoint,age*=trace+++
|===


[[config_server.logs.gc.rotation.keep_number]]
=== `server.logs.gc.rotation.keep_number`

.server.logs.gc.rotation.keep_number
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Number of GC logs to keep.
|Valid values
a|An integer.
|Default value
m|+++5+++
|===


[[config_server.logs.gc.rotation.size]]
=== `server.logs.gc.rotation.size`

.server.logs.gc.rotation.size
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Size of each GC log that is kept.
|Valid values
a|A byte size (valid multipliers are `B`, `KiB`, `KB`, `K`, `kB`, `kb`, `k`, `MiB`, `MB`, `M`, `mB`, `mb`, `m`, `GiB`, `GB`, `G`, `gB`, `gb`, `g`, `TiB`, `TB`, `PiB`, `PB`, `EiB`, `EB`).
|Default value
m|+++20.00MiB+++
|===


[[config_server.logs.user.config]]
=== `server.logs.user.config`

.server.logs.user.config
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Path to the logging configuration of user logs.
|Valid values
a|A path. If relative, it is resolved from `server.directories.neo4j_home`.
|Default value
m|+++conf/user-logs.xml+++
|===


== Memory settings

Memory settings control how much memory is allocated to Neo4j and how it is used.
It is recommended to perform a certain amount of testing and tuning of these settings to figure out the optimal division of the available memory.
For more information on how to tune these settings, see xref:/performance/memory-configuration.adoc[Memory configuration], xref:/performance/disks-ram-and-other-tips.adoc[Disks, RAM and other tips], and xref:performance/gc-tuning.adoc[Tuning of the garbage collector].


[[config_db.memory.pagecache.warmup.enable]]
=== `db.memory.pagecache.warmup.enable`

.db.memory.pagecache.warmup.enable
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Page cache can be configured to perform usage sampling of loaded pages that can be used to construct active load profile. According to that profile pages can be reloaded on the restart, replication, etc. This setting allows disabling that behavior.
This feature is available in Neo4j Enterprise Edition.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[[config_db.memory.pagecache.warmup.preload]]
=== `db.memory.pagecache.warmup.preload`

.db.memory.pagecache.warmup.preload
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Page cache warmup can be configured to prefetch files, preferably when cache size is bigger than store size. Files to be prefetched can be filtered by 'dbms.memory.pagecache.warmup.preload.allowlist'. Enabling this disables warmup by profile.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


[[config_db.memory.pagecache.warmup.preload.allowlist]]
=== `db.memory.pagecache.warmup.preload.allowlist`

.db.memory.pagecache.warmup.preload.allowlist
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Page cache warmup prefetch file allowlist regex. By default matches all files.
|Valid values
a|A string.
|Default value
m|.*
|===


[role=label--enterprise-edition]
[[config_db.memory.pagecache.warmup.profile.interval]]
=== `db.memory.pagecache.warmup.profile.interval`

// label:enterprise-edition[Enterprise Edition]

.db.memory.pagecache.warmup.profile.interval
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The profiling frequency for the page cache. Accurate profiles allow the page cache to do an active warmup after a restart, reducing the mean time to performance.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++1m+++
|===


[role=label--dynamic]
[[config_db.memory.transaction.max]]
=== `db.memory.transaction.max`

// label:dynamic[Dynamic]

.db.memory.transaction.max
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Limit the amount of memory that a single transaction can consume, in bytes (or kilobytes with the 'k' suffix, megabytes with 'm', and gigabytes with 'g'). Zero means 'largest possible value'.
|Valid values
a|A byte size (valid multipliers are `B`, `KiB`, `KB`, `K`, `kB`, `kb`, `k`, `MiB`, `MB`, `M`, `mB`, `mb`, `m`, `GiB`, `GB`, `G`, `gB`, `gb`, `g`, `TiB`, `TB`, `PiB`, `PB`, `EiB`, `EB`) that is minimum `1.00MiB` or is `0B`.
|Default value
m|+++0B+++
|===


[role=label--dynamic]
[[config_db.memory.transaction.total.max]]
=== `db.memory.transaction.total.max`

// label:dynamic[Dynamic]

.db.memory.transaction.total.max
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Limit the amount of memory that all transactions in one database can consume, in bytes (or kilobytes with the 'k' suffix, megabytes with 'm' and gigabytes with 'g'). Zero means 'unlimited'.
|Valid values
a|A byte size (valid multipliers are `B`, `KiB`, `KB`, `K`, `kB`, `kb`, `k`, `MiB`, `MB`, `M`, `mB`, `mb`, `m`, `GiB`, `GB`, `G`, `gB`, `gb`, `g`, `TiB`, `TB`, `PiB`, `PB`, `EiB`, `EB`) that is minimum `10.00MiB` or is `0B`.
|Default value
m|+++0B+++
|===


[role=label--deprecated-5.8]
[[config_db.tx_state.memory_allocation]]
=== `db.tx_state.memory_allocation`

// label:deprecated[Deprecated in 5.8]

.db.tx_state.memory_allocation
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Defines whether memory for transaction state should be allocated on- or off-heap. Note that for small transactions you can gain up to 25% write speed by setting it to `ON_HEAP`.
|Valid values
a|One of [ON_HEAP, OFF_HEAP].
|Default value
m|+++ON_HEAP+++
|===


[role=label--deprecated-5.7]
[[config_server.db.query_cache_size]]
=== `server.db.query_cache_size`

// label:deprecated[Deprecated in 5.7]

.server.db.query_cache_size
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The number of cached Cypher query execution plans per database. The max number of query plans that can be kept in cache is the `number of databases` * ``server.db.query_cache_size``. With 10 databases and ``server.db.query_cache_size``=1000, the caches can keep 10000 plans in total on the instance, assuming that each DB receives queries that fill up its cache.
|Valid values
a|An integer that is minimum `0`.
|Default value
m|+++1000+++
|Replaced by
a|<<config_server.memory.query_cache.per_db_cache_num_entries,`server.memory.query_cache.per_db_cache_num_entries`>>
|===


[[config_dbms.memory.tracking.enable]]
=== `dbms.memory.tracking.enable`

.dbms.memory.tracking.enable
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Enable off heap and on heap memory tracking. Should not be set to `false` for clusters.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[role=label--changed-5.2 label--dynamic]
[[config_dbms.memory.transaction.total.max]]
=== `dbms.memory.transaction.total.max`

// label:dynamic[Dynamic] label:changed[Value changed in 5.2]

.dbms.memory.transaction.total.max
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Limit the amount of memory that all of the running transactions can consume, in bytes (or kilobytes with the 'k' suffix, megabytes with 'm' and gigabytes with 'g'). Zero means 'unlimited'. Defaults to 70% of the heap size limit.
|Valid values
a|A byte size (valid multipliers are `B`, `KiB`, `KB`, `K`, `kB`, `kb`, `k`, `MiB`, `MB`, `M`, `mB`, `mb`, `m`, `GiB`, `GB`, `G`, `gB`, `gb`, `g`, `TiB`, `TB`, `PiB`, `PB`, `EiB`, `EB`) that is minimum `10.00MiB` or is `0B`.
|Default value
m|
|===


[[config_server.memory.heap.initial_size]]
=== `server.memory.heap.initial_size`

.server.memory.heap.initial_size
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Initial heap size. By default it is calculated based on available system resources.
|Valid values
a|A byte size (valid multipliers are `B`, `KiB`, `KB`, `K`, `kB`, `kb`, `k`, `MiB`, `MB`, `M`, `mB`, `mb`, `m`, `GiB`, `GB`, `G`, `gB`, `gb`, `g`, `TiB`, `TB`, `PiB`, `PB`, `EiB`, `EB`).
|Default value
m|
|===


[[config_server.memory.heap.max_size]]
=== `server.memory.heap.max_size`

.server.memory.heap.max_size
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Maximum heap size. By default it is calculated based on available system resources.
|Valid values
a|A byte size (valid multipliers are `B`, `KiB`, `KB`, `K`, `kB`, `kb`, `k`, `MiB`, `MB`, `M`, `mB`, `mb`, `m`, `GiB`, `GB`, `G`, `gB`, `gb`, `g`, `TiB`, `TB`, `PiB`, `PB`, `EiB`, `EB`).
|Default value
m|
|===


[[config_server.memory.off_heap.block_cache_size]]
=== `server.memory.off_heap.block_cache_size`

.server.memory.off_heap.block_cache_size
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Defines the size of the off-heap memory blocks cache. The cache will contain this number of blocks for each block size that is power of two. Thus, maximum amount of memory used by blocks cache can be calculated as 2 * <<config_server.memory.off_heap.max_cacheable_block_size,server.memory.off_heap.max_cacheable_block_size>> * `server.memory.off_heap.block_cache_size`
|Valid values
a|An integer that is minimum `16`.
|Default value
m|+++128+++
|===


[[config_server.memory.off_heap.max_cacheable_block_size]]
=== `server.memory.off_heap.max_cacheable_block_size`

.server.memory.off_heap.max_cacheable_block_size
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Defines the maximum size of an off-heap memory block that can be cached to speed up allocations. The value must be a power of 2.
|Valid values
a|A byte size (valid multipliers are `B`, `KiB`, `KB`, `K`, `kB`, `kb`, `k`, `MiB`, `MB`, `M`, `mB`, `mb`, `m`, `GiB`, `GB`, `G`, `gB`, `gb`, `g`, `TiB`, `TB`, `PiB`, `PB`, `EiB`, `EB`) that is minimum `4.00KiB` and is power of 2.
|Default value
m|+++512.00KiB+++
|===


[role=label--deprecated-5.8]
[[config_server.memory.off_heap.transaction_max_size]]
=== `server.memory.off_heap.transaction_max_size`

// label:deprecated[Deprecated in 5.8]

.server.memory.off_heap.transaction_max_size
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The maximum amount of off-heap memory that can be used to store transaction state data; it's a total amount of memory shared across all active transactions. Zero means 'unlimited'. Used when <<config_db.tx_state.memory_allocation,db.tx_state.memory_allocation>> is set to 'OFF_HEAP'.
|Valid values
a|A byte size (valid multipliers are `B`, `KiB`, `KB`, `K`, `kB`, `kb`, `k`, `MiB`, `MB`, `M`, `mB`, `mb`, `m`, `GiB`, `GB`, `G`, `gB`, `gb`, `g`, `TiB`, `TB`, `PiB`, `PB`, `EiB`, `EB`) that is minimum `0B`.
|Default value
m|+++2.00GiB+++
|===


[[config_server.memory.pagecache.directio]]
=== `server.memory.pagecache.directio`

.server.memory.pagecache.directio
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Use direct I/O for page cache. This setting is supported only on Linux and only for a subset of record formats that use platform-aligned page size.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


[role=label--dynamic]
[[config_server.memory.pagecache.flush.buffer.enabled]]
=== `server.memory.pagecache.flush.buffer.enabled`

// label:dynamic[Dynamic]

.server.memory.pagecache.flush.buffer.enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Page cache can be configured to use a temporal buffer for flushing purposes. It is used to combine, if possible, sequence of several cache pages into one bigger buffer to minimize the number of individual IOPS performed and better utilization of available I/O resources, especially when those are restricted.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


[role=label--dynamic]
[[config_server.memory.pagecache.flush.buffer.size_in_pages]]
=== `server.memory.pagecache.flush.buffer.size_in_pages`

// label:dynamic[Dynamic]

.server.memory.pagecache.flush.buffer.size_in_pages
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Page cache can be configured to use a temporal buffer for flushing purposes. It is used to combine, if possible, sequence of several cache pages into one bigger buffer to minimize the number of individual IOPS performed and better utilization of available I/O resources, especially when those are restricted. Use this setting to configure individual file flush the buffer size in pages (8KiB). To be able to utilize this buffer during page cache flushing, buffered flush should be enabled.
|Valid values
a|An integer that is in the range `1` to `512`.
|Default value
m|+++128+++
|===


[[config_server.memory.pagecache.scan.prefetchers]]
=== `server.memory.pagecache.scan.prefetchers`

.server.memory.pagecache.scan.prefetchers
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The maximum number of worker threads to use for pre-fetching data when doing sequential scans. Set to '0' to disable pre-fetching for scans.
|Valid values
a|An integer that is in the range `0` to `255`.
|Default value
m|+++4+++
|===


[[config_server.memory.pagecache.size]]
=== `server.memory.pagecache.size`

.server.memory.pagecache.size
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The amount of memory to use for mapping the store files. If Neo4j is running on a dedicated server, then it is generally recommended to leave about 2-4 gigabytes for the operating system, give the JVM enough heap to hold all your transaction state and query context, and then leave the rest for the page cache. If no page cache memory is configured, then a heuristic setting is computed based on available system resources. By default the size of page cache will be 50% of available RAM minus the max heap size. The size of the page cache will also not be larger than 70x the max heap size (due to some overhead of the page cache in the heap.
|Valid values
a|A byte size (valid multipliers are `B`, `KiB`, `KB`, `K`, `kB`, `kb`, `k`, `MiB`, `MB`, `M`, `mB`, `mb`, `m`, `GiB`, `GB`, `G`, `gB`, `gb`, `g`, `TiB`, `TB`, `PiB`, `PB`, `EiB`, `EB`).
|Default value
m|
|===


[role=label--new-5.8 label--enterprise-edition]
[[config_server.memory.query_cache.sharing_enabled]]
=== `server.memory.query_cache.sharing_enabled`

// label:enterprise-edition[Enterprise Edition] label:new[Introduced in 5.7]

.server.memory.query_cache.sharing_enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Enable sharing cache space between different databases.
With this option turned on, databases will share cache space, but not cache entries.
This means that a database may store and retrieve entries from the shared cache, but it may not retrieve entries produced by another database.
The database may, however, evict entries from other databases as necessary, according to the constrained cache size and cache eviction policy.
In essence, databases may compete for cache space, but may not observe each other's entries.

When this option is turned on, the cache space available to all databases is configured with `server.memory.query_cache.shared_cache_num_entries`.
With this option turned off, the cache space available to each individual database is configured with `server.memory.query_cache.per_db_cache_num_entries`.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


[role=label--new-5.7 label--dynamic-5.10 label--enterprise-edition]
[[config_server.memory.query_cache.shared_cache_num_entries]]
=== `server.memory.query_cache.shared_cache_num_entries`

// label:enterprise-edition[Enterprise Edition] label:new[Introduced in 5.7] label:dynamic[Dynamic since 5.10]
// label:dynamic[Dynamic since 5.10]

.server.memory.query_cache.shared_cache_num_entries
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The number of cached queries for all databases.
The maximum number of queries that can be kept in a cache is exactly `server.memory.query_cache.shared_cache_num_entries`.
This setting is only deciding cache size when `server.memory.query_cache.sharing_enabled` is set to `true`.
|Valid values
a|An integer that is minimum `0`.
|Default value
m|+++1000+++
|===


[role=label--dynamic-5.10]
[[config_server.memory.query_cache.per_db_cache_num_entries]]
=== `server.memory.query_cache.per_db_cache_num_entries`

// label:dynamic[Dynamic since 5.10]

.server.memory.query_cache.per_db_cache_num_entries
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The number of cached queries per database.
The maximum number of queries that can be kept in a cache is `number of databases` * `server.memory.query_cache.per_db_cache_num_entries`.
With 10 databases and `server.memory.query_cache.per_db_cache_num_entries`=1000, the cache can keep 10000 plans in total.
This setting is only deciding cache size when `server.memory.query_cache.sharing_enabled` is set to `false`.
|Valid values
a|An integer that is minimum `0`.
|Default value
m|+++1000+++
|===


== Metrics settings

The metrics settings control whether Neo4j will log metrics, what metrics to log, how to log them, and how to expose them.
For better understanding of the metrics settings and how to configure them, see xref:monitoring/metrics/index.adoc[Metrics].


[role=label--enterprise-edition]
[[config_server.metrics.csv.enabled]]
=== `server.metrics.csv.enabled`

// label:enterprise-edition[Enterprise Edition]

.server.metrics.csv.enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Set to `true` to enable exporting metrics to CSV files.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[role=label--enterprise-edition]
[[config_server.metrics.csv.interval]]
=== `server.metrics.csv.interval`

// label:enterprise-edition[Enterprise Edition]

.server.metrics.csv.interval
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The reporting interval for the CSV files. That is, how often new rows with numbers are appended to the CSV files.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`) that is minimum `1ms`.
|Default value
m|+++30s+++
|===


[role=label--enterprise-edition]
[[config_server.metrics.csv.rotation.compression]]
=== `server.metrics.csv.rotation.compression`

// label:enterprise-edition[Enterprise Edition]

.server.metrics.csv.rotation.compression
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Decides what compression to use for the csv history files.
|Valid values
a|One of [NONE, ZIP, GZ].
|Default value
m|+++NONE+++
|===


[role=label--enterprise-edition]
[[config_server.metrics.csv.rotation.keep_number]]
=== `server.metrics.csv.rotation.keep_number`

// label:enterprise-edition[Enterprise Edition]

.server.metrics.csv.rotation.keep_number
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Maximum number of history files for the csv files.
|Valid values
a|An integer that is minimum `1`.
|Default value
m|+++7+++
|===


[role=label--enterprise-edition]
[[config_server.metrics.csv.rotation.size]]
=== `server.metrics.csv.rotation.size`

// label:enterprise-edition[Enterprise Edition]

.server.metrics.csv.rotation.size
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The file size in bytes at which the csv files will auto-rotate. If set to zero then no rotation will occur. Accepts a binary suffix `k`, `m` or `g`.
|Valid values
a|A byte size (valid multipliers are `B`, `KiB`, `KB`, `K`, `kB`, `kb`, `k`, `MiB`, `MB`, `M`, `mB`, `mb`, `m`, `GiB`, `GB`, `G`, `gB`, `gb`, `g`, `TiB`, `TB`, `PiB`, `PB`, `EiB`, `EB`) that is in the range `0B` to `8388608.00TiB`.
|Default value
m|+++10.00MiB+++
|===


[role=label--enterprise-edition]
[[config_server.metrics.enabled]]
=== `server.metrics.enabled`

// label:enterprise-edition[Enterprise Edition]

.server.metrics.enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Enable metrics. Setting this to `false` will to turn off all metrics.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[role=label--enterprise-edition]
[[config_server.metrics.filter]]
=== `server.metrics.filter`

// label:enterprise-edition[Enterprise Edition]

.server.metrics.filter
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Specifies which metrics should be enabled by using a comma separated list of globbing patterns. Only the metrics matching the filter will be enabled. For example `\*check_point*,neo4j.page_cache.evictions` will enable any checkpoint metrics and the pagecache eviction metric.
|Valid values
a|A comma-separated list where each element is A simple globbing pattern that can use `*` and `?`..
|Default value
m|`*bolt.connections*,*bolt.messages_received*,*bolt.messages_started*,*dbms.pool.bolt.free,*dbms.pool.bolt.total_size,*dbms.pool.bolt.total_used,*dbms.pool.bolt.used_heap,*cluster.raft.is_leader,*cluster.raft.last_leader_message,*cluster.raft.replication_attempt,*cluster.raft.replication_fail,*cluster.raft.last_applied,*cluster.raft.last_appended,*cluster.raft.append_index,*cluster.raft.commit_index,*cluster.raft.applied_index,*check_point.*,*cypher.replan_events,*ids_in_use*,*pool.transaction.*.total_used,*pool.transaction.*.used_heap,*pool.transaction.*.used_native,*store.size*,*transaction.active_read,*transaction.active_write,*transaction.committed*,*transaction.last_committed_tx_id,*transaction.peak_concurrent,*transaction.rollbacks*,*page_cache.hit*,*page_cache.page_faults,*page_cache.usage_ratio,*vm.file.descriptors.count,*vm.gc.time.*,*vm.heap.used,*vm.memory.buffer.direct.used,*vm.memory.pool.g1_eden_space,*vm.memory.pool.g1_old_gen,*vm.pause_time,*vm.thread*,*db.query.execution*`
|===


[role=label--enterprise-edition]
[[config_server.metrics.graphite.enabled]]
=== `server.metrics.graphite.enabled`

// label:enterprise-edition[Enterprise Edition]

.server.metrics.graphite.enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Set to `true` to enable exporting metrics to Graphite.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


[role=label--enterprise-edition]
[[config_server.metrics.graphite.interval]]
=== `server.metrics.graphite.interval`

// label:enterprise-edition[Enterprise Edition]

.server.metrics.graphite.interval
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The reporting interval for Graphite. That is, how often to send updated metrics to Graphite.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++30s+++
|===


[role=label--enterprise-edition]
[[config_server.metrics.graphite.server]]
=== `server.metrics.graphite.server`

// label:enterprise-edition[Enterprise Edition]

.server.metrics.graphite.server
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The hostname or IP address of the Graphite server.
|Valid values
a|A socket address in the format of `hostname:port`, `hostname`, or `:port`. If missing, it is acquired from server.default_listen_address.
|Default value
m|+++:2003+++
|===


[role=label--enterprise-edition]
[[config_server.metrics.jmx.enabled]]
=== `server.metrics.jmx.enabled`

// label:enterprise-edition[Enterprise Edition]

.server.metrics.jmx.enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Set to `true` to enable the JMX metrics endpoint.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[role=label--enterprise-edition]
[[config_server.metrics.prefix]]
=== `server.metrics.prefix`

// label:enterprise-edition[Enterprise Edition]

.server.metrics.prefix
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|A common prefix for the reported metrics field names.
|Valid values
a|A string.
|Default value
m|+++neo4j+++
|===


[role=label--enterprise-edition]
[[config_server.metrics.prometheus.enabled]]
=== `server.metrics.prometheus.enabled`

// label:enterprise-edition[Enterprise Edition]

.server.metrics.prometheus.enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Set to `true` to enable the Prometheus endpoint.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


[role=label--enterprise-edition]
[[config_server.metrics.prometheus.endpoint]]
=== `server.metrics.prometheus.endpoint`

// label:enterprise-edition[Enterprise Edition]

.server.metrics.prometheus.endpoint
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The hostname and port to use as Prometheus endpoint.
|Valid values
a|A socket address in the format of `hostname:port`, `hostname`, or `:port`. If missing, it is acquired from `server.default_listen_address`.
|Default value
m|+++localhost:2004+++
|===


== Neo4j Browser and client settings

Neo4j Browser and client settings apply only to Neo4j Browser and the client.


[role=label--enterprise-edition]
[[config_browser.allow_outgoing_connections]]
=== `browser.allow_outgoing_connections`

// label:enterprise-edition[Enterprise Edition]

.browser.allow_outgoing_connections
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Configure the policy for outgoing Neo4j Browser connections.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[role=label--enterprise-edition]
[[config_browser.credential_timeout]]
=== `browser.credential_timeout`

// label:enterprise-edition[Enterprise Edition]

.browser.credential_timeout
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Configure the Neo4j Browser to time out logged in users after this idle period. Setting this to 0 indicates no limit.
|Valid values
a|A duration (Valid units are: ns, μs, ms, s, m, h and d; default unit is s).
|Default value
m|+++0s+++
|===


[[config_browser.post_connect_cmd]]
=== `browser.post_connect_cmd`

.browser.post_connect_cmd
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Commands to be run when Neo4j Browser successfully connects to this server. Separate multiple commands with semi-colon.
|Valid values
a|A string.
|Default value
m|++++++
|===


[[config_browser.remote_content_hostname_whitelist]]
=== `browser.remote_content_hostname_whitelist`

.browser.remote_content_hostname_whitelist
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Whitelist of hosts for the Neo4j Browser to be allowed to fetch content from.
|Valid values
a|A string.
|Default value
m|+++guides.neo4j.com,localhost+++
|===


[role=label--enterprise-edition]
[[config_browser.retain_connection_credentials]]
=== `browser.retain_connection_credentials`

// label:enterprise-edition[Enterprise Edition]

.browser.retain_connection_credentials
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Configure the Neo4j Browser to store or not store user credentials.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[role=label--enterprise-edition]
[[config_browser.retain_editor_history]]
=== `browser.retain_editor_history`

// label:enterprise-edition[Enterprise Edition]

.browser.retain_editor_history
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Configure the Neo4j Browser to store or not store user editor history.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[[config_client.allow_telemetry]]
=== `client.allow_telemetry`

.client.allow_telemetry
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Configure client applications such as Browser and Bloom to send Product Analytics data.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


== Kubernetes settings

The Kubernetes settings are used to configure a cluster running on https://kubernetes.io/[Kubernetes^], where each server is running as a Kubernetes service.
The addresses of the other servers can be obtained using the List Service API, as described in the https://kubernetes.io/docs/reference/kubernetes-api/[Kubernetes API documentation^].
For more information, see xref:clustering/setup/discovery.adoc#clustering-discovery-k8s[Discovery in Kubernetes].


.Kubernetes settings
[role=label--enterprise-edition]
[[config_dbms.kubernetes.address]]
=== `dbms.kubernetes.address`

// label:enterprise-edition[Enterprise Edition]

.dbms.kubernetes.address
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Address for Kubernetes API.
|Valid values
a|A socket address in the format of `hostname:port`, `hostname`, or `:port`.
|Default value
m|+++kubernetes.default.svc:443+++
|===


[role=label--enterprise-edition]
[[config_dbms.kubernetes.ca_crt]]
=== `dbms.kubernetes.ca_crt`

// label:enterprise-edition[Enterprise Edition]

.dbms.kubernetes.ca_crt
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|File location of CA certificate for Kubernetes API.
|Valid values
a|A path.
|Default value
m|+++/var/run/secrets/kubernetes.io/serviceaccount/ca.crt+++
|===


[role=label--enterprise-edition]
[[config_dbms.kubernetes.cluster_domain]]
=== `dbms.kubernetes.cluster_domain`

// label:enterprise-edition[Enterprise Edition]

.dbms.kubernetes.cluster_domain
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Kubernetes cluster domain.
|Valid values
a|A string.
|Default value
m|+++cluster.local+++
|===


[role=label--enterprise-edition]
[[config_dbms.kubernetes.label_selector]]
=== `dbms.kubernetes.label_selector`

// label:enterprise-edition[Enterprise Edition]

.dbms.kubernetes.label_selector
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|LabelSelector for Kubernetes API.
|Valid values
a|A string.
|Default value
m|
|===


[role=label--enterprise-edition]
[[config_dbms.kubernetes.namespace]]
=== `dbms.kubernetes.namespace`

// label:enterprise-edition[Enterprise Edition]

.dbms.kubernetes.namespace
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|File location of namespace for Kubernetes API.
|Valid values
a|A path.
|Default value
m|+++/var/run/secrets/kubernetes.io/serviceaccount/namespace+++
|===


[role=label--enterprise-edition]
[[config_dbms.kubernetes.service_port_name]]
=== `dbms.kubernetes.service_port_name`

// label:enterprise-edition[Enterprise Edition]

.dbms.kubernetes.service_port_name
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Service port name for discovery for Kubernetes API.
|Valid values
a|A string.
|Default value
m|
|===


[role=label--enterprise-edition]
[[config_dbms.kubernetes.token]]
=== `dbms.kubernetes.token`

// label:enterprise-edition[Enterprise Edition]

.dbms.kubernetes.token
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|File location of token for Kubernetes API.
|Valid values
a|A path.
|Default value
m|+++/var/run/secrets/kubernetes.io/serviceaccount/token+++
|===


== Security settings

The security settings are used to configure the security of your Neo4j deployment.
Refer to the xref:security/index.adoc[Security] section for thorough information on security in Neo4j.


[[config_dbms.security.allow_csv_import_from_file_urls]]
=== `dbms.security.allow_csv_import_from_file_urls`


.dbms.security.allow_csv_import_from_file_urls
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Determines if Cypher will allow using file URLs when loading data using `LOAD CSV`. Setting this value to `false` will cause Neo4j to fail `LOAD CSV` clauses that load data from the file system.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[role=label--enterprise-edition]
[[config_dbms.security.auth_cache_max_capacity]]
=== `dbms.security.auth_cache_max_capacity`

// label:enterprise-edition[Enterprise Edition]

.dbms.security.auth_cache_max_capacity
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The maximum capacity for authentication and authorization caches (respectively).
|Valid values
a|An integer.
|Default value
m|+++10000+++
|===


[role=label--enterprise-edition]
[[config_dbms.security.auth_cache_ttl]]
=== `dbms.security.auth_cache_ttl`

// label:enterprise-edition[Enterprise Edition]

.dbms.security.auth_cache_ttl
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The time to live (TTL) for cached authentication and authorization info when using external auth providers (LDAP or plugin). Setting the TTL to 0 will disable auth caching. Disabling caching while using the LDAP auth provider requires the use of an LDAP system account for resolving authorization information.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++10m+++
|===


[role=label--enterprise-edition]
[[config_dbms.security.auth_cache_use_ttl]]
=== `dbms.security.auth_cache_use_ttl`

// label:enterprise-edition[Enterprise Edition]

.dbms.security.auth_cache_use_ttl
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Enable time-based eviction of the authentication and authorization info cache for external auth providers (LDAP or plugin). Disabling this setting will make the cache live forever and only be evicted when `<<config_dbms.security.auth_cache_max_capacity,dbms.security.auth_cache_max_capacity>>` is exceeded.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[[config_dbms.security.auth_enabled]]
=== `dbms.security.auth_enabled`

.dbms.security.auth_enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Enable auth requirement to access Neo4j.
|Valid values
a|A boolean.
|Default value
m|true
|===


[role=label--new-5.3]
[[config_config_dbms.security.auth_minimum_password_length]]
=== `dbms.security.auth_minimum_password_length`

// label:version-number[Neo4j 5.3]

.dbms.security.auth_minimum_password_length
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The minimum number of characters required in a password.
|Valid values
a|An integer that is minimum `1`.
|Default value
m|+++8+++
|===


[[config_dbms.security.auth_lock_time]]
=== `dbms.security.auth_lock_time`

.dbms.security.auth_lock_time
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The amount of time user account should be locked after a configured number of unsuccessful authentication attempts. The locked out user will not be able to log in until the lock period expires, even if correct credentials are provided. Setting this configuration option to a low value is not recommended because it might make it easier for an attacker to brute force the password.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`) that is minimum `0s`.
|Default value
m|+++5s+++
|===


[[config_dbms.security.auth_max_failed_attempts]]
=== `dbms.security.auth_max_failed_attempts`

.dbms.security.auth_max_failed_attempts
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The maximum number of unsuccessful authentication attempts before imposing a user lock for  the configured amount of time, as defined by `<<config_dbms.security.auth_lock_time,dbms.security.auth_lock_time>>`.The locked out user will not be able to log in until the lock period expires, even if correct  credentials are provided. Setting this configuration option to values less than 3 is not recommended because it might make  it easier for an attacker to brute force the password.
|Valid values
a|An integer that is minimum `0`.
|Default value
m|+++3+++
|===


[role=label--enterprise-edition]
[[config_dbms.security.authentication_providers]]
=== `dbms.security.authentication_providers`

// label:enterprise-edition[Enterprise Edition]

.dbms.security.authentication_providers
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|A list of security authentication providers containing the users and roles. This can be any of the built-in `native` or `ldap` providers, or it can be an externally provided plugin, with a custom name prefixed by `plugin-`, i.e. `plugin-<AUTH_PROVIDER_NAME>`. They will be queried in the given order when login is attempted.
|Valid values
a|A comma-separated list where each element is a string.
|Default value
m|+++native+++
|===


[role=label--enterprise-edition]
[[config_dbms.security.authorization_providers]]
=== `dbms.security.authorization_providers`

// label:enterprise-edition[Enterprise Edition]

.dbms.security.authorization_providers
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|A list of security authorization providers containing the users and roles. This can be any of the built-in `native` or `ldap` providers, or it can be an externally provided plugin, with a custom name prefixed by `plugin-`, i.e. `plugin-<AUTH_PROVIDER_NAME>`. They will be queried in the given order when login is attempted.
|Valid values
a|A comma-separated list where each element is a string.
|Default value
m|+++native+++
|===


[role=label--enterprise-edition]
[[config_dbms.security.cluster_status_auth_enabled]]
=== `dbms.security.cluster_status_auth_enabled`

// label:enterprise-edition[Enterprise Edition]

.dbms.security.cluster_status_auth_enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Require authorization for access to the Causal Clustering status endpoints.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[[config_dbms.security.http_access_control_allow_origin]]
=== `dbms.security.http_access_control_allow_origin`

.dbms.security.http_access_control_allow_origin
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Value of the Access-Control-Allow-Origin header sent over any HTTP or HTTPS connector. This defaults to '*', which allows broadest compatibility. Note that any URI provided here limits HTTP/HTTPS access to that URI only.
|Valid values
a|A string.
|Default value
m|+++*+++
|===


[[config_dbms.security.http_auth_allowlist]]
=== `dbms.security.http_auth_allowlist`

.dbms.security.http_auth_allowlist
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Defines an allowlist of http paths where Neo4j authentication is not required.
|Valid values
a|A comma-separated list where each element is a string.
|Default value
m|+++/,/browser.*+++
|===


[[config_dbms.security.http_strict_transport_security]]
=== `dbms.security.http_strict_transport_security`

.dbms.security.http_strict_transport_security
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Value of the HTTP Strict-Transport-Security (HSTS) response header. This header tells browsers that a webpage should only be accessed using HTTPS instead of HTTP. It is attached to every HTTPS response. Setting is not set by default so 'Strict-Transport-Security' header is not sent. Value is expected to contain directives like 'max-age', 'includeSubDomains' and 'preload'.
|Valid values
a|A string.
|Default value
m|
|===


[role=label--new-5.20]
[[config_dbms.security.http_static_content_security_policy_header]]
=== `dbms.security.http_static_content_security_policy_header`

.dbms.security.http_static_content_security_policy_header
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Defines the Content-Security-Policy header to return to content returned on static endpoints.
|Valid values
a|A string.
|Default value
m|+++default-src 'self'; script-src 'self' cdn.segment.com canny.io; img-src 'self' data:; style-src 'self' fonts.googleapis.com 'unsafe-inline'; font-src 'self' fonts.gstatic.com; base-uri 'none'; object-src 'none'; frame-ancestors 'none'; connect-src 'self' api.canny.io api.segment.io ws: wss: http: https:+++
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.key.name]]
=== `dbms.security.key.name`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.key.name
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Name of the 256 length AES encryption key, which is used for the symmetric encryption.
|Valid values
a|A string.
|Default value
m|+++aesKey+++
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.keystore.password]]
=== `dbms.security.keystore.password`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.keystore.password
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Password for accessing the keystore holding a 256 length AES encryption key, which is used for the symmetric encryption.
|Valid values
a|A secure string.
|Default value
m|
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.keystore.path]]
=== `dbms.security.keystore.path`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.keystore.path
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Location of the keystore holding a 256 length AES encryption key, which is used for the symmetric encryption of secrets held in system database.
|Valid values
a|A path.
|Default value
m|
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.ldap.authentication.attribute]]
=== `dbms.security.ldap.authentication.attribute`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.ldap.authentication.attribute
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The attribute to use when looking up users.
Using this setting requires `<<config_dbms.security.ldap.authentication.search_for_attribute,dbms.security.ldap.authentication.search_for_attribute>>` to be true and thus `<<config_dbms.security.ldap.authorization.system_username,dbms.security.ldap.authorization.system_username>>` and `<<config_dbms.security.ldap.authorization.system_password,dbms.security.ldap.authorization.system_password>>` to be configured.
|Valid values
a|A string that matches the pattern `[A-Za-z0-9-]*` (has to be a valid LDAP attribute name, only containing letters [A-Za-z], digits [0-9] and hyphens [-].).
|Default value
m|+++samaccountname+++
|===


[role=label--enterprise-edition]
[[config_dbms.security.ldap.authentication.cache_enabled]]
=== `dbms.security.ldap.authentication.cache_enabled`

// label:enterprise-edition[Enterprise Edition]

.dbms.security.ldap.authentication.cache_enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Determines if the result of authentication via the LDAP server should be cached or not. Caching is used to limit the number of LDAP requests that have to be made over the network for users that have already been authenticated successfully. A user can be authenticated against an existing cache entry (instead of via an LDAP server) as long as it is alive (see `<<config_dbms.security.auth_cache_ttl,dbms.security.auth_cache_ttl>>`).
An important consequence of setting this to `true` is that Neo4j then needs to cache a hashed version of the credentials in order to perform credentials matching. This hashing is done using a cryptographic hash function together with a random salt. Preferably a conscious decision should be made if this method is considered acceptable by the security standards of the organization in that this Neo4j instance is deployed.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[role=label--enterprise-edition]
[[config_dbms.security.ldap.authentication.mechanism]]
=== `dbms.security.ldap.authentication.mechanism`

// label:enterprise-edition[Enterprise Edition]

.dbms.security.ldap.authentication.mechanism
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|LDAP authentication mechanism. This is one of `simple` or a SASL mechanism supported by JNDI, for example `DIGEST-MD5`. `simple` is basic username and password authentication and SASL is used for more advanced mechanisms. See RFC 2251 LDAPv3 documentation for more details.
|Valid values
a|A string.
|Default value
m|+++simple+++
|===


[role=label--enterprise-edition]
[[config_dbms.security.ldap.authentication.search_for_attribute]]
=== `dbms.security.ldap.authentication.search_for_attribute`

// label:enterprise-edition[Enterprise Edition]

.dbms.security.ldap.authentication.search_for_attribute
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Perform authentication by searching for an unique attribute of a user.
Using this setting requires `<<config_dbms.security.ldap.authorization.system_username,dbms.security.ldap.authorization.system_username>>` and `<<config_dbms.security.ldap.authorization.system_password,dbms.security.ldap.authorization.system_password>>` to be configured.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.ldap.authentication.user_dn_template]]
=== `dbms.security.ldap.authentication.user_dn_template`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.ldap.authentication.user_dn_template
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|LDAP user DN template. An LDAP object is referenced by its distinguished name (DN), and a user DN is an LDAP fully-qualified unique user identifier. This setting is used to generate an LDAP DN that conforms with the LDAP directory's schema from the user principal that is submitted with the authentication token when logging in. The special token {0} is a placeholder where the user principal will be substituted into the DN string.
|Valid values
a|A string that Must be a string containing '{0}' to understand where to insert the runtime authentication principal..
|Default value
m|+++uid={0},ou=users,dc=example,dc=com+++
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.ldap.authorization.access_permitted_group]]
=== `dbms.security.ldap.authorization.access_permitted_group`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.ldap.authorization.access_permitted_group
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The LDAP group to which a user must belong to get any access to the system.Set this to restrict access to a subset of LDAP users belonging to a particular group. If this is not set, any user to successfully authenticate via LDAP will have access to the PUBLIC role and any other roles assigned to them via <<config_dbms.security.ldap.authorization.group_to_role_mapping,dbms.security.ldap.authorization.group_to_role_mapping>>.
|Valid values
a|A string.
|Default value
m|++++++
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.ldap.authorization.group_membership_attributes]]
=== `dbms.security.ldap.authorization.group_membership_attributes`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.ldap.authorization.group_membership_attributes
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|A list of attribute names on a user object that contains groups to be used for mapping to roles when LDAP authorization is enabled. This setting is ignored when `dbms.ldap_authorization_nested_groups_enabled` is `true`.
|Valid values
a|A comma-separated list where each element is a string, which Can not be empty.
|Default value
m|+++memberOf+++
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.ldap.authorization.group_to_role_mapping]]
=== `dbms.security.ldap.authorization.group_to_role_mapping`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.ldap.authorization.group_to_role_mapping
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|An authorization mapping from LDAP group names to Neo4j role names. The map should be formatted as a semicolon separated list of key-value pairs, where the key is the LDAP group name and the value is a comma separated list of corresponding role names. For example: group1=role1;group2=role2;group3=role3,role4,role5
You could also use whitespaces and quotes around group names to make this mapping more readable, for example:
----
`dbms.security.ldap.authorization.group_to_role_mapping`=\
         "cn=Neo4j Read Only,cn=users,dc=example,dc=com"      = reader;    \
         "cn=Neo4j Read-Write,cn=users,dc=example,dc=com"     = publisher; \
         "cn=Neo4j Schema Manager,cn=users,dc=example,dc=com" = architect; \
         "cn=Neo4j Administrator,cn=users,dc=example,dc=com"  = admin
----
|Valid values
a|A string that must be a semicolon-separated list of key-value pairs or empty.
|Default value
m|++++++
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.ldap.authorization.nested_groups_enabled]]
=== `dbms.security.ldap.authorization.nested_groups_enabled`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.ldap.authorization.nested_groups_enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|This setting determines whether multiple LDAP search results will be processed (as is required for the lookup of nested groups). If set to `true` then instead of using attributes on the user object to determine group membership (as specified by `<<config_dbms.security.ldap.authorization.group_membership_attributes,dbms.security.ldap.authorization.group_membership_attributes>>`), the `user` object will only be used to determine the user's Distinguished Name, which will subsequently be used with  `<<config_dbms.security.ldap.authorization.user_search_filter,dbms.security.ldap.authorization.user_search_filter>>` in order to perform a nested group search. The Distinguished Names of the resultant group search results will be used to determine roles.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.ldap.authorization.nested_groups_search_filter]]
=== `dbms.security.ldap.authorization.nested_groups_search_filter`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.ldap.authorization.nested_groups_search_filter
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The search template which will be used to find the nested groups which the user is a member of. The filter should contain the placeholder token `{0}` which will be substituted with the user's Distinguished Name (which is found for the specified user principle using `<<config_dbms.security.ldap.authorization.user_search_filter,dbms.security.ldap.authorization.user_search_filter>>`). The default value specifies Active Directory's LDAP_MATCHING_RULE_IN_CHAIN (aka 1.2.840.113556.1.4.1941) implementation which will walk the ancestry of group membership for the specified user.
|Valid values
a|A string.
|Default value
m|+++(&(objectclass=group)(member:1.2.840.113556.1.4.1941:={0}))+++
|===


[role=label--enterprise-edition]
[[config_dbms.security.ldap.authorization.system_password]]
=== `dbms.security.ldap.authorization.system_password`

// label:enterprise-edition[Enterprise Edition]

.dbms.security.ldap.authorization.system_password
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|An LDAP system account password to use for authorization searches when `<<config_dbms.security.ldap.authorization.use_system_account,dbms.security.ldap.authorization.use_system_account>>` is `true`.
|Valid values
a|A secure string.
|Default value
m|
|===


[role=label--enterprise-edition]
[[config_dbms.security.ldap.authorization.system_username]]
===  `dbms.security.ldap.authorization.system_username`

// label:enterprise-edition[Enterprise Edition]

.dbms.security.ldap.authorization.system_username
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|An LDAP system account username to use for authorization searches when `<<config_dbms.security.ldap.authorization.use_system_account,dbms.security.ldap.authorization.use_system_account>>` is `true`. Note that the `<<config_dbms.security.ldap.authentication.user_dn_template,dbms.security.ldap.authentication.user_dn_template>>` will not be applied to this username, so you may have to specify a full DN.
|Valid values
a|A string.
|Default value
m|
|===


[role=label--enterprise-edition]
[[config_dbms.security.ldap.authorization.use_system_account]]
=== `dbms.security.ldap.authorization.use_system_account`

// label:enterprise-edition[Enterprise Edition]

.dbms.security.ldap.authorization.use_system_account
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Perform LDAP search for authorization info using a system account instead of the user's own account.
If this is set to `false` (default), the search for group membership will be performed directly after authentication using the LDAP context bound with the user's own account. The mapped roles will be cached for the duration of `<<config_dbms.security.auth_cache_ttl,dbms.security.auth_cache_ttl>>`, and then expire, requiring re-authentication. To avoid frequently having to re-authenticate sessions you may want to set a relatively long auth cache expiration time together with this option. +
 NOTE: This option will only work if the users are permitted to search for their own group membership attributes in the directory.
If this is set to `true`, the search will be performed using a special system account user with read access to all the users in the directory. You need to specify the username and password using the settings `<<config_dbms.security.ldap.authorization.system_username,dbms.security.ldap.authorization.system_username>>` and `<<config_dbms.security.ldap.authorization.system_password,dbms.security.ldap.authorization.system_password>>` with this option. Note that this account only needs read access to the relevant parts of the LDAP directory and does not need to have access rights to Neo4j, or any other systems.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.ldap.authorization.user_search_base]]
=== `dbms.security.ldap.authorization.user_search_base`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.ldap.authorization.user_search_base
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The name of the base object or named context to search for user objects when LDAP authorization is enabled. A common case is that this matches the last part of `<<config_dbms.security.ldap.authentication.user_dn_template,dbms.security.ldap.authentication.user_dn_template>>`.
|Valid values
a|A string that Can not be empty.
|Default value
m|+++ou=users,dc=example,dc=com+++
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.ldap.authorization.user_search_filter]]
=== `dbms.security.ldap.authorization.user_search_filter`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.ldap.authorization.user_search_filter
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The LDAP search filter to search for a user principal when LDAP authorization is enabled. The filter should contain the placeholder token {0} which will be substituted for the user principal.
|Valid values
a|A string.
|Default value
m|+++(&(objectClass=*)(uid={0}))+++
|===


[role=label--enterprise-edition]
[[config_dbms.security.ldap.connection_timeout]]
=== `dbms.security.ldap.connection_timeout`

// label:enterprise-edition[Enterprise Edition]

.dbms.security.ldap.connection_timeout
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The timeout for establishing an LDAP connection. If a connection with the LDAP server cannot be established within the given time the attempt is aborted. A value of 0 means to use the network protocol's (i.e., TCP's) timeout value.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++30s+++
|===


[role=label--enterprise-edition]
[[config_dbms.security.ldap.host]]
=== `dbms.security.ldap.host`

// label:enterprise-edition[Enterprise Edition]

.dbms.security.ldap.host
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|URL of LDAP server to use for authentication and authorization. The format of the setting is `<protocol>://<hostname>:<port>`, where hostname is the only required field. The supported values for protocol are `ldap` (default) and `ldaps`. The default port for `ldap` is 389 and for `ldaps` 636. For example: `ldaps://ldap.example.com:10389`.
You may want to consider using STARTTLS (`<<config_dbms.security.ldap.use_starttls,dbms.security.ldap.use_starttls>>`) instead of LDAPS for secure connections, in which case the correct protocol is `ldap`.
|Valid values
a|A string.
|Default value
m|+++localhost+++
|===


[role=label--enterprise-edition]
[[config_dbms.security.ldap.read_timeout]]
=== `dbms.security.ldap.read_timeout`

// label:enterprise-edition[Enterprise Edition]

.dbms.security.ldap.read_timeout
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The timeout for an LDAP read request (i.e. search). If the LDAP server does not respond within the given time the request will be aborted. A value of 0 means wait for a response indefinitely.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++30s+++
|===


[role=label--enterprise-edition]
[[config_dbms.security.ldap.referral]]
=== `dbms.security.ldap.referral`

// label:enterprise-edition[Enterprise Edition]

.dbms.security.ldap.referral
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The LDAP referral behavior when creating a connection. This is one of `follow`, `ignore` or `throw`.

* `follow` automatically follows any referrals
* `ignore` ignores any referrals
* `throw` throws an exception, which will lead to authentication failure.
|Valid values
a|A string.
|Default value
m|+++follow+++
|===


[role=label--enterprise-edition]
[[config_dbms.security.ldap.use_starttls]]
=== `dbms.security.ldap.use_starttls`

// label:enterprise-edition[Enterprise Edition]

.dbms.security.ldap.use_starttls
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Use secure communication with the LDAP server using opportunistic TLS. First an initial insecure connection will be made with the LDAP server, and a STARTTLS command will be issued to negotiate an upgrade of the connection to TLS before initiating authentication.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


[role=label--enterprise-edition]
[[config_dbms.security.log_successful_authentication]]
=== `dbms.security.log_successful_authentication`

// label:enterprise-edition[Enterprise Edition]

.dbms.security.log_successful_authentication
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Set to log successful authentication events to the security log. If this is set to `false` only failed authentication events will be logged, which could be useful if you find that the successful events spam the logs too much, and you do not require full auditing capability.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[role=label--enterprise-edition]
[[config_dbms.security.logs.ldap.groups_at_debug_level_enabled]]
=== `dbms.security.logs.ldap.groups_at_debug_level_enabled`

// label:enterprise-edition[Enterprise Edition]

.dbms.security.logs.ldap.groups_at_debug_level_enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|When set to `true`, will log the groups retrieved from the ldap server. This will only take effect when the security log level is set to `DEBUG`.WARNING: It is strongly advised that this is set to `false` when running in a production environment in order to prevent logging of sensitive information.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.oidc.-provider-.audience]]
=== `dbms.security.oidc.<provider>.audience`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.oidc.<provider>.audience
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Expected values of the Audience (aud) claim in the id token.
|Valid values
a|A comma-separated list where each element is a string, which Can not be empty.
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.oidc.-provider-.auth_endpoint]]
=== `dbms.security.oidc.<provider>.auth_endpoint`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.oidc.<provider>.auth_endpoint
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The OIDC authorization endpoint. If this is not supplied Neo4j will attempt to discover it from the well_known_discovery_uri.
|Valid values
a|a URI
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.oidc.-provider-.auth_flow]]
=== `dbms.security.oidc.<provider>.auth_flow`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.oidc.<provider>.auth_flow
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The OIDC flow to use. This is exposed to clients via the discovery endpoint. Supported values are `pkce` and `implicit`
|Valid values
a|One of [PKCE, IMPLICIT].
|Default value
m|+++PKCE+++
|===


[role=label--enterprise-edition label--dynamic label--deprecated]
[[config_dbms.security.oidc.-provider-.auth_params]]
=== `dbms.security.oidc.<provider>.auth_params`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic] label:deprecated[Deprecated]

.dbms.security.oidc.<provider>.auth_params
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Optional additional parameters that the auth endpoint requires. Please use params instead. The map is a semicolon separated list of key-value pairs. For example: `k1=v1;k2=v2`.
|Valid values
a|A simple key value map pattern `k1=v1;k2=v2`.
|Default value
m|+++{}+++
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.oidc.-provider-.authorization.group_to_role_mapping]]
=== `dbms.security.oidc.<provider>.authorization.group_to_role_mapping`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.oidc.<provider>.authorization.group_to_role_mapping
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|An authorization mapping from IdP group names to Neo4j role names. The map should be formatted as a semicolon separated list of key-value pairs, where the key is the IdP group name and the value is a comma separated list of corresponding role names. For example: group1=role1;group2=role2;group3=role3,role4,role5
You could also use whitespaces and quotes around group names to make this mapping more readable, for example:
----
dbms.security.oidc.<provider>.authorization.group_to_role_mapping=\
         "Neo4j Read Only"      = reader;    \
         "Neo4j Read-Write"     = publisher; \
         "Neo4j Schema Manager" = architect; \
         "Neo4j Administrator"  = admin
----
|Valid values
a|A string that must be semicolon-separated list of key-value pairs or empty
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.oidc.-provider-.claims.groups]]
=== `dbms.security.oidc.<provider>.claims.groups`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.oidc.<provider>.claims.groups
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The claim to use as the list of groups in Neo4j. These could be Neo4J roles directly, or can be mapped using dbms.security.oidc.<provider>.authorization.group_to_role_mapping.
From Neo4j 5.4, the JWT claim may also contain a single group returned as A string. as well as a list of groups as was previously required.

|Valid values
a|A string.
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.oidc.-provider-.claims.username]]
=== `dbms.security.oidc.<provider>.claims.username`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.oidc.<provider>.claims.username
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The claim to use as the username in Neo4j. This would typically be sub, but in some situations it may be be desirable to use something else such as email.
|Valid values
a|A string.
|Default value
m|+++sub+++
|===


[role=label--enterprise-edition label--dynamic label--deprecated]
[[config_dbms.security.oidc.-provider-.client_id]]
=== `dbms.security.oidc.<provider>.client_id`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic] label:deprecated[Deprecated]

.dbms.security.oidc.<provider>.client_id
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Client id. Not used. This value was previously used to validate the `azp` claim in the id_token, but this validation has been removed in line with updates to the OIDC specification.
|Valid values
a|A string.
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.oidc.-provider-.config]]
=== `dbms.security.oidc.<provider>.config`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.oidc.<provider>.config
[cols="<1s,<4a"]
|===
|Description
a|The accepted values (all optional) are:

* `principal`: in which JWT claim the user's email address is specified, email is the default. This is the value that will be shown in browser.
* `code_challenge_method`: default is `S256` and it's the only supported method at this moment. This setting applies only for pkce auth flow
* `token_type_principal`: the options are almost always either `access_token`, which is the default, or `id_token`.
* `token_type_authentication`: the options are almost always either `access_token`, which is the default, or `id_token`.
* `implicit_flow_requires_nonce`: true or false. Defaults to false.

|Valid values
a|A simple key-value map pattern `k1=v1;k2=v2`. Valid key options are: `[implicit_flow_requires_nonce, token_type_authentication, token_type_principal, principal, code_challenge_method]`.
|Default value
m|+++{}+++
|===


[[config_dbms.security.logs.oidc.jwt_claims_at_debug_level_enabled]]
=== `dbms.security.logs.oidc.jwt_claims_at_debug_level_enabled`

.dbms.security.logs.oidc.jwt_claims_at_debug_level_enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|When set to `true`, it logs the claims from the JWT. This will only take effect when the security log level is set to `DEBUG`. +
[WARNING]
====
It is strongly advised that this is set to `false` when running in a production environment in order to prevent logging of sensitive information. Also note that the contents of the JWT claims set can change over time because they are dependent entirely upon the ID provider.
====
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


[role=label--enterprise-edition]
[[config_dbms.security.oidc.-provider-.display_name]]
=== `dbms.security.oidc.<provider>.display_name`

// label:enterprise-edition[Enterprise Edition]

.dbms.security.oidc.<provider>.display_name
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The user-facing name of the provider as provided by the discovery endpoint to clients (Bloom, Browser etc.).
|Valid values
a|A string.
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.oidc.-provider-.get_groups_from_user_info]]
=== `dbms.security.oidc.<provider>.get_groups_from_user_info`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.oidc.<provider>.get_groups_from_user_info
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|When turned on, Neo4j gets the groups from the provider user info endpoint.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.oidc.-provider-.get_username_from_user_info]]
=== `dbms.security.oidc.<provider>.get_username_from_user_info`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.oidc.<provider>.get_username_from_user_info
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|When turned on, Neo4j gets the username from the provider user info endpoint.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.oidc.-provider-.issuer]]
=== `dbms.security.oidc.<provider>.issuer`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.oidc.<provider>.issuer
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The expected value of the iss claim in the id token. If this is not supplied Neo4j will attempt to discover it from the well_known_discovery_uri.
|Valid values
a|A string.
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.oidc.-provider-.jwks_uri]]
=== `dbms.security.oidc.<provider>.jwks_uri`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.oidc.<provider>.jwks_uri
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The location of the JWK public key set for the identity provider. If this is not supplied Neo4j will attempt to discover it from the well_known_discovery_uri.
|Valid values
a|a URI
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.oidc.-provider-.params]]
=== `dbms.security.oidc.<provider>.params`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.oidc.<provider>.params
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The map is a semicolon separated list of key-value pairs. For example: `k1=v1;k2=v2`.
The user should at least provide:
----
  client_id: the SSO Idp client idenfifier.
  response_type: code if auth_flow is pkce or token for implicit auth_flow.
  scope: often containing a subset of 'email profile openid groups'.
----
For example: `client_id=my-client-id;response_type=code;scope=openid profile email`.
|Valid values
a|A simple key-value map pattern `k1=v1;k2=v2`. Required key options are: `[scope, client_id, response_type]`.
|Default value
m|+++{}+++
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.oidc.-provider-.token_endpoint]]
=== `dbms.security.oidc.<provider>.token_endpoint`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.oidc.<provider>.token_endpoint
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The OIDC token endpoint. If this is not supplied Neo4j will attempt to discover it from the well_known_discovery_uri.
|Valid values
a|a URI
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.oidc.-provider-.token_params]]
=== `dbms.security.oidc.<provider>.token_params`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.oidc.<provider>.token_params
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Optional query parameters that the token endpoint requires. The map is a semicolon separated list of key-value pairs. For example: `k1=v1;k2=v2`.If the token endpoint requires a client_secret then this parameter should contain `client_secret=super-secret`
|Valid values
a|A simple key value map pattern `k1=v1;k2=v2`.
|Default value
m|+++{}+++
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.oidc.-provider-.user_info_uri]]
=== `dbms.security.oidc.<provider>.user_info_uri`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.oidc.<provider>.user_info_uri
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The identity providers user info uri.
|Valid values
a|a URI
|===


[role=label--enterprise-edition label--dynamic]
[[config_dbms.security.oidc.-provider-.well_known_discovery_uri]]
=== `dbms.security.oidc.<provider>.well_known_discovery_uri`

// label:enterprise-edition[Enterprise Edition] label:dynamic[Dynamic]

.dbms.security.oidc.<provider>.well_known_discovery_uri
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|OpenID Connect Discovery endpoint used to fetch identity provider settings. If not provided, `issuer`, `jwks_uri`, `auth_endpoint` should be present. If the auth_flow is pkce, `token_endpoint` should also be provided.
|Valid values
a|a URI
|===


[[config_dbms.security.procedures.allowlist]]
=== `dbms.security.procedures.allowlist`

.dbms.security.procedures.allowlist
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|A list of procedures (comma separated) that are to be loaded. The list may contain both fully-qualified procedure names, and partial names with the wildcard `*`. The default (`*`) loads all procedures. If no value is specified, no procedures will be loaded.
|Valid values
a|A comma-separated list where each element is a string.
|Default value
m|+++*+++
|===


[[config_dbms.security.procedures.unrestricted]]
=== `dbms.security.procedures.unrestricted`

.dbms.security.procedures.unrestricted
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|A list of procedures and user-defined functions (comma separated) that are allowed full access to the database. The list may contain both fully-qualified procedure names, and partial names with the wildcard `*`. Note that this enables these procedures to bypass security. Use with caution.
|Valid values
a|A comma-separated list where each element is a string.
|Default value
m|++++++
|===


[[config_dbms.netty.ssl.provider]]
=== `dbms.netty.ssl.provider`

.dbms.netty.ssl.provider
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Netty SSL provider.
|Valid values
a|One of [JDK, OPENSSL, OPENSSL_REFCNT].
|Default value
m|+++JDK+++
|===


== Server directories settings

The server directories settings can be used to change the default locations of your Neo4j files.
For more information, see xref:configuration/file-locations.adoc[Default file locations].


[role=label--enterprise-edition]
[[config_server.directories.cluster_state]]
=== `server.directories.cluster_state`

// label:enterprise-edition[Enterprise Edition]

.server.directories.cluster_state
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Directory to hold cluster state including Raft log.
|Valid values
a|A path. If relative, it is resolved from server.directories.data.
|Default value
m|+++cluster-state+++
|===


[[config_server.directories.data]]
=== `server.directories.data`

.server.directories.data
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Path of the data directory. You must not configure more than one Neo4j installation to use the same data directory.
|Valid values
a|A path. If relative, it is resolved from server.directories.neo4j_home.
|Default value
m|+++data+++
|===


[[config_server.directories.dumps.root]]
=== `server.directories.dumps.root`

.server.directories.dumps.root
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Root location where Neo4j will store database dumps optionally produced when dropping said databases.
|Valid values
a|A path. If relative, it is resolved from server.directories.data.
|Default value
m|+++dumps+++
|===


[[config_server.directories.import]]
=== `server.directories.import`

.server.directories.import
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Sets the root directory for file URLs used with the Cypher `LOAD CSV` clause. This should be set to a directory relative to the Neo4j installation path, restricting access to only those files within that directory and its subdirectories. For example the value "import" will only enable access to files within the 'import' folder. Removing this setting will disable the security feature, allowing all files in the local system to be imported. Setting this to an empty field will allow access to all files within the Neo4j installation folder.
|Valid values
a|A path. If relative, it is resolved from server.directories.neo4j_home.
|Default value
m|
|===


[[config_server.directories.lib]]
=== `server.directories.lib`

.server.directories.lib
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Path of the lib directory.
|Valid values
a|A path. If relative, it is resolved from server.directories.neo4j_home.
|Default value
m|+++lib+++
|===


[[config_server.directories.licenses]]
=== `server.directories.licenses`

.server.directories.licenses
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Path of the licenses directory.
|Valid values
a|A path. If relative, it is resolved from server.directories.neo4j_home.
|Default value
m|+++licenses+++
|===


[[config_server.directories.logs]]
=== `server.directories.logs`

.server.directories.logs
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Path of the logs directory.
|Valid values
a|A path. If relative, it is resolved from server.directories.neo4j_home.
|Default value
m|+++logs+++
|===


[role=label--enterprise-edition]
[[config_server.directories.metrics]]
=== `server.directories.metrics`

// label:enterprise-edition[Enterprise Edition]

.server.directories.metrics
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The target location of the CSV files: a path to a directory wherein a CSV file per reported field  will be written.
|Valid values
a|A path. If relative, it is resolved from server.directories.neo4j_home.
|Default value
m|+++metrics+++
|===


[[config_server.directories.neo4j_home]]
=== `server.directories.neo4j_home`

.server.directories.neo4j_home
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Root relative to which directory settings are resolved. Calculated and set by the server on startup. Defaults to the current working directory.
|Valid values
a|A path that is absolute.
|Default value
m|
|===


[[config_server.directories.plugins]]
=== `server.directories.plugins`

.server.directories.plugins
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Location of the database plugin directory. Compiled Java JAR files that contain database procedures will be loaded if they are placed in this directory.
|Valid values
a|A path. If relative, it is resolved from server.directories.neo4j_home.
|Default value
m|+++plugins+++
|===


[[config_server.directories.run]]
=== `server.directories.run`

.server.directories.run
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Path of the run directory. This directory holds Neo4j's runtime state, such as a pidfile when it is running in the background. The pidfile is created when starting neo4j and removed when stopping it. It may be placed on an in-memory filesystem such as tmpfs.
|Valid values
a|A path. If relative, it is resolved from server.directories.neo4j_home.
|Default value
m|+++run+++
|===


[[config_server.directories.script.root]]
=== `server.directories.script.root`

.server.directories.script.root
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Root location where Neo4j will store scripts for configured databases.
|Valid values
a|A path. If relative, it is resolved from server.directories.data.
|Default value
m|+++scripts+++
|===


[[config_server.directories.transaction.logs.root]]
===  `server.directories.transaction.logs.root`

.server.directories.transaction.logs.root
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Root location where Neo4j will store transaction logs for configured databases.
|Valid values
a|A path. If relative, it is resolved from server.directories.data.
|Default value
m|+++transactions+++
|===

== Server settings

Server settings apply only to the specific server and can be varied between configuration files across a cluster/DBMS.


[role=label--enterprise-edition]
[[config_server.backup.enabled]]
=== `server.backup.enabled`

// label:enterprise-edition[Enterprise Edition]

.server.backup.enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Enable support for running online backups.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[role=label--enterprise-edition]
[[config_server.backup.exec_connector.command]]
=== `server.backup.exec_connector.command`

// label:enterprise-edition[Enterprise Edition]

.server.backup.exec_connector.command
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Command to execute for ExecDataConnector list
|Valid values
a|A string.
|Default value
m|++++++
|===


[[config_server.backup.exec_connector.command_timeout]]


[role=label--enterprise-edition]
[[config_server.backup.exec_connector.scheme]]
=== `server.backup.exec_connector.scheme`

// label:enterprise-edition[Enterprise Edition]

.server.backup.exec_connector.scheme
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Schemes ExecDataConnector will match on
|Valid values
a|A comma-separated list where each element is a string.
|Default value
m|
|===


[[config_server.backup.exec_connector.tls_ca]]


[role=label--enterprise-edition]
[[config_server.backup.listen_address]]
=== `server.backup.listen_address`

// label:enterprise-edition[Enterprise Edition]

.server.backup.listen_address
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Network interface and port for the backup server to listen on.
|Valid values
a|A socket address in the format of `hostname:port`, `hostname`, or `:port`.
|Default value
m|+++127.0.0.1:6362+++
|===


[role=label--enterprise-edition]
[[config_server.backup.store_copy_max_retry_time_per_request]]
=== `server.backup.store_copy_max_retry_time_per_request`

// label:enterprise-edition[Enterprise Edition]

.server.backup.store_copy_max_retry_time_per_request
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Maximum retry time per request during store copy. Regular store files and indexes are downloaded in separate requests during store copy. This configures the maximum time failed requests are allowed to resend.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++20m+++
|===


[[config_server.config.strict_validation.enabled]]
=== `server.config.strict_validation.enabled`

.server.config.strict_validation.enabled
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|A strict configuration validation will prevent the database from starting up if unknown configuration options are specified in the neo4j settings namespace (such as dbms., cypher., etc) or if settings are declared multiple times.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[role=label--dynamic]
[[config_server.databases.default_to_read_only]]
=== `server.databases.default_to_read_only`

// label:dynamic[Dynamic]

.server.databases.default_to_read_only
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Whether or not any database on this instance is read_only by default. If false, individual databases may be marked as read_only using server.database.read_only. If true, individual databases may be marked as writable using <<config_server.databases.writable,server.databases.writable>>.
|Valid values
a|A boolean.
|Default value
m|+++false+++
|===


[role=label--dynamic]
[[config_server.databases.read_only]]
=== `server.databases.read_only`

// label:dynamic[Dynamic]

.server.databases.read_only
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|List of databases for which to prevent write queries. Databases not included in this list maybe read_only anyway depending upon the value of <<config_server.databases.default_to_read_only,server.databases.default_to_read_only>>.
|Valid values
a| A comma-separated set where each element is a valid database name containing only alphabetic characters, numbers, dots, and dashes with a length between 3 and 63 characters, starting with an alphabetic character but not with the name system.
|Default value
m|++++++
|===


[role=label--dynamic]
[[config_server.databases.writable]]
=== `server.databases.writable`

// label:dynamic[Dynamic]

.server.databases.writable
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|List of databases for which to allow write queries. Databases not included in this list will allow write queries anyway, unless <<config_server.databases.default_to_read_only,server.databases.default_to_read_only>> is set to true.
|Valid values
a|A comma-separated set where each element is a valid database name containing only alphabetic characters, numbers, dots, and dashes with a length between 3 and 63 characters, starting with an alphabetic character but not with the name system.
|Default value
m|++++++
|===


[role=label--enterprise-edition]
[[config_server.dynamic.setting.allowlist]]
=== `server.dynamic.setting.allowlist`

// label:enterprise-edition[Enterprise Edition]

.server.dynamic.setting.allowlist
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|A list of setting name patterns (comma separated) that are allowed to be dynamically changed. The list may contain both full setting names, and partial names with the wildcard `*`. If this setting is left empty all dynamic settings updates will be blocked.
|Valid values
a|A comma-separated list where each element is a string.
|Default value
m|+++*+++
|===


[[config_server.jvm.additional]]
=== `server.jvm.additional`

.server.jvm.additional
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Additional JVM arguments. Argument order can be significant. To use a Java commercial feature, the argument to unlock commercial features must precede the argument to enable the specific feature in the config value string.
|Valid values
a|One or more jvm arguments.
|Default value
m|
|===


[role=label--enterprise-edition label--deprecated-5.6]
[[config_server.max_databases]]
=== `server.max_databases`

// label:enterprise-edition[Enterprise Edition] label:deprecated[Deprecated in 5.6]

.server.max_databases
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The maximum number of databases.
|Valid values
a|A long that is minimum `2`.
|Default value
m|+++100+++
|Replaced by
a|<<config_dbms.max_databases,`dbms.max_databases`>>
|===


[role=label--enterprise-edition]
[[config_server.panic.shutdown_on_panic]]
=== `server.panic.shutdown_on_panic`

// label:enterprise-edition[Enterprise Edition]

.server.panic.shutdown_on_panic
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|If there is a Database Management System Panic (an irrecoverable error) should the neo4j process shut down or continue running. Following a DbMS panic it is likely that a significant amount of functionality will be lost. Recovering full functionality will require a Neo4j restart. Default is `false` except for Neo4j Enterprise Edition deployments running on Kubernetes where it is `true`.
|Valid values
a|A boolean.
|Default value
m|false
|===


[[config_server.threads.worker_count]]
=== `server.threads.worker_count`

.server.threads.worker_count
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Number of Neo4j worker threads. This setting is only valid for REST and does not influence bolt-server. It sets the number of worker threads for the Jetty server used by neo4j-server. This option can be tuned when you plan to execute multiple, concurrent REST requests, to get more throughput from the database. Your OS might enforce a lower limit than the maximum value specified here. Number of available processors, or 500 for machines that have more than 500 processors.
|Valid values
a|An integer that is in the range `1` to `44738`.
|Default value
m|
|===


[[config_server.unmanaged_extension_classes]]
=== `server.unmanaged_extension_classes`

.server.unmanaged_extension_classes
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Comma-separated list of <classname>=<mount point> for unmanaged extensions.
|Valid values
a|A comma-separated list where each element is `<classname>=<mount point>` string.
|Default value
m|++++++
|===


[[config_server.windows_service_name]]
=== `server.windows_service_name`

.server.windows_service_name
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Name of the Windows Service managing Neo4j when installed using `neo4j install-service`. Only applicable on Windows OS. +
NOTE: This must be unique for each installation.
|Valid values
a|A string.
|Default value
m|+++neo4j+++
|===


== Transaction settings

The transaction settings helps you manage the transactions in your database, for example, the transaction timeout, the lock acquisition timeout, the maximum number of concurrently running transactions, etc.
For more information, see xref:/database-internals/transaction-management.adoc#_manage-transactions[Manage transactions] and xref:/database-internals/concurrent-data-access.adoc[Concurrent data access].


[role=label--dynamic]
[[config_db.lock.acquisition.timeout]]
=== `db.lock.acquisition.timeout`

// label:dynamic[Dynamic]

.db.lock.acquisition.timeout
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The maximum time interval within which lock should be acquired. Zero (default) means the timeout is disabled.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++0s+++
|===


[[config_db.shutdown_transaction_end_timeout]]
=== `db.shutdown_transaction_end_timeout`

.db.shutdown_transaction_end_timeout
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The maximum amount of time to wait for running transactions to complete before allowing initiated database shutdown to continue.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++10s+++
|===


[role=label--dynamic]
[[config_db.transaction.bookmark_ready_timeout]]
=== `db.transaction.bookmark_ready_timeout`

// label:dynamic[Dynamic]

.db.transaction.bookmark_ready_timeout
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The maximum amount of time to wait for the database state represented by the bookmark.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`) that is minimum `1s`.
|Default value
m|+++30s+++
|===


[role=label--dynamic]
[[config_db.transaction.concurrent.maximum]]
=== `db.transaction.concurrent.maximum`

// label:dynamic[Dynamic]

.db.transaction.concurrent.maximum
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The maximum number of concurrently running transactions. If set to 0, the limit is disabled.
|Valid values
a|An integer.
|Default value
m|+++1000+++
|===


[[config_db.transaction.monitor.check.interval]]
=== `db.transaction.monitor.check.interval`

.db.transaction.monitor.check.interval
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Configures the time interval between transaction monitor checks. Determines how often the monitor thread will check a transaction for timeout.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++2s+++
|===


[role=label--dynamic]
[[config_db.transaction.sampling.percentage]]
=== `db.transaction.sampling.percentage`

// label:dynamic[Dynamic]

.db.transaction.sampling.percentage
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Transaction sampling percentage.
|Valid values
a|An integer that is in the range `1` to `100`.
|Default value
m|+++5+++
|===


[role=label--dynamic]
[[config_db.transaction.timeout]]
=== `db.transaction.timeout`

// label:dynamic[Dynamic]

.db.transaction.timeout
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|The maximum time interval of a transaction within which it should be completed.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++0s+++
|===


[role=label--dynamic]
[[config_db.transaction.tracing.level]]
=== `db.transaction.tracing.level`

// label:dynamic[Dynamic]

.db.transaction.tracing.level
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Transaction creation tracing level.
|Valid values
a|One of [DISABLED, SAMPLE, ALL].
|Default value
m|+++DISABLED+++
|===

[role=label--new-5.20]
[[config_server.http.transaction_idle_timeout]]
=== `server.http.transaction_idle_timeout`

.server.http.transaction_idle_timeout
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Timeout for idle transactions in the HTTP Server. +
NOTE: This is different from 'db.transaction.timeout' which will timeout the underlying transaction.
|Valid values
a|A duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d`; default unit is `s`).
|Default value
m|+++30s+++
|===


== Transaction log settings

Transaction logs keep the list of transactions that have not yet been applied to the store files.
This is necessary for recovery.
The following settings configure the number of transaction logs left after a pruning operation and the size of the transaction log files.

See also <<Checkpoint settings>>.


[[config_db.recovery.fail_on_missing_files]]
=== `db.recovery.fail_on_missing_files`

.db.recovery.fail_on_missing_files
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|If `true`, Neo4j will abort recovery if transaction log files are missing. Setting this to `false` will allow Neo4j to create new empty missing files for the already existing database, but the integrity of the database might be compromised.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[[config_db.tx_log.buffer.size]]
=== `db.tx_log.buffer.size`

.db.tx_log.buffer.size
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|On serialization of transaction logs, they will be temporary stored in the byte buffer that will be flushed at the end of the transaction or at any moment when the buffer will be full.
By default, the size of the byte buffer is based on the number of available CPU's with a minimal buffer size of 512KB. Every other 4 CPU's will add another 512KB into the buffer size. The maximal buffer size in this default scheme is 4MB taking into account that you can have one transaction log writer per database in multi-database env. For example, runtime with 4 CPUs will have the buffer size of 1MB; runtime with 8 CPUs will have the buffer size of 1MB 512KB; runtime with 12 CPUs will have the buffer size of 2MB.
|Valid values
a|A long that is minimum `131072`.
|Default value
m|
|===


[role=label--dynamic]
[[config_db.tx_log.preallocate]]
=== `db.tx_log.preallocate`

// label:dynamic[Dynamic]

.db.tx_log.preallocate
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Specify if Neo4j should try to preallocate the logical log file in advance.
It optimizes file system by ensuring there is room to accommodate newly generated files and avoid file-level fragmentation.
|Valid values
a|A boolean.
|Default value
m|+++true+++
|===


[role=label--changed-5.13 label--dynamic]
[[config_db.tx_log.rotation.retention_policy]]
=== `db.tx_log.rotation.retention_policy`

// label:dynamic[Dynamic] label:changed[Default value changed in 5.13]

.db.tx_log.rotation.retention_policy
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Specify how long Neo4j should keep logical transaction logs to backup the database.
For example, `10 days` prunes logical logs that only contain transactions older than 10 days.
Alternatively, `100k txs` keeps the 100k latest transactions from each database and prunes any older transactions.
From Neo4j 5.9 onwards, you can optionally add a period-based restriction to the size of logs to keep.
For example, `2 days 1G` prunes logical logs that only contain transactions older than 2 days or are larger than 1G.
|Valid values
a| A string that matches the pattern `^(true\|keep_all\|false\|keep_none\|(\d+[KkMmGg]?( (files\|size\|txs\|entries\|hours( \d+[KkMmGg]?)?\|days( \d+[KkMmGg]?)?))))$` (Must be `true` or `keep_all`, `false` or `keep_none`, or of format `<number><optional unit> <type> <optional space restriction>`. Valid units are `K`, `M` and `G`. Valid types are `files`, `size`, `txs`, `entries`, `hours` and `days`. Valid optional space restriction is a logical log space restriction like 100M. For example, `100M size` will limit logical log space on disk to 100MiB per database, and `200K txs` will limit the number of transactions kept to 200 000 per database.).
|Default value
m|+++2 days 2G+++
|===


[role=label--dynamic]
[[config_db.tx_log.rotation.size]]
=== `db.tx_log.rotation.size`

// label:dynamic[Dynamic]

.db.tx_log.rotation.size
[frame="topbot", stripes=odd, grid="cols", cols="<1s,<4"]
|===
|Description
a|Specifies at which file size the logical log will auto-rotate. The minimum accepted value is 128 KiB.
|Valid values
a|A byte size (valid multipliers are `B`, `KiB`, `KB`, `K`, `kB`, `kb`, `k`, `MiB`, `MB`, `M`, `mB`, `mb`, `m`, `GiB`, `GB`, `G`, `gB`, `gb`, `g`, `TiB`, `TB`, `PiB`, `PB`, `EiB`, `EB`) that is minimum `128.00KiB`.
|Default value
m|+++256.00MiB+++
|===
