[[cypher-version-configuration]]
= Configure the Cypher default version
:page-role: new-2025.06
:description: How to configure the Cypher default version.

You can specify the version of Cypher in which you want to run your queries, choosing between Cypher 5 and Cypher 25.
Cypher 5 is the default version for all newly-created databases, however, if you want to take advantage of the new features in Cypher 25, you can set the default version to Cypher 25.

For more information about the Cypher versioning, see link:{neo4j-docs-base-uri}/cypher-manual/25/queries/select-version/[Cypher Manual -> Select Cypher version].

To specify the Cypher version, use one of the following options:

Configure a default Cypher version for the whole DBMS::
The default language version for the whole DBMS can be configured in the _neo4j.conf_ file using the setting xref:configuration/configuration-settings.adoc#config_db.query.default_language[db.query.default_language] (default value: CYPHER_5). +
Changing this setting in an existing DBMS, *does not* affect existing databases.
It only applies to newly-created databases unless the version is specified as part of the `CREATE` or `ALTER` database commands.

Configure a default Cypher version per database::
The default language for a specific database can be set using a Cypher database administration command with the `SET DEFAULT LANGUAGE` clause when creating the database or by altering the database after it has been created.
This setting determines the default language for the specified database, overriding the default language set in the configuration file.
For example, `CREATE DATABASE mydb SET DEFAULT LANGUAGE CYPHER 25` or `ALTER DATABASE mydb SET DEFAULT LANGUAGE CYPHER 5`.
For more details and examples, see xref:database-administration/syntax.adoc#administration-syntax-database-management[Database management command syntax] and the respective pages in the xref:database-administration/index.adoc[] section. +
If not specified, the default language for the database is set to the default language of the DBMS.
Setting the default language requires the `SET DATABASE DEFAULT LANGUAGE` privilege.

Set the Cypher version on a per-query basis::
The default language for a specific query can be set by prepending the query with the `CYPHER 5` or `CYPHER 25` keyword. +
For example, `CYPHER 25 MATCH (n) RETURN n` or `CYPHER 5 MATCH (n) RETURN n`.
This setting determines the language for the specified query, overriding the default language set in the configuration file and the database.
