[role=enterprise-edition]
[[dynamic-settings]]
= Dynamic settings
:description: How to change your Neo4j configuration while Neo4j is running, and which settings can be changed.


[[dynamic-settings-introduction]]
== Introduction

Neo4j Enterprise Edition supports changing some configuration settings at runtime, without restarting the service.
Changes to the configuration at runtime are not persisted.
To avoid losing changes when restarting Neo4j, you must ensure that the xref:configuration/file-locations.adoc[_neo4j.conf_ file] is also updated.


[NOTE]
====
label:cluster[Cluster]

In a clustered environment, `CALL dbms.setConfigValue` affects only the cluster member it is run against, and it is not propagated to other members.
Therefore, you should connect using `bolt://` rather than `neo4j://` to ensure that the setting is changed on the member connected to, and not on the unintended leader.
If you want to change the configuration settings on all cluster members, you have to run the procedure against each of them and update their _neo4j.conf_ file.
====


[[dynamic-settings-discover]]
== Discover dynamic settings

Use the procedure `dbms.listConfig()` to discover which configuration values can be dynamically updated, or consult xref:configuration/dynamic-settings.adoc#dynamic-settings-reference[Dynamic settings reference].

.Discover dynamic settings
====

[source, cypher]
----
CALL dbms.listConfig()
YIELD name, dynamic
WHERE dynamic
RETURN name
ORDER BY name
LIMIT 4;
----

[queryresult]
----
+----------------------------------------------+
| name                                         |
+----------------------------------------------+
| "dbms.checkpoint.iops.limit"                 |
| "dbms.logs.query.allocation_logging_enabled" |
| "dbms.logs.query.enabled"                    |
| "dbms.logs.query.page_logging_enabled"       |
+----------------------------------------------+
4 rows
----

====


[[dynamic-settings-procedure]]
== Update dynamic settings

An xref:authentication-authorization/terminology.adoc#term-administrator[administrator] is able to change some configuration settings at runtime, without restarting the service.

*Syntax:*

`CALL dbms.setConfigValue(_setting_, _value_)`

*Returns:*

Nothing on success.

*Exceptions:*

|===
| Unknown or invalid setting name.
| The setting is not dynamic and can not be changed at runtime.
| Invalid setting value.
|===

The following example shows how to dynamically enable query logging.

.Set a config value
====
[source, cypher]
----
CALL dbms.setConfigValue('dbms.logs.query.enabled', 'info')
----
====

If an invalid value is passed, the procedure will show a message to that effect.

.Try to set invalid config value
====
[source, cypher]
----
CALL dbms.setConfigValue('dbms.logs.query.enabled', 'yes')
----

[queryresult]
----
Failed to invoke procedure `dbms.setConfigValue`: Caused by: org.neo4j.graphdb.config.InvalidSettingException: Bad value 'yes' for setting 'dbms.logs.query.enabled': 'yes' not one of [OFF, INFO, VERBOSE]
----
====

To reset a config value to its default, pass an empty string as the _value_ argument.

.Reset a config value to default
====
[source, cypher]
----
CALL dbms.setConfigValue('dbms.logs.query.enabled', '')
----
====