:description: Information about the `SHOW SETTINGS` command.
:page-role: not-on-aura
= List settings

This page describes listing configuration settings using the `SHOW SETTINGS` command.
For general information about the `SHOW` command, see the link:{neo4j-docs-base-uri}/cypher-manual/clauses/show/[Cypher Manual -> SHOW].

[NOTE]
====
Configurations settings can also be listed using the xref:procedures/built-in-procedures.adoc#procedure_dbms_listConfig[`dbms.listConfig()`] procedure. 
// Link will not work until SHOW PROCEDURES PR is merged
====

[[syntax]]
== Syntax

For full details about the syntax descriptions, see xref:database-administration/syntax.adoc#administration-syntax-reading[Administration command syntax].

[options="header", width="100%", cols="1,5a"]
|===
| Action | Syntax

| List settings

a|
[source, syntax, role="noheader"]
----
SHOW SETTING[S] [setting-name[,...]]
[YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
[WHERE expression]
[RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----

[NOTE]
====
Setting names must be supplied as one or more comma-separated quoted `STRING` values or as an expression resolving to a `STRING` or a `LIST<STRING>`.
====
|===

[NOTE]
====
When using the `RETURN` clause, the `YIELD` clause is mandatory and must not be omitted.
====

[[return-columns]]
== Return columns

`SHOW SETTINGS` will produce a table with the following columns:

.Show settings output
[options="header", cols="4,6,2"]
|===
| Column | Description | Type

m| name
a| The name of the setting. label:default-output[]
m| STRING

m| value
a| The current value of the setting. label:default-output[]
m| STRING

m| isDynamic
a|
Whether the value of the setting can be updated dynamically, without restarting the server.
For dynamically updating a setting value, see link:{neo4j-docs-base-uri}/operations-manual/current/configuration/dynamic-settings/[Update dynamic settings].
label:default-output[]
m| BOOLEAN

m| defaultValue
a| The default value of the setting. label:default-output[]
m| STRING

m| description
a| The setting description. label:default-output[]
m| STRING

m| startupValue
a| The value of the setting at last startup.
m| STRING

m| isExplicitlySet
a| Whether the value of the setting is explicitly set by the user, either through configuration or dynamically.
m| BOOLEAN

m| validValues
a| A description of valid values for the setting.
m| STRING

m| isDeprecated
a| Whether the setting is deprecated.

m| BOOLEAN

|===

The deprecation information for procedures is returned both in the `isDeprecated` and `option` columns.

[[examples]]
== Examples

.List all settings with default return columns
[source, cypher]
----
SHOW SETTINGS
----

.List all settings with all return columns
[source, cypher]
----
SHOW SETTINGS YIELD *
----

.List all settings with specified return columns
[source, cypher]
----
SHOW SETTINGS YIELD name, defaultValue, startupValue
----

.List named settings
[source, cypher]
----
SHOW SETTINGS "server.bolt.enabled", "server.bolt.advertised_address", "server.bolt.listen_address"
----

.Filter `SHOW SETTINGS` with `WHERE`
[source, cypher]
----
SHOW SETTINGS YIELD name, value, description
WHERE name STARTS WITH 'server'
RETURN name, value, description
----
