[[neo4j-conf]]
= The neo4j.conf file
:description: This section introduces the _neo4j.conf_ file, and its syntax. 

This section contains the following:

* xref:configuration/neo4j-conf.adoc#neo4j-conf-introduction[Introduction]
* xref:configuration/neo4j-conf.adoc#neo4j-conf-syntax[Syntax]
* xref:configuration/neo4j-conf.adoc#neo4j-conf-JVM[JVM-specific configuration settings]
* xref:configuration/neo4j-conf.adoc#neo4j-conf-current-settings[List currently active settings]

For a complete reference of Neo4j configuration settings, see xref:reference/configuration-settings.adoc[Configuration settings].


[[neo4j-conf-introduction]]
== Introduction

The _neo4j.conf_ file is the main source of configuration settings in Neo4j, and includes the mappings of configuration setting keys to values.
The location of the _neo4j.conf_ file in the different configurations of Neo4j is listed in xref:configuration/file-locations.adoc#table-file-locations[Default file locations].

Most of the configuration settings in the _neo4j.conf_ file apply directly to Neo4j itself, but there are also some settings which apply to the Java Runtime (the JVM) on which Neo4j runs.
For more information, see the xref:configuration/neo4j-conf.adoc#neo4j-conf-JVM[JVM specific configuration settings] below.
Many of the configuration settings are also used by the `neo4j` launcher scripts.


[[neo4j-conf-syntax]]
== Syntax

* The equals sign (`=`) maps configuration setting keys to configuration values.
* Lines that start with the number sign (`#`) are handled as comments.
* Empty lines are ignored.
* Configuring a setting in _neo4j.conf_ will overwrite any default values.
In case a setting can define a list of values, and you wish to amend the default values with custom values, you will have to explicitly list the default values along with the new values.
* There is no order for configuration settings, and each setting in the _neo4j.conf_ file must be uniquely specified.
If you have multiple configuration settings with the same key, but different values, this can lead to unpredictable behavior.
+
The only exception to this is `xref:reference/configuration-settings.adoc#config_dbms.jvm.additional[dbms.jvm.additional]`.
If you set more than one value for `xref:reference/configuration-settings.adoc#config_dbms.jvm.additional[dbms.jvm.additional]`, then each setting value will add another custom JVM argument to the `java` launcher.
  

[[neo4j-conf-JVM]]
== JVM-specific configuration settings

* `xref:reference/configuration-settings.adoc#config_dbms.memory.heap.initial_size[dbms.memory.heap.initial_size]`
* `xref:reference/configuration-settings.adoc#config_dbms.memory.heap.max_size[dbms.memory.heap.max_size]`
* `xref:reference/configuration-settings.adoc#config_dbms.jvm.additional[dbms.jvm.additional]`


[[neo4j-conf-current-settings]]
== List currently active settings

You can use the procedure `dbms.listConfig()` to list the currently active configuration settings and their values.

.List currently active configuration settings
====

[source, cypher]
----
CALL dbms.listConfig()
YIELD name, value
WHERE name STARTS WITH 'dbms.'
RETURN name, value
ORDER BY name
LIMIT 4;
----

[queryresult]
----
+----------------------------------------------+
| name                           | value       |
+----------------------------------------------+
| "dbms.active_database"         | "graph.db"  |
| "dbms.allow_format_migration"  | "false"     |
| "dbms.allow_upgrade"           | "false"     |
| "dbms.checkpoint"              | "periodic"  |
+----------------------------------------------+
4 rows
----
====

See also xref:configuration/dynamic-settings.adoc[Dynamic settings] for information about dynamic settings.
