:description: This page describes how to reset a password to recover a user's access when their password is lost. It specifically focuses on how to recover an admin user if all the admin users have been unassigned the admin role, and how to recreate the built-in admin role if it has been dropped.
[[password-and-user-recovery]]
= Password and user recovery

This page describes how to create a new password to recover access to a user when their password is lost.
It specifically focuses on how to recover an admin user if all the admin users have been unassigned the admin role, and how to recreate the built-in admin role if it has been dropped.

[[disable-authentication]]
== Disable authentication

[.tabbed-example]
=====
[.include-with-standalone]
======

. Stop Neo4j:
+
[source, shell]
----
$ bin/neo4j stop
----
. Open the _neo4j.conf_ file and set `dbms.security.auth_enabled` parameter to `false` to disable the authentication:
+
[source, properties]
----
dbms.security.auth_enabled=false
----
+
[NOTE]
====
It is recommended to block network connections during the recovery phase, so users can connect to Neo4j only via `localhost`.
This can be achieved by either:

* Temporarily commenting out the `server.default_listen_address` parameter:
+
[source, properties]
----
#server.default_listen_address=<your_configuration>
----

or

* Providing the specific localhost value:
+
[source, properties]
----
server.default_listen_address=127.0.0.1
----
====
. Start Neo4j:
+
[source, shell]
----
$ bin/neo4j start
----
======
[.include-with-cluster]
======
. Stop the cluster (all Core servers and Read Replicas).
+
[source, shell]
----
$ bin/neo4j stop
----
+
. On each Core server, open the _neo4j.conf_ file and modify the following settings:
.. Set `dbms.security.auth_enabled` parameter to `false` to disable the authentication:
+
[source, properties]
----
dbms.security.auth_enabled=false
----
+
.. Disable the HTTP and HTTPS network connections and restrict the `bolt` connector to use only `localhost`.
This ensures that no one from outside can access the cluster during the recovery period.
+
[source, properties]
----
#server.http.enabled=true
#server.https.enabled=true
server.bolt.listen_address:127.0.0.1
----
+
. Start all Core servers:
+
[source, shell]
----
$ bin/neo4j start
----
======
=====

[[password-recovery-for-admin]]
== Recover a lost password

You can use a client such as xref:tools/cypher-shell.adoc[Cypher Shell] or the Neo4j Browser to connect to the xref:manage-databases/introduction.adoc#manage-databases-system[`system`] database and set a new password for the admin user.

[NOTE]
====
In a cluster deployment, you should complete the steps only on one of the Core servers.
====

. Complete the steps in xref:configuration/password-and-user-recovery.adoc#disable-authentication[Disable authentication] as per your deployment.
. Connect to the `system` database using Cypher shell.
Alternatively, log into Neo4j Browser.
+
[source, shell]
----
$ bin/cypher-shell -d system
----
+
[NOTE]
====
label:Cluster[] If you have specified a non-default port for your `bolt` connector, add `-a neo4j://<your-core>:<non-default-bolt-port>` to the `cypher-shell` command to be able to connect to your Core server.
====
. Set a new password for the admin user.
In this example, the admin user is named `neo4j`.
+
[source, cypher]
----
ALTER USER neo4j SET PASSWORD 'mynewpass'
----
. Exit the `cypher-shell` console:
+
[source, shell]
----
:exit;
----
. Proceed with the xref:configuration/password-and-user-recovery.adoc#post-recovery[post-recovery steps] as per your deployment.

[[recover-unassigned-admin-role]]
== Recover an unassigned admin role

You can use a client such as xref:tools/cypher-shell.adoc[Cypher Shell] or the Neo4j Browser to connect to the xref:manage-databases/introduction.adoc#manage-databases-system[`system`] database and grant the admin user role to an existing user.

[NOTE]
====
In a cluster deployment, you should complete the steps only on one of the Core servers.
====

. Complete the steps in xref:configuration/password-and-user-recovery.adoc#disable-authentication[Disable authentication] as per your deployment.
. Connect to the `system` database using Cypher shell.
Alternatively, log into Neo4j Browser.
+
[source, shell]
----
$ bin/cypher-shell -d system
----
+
[NOTE]
====
label:Cluster[] If you have specified a non-default port for your `bolt` connector, add `-a neo4j://<your-core>:<non-default-bolt-port>` to the `cypher-shell` command to be able to connect to your Core server.
====
. Grant the admin user role to an existing user.
In this example, the user is named `neo4j`.
+
[source, cypher]
----
GRANT ROLE admin TO neo4j
----
. Exit the `cypher-shell` console:
+
[source, shell]
----
:exit;
----
. Proceed with the xref:configuration/password-and-user-recovery.adoc#post-recovery[post-recovery steps] as per your deployment.

[[recover-admin-role]]
== Recover the admin role

If you have removed the admin role from your system entirely, you can use a client such as xref:tools/cypher-shell.adoc[Cypher Shell] or the Neo4j Browser to connect to the xref:manage-databases/introduction.adoc#manage-databases-system[`system`] database and recreate the role with its original capabilities.

[NOTE]
====
In a cluster deployment, you should complete the steps only on one of the Core servers.
====

. Complete the steps in xref:configuration/password-and-user-recovery.adoc#disable-authentication[Disable authentication] as per your deployment.
. Connect to the `system` database using Cypher shell.
Alternatively, log into Neo4j Browser.
+
[source, shell]
----
$ bin/cypher-shell -d system
----
+
[NOTE]
====
label:Cluster[] If you have specified a non-default port for your `bolt` connector, add `-a neo4j://<your-core>:<non-default-bolt-port>` to the `cypher-shell` command to be able to connect to your Core server.
====
. Recreate the admin role with its original capabilities.
+
[source, cypher]
----
CREATE ROLE admin;
GRANT ALL DBMS PRIVILEGES ON DBMS TO admin;
GRANT TRANSACTION MANAGEMENT ON DATABASE * TO admin;
GRANT START ON DATABASE * TO admin;
GRANT STOP ON DATABASE * TO admin;
GRANT MATCH {*} ON GRAPH * TO admin;
GRANT WRITE ON GRAPH * TO admin;
GRANT ALL ON DATABASE * TO admin;
----
. Grant the admin user role to an existing user.
+
[NOTE]
====
Before running the `:exit` command, we suggest granting the newly created role to a user.
Although this is optional, without this step you will have only collected all admin privileges in a role that no one is assigned to.

To grant the role to a user (assuming your existing user is named `neo4j`), you can run `GRANT ROLE admin TO neo4j;`
====
. Exit the `cypher-shell` console:
+
[source, shell]
----
:exit;
----
. Proceed with the xref:configuration/password-and-user-recovery.adoc#post-recovery[post-recovery steps] as per your deployment.

[[post-recovery]]
== Post-recovery steps

[.tabbed-example]
=====
[.include-with-standalone]
======

. Stop Neo4j:
+
[source, shell]
----
$ bin/neo4j stop
----
. Enable the authentication and restore your Neo4j to its original configuration (See xref:configuration/password-and-user-recovery.adoc#disable-authentication[Disable authentication]).
. Start Neo4j:
+
[source, shell]
----
$ bin/neo4j start
----
======
[.include-with-cluster]
======
. Stop the Core servers.
+
[source, shell]
----
$ bin/neo4j stop
----
+
. Enable the authentication and restore each Core server to its original configuration (See xref:configuration/password-and-user-recovery.adoc#disable-authentication[Disable authentication]).
. Start the cluster (all Core servers and Read Replicas):
+
[source, shell]
----
$ bin/neo4j start
----
======
=====
