[[plugins]]
= Configure plugins
:description: This page describes how to load plugins to a Neo4j deployment.

Neo4j Enterprise Edition comes bundled with a range of pre-installed products, such as Graph Data Science library and Bloom, which can be used to extend the Neo4j capabilities.
The JAR files for these products are located in the _products_ folder and can be installed as plugins.

Neo4j Community Edition comes with the APOC plugin only in the _labs_ directory.

If you want to use your own plugins, ensure that you add them to the designated _plugins_ directory.
This directory serves as the central location where Neo4j looks for and loads the plugins at startup.

[NOTE]
====
Bloom Enterprise and GDS Enterprise require a license activation key.
Reach out to your Neo4j account representative or request a representative to link:https://neo4j.com/contact-us/#sales-inquiry[contact you].
====

The following plugins are supported:

.Supported Neo4j plugins
[options="header",cols="d,m,b,a"]
|===
|Name |Key  | License activation key required | Further information

| APOC Extended
| `apoc-extended`
|
| link:https://neo4j.com/labs/apoc/5/[APOC Extended user guide (Labs project)]

| APOC
| `apoc`
|
| link:https://neo4j.com/docs/apoc/current/[APOC user guide]

| Bloom Enterprise footnote:[You can also get basic access to Bloom via Graph Apps in Neo4j Desktop without a license key. See link:{neo4j-docs-base-uri}/bloom-user-guide/current/bloom-installation/bloom-deployment-modes/[Bloom deployment modes] for more details.]
| `bloom`
| {check-mark}
| link:{neo4j-docs-base-uri}/bloom-user-guide/current/[Neo4j Bloom]

| GenAI footnote:[Introduced in 5.17 in Enterprise Edition only. From Neo4j 5.23, the GenAI plugin is also available in Neo4j Community Edition.]
| `genai`
|
| link:{neo4j-docs-base-uri}/cypher-manual/5/genai-integrations/[Cypher Manual -> GenAI integrations].

| GraphQL
| `graphql`
|
| link:{neo4j-docs-base-uri}/graphql/current/[Neo4j GraphQL Library]

| Graph Algorithms
| `graph-algorithms`
|
| link:{neo4j-docs-base-uri}/graph-data-science/current/installation/installation-enterprise-edition/[The Neo4j Graph Data Science Library Manual]

| Graph Data Science
| `graph-data-science`
|
| link:{neo4j-docs-base-uri}/graph-data-science/current/installation/#_installation_methods[Graph Data Science]

| Graph Data Science Enterprise
| `graph-data-science`
| {check-mark}
| link:{neo4j-docs-base-uri}/graph-data-science/current/[GDS Enterprise Edition]

| Neo Semantics
| `n10s`
|
| link:https://neo4j.com/labs/neosemantics/[Neo Semantics]
|===

For more information on using plugins in a different Neo4j setup, see:

* link:{neo4j-docs-base-uri}/desktop/current/operations/instance-management/#_install_plugins[Neo4j Desktop -> Install a plugin]
* xref:docker/plugins.adoc[Docker -> Plugins]
* xref:/kubernetes/plugins.adoc[Kubernetes -> Plugins]
* link:{neo4j-docs-base-uri}/java-reference/{page-version}/extending-neo4j/project-setup/#_build_dependencies[Java-Reference -> Setting up a plugin project].

== Install and configure plugins

Here are the steps to enable the plugins:

. Move or copy the plugins (_.jar files_) from _<NEO4J_HOME>/products_ and _<NEO4J_HOME>/labs_ to the _<NEO4J_HOME>/plugins_ directory.
See xref:configuration/file-locations.adoc[Default file locations] for more information.

. Add the following lines in _<NEO4J_HOME>/conf/neo4j.conf_:
+
[source, properties]
----
# to enable GDS:

* dbms.security.procedures.unrestricted=gds.*
* dbms.security.procedures.allowlist=gds.*
* gds.enterprise.license_file=/path/to/my/license/keyfile


#  to enable Bloom:

* dbms.security.procedures.unrestricted=bloom.*
* dbms.bloom.license_file=/path/to/my/license/keyfile


#  to enable both GDS and Bloom:

* dbms.security.procedures.unrestricted=gds.*,bloom.*
* dbms.security.procedures.allowlist=gds.*
* gds.enterprise.license_file=/path/to/my/license/keyfile
* dbms.bloom.license_file=/path/to/my/license/keyfile
----
. Install the plugins.
+
Refer to link:https://neo4j.com/docs/bloom-user-guide/current/bloom-installation/[Bloom documentation], link:https://neo4j.com/docs/graph-data-science/current/installation/[GDS documentation] for more details on how to install them.

[NOTE]
====
All installed plugins will automatically be loaded every time Neo4j is started.
Because of that, the number of plugins may impact the startup time.
Install only the necessary plugins to avoid performance issues.
====

