[[plugins]]
= Configure plugins
:description: This page describes how to load plugins to a Neo4j deployment.

Neo4j distributions come bundled with a range of pre-installed products, such as Graph Data Science library, Bloom, and Ops Manager, which can be used to extend the Neo4j capabilities.
The JAR files for these products are located in the _product_ and _labs_ folders and can be installed as plugins.

If you want to use your own plugins, ensure that you add them to the designated _plugins_ directory.
This directory serves as the central location where Neo4j looks for and loads the plugins at startup.

[NOTE]
====
Bloom and GDS Enterprise require a license activation key to become available to the user within Neo4j.
Reach out to your Neo4j account representative or request a representative to link:https://neo4j.com/contact-us/#sales-inquiry[contact you].
====

The following plugins are supported:

.Supported Neo4j plugins
[options="header",cols="d,m,b,a"]
|===
|Name |Key  | License required | Further information

| APOC
| `apoc`
| {cross-mark}
| https://neo4j.com/labs/apoc/4.4/[APOC user guide]

| APOC Core
| `apoc-core`
| {cross-mark}
| https://neo4j.com/labs/apoc/4.4/[APOC user guide]

| Bloom
| `bloom`
| {check-mark}
| link:{neo4j-docs-base-uri}/bloom-user-guide[Neo4j Bloom]

| Streams
| `streams`
| {cross-mark}
| link:{neo4j-docs-base-uri}/kafka-streams[Neo4j Streaming Data Integrations User Guide]

| GraphQL
| `graphql`
| {cross-mark}
| link:{neo4j-docs-base-uri}/graphql/current/[Neo4j GraphQL Library]

| Graph Algorithms
| `graph-algorithms`
| {cross-mark}
| link:{neo4j-docs-base-uri}/graph-data-science[The Neo4j Graph Data Science Library Manual]


| Graph Data Science
| `graph-data-science`
| {cross-mark}
| link:{neo4j-docs-base-uri}/graph-data-science[The Neo4j Graph Data Science Library Manual]

| Neo Semantics
| `n10s`
| {cross-mark}
| https://neo4j.com/labs/nsmtx-rdf/[Neo Semantics]
|===


For more information on using plugins in a different Neo4j setup, see link:{neo4j-docs-base-uri}/desktop-manual/1.6/operations/install-plugin/[Neo4j Desktop -> Install a plugin], xref:docker/operations.adoc#docker-neo4jlabs-plugins[Docker -> Configure Neo4j plugins], xref:/kubernetes/configuration.adoc#operations-installing-plugins[Kubernetes -> Plugins], and link:{neo4j-docs-base-uri}/java-reference/{page-version}/extending-neo4j/project-setup/#_build_dependencies[Java-Reference -> Setting up a plugin project].

== Install and configure plugins

Here are the steps to enable the plugins:

. Move or copy the plugins (_.jar files_) from _<NEO4J_HOME>/products_ and _<NEO4J_HOME>/labs_ to the _<NEO4J_HOME>/plugins_ directory.
See the table in xref:configuration/file-locations.adoc[File locations] for more information.

. Add the following lines in _$NEO4J_HOME/conf/neo4j.conf_:
+
[source, properties]
----
# to enable GDS:

* dbms.security.procedures.unrestricted=gds.*
* dbms.security.procedures.allowlist=gds.*
* gds.enterprise.license_file=/path/to/my/license/keyfile


#  to enable Bloom:

* dbms.security.procedures.unrestricted=bloom.*
* dbms.bloom.license_file=/path/to/my/license/keyfile


#  to enable both GDS and Bloom:

* dbms.security.procedures.unrestricted=gds.*,bloom.*
* dbms.security.procedures.allowlist=gds.*
* gds.enterprise.license_file=/path/to/my/license/keyfile
* dbms.bloom.license_file=/path/to/my/license/keyfile
----
. Install the plugins.
+
Refer to link:https://neo4j.com/docs/bloom-user-guide/current/bloom-installation/[Bloom documentation], link:https://neo4j.com/docs/graph-data-science/current/installation/[GDS documentation], and  https://neo4j.com/docs/ops-manager/current[Neo4j Ops Manager documentation] for more details on how to install them.

[NOTE]
====
All installed plugins will automatically be loaded every time Neo4j is started.
Because of that, the number of plugins may impact the startup time.
Install only the necessary plugins to avoid performance issues.
====