[[plugins]]
= Configure plugins
:description: This page describes all supported plugin in Neo4j and how to load them into your deployment.

== Overview

Plugins are Java Archive (_.jar_) files that extend the functionality of Neo4j by adding new features and capabilities, such as graph algorithms, data integration, visualization, and monitoring tools.

Both Neo4j Community Edition (CE) and Enterprise Edition (EE) come with a range of pre-installed products, such as Gen AI, Bloom, and Graph Data Science in the _products_ directory, and the APOC Core jar file in the _labs_ directory. +

Fleet management is also included in the _products_ directory in versions Neo4j 4.4.45+, 5.26.12+, and versions between 2025.08.0 and 2026.02.2 inclusive.
However, starting with Neo4j 2026.03, Fleet Manager is built-in and enabled by default, therefore, the plugin is no longer supported.
For details on how to enable the Fleet management plugin in Neo4j 4.4.45+, 5.26.12+, and versions between 2025.08.0 and 2026.02.2 inclusive, see <<install-and-configure-plugins, Install and configure plugins>>.

[NOTE]
====
Using the Fleet management plugin in Neo4j CE deployments is subject to some limitations due to the limited set of features, such as no metrics being available.
Also, it is offered on a best-effort basis.
Neo4j does not offer any technical support for it.
====

If your Neo4j CE installation does not include the bundled GDS plugin, check the link:{neo4j-docs-base-uri}/graph-data-science/current/installation/supported-neo4j-versions[Neo4j Graph Data Science Library Manual -> Supported Neo4j versions] to find your matching GDS library version and download it separately.
For detailed installation, refer to the corresponding Neo4j GDS manual.


Some of these plugins, such as Bloom and GDS Enterprise require a license activation key.
Reach out to your Neo4j account representative or request a representative to link:https://neo4j.com/contact-us/#sales-inquiry[contact you].

If you want to use your own plugins or any of the other supported plugins, such as APOC Extended and Neo4jsemantics, ensure that you download and add them to the _plugins_ directory.
See their respective documentation for more information.

[[supported-plugins]]
== Supported plugins and documentation

The following plugins are supported:

.Supported Neo4j plugins and documentation
[options="header",cols="d,m,b,a"]
|===
|Name |Key  | License activation key required | Documentation

| APOC Core
| `apoc`
|
| link:https://neo4j.com/docs/apoc/current/[APOC Core documentation]

| APOC Extended
| `apoc-extended`
|
| link:https://neo4j.com/labs/apoc/2025/[APOC Extended user guide (Labs project)]

| Bloom
| `bloom`
| {check-mark} footnote:[You can also get basic access, without a license key, to link:{neo4j-docs-base-uri}/bloom-user-guide/current/bloom-installation/bloom-deployment-modes/[Bloom via Graph Apps] in Neo4j Desktop or the link:https://console.neo4j.io/ce[Neo4j Aura console].]
| link:{neo4j-docs-base-uri}/bloom-user-guide/current/[Neo4j Bloom]

| Fleet management footnote:[Starting with Neo4j 2026.03, Fleet manager is built-in and enabled by default. The Fleet management plugin is not supported in versions 2026.03 and later.]
| `fleet-management`
|
| link:{neo4j-docs-base-uri}/aura/fleet-management/overview/[Fleet management]


| GenAI
| `genai`
|
| link:{neo4j-docs-base-uri}/genai/plugin/current/[Neo4j GenAI plugin].

| Graph Data Science
| `graph-data-science`
| {check-mark} footnote:[Graph Data Science is available in both Neo4j CE and EE editions. The Enterprise Edition includes additional features and requires a license key.]
| link:{neo4j-docs-base-uri}/graph-data-science/current/installation/#_installation_methods[Graph Data Science]

| Neosemantics
| `n10s`
|
| link:https://neo4j.com/labs/neosemantics/[Neosemantics]

|===

For more information on using plugins in a different Neo4j setup, see:

* link:{neo4j-docs-base-uri}/desktop/current/operations/instance-management/#_install_plugins[Neo4j Desktop -> Install a plugin]
* xref:docker/plugins.adoc[Docker -> Plugins]
* xref:/kubernetes/plugins.adoc[Kubernetes -> Plugins]
* link:{neo4j-docs-base-uri}/java-reference/{page-version}/extending-neo4j/project-setup/#_build_dependencies[Java-Reference -> Setting up a plugin project].

[[install-and-configure-plugins]]
== Install and configure plugins

To install and configure plugins in a Neo4j deployment, follow these steps.
If you are using a cluster, the plugin must be installed *on each server*.

. Move or copy the plugins (_.jar files_) from _<NEO4J_HOME>/products_ and _<NEO4J_HOME>/labs_ to the _<NEO4J_HOME>/plugins_ directory.
See xref:configuration/file-locations.adoc[Default file locations] for more information.
+
[NOTE]
====
Some plugins are not bundled with Neo4j and need to be downloaded separately, such as APOC Extended and Neosemantics.
See <<supported-plugins, Supported plugins and documentation>> for more information and links to the respective documentation.
====

. All plugins provide a number of procedures for you to use the functionality they offer.
To be able to run them, add the respective plugin to the following settings in the _neo4j.conf_ file:

* xref:configuration/configuration-settings.adoc#config_dbms.security.procedures.unrestricted[`dbms.security.procedures.unrestricted`]
* If the plugin requires a license key, add the path to the license key file as well.
* If xref:configuration/configuration-settings.adoc#config_dbms.security.procedures.allowlist[`dbms.security.procedures.allowlist`] is set in your configuration, also add the plugin to this setting, otherwise no change is needed.
By default, all procedures are loaded.
For more information, see xref:security/securing-extensions.adoc[Securing extensions].
+
[source, properties]
----

# to enable APOC core:
# * dbms.security.procedures.unrestricted=apoc.*
# * dbms.security.procedures.allowlist=apoc.*

# to enable APOC Extended:
# * dbms.security.procedures.unrestricted=apoc.*,apoc.extended.*
# * dbms.security.procedures.allowlist=apoc.*,apoc.extended.*

#  to enable Bloom:
# * dbms.security.procedures.unrestricted=bloom.*
# * dbms.security.procedures.allowlist=bloom.*
# * dbms.bloom.license_file=/path/to/my/license/keyfile

# to enable Fleet management:
# * dbms.security.procedures.unrestricted=fleetManagement.*
# * dbms.security.procedures.allowlist=fleetManagement.*

# to enable GDS:
# * dbms.security.procedures.unrestricted=gds.*
# * dbms.security.procedures.allowlist=gds.*
# * gds.enterprise.license_file=/path/to/my/license/keyfile

#  to enable both GDS and Bloom:
# * dbms.security.procedures.unrestricted=gds.*,bloom.*
# * dbms.security.procedures.allowlist=gds.*,bloom.*
# * gds.enterprise.license_file=/path/to/my/license/keyfile
# * dbms.bloom.license_file=/path/to/my/license/keyfile

# to enable GenAI:
# * dbms.security.procedures.unrestricted=genai.*
# * dbms.security.procedures.allowlist=genai.*

# to enable Neosemantics:
# * dbms.security.procedures.unrestricted=n10s.*
# * dbms.security.procedures.allowlist=n10s.*
----
. Restart Neo4j for the plugins to be loaded and available for use.
+
[NOTE]
====
All installed plugins will automatically be loaded every time Neo4j is started.
Because of that, the number of plugins may impact the startup time.
Install only the necessary plugins to avoid performance issues.
====

For further information on how to use the plugins, see their respective documentation, linked in <<supported-plugins, Supported plugins and documentation>>.