[[plugins]]
= Configure plugins
:description: This page describes how to load plugins to a Neo4j deployment.

== Overview

Plugins are Java Archive (_.jar_) files that extend the functionality of Neo4j by adding new features and capabilities, such as graph algorithms, data integration, and visualization tools.

Neo4j Community Edition (CE) comes with a range of pre-installed products, such as Gen AI, Graph Data Science, and Fleet management in the _products_ directory and the APOC Core jar file in the _labs_ directory.

[NOTE]
====
Using the Fleet management plugin in Neo4j CE deployments is subject to some limitations due to the limited set of features, such as no metrics being available.
Also, it is offered on a best-effort basis.
Neo4j does not offer any technical support for it.
====

Neo4j Enterprise Edition (EE) comes with Graph Data Science Enterprise, Bloom, Gen AI, and Fleet management, located in the _products_ directory, and the APOC Core jar file in the _labs_ directory.
Some of these plugins, Bloom and GDS Enterprise require a license activation key.
Reach out to your Neo4j account representative or request a representative to link:https://neo4j.com/contact-us/#sales-inquiry[contact you].

If you want to use your own plugins or other supported plugins, ensure that you add them to the designated _plugins_ directory.
This directory serves as the central location where Neo4j looks for and loads the plugins at startup.

== Supported plugins

The following plugins are supported:

.Supported Neo4j plugins
[options="header",cols="d,m,b,a"]
|===
|Name |Key  | License activation key required | Further information

| APOC Extended
| `apoc-extended`
|
| link:https://neo4j.com/labs/apoc/5/[APOC Extended user guide (Labs project)]

| APOC Core
| `apoc`
|
| link:https://neo4j.com/docs/apoc/current/[APOC Core documentation]

| Bloom Enterprise footnote:[You can also get basic access to Bloom via Graph Apps in Neo4j Desktop or the link:http://console-preview.neo4j.io/self-managed[Neo4j Aura console] without a license key. See link:{neo4j-docs-base-uri}/bloom-user-guide/current/bloom-installation/bloom-deployment-modes/[Bloom deployment modes] and for more details.]
| `bloom`
| {check-mark}
| link:{neo4j-docs-base-uri}/bloom-user-guide[Neo4j Bloom]

| Fleet management
| `fleet-management`
|
| link:{neo4j-docs-base-uri}/aura/fleet-management/setup/[Fleet management]

| GenAI
| `genai`
|
| link:{neo4j-docs-base-uri}/cypher-manual/current/genai-integrations/[Cypher Manual -> GenAI integrations].

| GraphQL
| `graphql`
|
| link:{neo4j-docs-base-uri}/graphql/current/[Neo4j GraphQL Library]

| Graph Algorithms
| `graph-algorithms`
|
| link:{neo4j-docs-base-uri}/graph-data-science/current/installation/installation-enterprise-edition/[The Neo4j Graph Data Science Library Manual]

| Graph Data Science
| `graph-data-science`
|
| link:{neo4j-docs-base-uri}/graph-data-science/current/installation/#_installation_methods[Graph Data Science]

| Graph Data Science Enterprise
| `graph-data-science`
| {check-mark}
| link:{neo4j-docs-base-uri}/graph-data-science[GDS Enterprise Edition]

| Neo Semantics
| `n10s`
|
| link:https://neo4j.com/labs/neosemantics/[Neo Semantics]

|===

For more information on using plugins in a different Neo4j setup, see:

* link:{neo4j-docs-base-uri}/desktop/current/operations/instance-management/#_install_plugins[Neo4j Desktop -> Install a plugin]
* xref:docker/plugins.adoc[Docker -> Plugins]
* xref:/kubernetes/plugins.adoc[Kubernetes -> Plugins]
* link:{neo4j-docs-base-uri}/java-reference/{page-version}/extending-neo4j/project-setup/#_build_dependencies[Java-Reference -> Setting up a plugin project].

== Install and configure plugins

To install and configure plugins in a Neo4j deployment, follow these steps:

. Move or copy the plugins (_.jar files_) from _<NEO4J_HOME>/products_ and _<NEO4J_HOME>/labs_ to the _<NEO4J_HOME>/plugins_ directory.
See xref:configuration/file-locations.adoc[Default file locations] for more information.

. Configure the plugins that you want to enable by adding and uncommenting the following settings in the _neo4j.conf_ file:
+
[source, properties]
----
# Add the plugin that you want to enable to the unrestricted procedures setting.
# If the plugin requires a license key, add the path to the license key file as well.
# If dbms.security.procedures.allowlist is set in your configuration, also add the plugin to this setting, otherwise no change is needed. By default, all procedures are loaded.

# to enable APOC:
# * dbms.security.procedures.unrestricted=apoc.*
# * dbms.security.procedures.allowlist=apoc.*

# to enable APOC Extended:
# * dbms.security.procedures.unrestricted=apoc.*,apoc.extended.*
# * dbms.security.procedures.allowlist=apoc.*,apoc.extended.*

#  to enable Bloom:
# * dbms.security.procedures.unrestricted=bloom.*
# * dbms.security.procedures.allowlist=bloom.*
# * dbms.bloom.license_file=/path/to/my/license/keyfile

# to enable Fleet management:
# * dbms.security.procedures.unrestricted=fleetManagement.*
# * dbms.security.procedures.allowlist=fleetManagement.*

# to enable GDS:
# * dbms.security.procedures.unrestricted=gds.*
# * dbms.security.procedures.allowlist=gds.*
# * gds.enterprise.license_file=/path/to/my/license/keyfile

#  to enable both GDS and Bloom:
# * dbms.security.procedures.unrestricted=gds.*,bloom.*
# * dbms.security.procedures.allowlist=gds.*,bloom.*
# * gds.enterprise.license_file=/path/to/my/license/keyfile
# * dbms.bloom.license_file=/path/to/my/license/keyfile

# to enable GenAI:
# * dbms.security.procedures.unrestricted=genai.*
# * dbms.security.procedures.allowlist=genai.*

# to enable GraphQL:
# * dbms.security.procedures.unrestricted=graphql.*
# * dbms.security.procedures.allowlist=graphql.*

# to enable Neo Semantics:
# * dbms.security.procedures.unrestricted=n10s.*
# * dbms.security.procedures.allowlist=n10s.*
----
+
For more information on configuring the plugins, see the respective documentation:
+
* link:https://neo4j.com/docs/bloom-user-guide/current/bloom-installation/[Bloom documentation]
* link:https://neo4j.com/docs/graph-data-science/current/installation/[GDS documentation]
* link:https://neo4j.com/docs/aura/fleet-management/setup/[Fleet management documentation]
* link:https://neo4j.com/docs/cypher-manual/current/genai-integrations/[GenAI documentation]
* link:https://neo4j.com/docs/apoc/current/installation/[APOC documentation]
* link:https://neo4j.com/labs/apoc/5/installation/[APOC extended documentation]
* link:https://neo4j.com/docs/graphql/current/[GraphQL documentation]
* link:https://neo4j.com/labs/neosemantics/[Neo Semantics documentation]

. Restart Neo4j for the plugins to be loaded and available for use.
+
[NOTE]
====
All installed plugins will automatically be loaded every time Neo4j is started.
Because of that, the number of plugins may impact the startup time.
Install only the necessary plugins to avoid performance issues.
====
