[[ports]]
= Ports
:description: This section lists ports relevant to a Neo4j installation. 

This section provides an overview for determining which Neo4j-specific ports should be opened up in your firewalls.
Note that these ports are in addition to those necessary for ordinary network operation.
Specific recommendations on port openings cannot be made, as the firewall configuration must be performed taking your particular conditions into consideration.

[options="header"]
|===
| Name | Default port number |	Related settings        | Comments
| Backups | `6362-6372` | `xref:reference/configuration-settings.adoc#config_dbms.backup.enabled[dbms.backup.enabled]`
`xref:reference/configuration-settings.adoc#config_dbms.backup.address[dbms.backup.address]` |
Backups are enabled by default.
In production environments, external access to the backup port(s) should be blocked by a firewall.
See also xref:backup/index.adoc[Backup].
| HTTP	| `7474` | See xref:configuration/connectors.adoc[Configure connectors]. | It is recommended to not open up this port for external access in production environments, since traffic is unencrypted.
Used by Neo4j Browser.
Also used by REST API.
| HTTPS	| `7473` | See xref:configuration/connectors.adoc[Configure connectors]. | Also used by REST API.
| Bolt	| `7687` | See xref:configuration/connectors.adoc[Configure connectors]. | Used by Cypher Shell and by Neo4j Browser.
| Causal Cluster | `5000`, `6000`, `7000` | `xref:reference/configuration-settings.adoc#config_causal_clustering.discovery_listen_address[causal_clustering.discovery_listen_address]`
`xref:reference/configuration-settings.adoc#config_causal_clustering.transaction_listen_address[causal_clustering.transaction_listen_address]`
`xref:reference/configuration-settings.adoc#config_causal_clustering.raft_listen_address[causal_clustering.raft_listen_address]`
| The listed ports are the default ports in _neo4j.conf_.
The ports are likely be different in a production installation; therefore the potential opening of ports must be modified accordingly.
See also xref:clustering/settings.adoc[Settings reference].
| HA Cluster | `5001`, `6001` | `xref:reference/configuration-settings.adoc#config_ha.host.coordination[ha.host.coordination]`
`xref:reference/configuration-settings.adoc#config_ha.host.data[ha.host.data]`
| The listed ports are the default ports in _neo4j.conf_.
The ports will most likely be different in a production installation; therefore the potential opening of ports must be modified accordingly.
See also xref:ha-cluster/index.adoc[HA cluster].
| Graphite monitoring |	`2003` | `xref:reference/configuration-settings.adoc#config_metrics.graphite.server[metrics.graphite.server]` | This is an outbound connection in order for the Neo4j database to communicate with the Graphite server.
See also xref:monitoring/metrics/index.adoc[Metrics].
| Prometheus monitoring |	`2004` | `xref:reference/configuration-settings.adoc#config_metrics.prometheus.enabled[metrics.prometheus.enabled]` and `xref:reference/configuration-settings.adoc#config_metrics.prometheus.endpoint[metrics.prometheus.endpoint]` |
See also xref:monitoring/metrics/index.adoc[Metrics].
| JMX monitoring | `3637` | `xref:reference/configuration-settings.adoc#config_dbms.jvm.additional[+++dbms.jvm.additional=-Dcom.sun.management.jmxremote.port=3637+++]` | This setting is for exposing the JMX.
This is not the recommended way of inspecting a Neo4j database.
It is not enabled by default.
|===
