:description: How to set an initial password for Neo4j.
[[post-installation-set-initial-password]]
= Set an initial password

Use the `set-initial-password` command of `neo4j-admin` to define the password for the native user `neo4j`.
This must be performed before starting up the database for the first time.

If the password is not set explicitly using this method, it will be set to the default password `neo4j`.
In that case, you will be prompted to change the default password at first login.



[NOTE]
====
The default minimum password length is 8 characters.

Use the xref:configuration/configuration-settings.adoc#config_config_dbms.security.auth_minimum_password_length[`dbms.security.auth_minimum_password_length`] configuration setting to change the default minimum value.
====

*Syntax:*

`neo4j-admin dbms set-initial-password <password> [--require-password-change]`

.Use the `set-initial-password` command of neo4j-admin
====

You can set the password for the native `neo4j` user before starting the database for the first time. +
For security reasons, it is recommended to store the password securely and not to include it directly in the command line.
For example, you can temporarily store the password in a file on disk and then read the file into the command using `cat`, for example:
----
bin/neo4j-admin dbms set-initial-password $(cat /home/user/password.file)
----
====

.Use the `set-initial-password` command of neo4j-admin with the optional `--require-password-change` flag
====

Alternatively, you can set the password for the native `neo4j` user before starting the database for the first time and require the user to change it at first login by using the `--require-password-change` flag:
----
bin/neo4j-admin dbms set-initial-password secretPassword --require-password-change
----
====