:description: How to set an initial password for Neo4j.
[[post-installation-set-initial-password]]
= Set an initial password

Use the `set-initial-password` command of `neo4j-admin` to define the password for the native user `neo4j`.
This must be performed before starting up the database for the first time.

[NOTE]
====
It is recommended that passwords have at least 8 characters.
====

*Syntax:*

`neo4j-admin dbms set-initial-password <password> [--require-password-change]`

.Use the `set-initial-password` command of neo4j-admin
====

Set the password for the native `neo4j` user to 'h6u4%kr' before starting the database for the first time.
----
$neo4j-home> bin/neo4j-admin dbms set-initial-password h6u4%kr
----
====

.Use the `set-initial-password` command of neo4j-admin with the optional `--require-password-change` flag
====

Set the password for the native `neo4j` user to 'secretpassword' before starting the database for the first time.
You will be prompted to change this password to one of your own choice at first login.
----
$neo4j-home> bin/neo4j-admin dbms set-initial-password secretpassword --require-password-change
----
====

If the password is not set explicitly using this method, it will be set to the default password `neo4j`.
In that case, you will be prompted to change the default password at first login.