:description: This page describes how to alter composite databases.
:page-role: new-2025.06 enterprise-edition not-on-aura
[[composite-databases-alter]]
= Alter composite databases

You can modify composite databases using the Cypher command `ALTER DATABASE`.

== Syntax

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax

| ALTER DATABASE
|
[source, syntax, role="noheader"]
----
ALTER DATABASE name [IF EXISTS]
SET DEFAULT LANGUAGE CYPHER {5\|25}
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----
|===

[role=label--new-2025.06]
== Alter the default Cypher version of a composite database

You can change the default Cypher version of an existing composite database using the `ALTER DATABASE` command with the `SET DEFAULT LANGUAGE` clause.
For example:

[source, cypher]
----
ALTER DATABASE inventory SET DEFAULT LANGUAGE CYPHER 25
----

This command will change the default Cypher version of the composite database `inventory` to Cypher 25.

include::partial$/view-cypher-version.adoc[]

.Result
[role="queryresult",options="header,footer",cols="2*<m"]
|===
| name | defaultLanguage

| "neo4j"    | "CYPHER 25"
| "library"   | "CYPHER 5"
| "inventory" | "CYPHER 25"
| "sci-fi"   | "CYPHER 5"
| "system"    | "CYPHER 25"

2+d|Rows: 5
|===

[NOTE]
====
Setting the default language to `CYPHER 25` ensures that all queries run on that database will use the version of `Cypher 25` that the database is currently running (unless you prepend your queries with `CYPHER 5`, which overrides this default).
For example, a Neo4j 2025.08 database with default language `Cypher 25` will use `Cypher 25` as it exists in Neo4j 2025.08, including any changes introduced in Neo4j 2025.06, 2025.07, and 2025.08.
====