:description: This page describes how to delete composite databases.
[role=enterprise-edition not-on-aura]
[[composite-databases-delete]]
= Delete composite databases

You can delete composite databases using either the command `DROP COMPOSITE DATABASE name` or the more general one `DROP DATABASE name`.
However, keep in mind that the first command will fail if the target database is not composite, while the second one will not fail because it targets any database.

.Query
[source, cypher]
----
DROP COMPOSITE DATABASE inventory
----

[[composite-databases-delete-with-aliases]]
== Delete a composite database with constituent database aliases

In general, deleting a composite database that has constituent database aliases will fail due to those database aliases.
This affects both the local and remote constituent database aliases belonging to the specified composite database.

By appending `CASCADE ALIASES` to the command `DROP COMPOSITE DATABASE`, those constituent database aliases can be dropped together with the composite database.
This affects both the local and remote constituent database aliases belonging to the specified composite database.

Using `CASCADE ALIASES` requires the `DROP ALIAS` privilege (see xref:authentication-authorization/dbms-administration.adoc#access-control-dbms-administration-alias-management[ALIAS MANAGEMENT privileges]).

Given composite database and database alias:
[source, cypher]
----
CREATE COMPOSITE DATABASE movies
CREATE ALIAS movies.sweden FOR DATABASE `swedish-movies`
----

Then both the constituent database alias `sweden` and the composite database `movies` will be dropped with:
[source, cypher]
----
DROP COMPOSITE DATABASE movies CASCADE ALIASES
----

This behaviour would be the same for the more general one `DROP DATABASE name` as well when using it to drop composite databases.

The option `RESTRICT` explicitly requests the default behavior of the command.

[NOTE]
====
The `CASCADE ALIASES` option will drop the same aliases that would be given in the error message from trying to drop the database using the `RESTRICT` mode instead.
====

