:description: This page describes how to delete composite databases.
[role=enterprise-edition not-on-aura]
[[composite-databases-delete]]
= Delete composite databases

You can delete composite databases using either the command `DROP COMPOSITE DATABASE name` or the more general one `DROP DATABASE name`.
However, keep in mind that the first command targets only composite databases, while the second one targets any database.

.Query
[source, cypher]
----
DROP COMPOSITE DATABASE inventory
----

[[composite-databases-delete-with-aliases]]
== Delete a composite database with constituent database aliases

There are two ways of dropping a composite database with constituent database aliases (local or remote):

* Drop the constituent database aliases first, then use `DROP COMPOSITE DATABASE name` to drop the composite database.
* Use `DROP COMPOSITE DATABASE name CASCADE ALIASES` to also drop the constituent database aliases while dropping the composite database.
This operation does not drop the actual target database of the constituent database aliases.

Using `CASCADE ALIASES` requires the `DROP ALIAS` privilege.
For more information, see xref:authentication-authorization/dbms-administration.adoc#access-control-dbms-administration-alias-management[ALIAS MANAGEMENT privileges].

Given composite database and database alias:
[source, cypher]
----
CREATE COMPOSITE DATABASE movies
CREATE ALIAS movies.sweden FOR DATABASE `swedish-movies`
----

Then both the constituent database alias `sweden` and the composite database `movies` will be dropped with:
[source, cypher]
----
DROP COMPOSITE DATABASE movies CASCADE ALIASES
----

This behavior would be the same for the more general command `DROP DATABASE name` when using it to drop a composite database.

The option `RESTRICT` explicitly requests the default behavior of the command.

[NOTE]
====
For composite databases, the aliases that are dropped when using the `CASCADE ALIASES` option can be found in the `constituents` column of `SHOW DATABASE`.
====

