:description: This page describes how to delete composite databases.
[role=enterprise-edition not-on-aura]
[[composite-databases-delete]]
= Delete composite databases

You can delete composite databases using either the command `DROP COMPOSITE DATABASE name` or the more general one `DROP DATABASE name`.
However, keep in mind that the first command will fail if the target database is not composite, while the second one will not fail because it targets any database.

.Query
[source, cypher]
----
DROP COMPOSITE DATABASE inventory
----

[[composite-databases-delete-with-aliases]]
== Delete a composite database with constituent database aliases

In general, deleting a composite database that has constituent database aliases will fail as these aliases need to be dropped first.
This applies to both the local and remote constituent database aliases belonging to the specified composite database.

By appending `CASCADE ALIASES` to the command `DROP COMPOSITE DATABASE`, those constituent database aliases can be dropped alongside the composite database.
This affects both the local and remote constituent database aliases belonging to the specified composite database.
However, the behavior does not cascade further, the target of those constituent database aliases are not dropped.

Using `CASCADE ALIASES` requires the `DROP ALIAS` privilege (see xref:authentication-authorization/dbms-administration.adoc#access-control-dbms-administration-alias-management[ALIAS MANAGEMENT privileges]).

Given composite database and database alias:
[source, cypher]
----
CREATE COMPOSITE DATABASE movies
CREATE ALIAS movies.sweden FOR DATABASE `swedish-movies`
----

Then both the constituent database alias `sweden` and the composite database `movies` will be dropped with:
[source, cypher]
----
DROP COMPOSITE DATABASE movies CASCADE ALIASES
----

This behavior would be the same for the more general command `DROP DATABASE name` when using it to drop a composite database.

The option `RESTRICT` explicitly requests the default behavior of the command.

[NOTE]
====
For composite databases, the aliases that will be dropped when using the `CASCADE ALIASES` option can be found in the `constituents` column of `SHOW DATABASE`.
====

