[role=enterprise-edition not-on-aura]
[[composite-databases]]
= Managing composite databases

This page describes how to manage composite databases in Neo4j.
Note that it is not possible to modify access options or database topologies for composite databases.


[[composite-databases-create]]
== Creating and listing composite databases

Composite databases can be created using `CREATE COMPOSITE DATABASE`.

Composite database names are subject to the same rules as xref:administration-databases-create-database[standard databases].
One difference is however that the deprecated syntax using dots without enclosing the name in backticks is not available.
Both dots and dashes need to be enclosed within backticks when using composite databases.

[NOTE]
====
Having dots (`.`) in the composite database names is not recommended.
This is due to the difficulty of determining if a dot is part of the composite database name or a delimiter for a database alias in a composite database.
====

.+CREATE COMPOSITE DATABASE+
=====
.Query
[source, cypher, role=test-setup]
----
CREATE COMPOSITE DATABASE inventory
----
=====

.+SHOW DATABASE+
======

When a composite database has been created, it will show up in the listing provided by the command `SHOW DATABASES`.

.Query
[source, cypher]
----
SHOW DATABASES 
----

.Result
[role="queryresult"]
----
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| name        | type        | aliases | access       | address          | role      | writer | requestedStatus | currentStatus | statusMessage | default | home  | constituents |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "inventory" | "composite" | []      | "read-only"  | "localhost:7687" | NULL      | FALSE  | "online"        | "online"      | ""            | FALSE   | FALSE | []           |
| "neo4j"     | "standard"  | []      | "read-write" | "localhost:7687" | "primary" | TRUE   | "online"        | "online"      | ""            | TRUE    | TRUE  | []           |
| "system"    | "system"    | []      | "read-write" | "localhost:7687" | "primary" | TRUE   | "online"        | "online"      | ""            | FALSE   | FALSE | []           |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
----

======


For a full description of the columns returned by this command, and how to sort the results by specific columns, see xref:database-administration/standard-databases/manage-databases.adoc#manage-databases-listing-databases[here].

In order to create database aliases in the composite database, give the composite database as namespace for the alias.
For information about creating aliases in composite databases, see xref:database-administration/aliases/manage-aliases.adoc#alias-management-create-composite-database-alias[here].

[[composite-databases-existing]]
== Handling existing composite databases

These commands are optionally idempotent, with the default behavior to fail with an error if the database already exists.
Appending `IF NOT EXISTS` to the command ensures that no error is returned and nothing happens should the database already exist.
Adding `OR REPLACE` to the command will result in any existing database being deleted and a new one created.

These behavior flags apply to both standard and composite databases (e.g. a composite database may replace a standard one or another composite.)


.+CREATE DATABASE+
======

.Query
[source, cypher]
----
CREATE COMPOSITE DATABASE inventory IF NOT EXISTS
----

This will not create a new composite database, because a composite database with the name `inventory` already exists.

======


.+CREATE OR REPLACE DATABASE+
======

.Query
[source, cypher]
----
CREATE OR REPLACE COMPOSITE DATABASE inventory
----

This is equivalent to running `DROP COMPOSITE DATABASE inventory IF EXISTS` followed by `CREATE COMPOSITE DATABASE inventory`.

======


[NOTE]
====
The `IF NOT EXISTS` and `OR REPLACE` parts of these commands cannot be used together.
====

[[composite-databases-stop]]
== Stopping composite databases

Databases can be stopped using the command `STOP DATABASE`.


.+STOP DATABASE+
======

.Query
[source, cypher]
----
STOP DATABASE inventory
----

[NOTE]
====
Both standard databases and composite databases can be stopped using this command.
====

======

.+SHOW STOPPED DATABASE+
======

The status of the stopped database can be seen using the command `SHOW DATABASE name`.

.Query
[source, cypher]
----
SHOW DATABASE inventory YIELD name, requestedStatus, currentStatus
----

.Result
[role="queryresult"]
----
+-----------------------------------------------+
| name        | requestedStatus | currentStatus |
+-----------------------------------------------+
| "inventory" | "offline"       | "offline"     |
+-----------------------------------------------+
----

======

[[composite-databases-start]]
== Starting composite databases

Databases can be started using the command `START DATABASE`.


.+START DATABASE+
======

.Query
[source, cypher]
----
START DATABASE inventory
----

[NOTE]
====
Both standard databases and composite databases can be stopped using this command.
====

======


.+SHOW STARTED DATABASE+
======

The status of the started database can be seen using the command `SHOW DATABASE name`.

.Query
[source, cypher]
----
SHOW DATABASE inventory YIELD name, requestedStatus, currentStatus
----

.Result
[role="queryresult",options="header,footer",cols="3*<m"]
----
+-----------------------------------------------+
| name        | requestedStatus | currentStatus |
+-----------------------------------------------+
| "inventory" | "online"        | "online"      |
+-----------------------------------------------+
----

======

[[composite-databases-delete]]
== Deleting composite databases

Composite databases can be deleted using the command `DROP COMPOSITE DATABASE name`.
This command will fail if the targeted database is not a composite database.
It is also possible to use the shorter command `DROP DATABASE name` for composite databases, but this command will not fail in case the targeted database is not a composite database.

.+DROP COMPOSITE DATABASE+
======

.Query
[source, cypher]
----
DROP COMPOSITE DATABASE inventory
----

======
