:description: This chapter describes how to enable the metrics that you want to monitor.
[role=enterprise-edition]
[[metrics-enable]]
= Enable metrics logging

[NOTE]
====
A subset of all available metrics is enabled by default.
See xref:reference/configuration-settings.adoc#config_metrics.filter[`metrics.filter`].
The list was last updated in version 4.2.
====

You can enable/disable metrics using the configuration setting xref:reference/configuration-settings.adoc#config_metrics.enabled[`metrics.enabled`].
You can also use the setting `metrics.filter` to enable only the metrics that you want.
The metrics must be specified as a comma-separated list of globbing patterns.
The following example enables all checkpoint metrics and the pagecache eviction metric:

[source, properties]
----
# Setting for enabling all supported metrics. (Default is true) Setting this to false disables all metrics.
metrics.enabled=true

# Setting for exposing metrics.
metrics.filter=*check_point*,neo4j.page_cache.evictions
----

When specifying a complete metric name, you should take into account whether xref:reference/configuration-settings.adoc#config_metrics.namespaces.enabled[`metrics.namespaces.enabled`] is set.

All metrics are logged to CSV files in the _/metrics_ folder.
