[role=enterprise-edition]
[[metrics-expose]]
= Expose metrics
:description: This section describes how to log and display various metrics by using the Neo4j metrics output facilities. 


This section describes the following:

** xref:monitoring/metrics/expose.adoc#metrics-enable[Enable metrics logging]
** xref:monitoring/metrics/expose.adoc#metrics-graphite[Graphite]
** xref:monitoring/metrics/expose.adoc#metrics-prometheus[Prometheus]
** xref:monitoring/metrics/expose.adoc#metrics-csv[CSV files]
** xref:monitoring/metrics/expose.adoc#metrics-jmx[JMX MBeans]


[[metrics-enable]]
== Enable metrics logging

By default, metrics logging into CSV files and exposure via JMX MBeans are enabled.
All metrics are enabled once `metrics.enabled=true` is set and you can use the individual settings to disable specific metrics.

[source, properties]
----
# Setting for enabling all supported metrics.
metrics.enabled=true

# Setting for exposing metrics about transactions; number of transactions started, committed, etc.
metrics.neo4j.tx.enabled=false

# Setting for exposing metrics about the Neo4j page cache; page faults, evictions, flushes and exceptions, etc.
metrics.neo4j.pagecache.enabled=false

# Setting for exposing metrics about approximately entities are in the database; nodes, relationships, properties, etc.
metrics.neo4j.counts.enabled=false
----


[[metrics-graphite]]
== Graphite

Send metrics to https://graphiteapp.org/[Graphite] or any monitoring tool based on the Graphite protocol.

Add the following settings to xref:configuration/neo4j-conf.adoc[_neo4j.conf_] in order to enable integration with Graphite:

[source, properties]
----
# Enable the Graphite integration. Default is 'false'.
metrics.graphite.enabled=true
# The IP and port of the Graphite server on the format <hostname or IP address>:<port number>.
# The default port number for Graphite is 2003.
metrics.graphite.server=localhost:2003
# How often to send data. Default is 3 seconds.
metrics.graphite.interval=3s
# Prefix for Neo4j metrics on Graphite server.
metrics.prefix=Neo4j_1
----

Start Neo4j and connect to Graphite via a web browser in order to monitor your Neo4j metrics.

[NOTE]
--
If you configure the Graphite server to be a hostname or DNS entry you should be aware that the JVM resolves hostnames to IP addresses and by default caches the result indefinitely for security reasons.
This is controlled by the value of `networkaddress.cache.ttl` in the JVM Security properties.
See https://docs.oracle.com/javase/8/docs/technotes/guides/net/properties.html for more information.
--


[[metrics-prometheus]]
== Prometheus

Publish metrics for polling as https://prometheus.io/[Prometheus] endpoint.

Add the following settings to _neo4j.conf_ in order to enable the Prometheus endpoint.

[source, properties]
----
# Enable the Prometheus endpoint. Default is 'false'.
metrics.prometheus.enabled=true
# The IP and port the endpoint will bind to in the format <hostname or IP address>:<port number>.
# The default is localhost:2004.
metrics.prometheus.endpoint=localhost:2004
----

When Neo4j is fully started a Prometheus endpoint will be available at the configured address.


[[metrics-csv]]
== CSV files

Export metrics to CSV files.

Add the following settings to _neo4j.conf_ in order to enable export of metrics into local .CSV files:

[source, properties]
----
# Enable the CSV exporter. Default is 'true'.
metrics.csv.enabled=true
# Directory path for output files.
# Default is a "metrics" directory under NEO4J_HOME.
#dbms.directories.metrics='/local/file/system/path'
# How often to store data. Default is 3 seconds.
metrics.csv.interval=3s
# The maximum number of CSV files that will be saved. Default is 7.
metrics.csv.rotation.keep_number=7
# The file size at which the csv files will auto-rotate. Default is 10M.
metrics.csv.rotation.size=10M
----

[[metrics-jmx]]
== JMX MBeans

Expose metrics over JMX MBeans.

In order to enable metrics exposure via JMX, add the following setting to xref:configuration/neo4j-conf.adoc[_neo4j.conf_]:

[source, properties]
----
# Enable settings export via JMX. Default is 'true'.
metrics.jmx.enabled=true
----

For more information about accessing and adjusting the metrics, see link:{neo4j-docs-base-uri}/java-reference/{page-version}/jmx-metrics/[The Java Reference Guide -> JMX metrics].