[role=enterprise-edition]
[[metrics-expose]]
= Expose metrics
:description: This section describes how to log and display various metrics by using the Neo4j metrics output facilities. 


[[metrics-enable]]
== Enable metrics logging

[CAUTION]
====
The metrics that are enabled by default have been changed in the 4.2 release.

Any specific metrics that you want to be enabled *must* be specified in the `metrics.filter`.
====

By default, metrics logging into CSV files is enabled.
A subset of metrics are enabled once `metrics.enabled=true` is set, and you can use the `metrics.filter` setting to select the specific metrics you want to enable.

The `metrics.filter` should be specified as a comma separated list of globbing patterns.
For example, `\*check_point*,neo4j.dbms.page_cache.evictions` will enable all checkpoint metrics and the pagecache eviction metric.
When specifying a complete metric name, you should take into account whether `metrics.namespaces.enabled` is set:

[source, properties]
----
# Setting for enabling all supported metrics.
metrics.enabled=true

# Setting for enabling clear separation between global and database metrics.
metrics.namespaces.enabled=true

# Setting for exposing metrics. Should be specified as a comma separated list of globbing patterns.
metrics.filter=*causal_clustering*,*check_point*,neo4j.dbms.page_cache.evictions
----


[[metrics-graphite]]
== Graphite

Send metrics to https://graphiteapp.org/[Graphite] or any monitoring tool based on the Graphite protocol.

Add the following settings to xref:configuration/neo4j-conf.adoc[_neo4j.conf_] in order to enable integration with Graphite:

[source, properties]
----
# Enable the Graphite integration. Default is 'false'.
metrics.graphite.enabled=true
# The IP and port of the Graphite server on the format <hostname or IP address>:<port number>.
# The default port number for Graphite is 2003.
metrics.graphite.server=localhost:2003
# How often to send data. Default is 30 seconds.
metrics.graphite.interval=30s
# Prefix for Neo4j metrics on Graphite server.
metrics.prefix=Neo4j_1
----

Start Neo4j and connect to Graphite via a web browser in order to monitor your Neo4j metrics.

[NOTE]
--
If you configure the Graphite server to be a hostname or DNS entry you should be aware that the JVM resolves hostnames to IP addresses and by default caches the result indefinitely for security reasons.
This is controlled by the value of `networkaddress.cache.ttl` in the JVM Security properties.
See https://docs.oracle.com/javase/8/docs/technotes/guides/net/properties.html for more information.
--


[[metrics-prometheus]]
== Prometheus

Publish metrics for polling as https://prometheus.io/[Prometheus] endpoint.

Add the following settings to _neo4j.conf_ in order to enable the Prometheus endpoint.

[source, properties]
----
# Enable the Prometheus endpoint. Default is 'false'.
metrics.prometheus.enabled=true
# The IP and port the endpoint will bind to in the format <hostname or IP address>:<port number>.
# The default is localhost:2004.
metrics.prometheus.endpoint=localhost:2004
----

When Neo4j is fully started, a Prometheus endpoint will be available at the configured address.

[WARNING]
====
You should never expose the Prometheus endpoint directly to the Internet. 
If security is of paramount importance, you should set `metrics.prometheus.endpoint=localhost:2004` and configure a reverse HTTP proxy on the same machine that handles the authentication, SSL, caching, etc. 
====
If you can afford to send unencrypted metrics within the internal network, such as `metrics.prometheus.endpoint=10.0.0.123:2004`, all servers within the same netmask will be able to access it.

If you specify anything more permissible, such as `metrics.prometheus.endpoint=0.0.0.0:2004`, you should have a firewall rule to prevent any unauthorized access. 
Data in transit will still not be encrypted, so it should never go other any insecure networks.

[[metrics-csv]]
== CSV files

Export metrics to CSV files.

Add the following settings to _neo4j.conf_ in order to enable export of metrics into local .CSV files:

[source, properties]
----
# Enable the CSV exporter. Default is 'true'.
metrics.csv.enabled=true
# Directory path for output files.
# Default is a "metrics" directory under NEO4J_HOME.
#dbms.directories.metrics='/local/file/system/path'
# How often to store data. Default is 30 seconds.
metrics.csv.interval=30s
# The maximum number of CSV files that will be saved. Default is 7.
metrics.csv.rotation.keep_number=7
# The file size at which the csv files will auto-rotate. Default is 10M.
metrics.csv.rotation.size=10M
# Compresses the metric archive files.
metrics.csv.rotation.compression=zip
----

xref:reference/configuration-settings.adoc#config_metrics.csv.rotation.compression[metrics.csv.rotation.compression] selects the compression scheme to use on the files after rotation.
Since CSV files are highly compressible, it is recommended to enable compression of the files to save disk space.

[[metrics-jmx]]
== JMX MBeans

Expose metrics over JMX MBeans.

In version 4.2.2 and later, metrics via JMX are exposed by default.
In version 4.2.0 and 4.2.1, you can enable them by adding the following setting to xref:configuration/neo4j-conf.adoc[_neo4j.conf_]:

[source, properties]
----
# Enable settings export via JMX.
metrics.jmx.enabled=true
----

For more information about accessing and adjusting the metrics, see link:{neo4j-docs-base-uri}/java-reference/{page-version}/jmx-metrics/[The Java Reference Guide -> JMX metrics].
