:description: This chapter describes some essential metrics to monitor in Neo4j, how to enable their logging, and how to view them.
[role=enterprise-edition]
[[metrics]]
= Metrics

You can configure Neo4j to log many different metrics to help you keep your applications running smoothly.
By default, you can view this data via Neo4j Ops Manager (https://neo4j.com/docs/ops-manager/[NOM]), retrieved from CSV files, or exposed over JMX MBeans, but you can also export it to third-party monitoring tools, such as https://graphiteapp.org/[Graphite] and https://prometheus.io/[Prometheus].

[TIP]
====
Reading the xref:performance/index.adoc[] section is recommended to better understand the metrics.
====

This section describes the following:

** xref:monitoring/metrics/essential.adoc[Essential metrics] -- Some of the important metrics most Neo4j administrators need to monitor.
** xref:monitoring/metrics/enable.adoc[Enable metrics logging] -- How to configure Neo4j to log metrics data.
** xref:monitoring/metrics/expose.adoc[Expose metrics] -- How to view data using NOM, JMX, CSV files, or other third-party monitoring tools.
** xref:monitoring/metrics/reference.adoc[Metrics reference] -- Neo4j available metrics.
