[role=enterprise-edition]
[[metrics-reference]]
= Metrics reference
:description: This section includes metrics that are primarily to allow Neo4j experts to fine-tune specific issues. 

[CAUTION]
====
You should use caution when interpreting unfamiliar metrics.
Reading the xref:performance/index.adoc[] section is recommended to better understand the metrics.
====

[[metrics-types]]
== Types of metrics

Neo4j has the following types of metrics:

* Global -- covers the whole Neo4j DBMS.
* Per database -- covers an individual database.

The metrics fall into one of the following categories:

* Gauge -- shows an instantaneous reading of a particular value.
* Counter -- shows an accumulated value.
* Histogram -- shows the distribution of values.

[[metrics-global]]
=== Global metrics

Global metrics cover the whole database management system, and represents the status of the system as a whole.

Global metrics have the following name format: `<user-configured-prefix>.<metric-name>` if `xref:reference/configuration-settings.adoc#config_metrics.namespaces.enabled[metrics.namespaces.enabled]` is `false`, or `<user-configured-prefix>.dbms.<metric-name>` if the setting is `true`.
The <user-configured-prefix> can be configured with the `xref:reference/configuration-settings.adoc#config_metrics.prefix[metrics.prefix]` configuration setting.

Metrics of this type are reported as soon as the database management system is available.
For example, all JVM related metrics are global.
In particular, the `neo4j.vm.thread.count` metric has a default user-configured-prefix `neo4j` and the metric name is `vm.thread.count`.

By default, global metrics include:


* Bolt metrics
* Page cache metrics
* GC metrics
* Thread metrics
* Database operation metrics
* Web Server metrics
* JVM metrics

=== Database metrics

Each database metric is reported for a particular database only.
Database metrics are only available during the lifetime of the database.
When a database becomes unavailable, all of its metrics become unavailable also.

Database metrics have the following name format: `<user-configured-prefix>.<database-name>.<metric-name>` if `xref:reference/configuration-settings.adoc#config_metrics.namespaces.enabled[metrics.namespaces.enabled]` is `false`, or `<user-configured-prefix>.database.<database-name>.<metric-name>` if the setting is `true`.
The <user-configured-prefix> can be configured with the `xref:reference/configuration-settings.adoc#config_metrics.prefix[metrics.prefix]` configuration setting.

For example, any transaction metric is a database metric.
In particular, the `neo4j.mydb.transaction.started` metric has a default user-configured-prefix `neo4j`
and is a metric for the `mydb` database.

By default, database metrics include:

 * Transaction metrics
 * Checkpoint metrics
 * Log rotation metrics
 * Database data metrics
 * Cypher metrics
 * Causal clustering metrics

[[metrics-general-purpose]]
== General-purpose metrics

include::{import-neo4j-metrics-docs-docs}/ops/available-metrics.adoc[leveloffset=+1]


[[causal-clustering-metrics]]
== Metrics specific to Causal Clustering

include::{import-neo4j-metrics-docs-docs}/ops/cc-metrics.adoc[]


[[jvm-metrics]]
== Java Virtual Machine Metrics

The JVM metrics show information about garbage collections (for example, the number of events and time spent collecting), memory pools and buffers, and the number of active threads running.
They are environment dependent and therefore, may vary on different hardware and with different JVM configurations.
The metrics about the JVM's memory usage expose values that are provided by the MemoryPoolMXBeans and BufferPoolMXBeans.
The memory pools are memory managed by the JVM, for example, `neo4j.vm.memory.pool.g1_survivor_space`.
Therefore, if necessary, you can tune them using the JVM settings.
The buffer pools are space outside of the memory managed by the garbage collector.
Neo4j allocates buffers in those pools as it needs them.
You can limit this memory using JVM settings, but there is never any good reason for you to set them.

include::{import-neo4j-metrics-docs-docs}/ops/jvm-metrics.adoc[leveloffset=-1]
