
:description: Import progress reporting using the `neo4j-admin database import` command.
:page-role: new-2026.03
[[import-logs]]
= Import progress reporting

When starting the import, the `neo4j-admin database import` command creates a directory where it stores information about the import process, such as verbose logging, detailed progress, bad collector information (see the `--bad-tolerance` option), and profiling (Java flight recording) if enabled.
If the `--profile-results-path` option is provided, then this path is used instead for Java flight records.

The directory is created with a unique name that includes the database name and the timestamp of when the import started, in the form of _server/data/imports/dbname-yyyy-MM-dd.HH.mm.ss_.
In 2026.04, the directory location is changed from _server/data/imports_ to _server/logs/_.

The directory is removed at the end of the import job, except in the following cases:

* Profiling or verbose mode is enabled.
* Import fails with errors.
* Violations are reported by the bad collector, i.e., the import succeeds but data issues are detected.

The detailed progress of reporting is in `progress.json.log` and is a JSON object entry per line for each snapshot.

Violations are reported as JSON object entries, one per line, in `report.json.log`.

The import CLI supports the `--report-file` option to override the default output path.
When provided, violations are written to the specified location in the same JSON format.

Each JSON entry includes a `message` field equivalent to the pre-2026.03 format, along with additional fields that provide more detailed information.

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]

endif::[]