:page-role: new-2026.01
:description: Using pattern style for matching nodes and relationships files.
[[path-pattern-style]]
= Using pattern style for matching nodes and relationships files

The import tool supports three different pattern styles for matching `--nodes` and `--relationships` files using the `--path-pattern-style` argument of the import command.
Pattern styles are `glob`, `regex`, and `none`.
The default pattern style is `regex`.

`glob`::
Use `glob` style pattern matching when you have a lot of data organized into a more nested folder structure, for example, data grouped together by years:
+
[source]
----
/data/invoices/2024/invoices_jan.csv
...
/data/invoices/2024/invoices_dec.csv
/data/invoices/2025/invoices_jan.csv
...
/data/invoices/2025/invoices_dec.csv
/data/invoices/2026/invoices_jan.csv
----
+
It allows you to import all the files via something like `/data/invoices/**/invoices_{jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec}.csv`.

`regex`::
Use `regex` style pattern matching when you have a lot of data organized inside one folder.
For example:
+
[source]
----
/data/invoices/invoices_2024_1.csv
/data/invoices/invoices_2024_2.csv
...
/data/invoices/invoices_2026_1.csv
----
+
It allows you to import all the files via something like `/data/invoices/invoices_\d+_\d.csv`.

`none`::
Use `none` when you know the files and want to avoid pattern matching.
For example, this is especially useful when your files are in the cloud, and using the other two options may incur unnecessary performance and financial cost.

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]

endif::[]