[[debian]]
= Debian
:description: This section describes how to install Neo4j on Debian, and Debian-based distributions like Ubuntu, using the Neo4j Debian package. 

This section describes the following:

* xref:installation/linux/debian.adoc#debian-installation[Installation]
** xref:installation/linux/debian.adoc#debian-ubuntu-prerequisites[Prerequisites (Ubuntu 14.04 and Debian 8 only)]
** xref:installation/linux/debian.adoc#debian-add-repository[Add the repository]
** xref:installation/linux/debian.adoc#debian-install[Install Neo4j]
* xref:installation/linux/debian.adoc#debian-upgrade[Upgrade]
** xref:installation/linux/debian.adoc#debian-upgrade-from-3.x[Upgrade from Neo4j 3.x]
** xref:installation/linux/debian.adoc#debian-upgrade-from-2.3[Upgrade from Neo4j 2.3]
* xref:installation/linux/debian.adoc#debian-file-locations[File locations]
* xref:installation/linux/debian.adoc#debian-operation[Operation]


[[debian-installation]]
== Installation

To install Neo4j on Debian you need one of the following:

* A Java 8 runtime installed.
* The repository containing the Neo4j Debian package is known to the package manager.


[[debian-ubuntu-prerequisites]]
=== Prerequisites (Debian 8 and Ubuntu 14.04 only)

Neo4j {neo4j-version} requires the Java 8 runtime.
Java 8 is not included in Ubuntu 14.04 LTS or Debian 8 (jessie) and will have to be installed manually prior to installing or upgrading to Neo4j {neo4j-version}.
Debian 9 and Ubuntu 16.04 onwards already have the Openjdk Java 8 package available through `apt`.

Please note that users can no longer use Oracle Java 8 on Debian.


[[debian-java]]
==== Java 8 on Debian 8

. Add the line `deb http://archive.debian.org/debian jessie-backports main` to a file with the `.list` extension in _/etc/apt/sources.list.d/_.
+
In order to install Java, you will need to disable validity checks before running `apt-get update`:
+
[source, shell]
----
echo "deb http://archive.debian.org/debian jessie-backports main" | sudo tee /etc/apt/sources.list.d/jessie-backports.list
echo "Acquire::Check-Valid-Until false;" | sudo tee /etc/apt/apt.conf.d/10no-check-valid-until
sudo apt-get update
----
+
. For Java 8 to install with Neo4j, you must next install OpenJDK 8:
+
[source, shell]
----
sudo apt-get -t jessie-backports -y install openjdk-8-jre
----

You are now ready to install Neo4j {neo4j-version-exact}.
See xref:installation/linux/debian.adoc#multiple-java-versions[Dealing with multiple installed Java versions] to make sure you can start Neo4j after install.


[[ubuntu-java8]]
==== Java 8 on Ubuntu 14.04

* Users can no longer use Oracle Java 8 on Debian 8, and must use OpenJDK 8 to install:
+
[source, shell]
----
sudo add-apt-repository -y ppa:openjdk-r/ppa
sudo apt-get update
----

* Once installed, see xref:installation/linux/debian.adoc#multiple-java-versions[Dealing with multiple installed Java versions] to make sure you can start Neo4j after install.

You are now ready to install Neo4j {neo4j-version-exact}.
See xref:installation/linux/debian.adoc#multiple-java-versions[Dealing with multiple installed Java versions] to make sure you can start Neo4j after install.

[[multiple-java-versions]]
===== Dealing with multiple installed Java versions

It is important that you configure your default Java version to point to Java 8, or Neo4j {neo4j-version-exact} will be unable to start.
Do so with the `update-java-alternatives` command.

* First list all your installed version of Java with `update-java-alternatives --list`
+
Your results may vary, but this is an example of the output:
+
[source, shell]
----
java-1.7.0-openjdk-amd64 1071 /usr/lib/jvm/java-1.7.0-openjdk-amd64
java-1.8.0-openjdk-amd64 1069 /usr/lib/jvm/java-1.8.0-openjdk-amd64
----

* Identify your Java 8 version, in this case it is `java-1.8.0-openjdk-amd64`.
Then set it as the default with (replacing `<java8name>` with the appropriate name from above)
+
[source, shell]
----
sudo update-java-alternatives --jre --set <java8name>
----


[[debian-add-repository]]
=== Add the repository

* The Debian package is available from https://debian.neo4j.com.
To use the repository, follow these steps:
+
[source, shell,subs="attributes"]
----
wget -O - https://debian.neo4j.com/neotechnology.gpg.key | sudo apt-key add -
echo 'deb https://debian.neo4j.com stable {neo4j-version}' | sudo tee -a /etc/apt/sources.list.d/neo4j.list
sudo apt-get update
----


[NOTE]
====
In Ubuntu server installations you will also need to make sure that the `universe` repository is enabled.
If the `universe` repository is not present, the Neo4j installation will fail with the error `Depends: daemon but it is not installable`.

This can be fixed by running the command:
[source, shell,subs="attributes"]
----
sudo add-apt-repository universe
----
====


[[debian-install]]
=== Install Neo4j

To install Neo4j Community Edition:

[source, shell, subs="attributes"]
----
sudo apt-get install neo4j=1:{neo4j-version-exact}
----

To install Neo4j Enterprise Edition:

[source, shell, subs="attributes"]
----
sudo apt-get install neo4j-enterprise=1:{neo4j-version-exact}
----

Note that the version includes an epoch version component (`1:`), in accordance with the https://www.debian.org/doc/debian-policy/#s-f-version[Debian policy on versioning].

When installing Neo4j Enterprise Edition, you will be prompted to accept the license agreement.
Once the license agreement is accepted installation begins.
Your answer to the license agreement prompt will be remembered for future installations on the same system.

To forget the stored answer, and trigger the license agreement prompt on subsequent installation, use `debconf-communicate` to purge the stored answer:

[source, shell]
----
echo purge | sudo debconf-communicate neo4j-enterprise
----


==== Non-interactive installation of Neo4j Enterprise Edition

For Neo4j Enterprise Edition, the license agreement is presented in an interactive prompt.
If you require non-interactive installation of Neo4j Enterprise Edition, you can indicate that you have read and accepted the license agreement using `debconf-set-selections`:

[source, shell]
----
echo "neo4j-enterprise neo4j/question select I ACCEPT" | sudo debconf-set-selections
echo "neo4j-enterprise neo4j/license note" | sudo debconf-set-selections
----


[[debian-offline-installation]]
==== Offline installation

If you cannot reach `https://debian.neo4j.com`, perhaps due to a firewall, you will need to obtain Neo4j via an alternative machine which has the relevant access, and then move the package manually.

[NOTE]
====
It is important to note that using this method will mean that the offline machine will not receive the dependencies that
are that are normally downloaded and installed automatically when using `apt` for installing Neo4j; xref:tools/cypher-shell.adoc[Cypher Shell] and Java (if not installed already):

* The Cypher Shell package can be downloaded from {neo4j-download-center-uri}[Neo4j Download Center].
* For information on supported versions of Java, see xref:installation/requirements.adoc[System requirements].
====

. Run the following to download the required Debian package:
** Neo4j Enterprise Edition:
+
[source, shell, subs="attributes"]
----
curl -O https://dist.neo4j.org/deb/neo4j-enterprise_{neo4j-version-exact}_all.deb
----
** Neo4j Community Edition:
+
[source, shell, subs="attributes"]
----
curl -O https://dist.neo4j.org/deb/neo4j_{neo4j-version-exact}_all.deb
----

. Manually move the downloaded Debian package to the offline machine.
. Run the following on the offline machine to install Neo4j:
+
[source, shell]
----
sudo dpkg -i <deb file name>
----


[[debian-upgrade]]
== Upgrade


[[debian-upgrade-from-3.x]]
=== Upgrade from Neo4j 3.x

For upgrade of any 3.x version of Neo4j to {neo4j-version-exact}, follow instructions in xref:upgrade/index.adoc[Upgrade].


[[debian-upgrade-from-2.3]]
=== Upgrade from Neo4j 2.3

Follow the steps below when upgrading a Neo4j Debian/Ubuntu installation:

. Upgrade to Neo4j 3.2:
+
.. Migrate the configuration files.
+
The configuration files changed between Neo4j versions 2.3 and 3.2.
If you have not edited the configuration files, the Debian package will remove the files that are no longer necessary, and replace the old default files with new default files.
+
If you have changed configuration values in your 2.3 installation, you can use the provided config migration tool.
Two arguments are provided to tell the config migrator where to find the _conf/_ directory for the source and the destination.
Both must be provided, due to the filesystem layout of the Debian packages.
+
Because the Neo4j files and directories are owned by the `neo4j` user and `adm` group on Debian, it is necessary to use `sudo` to make sure the permissions remain intact:
+
[source, shell]
----
sudo -u neo4j -g adm java -jar /usr/share/neo4j/bin/tools/2.x-config-migrator.jar /var/lib/neo4j /var/lib/neo4j
----

.. Import the Neo4j 2.3 database to Neo4j 3.2.
+
The location of the database changed between Neo4j versions 2.3 and 3.2.
The Neo4j 2.3 databases will need to be imported to Neo4j 3.2.
To do this, use the `neo4j-admin import` command.
+
For example, to import a database called `graph.db` (the default database name in Neo4j 2.3), use the following command:
+
[source, shell]
----
sudo -u neo4j neo4j-admin import --mode=database --database=graph.db --from=/var/lib/neo4j/data/graph.db
----
+
This command will import the database located in `/var/lib/neo4j/data/graph.db` into Neo4j 3.2, and call it `graph.db`.
+
Once a database has been imported, and the upgrade has completed successfully, the old database can be removed safely.

.. Migrate the Neo4j 2.3 database to Neo4j 3.2.
+
The previous import step moved the database from its old on-disk location to the new on-disk location, but it did not upgrade the store format.
To do this, you must start the database service with the option to migrate the database format to the latest version.
+
In _neo4j.conf_ uncomment the option xref:reference/configuration-settings.adoc#config_dbms.allow_upgrade[`dbms.allow_upgrade=true`].
You can use the following command to change the line in-place if you have it commented out already, as it is in the default configuration:
+
[source, shell]
----
sudo sed -i 's/#dbms.allow_upgrade=true/dbms.allow_upgrade=true/' /etc/neo4j/neo4j.conf
----
+
Start the database service with the format migration option enabled, and the format migration will take place immediately:
+
[source, shell]
----
sudo service neo4j start
----


. Upgrade to Neo4j {neo4j-version-exact}.
+
Upgrade to Neo4j {neo4j-version-exact} by following the instructions in xref:upgrade/index.adoc[Upgrade].


[[debian-file-locations]]
== File locations

File locations for all Neo4j packages are documented xref:configuration/file-locations.adoc[_here_].


[[debian-operation]]
== Operation

Most Neo4j configuration goes into xref:configuration/file-locations.adoc[_neo4j.conf_].

For operating systems using `systemd`, some package-specific options are set in _neo4j.service_ and can be edited using `systemctl edit neo4j.service`.

For operating systems that are not using `systemd`, some package-specific options are set in _/etc/default/neo4j_.

[options="header"]
|===
| Environment variable     | Default value | Details
| _NEO4J_SHUTDOWN_TIMEOUT_ | _120_           | Timeout in seconds when waiting for Neo4j to stop. If it takes longer than this then the shutdown is considered to have failed. This may need to be increased if the system serves long-running transactions.
| _NEO4J_ULIMIT_NOFILE_    | _60000_         | Maximum number of file handles that can be opened by the Neo4j process.
|===
