:description: This section describes how to install Neo4j on Debian, and Debian-based distributions like Ubuntu, using the Neo4j Debian package.
[[debian]]
= Debian-based distributions (.deb)

[[debian-installation]]
== Installation

To install Neo4j on Debian you need to make sure of the following:

* An OpenJDK Java 11 runtime is installed or available through your package manager.
* The repository containing the Neo4j Debian package is known to the package manager.


[[debian-ubuntu-prerequisites]]
=== Java Prerequisites (Oracle Java and Ubuntu 16.04+ only)

Neo4j {neo4j-version} requires the Java 11 runtime.
Java 11 is not included in Ubuntu 16.04 LTS and will have to be set up manually prior to installing or upgrading to Neo4j {neo4j-version}, as described below.
Ubuntu 18.04 onwards already has the Openjdk Java 11 package available through `apt`.


[[debian-oraclejava]]
==== Oracle Java and Debian

Neo4j is compatible with Oracle Java on Debian/Ubuntu Linux, but should be installed via xref:installation/linux/tarball.adoc[tarball].
The Debian installer may still be used, but it will install OpenJDK Java 11 in addition to any existing Java installations.

This is due to changes in Oracle's Debian package manifest between Java versions 8 and 11.

[source, shell]
----
echo "deb https://httpredir.debian.org/debian stretch-backports main" | sudo tee -a /etc/apt/sources.list.d/stretch-backports.list
sudo apt-get update
sudo apt-get install openjdk-11-jre
----

If you already had a different version of Java installed, see xref:installation/linux/debian.adoc#multiple-java-versions[Dealing with multiple installed Java versions] to make sure Java 11 is the default version.
You are now ready to install Neo4j.


[[ubuntu-java11]]
==== Java 11 on Ubuntu 16.04

Add the official OpenJDK package repository to `apt`:

[source, shell]
----
sudo add-apt-repository -y ppa:openjdk-r/ppa
sudo apt-get update
----

You are now ready to install Neo4j, which will install Java 11 automatically if it is not already installed.
See xref:installation/linux/debian.adoc#multiple-java-versions[Dealing with multiple installed Java versions] to make sure you can start Neo4j after install.


[[multiple-java-versions]]
==== Dealing with multiple installed Java versions

It is important that you configure your default Java version to point to Java 11, or Neo4j {neo4j-version-exact} will be unable to start.
Do so with the `update-java-alternatives` command.

* First list all your installed version of Java with `update-java-alternatives --list`
+
Your results may vary, but this is an example of the output:
+
[source, shell]
----
java-1.11.0-openjdk-amd64 1071 /usr/lib/jvm/java-1.11.0-openjdk-amd64
java-1.8.0-openjdk-amd64 1069 /usr/lib/jvm/java-1.8.0-openjdk-amd64
----

* Identify your Java 11 version, in this case it is `java-1.11.0-openjdk-amd64`.
Then set it as the default with (replacing `<java11name>` with the appropriate name from above)
+
[source, shell]
----
sudo update-java-alternatives --jre --set <java11name>
----


[[debian-add-repository]]
=== Add the repository

The Debian package is available from https://debian.neo4j.com.


* To use the repository for generally available versions of Neo4j, run:
+
[source, shell]
----
wget -O - https://debian.neo4j.com/neotechnology.gpg.key | sudo apt-key add -
echo 'deb https://debian.neo4j.com stable latest' | sudo tee -a /etc/apt/sources.list.d/neo4j.list
sudo apt-get update
----
+
To avoid the risk of the `apt` package manager accidentally forcing a database upgrade, different major and minor releases of Neo4j are also available separately inside the repository.
To install Neo4j this way, specify the major and minor version required, in place of `latest`.
+
We recommend the following method for production or business critical installations:
+
[source, shell, subs="attributes"]
----
wget -O - https://debian.neo4j.com/neotechnology.gpg.key | sudo apt-key add -
echo 'deb https://debian.neo4j.com stable {neo4j-version}' | sudo tee -a /etc/apt/sources.list.d/neo4j.list
sudo apt-get update
----

* Once the repository has been added into `apt`, you can verify which Neo4j versions are available by running:
+
[source, shell]
----
apt list -a neo4j
----


[NOTE]
====
In Ubuntu server installations you will also need to make sure that the `universe` repository is enabled.
If the `universe` repository is not present, the Neo4j installation will fail with the error `Depends: daemon but it is not installable`.

This can be fixed by running the command:
[source, shell,subs="attributes"]
----
sudo add-apt-repository universe
----
====


[[debian-install]]
=== Install Neo4j

To install Neo4j Community Edition:

[source, shell, subs="attributes"]
----
sudo apt-get install neo4j=1:{neo4j-version-exact}
----

To install Neo4j Enterprise Edition:

[source, shell, subs="attributes"]
----
sudo apt-get install neo4j-enterprise=1:{neo4j-version-exact}
----

Note that the version includes an epoch version component (`1:`), in accordance with the https://www.debian.org/doc/debian-policy/[Debian policy on versioning].

[NOTE]
====
Versions of Neo4j that are not yet generally available may differ in naming.

The naming structure of packages are normally composed as `neo4j-enterprise=1:<version>~<release>`.
For example, Neo4j Enterprise Edition Milestone Release 3 would be: `neo4j-enterprise=1:4.0.0~beta03mr03`.

Refer to the download page for more information regarding the name of packages.
====

When installing Neo4j Enterprise Edition, you will be prompted to accept the license agreement.
Once the license agreement is accepted installation begins.
Your answer to the license agreement prompt will be remembered for future installations on the same system.

To forget the stored answer, and trigger the license agreement prompt on subsequent installation, use `debconf-communicate` to purge the stored answer:

[source, shell]
----
echo purge | sudo debconf-communicate neo4j-enterprise
----


==== Non-interactive installation of Neo4j Enterprise Edition

For Neo4j Enterprise Edition, the license agreement is presented in an interactive prompt.
If you require non-interactive installation of Neo4j Enterprise Edition, you can indicate that you have read and accepted the license agreement using `debconf-set-selections`:

[source, shell]
----
echo "neo4j-enterprise neo4j/question select I ACCEPT" | sudo debconf-set-selections
echo "neo4j-enterprise neo4j/license note" | sudo debconf-set-selections
----


[[debian-offline-installation]]
==== Offline installation

If you cannot reach `https://debian.neo4j.com`, perhaps due to a firewall, you will need to obtain Neo4j via an alternative machine which has the relevant access, and then move the package manually.

[NOTE]
====
It is important to note that using this method will mean that the offline machine will not receive the dependencies that
are that are normally downloaded and installed automatically when using `apt` for installing Neo4j; xref:tools/cypher-shell.adoc[Cypher Shell] and Java (if not installed already):

* The Cypher Shell package can be downloaded from {neo4j-download-center-uri}[Neo4j Deployment Center].
* For information on supported versions of Java, see xref:installation/requirements.adoc[System requirements].
====

. Run the following to download the required Debian software package:
** Neo4j Enterprise Edition:
+
[source, shell, subs="attributes"]
----
curl -O https://dist.neo4j.org/deb/neo4j-enterprise_{neo4j-version-exact}_all.deb
----
+
[NOTE]
====
To list all files that the Debian software package (`.deb` file) installs:
[source, shell, subs="attributes"]
----
dpkg --contents neo4j_{neo4j-version-exact}_all.deb
----
====
** Neo4j Community Edition:
+
[source, shell, subs="attributes"]
----
curl -O https://dist.neo4j.org/deb/neo4j_{neo4j-version-exact}_all.deb
----

. Manually move the downloaded Debian package to the offline machine.
. Run the following on the offline machine to install Neo4j:
+
[source, shell]
----
sudo dpkg -i <deb file name>
----

[[debian-file-locations]]
== File locations

File locations for all Neo4j packages are documented xref:configuration/file-locations.adoc[_here_].

[[debian-operation]]
== Operation

Most Neo4j configuration goes into xref:configuration/file-locations.adoc[_neo4j.conf_].

For operating systems using `systemd`, some package-specific options are set in _neo4j.service_ and can be edited using `systemctl edit neo4j.service`.

For operating systems that are not using `systemd`, some package-specific options are set in _/etc/default/neo4j_.

[options="header"]
|===
| Environment variable     | Default value | Details
| _NEO4J_SHUTDOWN_TIMEOUT_ | _120_           | Timeout in seconds when waiting for Neo4j to stop. If it takes longer than this then the shutdown is considered to have failed. This may need to be increased if the system serves long-running transactions.
| _NEO4J_ULIMIT_NOFILE_    | _60000_         | Maximum number of file handles that can be opened by the Neo4j process.
|===

[[debian-service-start-automatically]]
== Starting the service automatically on system start

On Debian-based distributions, Neo4j is enabled to start automatically on system boot by default.

[NOTE]
====
Before starting up the database for the first time, it is recommended to use the `set-initial-password` command of `neo4j-admin` to define the password for the native user `neo4j`.

If the password is not set explicitly using this method, it will be set to the default password `neo4j`.
In that case, you will be prompted to change the default password at first login.

For more information, see xref:configuration/set-initial-password.adoc[].
====

For more information on operating the Neo4j system service, see xref:installation/linux/systemd.adoc[Neo4j system service].

== Uninstall Neo4j

Follow these steps to uninstall Neo4j:

. (Optional) Create a xref:/backup-restore/index.adoc[backup] to avoid losing your data.
. Uninstall Neo4j:
+
[source, shell]
---
sudo apt remove neo4j
---