[[linux-rpm]]
= Deploy Neo4j using the Neo4j RPM package
:description: This section describes how to deploy Neo4j using the Neo4j RPM package on Red Hat, CentOS, Fedora, or Amazon Linux distributions. 


[[linux-yum]]
== Red Hat / CentOS / Fedora

For distros like Red Hat, CentOS, Fedora, and Amazon Linux the steps are as follows:

. Use the following as `root` to add the repository:
+
[source, shell]
----
rpm --import https://debian.neo4j.com/neotechnology.gpg.key
cat <<EOF >  /etc/yum.repos.d/neo4j.repo
[neo4j]
name=Neo4j RPM Repository
baseurl=https://yum.neo4j.com/stable
enabled=1
gpgcheck=1
EOF
----

. Install Neo4j.
** To install Neo4j Community Edition as `root`:
+
[source, shell, subs="attributes", role=noheader]
----
yum install neo4j-{neo4j-version-exact}
----

** To install Neo4j Enterprise Edition as `root`:
+
[source, shell, subs="attributes", role=noheader]
----
yum install neo4j-enterprise-{neo4j-version-exact}
----

. Run the following to return the version and edition of Neo4j that has been installed:
+
[source, shell, role=noheader]
----
rpm -qa | grep neo
----

[NOTE]
====
Neo4j supports Security-Enhanced Linux (SELinux), by default.
====


[[offline-installation]]
=== Offline installation

If you cannot reach `\https://yum.neo4j.com/stable` to install Neo4j using RPM, perhaps due to a firewall, you will need to obtain Neo4j via an alternative machine which has the relevant access, and then move the RPM package manually.

[NOTE]
====
It is important to note that using this method will mean that the offline machine will not receive the dependencies that are that are normally downloaded and installed automatically when using RPM for installing Neo4j; xref:tools/cypher-shell.adoc[Cypher Shell] and Java (if not installed already):

* The Cypher Shell RPM package can be downloaded from {neo4j-download-center-uri}[Neo4j Download Center].
* For information on supported versions of Java, see xref:installation/requirements.adoc[System requirements].
====

. Run the following to obtain the required RPM package:
** Neo4j Enterprise Edition:
+
[source, shell, subs="attributes", role=noheader]
----
curl -O https://dist.neo4j.org/rpm/neo4j-enterprise-{neo4j-version-exact}-1.noarch.rpm
----
** Neo4j Community Edition:
+
[source, shell, subs="attributes", role=noheader]
----
curl -O https://dist.neo4j.org/rpm/neo4j-{neo4j-version-exact}-1.noarch.rpm
----

. Manually move the downloaded RPM package to the offline machine.
. Run the following on the offline machine to install Neo4j:
+
[source, shell, role=noheader]
----
rpm -i <rpm file name>
----


[[linux-suse]]
== SUSE

[WARNING]
====
SUSE is not certified for production use.
These instructions are provided for convenience for those wishing to use Neo4j in non-production environments.
====

For SUSE-based distributions the steps are as follows:

. Use the following as `root` to add the repository:
+
[source, shell, role=noheader]
----
zypper addrepo --refresh https://yum.neo4j.com/stable neo4j-repository
----

. Install Neo4j.
** To install Neo4j Community Edition as `root`:
+
[source, shell, subs="attributes", role=noheader]
----
zypper install neo4j-{neo4j-version-exact}
----

** To install Neo4j Enterprise Edition as `root`:
+
[source, shell, subs="attributes", role=noheader]
----
zypper install neo4j-enterprise-{neo4j-version-exact}
----


[[linux-noninteractive]]
== Non-interactive installation of Neo4j Enterprise Edition

When installing Neo4j Enterprise Edition, you will be required to accept the license agreement before installation is allowed to complete.
This is an interactive prompt.
If you require non-interactive installation of Neo4j Enterprise Edition, you can indicate that you have read and accepted the license agreement by setting the environment variable `NEO4J_ACCEPT_LICENSE_AGREEMENT` to `yes`:

[source, shell, subs="attributes", role=noheader]
----
NEO4J_ACCEPT_LICENSE_AGREEMENT=yes yum install neo4j-enterprise-{neo4j-version-exact}
----


[[rpm-upgrade]]
== Upgrade

For upgrade of any 3.x version of Neo4j to Neo4j {neo4j-version-exact}, follow instructions in xref:upgrade/index.adoc[Upgrade].
