:description: How to deploy Neo4j using the Neo4j RPM package on Red Hat, CentOS, Fedora, or Amazon Linux distributions.
[[linux-rpm]]
= Deploy Neo4j using the Neo4j RPM package

You can deploy Neo4j on Red Hat, CentOS, Fedora, or Amazon Linux distributions using the Neo4j RPM package.

[[linux-rpm-prerequisites]]
== Java prerequisites

Neo4j {neo4j-version} requires the Java 17 runtime.


=== OpenJDK Java 17
Most of our supported Linux distributions have OpenJDK Java 17 available by default.
Consequently, no extra setup is required if you are using OpenJDK Java, the correct Java dependency will be installed by the package manager when installing Neo4j.


[[linux-rpm-prerequisites-oracle]]
=== Oracle Java 17
There is some minor setup required for compatibility with Oracle Java 17 because Oracle and OpenJDK provide incompatible RPM packages for Java 17.

We provide an adapter for Oracle Java 17 which must be installed before Neo4j.
The adapter contains no code, but will stop the package manager from installing OpenJDK 17 as a dependency despite an existing Oracle Java 17 installation.

. Download and install the Oracle Java 17 JDK from the https://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle website].
. Install the adapter:
+
[source, shell]
----
sudo yum install https://dist.neo4j.org/neo4j-java17-adapter.noarch.rpm
----
+
The SHA-256 of the adapter package can be verified against https://dist.neo4j.org/neo4j-java17-adapter.noarch.rpm.sha256.

=== Zulu JDK 17 or Corretto 17

If you wish to use a non-default JDK, it must be installed prior to starting the Neo4j installation.
Otherwise your package manager will install the default java distribution for your operating system, usually OpenJDK.

Installation instructions can be found on the manufacturer's website:

* https://www.azul.com/downloads/?package=jdk[Zulu JDK]
* https://aws.amazon.com/corretto[Amazon Corretto JDK]


[[linux-rpm-install]]
== Install on Red Hat, CentOS or Amazon Linux


[[linux-rpm-install-standard]]
=== Set up the repository

To use the repository for generally available versions of Neo4j, run the following as `root` to add the repository:

[source, shell]
----
rpm --import https://debian.neo4j.com/neotechnology.gpg.key
cat <<EOF >  /etc/yum.repos.d/neo4j.repo
[neo4j]
name=Neo4j RPM Repository
baseurl=https://yum.neo4j.com/stable/latest
enabled=1
gpgcheck=1
EOF
----

To avoid the risk of the package manager accidentally forcing a database upgrade, different major and minor releases of Neo4j are also available separately inside the repository.
To install Neo4j this way, specify the major and minor version required, in place of `latest`.

We recommend the following method for production or business critical installations:

[source, shell, subs="attributes"]
----
rpm --import https://debian.neo4j.com/neotechnology.gpg.key
cat <<EOF >  /etc/yum.repos.d/neo4j.repo
[neo4j]
name=Neo4j RPM Repository
baseurl=https://yum.neo4j.com/stable/{neo4j-version}
enabled=1
gpgcheck=1
EOF
----


=== Install Neo4j

* To install Neo4j Community Edition as `root`:
+
[source, shell, subs="attributes"]
----
yum install neo4j-{neo4j-version-exact}
----
+
* To install Neo4j Enterprise Edition as `root`:
+
[source, shell, subs="attributes"]
----
yum install neo4j-enterprise-{neo4j-version-exact}
----

[NOTE]
====
Neo4j supports Security-Enhanced Linux (SELinux), by default.
====


[role=enterprise-edition]
[[linux-rpm-install-noninteractive]]
=== Non-interactive installation of Neo4j Enterprise Edition

When installing Neo4j Enterprise Edition, you will be required to accept the license agreement before installation is allowed to complete.
This is an interactive prompt.
If you require non-interactive installation of Neo4j Enterprise Edition, you can indicate that you have read and accepted the license agreement by setting the environment variable `NEO4J_ACCEPT_LICENSE_AGREEMENT` to `yes`:

[source, shell, subs="attributes"]
----
NEO4J_ACCEPT_LICENSE_AGREEMENT=yes yum install neo4j-enterprise-{neo4j-version-exact}
----


[[linux-rpm-suse]]
== Install on SUSE

For SUSE-based distributions the steps are as follows:

. Use the following as `root` to add the repository:
+
[source, shell, subs="attributes"]
----
zypper addrepo --refresh https://yum.neo4j.com/stable/{neo4j-version} neo4j-repository
----

. Install Neo4j.
** To install Neo4j Community Edition as `root`:
+
[source, shell, subs="attributes"]
----
zypper install neo4j-{neo4j-version-exact}
----

** To install Neo4j Enterprise Edition as `root`:
+
[source, shell, subs="attributes"]
----
zypper install neo4j-enterprise-{neo4j-version-exact}
----


[[linux-rpm-install-offline-installation]]
== Offline installation

If you cannot reach `\https://yum.neo4j.com/stable/{neo4j-version}` to install Neo4j using RPM, perhaps due to a firewall, you will need to obtain Neo4j via an alternative machine which has the relevant access, and then move the RPM package manually.

[NOTE]
====
It is important to note that using this method will mean that the offline machine will not receive the dependencies
that are normally downloaded and installed automatically when using `yum` for installing Neo4j; xref:tools/cypher-shell.adoc[Neo4j Cypher Shell] and Java.

For information on supported versions of Java, see xref:installation/requirements.adoc[System requirements].
====


[[linux-rpm-install-offline-install-download]]
=== Downloading the RPM installers

The Cypher Shell RPM package can be downloaded from {neo4j-download-center-uri}/#cyphershell[Neo4j Download Center].

. Run the following to obtain the required Neo4j RPM package:
** Neo4j Enterprise Edition:
+
[source, curl, subs="attributes"]
----
curl -O https://dist.neo4j.org/rpm/neo4j-enterprise-{neo4j-version-exact}-1.noarch.rpm
----
** Neo4j Community Edition:
+
[source, curl, subs="attributes"]
----
curl -O https://dist.neo4j.org/rpm/neo4j-{neo4j-version-exact}-1.noarch.rpm
----
. Manually move the downloaded RPM packages to the offline machine.


If using Oracle Java 17, the same dependency issues apply as with the xref:installation/linux/rpm.adoc#linux-rpm-prerequisites-oracle[Oracle Java prerequisites].
You will need to additionally download and install the Java adaptor described in that section.


[[linux-rpm-install-offline-install-perform]]
=== Performing an offline installation

Before installing Neo4j, you must manually install the required Java 17 packages.
Then, Neo4j and Cypher Shell can be installed by running the following commands as `root` user:

[source, shell]
----
rpm --install <Cypher Shell RPM file name>
rpm --install <Neo4j RPM file name>
----


[[linux-rpm-install-offline-install-upgrade]]
==== Offline upgrade from 4.4.0 or later

Before you begin, you will need to have Java 17 pre-installed and set to the default Java version.
If using Oracle Java 17, the same dependency issues apply as with the xref:installation/linux/rpm.adoc#linux-rpm-prerequisites-oracle[Oracle Java prerequisites].

Due to strict dependencies between Neo4j and Cypher Shell, both packages must be upgraded simultaneously.
Run the following on the offline machine as `root`, to install Neo4j Cypher Shell and Neo4j simultaneously:

[source, shell]
----
rpm -U <Cypher Shell RPM file name> <Neo4j RPM file name>
----

This must be one single command, and Neo4j Cypher Shell must be the first package in the command.
