[[linux-service]]
= Neo4j system service
:description: This article covers configuring and operating the Neo4j system service. It assumes that your system has `systemd`, which is the case for most Linux distributions. 

[NOTE]
.Setting the number of open files.
====
For instructions on how to set the number of concurrent files that a user can have open, see xref:installation/linux/tarball.adoc#linux-open-files[Setting the number of open files].
====


[[linux-service-config]]
== Configuration

Configuration is stored in _/etc/neo4j/neo4j.conf_.
See xref:configuration/file-locations.adoc[File locations] for a complete catalog of where files are found for the various packages.

Before starting up the database for the first time, it is recommended to use the `set-initial-password` command of `neo4j-admin` to define the password for the native user `neo4j`.

If the password is not set explicitly using this method, it will be set to the default password `neo4j`.
In that case, you will be prompted to change the default password at first login.

For more information, see xref:configuration/set-initial-password.adoc[].

[[linux-service-control]]
== Controlling the service

System services are controlled with the `systemctl` command.
It accepts a number of commands:

[source, shell]
----
systemctl {start|stop|restart} neo4j
----

Service customizations can be placed in a service override file.
To edit your specific options, do the following command which will open up an editor of the appropriate file:

[source, shell]
----
systemctl edit neo4j
----

Then place any customizations under a `[Service]` section.
The following example lists default values that may be interesting to change for some users:

[source]
----
[Service]
# The user and group which the service runs as.
User=neo4j
Group=neo4j
# If it takes longer than this then the shutdown is considered to have failed.
# This may need to be increased if the system serves long-running transactions.
TimeoutSec=120
----

You can print the effective service, including possible overrides, with:

[source, shell]
----
systemctl cat neo4j
----

Remember to restart neo4j if you change any settings.

[source, shell]
----
systemctl restart neo4j
----


[[linux-service-log]]
== Log

The neo4j log is written to `journald` which can be viewed using the `journalctl` command:

[source, shell]
----
journalctl -e -u neo4j
----

`journald` automatically rotates the log after a certain time and by default it commonly does not persist across reboots.
Please see `man journald.conf` for further details.

== Uninstall Neo4j

Follow these steps to uninstall Neo4j:

. (Optional) Create a xref:/backup-restore/index.adoc[backup] to avoid losing your data.
. Uninstall Neo4j:
+
[source, shell]
---
sudo apt remove neo4j
---