[[installation-linux-tarball]]
= Linux tarball installation
:description: This section describes how to install Neo4j on Linux from a tarball, and run it as a console application or service. 

[[unix-console]]
== Unix console application

. If it is not already installed, get link:http://openjdk.java.net/[OpenJDK 11] or link:http://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle Java 11].
. Download the latest release from {neo4j-download-center-uri}[Neo4j Download Center].
+
Select the appropriate tar.gz distribution for your platform.
. Make sure to download Neo4j from {neo4j-download-center-uri}[Neo4j Download Center] and always check that the SHA hash of the downloaded file is correct:
.. To find the correct SHA hash, go to Neo4j Download Center and click on `SHA-256` which will be located below your downloaded file.
.. Using the appropriate commands for your platform, display the `SHA-256` hash for the file that you downloaded.
.. Ensure that the two are identical.
. Extract the contents of the archive, using `tar -xf <filename>`
+
Refer to the top-level extracted directory as: +NEO4J_HOME+
. Change directory to: `$NEO4J_HOME`
+
Run `./bin/neo4j console`
. Stop the server by typing `Ctrl-C` in the console.


[[installation-linux-tarball-service]]
== Linux service

If you want to run Neo4j as a system service, you can install either the xref:installation/linux/debian.adoc[Debian] or xref:installation/linux/rpm.adoc[RPM] package.

For more information on configuring and operating the Neo4j system service, see xref:installation/linux/systemd.adoc[Neo4j system service].


include::partial$/installation/linux/linux-open-files.adoc[leveloffset=+1]
