:description: This section describes how to install Neo4j on Linux from a tarball, and run it as a console application or service.
[[installation-linux-tarball]]
= Linux executable (.tar)

Before you install Neo4j on Linux from a tarball and run it as a console application or a service, check xref:installation/requirements.adoc[System Requirements] to see if your setup is suitable.

[[unix-console]]
== Install Neo4j from a tarball

. If it is not already installed, get link:https://openjdk.java.net/[OpenJDK 11] or link:https://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle Java 11].
. Download the latest Neo4j tarball from https://neo4j.com/download-center/[Neo4j Download Center] and unpack it:
+
[source, shell, subs="attributes"]
----
tar zxf neo4j-enterprise-{neo4j-version-exact}-unix.tar.gz
----
. Move the extracted files to your server's _/opt_ directory and create a symlink to it:
+
[source, shell, subs="attributes"]
----
mv neo4j-enterprise-{neo4j-version-exact} /opt/
ln -s /opt/neo4j-enterprise-{neo4j-version-exact} /opt/neo4j
----
. Create a `neo4j` user and group:
+
[source, shell]
----
groupadd neo4j
useradd -g neo4j neo4j -s /bin/bash
----
. Give the directory the correct ownership using one of the options:

* *Ubuntu*
+
[source, shell, subs="attributes"]
----
chown -R neo4j:adm /opt/neo4j-enterprise-{neo4j-version-exact}
----
* *RedHat*
+
[source, shell, subs="attributes"]
----
chown -R neo4j /opt/neo4j-enterprise-{neo4j-version-exact}
----
. Before starting up the database for the first time, it is recommended to use the `set-initial-password` command of `neo4j-admin` to define the password for the native user `neo4j`.
+
If the password is not set explicitly using this method, it will be set to the default password `neo4j`.
In that case, you will be prompted to change the default password at first login. +
For more information, see xref:configuration/set-initial-password.adoc[].
. Start Neo4j:
.. To run Neo4j as a console application, use: `<NEO4J_HOME>/bin/neo4j console`.
.. To run Neo4j in a background process, use: `<NEO4J_HOME>/bin/neo4j start`.
. Open  http://localhost:7474 in your web browser.
. Connect using the username `neo4j` with your password or with the default password `neo4j`.
In the latter case you will be prompted to change the password.
. Stop the server by typing `Ctrl-C` in the console.


[[linux-tarball-start-automatically]]
== Configure Neo4j to start automatically on system boot

You can create a Neo4j service and configure it to start automatically on system boot.

. Create the file _/lib/systemd/system/neo4j.service_ with the following contents:
+
[source, shell]
----
[Unit]
Description=Neo4j Graph Database
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=/opt/neo4j/bin/neo4j console
Restart=on-abnormal
User=neo4j
Group=neo4j
Environment="NEO4J_CONF=/opt/neo4j/conf" "NEO4J_HOME=/opt/neo4j"
LimitNOFILE=60000
TimeoutSec=120

[Install]
WantedBy=multi-user.target
----

. Reload systemctl to pick up the new service file:
+
[source, shell]
----
systemctl daemon-reload
----

. Configure Neo4j to start at boot time:
+
[source, shell]
----
systemctl enable neo4j
----
. Before starting up the database for the first time, it is recommended to use the `set-initial-password` command of `neo4j-admin` to define the password for the native user `neo4j`.
+
If the password is not set explicitly using this method, it will be set to the default password `neo4j`.
In that case, you will be prompted to change the default password at first login. +
For more information, see xref:configuration/set-initial-password.adoc[].
. Start Neo4j:
+
[source, shell]
----
systemctl start neo4j
----
. Check the status of the newly created service:
+
[source, shell]
----
systemctl status neo4j
----
. Reboot the system (if desired) to verify that Neo4j restarts on boot:
+
[source, shell]
----
reboot
----

For more information on operating the Neo4j system service, see xref:installation/linux/systemd.adoc[Neo4j system service].

include::partial$/installation/linux/linux-open-files.adoc[leveloffset=+1]

== Uninstall Neo4j

Follow these steps to uninstall Neo4j on Linux:

. (Optional) Create a xref:/backup-restore/index.adoc[backup] to avoid losing your data.
. Stop all Neo4j running services:
+
[source, shell]
---
sudo systemctl stop neo4j
sudo systemctl disable neo4j
---
. Delete _NEO4J_HOME_ and the file _/lib/systemd/system/neo4j.service_:
+
[source, shell]
---
rm /lib/systemd/system/neo4j.service
rm -rf NEO4J_HOME
---