:description: How to install Neo4j on Linux from a tarball, and run it as a console application or service.
[[installation-linux-tarball]]
= Linux executable (.tar)

Before you install Neo4j on Linux from a tarball and run it as a console application or a service, check xref:installation/requirements.adoc[System Requirements] to see if your setup is suitable.

[[unix-console]]
== Install Neo4j from a tarball

. If it is not already installed, get link:https://openjdk.java.net/[OpenJDK 21] or link:https://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle Java 21].
. Download the latest Neo4j tarball from link:{neo4j-download-center-uri}/?gdb-selfmanaged[Neo4j Deployment Center] and unpack it:
+
[source, shell, subs="attributes"]
----
tar zxf neo4j-enterprise-{neo4j-version-exact}-unix.tar.gz
----
. Move the extracted files to your server's _/opt_ directory and create a symlink to it:
+
[source, shell, subs="attributes"]
----
mv neo4j-enterprise-{neo4j-version-exact} /opt/
ln -s /opt/neo4j-enterprise-{neo4j-version-exact} /opt/neo4j
----
. Create a `neo4j` user and group:
+
[source, shell]
----
groupadd neo4j
useradd -g neo4j neo4j -s /bin/bash
----
. Give the directory the correct ownership using one of the options:

* *Ubuntu*
+
[source, shell, subs="attributes"]
----
chown -R neo4j:adm /opt/neo4j-enterprise-{neo4j-version-exact}
----
* *RedHat*
+
[source, shell, subs="attributes"]
----
chown -R neo4j /opt/neo4j-enterprise-{neo4j-version-exact}
----
. xref:configuration/file-locations.adoc#file-locations-file-locations[Change the default locations] of the _data_, _conf_, _certificates_, _licenses_, and _plugins_ (if you plan to use custom plugins) directories by setting the environment variable `NEO4J_CONF` and the respective xref:configuration/configuration-settings.adoc#_server_directories_settings[`server.directories.*`] settings to point to the desired locations.
+
[NOTE]
====
Storing your Neo4j files outside `NEO4J_HOME` will simplify the upgrade process later because you will be able to replace the DBMS binaries without affecting the configuration and state.
Otherwise, these Neo4j files will remain in the old installation folder and may be accidentally overwritten during an upgrade or deleted during a subsequent uninstall.
====
. Accept either the commercial or the evaluation license agreement before running the Neo4j Enterprise Edition.
If you are using Community Edition, you can skip this step.
* Use one of the following options to accept the commercial license agreement.
See the link:https://neo4j.com/terms/licensing/[Neo4j licensing] page for details on the available agreements.
+
** Set the environment variable `NEO4J_ACCEPT_LICENSE_AGREEMENT=yes`.
** Run `<NEO4J_HOME>/bin/neo4j-admin server license --accept-commercial`
* Use one of the following options to accept the link:https://neo4j.com/terms/enterprise_us/[Neo4j Evaluation Agreement for Neo4j Software].
+
** Set the environment variable `NEO4J_ACCEPT_LICENSE_AGREEMENT=eval`.
** Run `<NEO4J_HOME>/bin/neo4j-admin server license --accept-evaluation`.
. Before starting up the database for the first time, it is recommended to use the `set-initial-password` command of `neo4j-admin` to define the password for the native user `neo4j`.
+
If the password is not set explicitly using this method, it will be set to the default password `neo4j`.
In that case, you will be prompted to change the default password at first login. +
For more information, see xref:configuration/set-initial-password.adoc[].
. Start Neo4j:
* To run Neo4j as a console application, use: `<NEO4J_HOME>/bin/neo4j console`.
* To run Neo4j in a background process, use: `<NEO4J_HOME>/bin/neo4j start`.
. Open  _\http://localhost:7474/_ in your web browser.
. Connect using the username `neo4j` with your password or the default password `neo4j`.
You will then be prompted to change the password.
. Stop the server by typing `Ctrl-C` in the console.


[[linux-tarball-start-automatically]]
== Configure Neo4j to start automatically on system boot

You can create a Neo4j service and configure it to start automatically on system boot.

. Create the file _/lib/systemd/system/neo4j.service_ with the following contents:
+
[source, shell]
----
[Unit]
Description=Neo4j Graph Database
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=/opt/neo4j/bin/neo4j console
Restart=on-abnormal
User=neo4j
Group=neo4j
Environment="NEO4J_CONF=/opt/neo4j/conf" "NEO4J_HOME=/opt/neo4j"
LimitNOFILE=60000
TimeoutSec=120

[Install]
WantedBy=multi-user.target
----

. Reload systemctl to pick up the new service file:
+
[source, shell]
----
systemctl daemon-reload
----

. Configure Neo4j to start at boot time:
+
[source, shell]
----
systemctl enable neo4j
----

. Before starting up the database for the first time, it is recommended to use the `set-initial-password` command of `neo4j-admin` to define the password for the native user `neo4j`.
+
If the password is not set explicitly using this method, it will be set to the default password `neo4j`.
In that case, you will be prompted to change the default password at first login. +
For more information, see xref:configuration/set-initial-password.adoc[].

. Start Neo4j:
+
[source, shell]
----
systemctl start neo4j
----
. Check the status of the newly created service:
+
[source, shell]
----
systemctl status neo4j
----
. Reboot the system (if desired) to verify that Neo4j restarts on boot:
+
[source, shell]
----
reboot
----

For more information on operating the Neo4j system service, see xref:installation/linux/systemd.adoc[Neo4j system service].

[[linux-open-files]]
== Setting the number of open files

Linux platforms impose an upper limit on the number of concurrently open files per user and session.
To check your limit for the current session, run the command `ulimit -n`.
The default value is 1024.

[source, shell]
----
ulimit -n
----

However, if you experience exceptions on `Too many open files` or `Could not stat() directory`, you have to increase the limit to 40000 or more, depending on your usage patterns.
This is especially true when many indexes are used, or the server installation sees too many open network connections or sockets.

A quick solution is the command `ulimit -n <the-new-limit>`, but it will set a new limit only for the root user and will affect only the current session.
If you want to set the value system-wide, follow the instructions for your platform.

The following steps set the open file descriptor limit to 60000 for the user _neo4j_ under Ubuntu 16.04 LTS, Debian 8, CentOS 7, or later versions.

=== Running Neo4j as a service

. Open the _neo4j.service_ file with root privileges.
+
[source, shell]
----
sudo systemctl edit neo4j.service
----

. Append the following to the `[Service]` section, created in <<linux-tarball-start-automatically>>:
+
[source]
----
[Service]
...
LimitNOFILE=60000
----

=== Running Neo4j as an interactive user (e.g., for testing purposes)

. Open the _user.conf_ file with root privileges in a text editor.
This example uses Vim:
+
[source, shell]
----
sudo vi /etc/systemd/user.conf
----

. Uncomment and define the value of `DefaultLimitNOFILE`, found in the `[Manager]` section.
+
[source]
----
[Manager]
...
DefaultLimitNOFILE=60000
----

. Open the _/etc/security/limits.conf_ file.
+
[source, shell]
----
sudo vi /etc/security/limits.conf
----

. Define the following values:
+
[source]
----
neo4j	soft	nofile	60000
neo4j	hard	nofile	60000
----

. Reload the `systemd` settings.
+
[source, shell]
----
sudo systemctl daemon-reload
----

. Reboot your machine.

== Uninstall Neo4j

Follow these steps to uninstall Neo4j on Linux:

. (Optional) Create a xref:/backup-restore/index.adoc[backup] to avoid losing your data.
. Stop all Neo4j running services:
+
[source, shell]
---
sudo systemctl stop neo4j
sudo systemctl disable neo4j
---
. Delete _NEO4J_HOME_ and the file _/lib/systemd/system/neo4j.service_:
+
[source, shell]
---
rm /lib/systemd/system/neo4j.service
rm -rf NEO4J_HOME
---