:description: This section describes the administration and operation of Composite databases.
[role=enterprise-edition]
[[composite-databases-administration]]
= Managing Composite databases

Composite databases are managed using administrative commands.
They are created with the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/databases#administration-databases-create-composite-database[`CREATE COMPOSITE DATABASE`^] command.

== Create a Composite database

====
[source, cypher]
----
CREATE COMPOSITE DATABASE cineasts
----
====

Constituent graphs are added with the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/aliases#alias-management-create-database-alias[`CREATE ALIAS`^] administrative command, for example:

== Create an alias on a Composite database

====
[source, cypher]
----
CREATE ALIAS `cineasts`.`latest`
  FOR DATABASE movies2022
----
====

[NOTE]
====
`.` is used as a separating character between the namespace and database name in aliases.
It is therefore recommended to avoid `.` characters in database and composite database names.
If '.' is needed in either name, the name must be surrounded by backticks, i.e. `composite.`db.name``.
Backticks may be added regardless of whether the name contains special characters or not, so it is good practice to always backtick both names, i.e. `pass:[`composite`.`db.name`]`.
For more details on escaping special characters, see link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/administration/aliases/#alias-management-escaping[Alias names and escaping].
====

Aliases can also be created for databases on other DBMSs:

== Create an alias for a remote database on a Composite database

====
[source, cypher]
----
CREATE ALIAS `cineasts`.`upcoming`
  FOR DATABASE upcoming
  AT 'neo4j+s://other.dbms.com'
  USER $user
  PASSWORD $secretpassword
----
====

The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/databases#administration-databases-show-databases[`SHOW DATABASE`^] administrative command includes Composite databases.

Their `type` is reported as `"composite"`, and the `constituents` column lists the names of the aliases contained.

== Show a Composite database

====
[source, cypher]
----
SHOW DATABASE cineasts YIELD name, type, constituents
----
----
+---------------------------------------------------------------------+
| name       | type        | constituents                             |
+---------------------------------------------------------------------+
| "cineasts" | "composite" | ["cineasts.latest", "cineasts.upcoming"] |
+---------------------------------------------------------------------+

----
====


The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/aliases#alias-management-show-alias[`SHOW ALIASES FOR DATABASE`^] administrative command can be used to inspect aliases on Composite databases in further detail.

== Show Composite database aliases

====
[source, cypher]
----
SHOW ALIASES FOR DATABASE
----
----
+----------------------------------------------------------------------------------------+
| name                | database     | location | url                        | user      |
+----------------------------------------------------------------------------------------+
| "cineasts.latest"   | "movies2022" | "local"  | NULL                       | NULL      |
| "cineasts.upcoming" | "upcoming"   | "remote" | "neo4j+s://other.dbms.com" | "cineast" |
+----------------------------------------------------------------------------------------+
----
====

For a full description of the administrative commands for managing Composite databases, see link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/databases[Cypher Manual -> Database management^].


[[composite-databases-connecting]]
== Connect to drivers and applications

Drivers and client applications connect to Composite databases just like standard databases.
For more information, see the respective link:{neo4j-docs-base-uri}/[Neo4j Driver manual^].
