[role=enterprise-edition]
[[composite-databases-further-considerations]]
= Further considerations
:description: This section presents considerations about composite databases that developers and administrators must be aware of.

== Sharding an existing database
An existing database can be sharded with the help of the `neo4j-admin database copy` command.
See xref:composite-databases/sharding-with-copy.adoc[Sharding data with the copy command] for an example.

== Composite database transactions

Composite databases do not support `WRITE` transactions that span across multiple graphs.
To avoid common mistakes that may lead to data corruption, `WRITE` operations on more than one graph within the same transaction, are not allowed.
Transactions with queries that read from multiple graphs, or read from multiple graphs and write to a single graph, are allowed.

== Neo4j embedded

Composite databases are not available when Neo4j is used as an embedded database in Java applications.
Composite databases can be used only in a typical client/server mode, when users connect to a Neo4j DBMS from their client application or tool, via Bolt or HTTP protocol.

== Cypher runtime

When a query is submitted to a composite database, different parts of the query may run using different runtimes.
Clauses or expressions in scopes where no graph has been specified run using the _slotted_ runtime.
Parts of the query directed to different constituent graphs, will be run using the default runtime for that graph, or respect the submitted link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/query-tuning/query-options/#cypher-runtime[Cypher query options] if specified.
