[role=enterprise-edition]
[[composite-databases-introduction]]
= Introduction
:description: An introduction to composite databases. 


[[composite-databases-overview]]
== Overview

As of Neo4j 5, Fabric has been replaced by composite databases, a functionality which allows queries that access multiple graphs at once.
This is a function that enables:

* *Data Federation*: the ability to access data available in distributed sources in the form of *disjointed graphs*.
* *Data Sharding*: the ability to access data available in distributed sources in the form of a *common graph partitioned on multiple databases*.

[[composite-databases-concepts]]
== Concepts

Composite databases don't store any data on their own, but rather give access to the graphs found on other databases.
These graphs are added to the composite database by means of database aliases.

A Neo4j DBMS can have multiple composite databases, and they can be created both in single-instance deployments, and in cluster deployments.

Composite databases are managed using administrative commands.
They are created with the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/databases#administration-databases-create-composite-database[`CREATE COMPOSITE DATABASE`] command.

.Creating a composite database
====
[source, cypher]
----
CREATE COMPOSITE DATABASE cineasts
----
====

Constituent graphs are added with the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/aliases#alias-management-create-database-alias[`CREATE ALIAS`] administrative command, for example:

.Creating an alias on a composite database
====
[source, cypher]
----
CREATE ALIAS cineasts.latest
  FOR DATABASE movies2022
----
====

Aliases can also be created for databases on other DBMSs:

.Creating an alias for a remote database on a composite database
====
[source, cypher]
----
CREATE ALIAS cineasts.upcoming
  FOR DATABASE upcoming
  AT 'neo4j+s://other.dbms.com'
  USER $user
  PASSWORD $password
----
====

The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/databases#administration-databases-show-databases[`SHOW DATABASE`] administrative command includes composite databases.

Their `type` is reported as `"composite"`, and the `constituents` column lists the names of the aliases contained.

.Showing a composite database
====
[source, cypher]
----
SHOW DATABASE cineasts YIELD name, type, constituents
----
----
+---------------------------------------------------------------------+
| name       | type        | constituents                             |
+---------------------------------------------------------------------+
| "cineasts" | "composite" | ["cineasts.latest", "cineasts.upcoming"] |
+---------------------------------------------------------------------+

----
====


The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/aliases#alias-management-show-alias[`SHOW ALIASES FOR DATABASE`] administrative command can be used to inspect aliases on composite databases in further detail.

.Showing composite database aliases
====
[source, cypher]
----
SHOW ALIASES FOR DATABASE
----
----
+----------------------------------------------------------------------------------------+
| name                | database     | location | url                        | user      |
+----------------------------------------------------------------------------------------+
| "cineasts.latest"   | "movies2022" | "local"  | NULL                       | NULL      |
| "cineasts.upcoming" | "upcoming"   | "remote" | "neo4j+s://other.dbms.com" | "cineast" |
+----------------------------------------------------------------------------------------+
----
====

For a full description of the administrative commands for managing composite databases, see link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/databases[Cypher Manual -> Database management].
