:description: This section describes the administration and operation of composite databases.
[role=enterprise-edition]
[[composite-databases]]
= Managing composite databases

Composite databases are managed using administrative commands.
They are created with the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/databases#administration-databases-create-composite-database[`CREATE COMPOSITE DATABASE`^] command.

== Create a composite database

====
[source, cypher]
----
CREATE COMPOSITE DATABASE cineasts
----
====

Constituent graphs are added with the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/aliases#alias-management-create-database-alias[`CREATE ALIAS`^] administrative command, for example:

== Create an alias on a composite database

====
[source, cypher]
----
CREATE ALIAS cineasts.latest
  FOR DATABASE movies2022
----
====

Aliases can also be created for databases on other DBMSs:

== Create an alias for a remote database on a composite database

====
[source, cypher]
----
CREATE ALIAS cineasts.upcoming
  FOR DATABASE upcoming
  AT 'neo4j+s://other.dbms.com'
  USER $user
  PASSWORD $secretpassword
----
====

The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/databases#administration-databases-show-databases[`SHOW DATABASE`^] administrative command includes composite databases.

Their `type` is reported as `"composite"`, and the `constituents` column lists the names of the aliases contained.

== Show a composite database

====
[source, cypher]
----
SHOW DATABASE cineasts YIELD name, type, constituents
----
----
+---------------------------------------------------------------------+
| name       | type        | constituents                             |
+---------------------------------------------------------------------+
| "cineasts" | "composite" | ["cineasts.latest", "cineasts.upcoming"] |
+---------------------------------------------------------------------+

----
====


The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/aliases#alias-management-show-alias[`SHOW ALIASES FOR DATABASE`^] administrative command can be used to inspect aliases on composite databases in further detail.

== Show composite database aliases

====
[source, cypher]
----
SHOW ALIASES FOR DATABASE
----
----
+----------------------------------------------------------------------------------------+
| name                | database     | location | url                        | user      |
+----------------------------------------------------------------------------------------+
| "cineasts.latest"   | "movies2022" | "local"  | NULL                       | NULL      |
| "cineasts.upcoming" | "upcoming"   | "remote" | "neo4j+s://other.dbms.com" | "cineast" |
+----------------------------------------------------------------------------------------+
----
====

For a full description of the administrative commands for managing composite databases, see link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/databases[Cypher Manual -> Database management^].

== Shard an existing database
An existing database can be sharded with the help of the `neo4j-admin database copy` command.
See xref:composite-databases/sharding-with-copy.adoc[Sharding data with the copy command^] for an example.

[[composite-databases-connecting]]
== Connect to drivers and applications

Drivers and client applications connect to composite databases just like standard databases.
For more information, see the respective link:{neo4j-docs-base-uri}/[Neo4j Driver manual^].
