:description: This section describes how to move from a single `system` primary deployment to a cluster.
[role=enterprise-edition]
[[single-to-cluster]]
= Move from a single `system` primary to a cluster deployment

This is an example of how to move from a deployment with a single `system` primary to a cluster with multiple `system` primaries.

== Guide
. Ensure that the single `system` primary server is stopped. 
. Edit the configuration file on the single `system` primary server to include the discovery endpoints of itself and the servers that will form the cluster. This is the `dbms.cluster.discovery.endpoints` configuration setting in `neo4j.conf`. 
. For each of the other servers that will form the cluster configure them as required. For information on important cluster settings see xref:clustering/setup/deploy.adoc[Deploy a basic cluster].
. On the single `system` primary server dump the `system` database using the `neo4j-admin database dump` command.
. For each other server that will form the cluster use the `neo4j-admin database load` command to load the system database from the single `system` primary server.
. Now start all servers.
. Using `SHOW SERVERS` verify that all servers except the server from the single `system` primary deployment are in a `Free` state. 
. Using `SHOW DATABASES` verify that all user databases are still running on the server from the single `system` primary deployment.
. Enable each `Free` server using `ENABLE SERVER`.
. You can then scale up user databases using `ALTER DATABASE`.
