[[security-checklist]]
= Security checklist
:description: This section provides a summary of recommendations regarding security in Neo4j. 

Below is a simple checklist highlighting the specific areas within Neo4j that may need some extra attention in order to ensure the appropriate level of security for your application.

. Deploy Neo4j on safe servers in safe networks:
.. Use subnets and firewalls.
.. Only open up for the necessary ports.
For a list of relevant ports see xref:configuration/ports.adoc[Ports].
+
In particular, ensure that there is no external access to the port specified by the setting `xref:reference/configuration-settings.adoc#config_dbms.backup.address[dbms.backup.address]`.
Failing to protect this port may leave a security hole open by which an unauthorized user can make a copy of the database onto a different machine.
. Protect data-at-rest:
.. Use volume encryption (e.g. Bitlocker).
.. Manage access to database dumps (refer to xref:tools/dump-load.adoc[Dump and load databases]) and backups (refer to xref:backup/performing.adoc[Perform a backup]).
.. Manage access to data files and transaction logs by ensuring the correct file permissions on the Neo4j files.
Refer to xref:configuration/file-locations.adoc#file-locations-permissions[File permissions] for instructions on permission levels.
. Protect data-in-transit:
.. For remote access to the Neo4j database, only open up for encrypted Bolt or HTTPS.
.. Use SSL certificates issued from a trusted Certificate Authority.
... For configuring your Neo4j installation to use encrypted communication, refer to xref:security/ssl-framework.adoc[SSL framework].
... If using Causal Clustering, configure and use encryption for intra-cluster communication.
For details, see xref:clustering/intra-cluster-encryption.adoc[Intra-cluster encryption].
... If using Causal Clustering, configure and use encryption for backups.
This ensures that only servers with the specified SSL policy and SSL certificates will be able to access the server and perform the backup.
... For configuring your Bolt and/or HTTPS connectors, refer to xref:configuration/connectors.adoc[Configure connectors].
... If using LDAP, configure your LDAP system with encryption via StartTLS; see xref:authentication-authorization/ldap-integration.adoc#ldap-encrypted-starttls[Use LDAP with encryption via StartTLS].
. Be on top of the security for custom extensions:
.. Validate any custom code that you deploy (procedures and unmanaged extensions) and ensure that they do not expose any parts of the product or data unintentionally.
.. Survey the settings `xref:reference/configuration-settings.adoc#config_dbms.security.procedures.unrestricted[dbms.security.procedures.unrestricted]` and `xref:reference/configuration-settings.adoc#config_dbms.security.procedures.whitelist[dbms.security.procedures.whitelist]` to ensure that they exclusively contain intentionally exposed extensions.
. Ensure the correct file permissions on the Neo4j files.
. Protect against the execution of unauthorized extensions by restricting access to the _bin_, _lib_, and _plugins_ directories.
Only the operating system user that Neo4j runs as should have permissions to those files.
Refer to xref:configuration/file-locations.adoc#file-locations-permissions[File permissions] for instructions on permission levels.
. If `LOAD CSV` is enabled, ensure that it does not allow unauthorized users to import data.
How to configure `LOAD CSV` is described in link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/clauses/load-csv[Cypher Manual -> `LOAD CSV`].
. Do not turn off Neo4j authentication.
Refer to xref:authentication-authorization/enable.adoc[Configuration] for details on this setting.
. Survey your _xref:configuration/file-locations.adoc[neo4j.conf]_ file for ports relating to deprecated functions such as remote JMX (controlled by the parameter setting `dbms.jvm.additional=-Dcom.sun.management.jmxremote.port=3637`).
. Review xref:security/browser.adoc[Browser credentials handling] to determine whether the default credentials handling in Neo4j Browser complies with your security regulations.
  Follow the instructions to configure it if necessary.
. Use the latest patch version of Neo4j.
