[[security-checklist]]
= Security checklist
:description: This page provides a summary of recommendations regarding post-deploy security in Neo4j.

The following checklist highlights the specific areas within Neo4j that may need extra attention to ensure the appropriate level of security for your application after Neo4j is deployed.

. Deploy Neo4j on safe servers in secure networks:
.. Use subnets and firewalls to segment the network.
+
image:flat-vs-segmented-network.svg[title="An example of flat vs. segmented network", role="middle"]

.. Open only the ports that you need.
For a list of relevant ports, see xref:configuration/ports.adoc[Ports].
+
In particular, ensure that there is no external access to the port specified by the setting xref:configuration/configuration-settings.adoc#config_server.backup.listen_address[`server.backup.listen_address`].
Failing to protect this port may open a security hole by which an unauthorized user can make a copy of the database onto a different machine.
. Protect data-at-rest:
.. Use volume encryption (e.g., Bitlocker).
.. Manage access to database dumps and backups.
Refer to xref:backup-restore/offline-backup.adoc[Back up an offline database] and backups xref:backup-restore/online-backup.adoc[Back up an online database] for more information.
.. Manage access to configuration files, data files, and transaction logs by ensuring the correct file permissions on the Neo4j files.
Refer to xref:configuration/file-locations.adoc[Default file locations] for instructions on permission levels.
. Protect data-in-transit:
.. For remote access to the Neo4j database, only use encrypted Bolt or HTTPS.
.. Use SSL certificates issued from a trusted Certificate Authority.
.. For configuring your Neo4j installation to use encrypted communication, refer to xref:security/ssl-framework.adoc[SSL framework].
.. If using clustering, configure and use encryption for intra-cluster communication.
For details, see xref:clustering/setup/encryption.adoc[Intra-cluster encryption].
.. If using clustering, configure and use encryption for backups.
This ensures that only servers with the specified SSL policy and SSL certificates can access the server and perform the backup.
.. For configuring your Bolt and HTTPS connectors, refer to xref:configuration/connectors.adoc[Configure network connectors].
.. If using LDAP, configure your LDAP system with encryption via StartTLS.
For more information, see xref:authentication-authorization/ldap-integration.adoc#auth-ldap-encrypted-starttls[Use LDAP with encryption via StartTLS].
. Be on top of the security for custom extensions:
.. Validate any custom code you deploy (procedures and unmanaged extensions) and ensure that they do not unintentionally expose any parts of the product or data.
.. Survey the settings `xref:configuration/configuration-settings.adoc#config_dbms.security.procedures.unrestricted[dbms.security.procedures.unrestricted]` and `xref:configuration/configuration-settings.adoc#config_dbms.security.procedures.allowlist[dbms.security.procedures.allowlist]` to ensure that they exclusively contain intentionally exposed extensions.
. Make sure you have the xref:configuration/file-locations.adoc[Default file locations] on the Neo4j files.
. Protect against the execution of unauthorized extensions by restricting access to the _bin_, _lib_, and _plugins_ directories.
Only the operating system user that Neo4j runs as should have permissions to those files.
Refer to xref:configuration/file-locations.adoc[Default file locations] for instructions on permission levels.
. With `LOAD CSV` enabled, ensure that it does not allow unauthorized users to import data.
How to configure `LOAD CSV` is described in link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/load-csv[Cypher Manual -> `LOAD CSV`].
. Use Neo4j authentication.
The setting `xref:configuration/configuration-settings.adoc#config_dbms.security.auth_enabled[dbms.security.auth_enabled]` controls native authentication.
The default value is `true`.
. Survey your xref:configuration/neo4j-conf.adoc#neo4j-conf-JVM[JVM-specific configuration settings] in the _neo4j.conf_ file for ports relating to deprecated functions, such as remote JMX (controlled by the parameter setting `dbms.jvm.additional=-Dcom.sun.management.jmxremote.port=3637`).
. Review xref:security/browser.adoc[Browser credentials handling] to determine whether the default credentials handling in Neo4j Browser complies with your security regulations.
Follow the instructions to configure it if necessary.
. Use the latest patch version of Neo4j and set up a process to update it when security advisories are published.
