[[securing-extensions]]
= Securing extensions
:description: This page describes how to use allow listing to ensure the security of custom-written additions in Neo4j. 

Neo4j can be extended by writing custom code which can be invoked directly from Cypher, as described in link:{neo4j-docs-base-uri}/java-reference/{page-version}/extending-neo4j/procedures#extending-neo4j-procedures[Java Reference -> User-defined procedures] and link:{neo4j-docs-base-uri}/java-reference/{page-version}/extending-neo4j/functions#extending-neo4j-functions[Java Reference -> User-defined functions].
This page describes how to ensure the security of these additions.


[[allow-listing]]
== Allow listing

Allow listing can be used to allow the loading of only a few extensions from a larger library.

The configuration setting xref:reference/configuration-settings.adoc#config_dbms.security.procedures.allowlist[`dbms.security.procedures.allowlist`] is used to name certain procedures that should be available from a library.
It defines a comma-separated list of procedures that are to be loaded.
The list may contain both fully qualified procedure names, and partial names with the wildcard `*`.

.Allow listing
====

In this example we wish to allow the use of the method `apoc.load.json` as well as all the methods under `apoc.coll`.
We do not want to make available any additional extensions from the `apoc` library, other than the ones matching these criteria.

[source, properties]
----
# Example allow listing
dbms.security.procedures.allowlist=apoc.coll.*,apoc.load.*
----
====

There are a few things that should be noted about `dbms.security.procedures.allowlist`:

* If using this setting, no extensions other than those listed will be loaded.
  In particular, if it is set to the empty string, no extensions will be loaded.
* The default of the setting is `*`.
  This means that if you do not explicitly give it a value (or no value), all libraries in the xref:configuration/file-locations.adoc[_plugins_] directory will be loaded.
