[[securing-extensions]]
= Securing extensions
:description: This page describes how to use allow listing and unrestricting to ensure the security of custom-written additions in Neo4j.

Neo4j can be extended by writing custom code which can be invoked directly from Cypher, as described in link:{neo4j-docs-base-uri}/java-reference/{page-version}/extending-neo4j/procedures[Java Reference -> User-defined procedures] and link:{neo4j-docs-base-uri}/java-reference/{page-version}/extending-neo4j/functions[Java Reference -> User-defined functions].
This page describes how to ensure the security of these additions.


[[allow-listing]]
== Allow listing

Allow listing can be used to allow the loading of only a few extensions from a larger library.
It is recommended to load extensions using the principle of least privilege.
This principle dictates that you only load the procedures and functions necessary to execute your queries.

The configuration setting xref:configuration/configuration-settings.adoc#config_dbms.security.procedures.allowlist[`dbms.security.procedures.allowlist`] is used to name certain procedures and functions that should be available from a library.
It defines a comma-separated list of procedures and functions that are to be loaded.
The list may contain both fully qualified procedure names, and partial names with the wildcard `*`.

.Allow listing
====

In this example, you need to allow the use of the method `apoc.load.json` as well as all the methods under `apoc.coll`.
You do not want any additional extensions from the `apoc` library to become available, other than the ones matching these criteria.

[source, properties]
----
# Example allow listing
dbms.security.procedures.allowlist=apoc.coll.*,apoc.load.json
----
====

There are a few things that should be noted about `dbms.security.procedures.allowlist`:

* If using this setting, no extensions other than those listed will be loaded.
  In particular, if it is set to the empty string, no extensions will be loaded.

[WARNING]
====
// tag::warnings[]
* The default of the setting is `*`.
  This means that if you do not explicitly give it a value (or no value), all libraries in the xref:configuration/file-locations.adoc[_plugins_] directory will be loaded.
// end::warnings[]
====

[[unrestricting]]
== Unrestricting

For security reasons, procedures and functions that use internal APIs are disabled by default.
In this case, it is also recommended to use the principle of least privilege and only unrestrict those procedures and functions which you are certain to use.

Procedures and functions can be unrestricted using the configuration setting xref:configuration/configuration-settings.adoc#config_dbms.security.procedures.unrestricted[`dbms.security.procedures.unrestricted`].
It defines a comma-separated list of procedures and functions that are to be unrestricted.
The list may contain both fully qualified procedure and function names, and partial names with the wildcard (`*`) expression.

.Unrestricting
====

In this example, you need to unrestict the use of the procedures `apoc.cypher.runFirstColumn` and `apoc.cypher.doIt`.

[source, properties]
----
# Example unrestricting
dbms.security.procedures.unrestricted=apoc.cypher.runFirstColumn,apoc.cypher.doIt
----
====
