[[ssl-framework]]
= SSL framework
:description: Describes SSL/TLS integration for securing communication channels in Neo4j. 

Neo4j supports the securing of communication channels using standard SSL/TLS technology.


[[ssl-introduction]]
== Introduction

The SSL support is enabled per communication channel and requires SSL certificates encoded in the `PEM` format.
The process is described in the following sections.

[[ssl-certificates]]
== Certificates

The instructions in this section assume that you have already acquired the required xref:security/ssl-framework.adoc#term-ssl-certificate[certificates].

All certificates must be in the `PEM` format, and they can be combined into one file.
The private key is also required to be in the `PEM` format.
Multi-host and wildcard certificates are supported.

[TIP]
====
Valid trusted certificates can be generated for free using non-profit CAs such as Let's Encrypt.
====

[[ssl-connectors]]
== Connectors

Before enabling SSL support, you must ensure the following connector configurations to avoid errors:

* Set `dbms.connector.https.enabled` to `true` when using HTTPS.
* Set `dbms.connector.bolt.tls_level` to `REQUIRED` or `OPTIONAL` when using Bolt. 

For more information on configuring connectors, see xref:configuration/connectors.adoc[Configure connectors].

[[ssl-configuration]]
== Configuration

The SSL policies are configured by assigning values to parameters of the following format:

`dbms.ssl.policy.<scope>.<setting-suffix>`

The `scope` is the name of the communication channel, and must be one of `bolt`, `https`, `cluster`, `backup` or `fabric`.

Each policy needs to be explicitly enabled by setting:

`dbms.ssl.policy.<scope>.enabled=true`


[[ssl-settings]]
=== Settings

The valid values for `setting-suffix` are described below.

[options="header"]
|===
| Setting suffix         | Description                                                                            | Default value
3+^.^| *Basic*
| `enabled`              | Setting this to `true` will enable this policy.                                        | `false`
| `base_directory`       | The base directory under which cryptographic objects are searched for by default.      | `certificates/<scope>`
| `private_key`          | The private key used for authenticating and securing this instance.                    | `private.key`
| `private_key_password` | The passphrase to decode the private key.
                           Only applicable for encrypted private keys.                                            |
| `public_certificate`   | A public certificate matching the private key signed by a Certificate Authority (CA).  | `public.crt`
| `trusted_dir`          | A directory populated with certificates of trusted parties.                            | `trusted/`
| `revoked_dir`          | A directory populated with certificate revocation lists (CRLs).                        | `revoked/`
3+^.^| *Advanced*
| `verify_hostname`      | Enabling this setting will turn on client-side hostname verification.
                           After the client has received the servers public certificate, it will compare the
                           address it used against the certificate Common Name (CN) and Subject Alternative
                           Names (SAN) fields.
                           If the address used doesn’t match those fields, the client will disconnect.            | `false`
| `ciphers`              | A comma-separated list of ciphers suits that will be allowed during cipher negotiation.
                           Valid values depend on the current JRE and SSL provider, see note below for examples.  | Java platform default allowed cipher suites
| `tls_versions`         | A comma-separated list of allowed TLS versions.                                        | `TLSv1.2`
| `client_auth`          | Whether or not clients must be authenticated.
                           Setting this to `REQUIRE` effectively enables mutual authentication for servers.
                           Available values given to this setting are `NONE`, `OPTIONAL`, or `REQUIRE`.           | `OPTIONAL` for `bolt` and `https` and `REQUIRE` for `cluster` and `backup`.
| `trust_all`            | Setting this to `true` will result in all clients and servers being trusted.
                           The content of the `trusted_dir` directory will be ignored.
                           Use of this is discouraged, since it will not offer security.
                           It is provided as a mean of debugging.                                                 | `false`
|===

[NOTE]
====
Ciphers supported by the Oracle JRE can be found here:
https://docs.oracle.com/en/java/javase/11/docs/specs/security/standard-names.html#jsse-cipher-suite-names
====

For security reasons, Neo4j will not attempt to automatically create any of these directories.
The creation of an SSL policy therefore requires the appropriate file system structure to be set up manually.
Note that the existence of the directories is mandatory, as well as the presence of the certificate file and the private key.
Ensure correct permissions are set on the private key, such that only the Neo4j user can read it.

[[ssl-bolt-example]]
.Enable Bolt SSL
====

In this example we will configure Bolt to use SSL/TLS.
As the simplest configuration possible, we will just enable it in _neo4j.conf_ and rely on the default values:

[source, properties]
----
dbms.ssl.policy.bolt.enabled=true
----

Then create the mandatory directories:

[source, shell]
----
$neo4j-home> mkdir certificates/bolt
$neo4j-home> mkdir certificates/bolt/trusted
$neo4j-home> mkdir certificates/bolt/revoked
----

Finally, place the files _private.key_ and _public.crt_ into the base directory:

[source, shell]
----
$neo4j-home> cp /path/to/certs/private.key certificates/bolt
$neo4j-home> cp /path/to/certs/public.crt certificates/bolt
----

The base directory should now show the following listings:

[source, shell]
----
$neo4j-home> ls certificates/bolt
-r-------- ... private.key
-rw-r--r-- ... public.crt
drwxr-xr-x ... revoked
drwxr-xr-x ... trusted
----
====


[[ssl-providers]]
== Choosing an SSL provider

The secure networking in Neo4j is provided through the Netty library, which supports both the native JDK SSL provider as well as Netty-supported OpenSSL derivatives.

Follow these steps to utilize OpenSSL:

. Install a suitable dependency into the `plugins/` folder of Neo4j.
  Dependencies can be downloaded from https://netty.io/wiki/forked-tomcat-native.html.
. Set `xref:reference/configuration-settings.adoc#config_dbms.netty.ssl.provider[dbms.netty.ssl.provider]=OPENSSL`.

[NOTE]
Using OpenSSL can significantly improve performance, especially for AES-GCM-cryptos, e.g. TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256.


[[ssl-terminology]]
== Terminology

The following terms are relevant to SSL support within Neo4j:

[.compact]
[[term-ssl-certificate-authority]]Certificate Authority (_CA_)::
A trusted entity that issues electronic documents that can verify the identity of a digital entity.
The term commonly refers to globally recognized CAs, but can also include internal CAs that are trusted inside of an organization.
The electronic documents are digital xref:security/ssl-framework.adoc#term-ssl-certificate[certificates].
They are an essential part of secure communication, and play an important part in the xref:security/ssl-framework.adoc#term-ssl-pki[Public Key Infrastructure].

[[term-ssl-certificate-revocation-list]]Certificate Revocation List (_CRL_)::
In the event of a certificate being compromised, that certificate can be revoked.
This is done by means of a list (located in one or several files) spelling out which certificates are revoked.
The CRL is always issued by the xref:security/ssl-framework.adoc#term-ssl-certificate-authority[CA] which issues the corresponding certificates.

[[term-ssl-cipher]]cipher::
An algorithm for performing encryption or decryption.
In the most general implementation of encryption of Neo4j communications, we make implicit use of ciphers that are included as part of the Java platform.
The configuration of the SSL framework also allows for the explicit declaration of allowed ciphers.

[[term-ssl-channel]]communication channel::
A means for communicating with the Neo4j database.
Available channels are:
* Bolt client traffic
* HTTPS client traffic
* intra-cluster communication
* backup traffic

[[term-ssl-cryptographic-objects]]cryptographic objects::
A term denoting the artifacts xref:security/ssl-framework.adoc#term-ssl-private-key[private keys], xref:security/ssl-framework.adoc#term-ssl-certificate[certificates] and xref:security/ssl-framework.adoc#term-ssl-certificate-revocation-list[CRLs].

[[term-ssl-configuration-parameters]]configuration parameters::
These are the parameters defined for a certain xref:security/ssl-framework.adoc#term-ssl-policy[ssl policy] in _neo4j.conf_.

[[term-ssl-certificate]]certificate::
SSL certificates are issued by a trusted xref:security/ssl-framework.adoc#term-ssl-certificate-authority[certificate authority (_CA_)].
The public key can be obtained and used by anyone to encrypt messages intended for a particular recipient.
The certificate is commonly stored in a file named _<file name>.crt_.
This is also referred to as the xref:security/ssl-framework.adoc#term-ssl-public-key[public key].

[[term-ssl-san]]SAN::
SAN is an acronym for _Subject Alternative Names_.
It is an extension to certificates that one can include optionally.
When presented with a certificate that includes SAN entries, it is recommended that the address of the host is checked against this field.
Verifying that the hostname matches the certificate SAN helps prevent attacks where a rogue machine has access to a valid key pair.

[[term-ssl]]SSL::
SSL is an acronym for _Secure Sockets Layer_, and is the predecessor of xref:security/ssl-framework.adoc#term-ssl-tls-protocol[TLS].
It is common to refer to SSL/TLS as just SSL.
However, the modern and secure version is TLS, and this is also the default in Neo4j.

[[term-ssl-policy]]SSL policy::
An SSL policy in Neo4j consists of a xref:security/ssl-framework.adoc#term-ssl-certificate[a digital certificate] and a set of configuration parameters defined in _neo4j.conf_.

[[term-ssl-private-key]]private key::
The private key ensures that encrypted messages can be deciphered only by the intended recipient.
The private key is commonly stored in a file named _<file name>.key_.
It is important to protect the private key to ensure the integrity of encrypted communication.

[[term-ssl-pki]]Public Key Infrastructure (_PKI_)::
A set of roles, policies, and procedures needed to create, manage, distribute, use, store, and revoke xref:security/ssl-framework.adoc#term-ssl-certificate[digital certificates] and manage xref:security/ssl-framework.adoc#term-ssl-public-key[public-key] encryption.

[[term-ssl-public-key]]public key::
The public key can be obtained and used by anyone to encrypt messages intended for a particular recipient.
This is also referred to as the xref:security/ssl-framework.adoc#term-ssl-certificate[certificate].

[[term-ssl-tls-protocol]]TLS protocol::
The cryptographic protocol that provides communications security over a computer network.
The Transport Layer Security (TLS) protocol and its predecessor, the Secure Sockets Layer (SSL) protocol are both frequently referred to as "SSL".

[[term-ssl-TLS-version]]TLS version::
A version of the TLS protocol.
