[[ssl-post-quantum]]
= Configuring SSL for Post-Quantum/Hybrid Key Exchange
:description: How to configure Neo4j to use post-quantum cryptographic key exchange.
:keywords: ssl, tls, authentication, encryption, encrypted, security, post-quantum

Neo4j can be configured to use post-quantum/hybrid key exchange when using the OpenSSL provider.
This makes Neo4j more resilient to post-quantum attacks.

This guide helps configure Neo4j to use post-quantum/hybrid key exchange. It is provided in addition to the documentation
provided by xref:security/ssl-framework.adoc[] where further configuration is detailed.

[[ssl-post-quantum-prerequisites]]
== Prerequisites

* Verify that the machine running Neo4j has https://openssl-library.org/[OpenSSL] 3.5 or later.
* Neo4j has been configured with OpenSSL being the xref:security/ssl-framework.adoc#ssl-providers[SSL Provider].

[[ssl-post-quantum-verify]]
== Verifying Post-quantum/hybrid key exchange

No further configuration is needed to enable post-quantum/hybrid key exchange. To verify that it has been
enabled successfully you can use OpenSSL client to check whether a post-quantum algorithm has been used in the
key exchange.

To do this we will open a connection to the database with `openssl s_client` by restricting the key exchange
algorithm to the post-quantum/hybrid exchange group `X25519MLKEM768`

[source, console, subs="attributes"]
.Check whether post-quantum key exchange is supported
----
openssl s_client -connect localhost:7687 -groups X25519MLKEM768
----

Note: If you are using self-signed certificates, you may need to also provide `openssl` with the certificate file. For example:

[source, console, subs="attributes"]
.Check whether post-quantum key exchange is supported with self-signed certificate
----
openssl s_client -connect localhost:7687 -groups X25519MLKEM768 -CAfile "path_to_self_signed_cert"
----

If configuration has been successful, you should see a connection being opened and within the `openssl` output
a reference to the `X25519MLKEM768` group being used during connection establishment. For example:

[source, console, subs="attributes"]
.Verify openssl console output
----
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: rsa_pss_rsae_sha256
Negotiated TLS1.3 group: X25519MLKEM768
----

== Only using post-quantum/hybrid key exchange

With the above configuration, `X25519MLKEM768` will be available on the server but there
will also be a fallback to other key exchange algorithms should the client not supprot it.
To require the use of `X25519MLKEM768`,
https://docs.openssl.org/3.6/man5/config/[configure OpenSSL] on the host machine so that only post-quantum/hybrid
key exchange is possible.

For example, in your OpenSSL configuration file `openssl.conf`:

[source, text]
.OpenSSL Configuration – Requiring post-quantum/hybrid key exchange
----
openssl_conf = default_conf

[default_conf]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
Groups = X25519MLKEM768
----


== Client Configuration

Neo4j support a wide range of clients which may also need configuration. Please see the various manuals for instructions
if required.

== Limitation

Currently only Bolt supports post-quantum/hybrid key exchange via the OpenSSL provider. The HTTP server does not currently support
 post-quantum/hybrid key exchange. Support depends on the Java ecosystem backporting post-quantum/hybrid
key exchange features to LTS versions of the JDK.