[role=enterprise-edition]
[[propagate-users-and-roles]]
= Propagate users and roles
:description: This section describes how to propagate native users, roles, and role assignments across a Neo4j cluster. 

Native users, and user passwords recorded in SHA-256 encrypted format, are stored in a file named _auth_.
Roles and role assignments are stored in a file named _roles_.
The files are located in the xref:configuration/file-locations.adoc[_data_] directory, in a subdirectory called _dbms_.
Neo4j automatically reloads the stored users and assigned roles from disk every five seconds.

Changes to users and roles are applied only to the Neo4j instance on which the commands are executed.
This means that changes are not automatically propagated across a cluster of Neo4j instances, but have to be specifically provided for.
A number of options are available to propagate changes to native users, custom roles, and role assignments across a cluster:

* Manually copy users and roles files on disk to all other cluster instances
* Use a shared network folder to store users and roles files
* Create an automated process that synchronizes the stored data across the cluster using, for example, a combination of `rsync` and `crontab`

The recommended solution for clustered security is to use the LDAP or plugin auth provider.
