:description: How to install and operate Neo4j (standalone or cluster) on Kubernetes.
[[kubernetes]]
= Kubernetes


[NOTE]
====
The Neo4j Helm Charts replace the Labs Helm Charts project at https://neo4j.com/labs.
This is the recommended way to run Neo4j on Kubernetes.
For more information on how to move from the Labs Helm Charts to the Neo4j Helm Charts, see the <<_migrate_neo4j_from_the_labs_helm_charts_to_the_neo4j_helm_charts_offline>>.
====

This chapter describes the following:

* <<kubernetes-overview, Introduction>> -- Introduction to running Neo4j on a Kubernetes cluster using Neo4j Helm Charts.
* <<helm-charts-setup, Configure the Neo4j Helm Chart repository>> -- Configure the Neo4j Helm Chart repository and check for the available charts.
* <<quick-start-standalone, Quickstart: Deploy a standalone instance>> -- Deploy a Neo4j standalone instance to a cloud (GKE, AWS, AKS) or a local (via Docker Desktop for macOS) Kubernetes cluster.
* <<quick-start-cluster, Quickstart: Deploy a cluster>> -- Deploy a Neo4j cluster to a cloud (GKE, AWS, AKS) Kubernetes cluster.
* <<kubernetes-neo4j-configuration, Configure a Neo4j deployment>> -- Configure a Neo4j deployment using a customized _values.yaml_ file.
* <<persistent-volumes, Persistent volumes>> -- Use persistent volumes with the Neo4j Helm Charts and what types Neo4j supports.
* <<accessing-neo4j, Access a Neo4j DBMS>> -- Access a Neo4j DBMS running on Kubernetes.
* <<accessing-cluster, Access a Neo4j cluster>> -- Access a Neo4j cluster running on Kubernetes.
* <<multi-dc-cluster-aks, Deploy a single Neo4j cluster across multiple AKS clusters>> -- Deploy a single Neo4j cluster with three primary servers running on three different AKS clusters.
* <<kubernetes-import-data, Import data>> -- Import data into a Neo4j database.
* <<kubernetes-monitoring, Monitoring>> -- Monitor a Neo4j deployment running on Kubernetes.
* <<kubernetes-maintenance, Operations>> -- Maintain a Neo4j deployment running on Kubernetes.
* <<kubernetes-troubleshooting, Troubleshooting>> -- Diagnose and troubleshoot a Neo4j deployment running on Kubernetes.

include::helm-charts-setup.adoc[leveloffset=+1]

include::quickstart-standalone/index.adoc[leveloffset=+1]

include::quickstart-cluster/index.adoc[leveloffset=+1]

include::configuration.adoc[leveloffset=+1]

include::persistent-volumes.adoc[leveloffset=+1]

include::accessing-neo4j.adoc[leveloffset=+1]

include::accessing-cluster.adoc[leveloffset=+1]

include::multi-dc-cluster/aks.adoc[leveloffset=+1]

include::import-data.adoc[leveloffset=+1]

include::monitoring.adoc[leveloffset=+1]

include::maintenance.adoc[leveloffset=+1]

include::troubleshooting.adoc[leveloffset=+1]
