:page-role: enterprise-edition aura-db-business-critical aura-db-dedicated
[[dbms-impersonate-privileges]]
= The DBMS `IMPERSONATE` privileges

////
[source, cypher, role=test-setup]
----
CREATE USER jake SET PASSWORD 'abcd1234' CHANGE NOT REQUIRED;
CREATE ROLE roleAdder IF NOT EXISTS;
CREATE ROLE roleNameModifier IF NOT EXISTS;
CREATE ROLE roleDropper IF NOT EXISTS;
CREATE ROLE roleAssigner IF NOT EXISTS;
CREATE ROLE roleRemover IF NOT EXISTS;
CREATE ROLE roleViewer IF NOT EXISTS;
CREATE ROLE roleManager IF NOT EXISTS;
CREATE ROLE userAdder IF NOT EXISTS;
CREATE ROLE userNameModifier IF NOT EXISTS;
CREATE ROLE userModifier IF NOT EXISTS;
CREATE ROLE userDropper IF NOT EXISTS;
CREATE ROLE userViewer IF NOT EXISTS;
CREATE ROLE userManager IF NOT EXISTS;
CREATE ROLE userImpersonator IF NOT EXISTS;
CREATE ROLE allUserImpersonator IF NOT EXISTS;
CREATE ROLE authModifier IF NOT EXISTS;
CREATE ROLE passwordModifier IF NOT EXISTS;
CREATE ROLE statusModifier IF NOT EXISTS;
CREATE ROLE homeDbModifier IF NOT EXISTS;
CREATE ROLE databaseAdder IF NOT EXISTS;
CREATE ROLE compositeDatabaseAdder IF NOT EXISTS;
CREATE ROLE databaseDropper IF NOT EXISTS;
CREATE ROLE compositeDatabaseDropper IF NOT EXISTS;
CREATE ROLE databaseModifier IF NOT EXISTS;
CREATE ROLE accessModifier IF NOT EXISTS;
CREATE ROLE languageModifier IF NOT EXISTS;
CREATE ROLE compositeDatabaseModifier IF NOT EXISTS;
CREATE ROLE compositeDatabaseManager IF NOT EXISTS;
CREATE ROLE databaseManager IF NOT EXISTS;
CREATE ROLE aliasAdder IF NOT EXISTS;
CREATE ROLE aliasDropper IF NOT EXISTS;
CREATE ROLE aliasModifier IF NOT EXISTS;
CREATE ROLE aliasViewer IF NOT EXISTS;
CREATE ROLE aliasManager IF NOT EXISTS;
CREATE ROLE privilegeViewer IF NOT EXISTS;
CREATE ROLE privilegeAssigner IF NOT EXISTS;
CREATE ROLE privilegeRemover IF NOT EXISTS;
CREATE ROLE privilegeManager IF NOT EXISTS;
CREATE ROLE procedureExecutor IF NOT EXISTS;
CREATE ROLE deniedProcedureExecutor IF NOT EXISTS;
CREATE ROLE boostedProcedureExecutor IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor1 IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor2 IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor3 IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor4 IF NOT EXISTS;
CREATE ROLE adminProcedureExecutor IF NOT EXISTS;
CREATE ROLE functionExecutor IF NOT EXISTS;
CREATE ROLE deniedFunctionExecutor IF NOT EXISTS;
CREATE ROLE boostedFunctionExecutor IF NOT EXISTS;
CREATE ROLE globbing1 IF NOT EXISTS;
CREATE ROLE globbing2 IF NOT EXISTS;
CREATE ROLE globbing3 IF NOT EXISTS;
CREATE ROLE globbing4 IF NOT EXISTS;
CREATE ROLE globbing5 IF NOT EXISTS;
CREATE ROLE globbing6 IF NOT EXISTS;
CREATE ROLE dbmsManager IF NOT EXISTS;
CREATE ROLE configurationViewer IF NOT EXISTS;
CREATE ROLE deniedConfigurationViewer IF NOT EXISTS;
CREATE ROLE serverManager IF NOT EXISTS;
CREATE ROLE serverViewer IF NOT EXISTS;
----
////

The DBMS privileges for impersonation can be granted, denied, or revoked like other privileges.

Impersonation is the ability of a user to assume another user's roles (and therefore privileges), with the restriction of not being able to execute updating `admin` commands as the impersonated user (i.e. they would still be able to use `SHOW` commands).

You can use the `IMPERSONATE` privilege to allow a user to impersonate another user.

[NOTE]
====
For more details about the syntax descriptions, see xref:database-administration/syntax.adoc#administration-syntax-reading[Reading the administration commands syntax].
====

.Impersonation privileges command syntax
[options="header", width="100%", cols="3a,2"]
|===
| Command | Description

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] IMPERSONATE [(*)]
    ON DBMS
    TO role[, ...]
| Enables the specified roles to impersonate any user.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] IMPERSONATE (user[, ...])
    ON DBMS
    TO role[, ...]
| Enables the specified roles to impersonate the specified users.

|===

=== Grant privilege to impersonate all users

You can grant the privilege to impersonate all users using the `IMPERSONATE (*)` privilege. +
For example:

.Query
[source, cypher, role=noplay]
----
GRANT IMPERSONATE (*) ON DBMS TO allUserImpersonator
----

As a result, the `allUserImpersonator` role has privileges that allow impersonating all users.
To list all privileges for the role `allUserImpersonator` as commands, use the following query:

.Query
[source, cypher, role=noplay]
----
SHOW ROLE allUserImpersonator PRIVILEGES AS COMMANDS;
----
.Result
[options="header,footer", width="100%", cols="m"]
|===
| command
| "GRANT IMPERSONATE (*) ON DBMS TO `allUserImpersonator`"
a|Rows: 1
|===

=== Grant privilege to impersonate specific users

You can also grant the privilege to impersonate specific users or a subset of users. +
For example:

.Query
[source, cypher, role=noplay]
----
GRANT IMPERSONATE (alice, bob) ON DBMS TO userImpersonator;
----

As a result, the `userImpersonator` role has privileges that allow impersonating only `alice` and `bob`.
Then, you deny the privilege to impersonate `alice`:

.Query
[source, cypher, role=noplay]
----
DENY IMPERSONATE (alice) ON DBMS TO userImpersonator;
----

As a result, the `userImpersonator` user would be able to impersonate only `bob`.

To list all privileges for the role `userImpersonator` as commands, use the following query:

.Query
[source, cypher, role=noplay]
----
SHOW ROLE userImpersonator PRIVILEGES AS COMMANDS;
----
.Result
[options="header,footer", width="100%", cols="m"]
|===
| command
| "DENY IMPERSONATE (alice) ON DBMS TO `userImpersonator`"
| "GRANT IMPERSONATE (alice) ON DBMS TO `userImpersonator`"
| "GRANT IMPERSONATE (bob) ON DBMS TO `userImpersonator`"
a|Rows: 3
|===
