:page-role: enterprise-edition aura-db-business-critical aura-db-dedicated
[[dbms-database-management-privileges]]
= The DBMS `DATABASE MANAGEMENT` privileges

////
[source, cypher, role=test-setup]
----
CREATE USER jake SET PASSWORD 'abcd1234' CHANGE NOT REQUIRED;
CREATE ROLE roleAdder IF NOT EXISTS;
CREATE ROLE roleNameModifier IF NOT EXISTS;
CREATE ROLE roleDropper IF NOT EXISTS;
CREATE ROLE roleAssigner IF NOT EXISTS;
CREATE ROLE roleRemover IF NOT EXISTS;
CREATE ROLE roleViewer IF NOT EXISTS;
CREATE ROLE roleManager IF NOT EXISTS;
CREATE ROLE userAdder IF NOT EXISTS;
CREATE ROLE userNameModifier IF NOT EXISTS;
CREATE ROLE userModifier IF NOT EXISTS;
CREATE ROLE userDropper IF NOT EXISTS;
CREATE ROLE userViewer IF NOT EXISTS;
CREATE ROLE userManager IF NOT EXISTS;
CREATE ROLE userImpersonator IF NOT EXISTS;
CREATE ROLE allUserImpersonator IF NOT EXISTS;
CREATE ROLE authModifier IF NOT EXISTS;
CREATE ROLE passwordModifier IF NOT EXISTS;
CREATE ROLE statusModifier IF NOT EXISTS;
CREATE ROLE homeDbModifier IF NOT EXISTS;
CREATE ROLE databaseAdder IF NOT EXISTS;
CREATE ROLE compositeDatabaseAdder IF NOT EXISTS;
CREATE ROLE databaseDropper IF NOT EXISTS;
CREATE ROLE compositeDatabaseDropper IF NOT EXISTS;
CREATE ROLE databaseModifier IF NOT EXISTS;
CREATE ROLE accessModifier IF NOT EXISTS;
CREATE ROLE languageModifier IF NOT EXISTS;
CREATE ROLE compositeDatabaseModifier IF NOT EXISTS;
CREATE ROLE compositeDatabaseManager IF NOT EXISTS;
CREATE ROLE databaseManager IF NOT EXISTS;
CREATE ROLE aliasAdder IF NOT EXISTS;
CREATE ROLE aliasDropper IF NOT EXISTS;
CREATE ROLE aliasModifier IF NOT EXISTS;
CREATE ROLE aliasViewer IF NOT EXISTS;
CREATE ROLE aliasManager IF NOT EXISTS;
CREATE ROLE privilegeViewer IF NOT EXISTS;
CREATE ROLE privilegeAssigner IF NOT EXISTS;
CREATE ROLE privilegeRemover IF NOT EXISTS;
CREATE ROLE privilegeManager IF NOT EXISTS;
CREATE ROLE procedureExecutor IF NOT EXISTS;
CREATE ROLE deniedProcedureExecutor IF NOT EXISTS;
CREATE ROLE boostedProcedureExecutor IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor1 IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor2 IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor3 IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor4 IF NOT EXISTS;
CREATE ROLE adminProcedureExecutor IF NOT EXISTS;
CREATE ROLE functionExecutor IF NOT EXISTS;
CREATE ROLE deniedFunctionExecutor IF NOT EXISTS;
CREATE ROLE boostedFunctionExecutor IF NOT EXISTS;
CREATE ROLE globbing1 IF NOT EXISTS;
CREATE ROLE globbing2 IF NOT EXISTS;
CREATE ROLE globbing3 IF NOT EXISTS;
CREATE ROLE globbing4 IF NOT EXISTS;
CREATE ROLE globbing5 IF NOT EXISTS;
CREATE ROLE globbing6 IF NOT EXISTS;
CREATE ROLE dbmsManager IF NOT EXISTS;
CREATE ROLE configurationViewer IF NOT EXISTS;
CREATE ROLE deniedConfigurationViewer IF NOT EXISTS;
CREATE ROLE serverManager IF NOT EXISTS;
CREATE ROLE serverViewer IF NOT EXISTS;
----
////

The DBMS privileges for database management can be granted, denied, or revoked like other privileges.

[NOTE]
====
For more details about the syntax descriptions, see xref:database-administration/syntax.adoc#administration-syntax-reading[Reading the administration commands syntax].
====

.Database management privileges command syntax
[options="header", width="100%", cols="3a,2"]
|===
| Command | Description

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] CREATE DATABASE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to create new standard databases.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] DROP DATABASE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to delete standard databases.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] ALTER DATABASE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to modify standard databases.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] SET DATABASE ACCESS
  ON DBMS
  TO role[, ...]
| Enables the specified roles to modify access to standard databases.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] SET DATABASE DEFAULT LANGUAGE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to set the default query language on a standard database.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] CREATE COMPOSITE DATABASE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to create new composite databases.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] DROP COMPOSITE DATABASE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to delete composite databases.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] ALTER COMPOSITE DATABASE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to modify composite databases.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] COMPOSITE DATABASE MANAGEMENT
  ON DBMS
  TO role[, ...]
| Enables the specified roles to create, delete or modify composite databases.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] DATABASE MANAGEMENT
  ON DBMS
  TO role[, ...]
| Enables the specified roles to create, delete, and modify databases.

|===

[NOTE]
====
From Cypher 25 (Neo4j server 2025.08), the `ALTER DATABASE`, `SET DATABASE ACCESS`, `SET DATABASE DEFAULT LANGUAGE`, and `ALTER COMPOSITE DATABASE` privileges can be granted both as database privileges and as DBMS privileges.
The DBMS privilege version is equivalent to granting the privilege for all databases, `DATABASE *`.
For more information on the database privilege versions, see xref:authentication-authorization/database-administration.adoc#access-control-database-administration-alter-db[The alter database-related privileges].
====

=== Grant privilege to create standard databases

You can grant the privilege to create standard databases using the `CREATE DATABASE` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT CREATE DATABASE ON DBMS TO databaseAdder
----

As a result, the `databaseAdder` role has privileges that only allow creating standard databases.
To list all privileges for the role `databaseAdder` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE databaseAdder PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT CREATE DATABASE ON DBMS TO `databaseAdder`"
a|Rows: 1
|===

=== Grant privilege to create composite databases

You can grant the privilege to create composite databases using the `CREATE COMPOSITE DATABASE` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT CREATE COMPOSITE DATABASE ON DBMS TO compositeDatabaseAdder
----

As a result, the `compositeDatabaseAdder` role has privileges that only allow creating composite databases.
To list all privileges for the role `compositeDatabaseAdder` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE compositeDatabaseAdder PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT CREATE COMPOSITE DATABASE ON DBMS TO `compositeDatabaseAdder`"
a|Rows: 1
|===

=== Grant privilege to delete standard databases

You can grant the privilege to delete standard databases using the `DROP DATABASE` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT DROP DATABASE ON DBMS TO databaseDropper
----

As a result, the `databaseDropper` role has privileges that only allow deleting standard databases.
To list all privileges for the role `databaseDropper` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE databaseDropper PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT DROP DATABASE ON DBMS TO `databaseDropper`"
a|Rows: 1
|===

=== Grant privilege to delete composite databases

You can grant the privilege to delete composite databases using the `DROP COMPOSITE DATABASE` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT DROP COMPOSITE DATABASE ON DBMS TO compositeDatabaseDropper
----

As a result, the `compositeDatabaseDropper` role has privileges that only allow deleting composite databases.
To list all privileges for the role `compositeDatabaseDropper` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE compositeDatabaseDropper PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT DROP COMPOSITE DATABASE ON DBMS TO `compositeDatabaseDropper`"
a|Rows: 1
|===

=== Grant privilege to modify standard databases

You can grant the privilege to modify standard databases using the `ALTER DATABASE` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT ALTER DATABASE ON DBMS TO databaseModifier;
----

As a result, the `databaseModifier` role has privileges that only allow modifying standard databases.
To list all privileges for the role `databaseModifier` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE databaseModifier PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT ALTER DATABASE ON DBMS TO `databaseModifier`"
a|Rows: 1
|===

[NOTE]
====
From Cypher 25 (Neo4j server 2025.08), the `ALTER DATABASE` privileges can be granted both as database privileges and as DBMS privileges.
The DBMS privilege version is equivalent to granting the privilege for all databases, `DATABASE *`.
For more information on the database privilege versions, see xref:authentication-authorization/database-administration.adoc#access-control-database-administration-alter-db[The alter database-related privileges].
====

=== Grant privilege to modify access to standard databases

You can grant the privilege to modify access to standard databases using the `SET DATABASE ACCESS` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT SET DATABASE ACCESS ON DBMS TO accessModifier
----

As a result, the `accessModifier` role has privileges that only allow modifying access to standard databases.
To list all privileges for the role `accessModifier` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE accessModifier PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT SET DATABASE ACCESS ON DBMS TO `accessModifier`"
a|Rows: 1
|===

[NOTE]
====
From Cypher 25 (Neo4j server 2025.08), the `SET DATABASE ACCESS` privileges can be granted both as database privileges and as DBMS privileges.
The DBMS privilege version is equivalent to granting the privilege for all databases, `DATABASE *`.
For more information on the database privilege versions, see xref:authentication-authorization/database-administration.adoc#access-control-database-administration-alter-db[The alter database-related privileges].
====

[role=label--new-2025.06]
=== Grant privilege to modify the default language of standard databases

You can grant the privilege to modify the default language of standard databases using the `SET DATABASE DEFAULT LANGUAGE` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT SET DATABASE DEFAULT LANGUAGE ON DBMS TO languageModifier
----

As a result, the `languageModifier` role has privileges that only allow modifying default language to standard databases.
To list all privileges for the role `languageModifier` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE languageModifier PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT SET DATABASE DEFAULT LANGUAGE ON DBMS TO `languageModifier`"
a|Rows: 1
|===

[NOTE]
====
From Cypher 25 (Neo4j server 2025.08), the `SET DATABASE DEFAULT LANGUAGE` privileges can be granted both as database privileges and as DBMS privileges.
The DBMS privilege version is equivalent to granting the privilege for all databases, `DATABASE *`.
For more information on the database privilege versions, see xref:authentication-authorization/database-administration.adoc#access-control-database-administration-alter-db[The alter database-related privileges].
====

[role=label--new-2025.06]
[[grant-privilege-alter-composite-database]]
=== Grant privilege to modify composite databases

You can grant the privilege to modify composite databases using the `ALTER COMPOSITE DATABASE` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT ALTER COMPOSITE DATABASE ON DBMS TO compositeDatabaseModifier;
----

As a result, the `compositeDatabaseModifier` role has privileges that only allow modifying composite databases.
To list all privileges for the role `compositeDatabaseModifier` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE compositeDatabaseModifier PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT ALTER COMPOSITE DATABASE ON DBMS TO `compositeDatabaseModifier`"
a|Rows: 1
|===

[NOTE]
====
From Cypher 25 (Neo4j server 2025.08), the `ALTER COMPOSITE DATABASE` privileges can be granted both as database privileges and as DBMS privileges.
The DBMS privilege version is equivalent to granting the privilege for all databases, `DATABASE *`.
For more information on the database privilege versions, see xref:authentication-authorization/database-administration.adoc#access-control-database-administration-alter-db[The alter database-related privileges].
====

=== Grant privilege to manage composite databases

You can grant the privilege to create, delete, and modify composite databases using the `COMPOSITE DATABASE MANAGEMENT` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT COMPOSITE DATABASE MANAGEMENT ON DBMS TO compositeDatabaseManager;
----

As a result, the `compositeDatabaseManager` role has all privileges to manage composite databases.
To list all privileges for the role `compositeDatabaseManager` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE compositeDatabaseManager PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT COMPOSITE DATABASE MANAGEMENT ON DBMS TO `compositeDatabaseManager`"
a|Rows: 1
|===

=== Grant privilege to manage standard and composite databases

You can grant the privilege to create, delete, and modify standard and composite databases using the `DATABASE MANAGEMENT` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT DATABASE MANAGEMENT ON DBMS TO databaseManager;
----

As a result, the `databaseManager` role has all privileges to manage standard and composite databases.
To list all privileges for the role `databaseManager` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE databaseManager PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT DATABASE MANAGEMENT ON DBMS TO `databaseManager`"
a|Rows: 1
|===