:description: Details the privileges associated with the administrator role for managing the DBMS.
:page-role: enterprise-edition aura-db-business-critical aura-db-dedicated
= Administrator role privileges

You can manage DBMS privileges using either the built-in `admin` role or by creating a custom role with the specific privileges you need.

== Using the built-in `admin` role to manage DBMS privileges

The xref:authentication-authorization/built-in-roles.adoc#access-control-built-in-roles-admin[`admin` role] role is a built-in superuser role that has all privileges on the DBMS and can perform all administrative tasks.

This includes the following tasks and their relevant privileges:

* Create, delete, and modify xref:authentication-authorization/dbms-administration/dbms-database-management-privileges.adoc[databases] and  xref:authentication-authorization/dbms-administration/dbms-alias-management-privileges.adoc[aliases].
* Change configuration parameters.
* xref:authentication-authorization/database-administration.adoc#access-control-database-administration-transaction[Manage transactions].
* Manage xref:authentication-authorization/dbms-administration/dbms-user-management-privileges.adoc[users], xref:authentication-authorization/dbms-administration/dbms-user-metadata-management-privileges.adoc[user metadata], xref:authentication-authorization/dbms-administration/dbms-role-management-privileges.adoc[roles] and xref:authentication-authorization/dbms-administration/dbms-auth-rule-management-privileges.adoc[auth rules].
* Manage xref:authentication-authorization/dbms-administration/dbms-privilege-management-privileges.adoc[privilege management].
* Manage xref:authentication-authorization/privileges-reads.adoc[read] and xref:authentication-authorization/privileges-writes.adoc[write] sub-graph privileges.
* Manage xref:authentication-authorization/dbms-administration/dbms-impersonate-privileges.adoc[impersonation privileges].
* Manage xref:authentication-authorization/dbms-administration/dbms-execute-privileges.adoc[procedure security].
* Manage xref:authentication-authorization/load-privileges.adoc[load data security].

To enable a user to perform these tasks, you can grant them the `admin` role, but it is also possible to make a custom role with a subset of these privileges.
All privileges are also assignable using Cypher commands.


[[access-control-dbms-administration-custom]]
== Using a custom role to manage DBMS privileges

You can create a custom role to manage DBMS privileges by granting the privileges you want to the role.
Alternatively, you can copy the `admin` role and revoke or deny the unwanted privileges.
The following examples show how to create a custom role with a subset of the privileges that the `admin` role using both methods.

=== Create a custom administrator role from scratch

Create an administrator role that can only manage users and roles by creating a new role and granting the `USER MANAGEMENT` and `ROLE MANAGEMENT` privileges.

. Create the new role:
+
[source, cypher, role=noplay]
----
CREATE ROLE userAndRoleAdministrator;
----
. Grant the privilege to manage users:
+
[source, cypher, role=noplay]
----
GRANT USER MANAGEMENT ON DBMS TO userAndRoleAdministrator;
----
. Grant the privilege to manage roles:
+
[source, cypher, role=noplay]
----
GRANT ROLE MANAGEMENT ON DBMS TO userAndRoleAdministrator;
----
+
As a result, the `userAndRoleAdministrator` role has privileges that only allow user and role management.
. To show all privileges for the role `userAndRoleAdministrator` as commands, use the following query:
+
[source, cypher, role=noplay]
----
SHOW ROLE userAndRoleAdministrator PRIVILEGES AS COMMANDS;
----
+
.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT ROLE MANAGEMENT ON DBMS TO `userAndRoleAdministrator`"
|"GRANT USER MANAGEMENT ON DBMS TO `userAndRoleAdministrator`"
a|Rows: 2
|===

[NOTE]
====
This role does not allow all DBMS capabilities.
For example, the role is missing privileges for managing, creating, and dropping databases, as well as executing `admin` procedures.
To create a more powerful administrator, you can grant a different set of privileges.
====

=== Create a more powerful custom administrator role from scratch

You can also create a custom administrator role with limited capabilities.
This can be done by creating a new role and granting all `DBMS` privileges, then denying the ones you do not want the role to have, and then granting additional privileges you want to include.
For example, you can create a custom administrator role `customAdministrator` that has all DBMS privileges except for creating, dropping, and modifying databases, and also has the privilege for managing transactions.

. Create a new role:
+
[source, cypher, role=noplay]
----
CREATE ROLE customAdministrator;
----
. Grant the privilege for all DBMS capabilities:
+
[source, cypher, role=noplay]
----
GRANT ALL DBMS PRIVILEGES ON DBMS TO customAdministrator;
----
. Explicitly deny the privilege to manage databases:
+
[source, cypher, role=noplay]
----
DENY DATABASE MANAGEMENT ON DBMS TO customAdministrator;
----
. Grant the transaction management privilege:
+
[source, cypher, role=noplay]
----
GRANT TRANSACTION MANAGEMENT (*) ON DATABASE * TO customAdministrator;
----
+
As a result, the `customAdministrator` role has privileges that include managing transactions and all DBMS privileges except creating, dropping, and modifying databases.
. To show all privileges for the role `customAdministrator` as commands, use the following query:
+
[source, cypher, role=noplay]
----
SHOW ROLE customAdministrator PRIVILEGES AS COMMANDS;
----
+
.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"DENY DATABASE MANAGEMENT ON DBMS TO `customAdministrator`"
|"GRANT ALL DBMS PRIVILEGES ON DBMS TO `customAdministrator`"
|"GRANT TRANSACTION MANAGEMENT (*) ON DATABASE * TO `customAdministrator`"
a|Rows: 3
|===

=== Create a custom administrator role by copying the `admin` role

You can also create a custom administrator role by copying the `admin` role and then revoking or denying the privileges you do not want.
For example, you can create a new role called `newAdministrator` that has all the privileges of the `admin` role, and then revoke the ability to read/write/load data, manage constraints, indexes, name, and remove ability to access all databases, except the `system` database.

. Create a new role by copying the `admin` role:
+
[source, cypher, role=noplay]
----
CREATE ROLE newAdministrator AS COPY OF admin;
----

. Revoke the ability to read/write/load data:
+
[source, cypher, role=noplay]
----
REVOKE GRANT MATCH {*} ON GRAPH * NODE * FROM newAdministrator;
REVOKE GRANT MATCH {*} ON GRAPH * RELATIONSHIP * FROM newAdministrator;
REVOKE GRANT WRITE ON GRAPH * FROM newAdministrator;
REVOKE GRANT LOAD ON ALL DATA FROM newAdministrator;
----

. Revoke the ability to manage index/constraint/name:
+
[source, cypher, role=noplay]
----
REVOKE GRANT CONSTRAINT MANAGEMENT ON DATABASE * FROM newAdministrator;
REVOKE GRANT INDEX MANAGEMENT ON DATABASE * FROM newAdministrator;
REVOKE GRANT NAME MANAGEMENT ON DATABASE * FROM newAdministrator;
REVOKE GRANT SHOW CONSTRAINT ON DATABASE * FROM newAdministrator;
REVOKE GRANT SHOW INDEX ON DATABASE * FROM newAdministrator;
----

. Revoke the ability to access all databases:
+
[source, cypher, role=noplay]
----
REVOKE GRANT ACCESS ON DATABASE * FROM newAdministrator;
----
. Grant the ability to access the `system` database:
+
[source, cypher, role=noplay]
----
GRANT ACCESS ON DATABASE system TO newAdministrator;
----

. To show all privileges for the role `newAdministrator` as commands, use the following query:
+
[source, cypher, role=noplay]
----
SHOW ROLE newAdministrator PRIVILEGES AS COMMANDS;
----
+
.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
| "GRANT ACCESS ON DATABASE `system` TO `newAdministrator`"
| "GRANT ALL DBMS PRIVILEGES ON DBMS TO `newAdministrator`"
| "GRANT START ON DATABASE * TO `newAdministrator`"
| "GRANT STOP ON DATABASE * TO `newAdministrator`"
| "GRANT TRANSACTION MANAGEMENT (*) ON DATABASE * TO `newAdministrator`"
a|Rows: 5
|===

