:description: Details the DBMS privileges for user management.
:page-role: enterprise-edition aura-db-business-critical aura-db-dedicated
[[dbms-user-management-privileges]]
= The DBMS `USER MANAGEMENT` privileges

////
[source, cypher, role=test-setup]
----
CREATE USER jake SET PASSWORD 'abcd1234' CHANGE NOT REQUIRED;
CREATE ROLE roleAdder IF NOT EXISTS;
CREATE ROLE roleNameModifier IF NOT EXISTS;
CREATE ROLE roleDropper IF NOT EXISTS;
CREATE ROLE roleAssigner IF NOT EXISTS;
CREATE ROLE roleRemover IF NOT EXISTS;
CREATE ROLE roleViewer IF NOT EXISTS;
CREATE ROLE roleManager IF NOT EXISTS;
CREATE ROLE userAdder IF NOT EXISTS;
CREATE ROLE userNameModifier IF NOT EXISTS;
CREATE ROLE userModifier IF NOT EXISTS;
CREATE ROLE userDropper IF NOT EXISTS;
CREATE ROLE userViewer IF NOT EXISTS;
CREATE ROLE userManager IF NOT EXISTS;
CREATE ROLE userImpersonator IF NOT EXISTS;
CREATE ROLE allUserImpersonator IF NOT EXISTS;
CREATE ROLE authModifier IF NOT EXISTS;
CREATE ROLE passwordModifier IF NOT EXISTS;
CREATE ROLE statusModifier IF NOT EXISTS;
CREATE ROLE homeDbModifier IF NOT EXISTS;
CREATE ROLE databaseAdder IF NOT EXISTS;
CREATE ROLE compositeDatabaseAdder IF NOT EXISTS;
CREATE ROLE databaseDropper IF NOT EXISTS;
CREATE ROLE compositeDatabaseDropper IF NOT EXISTS;
CREATE ROLE databaseModifier IF NOT EXISTS;
CREATE ROLE accessModifier IF NOT EXISTS;
CREATE ROLE languageModifier IF NOT EXISTS;
CREATE ROLE compositeDatabaseModifier IF NOT EXISTS;
CREATE ROLE compositeDatabaseManager IF NOT EXISTS;
CREATE ROLE databaseManager IF NOT EXISTS;
CREATE ROLE aliasAdder IF NOT EXISTS;
CREATE ROLE aliasDropper IF NOT EXISTS;
CREATE ROLE aliasModifier IF NOT EXISTS;
CREATE ROLE aliasViewer IF NOT EXISTS;
CREATE ROLE aliasManager IF NOT EXISTS;
CREATE ROLE privilegeViewer IF NOT EXISTS;
CREATE ROLE privilegeAssigner IF NOT EXISTS;
CREATE ROLE privilegeRemover IF NOT EXISTS;
CREATE ROLE privilegeManager IF NOT EXISTS;
CREATE ROLE procedureExecutor IF NOT EXISTS;
CREATE ROLE deniedProcedureExecutor IF NOT EXISTS;
CREATE ROLE boostedProcedureExecutor IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor1 IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor2 IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor3 IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor4 IF NOT EXISTS;
CREATE ROLE adminProcedureExecutor IF NOT EXISTS;
CREATE ROLE functionExecutor IF NOT EXISTS;
CREATE ROLE deniedFunctionExecutor IF NOT EXISTS;
CREATE ROLE boostedFunctionExecutor IF NOT EXISTS;
CREATE ROLE globbing1 IF NOT EXISTS;
CREATE ROLE globbing2 IF NOT EXISTS;
CREATE ROLE globbing3 IF NOT EXISTS;
CREATE ROLE globbing4 IF NOT EXISTS;
CREATE ROLE globbing5 IF NOT EXISTS;
CREATE ROLE globbing6 IF NOT EXISTS;
CREATE ROLE dbmsManager IF NOT EXISTS;
CREATE ROLE configurationViewer IF NOT EXISTS;
CREATE ROLE deniedConfigurationViewer IF NOT EXISTS;
CREATE ROLE serverManager IF NOT EXISTS;
CREATE ROLE serverViewer IF NOT EXISTS;
----
////

The DBMS privileges for user management can be granted, denied, or revoked like other privileges.

[NOTE]
====
For more details about the syntax descriptions, see xref:database-administration/syntax.adoc#administration-syntax-reading[Reading the administration commands syntax].
====

.User management privileges command syntax
[options="header", width="100%", cols="3a,2"]
|===
| Command | Description

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] CREATE USER
  ON DBMS
  TO role[, ...]
| Enables the specified roles to create new users.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] RENAME USER
  ON DBMS
  TO role[, ...]
| Enables the specified roles to change the name of users.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] ALTER USER
  ON DBMS
  TO role[, ...]
| Enables the specified roles to modify users.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] SET PASSWORD[S]
  ON DBMS
  TO role[, ...]
| Enables the specified roles to modify users' passwords and whether those passwords must be changed upon first login.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] SET AUTH
  ON DBMS
  TO role[, ...]
| Enables the specified roles to `SET` or `REMOVE` users' xref:authentication-authorization/auth-providers.adoc[auth providers].

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] SET USER HOME DATABASE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to modify users' home database.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] SET USER STATUS
  ON DBMS
  TO role[, ...]
| Enables the specified roles to modify the account status of users.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] DROP USER
  ON DBMS
  TO role[, ...]
| Enables the specified roles to delete users.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] SHOW USER
  ON DBMS
  TO role[, ...]
| Enables the specified roles to list users.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] USER MANAGEMENT
  ON DBMS
  TO role[, ...]
| Enables the specified roles to create, delete, modify, and list users.

|===

[[grant-create-user-privilege]]
== Grant privilege to create users

You can grant the privilege to add users using the `CREATE USER` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT CREATE USER ON DBMS TO userAdder
----

As a result, the `userAdder` role has privileges that only allow adding users.
To list all privileges for the role `userAdder` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE userAdder PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT CREATE USER ON DBMS TO `userAdder`"
a|Rows: 1
|===

== Grant privilege to rename users

You can grant the privilege to rename users using the `RENAME USER` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT RENAME USER ON DBMS TO userNameModifier
----

As a result, the `userNameModifier` role has privileges that only allow renaming users.
To list all privileges for the role `userNameModifier` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE userNameModifier PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT RENAME USER ON DBMS TO `userNameModifier`"
a|Rows: 1
|===

== Grant privilege to modify users

You can grant the privilege to modify users using the `ALTER USER` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT ALTER USER ON DBMS TO userModifier
----

As a result, the `userModifier` role has privileges that only allow modifying users.
To list all privileges for the role `userModifier` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE userModifier PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT ALTER USER ON DBMS TO `userModifier`"
a|Rows: 1
|===


The `ALTER USER` privilege allows the user to run the `ALTER USER` administration command with one or several of the `SET PASSWORD`, `SET PASSWORD CHANGE [NOT] REQUIRED`, `SET AUTH`, `REMOVE AUTH`, `SET STATUS`, `SET HOME DATABASE`, and `REMOVE HOME DATABASE` parts. +
For example:

[source, cypher, role=noplay]
----
ALTER USER jake SET PASSWORD 'verysecret' SET STATUS SUSPENDED
----

[NOTE]
====
Note that the combination of the `SET PASSWORDS`, `SET AUTH`, `SET USER STATUS`, and `SET USER HOME DATABASE` privileges is equivalent to the `ALTER USER` privilege.
====

== Grant privilege to modify users' passwords

You can grant the privilege to modify users' passwords and whether those passwords must be changed upon first login using the `SET PASSWORDS` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT SET PASSWORDS ON DBMS TO passwordModifier
----

As a result, the `passwordModifier` role has privileges that only allow modifying users' passwords and whether those passwords must be changed upon first login.
To list all privileges for the role `passwordModifier` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE passwordModifier PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT SET PASSWORD ON DBMS TO `passwordModifier`"
a|Rows: 1
|===

The `SET PASSWORDS` privilege allows the user to run the `ALTER USER` administration command with one or both of the `SET PASSWORD` and `SET PASSWORD CHANGE [NOT] REQUIRED` parts.

[source, cypher, role=noplay]
----
ALTER USER jake SET PASSWORD 'abcd5678' CHANGE NOT REQUIRED
----

== Grant privilege to modify users' auth information

You can grant the privilege to modify users' auth information using the `SET AUTH` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT SET AUTH ON DBMS TO authModifier
----
As a result, the `authModifier` role has privileges that only allow modifying users' auth information.

The `SET AUTH` privilege allows the user to run the `ALTER USER` administration command with one or both of the `SET
AUTH` and `REMOVE AUTH` parts. +
For example:

[source, cypher, role=noplay]
----
ALTER USER jake REMOVE AUTH 'native' SET AUTH 'oidc-okta' { SET id 'jakesUniqueOktaUserId' }
----

== Grant privilege to modify the account status of users

You can grant the privilege to modify the account status of users using the `SET USER STATUS` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT SET USER STATUS ON DBMS TO statusModifier
----

As a result, the `statusModifier` role has privileges that only allow modifying the account status of users.
To list all privileges for the role `statusModifier` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE statusModifier PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT SET USER STATUS ON DBMS TO `statusModifier`"
a|Rows: 1
|===

The `SET USER STATUS` privilege allows the user to run the `ALTER USER` administration command with only the `SET STATUS` part:

[source, cypher, role=noplay]
----
ALTER USER jake SET STATUS ACTIVE
----

== Grant privilege to modify the home database of users

You can grant the privilege to modify the home database of users using the `SET USER HOME DATABASE` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT SET USER HOME DATABASE ON DBMS TO homeDbModifier
----

As a result, the `homeDbModifier` role has privileges that only allow modifying the home database of users.
To list all privileges for the role `homeDbModifier` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE homeDbModifier PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT SET USER HOME DATABASE ON DBMS TO `homeDbModifier`"
|"GRANT SET USER STATUS ON DBMS TO `homeDbModifier`"
a|Rows: 2
|===

The `SET USER HOME DATABASE` privilege allows the user to run the `ALTER USER` administration command with only the `SET HOME DATABASE` or `REMOVE HOME DATABASE` part:

[source, cypher, role=noplay]
----
ALTER USER jake SET HOME DATABASE otherDb
----

[source, cypher, role=noplay]
----
ALTER USER jake REMOVE HOME DATABASE
----

[[grant-delete-user-privilege]]
== Grant privilege to delete users

You can grant the privilege to delete users using the `DROP USER` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT DROP USER ON DBMS TO userDropper
----

As a result, the `userDropper` role has privileges that only allow deleting users.
To list all privileges for the role `userDropper` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE userDropper PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT DROP USER ON DBMS TO `userDropper`"
a|Rows: 1
|===


== Grant privilege to show users

You can grant the privilege to show users using the `SHOW USER` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT SHOW USER ON DBMS TO userViewer
----

As a result, the `userViewer` role has privileges that only allow showing users.
To list all privileges for the role `userViewer` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE userViewer PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT SHOW USER ON DBMS TO `userViewer`"
a|Rows: 1
|===

== Grant privilege to manage users

You can grant the privilege to create, rename, modify, delete, and list users using the `USER MANAGEMENT` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT USER MANAGEMENT ON DBMS TO userManager
----

As a result, the `userManager` role has all privileges to manage users.
To list all privileges for the role `userManager` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE userManager PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT SHOW USER ON DBMS TO `userManager`"
a|Rows: 1
|===