:description: Details the DBMS privileges for privilege management.
:page-role: enterprise-edition aura-db-business-critical aura-db-dedicated
[[dbms-privilege-management-privileges]]
= DBMS `PRIVILEGE MANAGEMENT` privileges

////
[source, cypher, role=test-setup]
----
CREATE ROLE privilegeViewer IF NOT EXISTS;
CREATE ROLE privilegeAssigner IF NOT EXISTS;
CREATE ROLE privilegeRemover IF NOT EXISTS;
CREATE ROLE privilegeManager IF NOT EXISTS;
----
////

The DBMS privileges for privilege management can be granted, denied, or revoked like other privileges.

[NOTE]
====
For more details about the syntax descriptions, see xref:database-administration/syntax.adoc#administration-syntax-reading[Reading the administration commands syntax].
====

.Privilege management privileges command syntax
[options="header", width="100%", cols="3a,2"]
|===
| Command | Description

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] SHOW PRIVILEGE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to list privileges.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] ASSIGN PRIVILEGE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to assign privileges using the `GRANT` and `DENY` commands.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] REMOVE PRIVILEGE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to remove privileges using the `REVOKE` command.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] PRIVILEGE MANAGEMENT
  ON DBMS
  TO role[, ...]
| Enables the specified roles to list, assign, and remove privileges.
|===

== Grant privilege to show privileges

You can grant the `SHOW PRIVILEGE` privilege to allow a user to show privileges using the `SHOW PRIVILEGE`, `SHOW ROLE roleName PRIVILEGES`, and `SHOW USER username PRIVILEGES` administration commands.
The `SHOW USER username PRIVILEGES` command also requires the `SHOW USER` privilege.

For example:

[source, cypher, role=noplay]
----
GRANT SHOW PRIVILEGE ON DBMS TO privilegeViewer;
----

As a result, the `privilegeViewer` role has privileges that only allow showing privileges.
To show all privileges for the role `privilegeViewer` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE privilegeViewer PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT SHOW PRIVILEGE ON DBMS TO `privilegeViewer`"
a|Rows: 1
|===

[NOTE]
====
No specific privileges are required for showing the current user's privileges through the `SHOW USER _username_ PRIVILEGES` or `SHOW USER PRIVILEGES` commands.

If a non-native auth provider like LDAP is in use, `SHOW USER PRIVILEGES` will only work with a limited capacity by making it only possible for a user to show their own privileges.
Other users' privileges cannot be listed when using a non-native auth provider.
====

== Grant privilege to assign privileges

You can grant the privilege to assign privileges using the `ASSIGN PRIVILEGE` privilege. +
A user with this privilege is allowed to execute `GRANT` and `DENY` administration commands. +
For example:

[source, cypher, role=noplay]
----
GRANT ASSIGN PRIVILEGE ON DBMS TO privilegeAssigner;
----

As a result, the `privilegeAssigner` role has privileges that only allow assigning privileges.
To show all privileges for the role `privilegeAssigner` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE privilegeAssigner PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT ASSIGN PRIVILEGE ON DBMS TO `privilegeAssigner`"
a|Rows: 1
|===

== Grant privilege to remove privileges

You can grant the privilege to remove privileges from roles using the `REMOVE PRIVILEGE` privilege. +
A user with this privilege is allowed to execute `REVOKE` administration commands. +
For example:

[source, cypher, role=noplay]
----
GRANT REMOVE PRIVILEGE ON DBMS TO privilegeRemover;
----

As a result, the `privilegeRemover` role has privileges that only allow removing privileges.
To show all privileges for the role `privilegeRemover` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE privilegeRemover PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT REMOVE PRIVILEGE ON DBMS TO `privilegeRemover`"
a|Rows: 1
|===

== Grant privilege to manage privileges

You can grant the privilege to list, assign, and remove privileges using the `PRIVILEGE MANAGEMENT` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT PRIVILEGE MANAGEMENT ON DBMS TO privilegeManager;
----

As a result, the `privilegeManager` role has all privileges to manage privileges.
To show all privileges for the role `privilegeManager` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE privilegeManager PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT PRIVILEGE MANAGEMENT ON DBMS TO `privilegeManager`"
a|Rows: 1
|===
