:page-role: enterprise-edition aura-db-business-critical aura-db-dedicated
[[dbms-privilege-management-privileges]]
= The DBMS `PRIVILEGE MANAGEMENT` privileges

////
[source, cypher, role=test-setup]
----
CREATE USER jake SET PASSWORD 'abcd1234' CHANGE NOT REQUIRED;
CREATE ROLE roleAdder IF NOT EXISTS;
CREATE ROLE roleNameModifier IF NOT EXISTS;
CREATE ROLE roleDropper IF NOT EXISTS;
CREATE ROLE roleAssigner IF NOT EXISTS;
CREATE ROLE roleRemover IF NOT EXISTS;
CREATE ROLE roleViewer IF NOT EXISTS;
CREATE ROLE roleManager IF NOT EXISTS;
CREATE ROLE userAdder IF NOT EXISTS;
CREATE ROLE userNameModifier IF NOT EXISTS;
CREATE ROLE userModifier IF NOT EXISTS;
CREATE ROLE userDropper IF NOT EXISTS;
CREATE ROLE userViewer IF NOT EXISTS;
CREATE ROLE userManager IF NOT EXISTS;
CREATE ROLE userImpersonator IF NOT EXISTS;
CREATE ROLE allUserImpersonator IF NOT EXISTS;
CREATE ROLE authModifier IF NOT EXISTS;
CREATE ROLE passwordModifier IF NOT EXISTS;
CREATE ROLE statusModifier IF NOT EXISTS;
CREATE ROLE homeDbModifier IF NOT EXISTS;
CREATE ROLE databaseAdder IF NOT EXISTS;
CREATE ROLE compositeDatabaseAdder IF NOT EXISTS;
CREATE ROLE databaseDropper IF NOT EXISTS;
CREATE ROLE compositeDatabaseDropper IF NOT EXISTS;
CREATE ROLE databaseModifier IF NOT EXISTS;
CREATE ROLE accessModifier IF NOT EXISTS;
CREATE ROLE languageModifier IF NOT EXISTS;
CREATE ROLE compositeDatabaseModifier IF NOT EXISTS;
CREATE ROLE compositeDatabaseManager IF NOT EXISTS;
CREATE ROLE databaseManager IF NOT EXISTS;
CREATE ROLE aliasAdder IF NOT EXISTS;
CREATE ROLE aliasDropper IF NOT EXISTS;
CREATE ROLE aliasModifier IF NOT EXISTS;
CREATE ROLE aliasViewer IF NOT EXISTS;
CREATE ROLE aliasManager IF NOT EXISTS;
CREATE ROLE privilegeViewer IF NOT EXISTS;
CREATE ROLE privilegeAssigner IF NOT EXISTS;
CREATE ROLE privilegeRemover IF NOT EXISTS;
CREATE ROLE privilegeManager IF NOT EXISTS;
CREATE ROLE procedureExecutor IF NOT EXISTS;
CREATE ROLE deniedProcedureExecutor IF NOT EXISTS;
CREATE ROLE boostedProcedureExecutor IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor1 IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor2 IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor3 IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor4 IF NOT EXISTS;
CREATE ROLE adminProcedureExecutor IF NOT EXISTS;
CREATE ROLE functionExecutor IF NOT EXISTS;
CREATE ROLE deniedFunctionExecutor IF NOT EXISTS;
CREATE ROLE boostedFunctionExecutor IF NOT EXISTS;
CREATE ROLE globbing1 IF NOT EXISTS;
CREATE ROLE globbing2 IF NOT EXISTS;
CREATE ROLE globbing3 IF NOT EXISTS;
CREATE ROLE globbing4 IF NOT EXISTS;
CREATE ROLE globbing5 IF NOT EXISTS;
CREATE ROLE globbing6 IF NOT EXISTS;
CREATE ROLE dbmsManager IF NOT EXISTS;
CREATE ROLE configurationViewer IF NOT EXISTS;
CREATE ROLE deniedConfigurationViewer IF NOT EXISTS;
CREATE ROLE serverManager IF NOT EXISTS;
CREATE ROLE serverViewer IF NOT EXISTS;
----
////

The DBMS privileges for privilege management can be granted, denied, or revoked like other privileges.

[NOTE]
====
For more details about the syntax descriptions, see xref:database-administration/syntax.adoc#administration-syntax-reading[Reading the administration commands syntax].
====

.Privilege management privileges command syntax
[options="header", width="100%", cols="3a,2"]
|===
| Command | Description

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] SHOW PRIVILEGE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to list privileges.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] ASSIGN PRIVILEGE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to assign privileges using the `GRANT` and `DENY` commands.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] REMOVE PRIVILEGE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to remove privileges using the `REVOKE` command.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] PRIVILEGE MANAGEMENT
  ON DBMS
  TO role[, ...]
| Enables the specified roles to list, assign, and remove privileges.
|===

=== Grant privilege to list privileges

You can grant the `SHOW PRIVILEGE` privilege to allow a user to list privileges using the `SHOW PRIVILEGE`, `SHOW ROLE roleName PRIVILEGES`, and `SHOW USER username PRIVILEGES` administration commands.
The `SHOW USER username PRIVILEGES` command also requires the `SHOW USER` privilege.

For example:

[source, cypher, role=noplay]
----
GRANT SHOW PRIVILEGE ON DBMS TO privilegeViewer;
----

As a result, the `privilegeViewer` role has privileges that only allow showing privileges.
To list all privileges for the role `privilegeViewer` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE privilegeViewer PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT SHOW PRIVILEGE ON DBMS TO `privilegeViewer`"
a|Rows: 1
|===

[NOTE]
====
No specific privileges are required for showing the current user's privileges through the `SHOW USER _username_ PRIVILEGES` or `SHOW USER PRIVILEGES` commands.

If a non-native auth provider like LDAP is in use, `SHOW USER PRIVILEGES` will only work with a limited capacity by making it only possible for a user to show their own privileges.
Other users' privileges cannot be listed when using a non-native auth provider.
====

=== Grant privilege to assign privileges

You can grant the privilege to assign privileges using the `ASSIGN PRIVILEGE` privilege. +
A user with this privilege is allowed to execute `GRANT` and `DENY` administration commands. +
For example:

[source, cypher, role=noplay]
----
GRANT ASSIGN PRIVILEGE ON DBMS TO privilegeAssigner;
----

As a result, the `privilegeAssigner` role has privileges that only allow assigning privileges.
To list all privileges for the role `privilegeAssigner` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE privilegeAssigner PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT ASSIGN PRIVILEGE ON DBMS TO `privilegeAssigner`"
a|Rows: 1
|===

=== Grant privilege to remove privileges

You can grant the privilege to remove privileges from roles using the `REMOVE PRIVILEGE` privilege. +
A user with this privilege is allowed to execute `REVOKE` administration commands. +
For example:

[source, cypher, role=noplay]
----
GRANT REMOVE PRIVILEGE ON DBMS TO privilegeRemover;
----

As a result, the `privilegeRemover` role has privileges that only allow removing privileges.
To list all privileges for the role `privilegeRemover` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE privilegeRemover PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT REMOVE PRIVILEGE ON DBMS TO `privilegeRemover`"
a|Rows: 1
|===

=== Grant privilege to manage privileges

You can grant the privilege to list, assign, and remove privileges using the `PRIVILEGE MANAGEMENT` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT PRIVILEGE MANAGEMENT ON DBMS TO privilegeManager;
----

As a result, the `privilegeManager` role has all privileges to manage privileges.
To list all privileges for the role `privilegeManager` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE privilegeManager PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT PRIVILEGE MANAGEMENT ON DBMS TO `privilegeManager`"
a|Rows: 1
|===
