:description: Details the DBMS privileges for alias management.
:page-role: enterprise-edition aura-db-business-critical aura-db-dedicated
[[dbms-alias-management-privileges]]
= The DBMS `ALIAS MANAGEMENT` privileges
////
[source, cypher, role=test-setup]
----
CREATE USER jake SET PASSWORD 'abcd1234' CHANGE NOT REQUIRED;
CREATE ROLE roleAdder IF NOT EXISTS;
CREATE ROLE roleNameModifier IF NOT EXISTS;
CREATE ROLE roleDropper IF NOT EXISTS;
CREATE ROLE roleAssigner IF NOT EXISTS;
CREATE ROLE roleRemover IF NOT EXISTS;
CREATE ROLE roleViewer IF NOT EXISTS;
CREATE ROLE roleManager IF NOT EXISTS;
CREATE ROLE userAdder IF NOT EXISTS;
CREATE ROLE userNameModifier IF NOT EXISTS;
CREATE ROLE userModifier IF NOT EXISTS;
CREATE ROLE userDropper IF NOT EXISTS;
CREATE ROLE userViewer IF NOT EXISTS;
CREATE ROLE userManager IF NOT EXISTS;
CREATE ROLE userImpersonator IF NOT EXISTS;
CREATE ROLE allUserImpersonator IF NOT EXISTS;
CREATE ROLE authModifier IF NOT EXISTS;
CREATE ROLE passwordModifier IF NOT EXISTS;
CREATE ROLE statusModifier IF NOT EXISTS;
CREATE ROLE homeDbModifier IF NOT EXISTS;
CREATE ROLE databaseAdder IF NOT EXISTS;
CREATE ROLE compositeDatabaseAdder IF NOT EXISTS;
CREATE ROLE databaseDropper IF NOT EXISTS;
CREATE ROLE compositeDatabaseDropper IF NOT EXISTS;
CREATE ROLE databaseModifier IF NOT EXISTS;
CREATE ROLE accessModifier IF NOT EXISTS;
CREATE ROLE languageModifier IF NOT EXISTS;
CREATE ROLE compositeDatabaseModifier IF NOT EXISTS;
CREATE ROLE compositeDatabaseManager IF NOT EXISTS;
CREATE ROLE databaseManager IF NOT EXISTS;
CREATE ROLE aliasAdder IF NOT EXISTS;
CREATE ROLE aliasDropper IF NOT EXISTS;
CREATE ROLE aliasModifier IF NOT EXISTS;
CREATE ROLE aliasViewer IF NOT EXISTS;
CREATE ROLE aliasManager IF NOT EXISTS;
CREATE ROLE privilegeViewer IF NOT EXISTS;
CREATE ROLE privilegeAssigner IF NOT EXISTS;
CREATE ROLE privilegeRemover IF NOT EXISTS;
CREATE ROLE privilegeManager IF NOT EXISTS;
CREATE ROLE procedureExecutor IF NOT EXISTS;
CREATE ROLE deniedProcedureExecutor IF NOT EXISTS;
CREATE ROLE boostedProcedureExecutor IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor1 IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor2 IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor3 IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor4 IF NOT EXISTS;
CREATE ROLE adminProcedureExecutor IF NOT EXISTS;
CREATE ROLE functionExecutor IF NOT EXISTS;
CREATE ROLE deniedFunctionExecutor IF NOT EXISTS;
CREATE ROLE boostedFunctionExecutor IF NOT EXISTS;
CREATE ROLE globbing1 IF NOT EXISTS;
CREATE ROLE globbing2 IF NOT EXISTS;
CREATE ROLE globbing3 IF NOT EXISTS;
CREATE ROLE globbing4 IF NOT EXISTS;
CREATE ROLE globbing5 IF NOT EXISTS;
CREATE ROLE globbing6 IF NOT EXISTS;
CREATE ROLE dbmsManager IF NOT EXISTS;
CREATE ROLE configurationViewer IF NOT EXISTS;
CREATE ROLE deniedConfigurationViewer IF NOT EXISTS;
CREATE ROLE serverManager IF NOT EXISTS;
CREATE ROLE serverViewer IF NOT EXISTS;
----
////

The DBMS privileges for alias management can be granted, denied, or revoked like other privileges.
This applies to both local and remote aliases.

[NOTE]
====
For more details about the syntax descriptions, see xref:database-administration/syntax.adoc#administration-syntax-reading[Reading the administration commands syntax].
====

.Alias management privileges command syntax
[options="header", width="100%", cols="3a,2"]
|===
| Command | Description

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] CREATE ALIAS
ON DBMS
TO role[, ...]
| Enables the specified roles to create new aliases.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] DROP ALIAS
ON DBMS
TO role[, ...]
| Enables the specified roles to delete aliases.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] ALTER ALIAS
ON DBMS
TO role[, ...]
| Enables the specified roles to modify aliases.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] SHOW ALIAS
ON DBMS
TO role[, ...]
| Enables the specified roles to list aliases.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] ALIAS MANAGEMENT
ON DBMS
TO role[, ...]
| Enables the specified roles to list, create, delete, and modify aliases.

|===

== Grant privilege to create aliases

You can grant the privilege to create aliases using the `CREATE ALIAS` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT CREATE ALIAS ON DBMS TO aliasAdder;
----

As a result, the `aliasAdder` role has privileges that only allow creating aliases.
To list all privileges for the role `aliasAdder` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE aliasAdder PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT CREATE ALIAS ON DBMS TO `aliasAdder`"
a|Rows: 1
|===

== Grant privilege to delete aliases

You can grant the privilege to delete aliases using the `DROP ALIAS` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT DROP ALIAS ON DBMS TO aliasDropper;
----

As a result, the `aliasDropper` role has privileges that only allow deleting aliases.
See all privileges for the role `aliasDropper` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE aliasDropper PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT DROP ALIAS ON DBMS TO `aliasDropper`"
a|Rows: 1
|===

== Grant privilege to modify aliases

You can grant the privilege to modify aliases using the `ALTER ALIAS` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT ALTER ALIAS ON DBMS TO aliasModifier;
----

As a result, the `aliasModifier` role has privileges that only allow modifying aliases.
To list all privileges for the role `aliasModifier` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE aliasModifier PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT ALTER ALIAS ON DBMS TO `aliasModifier`"
a|Rows: 1
|===


== Grant privilege to list aliases

You can grant the privilege to list aliases using the `SHOW ALIAS` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT SHOW ALIAS ON DBMS TO aliasViewer;
----

As a result, the `aliasViewer` role has privileges that only allow modifying aliases.
To list all privileges for the role `aliasViewer` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE aliasViewer PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT SHOW ALIAS ON DBMS TO `aliasViewer`"
a|Rows: 1
|===

== Grant privilege to manage aliases

You can grant the privilege to create, delete, modify, and list aliases using the `ALIAS MANAGEMENT` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT ALIAS MANAGEMENT ON DBMS TO aliasManager;
----

As a result, the `aliasManager` role has all privileges to manage aliases.
To list all privileges for the role `aliasManager` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE aliasManager PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT ALIAS MANAGEMENT ON DBMS TO `aliasManager`"
a|Rows: 1
|===