:description: Details the DBMS privileges for server management.
:page-role: enterprise-edition aura-db-business-critical aura-db-dedicated
[[dbms-server-management-privileges]]
= DBMS `SERVER MANAGEMENT` privileges

////
[source, cypher, role=test-setup]
----
CREATE ROLE serverManager IF NOT EXISTS;
CREATE ROLE serverViewer IF NOT EXISTS;
----
////

The DBMS privileges for server management can be granted, denied, or revoked like other privileges.

[NOTE]
====
For more details about the syntax descriptions, see xref:database-administration/syntax.adoc#administration-syntax-reading[Reading the administration commands syntax].
====

.Server management privileges command syntax
[options="header", width="100%", cols="3a,2"]
|===
| Command | Description

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] SERVER MANAGEMENT
  ON DBMS
  TO role[, ...]
| Enables the specified roles to show, enable, rename, alter, reallocate, deallocate, and drop servers.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] SHOW SERVERS
  ON DBMS
  TO role[, ...]
| Enables the specified roles to show servers.
|===

== Grant privilege to manage servers

You can grant the privilege to show, enable, rename, alter, reallocate, deallocate, and drop servers using the `SERVER MANAGEMENT` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT SERVER MANAGEMENT ON DBMS TO serverManager;
----

As a result, the `serverManager` role has all privileges to manage servers.
To show all privileges for the role `serverManager` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE serverManager PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT SERVER MANAGEMENT ON DBMS TO `serverManager`"
a|Rows: 1
|===


== Grant privilege to show servers

You can grant the privilege to show servers using the `SHOW SERVERS` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT SHOW SERVERS ON DBMS TO serverViewer;
----

As a result, the `serverViewer` role has privileges that only allow showing servers.
To show all privileges for the role `serverViewer` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE serverViewer PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT SHOW SERVERS ON DBMS TO `serverViewer`"
a|Rows: 1
|===