:description: Details the DBMS privileges for role management.
:page-role: enterprise-edition aura-db-business-critical aura-db-dedicated
[[dbms-role-management-privileges]]
= DBMS `ROLE MANAGEMENT` privileges

////
[source, cypher, role=test-setup]
----
CREATE ROLE roleAdder IF NOT EXISTS;
CREATE ROLE roleNameModifier IF NOT EXISTS;
CREATE ROLE roleDropper IF NOT EXISTS;
CREATE ROLE roleAssigner IF NOT EXISTS;
CREATE ROLE roleRemover IF NOT EXISTS;
CREATE ROLE roleViewer IF NOT EXISTS;
CREATE ROLE roleManager IF NOT EXISTS;
----
////

The DBMS privileges for role management can be granted, denied, or revoked like other privileges.

[NOTE]
====
For more details about the syntax descriptions, see xref:database-administration/syntax.adoc#administration-syntax-reading[Reading the administration commands syntax].
====

.Role management privileges command syntax
[options="header", width="100%", cols="3a,2"]
|===
| Command | Description

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] CREATE ROLE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to create new roles.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] RENAME ROLE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to change the name of roles.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] DROP ROLE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to delete roles.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] ASSIGN ROLE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to assign roles to users.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] REMOVE ROLE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to remove roles from users.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] SHOW ROLE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to list roles.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] ROLE MANAGEMENT
  ON DBMS
  TO role[, ...]
| Enables the specified roles to create, delete, assign, remove, and list roles.

|===

== Grant privilege to create roles

You can grant the privilege to add roles using the `CREATE ROLE` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT CREATE ROLE ON DBMS TO roleAdder;
----

As a result, the `roleAdder` role has privileges that only allow adding roles.

To show all privileges for the role `roleAdder` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE roleAdder PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT CREATE ROLE ON DBMS TO `roleAdder`"
a|Rows: 1
|===

== Grant privilege to rename roles

You can grant the privilege to rename roles using the `RENAME ROLE` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT RENAME ROLE ON DBMS TO roleNameModifier;
----

As a result, the `roleNameModifier` role has privileges that only allow renaming roles.

To show all privileges for the role `roleNameModifier`, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE roleNameModifier PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT RENAME ROLE ON DBMS TO `roleNameModifier`"
a|Rows: 1
|===

== Grant privilege to delete roles

You can grant the privilege to delete roles using the `DROP ROLE` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT DROP ROLE ON DBMS TO roleDropper;
----

As a result, the `roleDropper` role has privileges that only allow deleting roles.

To show all privileges for the role `roleDropper`, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE roleDropper PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT DROP ROLE ON DBMS TO `roleDropper`"
a|Rows: 1
|===

[[access-control-dbms-administration-role-assignment]]
== Grant privilege to assign roles

You can grant the privilege to assign roles to users or auth rules using the `ASSIGN ROLE` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT ASSIGN ROLE ON DBMS TO roleAssigner;
----

As a result, the `roleAssigner` role has privileges that only allow assigning/granting roles.

To show all privileges for the role `roleAssigner` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE roleAssigner PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT ASSIGN ROLE ON DBMS TO `roleAssigner`"
a|Rows: 1
|===

[[access-control-dbms-administration-role-removal]]
== Grant privilege to remove roles

You can grant the privilege to remove roles from users or auth rules using the `REMOVE ROLE` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT REMOVE ROLE ON DBMS TO roleRemover;
----

As a result, the `roleRemover` role has privileges that only allow removing/revoking roles.

To show all privileges for the role `roleRemover` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE roleRemover PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT REMOVE ROLE ON DBMS TO `roleRemover`"
a|Rows: 1
|===

== Grant privilege to show roles

You can grant the privilege to show roles using the `SHOW ROLE` privilege.
A role with this privilege is allowed to execute the `SHOW ROLES` and `SHOW POPULATED ROLES` administration commands.

[NOTE]
====
In order to use `SHOW ROLES WITH USERS` and `SHOW POPULATED ROLES WITH USERS` administration commands, both the `SHOW ROLE` and the `SHOW USER` privileges are required.
====

[role=label--new-2026.03]
[NOTE]
====
In order to use the `SHOW ROLES WITH AUTH RULES` administration command, both the `SHOW ROLE` and the `SHOW AUTH RULE` privileges are required.
====

The following query shows an example of how to grant the `SHOW ROLE` privilege:

[source, cypher, role=noplay]
----
GRANT SHOW ROLE ON DBMS TO roleViewer;
----

As a result, the `roleViewer` role has privileges that only allow showing roles.

To show all privileges for the role `roleViewer` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE roleViewer PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT SHOW ROLE ON DBMS TO `roleViewer`"
a|Rows: 1
|===

== Grant privilege to manage roles

You can grant the privilege to create, rename, delete, assign, remove, and list roles using the `ROLE MANAGEMENT` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT ROLE MANAGEMENT ON DBMS TO roleManager;
----

As a result, the `roleManager` role has all privileges to manage roles.

To show all privileges for the role `roleManager` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE roleManager PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT ROLE MANAGEMENT ON DBMS TO `roleManager`"
a|Rows: 1
|===