:description: Details the DBMS privileges for auth rule management.
:page-role: enterprise-edition aura-db-business-critical aura-db-dedicated
[[dbms-auth-rule-management-privileges]]
= The DBMS `AUTH RULE MANAGEMENT` privileges

////
[source, cypher, role=test-setup]
----
CREATE ROLE authRuleManager IF NOT EXISTS;
CREATE ROLE authRuleAdder IF NOT EXISTS;
CREATE ROLE authRuleNameModifier IF NOT EXISTS;
CREATE ROLE authRuleAlterer IF NOT EXISTS;
CREATE ROLE authRuleDropper IF NOT EXISTS;
CREATE ROLE authRuleViewer IF NOT EXISTS;
----
////

The DBMS privileges for auth rule management can be granted, denied, or revoked like other privileges.

[NOTE]
====
For more details about the syntax descriptions, see xref:database-administration/syntax.adoc#administration-syntax-reading[Reading the administration commands syntax].
====

.Auth rule management privileges command syntax
[options="header", width="100%", cols="3a,2"]
|===
| Command | Description

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] CREATE AUTH RULE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to create new auth rules.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] RENAME AUTH RULE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to change the name of auth rules.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] ALTER AUTH RULE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to alter auth rules. Either by setting their `ENABLED` status or by setting their `CONDITION`.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] DROP AUTH RULE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to delete auth rules.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] SHOW AUTH RULE
  ON DBMS
  TO role[, ...]
| Enables the specified roles to show auth rules.

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] AUTH RULE MANAGEMENT
  ON DBMS
  TO role[, ...]
| Enables the specified roles to create, alter, rename, show, and delete auth rules.

|===

[[grant-create-auth-rule-privilege]]
== Grant privilege to create auth rules

You can grant the privilege to add auth rules using the `CREATE AUTH RULE` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT CREATE AUTH RULE ON DBMS TO authRuleAdder;
----

As a result, the `authRuleAdder` role has privileges that allow adding auth rules.
To list all privileges for the role `authRuleAdder` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE authRuleAdder PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT CREATE authRuleAdder ON DBMS TO `authRuleAdder`"
a|Rows: 1
|===

[[grant-rename-auth-rule-privilege]]
== Grant privilege to rename auth rules

You can grant the privilege to rename auth rules using the `RENAME AUTH RULE` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT RENAME AUTH RULE ON DBMS TO authRuleNameModifier;
----

As a result, the `authRuleNameModifier` role has privileges that allow renaming auth rules.
To list all privileges for the role `authRuleNameModifier`, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE authRuleNameModifier PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT RENAME AUTH RULE ON DBMS TO `authRuleNameModifier`"
a|Rows: 1
|===

[[grant-alter-auth-rule-privilege]]
== Grant privilege to alter auth rules

You can grant the privilege to alter auth rules using the `ALTER AUTH RULE` privilege.  This privilege allows users to alter the auth rule either by setting its `ENABLED` status or by setting its `CONDITION` +
For example:

[source, cypher, role=noplay]
----
GRANT ALTER AUTH RULE ON DBMS TO authRuleAlterer;
----

As a result, the `authRuleAlterer` role has privileges that allow altering auth rules.
To list all privileges for the role `authRuleAlterer`, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE authRuleAlterer PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT ALTER AUTH RULE ON DBMS TO `authRuleAlterer`"
a|Rows: 1
|===

[[grant-drop-auth-rule-privilege]]
== Grant privilege to delete auth rules

You can grant the privilege to delete auth rules using the `DROP AUTH RULE` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT DROP AUTH RULE ON DBMS TO authRuleDropper;
----

As a result, the `authRuleDropper` role has privileges that allow deleting auth rules.
To list all privileges for the role `authRuleDropper`, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE authRuleDropper PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT DROP AUTH RULE ON DBMS TO `authRuleDropper`"
a|Rows: 1
|===

[[grant-show-auth-rule-privilege]]
== Grant privilege to show auth rules

You can grant the privilege to show auth rules using the `SHOW AUTH RULE` privilege.
A role with this privilege is allowed to execute the `SHOW AUTH RULES` administration commands.

The following query shows an example of how to grant the `SHOW AUTH RULE` privilege:

[source, cypher, role=noplay]
----
GRANT SHOW AUTH RULE ON DBMS TO authRuleViewer;
----

As a result, the `authRuleViewer` role has privileges that allow showing auth rules.
To list all privileges for the role `authRuleViewer` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE authRuleViewer PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT SHOW AUTH RULE ON DBMS TO `authRuleViewer`"
a|Rows: 1
|===

== Grant privilege to manage auth rules

You can grant the privilege to create, alter, rename, show, and delete auth rules using the `AUTH RULE MANAGEMENT` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT AUTH RULE MANAGEMENT ON DBMS TO authRuleManager;
----

As a result, the `authRuleManager` role has all privileges to manage auth rules.
To list all privileges for the role `authRuleManager` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE authRuleManager PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT AUTH RULE MANAGEMENT ON DBMS TO `authRuleManager`"
a|Rows: 1
|===