:description: Details the DBMS privileges for auth rule management.
:page-role: enterprise-edition aura-db-business-critical aura-db-dedicated
[[dbms-auth-rule-management-privileges]]
= The DBMS `AUTH RULE MANAGEMENT` privileges

////
[source, cypher, role=test-setup]
----
CREATE ROLE authRuleManager IF NOT EXISTS;
----
////

The DBMS privileges for auth rule management can be granted, denied, or revoked like other privileges.

[NOTE]
====
For more details about the syntax descriptions, see xref:database-administration/syntax.adoc#administration-syntax-reading[Reading the administration commands syntax].
====

.Auth rule management privileges command syntax
[options="header", width="100%", cols="3a,2"]
|===
| Command | Description

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] AUTH RULE MANAGEMENT
  ON DBMS
  TO role[, ...]
| Enables the specified roles to create, show, and delete auth rules.

|===

== Grant privilege to manage auth rules

You can grant the privilege to create, show, and delete auth rules using the `AUTH RULE MANAGEMENT` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT AUTH RULE MANAGEMENT ON DBMS TO authRuleManager;
----

As a result, the `authRuleManager` role has all privileges to manage auth rules.
To list all privileges for the role `authRuleManager` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE authRuleManager PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT AUTH RULE MANAGEMENT ON DBMS TO `authRuleManager`"
a|Rows: 1
|===