:description: Details the DBMS privileges for viewing configuration settings.
:page-role: enterprise-edition aura-db-business-critical aura-db-dedicated
[[dbms-setting-privileges]]
= DBMS `SETTING` privileges

////
[source, cypher, role=test-setup]
----
CREATE ROLE configurationViewer IF NOT EXISTS;
CREATE ROLE deniedConfigurationViewer IF NOT EXISTS;
----
////

You can grant the privilege to show configuration settings using the `SHOW SETTING` privilege.
A role with this privilege is allowed to show the configuration settings matched by the xref:authentication-authorization/dbms-administration/index.adoc#access-control-name-globbing[name-globbing].

[NOTE]
====
For more details about the syntax descriptions, see xref:database-administration/syntax.adoc#administration-syntax-reading[Reading the administration commands syntax].
====

.Setting privileges command syntax
[options="header", width="100%", cols="3a,2"]
|===
| Command
| Description

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] SHOW SETTING[S] name-globbing[, ...]
  ON DBMS
  TO role[, ...]
| Enables the specified roles to list given configuration settings.
|===

== Grant privilege to show all settings

You can grant the privilege to show all settings using `SHOW SETTING \*` or all settings in a namespace using `SHOW SETTING namespace.*`.
The following query shows an example of how to grant `SHOW SETTING` privilege to view all settings in the `server.bolt` namespace:

[source, cypher, role=noplay]
----
GRANT SHOW SETTING server.bolt.* ON DBMS TO configurationViewer;
----

Users with the role `configurationViewer` can then view any setting in the `server.bolt` namespace.

As a result, the `configurationViewer` role has privileges that only allow showing settings in the `server.bolt` namespace.
To show all privileges for the role `configurationViewer` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE configurationViewer PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT SHOW SETTING server.bolt.* ON DBMS TO `configurationViewer`"
a|Rows: 1
|===

== Grant privilege to show all but some settings

You can grant the privilege to show all but a few settings using `SHOW SETTINGS *` and deny the unwanted settings. +
For example, the following queries allow you to view all settings, except those starting with `dbms.security`:

[source, cypher, role=noplay]
----
GRANT SHOW SETTINGS * ON DBMS TO deniedConfigurationViewer;
----

[source, cypher, role=noplay]
----
DENY SHOW SETTING dbms.security* ON DBMS TO deniedConfigurationViewer;
----

As a result, the `deniedConfigurationViewer` role has privileges that allow showing all settings except those starting with `dbms.security`.
To show all privileges for the role `deniedConfigurationViewer` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE deniedConfigurationViewer PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"DENY SHOW SETTING dbms.security* ON DBMS TO `deniedConfigurationViewer`"
|"GRANT SHOW SETTING * ON DBMS TO `deniedConfigurationViewer`"
a|Rows: 2
|===

As the query result shows, viewing settings starting with `dbms.security` is blocked, but the rest can still be shown.