:description: Details the DBMS privileges for auth rule management.
:page-role: enterprise-edition aura-db-business-critical aura-db-dedicated
[[dbms-auth-rule-management-privileges]]
= The DBMS `AUTH RULE MANAGEMENT` privileges

////
[source, cypher, role=test-setup]
----
CREATE USER jake SET PASSWORD 'abcd1234' CHANGE NOT REQUIRED;
CREATE ROLE roleAdder IF NOT EXISTS;
CREATE ROLE roleNameModifier IF NOT EXISTS;
CREATE ROLE roleDropper IF NOT EXISTS;
CREATE ROLE roleAssigner IF NOT EXISTS;
CREATE ROLE roleRemover IF NOT EXISTS;
CREATE ROLE roleViewer IF NOT EXISTS;
CREATE ROLE roleManager IF NOT EXISTS;
CREATE ROLE userAdder IF NOT EXISTS;
CREATE ROLE userNameModifier IF NOT EXISTS;
CREATE ROLE userModifier IF NOT EXISTS;
CREATE ROLE userDropper IF NOT EXISTS;
CREATE ROLE userViewer IF NOT EXISTS;
CREATE ROLE userManager IF NOT EXISTS;
CREATE ROLE userImpersonator IF NOT EXISTS;
CREATE ROLE allUserImpersonator IF NOT EXISTS;
CREATE ROLE authModifier IF NOT EXISTS;
CREATE ROLE passwordModifier IF NOT EXISTS;
CREATE ROLE statusModifier IF NOT EXISTS;
CREATE ROLE homeDbModifier IF NOT EXISTS;
CREATE ROLE databaseAdder IF NOT EXISTS;
CREATE ROLE compositeDatabaseAdder IF NOT EXISTS;
CREATE ROLE databaseDropper IF NOT EXISTS;
CREATE ROLE compositeDatabaseDropper IF NOT EXISTS;
CREATE ROLE databaseModifier IF NOT EXISTS;
CREATE ROLE accessModifier IF NOT EXISTS;
CREATE ROLE languageModifier IF NOT EXISTS;
CREATE ROLE compositeDatabaseModifier IF NOT EXISTS;
CREATE ROLE compositeDatabaseManager IF NOT EXISTS;
CREATE ROLE databaseManager IF NOT EXISTS;
CREATE ROLE aliasAdder IF NOT EXISTS;
CREATE ROLE aliasDropper IF NOT EXISTS;
CREATE ROLE aliasModifier IF NOT EXISTS;
CREATE ROLE aliasViewer IF NOT EXISTS;
CREATE ROLE aliasManager IF NOT EXISTS;
CREATE ROLE privilegeViewer IF NOT EXISTS;
CREATE ROLE privilegeAssigner IF NOT EXISTS;
CREATE ROLE privilegeRemover IF NOT EXISTS;
CREATE ROLE privilegeManager IF NOT EXISTS;
CREATE ROLE procedureExecutor IF NOT EXISTS;
CREATE ROLE deniedProcedureExecutor IF NOT EXISTS;
CREATE ROLE boostedProcedureExecutor IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor1 IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor2 IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor3 IF NOT EXISTS;
CREATE ROLE deniedBoostedProcedureExecutor4 IF NOT EXISTS;
CREATE ROLE adminProcedureExecutor IF NOT EXISTS;
CREATE ROLE functionExecutor IF NOT EXISTS;
CREATE ROLE deniedFunctionExecutor IF NOT EXISTS;
CREATE ROLE boostedFunctionExecutor IF NOT EXISTS;
CREATE ROLE globbing1 IF NOT EXISTS;
CREATE ROLE globbing2 IF NOT EXISTS;
CREATE ROLE globbing3 IF NOT EXISTS;
CREATE ROLE globbing4 IF NOT EXISTS;
CREATE ROLE globbing5 IF NOT EXISTS;
CREATE ROLE globbing6 IF NOT EXISTS;
CREATE ROLE dbmsManager IF NOT EXISTS;
CREATE ROLE configurationViewer IF NOT EXISTS;
CREATE ROLE deniedConfigurationViewer IF NOT EXISTS;
CREATE ROLE serverManager IF NOT EXISTS;
CREATE ROLE serverViewer IF NOT EXISTS;
----
////

The DBMS privileges for auth rule management can be granted, denied, or revoked like other privileges.

[NOTE]
====
For more details about the syntax descriptions, see xref:database-administration/syntax.adoc#administration-syntax-reading[Reading the administration commands syntax].
====

.Auth rule management privileges command syntax
[options="header", width="100%", cols="3a,2"]
|===
| Command | Description

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] AUTH RULE MANAGEMENT
  ON DBMS
  TO role[, ...]
| Enables the specified roles to create and delete auth rules.

|===

== Grant privilege to manage auth rules

You can grant the privilege to create and delete auth rules using the `AUTH RULE MANAGEMENT` privilege. +
For example:

[source, cypher, role=noplay]
----
GRANT AUTH RULE MANAGEMENT ON DBMS TO authRuleManager;
----

As a result, the `authRuleManager` role has all privileges to manage auth rules.
To list all privileges for the role `authRuleManager` as commands, use the following query:

[source, cypher, role=noplay]
----
SHOW ROLE authRuleManager PRIVILEGES AS COMMANDS;
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT AUTH RULE MANAGEMENT ON DBMS TO `authRuleManager`"
a|Rows: 1
|===