= Neo4j composite database
:description: This tutorial describes how to create databases for the composite and how to configure them.

Composite databases allow queries that access multiple graphs at once.
This is a function that enables:

* *Data Federation*: the ability to access data available in distributed sources in the form of *disjointed graphs*.
* *Data Sharding*: the ability to access data available in distributed sources in the form of a *common graph partitioned on multiple databases*.

In this tutorial, you will learn how to:

* <<tutorial-composite-database-create, Create databases for the composite>>
* <<tutorial-composite-database-config, Configure a composite database>>


[[tutorial-composite-database-create]]
== Create databases for the composite
You need three databases: `db0` for the Product catalog, `db1` for the EU customer data, and `db2` for the AME customers.

. Start the Neo4j DBMS:
+
[source, shell, role=noplay]
----
bin/neo4j start
----
. Check all available databases:
+
[source, shell, role=noplay]
----
ls -al /data/databases/
----
+
[queryresult]
----
total 0
drwxr-xr-x@  5 username  staff   160  9 Jun 12:53 .
drwxr-xr-x@  5 username  staff   160  9 Jun 12:53 ..
drwxr-xr-x  37 username  staff  1184  9 Jun 12:53 neo4j
-rw-r--r--   1 username  staff     0  9 Jun 12:53 store_lock
drwxr-xr-x  38 username  staff  1216  9 Jun 12:53 system
----
. Connect to the Neo4j DBMS using `cypher-shell` with the default credentials and change the password when prompted.
+
[source, shell, role=noplay]
----
bin/cypher-shell -u neo4j -p neo4j
----
+
[queryresult]
----
Password change required
new password: *****
Connected to Neo4j 4.1.x at neo4j://localhost:7687 as user neo4j.
Type :help for a list of available commands or :exit to exit the shell.
Note that Cypher queries must end with a semicolon.
----
+
[NOTE]
====
For more information about the Cypher Shell command-line interface (CLI) and how to use it, see <<cypher-shell>>.
====
. Run the command `SHOW DATABASES` to list all available databases:
+
[source, cypher, role=noplay]
----
SHOW DATABASES;
----
+
[queryresult]
----
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| name     | type       | aliases | access       | address          | role      | writer | requestedStatus | currentStatus | statusMessage | default | home  | constituents |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "neo4j"  | "standard" | []      | "read-write" | "localhost:7687" | "primary" | TRUE   | "online"        | "online"      | ""            | TRUE    | TRUE  | []           |
| "system" | "system"   | []      | "read-write" | "localhost:7687" | "primary" | TRUE   | "online"        | "online"      | ""            | FALSE   | FALSE | []           |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
2 rows available after 102 ms, consumed after another 11 ms
----
. Run the command `CREATE DATABASE <database-name>` to create the databases:
+
[source, cypher, role=noplay]
----
CREATE DATABASE db0;
----
+
[queryresult]
----
0 rows available after 137 ms, consumed after another 0 ms
----
+
[source, cypher, role=noplay]
----
CREATE DATABASE db1;
----
+
[queryresult]
----
0 rows available after 141 ms, consumed after another 0 ms
----
+
[source, cypher, role=noplay]
----
CREATE DATABASE db2;
----
+
[queryresult]
----
0 rows available after 135 ms, consumed after another 0 ms
----
+
. Run the command `SHOW DATABASES` again to verify that the new databases have been created and are `online`:
+
[source, cypher, role=noplay]
----
SHOW DATABASES;
----
+
[queryresult]
----
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| name     | type       | aliases | access       | address          | role      | writer | requestedStatus | currentStatus | statusMessage | default | home  | constituents |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "db0"    | "standard" | []      | "read-write" | "localhost:7687" | "primary" | TRUE   | "online"        | "online"      | ""            | FALSE   | FALSE | []           |
| "db1"    | "standard" | []      | "read-write" | "localhost:7687" | "primary" | TRUE   | "online"        | "online"      | ""            | FALSE   | FALSE | []           |
| "db2"    | "standard" | []      | "read-write" | "localhost:7687" | "primary" | TRUE   | "online"        | "online"      | ""            | FALSE   | FALSE | []           |
| "neo4j"  | "standard" | []      | "read-write" | "localhost:7687" | "primary" | TRUE   | "online"        | "online"      | ""            | TRUE    | TRUE  | []           |
| "system" | "system"   | []      | "read-write" | "localhost:7687" | "primary" | TRUE   | "online"        | "online"      | ""            | FALSE   | FALSE | []           |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
5 rows available after 8 ms, consumed after another 7 ms
----

[[tutorial-composite-database-config]]
== Configure a composite database
Set up a composite database with the `CREATE COMPOSITE DATABASE` Cypher command and add local database aliases as constituents to the composite database.
In this example, the composite database is called `compositenw`.

. Run the command `CREATE COMPOSITE DATABASE <composite-database-name>` to create the composite database:
+
[source, cypher, role=noplay]
----
CREATE COMPOSITE DATABASE compositenw;
----
+
[queryresult]
----
0 rows available after 137 ms, consumed after another 0 ms
----
. Run the command `CREATE ALIAS <composite-database-name>.<alias-name> FOR DATABASE <database-name>` to create the constituent database aliases:
+
[source, cypher, role=noplay]
----
CREATE ALIAS compositenw.product FOR DATABASE db0;
----
+
[queryresult]
----
0 rows available after 101 ms, consumed after another 0 ms
----
+
[source, cypher, role=noplay]
----
CREATE ALIAS compositenw.customerEU FOR DATABASE db1;
----
+
[queryresult]
----
0 rows available after 107 ms, consumed after another 0 ms
----
+
[source, cypher, role=noplay]
----
CREATE ALIAS compositenw.customerAME FOR DATABASE db2;
----
+
[queryresult]
----
0 rows available after 98 ms, consumed after another 0 ms
----
+
[NOTE]
====
The constituent database aliases in this tutorial are local database aliases (pointing to databases in the same Neo4j DBMS),
but they can just as well be remote database aliases (pointing to databases in another Neo4j DBMS).
====
+
. Run the command `SHOW DATABASES` to verify that the composite database has been configured and is `online`:
+
[source, cypher, role=noplay]
----
SHOW DATABASES;
----
+
[queryresult]
----
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| name          | type        | aliases                     | access       | address          | role      | writer | requestedStatus | currentStatus | statusMessage | default | home  | constituents                                                                 |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "db0"         | "standard"  | ["compositenw.product"]     | "read-write" | "localhost:7687" | "primary" | TRUE   | "online"        | "online"      | ""            | FALSE   | FALSE | []                                                                           |
| "db1"         | "standard"  | ["compositenw.customerEU"]  | "read-write" | "localhost:7687" | "primary" | TRUE   | "online"        | "online"      | ""            | FALSE   | FALSE | []                                                                           |
| "db2"         | "standard"  | ["compositenw.customerAME"] | "read-write" | "localhost:7687" | "primary" | TRUE   | "online"        | "online"      | ""            | FALSE   | FALSE | []                                                                           |
| "compositenw" | "composite" | []                          | "read-only"  | "localhost:7687" | "primary" | FALSE  | "online"        | "online"      | ""            | FALSE   | FALSE | ["compositenw.customerAME", "compositenw.customerEU", "compositenw.product"] |
| "neo4j"       | "standard"  | []                          | "read-write" | "localhost:7687" | "primary" | TRUE   | "online"        | "online"      | ""            | TRUE    | TRUE  | []                                                                           |
| "system"      | "system"    | []                          | "read-write" | "localhost:7687" | "primary" | TRUE   | "online"        | "online"      | ""            | FALSE   | FALSE | []                                                                           |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
6 rows available after 242 ms, consumed after another 18 ms
----
. Run the command `SHOW ALIASES FOR DATABASES` to verify that the database aliases have been configured:
+
[source, cypher, role=noplay]
----
SHOW ALIASES FOR DATABASES;
----
+
[queryresult]
----
+----------------------------------------------------------------+
| name                      | database  | location | url  | user |
+----------------------------------------------------------------+
| "compositenw.product"     | "db0"     | "local"  | null | null |
| "compositenw.customerEU"  | "db1"     | "local"  | null | null |
| "compositenw.customerAME" | "db2"     | "local"  | null | null |
+----------------------------------------------------------------+
3 rows available after 203 ms, consumed after another 16 ms
----