[role=enterprise-edition]
[[tutorial-local-cluster]]
= Set up a local Causal Cluster
:description: This tutorial walks through the basics of setting up a Neo4j Causal Cluster. The result is a local cluster of six instances: three Cores and three Read Replicas.

In this tutorial, you will learn how to deploy a Causal Cluster locally on a single machine.

[NOTE]
====
Keep in mind that a cluster on a single machine has no fault tolerance and is therefore not suitable for production use.
====

A typical Causal Cluster consists of three Core instances and three Read Replicas.
The Core instances are responsible for keeping the data safe, and the Read Replicas are responsible for scaling the capacity of the cluster.
For details on the number of servers required for a Causal Cluster, see xref:clustering/introduction.adoc#clustering-primary-servers[Primary servers].

The Core of the Causal Cluster is intended to remain stable over time.
The roles within the Core may change as needed, but the Core itself is long-lived and stable. +
Read Replicas live at the edge of the cluster and can be brought up and taken down without affecting the Core.
They can be added as needed to increase the operational capacity of the cluster as a whole.

For more information about Causal Clustering architecture, configuration, and operation, see xref:clustering/index.adoc[Clustering].

[[tutorial-local-cluster-download-neo4j]]
== Download Neo4j

You download Neo4j and prepare your local environment.

. Create a local working directory.
. Download a copy of the Neo4j Enterprise Edition from link:https://neo4j.com/deployment-center/[the Neo4j download site].
. Unpack Neo4j in the working directory.

[[tutorial-local-cluster-configure-cores]]
== Set up the Core servers
You create and configure three Core instances.

[discrete]
[[tutorial-local-cluster-configure-core01]]
=== Configure and start the first Core instance

You create and configure the first Core instance.

. Make a copy of the _neo4j-enterprise-{neo4j-version-exact}_ directory and name it _core-01_. +
You have to keep the original directory for setting up the other Core instances and Read Replicas.
The _core-01_ directory will contain the first Core instance.
. Open the Neo4j configuration file, xref:configuration/neo4j-conf.adoc[_conf/neo4j.conf_], and configure the following settings:
+
[TIP]
====
If you cannot find the configuration file, see xref:configuration/file-locations.adoc[File locations].
====
.. Locate and uncomment the setting `dbms.mode=CORE`.
.. Locate and uncomment the setting `causal_clustering.minimum_core_cluster_size_at_formation=3`.
.. Locate and uncomment the setting `causal_clustering.minimum_core_cluster_size_at_runtime=3`.
.. Locate and uncomment the setting `causal_clustering.initial_discovery_members=localhost:5000,localhost:5001,localhost:5002`.
.. Locate and uncomment the setting `causal_clustering.discovery_listen_address=:5000`.
.. Locate and uncomment the setting `causal_clustering.transaction_listen_address=:6000`.
.. Locate and uncomment the setting `causal_clustering.raft_listen_address=:7000`.
.. Locate and uncomment the setting `dbms.connector.bolt.listen_address=:7687`.
.. Locate and uncomment the setting `dbms.connector.http.listen_address=:7474`.
.. Locate and uncomment the setting `dbms.connector.https.listen_address`, and change the value to `:6474`.
.. Locate and uncomment the setting `dbms.backup.listen_address=0.0.0.0:6362`.
. Save the file.
. Open a command-line tool and navigate to _core-01_ directory.
. Run the following command to start _core-01_:
+
[source, shell]
----
core-01$ ./bin/neo4j start
----

[discrete]
[[tutorial-local-cluster-configure-core02]]
=== Create and configure the second Core instance

You create and configure the second Core instance.

. Make a new copy of the _neo4j-enterprise-{neo4j-version-exact}_ directory and name it _core-02_.
. Overwrite _core-02/conf/neo4j.conf_ with the just modified _core-01/conf/neo4j.conf_. Then in the new _core-02_ directory, open
the _conf/neo4j.conf_ file and configure the following settings:
.. Locate the setting `causal_clustering.discovery_listen_address` and change the value to `:5001`.
.. Locate the setting `causal_clustering.transaction_listen_address` and change the value to `:6001`.
.. Locate the setting `causal_clustering.raft_listen_address` and change the value to `:7001`.
.. Locate the setting `dbms.connector.bolt.listen_address` and change the value to `:7688`.
.. Locate the setting `dbms.connector.http.listen_address` and change the value to `:7475`.
.. Locate the setting `dbms.connector.https.listen_address` and change the value to `:6475`.
.. Locate the setting `dbms.backup.listen_address` and change the value to `0.0.0.0:6363`.
. Save the file.
. Open a command-line tool and navigate to _core-02_ directory.
. Run the following command to start _core-02_:
+
[source, shell]
----
core-02$ ./bin/neo4j start
----

[discrete]
[[tutorial-local-cluster-configure-core03]]
=== Create and configure the third Core instance

You create and configure the third Core instance.

. Make a new copy of the _neo4j-enterprise-{neo4j-version-exact}_ directory and name it _core-03_.
. Overwrite _core-03/conf/neo4j.conf_ with the just modified _core-02/conf/neo4j.conf_. Then in the new _core-03_ directory, open
the _conf/neo4j.conf_ file and configure the following settings:
.. Locate the setting `causal_clustering.discovery_listen_address` and change the value to `:5002`.
.. Locate the setting `causal_clustering.transaction_listen_address` and change the value to `:6002`.
.. Locate the setting `causal_clustering.raft_listen_address` and change the value to `:7002`.
.. Locate the setting `dbms.connector.bolt.listen_address` and change the value to `:7689`.
.. Locate the setting `dbms.connector.http.listen_address` and change the value to `:7476`.
.. Locate the setting `dbms.connector.https.listen_address` and change the value to `:6476`.
.. Locate the setting `dbms.backup.listen_address` and change the value to `0.0.0.0:6364`.
. Save the file.
. Open a command-line tool and navigate to _core-03_ directory.
. Run the following command to start _core-03_:
+
[source, shell]
----
core-03$ ./bin/neo4j start
----

[TIP]
.Startup Time
====
To follow along with the startup of a server, check the messages in _<instance-home>/logs/neo4j.log_:

* On a Unix system, run the command `tail -n100 logs/neo4j.log`.
* On Windows Server, run `Get-Content .\logs\neo4j.log -Tail 10 -Wait`.

While an instance is joining the cluster, the server may appear unavailable.
In the case where an instance is joining a cluster with lots of data, it may take a number of minutes for the new instance to download the data from the cluster and become available.
====


[[tutorial-local-cluster-check-status]]
== Check the status of the cluster

The minimal cluster of three Core servers is operational and is ready to serve requests.

Connect to any of the three Core instances to check the cluster status.

. Open _core-01_ at _\http://localhost:7474_.
. Authenticate with the default `neo4j/neo4j` credentials, and set a new password when prompted.
. Check the status of the cluster by running the following in Neo4j Browser:
+
[source, cypher]
----
:sysinfo
----
+
.A cluster of three Core instances.
====
[options="header"]
|===
| Name | Address | Role	| Status | Default | Error
| neo4j	| localhost:7689 | follower | online | true | -
| neo4j	| localhost:7688 | follower | online | true | -
| neo4j	| localhost:7687 | leader | online | true | -
| system	| localhost:7689 | follower | online | - | -
| system	| localhost:7688 | follower | online | - | -
| system	| localhost:7687 | leader` | online | - | -

|===
====
+
. Run the following query to create nodes and relationships.
+
[source, cypher]
----
UNWIND range(0, 100) AS value
MERGE (person1:Person {id: value})
MERGE (person2:Person {id: toInteger(100.0 * rand())})
MERGE (person1)-[:FRIENDS]->(person2)
----
+
. Open a new tab and point your web browser to a follower, for example, _core-02_ at _\http://localhost:7475_.
. Authenticate with the credentials you have set up for _core-01_.
. Run the following query to verify that the data has been replicated:
+
[source, cypher]
----
MATCH path = (person:Person)-[:FRIENDS]-(friend)
RETURN path
LIMIT 10
----


[[tutorial-local-cluster-configure-read-replicas]]
== Set up the Read Replicas

Because the Read Replicas do not participate in quorum decisions, their configuration is simpler than the configuration of the Core servers.

You configure a Read Replica by setting the address of a Core instance that it can bind to in order to discover the cluster.
For details, see xref:clustering-advanced/lifecycle.adoc#causal-clustering-discovery-protocol[Discovery protocol]. +
After the initial discovery, the Read Replicas can choose a Core instance from which to catch up.
For details, see xref:clustering-advanced/lifecycle.adoc#causal-clustering-catchup-protocol[Catchup protocol].

[discrete]
[[tutorial-local-cluster-configure-read-replica01]]
=== Configure and start the first Read Replica

You create and configure the first Read Replica.

. Make a copy of the _neo4j-enterprise-{neo4j-version-exact}_ directory and name it _replica-01_.
. In the new _replica-01_ directory, open the _conf/neo4j.conf_ file and configure the following settings:
.. Locate and uncomment the setting `dbms.mode`, and change the value to `READ_REPLICA`.
.. Locate and uncomment the setting `causal_clustering.initial_discovery_members=localhost:5000,localhost:5001,localhost:5002`.
.. Locate and uncomment the setting `causal_clustering.discovery_listen_address`, and change the value to `:5003`.
.. Locate and uncomment the setting `causal_clustering.transaction_listen_address`, and change the value to `:6003`.
.. Locate and uncomment the setting `dbms.connector.bolt.listen_address`, and change the value to `:7690`.
.. Locate and uncomment the setting `dbms.connector.http.listen_address`, and change the value to `:7477`.
.. Locate and uncomment the setting `dbms.connector.https.listen_address`, and change the value to `:6477`.
.. Locate and uncomment the setting `dbms.backup.listen_address`, and change the values to `0.0.0.0:6365`.
. Save the file.
. Open a command-line tool and navigate to _replica-01_ directory.
. Run the following command to start _replica-01_:
+
[source, shell]
----
replica-01$ ./bin/neo4j start
----

[discrete]
[[tutorial-local-cluster-configure-read-replica02]]
=== Configure and start the second Read Replica

You create and configure the second Read Replica.

. Make a new copy of the _neo4j-enterprise-{neo4j-version-exact}_ directory and name it _replica-02_.
. Overwrite _replica-02/conf/neo4j.conf_ with the just modified _replica-01/conf/neo4j.conf_. Then in the new _replica-02_ directory, open
the _conf/neo4j.conf_ file and configure the following settings:
.. Locate the setting `causal_clustering.discovery_listen_address` and change the value to `:5004`.
.. Locate the setting `causal_clustering.transaction_listen_address` and change the value to `:6004`.
.. Locate the setting `dbms.connector.bolt.listen_address` and change the value to `:7691`.
.. Locate the setting `dbms.connector.http.listen_address` and change the value to `:7478`.
.. Locate the setting `dbms.connector.https.listen_address` and change the value to `:6478`.
.. Locate the setting `dbms.backup.listen_address` and change the value to `0.0.0.0:6366`.
. Save the file.
. Open a command-line tool and navigate to _replica-02_ directory.
. Run the following command to start _replica-02_:
+
[source, shell]
----
replica-02$ ./bin/neo4j start
----

[discrete]
[[tutorial-local-cluster-configure-read-replica03]]
=== Configure and start the third Read Replica

You create and configure the third Read Replica.

. Make a new copy of the _neo4j-enterprise-{neo4j-version-exact}_ directory and name it _replica-03_.
. Overwrite _replica-03/conf/neo4j.conf_ with the just modified _replica-02/conf/neo4j.conf_. Then in the new _replica-03_ directory, open
the _conf/neo4j.conf_ file and configure the following settings:
.. Locate the setting `causal_clustering.discovery_listen_address` and change the value to `:5005`.
.. Locate the setting `causal_clustering.transaction_listen_address` and change the value to `:6005`.
.. Locate the setting `dbms.connector.bolt.listen_address` and change the value to `:7692`.
.. Locate the setting `dbms.connector.http.listen_address` and change the value to `:7479`.
.. Locate the setting `dbms.connector.https.listen_address` and change the value to `:6479`.
.. Locate the setting `dbms.backup.listen_address` and change the value to `0.0.0.0:6367`.
. Save the file.
. Open a command-line tool and navigate to _replica-03_ directory.
. Run the following command to start _replica-03_:
+
[source, shell]
----
replica-03$ ./bin/neo4j start
----

[[tutorial-local-cluster-test-with-read-replicas]]
== Check the status of the cluster

Your cluster of three Core servers and three Read Replicas is operational and is ready to serve requests.

In your _core-01_ browser, check the cluster status by running the following in Neo4j Browser:
[source, cypher]
----
:sysinfo
----

.A cluster of three Core instances and three Read Replicas.
====
[options="header"]
|===
| Name | Address | Role	| Status | Default | Error
| neo4j	| localhost:7689 | follower | online | true | -
| neo4j	| localhost:7688 | follower | online | true | -
| neo4j	| localhost:7687 | leader | online | true | -
| neo4j	| localhost:7692 | read_replica | online | true | -
| neo4j	| localhost:7691 | read_replica | online | true | -
| neo4j	| localhost:76890 | read_replica | online | true | -
| system	| localhost:7689 | follower | online | - | -
| system	| localhost:7688 | follower | online | - | -
| system	| localhost:7687 | leader | online | - | -
| system	| localhost:7692 | read_replica | online | - | -
| system	| localhost:7691 | read_replica | online | - | -
| system	| localhost:7690 | read_replica | online | - | -
|===
====

. Open a new tab and point your web browser to a Read Replica, for example, _replica-01_ at _\http://localhost:7477_.
. Login with `neo4j` and the previously set password and *use the `bolt://` schema*.
. Run the following query to verify that the data has been replicated:
+
[source, cypher]
----
MATCH path = (person:Person)-[:FRIENDS]-(friend)
RETURN path
LIMIT 10
----
