[role=enterprise-edition]
[[tutorial-immutable-privileges]]
= Administering immutable privileges
:description: This tutorial describes methods for administering immutable privileges.

This tutorial describes how to administer immutable privileges, which are useful assets for restricting the actions of users who themselves are able to administer privileges.
They offer a way to prevent such users from simply removing any restrictions by using their link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/administration/access-control/dbms-administration#access-control-dbms-administration-privilege-management[privilege management] privileges.

In other words, having  link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/administration/access-control/dbms-administration#access-control-dbms-administration-privilege-management[privilege management] privileges is not sufficient to add or remove immutable privileges.
The only way immutable privileges can be added or removed is when auth is disabled.

[CAUTION]
====
This should only be performed when you have other means of preventing access to the Neo4j DBMS.
====

When auth is disabled, immutable privileges can be added and removed in the same way as regular privileges.
To do so, follow these steps:

. Change the config setting xref:configuration/configuration-settings.adoc#config_dbms.security.auth_enabled[`dbms.security.auth_enabled`] to `false`.
. Restart the Neo4j DBMS.
. Create or remove immutable privileges in the same way as regular privileges using the keyword `IMMUTABLE`.
For example:
[source, cypher, role=noplay]
----
DENY IMMUTABLE DATABASE MANAGEMENT ON DBMS TO PUBLIC
----
[start=4]
. Change the config setting xref:configuration/configuration-settings.adoc#config_dbms.security.auth_enabled[`dbms.security.auth_enabled`] to `true`.
. Restart the Neo4j DBMS.
. Observe that the following immutable privileges are now in place:

[source, cypher, role=noplay]
----
SHOW PRIVILEGES WHERE IMMUTABLE
----

.Result
[options="header,footer", width="100%", cols="m,m,m,m,m,m,m"]
|===
|access
|action
|resource
|graph
|segment
|role
|immutable

|"DENIED"
|"database_management"
|"database"
|"*"
|"database"
|"PUBLIC"
|true
6+a|Rows: 1
|===

Privileges like this one can now be considered to be an immutable part of the DBMS.
The only way to subsequently remove it would be to repeat this process.
