[[consistency-checker]]
= Consistency checker
:description: Describes the Neo4j consistency checker. 

You can use the `neo4j-admin database check` command to check the consistency of a database, a dump, or a backup.
The `neo4j-admin` tool is located in the _/bin_ directory.
If checking the consistency of a database, note that it has to be stopped first or else the consistency check will result in an error.

[NOTE]
====
It is not recommended to use an NFS to check the consistency of a database, a dump, or a backup as this slows the process down significantly.
====

== Syntax

The `neo4j-admin database check` command has the following syntax:

----
neo4j-admin database check [--force] [--verbose] [--check-counts[=true|false]] [--check-graph[=true|false]]
                           [--check-indexes[=true|false]] [--check-property-owners[=true|false]]
                           [--additional-config=<file>] [--report-path=<path>]
                           [[--from-path-data=<path> --from-path-txn=<path>] | [--from-path=<path> [--temp-path=<path>]]]
                           <database>
----

`<database>` -- Name of the database to check.

== Options

The `neo4j-admin database check` command has the following options:

[options="header",cols="m,m,a"]
|===
| Option                    | Default       | Description
|  --additional-config      |               | Path to a configuration file that contains additional configuration options.
|  --verbose                | false         | Enable verbose output.
|  --report-path            | .             | Path to where a consistency report will be written. Interpreted as a directory, unless it
has an extension of _.report_.
|  --check-graph            | true          | Perform checks between nodes, relationships, properties, types, and tokens.
|  --check-indexes          | true          | Perform checks on indexes by comparing content with the store.
|  --check-counts           | <check-graph> | Perform consistency checks on the counts. Requires the `check-graph` option to be `true` (which is by default) or you can specify `--check-graph/--check-graph=true`.
|  --check-property-owners  | false         | Perform consistency checks on the ownership of properties. Requires the `check-graph` option to be `true` (which is by default) or you can specify `--check-graph/--check-graph=true`.
|  --from-path-data         | xref:reference/configuration-settings.adoc#config_server.directories.data[`server.directories.data`]/databases
                                            | Path to the _/databases_ directory, containing the database directory to source from.
|  --from-path-txn          | xref:reference/configuration-settings.adoc#config_server.directories.transaction.logs.root[`server.directories.transaction.logs.root`]
                                            | Path to the _/transactions_ directory, containing the transaction directory for the database to source from.
|  --from-path              |               | Path to the directory containing dump/backup artifacts whose consistency will be checked.
|  --temp-path              | <from-path>   | Path to a directory to be used as a staging area to extract dump/backup artifacts if needed.
|  --force                  | false         | Force a consistency check to be run, overriding resource checks.
|===


== Output

If the consistency checker does not find errors, it exits cleanly and does not produce a report.
If the consistency checker finds errors, it exits with an exit code other than `0` and writes a report file with a name on the format `inconsistencies-YYYY-MM-DD.HH24.MI.SS.report`.
The location of the report file is the current working directory, or as specified by the parameter `report-path`.

== Example

.Run the consistency checker
====
Note that the database must be stopped first.

----
$neo4j-home> bin/neo4j-admin database check neo4j

ID Generator consistency check
....................  10%
....................  20%
....................  30%
....................  40%
....................  50%
....................  60%
....................  70%
....................  80%
....................  90%
.................... 100%
Index structure consistency check
....................  10%
....................  20%
....................  30%
....................  40%
....................  50%
....................  60%
....................  70%
....................  80%
....................  90%
.................... 100%
Consistency check
....................  10%
....................  20%
....................  30%
....................  40%
....................  50%
....................  60%
....................  70%
....................  80%
....................  90%
.................... 100%

----

Run with the `--from-path` option to check the consistency of a backup or a dump.
----
bin/neo4j-admin database check --from-path=<directory-with-backup-or-dump> neo4j
----

====

[NOTE]
====
`neo4j-admin database check` cannot be applied to xref:composite-databases/introduction.adoc#composite-databases-concepts[composite databases].
 It must be run directly on the databases that are part of a composite database.
====
