:description: This section describes commands for managing and administering a Neo4j DBMS.
[[neo4j-admin]]
= Neo4j Admin and Neo4j CLI

[[neo4j-admin-introduction]]
== Introduction

Neo4j Admin is the primary tool for managing a Neo4j DBMS.
It is a command-line tool that is installed as part of the product and can be executed with a number of commands.
Some of the commands are described in more detail in separate sections.

[NOTE]
====
The Neo4j Admin commands must be invoked with the same user as Neo4j runs as.
This guarantees that Neo4j will have full rights to start and work with the database files you use.
====

[[neo4j-admin-syntax-and-commands]]
== Syntax and commands

*Syntax*

Neo4j Admin is located in the xref:configuration/file-locations.adoc[_bin_] directory and is invoked as:

`neo4j-admin [-hV] [COMMAND]`

* `-h`, `--help` -- Show the `neo4j-admin` help message and exit.
* `-V`, `--version` -- Print the `neo4j-admin` version information and exit.

*Commands*

[options="header", cols="25,25a,50a"]
|===
| Functionality area
| Command
| Description
.8+| General
| `help <command>`
| Display help information about the specified command.

| `check-consistency`
| Check the consistency of a database.

For details, see xref:tools/neo4j-admin/consistency-checker.adoc[Consistency checker].

| `report`
| Produce a zip/tar of the most common information needed for remote assessments.

For details, see xref:tools/neo4j-admin/neo4j-admin-report.adoc[Neo4j Admin report].

| `store-info`
| Print information about a Neo4j database store.

For details, see xref:tools/neo4j-admin/neo4j-admin-store-info.adoc[Display store information].

| `memrec`
| Print Neo4j heap and pagecache memory settings recommendations.

For details, see xref:tools/neo4j-admin/neo4j-admin-memrec.adoc[Memory recommendations].

| `import`
| Import from a collection of CSV files or a pre-3.0 database.

For details, see xref:tools/neo4j-admin/neo4j-admin-import.adoc[Import].

| `copy`
| Copy data from an existing database to a new database.

For details, see xref:backup-restore/copy-database.adoc[Copy a database store].

| `push-to-cloud`
| Dump a local offline database, and imports it into a specified Neo4j AuraDB instance.
The target location is your Neo4j Aura Bolt URI.

For details, see xref:tools/neo4j-admin/push-to-cloud.adoc[Push to cloud].

.2+| Authentication
| `set-default-admin`
|  Set the default admin user when no roles are present.

| `set-initial-password`
| Set the initial password of the initial admin user (`neo4j`).

For details, see xref:configuration/set-initial-password.adoc[Set an initial password].

.2+| Offline backup and restore

For details, see xref:backup-restore/offline-backup.adoc[Back up an offline database] and xref:backup-restore/restore-dump.adoc[Restore a database dump].
| `dump`
| Dump a database into a single-file archive.

| `load`
| Load a database from an archive created with the `dump` command.

.3+| Online backup and restore

For details, see xref:backup-restore/online-backup.adoc[], xref:backup-restore/prepare-restore.adoc[], and xref:backup-restore/restore-backup.adoc[].
| `backup`
| Perform an online backup from a running Neo4j server.

| `prepare-restore`
| Prepare a backup for restoring by applying the latest transactions pulled at the time of backup but not yet applied to the store.

| `restore`
| Restore a backed-up database.

.2+| Clustering
| `unbind`
| Remove cluster state data from a stopped Neo4j server.

For details, see xref:tools/neo4j-admin/unbind.adoc[Unbind a Core Server].

| `get-server-id`
|  Display the Server ID of a Neo4j instance.

If no Server ID is returned, either Neo4j has never started or it has been unbound.
Start Neo4j to create a new Server ID and then re-run this command.

The Server ID can be used in Cypher commands to identify an instance.
|===

[[neo4j-admin-environment-variables]]
== Environment variables

== Environment variables

The Neo4j Admin tool can also use the following environment variables:

[options="header", cols="1m,3a"]
|===
| Environment variable
| Description

| NEO4J_DEBUG
| Set to anything to enable debug output.

| NEO4J_HOME
| Neo4j home directory.

| NEO4J_CONF
| Path to the directory that contains _neo4j.conf_.

| HEAP_SIZE
| Set JVM maximum heap size during command execution.
Takes a number and a unit, for example, 512m.

| JAVA_OPTS
| Additional JVM arguments.

|===

[NOTE]
====
By default, `dbms.jvm.additional` settings specified in the configuration file are used when invoking Admin commands.
Even though this is a default behavior, it might lead to problems when an Admin command is invoked on the same machine running DBMS.
Since the command reuses JVM memory settings configured for the DBMS, the machine might not have enough memory to run both tasks simultaneously.
Even if it does, Admin commands require nowhere near as much memory as the DBMS, so this default behavior is wasteful in most cases.

Still, memory consumption might not be the only issue. For instance, if the DBMS JVM is configured to open an administration port
for JMX or debugging, Admin commands will try to open the same port and thus conflict with a running DBMS.
If the default behavior described above is problematic, Admin commands can be instructed to ignore `dbms.jvm.additional`
from the configuration file by simply using `JAVA_OPTS` with any non-empty value, for example:
`JAVA_OPTS=-Xmx512m neo4j-admin ...`.
Setting `JAVA_OPTS` to any non-empty value will make the invoked Admin command completely ignore all `dbms.jvm.additional` settings in the configuration file.
====


[[neo4j-admin-exit-codes]]
== Exit codes

When `neo4j-admin` finishes as expected, it returns an exit code of `0`.
A non-zero exit code means something undesired happened during command execution.
The non-zero exit code can contain further information about the error, such as the `backup` command's xref:backup-restore/online-backup.adoc#backup-command-exit-codes[exit codes].
