[[neo4j-admin-migrate-configuration]]
= Migrate the Neo4j configuration file
:description: This chapter describes the `neo4j-admin server migrate-configuration` command. 

You can use the `migrate-configuration` command to migrate a Neo4j configuration file from the previous `MAJOR` version.
However, this step of the migration process is optional.
You can also run a Neo4j DBMS with the configuration from the last MAJOR version.

Why use the command?::
* Configuration migration is a purely mechanical process, and using the explicit migration with the `migrate-configuration` command allows you to inspect and customize the output.
* The command output provides valuable insight into the migration process, including notification about settings that could not have been meaningfully migrated, for instance, because the concept or behavior no longer exists in the new `MAJOR` version of the DBMS.

== Syntax

The `migrate-configuration` command has the following syntax:

`neo4j-admin server migrate-configuration`

//== Example
