:description: This chapter describes the `neo4j-admin database migrate` command.
[[neo4j-admin-migrate]]
= Migrate a database

You can use the `neo4j-admin database migrate` command to migrate a Neo4j database from one store format to another or to a later `MAJOR` version of the same format.

A store format defines how the data of a database is stored on the file system.

As of Neo4j 5, the store format of a database is versioned with the `MAJOR.MINOR` scheme, independent of Neo4j versioning.
An upgrade to the latest `MINOR` format version is an automatic operation performed on database startup.
A migration to a higher `MAJOR` format version or another format is a manual action performed with the `migrate` command.

The store format for new databases can be set with the xref:reference/configuration-settings.adoc#config_db.format[`db.format`] configuration setting.

== Syntax

The `neo4j-admin database  migrate` has the following syntax:

----
neo4j-admin database  migrate --to-format=<format> <database name>
----

== Options

If the format is specified with the `--to-format` option, the target database is migrated to the latest known combination of `MAJOR` and `MINOR` version of the specified format:

----
neo4j-admin database  migrate --to-format=<format> <database name>
----

Invoking the command without specifying the format with `--to-format` option migrates the target database the latest known combination of `MAJOR` and `MINOR` version of the current format:

----
neo4j-admin database migrate <database name>
----
