:description: This chapter describes the `report` command of Neo4j Admin.
[[neo4j-admin-report]]
= Neo4j Admin report

//Check Mark
:check-mark: icon:check[]

You can use the `neo4j-admin server report` command to collect information about a Neo4j installation and save it to an archive.

== Syntax

The `neo4j-admin server report` command has the following syntax:

----
neo4j-admin server report [-h]
                          [--expand-commands]
                          [--list]
                          [--verbose]
                          [--ignore-disk-space-check[=true|false]]
                          [--additional-config=<file>]
                          [--to-path=<path>]
                          [<classifier>...]
----

The intended usage of the report tool is to simplify the support process by collecting the relevant information in a standard way.
This tool does not send any information automatically.
To share this information with the Neo4j Support organization, you have to send it manually.

== Options and classifiers

The `neo4j-admin server report` command has the following options and classifiers:

.Options
[options="header", cols="<2m,^1a,<4a"]
|===
| Option
| Possible values
| Description

| -h, --help
| 
| Show this help message and exit.

| `--expand-commands`
| 
| Allow command expansion in config value evaluation.

| --list
|
| List all available classifiers.

| --verbose
|
| Enable verbose output.

| --ignore-disk-space-check
| `true` or `false` (Default: `false`)
| Ignore disk full warning.

| --to-path
| `<path>` (Default: _/tmp_)
|  Destination directory for reports.
|===

By default, the tool tries to estimate the final size of the report and uses that to assert that there is enough disk space available for it.
If there is not enough available space, the tool aborts.
However, this estimation is pessimistic and does not consider the compression.
Therefore, if you are confident that you do have enough disk space, you can disable this check with the option `--ignore-disk-space-check`.

[[classifiers]]
.Classifiers
[options="header", cols="<1m,^1a,<4a"]
|===
| Classifier
| Online
| Description

| all
|
| Include all of the available classifiers.

| ccstate
|
| Include the current cluster state.

| config
|
| Include Neo4j configuration files.

| heap
| {check-mark}
| Include a heap dump.

| logs
|
| Include log files, e.g., _debug.log_, _neo4j.log_, etc.

| metrics
|
| Include the collected metrics.

| plugins
|
| Include a text view of the plugin directory (no files are collected).

| ps
|
| Include a list of running processes.

| raft
|
| Include the raft log.

| sysprop
| {check-mark}
| Include a list of Java system properties.

| threads
| {check-mark}
| Include a thread dump of the running instance.

| tree
|
| Include a text view of the folder structure of the data directory (no files are collected).

| tx
|
| Include transaction logs.
|===

The classifiers marked as _Online_ work only when you have a running Neo4j instance that the tool can find.

If no classifiers are specified, the following classifiers are used: `logs`, `config`, `plugins`, `tree`, `metrics`, `threads`, `sysprop`, `ps`, and `version`.

The reporting tool does not read any data from your database.
However, the heap, the raft logs, and the transaction logs may contain data.
Additionally, even though the standard _neo4j.conf_ file does not contain password information, for specific configurations, it may have this type of information.
Therefore, be aware of your organization's data security rules before using the classifiers `heap`, `tx`, `raft`, and `config`.

== Examples

[NOTE]
====
This tool uses the https://docs.oracle.com/javase/8/docs/technotes/guides/attach/index.html[Java Attach API] to gather data from a running Neo4j instance.
Therefore, it requires the Java JDK to run properly.
====

.Invoke `neo4j-admin server report` using the default classifiers
====

The following command gathers information about the Neo4j instance using the default classifiers and saves it to the default location:

[source, shell]
----
$neo4j-home> bin/neo4j-admin server report
----
====

.Invoke `neo4j-admin server report` using all classifiers
====

The following command gathers information about the Neo4j instance using all classifiers and saves it to a specified location:

[source, shell]
----
$neo4j-home> bin/neo4j-admin server report --to-path=./report all
----
====

.Invoke `neo4j-admin server report` to gather only logs and thread dumps
====

The following command gathers only logs and thread dumps from the running Neo4j instance and saves it to a specified location:

[source, shell]
----
$neo4j-home> bin/neo4j-admin server report --to-path=./report threads logs
----
====
