:description: How to import a database from an existing Neo4j instance into Neo4j Aura using `neo4j-admin push-to-cloud`.
[role=aura]
[[neo4j-admin-push-to-cloud]]
= Push to cloud

You can use the `neo4j-admin database upload` command to upload a local Neo4j database dump into a Neo4j Aura instance.

[NOTE]
====
This operation is secured and TLS encrypted end to end.
====

== Syntax

----
neo4j-admin push-to-cloud [--overwrite] [--verbose] --bolt-uri=<boltURI>
                          [--database=<database>] [--dump=<dump>]
                          [--dump-to=<tmpDumpFile>] [--password=<password>]
                          [--username=<username>]
----

== Options

[options="header" cols="<20m,<20m,<60a"]
|===
| Option
| Default
| Description

|  --database
| neo4j
| Name of the database to push.

This argument cannot be used together with `--dump`.

|  --dump
|
| Path to an existing database dump for upload, in the format _/path/to/my-neo4j-database-dump-file_.

This argument cannot be used together with `--database`.

|  --dump-to
|
| Optional.

Target path for temporary database dump file to be uploaded, in the format _/path/to/temp-file_.

Used in combination with the `--database` argument.

|  --bolt-uri
|
| Bolt URI of the target database.
For example, `neo4j://mydatabaseid.databases.neo4j.io`.

|  --username
|
| Optional.

Username of the target database to push this database to.
If you do not provide a username, you will be prompted to provide one.
Alternatively, the `NEO4J_USERNAME` environment variable can be used.

|  --password
|
| Optional.

Password of the target database to push this database to.
If you do not provide a password, you will be prompted to provide one.
Alternatively, the `NEO4J_PASSWORD` environment variable can be used.

|  --overwrite
|
| Optional.

Overwrite the data in the target database.

|  --verbose
|
| Optional.

Enable verbose output.
|===

== Limitations

* A Neo4j Aura database must already be provisioned and running.
* Your local database must be stopped before you run the `push-to-cloud` command with the `--database` argument.
The `push-to-cloud` function cannot be used with a source database which is currently in use.
* If used with a running source database, it will exit and print an error.

== Output

If the `push-to-cloud` function completes successfully, it will exit with the following log line:

----
“Your data was successfully pushed to cloud and is now running”.
----

If the `push-to-cloud` function encounters an error at any point, you will be provided with instructions on how to try again, or to contact Neo4j Aura support.

== Example

Run with the `--database` option to dump a specific database name.
Note that the local database must be stopped first.

[source, shell,role=nocopy]
----
$neo4j-home> bin/neo4j stop
$neo4j-home> bin/neo4j-admin push-to-cloud --database=graph.db --bolt-uri=<neo4j-cloud-bolt-uri>
Neo4j cloud database user name: neo4j
Neo4j cloud database password:
Dumped contents of database 'graph.db' into '$neo4j-home/dump-of-graph.db-1569931327069'
Upload
....................  10%
....................  20%
....................  30%
....................  40%
....................  50%
....................  60%
....................  70%
....................  80%
....................  90%
.................... 100%
We have received your export and it is currently being loaded into your cloud instance.
You can wait here, or abort this command and head over to the console to be notified of when your database is running.
Import status
....................  10%
....................  20%
....................  30%
....................  40%
....................  50%
....................  60%
....................  70%
....................  80%
....................  90%
.................... 100%
Your data was successfully pushed to cloud and is now running.
----
