:description: How to import a database from an existing Neo4j instance into Neo4j Aura using `neo4j-admin push-to-cloud`.
[role=aura]
[[neo4j-admin-push-to-cloud]]
= Push to cloud

The `neo4j-admin push-to-cloud` command uploads a database or a dump into a Neo4j Aura instance. +

[NOTE]
====
To upload a 4.3 database in Aura, it is highly recommended to first upgrade it to 4.4 and then use the `neo4j-admin push-to-cloud command`.
====

The following table shows the compatibility between the dump version that you want to upload and the version of the Neo4j Aura instance.

[options="header" cols="50%, 50%"]
|===
| Dump version
| Aura version

| v4.3
| v4

|===


[NOTE]
====
This operation is secured and TLS encrypted end to end.
====

== Syntax

----
neo4j-admin push-to-cloud [--overwrite] [--verbose] --bolt-uri=<boltURI>
                          [--database=<database>] [--dump=<dump>]
                          [--dump-to=<tmpDumpFile>] [--password=<password>]
                          [--username=<username>]
----

== Options

[options="header" cols="<20m,<20m,<60a"]
|===
| Option
| Default
| Description

|  --database
| neo4j
| Name of the database to push.

This argument cannot be used together with `--dump`.

|  --dump
|
| Path to an existing database dump for upload, in the format _/path/to/my-neo4j-database-dump-file_.

This argument cannot be used together with `--database`.

|  --dump-to
|
| Optional.

Target path for temporary database dump file to be uploaded, in the format _/path/to/temp-file_.

Used in combination with the `--database` argument.

|  --bolt-uri
|
| Bolt URI of the target database.
For example, `neo4j://mydatabaseid.databases.neo4j.io`.

|  --username
|
| Optional.

Username of the target database to push this database to.
If you do not provide a username, you will be prompted to provide one.
Alternatively, the `NEO4J_USERNAME` environment variable can be used.

|  --password
|
| Optional.

The password of the target database to push this database to.
If you do not provide a password, you will be prompted to provide one.
Alternatively, you can use the `NEO4J_PASSWORD` environment variable.

|  --overwrite
|
| Optional.

Overwrite the data in the target database.

|  --verbose
|
| Optional.

Enable verbose output.
|===

== Limitations

* A Neo4j Aura database must already be provisioned and running.
* Your local database must be stopped before you run the `push-to-cloud` command with the `--database` argument.
The `push-to-cloud` function cannot be used with a source database that is currently in use.

[CAUTION]
====
The `neo4j-admin push-to-cloud` command is not compatible with instances encrypted with link:{neo4j-docs-base-uri}/aura/platform/security/#_customer_managed_keys[Customer Managed Keys].
Use `neo4j-admin database upload` in Neo4j Admin version 5 to upload data to instances encrypted with Customer Managed Keys.
For more information see link:{neo4j-docs-base-uri}/aura/auradb/importing/import-database[Neo4j Admin database upload].
====


== Output

If the `push-to-cloud` function completes successfully, it exits with the following logline:

----
Your data was successfully pushed to Aura and is now running.
----

If the `push-to-cloud` function encounters an error at any point, you will be provided with instructions on how to try again or to contact Neo4j Aura support. +
Additionally, you can use the `--verbose` option to enable verbose output.

== Examples

The following examples show how to use the `push-to-cloud` command to upload a database or a database dump to a Neo4j Aura instance.
You need your AuraDB instance URI (`neo4j+s://your-databaseid.databases.neo4j.io`), as can be seen in the Aura console, and your AuraDB instance password.

[NOTE]
====
You should use the `--overwrite` option to overwrite the target database.
Otherwise, the command aborts and throws an error.
====

[CAUTION]
====
This command does not currently support https://neo4j.com/docs/aura/platform/security/secure-connections/#_vpc_isolation[private linking].
Please https://aura.support.neo4j.com/hc/en-us/requests/new[raise a support ticket] if you have public traffic disabled and need to use this command.
====

.Upload a database dump to a Neo4j Aura instance
[source, shell,role=nocopy]
----
bin/neo4j-admin push-to-cloud --dump=/path/to/dumpfile/movies.dump --bolt-uri=neo4j+s://your-databaseid.databases.neo4j.io --overwrite

# An example output:

Selecting JVM - Version:11.0.6+8-LTS, Name:Java HotSpot(TM) 64-Bit Server VM, Vendor:Oracle Corporation
Neo4j aura username (default: neo4j):
Neo4j aura password for neo4j:
Upload
....................  10%
....................  20%
....................  30%
....................  40%
....................  50%
....................  60%
....................  70%
....................  80%
....................  90%
.................... 100%
We have received your export and it is currently being loaded into your Aura instance.
You can wait here, or abort this command and head over to the console to be notified of when your database is running.
Import progress (estimated)
....................  10%
....................  20%
....................  30%
....................  40%
....................  50%
....................  60%
....................  70%
....................  80%
....................  90%
.................... 100%
Your data was successfully pushed to Aura and is now running.
It is safe to delete the dump file now: /path/to/dumpfile/movies.dump
----

.Upload a database to a Neo4j Aura instance
[source, shell, role=nocopy]
----
# Stop the `neo4j` database:

bin/cypher-shell -u neo4j -p <password>
neo4j@neo4j> :use system;
neo4j@system> stop database neo4j;

# Run the push-to-cloud command to upload the `neo4j` database into your Aura instance

bin/neo4j-admin push-to-cloud --database=neo4j --bolt-uri=neo4j+s://your-databaseid.databases.neo4j.io --overwrite

# An example output:

Selecting JVM - Version:11.0.6+8-LTS, Name:Java HotSpot(TM) 64-Bit Server VM, Vendor:Oracle Corporation
Neo4j aura username (default: neo4j):
Neo4j aura password for neo4j:
Done: 70 files, 854.0KiB processed.
Dumped contents of database 'neo4j' into '/<neo4j-home>/dump-of-neo4j-1669732123683'
Upload
....................  10%
....................  20%
....................  30%
....................  40%
....................  50%
....................  60%
....................  70%
....................  80%
....................  90%
.................... 100%
We have received your export and it is currently being loaded into your Aura instance.
You can wait here, or abort this command and head over to the console to be notified of when your database is running.
Import progress (estimated)
....................  10%
....................  20%
....................  30%
....................  40%
....................  50%
....................  60%
....................  70%
....................  80%
....................  90%
.................... 100%
Your data was successfully pushed to Aura and is now running.
----

