:description: How to import a database from an existing Neo4j instance into Neo4j Aura using `neo4j-admin database upload`.
[role=aura]
[[neo4j-admin-push-to-cloud]]
= Upload to Neo4j Aura

You can use the `neo4j-admin database upload` command to upload a local Neo4j database dump into a Neo4j Aura instance.

[NOTE]
====
This operation is secured and TLS encrypted end to end.
====

== Syntax

The `neo4j-admin database upload` command has the following syntax:

----
neo4j-admin database upload [--verbose] [--overwrite-destination[=true|false]]
                            --from-path=<path> [--to=<destination>] [--to-password=<password>]
                            --to-uri=<uri> [--to-user=<username>] <database>

----

== Options

The `neo4j-admin database upload` command has the following options:

.Options
[options="header" cols="<20m,<20m,<60a"]
|===
| Option
| Default
| Description

| <database>
|
| Name of the database that should be uploaded.

The name is used to select a dump file which is expected to be named <database>.dump.

| --from-path
|
| Path to a directory containing a database dump to upload.

| --to
| aura
| The destination for the upload.

| --to-uri
|
| Bolt URI of the target Aura database.
For example, `neo4j://myaurainstanceid.databases.neo4j.io`.

|  --to-user
|
| Optional.

The username of the target Aura instance where you will upload this database.
If you do not provide a username, you will be prompted to provide one.
Alternatively, you can use the `NEO4J_USERNAME` environment variable.

|  --to-password
|
| Optional.

The password for the target Aura instance where you will upload this database.
If you do not provide a password, you will be prompted to provide one.
Alternatively, the `NEO4J_PASSWORD` environment variable can be used.

|  --overwrite-destination
| false
| Optional.

Overwrite the data in the target database.

|  --verbose
|
| Optional.

Enable verbose output.
|===

== Limitations

* A Neo4j Aura instance must already be provisioned and running.

== Output

If the `upload` function completes successfully, it will exit with the following log line:

----
“Your data was successfully pushed to Aura and is now running”.
----

If the `upload` function encounters an error at any point, you will be provided with instructions on how to try again, or to contact Neo4j Aura support.

== Example

[source, shell,role=nocopy]
----
$neo4j-home> bin/neo4j-admin database upload graph.db --from-path=<path-to-directory-with-graph.db.dump> --bolt-uri=<neo4j-cloud-bolt-uri>
Neo4j cloud database user name: neo4j
Neo4j cloud database password:
Upload
....................  10%
....................  20%
....................  30%
....................  40%
....................  50%
....................  60%
....................  70%
....................  80%
....................  90%
.................... 100%
We have received your export and it is currently being loaded into your Aura instance.
You can wait here, or abort this command and head over to the console to be notified of when your database is running.
Import progress
....................  10%
....................  20%
....................  30%
....................  40%
....................  50%
....................  60%
....................  70%
....................  80%
....................  90%
.................... 100%
Your data was successfully pushed to Aura and is now running.
----
