:description: How to import a database from an existing Neo4j instance into Neo4j Aura using `neo4j-admin push-to-cloud`.
[role=aura]
[[neo4j-admin-push-to-cloud]]
= Upload to Neo4j AuraDB

The `neo4j-admin push-to-cloud` command enables you to dump a local Neo4j database and import it into a Neo4j Aura instance.

[NOTE]
====
This operation is secured and TLS encrypted end to end.
====

== Syntax

----
neo4j-admin push-to-cloud [--overwrite] [--verbose] --bolt-uri=<boltURI>
                          [--database=<database>] [--dump=<dump>]
                          [--dump-to=<tmpDumpFile>] [--password=<password>]
                          [--username=<username>]
----

== Options

[options="header" cols="<20m,<20m,<60a"]
|===
| Option
| Default
| Description

|  --database
| neo4j
| Name of the database to push.

This argument cannot be used together with `--dump`.

|  --dump
|
| Path to an existing database dump for upload, in the format _/path/to/my-neo4j-database-dump-file_.

This argument cannot be used together with `--database`.

|  --dump-to
|
| Optional.

Target path for temporary database dump file to be uploaded, in the format _/path/to/temp-file_.

Used in combination with the `--database` argument.

|  --bolt-uri
|
| Bolt URI of the target database.
For example, `neo4j://mydatabaseid.databases.neo4j.io`.

|  --username
|
| Optional.

Username of the target database to push this database to.
If you do not provide a username, you will be prompted to provide one.
Alternatively, the `NEO4J_USERNAME` environment variable can be used.

|  --password
|
| Optional.

The password of the target database to push this database to.
If you do not provide a password, you will be prompted to provide one.
Alternatively, you can use the `NEO4J_PASSWORD` environment variable.

|  --overwrite
|
| Optional.

Overwrite the data in the target database.

|  --verbose
|
| Optional.

Enable verbose output.
|===

== Limitations

* A Neo4j Aura database must already be provisioned and running.
* Your local database must be stopped before you run the `push-to-cloud` command with the `--database` argument.
The `push-to-cloud` function cannot be used with a source database that is currently in use.

== Output

If the `push-to-cloud` function completes successfully, it exits with the following logline:

----
Your data was successfully pushed to Aura and is now running.
----

If the `push-to-cloud` function encounters an error at any point, you will be provided with instructions on how to try again or to contact Neo4j Aura support.
Additionally, you can use the `--verbose` option to enable verbose output.

== Examples

The following examples show how to use the `push-to-cloud` command to upload a database and a database dump to a Neo4j Aura instance.
Note that the `--overwrite` option is used to overwrite the existing data in the target database.
The `neo4j-admin push-to-cloud` command also needs your AuraDB instance URI (`neo4j+s://your-databaseid.databases.neo4j.io`) as can be seen in the Aura console and your AuraDB instance password.

.Upload a database dump to a Neo4j Aura instance
[source, shell,role=nocopy]
----
bin/neo4j-admin push-to-cloud --dump=/path/to/dumps/movies.dump --bolt-uri=neo4j+s://your-databaseid.databases.neo4j.io --overwrite

# An example output:

Selecting JVM - Version:11.0.6+8-LTS, Name:Java HotSpot(TM) 64-Bit Server VM, Vendor:Oracle Corporation
Neo4j aura username (default: neo4j):
Neo4j aura password for neo4j:
Upload
....................  10%
....................  20%
....................  30%
....................  40%
....................  50%
....................  60%
....................  70%
....................  80%
....................  90%
.................... 100%
We have received your export and it is currently being loaded into your Aura instance.
You can wait here, or abort this command and head over to the console to be notified of when your database is running.
Import progress (estimated)
....................  10%
....................  20%
....................  30%
....................  40%
....................  50%
....................  60%
....................  70%
....................  80%
....................  90%
.................... 100%
Your data was successfully pushed to Aura and is now running.
It is safe to delete the dump file now: /path/to/dumps/movies.dump
----

.Upload a database to a Neo4j Aura instance
[source, shell, role=nocopy]
----
# Stop the `neo4j` database:

bin/cypher-shell -u neo4j -p <password>
neo4j@neo4j> :use system;
neo4j@system> stop database neo4j;

# Run the push-to-cloud command to upload the `neo4j` database into your Aura instance

bin/neo4j-admin push-to-cloud --database=neo4j --bolt-uri=neo4j+s://your-databaseid.databases.neo4j.io --overwrite

# An example output:

Selecting JVM - Version:11.0.6+8-LTS, Name:Java HotSpot(TM) 64-Bit Server VM, Vendor:Oracle Corporation
Neo4j aura username (default: neo4j):
Neo4j aura password for neo4j:
Done: 70 files, 854.0KiB processed.
Dumped contents of database 'neo4j' into '/<neo4j-home>/dump-of-neo4j-1669732123683'
Upload
....................  10%
....................  20%
....................  30%
....................  40%
....................  50%
....................  60%
....................  70%
....................  80%
....................  90%
.................... 100%
We have received your export and it is currently being loaded into your Aura instance.
You can wait here, or abort this command and head over to the console to be notified of when your database is running.
Import progress (estimated)
....................  10%
....................  20%
....................  30%
....................  40%
....................  50%
....................  60%
....................  70%
....................  80%
....................  90%
.................... 100%
Your data was successfully pushed to Aura and is now running.
----

