:description: How to remove cluster state data from a Neo4j server using `neo4j-admin unbind`.
[[neo4j-admin-unbind]]
= Unbind a Neo4j cluster server

[[unbind-command]]
== Command

The cluster state of a Causal Cluster member can be removed by using the following command:

[[unbind-command-syntax]]
=== Syntax

----
neo4j-admin unbind [--verbose]
                   [--expand-commands]
                   [--archive-cluster-state=<true/false>]
                   [--archive-path=<path>]
----

[[unbind-command-options]]
=== Options

[options="header", cols="2m,1,3"]
|===
| Option                     | Default          | Description
| `--verbose`                |                  | Enable verbose output.
| `--expand-commands`        |                  | Allow command expansion in config value evaluation.
| `--archive-cluster-state`  | false            | Enable or disable the cluster state archiving.
| `--archive-path`           |                  | Destination (file or folder) of the cluster state archive.
|===

[[unbind-command-limitatations]]
=== Limitations

The Neo4j server process must be shut down before running the `neo4j-admin unbind` command.

[[unbind-command-usage]]
== Examples of usage

You can use the `neo4j-admin unbind` command to:

* Turn a cluster member into a standalone server:
+
To start the Neo4j server in single (standalone) mode after unbinding it from the cluster, first set xref:reference/configuration-settings.adoc#config_dbms.mode[`dbms.mode=SINGLE`] in _xref:configuration/file-locations.adoc[neo4j.conf]_.

* Seed a Causal Cluster with existing store files:
+
To seed a new cluster using the store files of another cluster, you must first run `neo4j-admin unbind` on each server.
For more information about seeding Causal Clusters, see xref:clustering/seed.adoc[Seed a cluster].
+
[WARNING]
====
If a cluster holds a previous version of any of the databases being seeded, you must `DROP` those databases before seeding.
Alternatively, you can stop every instance, unbind them from the cluster using `neo4j-admin unbind` and then forcefully restore the correct seeds (backups) for the databases in question.
If you do not `DROP` or `unbind` before seeding, either with `neo4j-admin restore` or `neo4j-admin load`, the database's store files and cluster state will be out of sync, potentially leading to logical corruptions.
====

* Recover a Causal Cluster:
+
In the event of serious failures you may need to recover an entire Causal Cluster from backups.
Before restoring those backups, you must first run `neo4j-admin unbind` on each server.
For more information about recovering databases from online backups, see xref:backup-restore/restore-backup.adoc[Restore a database backup].
+
[NOTE]
====
From Neo4j version 4.0.0 onwards, you *must* run the `neo4j-admin unbind` command on both Read Replicas and Core members.
====

[[unbind-command-archive]]
== Archive cluster state

If something goes wrong and debugging is needed, you can archive the cluster state, from the _<neo4j-home>_ folder, run the `neo4j-admin server unbind` command with the arguments `--archive-cluster-state=true` and `--archive-path=<destination-folder>`:

[source, shell]
----
bin/neo4j-admin unbind --archive-path=/path/to/archive-folder --archive-cluster-state=true
----

The default resultant file is named: 

[result]
----
unbound_cluster_state.<YYYYMMDDHH24MM>.zip
----
