:description: How to remove cluster state data from a Neo4j server using `neo4j-admin unbind`.
[[neo4j-admin-unbind]]
= Unbind a Neo4j cluster server
:description: This section describes how to remove cluster state data from a Neo4j server. 

You can use the `neo4j-admin unbind` command to remove the cluster state of a cluster member.

[[unbind-command-syntax]]
== Syntax

The `neo4j-admin unbind` command has the following syntax:

----
neo4j-admin unbind [--verbose]
                   [--expand-commands]
                   [--archive-cluster-state=<true/false>]
                   [--archive-path=<path>]
----

[[unbind-command-options]]
== Options

The `neo4j-admin unbind` command has the following options:

.Options
[options="header", cols="2m,1,3"]
|===
| Option                     | Default          | Description
| `--verbose`                |                  | Enable verbose output.
| `--expand-commands`        |                  | Allow command expansion in config value evaluation.
| `--archive-cluster-state`  | false            | Enable or disable the cluster state archiving.
| `--archive-path`           |                  | Destination (file or folder) of the cluster state archive.
|===

[[unbind-command-limitatations]]
== Limitations

The Neo4j server process must be shut down before running the `neo4j-admin unbind` command.

[[unbind-command-usage]]
== Examples

You can use the `neo4j-admin unbind` command to:

* Turn a cluster member into a standalone server:
+
To start the Neo4j server in single (standalone) mode after unbinding it from the cluster, first set <<config_server.cluster.initial_mode_constraint, `server.cluster.initial_mode_constraint=SINGLE`>> in _xref:configuration/file-locations.adoc[neo4j.conf]_.

* Seed a Neo4j cluster with existing store files:
+
To seed a new cluster using the store files of another cluster, you must first run `neo4j-admin unbind` on each server.
For more information about seeding a Neo4j cluster, see xref:clustering/databases.adoc#cluster-seed[Seed a cluster].
+
[WARNING]
====
If a cluster holds a previous version of any of the databases being seeded, you must `DROP` those databases before seeding.
Alternatively, you can stop every instance, unbind them from the cluster using xref:tools/neo4j-admin/unbind.adoc[neo4j-admin unbind] and then forcefully restore the correct seeds (backups) for the databases in question.
If you do not `DROP` or `unbind` before seeding, either with `neo4j-admin database restore` or `neo4j-admin database load`, the database's store files and cluster state will be out of sync, potentially leading to logical corruptions.
====

* Recover a Neo4j Cluster:
+
In the event of serious failures you may need to recover an entire cluster from backups.
Before restoring those backups, you must first run `neo4j-admin unbind` on each server.
For more information about recovering databases from online backups, see xref:backup-restore/restore-backup.adoc[Restore a database backup].
+
[NOTE]
====
You *must* run the `neo4j-admin unbind` command on both primary and secondary servers.
====

[[unbind-command-archive]]
== Archive cluster state

To archive the cluster state, from the _<neo4j-home>_ folder, run the `neo4j-admin unbind` command with the arguments `--archive-cluster-state=true` and `--archive-path=<destination-folder>`:

[source, shell]
----
bin/neo4j-admin unbind --archive-path=/path/to/archive-folder --archive-cluster-state=true
----

The default resultant file is named:

[result]
----
unbound_cluster_state.<YYYYMMDDHH24MM>.zip
----
