:description: How to remove cluster state data from a Neo4j server using `neo4j-admin server unbind`.
[role=enterprise-edition]
[[neo4j-admin-unbind]]
= Unbind a Neo4j cluster server

You can use the `neo4j-admin server unbind` command to remove and archive the cluster state of a cluster server so that it can rebind to a cluster.

[[unbind-command-syntax]]
== Syntax

The `neo4j-admin server unbind` command has the following syntax:

----
neo4j-admin server unbind [-h] [--expand-commands] [--verbose]
                          [--archive-cluster-state[=true|false]]
                          [--additional-config=<file>]
                          [--archive-path=<path>]
----

[[unbind-command-options]]
== Options

The `neo4j-admin server unbind` command has the following options:

.`neo4j-admin server unbind` options
[options="header", cols="5m,6a,2m"]
|===
| Option
| Description
| Default

|--additional-config=<file>footnote:[See xref:tools/neo4j-admin/index.adoc#_configuration[Tools -> Configuration] for details.]
|Configuration file with additional configuration.
|

|--archive-cluster-state[=true\|false]
|Enable or disable the cluster state archiving.
|false

|--archive-path=<path>
|Destination (file or folder) of the cluster state archive.
|

|--expand-commands
|Allow command expansion in config value evaluation.
|

|-h, --help
|Show this help message and exit.
|

|--verbose
|Enable verbose output.
|
|===

[[unbind-command-limitatations]]
== Limitations

The Neo4j server must be shut down before running the `neo4j-admin server unbind` command.

[[unbind-command-usage]]
== Usage

You can use the `neo4j-admin server unbind` command to remove the cluster state of a cluster server, turn a cluster server into a standalone server, or remove and archive the cluster state of a cluster server.

=== Remove the cluster state of a server

To remove the cluster state of a server, run the `neo4j-admin server unbind` command from the _<NEO4J_HOME>_ folder of that server.
When restarted, an unbound server rejoins the cluster as a new server and has to be enabled using the `ENABLE SERVER` command.

[WARNING]
====
Note that the `unbind` command preserves all database stores on the server.
When the unbound server is restarted and enabled, it is seen as an entirely new server.
Therefore, there is no guarantee that the allocator will pick this server to host the same databases.
This may lead to having orphaned database stores on this server.
====

=== Turn a cluster member into a standalone server

To start the Neo4j server in single (standalone) mode after unbinding it from the cluster, verify that xref:configuration/configuration-settings.adoc#config_initial.server.mode_constraint[`initial.server.mode_constraint`] is set to `NONE` in xref:configuration/neo4j-conf.adoc[The neo4j.conf file].

=== Archive cluster state

If something goes wrong and debugging is needed, you can archive the cluster state, from the _<NEO4J_HOME>_ folder, run the `neo4j-admin server unbind` command with the arguments `--archive-cluster-state=true` and `--archive-path=<destination-folder>`:

[source, shell]
----
bin/neo4j-admin server unbind --archive-path=/path/to/archive-folder --archive-cluster-state=true
----

The default resultant file is named:

[result]
----
unbound_cluster_state.<YYYYMMDDHH24MM>.zip
----
