:description: How to remove cluster state data from a Neo4j server using `neo4j-admin unbind`.
[[neo4j-admin-unbind]]
= Unbind a Neo4j cluster server

You can use the `neo4j-admin unbind` command to remove the cluster state of a cluster member.

[[unbind-command-syntax]]
== Syntax

The `neo4j-admin unbind` command has the following syntax:

----
neo4j-admin unbind [--verbose]
                   [--expand-commands]
                   [--archive-cluster-state=<true/false>]
                   [--archive-path=<path>]
----

[[unbind-command-options]]
== Options

The `neo4j-admin unbind` command has the following options:

.Options
[options="header", cols="2m,1,3"]
|===
| Option                     | Default          | Description
| `--verbose`                |                  | Enable verbose output.
| `--expand-commands`        |                  | Allow command expansion in config value evaluation.
| `--archive-cluster-state`  | false            | Enable or disable the cluster state archiving.
| `--archive-path`           |                  | Destination (file or folder) of the cluster state archive.
|===

[[unbind-command-limitatations]]
== Limitations

The Neo4j server process must be shut down before running the `neo4j-admin unbind` command.

[[unbind-command-usage]]
== Examples

You can use the `neo4j-admin unbind` command to:

* Remove the cluster state of a server. This means that once restarted this server will rejoin the cluster as a new server and will have to be enabled using ENABLE SERVER command.

[WARNING]
====
If you unbind a server, then all of the database stores on that server will be preserved. Once this server is restated and enabled it will be seen as an entirely new server and therefore there is no guarantee that the allocator will pick this server to host the same databases. This may lead to having orphaned database stores on this server.
====

[[unbind-command-archive]]
== Archive cluster state

To archive the cluster state, from the _<neo4j-home>_ folder, run the `neo4j-admin unbind` command with the arguments `--archive-cluster-state=true` and `--archive-path=<destination-folder>`:

[source, shell]
----
bin/neo4j-admin unbind --archive-path=/path/to/archive-folder --archive-cluster-state=true
----

The default resultant file is named:

[result]
----
unbound_cluster_state.<YYYYMMDDHH24MM>.zip
----
