:description: How to remove cluster state data from a Neo4j server using `neo4j-admin server unbind`.
[role=enterprise-edition]
[[neo4j-admin-unbind]]
= Unbind a Neo4j cluster server

You can use the `neo4j-admin server unbind` command to remove and archive the cluster state of a cluster server so that it can rebind to a cluster.

[WARNING]
====
Due to the new clustering architecture in Neo4j 5.x, the behavior of the `unbind` command has changed significantly compared to Neo4j 4.4.

Running the `unbind` command on any number of servers may result in the loss of cluster quorum, severely affecting clustering functionality.
Therefore, it is strongly recommended to consult with Neo4j Support before using the `unbind` command.

In Neo4j 5.x, use the `unbind` command only when troubleshooting **a specific server** and remember there is no guarantee that the allocator will reassign the same databases to this server, potentially resulting in orphaned database stores.

The `unbind` command preserves all database stores on the server; and when the unbound server is restarted, it is seen as an entirely new server.
Therefore, it will not host any of the databases it hosted before the operation.

In Neo4j 5.x, the `unbind` command cannot be used to convert a cluster member into a standalone server.
Instead, it is recommended to take backups, create the standalone server, and then use those backups to restore the databases.
====

[[unbind-command-syntax]]
== Syntax

The `neo4j-admin server unbind` command has the following syntax:

----
neo4j-admin server unbind [-h] [--expand-commands] [--verbose]
                          [--archive-cluster-state[=true|false]]
                          [--additional-config=<file>]
                          [--archive-path=<path>]
----

[[unbind-command-options]]
== Options

The `neo4j-admin server unbind` command has the following options:

.`neo4j-admin server unbind` options
[options="header", cols="5m,6a,2m"]
|===
| Option
| Description
| Default

|--additional-config=<file>footnote:[See xref:tools/neo4j-admin/index.adoc#_configuration[Tools -> Configuration] for details.]
|Configuration file with additional configuration.
|

|--archive-cluster-state[=true\|false]
|Enable or disable the cluster state archiving.
|false

|--archive-path=<path>
|Destination (file or folder) of the cluster state archive.
|

|--expand-commands
|Allow command expansion in config value evaluation.
|

|-h, --help
|Show this help message and exit.
|

|--verbose
|Enable verbose output.
|
|===

[[unbind-command-limitatations]]
== Limitations

The Neo4j server must be shut down before running the `neo4j-admin server unbind` command.

[[unbind-command-usage]]
== Usage

You can use the `neo4j-admin server unbind` command to remove or archive the cluster state of a cluster server.

=== Remove the cluster state of a server

To remove the cluster state of a server, run the `neo4j-admin server unbind` command from the _<NEO4J_HOME>_ folder of that server.
When restarted, an unbound server rejoins the cluster as a new server and has to be enabled using the `ENABLE SERVER` command.

=== Archive cluster state

If something goes wrong and debugging is needed, you can archive the cluster state, from the _<NEO4J_HOME>_ folder, run the `neo4j-admin server unbind` command with the arguments `--archive-cluster-state=true` and `--archive-path=<destination-folder>`:

[source, shell]
----
bin/neo4j-admin server unbind --archive-path=/path/to/archive-folder --archive-cluster-state=true
----

The default resultant file is named:

[result]
----
unbound_cluster_state.<YYYYMMDDHH24MM>.zip
----
