:description: How to import a database from an existing Neo4j instance into Neo4j Aura using `neo4j-admin database upload`.
[role=aura]
[[neo4j-admin-upload-to-aura]]
= Upload to Neo4j Aura

The `neo4j-admin database upload` command uploads a local Neo4j database dump into a Neo4j Aura instance. +
The following table shows the compatibility between the dump version that you want to upload and the version of the Neo4j Aura instance.

[options="header" cols="50%, 50%"]
|===
| Dump version 
| Aura version

| v5.x
| v5.latest

| v4.4
| v4 and v5.latest

| v4.3
| v4 and v5.latest
|===

[NOTE]
====
This operation is secured and TLS encrypted end to end.
====

== Syntax

The `neo4j-admin database upload` command has the following syntax:

----
neo4j-admin database upload [-h] 
                            [--expand-commands]
                            [--verbose]
                            [--overwrite-destination[=true|false]]
                            --from-path=<path> 
                            [--to=<destination>]
                            [--to-password=<password>]
                            --to-uri=<uri>
                            [--to-user=<username>]
                            <database>                           

----

== Options

The `neo4j-admin database upload` command has the following options:

.Options
[options="header" cols="1m,2a,3a"]
|===
| Option
| Possible values
| Description

| -h, --help
|
| Show this help message and exit.

| --expand-commands
|
| Allow command expansion in config value evaluation.

| --verbose
|
| Enable verbose output.

| --overwrite-destination
| `true` or `false` (Default: `false`)
| Overwrite the data in the target database.

| --from-path
| `<path>`
| Path to a directory containing a database dump to upload.

| --to
| `<destination>` (Default: `aura`)
| The destination for the upload.

| --to-password
| `<password>`
| The password for the target Aura instance where you will upload this database.
If you do not provide a password, you will be prompted to provide one.
Alternatively, the `NEO4J_PASSWORD` environment variable can be used.

| --to-uri
| `<uri>`
| The Bolt URI of the target Aura database.
For example, `neo4j+s://your-aurainstanceid.databases.neo4j.io`.

| --to-user
| `<username>`
| The username of the target Aura instance where you will upload this database.
If you do not provide a username, you will be prompted to provide one.
Alternatively, you can use the `NEO4J_USERNAME` environment variable.

| <database>
|
| Name of the database dump that should be uploaded. 
|===

== Limitations

* A Neo4j Aura instance must already be provisioned and running.

== Output

If the `upload` function completes successfully, it exits with the following logline:

----
“Your data was successfully pushed to Aura and is now running”.
----

If the `upload` function encounters an error at any point, you will be provided with instructions on how to try again or to contact Neo4j Aura support.

Additionally, you can use the `--verbose` option to enable verbose output.

== Example

The following examples show how to use the `neo4j-admin database upload` command to upload a database dump to a Neo4j Aura instance.
You need your Aura instance URI (neo4j+s://your-databaseid.databases.neo4j.io), as can be seen in the Aura console, and your Aura instance password.

[NOTE]
====
You should use the `--overwrite=true` option to overwrite the target database.
Otherwise, the command aborts and throws an error.
====

[source, shell,role=nocopy]
----
$neo4j-home> bin/neo4j-admin database upload <database> --from-path=<path-to-directory-with-database-dump> --to-uri=<neo4j+s://your-databaseid.databases.neo4j.io> --overwrite-destination=true
Neo4j cloud database user name: neo4j
Neo4j cloud database password:
Upload
....................  10%
....................  20%
....................  30%
....................  40%
....................  50%
....................  60%
....................  70%
....................  80%
....................  90%
.................... 100%
We have received your export and it is currently being loaded into your Aura instance.
You can wait here, or abort this command and head over to the console to be notified of when your database is running.
Import progress
....................  10%
....................  20%
....................  30%
....................  40%
....................  50%
....................  60%
....................  70%
....................  80%
....................  90%
.................... 100%
Your data was successfully pushed to Aura and is now running.
----
