[role=enterprise-edition]
[[cc-install-cores]]
= Install Neo4j cluster cores

Getting everything to work in Kubernetes requires that certain K8s objects have specific names that are referenced elsewhere.
Each Neo4j instance is a Helm “release” and has a _release name_.
Release name must consist of lower case alphanumeric characters, `-` or `.`, and must start and end with an alphanumeric character.

[NOTE]
====
The following example installations use `core-1`, `core-2`, `core-3` as release names for the core members.
====

. Install each core member individually using the deployment _core-<num>.values.yaml_ file created in xref:kubernetes/quickstart-cluster/create-value-file.adoc[Create Helm deployment values files] and the _neo4j/neo4j-cluster-core_ Helm chart.
.. Install `core-1`.
+
[source, shell, subs="attributes"]
----
helm install core-1 neo4j/neo4j-cluster-core -f core-1.values.yaml
----
+
.Example output
[source, role=noheader, subs="attributes"]
----
NAME: core-1
LAST DEPLOYED: Fri Nov  5 14:32:10 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing neo4j-cluster-core.

Your release "core-1" has been installed .

The neo4j user's password has been set to "my-password".

This release creates a single Neo4j Core instance. It  will not become ready until it is able to form a working Neo4j cluster by joining other Neo4j Core instances. To create a working cluster requires at least 3 Core instances.

Once you have a working Neo4j cluster you must install at least one Neo4j Service before you can connect applications to Neo4j. Available Neo4j services are:
  neo4j-headless-service - for connecting applications running inside Kubernetes to Neo4j
  neo4j-loadbalancer - for connecting applications running outside Kubernetes to Neo4j

Graphs are everywhere!
----

.. Install `core-2`.
+
[source, shell, subs="attributes"]
----
helm install core-2 neo4j/neo4j-cluster-core -f core-2.values.yaml
----
+
.Example output
[source, role=noheader, subs="attributes"]
----
NAME: core-2
LAST DEPLOYED: Fri Nov  5 14:36:14 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing neo4j-cluster-core.

Your release "core-2" has been installed .

The neo4j user's password has been set to "my-password".

This release creates a single Neo4j Core instance. It  will not become ready until it is able to form a working Neo4j cluster by joining other Neo4j Core instances. To create a working cluster requires at least 3 Core instances.

Once you have a working Neo4j cluster you must install at least one Neo4j Service before you can connect applications to Neo4j. Available Neo4j services are:
  neo4j-headless-service - for connecting applications running inside Kubernetes to Neo4j
  neo4j-loadbalancer - for connecting applications running outside Kubernetes to Neo4j

Graphs are everywhere!
----

.. Install `core-3`.
+
[source, shell, subs="attributes"]
----
helm install core-3 neo4j/neo4j-cluster-core -f core-3.values.yaml
----
+
.Example output
[source, role=noheader, subs="attributes"]
----
NAME: core-3
LAST DEPLOYED: Fri Nov  5 14:36:32 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing neo4j-cluster-core.

Your release "core-3" has been installed .

The neo4j user's password has been set to "my-password".

This release creates a single Neo4j Core instance. It  will not become ready until it is able to form a working Neo4j cluster by joining other Neo4j Core instances. To create a working cluster requires at least 3 Core instances.

Once you have a working Neo4j cluster you must install at least one Neo4j Service before you can connect applications to Neo4j. Available Neo4j services are:
  neo4j-headless-service - for connecting applications running inside Kubernetes to Neo4j
  neo4j-loadbalancer - for connecting applications running outside Kubernetes to Neo4j

Graphs are everywhere!
----
+
[NOTE]
====
If you have not passed a password for the `neo4j` user, the Neo4j Helm chart has automatically generated one for you.
The password is the same for all cluster members.

You can find it in the Helm install outputs.
Make a note of it.
====

. Verify that the core members have formed a cluster.
See the next section xref:kubernetes/quickstart-cluster/verify-cluster-formation.adoc[Verify the Neo4j cluster formation].
