[role=enterprise-edition]
[[cc-install-rr]]
= Install the Neo4j read replicas

Before you can install the read replica, you need to verify that the core members have formed a cluster.
For more information, see xref:kubernetes/quickstart-cluster/verify-cluster-formation.adoc[Verify the Neo4j cluster formation].

[NOTE]
====
Read Replicas can only be installed after a cluster of at least three cores is formed.
Otherwise, the helm install command throws the following error:
----
Error: template: neo4j-cluster-read-replica/templates/neo4j-auth.yaml:5:8: executing "neo4j-cluster-read-replica/templates/neo4j-auth.yaml" at <include "neo4j.checkIfClusterIsPresent" .>: error calling include: template: neo4j-cluster-read-replica/templates/_helpers.tpl:84:11: executing "neo4j.checkIfClusterIsPresent" at <fail "Cannot install Read Replica until a cluster of 3 or more cores is formed">: error calling fail: Cannot install Read Replica until a cluster of 3 or more cores is formed
----
====

. Install the Neo4j read replica using `rr-1` as a release name, the deployment _rr-1.values.yaml_ file created in xref:kubernetes/quickstart-cluster/create-value-file.adoc[Create value.yaml files], and the _neo4j/neo4j-cluster-read-replica_ Helm chart:
+
[source, shell, subs="attributes"]
----
helm install rr-1 neo4j/neo4j-cluster-read-replica -f rr-1.values.yaml
----
+
.Example output
[source, role=noheader, subs="attributes"]
----
NAME: rr-1
LAST DEPLOYED: Fri Nov  5 16:15:13 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing neo4j-cluster-read-replica.

Your release "rr-1" has been installed .

The neo4j user's password has been set to "my-password".

This release creates a single Neo4j Read Replica instance. It  will not become ready until it is able to join a working Neo4j cluster.

Graphs are everywhere!
----

. Verify that the read replica has joined the cluster.
See the next section xref:kubernetes/quickstart-cluster/verify-rr-joined.adoc[Verify the read replica has joined the cluster].

