:description: Prerequisites for deploying a Neo4j cluster to a cloud or a local Kubernetes cluster using Neo4j Helm Charts.
[role=enterprise-edition]
[[cc-prerequisites]]
= Prerequisites

Before you can deploy a Neo4j cluster on Kubernetes, you need to:

[[cc-general-prerequisites]]
== General prerequisites

* xref:kubernetes/helm-charts-setup.adoc[Configure the Neo4j Helm Chart repository].
* Obtain a valid license for Neo4j Enterprise Edition.
For more information, see https://neo4j.com/licensing/ or write to licensing@neo4j.com.
* Install the Kubernetes client command-line tool `kubectl` (https://kubernetes.io/docs/tasks/tools/).
* Set up a Kubernetes cluster with sufficient CPU and memory for your Neo4j deployment.
+
[NOTE]
====
This guide works with minimum CPU and memory allocated per Neo4j instance.
However, the Neo4j system requirements largely depend on the use of the software. 
Therefore, for running Neo4j in development or production environments, please refer to xref:installation/requirements.adoc[].
====
+
If you do not have a Kubernetes cluster, you can configure a multi-node one as per your environment, see the next section xref:kubernetes/quickstart-cluster/prerequisites.adoc#cc-env-prerequisites[Environment-specific prerequisites].

[[cc-env-prerequisites]]
== Environment-specific prerequisites

Select the tab as per your Kubernetes environment and complete all prerequisites on it.

[.tabbed-example]
==========
[.include-with-gke]
======
. Install the `gcloud` command-line interface (CLI) (https://cloud.google.com/sdk/docs/install).
. All the shell commands in this guide assume that the GCP Project, compute zone, and region to use, have been set using the 
`CLOUDSDK_CORE_PROJECT`, `CLOUDSDK_COMPUTE_ZONE`, and `CLOUDSDK_COMPUTE_REGION` environment variables, for example:
+
[source, shell]
----
export CLOUDSDK_CORE_PROJECT="neo4j-helm"
export CLOUDSDK_COMPUTE_ZONE="europe-west6-c"
export CLOUDSDK_COMPUTE_REGION="europe-west6"
export CLOUDSDK_CONTAINER_CLUSTER="my-neo4j-gke-cluster"
----
. If you do not have a Google Kubernetes Engine (GKE) cluster, you can create a multi-node cluster (one node per Neo4j instance) using:
+
[source, shell]
----
gcloud container clusters create my-neo4j-gke-cluster --num-nodes=<num> --machine-type "e2-standard-2"
----
+
[NOTE]
====
e2-standard-2 is the minimum instance type required for running the examples of this startup guide on GKE.
====
. Configure `kubectl` to use your GKE cluster using:
+
[source, shell]
----
gcloud container clusters get-credentials my-neo4j-gke-cluster
----
+
[source, role=noheader]
----
Fetching cluster endpoint and auth data.
kubeconfig entry generated for my-neo4j-gke-cluster.
----
======

[.include-with-aws]
======
. Install the `aws` command-line interface (CLI) (https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html).
Make sure you complete the AWS configuration step (https://docs.aws.amazon.com/cli/latest/userguide/getting-started-quickstart.html).
. Install the `eksctl` command-line interface (CLI) (https://docs.aws.amazon.com/eks/latest/userguide/getting-started-eksctl.html).
. All the shell commands in this guide assume that the AWS region and availability zone to use, have been set using the `AWS_DEFAULT_REGION` and `AWS_AVAILABILITY_ZONE` environment variables, for example:
+
[source, shell]
----
export AWS_DEFAULT_REGION="eu-west-1"
export AWS_AVAILABILITY_ZONE="eu-west-1c"
----
. If you do not have an AWS Elastic Kubernetes Service (EKS) cluster, you can create a multi-node cluster (one node per Neo4j instance) using the following command:
+
[NOTE]
====
This command requires that you have a public key named _id_rsa.pub_.
If you do not have one, you can generate it by running:

[source, shell]
----
ssh-keygen -t rsa -C "your-name@example.com"
----
====
+
[source, shell]
----
eksctl create cluster --name "my-neo4j-eks-cluster" --region "${AWS_DEFAULT_REGION}" --nodegroup-name "neo4j-nodes" --node-zones "${AWS_AVAILABILITY_ZONE}" --nodes-min 1 --nodes-max 4 --node-type c4.xlarge --nodes 4 --node-volume-size 10 --ssh-access --with-oidc
----
+
[NOTE]
====
If you want to use high-performance SSD `(gp3)` disks for the database or manually allocate disks, you must install the EBS CSI Driver.
See the link:https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html[AWS documentation] for instructions on installing the driver.
====

. Configure `kubectl` to use your EKS cluster using:
+
[source, shell]
----
aws eks update-kubeconfig --name my-neo4j-eks-cluster
----
======

[.include-with-azure]
======
. Install the `az` command-line interface (CLI) (https://docs.microsoft.com/en-us/cli/azure/install-azure-cli).
. Verify that you have a Resource Group with:
  * An Azure Kubernetes Service (AKS) cluster.
  * The AKS cluster principal needs to be assigned roles that allow it to manage Microsoft.Compute/disks in the Resource Group.
. Set the Resource group and the location to use as defaults using:
+
[source, shell]
----
az configure --defaults group=<MyResourceGroup>
az configure --defaults location=<MyAzureLocation>
----
+
[NOTE]
====
If you do not have an AKS cluster, follow the steps to create a multi-node cluster (one node per Neo4j instance).

. Create a cluster by running:
+
[source, shell]
----
az aks create --name my-neo4j-aks-cluster --node-count=<num>
----
+
. Configure `kubectl` to use your AKS cluster using:
+
[source, shell]
----
az aks get-credentials --name my-neo4j-aks-cluster --admin
----
====

======
==========

