:description: Neo4j Helm chart for cluster deployments.
[[cc-server-setup]]
= Neo4j Helm chart for cluster deployments

To offer the flexibility required to cluster users, the Helm chart for clusters takes a modular approach: the typical cluster deployment requires several Helm chart installations. 
For example, a cluster with three servers requires installing the _neo4j_ chart three times.
By separating the charts up, users can create a different topology of Neo4j and a different topology in their Kubernetes clusters to suit their needs.

The following diagram is a schematic representation of the Helm charts involved and the Kubernetes and Cloud resources they instantiate when installed:

.Neo4j cluster setup
image::cluster-on-k8s.svg[Example of Neo4j cluster setup in Kubernetes,width=700,role=popup]

The diagram shows an example of a Neo4j cluster setup with three servers.
The Kubernetes setup includes a headless service for accessing the cluster from inside Kubernetes and a load-balancer service for accessing the cluster from outside Kubernetes. 
