[role=enterprise-edition]
[[cc-uninstall-cleanup]]
= Uninstall the Neo4j cluster and clean up the created resources

[[uninstall-neo4j]]
== Uninstall all Neo4j Helm deployments

. Uninstall each of the cluster members (both the cores and read replica) and the services using their Helm release names:
+
[source, shell]
----
helm uninstall core-1 core-2 core-3 rr-1 lb headless
----
+
[source, result, role=noheader]
----
release "core-1" uninstalled
release "core-2" uninstalled
release "core-3" uninstalled
release "rr-1" uninstalled
release "lb" uninstalled
release "headless" uninstalled
----

[[si-cleanup-resources]]
== Fully remove all the data and resources

Uninstalling the Helm releases does not remove the created resources and data.
Therefore, after uninstalling the helm deployments, you also have to delete all the data and resources.

[.tabbed-example]
=====
[.include-with-gke]
======

. Display all data associated with each of the GCP persistent disks you have created, for example:
+
[source, shell]
----
gcloud compute disks describe "core-disk-1"
----
+
[NOTE]
====
If you re-create Neo4j with the same settings, it will pick up the same disk again, and all the data will still be on it.

Even if the GKE cluster is deleted, the persistent disks with the Neo4j data will still exist.
====
+
. Delete each of the GCP persistent disks you have created in xref:kubernetes/quickstart-cluster/create-pv.adoc[Create a persistent volume for each cluster member] using the following command and the name of the disk, for example:
+
[source, shell]
----
gcloud compute disks delete core-disk-1
----
+
[source, role=noheader]
----
The following disks will be deleted:
 - [core-disk-1] in [europe-west6-c]
Do you want to continue (Y/n)?  y
Deleted [https://www.googleapis.com/compute/v1/projects/neo4j-helm/zones/europe-west6-c/disks/core-disk-1].
----
+
[TIP]
====
If you want to delete the entire GKE Kubernetes cluster, run:

[source, shell]
----
gcloud container clusters delete my-neo4j-gke-cluster
----
====
======

[.include-with-aws]
======

. Display all data associated with the AWS EBS disks by running:
+
[source, shell]
----
aws ec2 describe-volumes --filters Name=tag:volume,Values=core-disk-1,core-disk-2,core-disk-3,rr-disk-1 --query "Volumes[*].{ID:VolumeId}" --output text
----
+
[NOTE]
====
If you re-create Neo4j with the same settings, it will pick up the same disk again, and all the data will still be on it.

Even if you delete the EKS cluster, the EBS disks with the Neo4j data will still exist.
Note that the disk _will_ be deleted if its Resource Group is deleted.
====
+
. Delete each of the AWS EBS disks you have created in xref:kubernetes/quickstart-cluster/create-pv.adoc[Create a persistent volume for each cluster member] using the following command and the volume ID, for example:
+
[source, shell]
----
aws ec2 delete-volume --volume-id "<volume id>"
----
+
[TIP]
====
If you are sure that you want to delete the entire EKS Kubernetes cluster, run:

[source, shell]
----
eksctl delete cluster my-neo4j-eks-cluster
----
====

======

[.include-with-azure]
======

. Display all data associated with the Azure managed disks by running:
+
[source, shell]
----
az disk show --name "core-disk-1"
----
+
[NOTE]
====
If you re-create Neo4j with the same settings, it will pick up the same disk again and all the data will still be on it.

Even if you delete the AKS cluster, the managed disk with the Neo4j data will still exist.
Note that the disk _will_ be deleted if its Resource Group is deleted.
====
+
. Delete each of the Azure managed disks you have created in xref:kubernetes/quickstart-cluster/create-pv.adoc[Create a persistent volume for each cluster member] using the following command and the disk name, for example:
+
[source, shell]
----
az disk delete --name "core-disk-1"
----
+
[TIP]
====
If you are sure that you want to delete the entire AKS Kubernetes cluster, run:

[source, shell]
----
az aks delete --name my-neo4j-aks-cluster
----
====

======
=====
