[[administration-constraints-create-a-unique-constraint-with-specified-index-provider-and-configuration]]
== Create a unique constraint with specified index provider and configuration ==
To create a unique constraint with a specific index provider and configuration for the backing index, the `OPTIONS` clause is used.
Valid values for the index provider are `native-btree-1.0` (deprecated), `lucene+native-3.0` (deprecated), and `range-1.0` (future index), default is `native-btree-1.0`.
The index type of the backing index is set depending on the provider, the `range-1.0` generates a <<indexes-future-indexes, future range index>> while the other providers generates a b-tree index.
The range index have no configuration settings. The valid b-tree configuration settings are

* `spatial.cartesian.min`
* `spatial.cartesian.max`
* `spatial.cartesian-3d.min`
* `spatial.cartesian-3d.max`
* `spatial.wgs-84.min`
* `spatial.wgs-84.max`
* `spatial.wgs-84-3d.min`
* `spatial.wgs-84-3d.max`

Non-specified settings have their respective default values.

In 4.4, b-tree index-backed constraints are still the correct alternative to use.

.Query
include::includes/administration-constraints-create-a-unique-constraint-with-specified-index-provider-and-configuration.query.adoc[]


Specifying index provider and configuration can be done individually.

.Result
include::includes/administration-constraints-create-a-unique-constraint-with-specified-index-provider-and-configuration.result.adoc[]

.Try this query live
include::includes/administration-constraints-create-a-unique-constraint-with-specified-index-provider-and-configuration.console.adoc[]

