:description: This section explains how to use Cypher to manage authentication and authorization at the user level using Cypher.

[role=label--new-5.24]
[[access-control-auth-objects]]
= Auth objects label:enterprise-edition[]

User Auth Objects provide a way to configure authentication and authorization at the user-level using Cypher.

Using the database in Auth Object mode mandates that only users with a corresponding Auth Object in the database can authenticate and authorize. This mode is enabled by changing the `dbms.security.require_local_user` configuration setting to `true`.

This gives us a way to link externally-defined users to the Neo4j internal user model. The internal model can define things such as roles (authorization), `SUSPENDED` status, `HOME DATABASE`, and metadata such as the unique displayed name of the user.

== Use Cases
. Provisioning different auth providers (including native username/password auth) for different users.
. Setting an arbitrary reader-friendly username for a user whilst using an external unique identifier (like `sub` for OIDC auth, which is itself not a reader-friendly value).
. Setting `HOME DATABASE` for externally authenticated users.
. Setting `SUSPENDED` status for an externally authenticated user.
. Using native authorization to manage roles for externally authenticated users.
. Retaining full control of which users can authenticate from within the database.

== How it works
When a user authenticates, their identifying attributes are checked against the relevant property of the Auth Objects in the database. If there is a match, then the user is linked to the Neo4j user and authorized according to the dbms security configuration settings which match the provider of the matching Auth Object.

The way that the matching lookup is done depends on the type of provider. For example:

- For an OIDC provider, the claim configured by xref:configuration/configuration-settings.adoc#config_dbms.security.oidc.-provider-.claims.username[`dbms.security.oidc.mysso.claims.username`] (default `sub`) is taken from the token and is used to look up an Auth Object whose `ID` and `provider` properties match the `sub` and provider respectively of the OIDC provider.
- For an LDAP provider, the `dn` is used to look up an auth Auth Object with a `provider` property of `ldap` and an `ID` property which matches the supplied `dn`.
- For the `native` (username/password) provider, the supplied username itself is used to look up the Auth Object.

== Enabling Auth Objects mode
When the configuration setting `dbms.security.require_local_user` is set to `true`, the lookups described above will be performed when the user authenticates, and a matching user Auth Object *must* exist in order for a user to be able to successfully authenticate and authorize.

== Examples
For examples of how to use Auth Objects with different authentication providers, see the following sections:

- xref:authentication-authorization/sso-integration.adoc#auth-sso-auth-objects[SSO Auth Object Examples]
- xref:authentication-authorization/manage-users.adoc#access-control-create-users[`native` Auth Object Examples]
- xref:authentication-authorization/ldap-integration.adoc#auth-ldap-auth-objects[LDAP Auth Object Examples]

