:description: This section explains how to use Cypher to manage authentication and authorization at the user level using Cypher.

[role=label--new-5.24]
[[access-control-auth-providers]]
= User Auth Providers label:enterprise-edition[]

Authentication and authorization can be controlled on a user-level using Cypher by setting Auth Providers on users.

In order to make use of Auth Providers, you need to set the `dbms.security.require_local_user` configuration setting to `true`.
This setting mandates that only users with a corresponding Auth Provider in the database can authenticate and authorize.

Auth Providers give you a way to link externally-defined users (e.g. in a 3rd party ID provider like OIDC or LDAP) to the Neo4j internal User model.

The internal model can define things such as roles (authorization), `SUSPENDED` status, `HOME DATABASE`, and metadata such as the unique displayed name of the user.

For consistency you can also define `native` (password-based) auth using the Auth Provider syntax, including native-only users (i.e. users who can only authenticate with a password).

== Use Cases
. Provisioning different auth providers (including native username/password auth) for different users.
. Setting an arbitrary reader-friendly username for a user whilst using an external unique identifier (like `sub` for OIDC auth, which is itself not a reader-friendly value).
. Setting `HOME DATABASE` for externally authenticated users.
. Setting `SUSPENDED` status for an externally authenticated user.
. Using native authorization to manage roles for externally authenticated users.
. Retaining full control of which users can authenticate from within the database.

== How it works
When a user authenticates, their identifying attributes are checked against the relevant property of the Auth Providers in the database.
If there is a match, then the user is linked to the Neo4j user and authorized according to the dbms security configuration settings which match the provider name of the matching Auth Provider.

The way that the matching lookup is done depends on the type of provider. For example:

- For an OIDC provider, the claim configured by xref:configuration/configuration-settings.adoc#config_dbms.security.oidc.-provider-.claims.username[`dbms.security.oidc.mysso.claims.username`] (default `sub`) is taken from the token and is used to look up an Auth Provider whose `ID` and `provider` properties match the `sub` and provider respectively of the OIDC provider.
- For an LDAP provider, the `dn` is used to look up an Auth Provider with a `provider` property of `ldap` and an `ID` property which matches the supplied `dn`.
- For the `native` (username/password) provider, the supplied username itself is used to look up the Auth Provider.

== Enabling User Auth Providers mode
When the configuration setting `dbms.security.require_local_user` is set to `true`, the lookups described above will be performed when the user authenticates, and a matching user Auth Provider *must* exist in order for a user to be able to successfully authenticate and authorize.

== Examples
For examples of how to use Auth Providers with different authentication providers, see the following sections:

- xref:authentication-authorization/sso-integration.adoc#auth-sso-auth-providers[SSO Auth Provider Examples]
- xref:authentication-authorization/manage-users.adoc#access-control-create-users[Native Auth Provider Examples]
- xref:authentication-authorization/ldap-integration.adoc#auth-ldap-auth-providers[LDAP Auth Provider Examples]

