:description: How to use Cypher to manage load privileges.

////
[source, cypher, role=test-setup]
----
CREATE ROLE roleLoadAllData
----
////

[role=enterprise-edition aura-db-enterprise]
[[access-control-load-privileges]]
= Load privileges

_This feature was released in Neo4j 5.13._

This section explains how to use Cypher to manage load privileges.
All load privileges apply to the whole system.
Like DBMS privileges, they do not belong to one specific database or graph.
For more details on the differences between graphs, databases, and the DBMS, refer to link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/introduction/cypher_neo4j/[Cypher Manual -> Cypher and Neo4j].

image::privileges_grant_and_deny_syntax_load_privileges.svg[width="800", title="Syntax of GRANT and DENY load Privileges"]

// TODO: add image later when there is more than one LOAD privilege
//image::privileges_hierarchy_load.svg[title="Load privileges hierarchy"]

The load privileges apply to the Cypher link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/clauses/load-csv/[`LOAD CSV` clause], deciding whether or not the data can be loaded from the given source.

The load privileges are assigned using Cypher administrative commands.
They can be granted, denied, and revoked in the same way as other privileges.
For more details, see xref:authentication-authorization/manage-privileges.adoc[RBAC and fine-grained privileges].

.Load privileges command syntax
[options="header", width="100%", cols="3a,2"]
|===
| Command | Description

| [source, syntax, role=noheader]
GRANT [IMMUTABLE] LOAD
  ON ALL DATA
  TO role[, ...]
| Enables the specified roles to load external data in queries.

|===

[NOTE]
====
More details about the syntax descriptions can be found xref:database-administration/syntax.adoc[Cypher syntax for administration commands].
====

Unlike other privileges, the `LOAD` privilege is not granted, denied, or revoked on `DBMS`, `Database`, or `Graph`, but instead on the data source to load from.
Adding `ON ALL DATA` means a role has the privilege to load data from all sources.

[[access-control-load-all-data]]
== The `ALL DATA` privilege

The load privilege on `ALL DATA` enables or disables loading data.
If granted, the user can load data from any source.
If missing or denied, no data can be loaded at all.

For example, the below query grants users with the role `roleLoadAllData` the ability to load data with `LOAD CSV`:

[source, cypher, role=noplay]
----
GRANT LOAD ON ALL DATA TO roleLoadAllData
----

The below query lists all privileges for the role `roleLoadAllData` as commands:

[source, cypher, role=noplay]
----
SHOW ROLE roleLoadAllData PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT LOAD ON ALL DATA TO `roleLoadAllData`"
a|Rows: 1
|===

The `LOAD ON ALL DATA` privilege is granted to the `PUBLIC` role by default.