:description: How to use Cypher to manage load privileges.
:page-role: enterprise-edition aura-db-business-critical aura-db-dedicated
////
[source, cypher, role=test-setup]
----
CREATE ROLE roleLoadAllData
CREATE ROLE roleLoadCidr
----
////

[[access-control-load-privileges]]
= Load privileges

_This feature is available from Neo4j 5.13._

This section explains how to use Cypher to manage load privileges.
All load privileges apply to the whole system.
Like DBMS privileges, they do not belong to one specific database or graph.
For more details on the differences between graphs, databases, and the DBMS, refer to link:{neo4j-docs-base-uri}/cypher-manual/5/introduction/cypher-neo4j/[Cypher Manual -> Cypher and Neo4j].

image::privileges_grant_and_deny_syntax_load_privileges.svg[width="800", title="Syntax of GRANT and DENY load Privileges"]

// TODO: add image later when there is more than one LOAD privilege
//image::privileges_hierarchy_load.svg[title="Load privileges hierarchy"]

The load privileges apply to the Cypher link:{neo4j-docs-base-uri}/cypher-manual/5/clauses/load-csv/[`LOAD CSV` clause], deciding whether or not the data can be loaded from the given source.

== Load privileges syntax

The load privileges are assigned using Cypher administrative commands.
They can be granted, denied, and revoked in the same way as other privileges.
For more details, see xref:authentication-authorization/manage-privileges.adoc[RBAC and fine-grained privileges].

.Load privileges command syntax
[options="header", width="100%", cols="3a,2"]
|===
| Command | Description

| [source, syntax]
GRANT [IMMUTABLE] LOAD
  ON ALL DATA
  TO role[, ...]
| Enables the specified roles to load external data in queries.

| [source, syntax]
GRANT [IMMUTABLE] LOAD
  ON CIDR cidr
  TO role[, ...]
| Enables the specified roles to load external data from the given CIDR range in queries.label:new[Introduced in 5.16]

|===

[NOTE]
====
More details about the syntax descriptions can be found xref:database-administration/syntax.adoc[Cypher syntax for administration commands].
====

Unlike other privileges, the `LOAD` privilege is not granted, denied, or revoked on `DBMS`, `DATABASE`, or `GRAPH`, but instead on the data source to load from.
Adding `ON ALL DATA` means a role has the privilege to load data from all sources.
To only allow loading data from sources given by a specific CIDR range use `ON CIDR cidr`.

[IMPORTANT]
====
It is strongly recommended to permit resource loading only over secure protocols such as HTTPS instead of insecure protocols like HTTP.
This can be done by limiting the accessible ranges to only trusted sources that use secure protocols.
If allowing an insecure protocol is absolutely unavoidable, Neo4j takes measures internally to enhance the security of these requests within their limitations.
However, this means that insecure URLs on virtual hosts will not function unless you add the JVM argument `-Dsun.net.http.allowRestrictedHeaders=true` to the configuration setting xref:configuration/configuration-settings.adoc#config_server.jvm.additional[`server.jvm.additional`].
====

[[access-control-load-all-data]]
== The `ALL DATA` privilege

The load privilege on `ALL DATA` enables or disables loading data.
If granted, the user can load data from any source.
If missing or denied, no data can be loaded at all.

.Grant users with the role `roleLoadAllData` the ability to load data with `LOAD CSV`
====
[source, cypher]
----
GRANT LOAD ON ALL DATA TO roleLoadAllData
----
====

.List all privileges for the role `roleLoadAllData` as commands
====
[source, cypher]
----
SHOW ROLE roleLoadAllData PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"GRANT LOAD ON ALL DATA TO `roleLoadAllData`"
a|Rows: 1
|===
====

The `LOAD ON ALL DATA` privilege is granted to the `PUBLIC` role by default.

[[access-control-load-cidr]]
== The `CIDR` privilege

_This feature is available from Neo4j 5.16._

The load privilege on `CIDR cidr` enables or disables loading data from the given IPv4 or IPv6 CIDR range.
If granted, the user can load data from sources in the given CIDR range.
If missing or denied, no data can be loaded from sources in the given CIDR range.

.Denies users with the role `roleLoadCidr` the ability to load data with `LOAD CSV` from `127.0.0.1/32`
====
[source, cypher]
----
DENY LOAD ON CIDR "127.0.0.1/32" TO roleLoadCidr
----
====

.List all privileges for the role `roleLoadCidr` as commands
====
[source, cypher]
----
SHOW ROLE roleLoadCidr PRIVILEGES AS COMMANDS
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|command
|"DENY LOAD ON CIDR "127.0.0.1/32" TO `roleLoadCidr`"
a|Rows: 1
|===
====