:description: This section explains how to use Cypher to manage roles in Neo4j.
:page-role: enterprise-edition aura-db-business-critical aura-db-dedicated

[[access-control-manage-roles]]
= Manage roles

////
[source, cypher, role=test-setup]
----
CREATE USER bob SET PASSWORD 'abcd1234' CHANGE NOT REQUIRED;
CREATE USER user1 SET PASSWORD 'abcd1234' CHANGE NOT REQUIRED;
CREATE USER user2 SET PASSWORD 'abcd1234' CHANGE NOT REQUIRED;
CREATE USER user3 SET PASSWORD 'abcd1234' CHANGE NOT REQUIRED;
CREATE ROLE myrole IF NOT EXISTS;
CREATE ROLE role1 IF NOT EXISTS;
CREATE ROLE role2 IF NOT EXISTS;
----
////

Roles can be created and managed using a set of Cypher administration commands executed against the `system` database.

When connected to the DBMS over `bolt`, administration commands are automatically routed to the `system` database.


[[access-control-role-syntax]]
== Role management command syntax

[NOTE]
====
For more details about the syntax descriptions, see xref:database-administration/syntax.adoc[].
====

.`SHOW ROLES` command syntax
[cols="<15s,<85"]
|===

| Command
m| SHOW ROLES

| Syntax
a|
[source, syntax, role="noheader"]
----
SHOW [ALL\|POPULATED] ROLE[S]
  [YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
  [WHERE expression]
  [RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----

| Description
a|
Lists roles.

When using the `RETURN` clause, the `YIELD` clause is mandatory and must not be omitted.

For more information, see xref:authentication-authorization/manage-roles.adoc#access-control-list-roles[Listing roles].

| Required privilege
a|
[source, privilege, role="noheader"]
----
GRANT SHOW ROLE
----


See xref:authentication-authorization/dbms-administration/dbms-role-management-privileges.adoc[DBMS ROLE MANAGEMENT privileges].
|===

.`SHOW ROLES WITH USERS` command syntax
[cols="<15s,<85"]
|===

| Command
m| SHOW ROLES WITH USERS

| Syntax
a|
[source, syntax, role="noheader"]
----
SHOW [ALL\|POPULATED] ROLE[S] WITH USER[S]
  [YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
  [WHERE expression]
  [RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----

| Description
a|
Lists roles and users assigned to them.

When using the `RETURN` clause, the `YIELD` clause is mandatory and must not be omitted.

For more information, see xref:authentication-authorization/manage-roles.adoc#access-control-list-roles[Listing roles].

| Required privilege
a|
[source, privilege, role="noheader"]
----
GRANT SHOW ROLE
----

For more information, see xref:authentication-authorization/dbms-administration/dbms-role-management-privileges.adoc[DBMS ROLE MANAGEMENT privileges].

[source, privilege, role="noheader"]
----
GRANT SHOW USER
----

For more information, see xref:authentication-authorization/dbms-administration/dbms-user-management-privileges.adoc[DBMS USER MANAGEMENT privileges].

|===

[role=label--new-2026.03]
.`SHOW ROLES WITH AUTH RULES` command syntax
[cols="<15s,<85"]
|===

| Command
m| SHOW ROLES WITH AUTH RULES

| Syntax
a|
[source, syntax, role="noheader"]
----
SHOW [ALL\|POPULATED] ROLE[S] WITH AUTH RULE[S]
  [YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
  [WHERE expression]
  [RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----

| Description
a|
Lists roles and auth rules assigned to them.

When using the `RETURN` clause, the `YIELD` clause is mandatory and must not be omitted.

For more information, see xref:authentication-authorization/manage-roles.adoc#access-control-list-roles[Listing roles].

| Required privilege
a|
[source, privilege, role="noheader"]
----
GRANT SHOW ROLE
----

For more information, see xref:authentication-authorization/dbms-administration/dbms-role-management-privileges.adoc[DBMS ROLE MANAGEMENT privileges].

[source, privilege, role="noheader"]
----
GRANT SHOW AUTH RULE
----

For more information, see xref:authentication-authorization/dbms-administration/dbms-auth-rule-management-privileges.adoc[DBMS AUTH RULE MANAGEMENT privileges].

|===

.`SHOW ROLE PRIVILEGES` command syntax
[cols="<15s,<85"]
|===

| Command
m| SHOW ROLE PRIVILEGES

| Syntax
a|
[source, syntax, role="noheader"]
----
SHOW ROLE[S] name[, ...] PRIVILEGE[S] [AS [REVOKE] COMMAND[S]]
  [YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
  [WHERE expression]
  [RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----

| Description
a|
Lists the privileges granted to the specified roles.

When using the `RETURN` clause, the `YIELD` clause is mandatory and must not be omitted.

The `SHOW ROLE name PRIVILEGES` command is described in xref:authentication-authorization/manage-privileges.adoc#access-control-list-privileges[Listing privileges].

| Required privilege
a|
[source, privilege, role="noheader"]
----
GRANT SHOW PRIVILEGE
----

See xref:authentication-authorization/dbms-administration/dbms-privilege-management-privileges.adoc[DBMS PRIVILEGE MANAGEMENT privileges].

|===

.`CREATE [IMMUTABLE] ROLE` command syntax
[cols="<15s,<85"]
|===


| Command
m| CREATE [IMMUTABLE] ROLE

| Syntax
a|
[source, syntax, role="noheader"]
----
CREATE ROLE name [IF NOT EXISTS] [AS COPY OF otherName]
----

| Description
a|
Creates a new role.

For more information, see xref:authentication-authorization/manage-roles.adoc#access-control-create-roles[Creating roles].

| Required privilege
a|
[source, privilege, role="noheader"]
----
GRANT CREATE ROLE
----

For more information, see xref:authentication-authorization/dbms-administration/dbms-role-management-privileges.adoc[DBMS ROLE MANAGEMENT privileges].

|===

.`CREATE OR REPLACE ROLE` command syntax
[cols="<15s,<85"]
|===
| Command
m| CREATE OR REPLACE ROLE

| Syntax
a|
[source, syntax, role="noheader"]
----
CREATE OR REPLACE ROLE name [AS COPY OF otherName]
----

| Description
a|
Creates a new role, or if a role with the same name exists, replace it.

For more information, see xref:authentication-authorization/manage-roles.adoc#access-control-create-roles[Creating roles].

| Required privilege
a|
[source, privilege, role="noheader"]
----
GRANT CREATE ROLE
----

[source, privilege, role="noheader"]
----
GRANT DROP ROLE
----

For more information, see xref:authentication-authorization/dbms-administration/dbms-role-management-privileges.adoc[DBMS ROLE MANAGEMENT privileges].

|===

.`RENAME ROLE` command syntax
[cols="<15s,<85"]
|===

| Command
m| RENAME ROLE

| Syntax
a|
[source, syntax, role="noheader"]
----
RENAME ROLE name [IF EXISTS] TO otherName
----

| Description
a|
Changes the name of a role.

For more information, see xref:authentication-authorization/manage-roles.adoc#access-control-rename-roles[Renaming roles].

| Required privilege
a|
[source, privilege, role="noheader"]
----
GRANT RENAME ROLE
----

For more information, see xref:authentication-authorization/dbms-administration/dbms-role-management-privileges.adoc[DBMS ROLE MANAGEMENT privileges].

|===

.`DROP ROLE` command syntax
[cols="<15s,<85"]
|===

| Command
m| DROP ROLE

| Syntax
a|
[source, syntax, role="noheader"]
----
DROP ROLE name [IF EXISTS]
----

| Description
a|
Removes a role.

For more information, see xref:authentication-authorization/manage-roles.adoc#access-control-drop-roles[Deleting roles].

| Required privilege
a|
[source, privilege, role="noheader"]
----
GRANT DROP ROLE
----

For more information, see xref:authentication-authorization/dbms-administration/dbms-role-management-privileges.adoc[DBMS ROLE MANAGEMENT privileges].

|===

.`GRANT ROLE TO` command syntax
[cols="<15s,<85"]
|===

| Command
m| GRANT ROLE TO

| Syntax
a|
[source, syntax, role="noheader"]
----
GRANT ROLE[S] name[, ...]
TO {AUTH RULE[S] authrule[, ...] \| [USER[S]] user[, ...]}
----

| Description
a|
Assigns roles directly to users or indirectly through attribute-based access control auth rules.

For more information on assigning roles to users, see xref:authentication-authorization/manage-roles.adoc#access-control-assign-roles[Assigning roles to users].

For more information on assigning roles to auth rules, see xref:authentication-authorization/attribute-based-access-control.adoc#assign-roles-auth-rules[Assigning roles to auth rules].

| Required privilege
a|
[source, privilege, role="noheader"]
----
GRANT ASSIGN ROLE
----

For more information, see xref:authentication-authorization/dbms-administration/dbms-role-management-privileges.adoc[DBMS ROLE MANAGEMENT privileges].

|===

.`REVOKE ROLE` command syntax
[cols="<15s,<85"]
|===

| Command
m| REVOKE ROLE

| Syntax
a|
[source, syntax, role="noheader"]
----
REVOKE ROLE[S] name[, ...]
FROM {AUTH RULE[S] authrule[, ...] \| [USER[S]] user[, ...]}
----

| Description
a|
Removes roles from users or attribute-based access control auth rules.

For more information on revoking roles from users, see xref:authentication-authorization/manage-roles.adoc#access-control-revoke-roles[Revoking roles from users].

For more information on revoking roles from auth rules, see xref:authentication-authorization/attribute-based-access-control.adoc#revoke-roles-auth-rules[Revoking roles from auth rules].

| Required privilege
a|
[source, privilege, role="noheader"]
----
GRANT REMOVE ROLE
----

For more information, see xref:authentication-authorization/dbms-administration/dbms-role-management-privileges.adoc[DBMS ROLE MANAGEMENT privileges].

|===


[[access-control-list-roles]]
== Listing roles


You can view all available roles using the Cypher command `SHOW ROLES`, which returns a single column by default.
Optionally, you can also use `SHOW ROLES YIELD *` to see if the role is immutable.
See <<access-control-immutable-roles, Immutable roles>> for more information.

.`SHOW ROLES` output
[options="header", width="100%", cols="2a,4,2m"]
|===
| Column
| Description
| Type

| role
| Role name
| STRING

| immutable
| `true` if the role is immutable, otherwise `false`.
| BOOLEAN
|===

=== Listing all roles

To list all roles, use the `SHOW ROLES` command:

[source, cypher, role=noplay]
----
SHOW ROLES
----

This is the same command as `SHOW ALL ROLES`.

.Result
[options="header,footer", width="100%", cols="m"]
|===
|role

|"PUBLIC"
|"admin"
|"architect"
|"editor"
|"publisher"
|"reader"

1+a|Rows: 6
|===

When first starting a Neo4j DBMS, there are a number of built-in roles:

* `PUBLIC` - a role that all users have granted.
By default it gives access to the home database and to execute privileges for procedures and functions.
* `reader` - can perform traverse and read operations in all databases except `system`.
* `editor` - can perform traverse, read, and write operations in all databases except `system`, but cannot create new labels or relationship types.
* `publisher` - can do the same as `editor`, but also create new labels and relationship types.
* `architect` - can do the same as `publisher` as well as create and manage indexes and constraints.
* `admin` - can do the same as all the above, as well as manage databases, aliases, users, roles, and privileges.

More information about the built-in roles and their privileges can be found in xref:authentication-authorization/built-in-roles.adoc[].

There are multiple versions of this command, the default being `SHOW ALL ROLES`.
To only show roles that are assigned to users or auth rules, the command is `SHOW POPULATED ROLES`.
This returns the same output columns as `SHOW ROLES`.

=== Listing users assigned to roles

To see which users are assigned to which roles, you can add `WITH USERS` to the command.

[source, cypher, role=noplay]
----
SHOW POPULATED ROLES WITH USERS
----

The command produces a row per role per user and yields a `member` column, in addition to the one returned by `SHOW ROLES`, containing the name of the user assigned to the role, or null if the role is not assigned to any users.
If a role is assigned to multiple users, it will appear once for each user.

.Result
[options="header,footer", width="100%", cols="m,m"]
|===
|role
|member

|"PUBLIC"
|"neo4j"

|"PUBLIC"
|"bob"

|"PUBLIC"
|"user1"

|"PUBLIC"
|"user2"

|"PUBLIC"
|"user3"

|"admin"
|"neo4j"

2+a|Rows: 6
|===

[role=label--new-2026.03]
=== Listing auth rules assigned to roles

To see which auth rules are assigned to which roles, add `WITH AUTH RULES` to the command:

[source, cypher, role=noplay]
----
SHOW POPULATED ROLES WITH AUTH RULES
----

The command produces a row per role per auth rule and yields an `authRule` column, in addition to the one returned by `SHOW ROLES`, containing the name of the auth rule assigned to the role, or null if the role is not assigned to any auth rules.
If a role is assigned to multiple auth rules, it will apppear once for each auth rule.

.Result
[options="header,footer", width="100%", cols="m,m"]
|===
|role
|authRule

|"PUBLIC"
|null

|"admin"
|"adminRule"

2+a|Rows: 6
|===

=== Filtering and ordering roles results

You can filter and sort the results by using `YIELD`, `ORDER BY`, and `WHERE`:

[source, cypher, role=noplay]
----
SHOW ROLES YIELD role
ORDER BY role
WHERE role ENDS WITH 'r'
----

In this example:

* The results are filtered to return only roles ending in 'r'.
* The results are ordered by the `role` column using `ORDER BY`.

It is also possible to use `SKIP` and `LIMIT` to paginate the results.

.Result
[options="header,footer", width="100%", cols="m"]
|===
|role

|"editor"
|"publisher"
|"reader"

1+a|Rows: 3
|===

[[access-control-create-roles]]
== Creating roles

There are different ways to create roles, depending on your needs.

The following naming rules apply to all roles created in Neo4j:

* The first character must be an ASCII alphabetic character.
* Subsequent characters can be ASCII alphabetic, numeric characters, and underscore.
* Role names are case sensitive.

=== Creating new roles

You can create roles using `CREATE [IMMUTABLE] ROLE`:

[source, syntax]
----
CREATE [IMMUTABLE] ROLE name [IF NOT EXISTS] [AS COPY OF otherName]
----

The `CREATE ROLE` command is optionally idempotent, with the default behavior to throw an exception if the role already exists.
Adding `IF NOT EXISTS` to the `CREATE ROLE` command ensures that no exception is thrown and nothing happens should the role already exist.

[source, cypher, role=noplay]
----
CREATE ROLE myrole IF NOT EXISTS
----

=== Creating new roles with the same privileges as existing roles

You can copy a role, keeping its privileges, using `CREATE [IMMUTABLE] ROLE name AS COPY OF otherName`:

[source, cypher, role=noplay]
----
CREATE ROLE mysecondrole AS COPY OF myrole
----

The created roles appear on the list provided by `SHOW ROLES`:

[source, cypher, role=noplay]
----
SHOW ROLES
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|role

|"PUBLIC"
|"admin"
|"architect"
|"editor"
|"myrole"
|"mysecondrole"
|"publisher"
|"reader"

1+a|Rows: 8
|===

=== Creating new roles or replacing existing roles

You can create or replace roles by using `CREATE OR REPLACE [IMMUTABLE] ROLE`:

[source, syntax]
----
CREATE OR REPLACE [IMMUTABLE] ROLE name [AS COPY OF otherName]
----

The `CREATE OR REPLACE ROLE` command results in any existing role being deleted and a new one created. +
For example:

[source, cypher, role=noplay]
----
CREATE OR REPLACE ROLE myrole
----

The command `CREATE OR REPLACE ROLE myrole` will delete the existing `myrole` and create a new one with the same name.
This is equivalent to running `DROP ROLE myrole IF EXISTS` followed by `CREATE ROLE myrole`.

[NOTE]
====
The `CREATE OR REPLACE ROLE` command does not allow you to use the `IF NOT EXISTS`.
====

[[access-control-immutable-roles]]
== Immutable roles

Immutable roles are roles that cannot be modified in the usual way.
This means they cannot be created, renamed, dropped, or have privileges granted to or revoked from them under normal operating conditions.
See xref:authentication-authorization/immutable-roles-privileges.adoc[Immutable roles and privileges] for details of when and how the `IMMUTABLE` keyword may be used.

They are useful in cases where you need a permanent built-in system role that cannot be modified even by users who have xref:authentication-authorization/dbms-administration/dbms-role-management-privileges.adoc[`ROLE MANAGEMENT` privileges] but yet can be granted to and revoked from users in the same way as an ordinary role.


[[access-control-rename-roles]]
== Renaming roles

You can rename a role using `RENAME ROLE` command:

[source, cypher, role=noplay]
----
RENAME ROLE mysecondrole TO mythirdrole
----

After renaming a role, the new name will appear on the list provided by `SHOW ROLES`:

[source, cypher, role=noplay]
----
SHOW ROLES
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|role

|"PUBLIC"
|"admin"
|"architect"
|"editor"
|"myrole"
|"mythirdrole"
|"publisher"
|"reader"

1+a|Rows: 8
|===

[NOTE]
====
The `RENAME ROLE` command is only available when using native authentication and authorization.
====


[[access-control-assign-roles]]
== Assigning roles to users

This section explains how roles can be directly granted to users.
For information on how roles can be assigned to users based on attribute-based rules, see xref:authentication-authorization/attribute-based-access-control.adoc[].

=== Assigning a role to a user

Users can be given access rights by assigning them roles using `GRANT ROLE`:

[source, cypher, role=noplay]
----
GRANT ROLE myrole TO bob
----

The roles assigned to each user can be seen on the list provided by xref:authentication-authorization/manage-users.adoc#access-control-list-users[`SHOW USERS`]:

[source, cypher, role=noplay]
----
SHOW USERS
----

.Result
[options="header,footer", width="100%", cols="2m,3m,3m,2m,2m"]
|===
|user
|roles
|passwordChangeRequired
|suspended
|home

|"bob"
|["myrole","PUBLIC"]
|false
|false
|<null>

|"neo4j"
|["admin","PUBLIC"]
|true
|false
|<null>

|"user1"
|["PUBLIC"]
|true
|false
|<null>

|"user2"
|["PUBLIC"]
|true
|false
|<null>

|"user3"
|["PUBLIC"]
|true
|false
|<null>

5+a|Rows: 5
|===

=== Assigning multiple roles to multiple users

You can assign multiple roles to multiple users in one command:

[source, cypher, role=noplay]
----
GRANT ROLES role1, role2 TO user1, user2, user3
----

[source, cypher, role=noplay]
----
SHOW USERS
----

.Result
[options="header,footer", width="100%", cols="2m,3m,3m,2m,2m"]
|===
|user
|roles
|passwordChangeRequired
|suspended
|home

|"bob"
|["myrole","PUBLIC"]
|false
|false
|<null>

|"neo4j"
|["admin","PUBLIC"]
|true
|false
|<null>

|"user1"
|["role1","role2","PUBLIC"]
|true
|false
|<null>

|"user2"
|["role1","role2","PUBLIC"]
|true
|false
|<null>

|"user3"
|["role1","role2","PUBLIC"]
|true
|false
|<null>

5+a|Rows: 5
|===

Common errors, such as attempts to grant roles to users who have already been granted those roles, will lead to notifications.
Some of these notifications may be replaced with errors in a future major version of Neo4j.
See link:https://neo4j.com/docs/status-codes/current/notifications/all-notifications/[Status Codes for Errors & Notifications -> List of notification codes] for details on notifications.

[[access-control-revoke-roles]]
== Revoking roles from users

This section explains how roles can be directly revoked from users.
For information on how roles can be revoked from users based on attribute-based rules, see xref:authentication-authorization/attribute-based-access-control.adoc[].

=== Revoking a role from a user

Users can lose access rights by revoking their role using `REVOKE ROLE`:

[source, cypher, role=noplay]
----
REVOKE ROLE myrole FROM bob
----

The roles revoked from users can no longer be seen on the list provided by `SHOW USERS`:

[source, cypher, role=noplay]
----
SHOW USERS
----

.Result
[options="header,footer", width="100%", cols="2m,3m,3m,2m,2m"]
|===
|user
|roles
|passwordChangeRequired
|suspended
|home

|"bob"
|["PUBLIC"]
|false
|false
|<null>

|"neo4j"
|["admin","PUBLIC"]
|true
|false
|<null>

|"user1"
|["role1","role2","PUBLIC"]
|true
|false
|<null>

|"user2"
|["role1","role2","PUBLIC"]
|true
|false
|<null>

|"user3"
|["role1","role2","PUBLIC"]
|true
|false
|<null>

5+a|Rows: 5
|===

=== Revoking multiple roles from multiple users

You can revoke multiple roles from multiple users in one command:

[source, cypher, role=noplay]
----
REVOKE ROLES role1, role2 FROM user1, user2, user3
----

Common errors, such as misspellings or attempts to revoke roles from users who have not been granted those roles, will lead to notifications.
In Cypher 25, notifications for impossible `REVOKE` commands, where a user, a role, or a database does not exist, have been replaced with errors.
See link:https://neo4j.com/docs/status-codes/current/notifications/all-notifications/[Status Codes for Errors & Notifications -> List of notification codes] for details on notifications.

[[access-control-drop-roles]]
== Deleting roles

You can delete roles that are no longer needed using the `DROP ROLE` command:

[source, cypher, role=noplay]
----
DROP ROLE mythirdrole
----

Deleting a role removes it from the list provided by `SHOW ROLES`:

[source, cypher, role=noplay]
----
SHOW ROLES
----

.Result
[options="header,footer", width="100%", cols="m"]
|===
|role

|"PUBLIC"
|"admin"
|"architect"
|"editor"
|"myrole"
|"publisher"
|"reader"

1+a|Rows: 8
|===

This command is optionally idempotent, with the default behavior to throw an exception if the role does not exist.
Adding `IF EXISTS` to the command will ensure that no exception is thrown and nothing happens should the role not exist:

[source, cypher, role=noplay]
----
DROP ROLE mythirdrole IF EXISTS
----
