:description: This section explains how to use Cypher to manage users in Neo4j.

[[access-control-manage-users]]
= Manage users

Users can be created and managed using a set of Cypher administration commands executed against the `system` database.
When connected to the DBMS over `bolt`, administration commands are automatically routed to the `system` database.

== User states

There are two types of user states in the `system` database:

`ACTIVE` state:: (default for new users)
Users can log into Neo4j and perform queries according to their privileges.

// [role=label--enterprise-edition]
`SUSPENDED` state label:enterprise-edition[]::

* Native users who authenticate and authorize against the system graph cannot log into Neo4j.
If suspended while using Neo4j, they lose all assigned roles with their privileges, including the `PUBLIC` role, until reactivated.
* Users who authenticate and authorize against an external ID provider (e.g., LDAP) can still log in.
If suspended while using Neo4j, they retain the roles and the privileges assigned by the external provider, including the `PUBLIC` role.
To prevent any of these, you need to use the mechanisms of their identity provider.

[[access-control-user-syntax]]
== User management command syntax

[NOTE]
====
For more details about the syntax descriptions, see xref:database-administration/syntax.adoc[].
====

[cols="<15s,<85"]
|===

| Command
m| SHOW CURRENT USER

| Syntax
a|
[source, syntax, role="noheader"]
----
SHOW CURRENT USER
  [YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
  [WHERE expression]
  [RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----

| Description
a|
Lists the current user.

When using the `RETURN` clause, the `YIELD` clause is mandatory and must not be omitted.

For more information, see xref:authentication-authorization/manage-users.adoc#access-control-current-users[Listing current user].

| Required privilege
a| None

|===


[cols="<15s,<85"]
|===

| Command
m| SHOW USERS

| Syntax
a|
[source, syntax, role="noheader"]
----
SHOW USER[S]
  [WITH AUTH]
  [YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
  [WHERE expression]
  [RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----

| Description
a|
Lists all users.

When using the `RETURN` clause, the `YIELD` clause is mandatory and must not be omitted.

For more information, see xref:authentication-authorization/manage-users.adoc#access-control-list-users[Listing users].

| Required privilege
a|
[source, privilege, role="noheader"]
----
GRANT SHOW USER
----

For more information, see xref:authentication-authorization/dbms-administration.adoc#access-control-dbms-administration-user-management[DBMS USER MANAGEMENT privileges].

|===


[cols="<15s,<85"]
|===
| Command
m| SHOW USER PRIVILEGES

| Syntax
a|
[source, syntax, role="noheader"]
----
SHOW USER[S] [name[, ...]] PRIVILEGE[S] [AS [REVOKE] COMMAND[S]]
  [YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
  [WHERE expression]
  [RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----

| Description
a|
Lists the privileges granted to the specified users or the current user if no user is specified.

When using the `RETURN` clause, the `YIELD` clause is mandatory and must not be omitted.

The `SHOW USER name PRIVILEGES` command is described in xref:authentication-authorization/manage-privileges.adoc#access-control-list-privileges[Listing privileges].

| Required privilege
a|
[source, privilege, role="noheader"]
----
GRANT SHOW PRIVILEGE
----

For more information, see xref:authentication-authorization/dbms-administration.adoc#access-control-dbms-administration-privilege-management[DBMS PRIVILEGE MANAGEMENT privileges].

[source, privilege, role="noheader"]
----
GRANT SHOW USER
----

For more information, see xref:authentication-authorization/dbms-administration.adoc#access-control-dbms-administration-user-management[DBMS USER MANAGEMENT privileges].
|===


[cols="<15s,<85"]
|===
| Command
m| CREATE USER

| Syntax
a|
[source, syntax, role="noheader"]
----
CREATE USER name [IF NOT EXISTS]
  [SET [PLAINTEXT \| ENCRYPTED] PASSWORD 'password']
  [[SET PASSWORD] CHANGE [NOT] REQUIRED]
  [SET STATUS {ACTIVE \| SUSPENDED}]
  [SET HOME DATABASE name]
  [SET AUTH [PROVIDER] 'provider' "{"{SET <key> <value>}..."}"]... # Introduced in Neo4j 5.24
----

`<key><value>` pairs for the `SET AUTH` clause could include:
[source, syntax, role="noheader"]
----
SET AUTH [PROVIDER] 'provider' "{"
    {
        SET ID 'id' # a unique identifier of the user in an external system
        \| SET [PLAINTEXT \| ENCRYPTED] PASSWORD 'password' # only applicable to the 'native' provider
        \| SET PASSWORD CHANGE [NOT] REQUIRED # only applicable to the 'native' provider
    }
"}"
----

| Description
a|
Creates a new user.

[NOTE]
====
It is mandatory to specify a `SET PASSWORD` and/or at least one `SET AUTH` clause because users must have at least one auth provider.
====

For more information, see xref:authentication-authorization/manage-users.adoc#access-control-create-users[Creating users].

| Required privilege
a|
[source, privilege, role="noheader"]
----
GRANT CREATE USER
----

For more information, see xref:authentication-authorization/dbms-administration.adoc#access-control-dbms-administration-user-management[DBMS USER MANAGEMENT privileges].

|===

[cols="<15s,<85"]
|===
| Command
m| CREATE OR REPLACE USER

| Syntax
a|
[source, syntax, role="noheader"]
----
CREATE OR REPLACE USER name
  [SET [PLAINTEXT \| ENCRYPTED] PASSWORD 'password']
  [[SET PASSWORD] CHANGE [NOT] REQUIRED]
  [SET STATUS {ACTIVE \| SUSPENDED}]
  [SET HOME DATABASE name]
  [SET AUTH [PROVIDER] 'provider' "{"{SET <key> <value>}..."}"]... # Introduced in Neo4j 5.24
----
`<key><value>` pairs for the `SET AUTH` clause could include:
[source, syntax, role="noheader"]
----
SET AUTH [PROVIDER] 'provider' "{"
    {
        SET ID 'id' # a unique identifier of the user in an external system
        \| SET [PLAINTEXT \| ENCRYPTED] PASSWORD 'password' # only applicable to the 'native' provider
        \| SET PASSWORD CHANGE [NOT] REQUIRED # only applicable to the 'native' provider
    }
"}"
----

| Description
a|
Creates a new user, or if a user with the same name exists, replace it.

[NOTE]
====
It is mandatory to specify a `SET PASSWORD` and/or at least one `SET AUTH` clause because users must have at least one auth provider.
====

For more information, see xref:authentication-authorization/manage-users.adoc#access-control-create-users[Creating users].

| Required privilege
a|
[source, privilege, role="noheader"]
----
GRANT CREATE USER
----

For more information, see xref:authentication-authorization/dbms-administration.adoc#access-control-dbms-administration-user-management[DBMS USER MANAGEMENT privileges].


[source, privilege, role="noheader"]
----
GRANT DROP USER
----

For more information, see xref:authentication-authorization/dbms-administration.adoc#access-control-dbms-administration-user-management[DBMS USER MANAGEMENT privileges].

|===

[cols="<15s,<85"]
|===
| Command
m| RENAME USER

| Syntax
a|
[source, syntax, role="noheader"]
----
RENAME USER name [IF EXISTS] TO otherName
----

| Description
a|
Changes the name of a user.

For more information, see xref:authentication-authorization/manage-users.adoc#access-control-rename-users[Renaming users].

| Required privilege
a|
[source, privilege, role="noheader"]
----
GRANT RENAME USER
----

For more information, see xref:authentication-authorization/dbms-administration.adoc#access-control-dbms-administration-user-management[DBMS USER MANAGEMENT privileges].

|===

[cols="<15s,<85"]
|===
| Command
m| ALTER USER

| Syntax
a|
[source, syntax, role="noheader"]
----
ALTER USER name [IF EXISTS]
  [REMOVE HOME DATABASE]
  [REMOVE { AUTH [PROVIDER[S]] provider[, ...] \| ALL AUTH [PROVIDER[S]] }]...
  [SET [PLAINTEXT \| ENCRYPTED] PASSWORD 'password']
  [[SET PASSWORD] CHANGE [NOT] REQUIRED]
  [SET STATUS {ACTIVE \| SUSPENDED} ]
  [SET HOME DATABASE name]
  [SET AUTH [PROVIDER] 'provider' "{"{SET <key> <value>}..."}"]... # Introduced in Neo4j 5.24
----
`<key><value>` pairs for the `SET AUTH` clause could include:
[source, syntax, role="noheader"]
----
SET AUTH [PROVIDER] 'provider' "{"
    {
        SET ID 'id' # a unique identifier of the user in an external system
        \| SET [PLAINTEXT \| ENCRYPTED] PASSWORD 'password' # PASSWORD clauses are only applicable to the 'native' provider
        \| SET PASSWORD CHANGE [NOT] REQUIRED # PASSWORD clauses are only applicable to the 'native' provider
    }
"}"
----

| Description
a|
Modifies the settings for an existing user.

* At least one `SET` or `REMOVE` clause is required.
* Any `REMOVE` clause(s) must appear before the first `SET` clause.


For more information, see xref:authentication-authorization/manage-users.adoc#access-control-alter-users[Modifying users].

| Required privilege
a|
[source, privilege, role="noheader"]
----
GRANT SET PASSWORD
----

[source, privilege, role="noheader"]
----
GRANT SET USER STATUS
----

[source, privilege, role="noheader"]
----
GRANT SET USER HOME DATABASE
----

[source, privilege, role="noheader"]
----
GRANT SET AUTH
----

For more information, see xref:authentication-authorization/dbms-administration.adoc#access-control-dbms-administration-user-management[DBMS USER MANAGEMENT privileges].

|===


[cols="<15s,<85"]
|===

| Command
m| ALTER CURRENT USER SET PASSWORD

| Syntax
a|
[source, syntax, role="noheader"]
----
ALTER CURRENT USER SET PASSWORD FROM 'oldPassword' TO 'newPassword'
----

| Description
a|
Changes the current user's password.

For more information, see xref:authentication-authorization/manage-users.adoc#access-control-alter-password[Changing the current user's password].

| Required privilege
a| None

|===


[cols="<15s,<85"]
|===

| Command
m| DROP USER

| Syntax
a|
[source, syntax, role="noheader"]
----
DROP USER name [IF EXISTS]
----

| Description
a|
Removes an existing user.

For more information, see xref:authentication-authorization/manage-users.adoc#access-control-drop-users[Delete users].

| Required privilege
a|
[source, privilege, role="noheader"]
----
GRANT DROP USER
----

For more information, see xref:authentication-authorization/dbms-administration.adoc#access-control-dbms-administration-user-management[DBMS USER MANAGEMENT privileges].

|===


[NOTE,role=label--enterprise-edition]
====
The `SHOW USER[S] PRIVILEGES` command is described in xref:authentication-authorization/manage-privileges.adoc#access-control-list-privileges[Listing privileges].
====


[[access-control-current-users]]
== Listing current user

You can view the currently logged-in user using the Cypher command `SHOW CURRENT USER`.
It produces a table with the following columns:

[options="header", width="100%", cols="2a,4,2m,^.^,^.^"]
|===
| Column
| Description
| Type
| Community Edition
| Enterprise Edition

| user
| User name
| STRING
| {check-mark}
| {check-mark}

| roles
| Roles granted to the user.

It returns `null` in Community edition.
| LIST OF STRING
| {cross-mark}
| {check-mark}

| passwordChangeRequired
| If `true`, the user must change their password at the next login.
| BOOLEAN
| {check-mark}
| {check-mark}

| suspended
| If `true`, the user is currently suspended.

It returns `null` in Community edition.
| BOOLEAN
| {cross-mark}
| {check-mark}

| home
| The home database configured by the user, or `null` if no home database has been configured.
If this database is unavailable and the user does not specify a database to use, they will not be able to log in.

It returns `null` in Community edition.
| STRING
| {cross-mark}
| {check-mark}
|===

[source, cypher, role=noplay]
----
SHOW CURRENT USER
----

.Result
[options="header,footer", width="100%", cols="2m,2m,3m,2m,2m"]
|===
|user
|roles
|passwordChangeRequired
|suspended
|home

|"jake"
|["PUBLIC"]
|false
|false
|<null>

5+a|Rows: 1
|===

[NOTE]
====
This command is only supported for a logged-in user and returns an empty result if authorization has been disabled.
====


[[access-control-list-users]]
== Listing users

You can list all available users using the Cypher command `SHOW USERS`.
It produces a table containing a single row per user with the following columns:

[options="header", width="100%", cols="2a,4,2m,^.^,^.^"]
|===
| Column
| Description
| Type
| Community Edition
| Enterprise Edition

| user
| User name
| STRING
| {check-mark}
| {check-mark}

| roles
| Native roles granted to the user using the `GRANT ROLE` command.

The set of roles a user receives in practice may differ from those in this column.
It depends on DMBS configuration and the user's xref:authentication-authorization/auth-providers.adoc[auth providers].

For example, if they use external (e.g. LDAP or OIDC) auth, or if `native` is not listed in the xref:configuration/configuration-settings.adoc#config_dbms.security.authorization_providers[`dbms.security.authorization_providers`] configuration setting.

It returns `null` in Community edition.
| LIST OF STRING
| {cross-mark}
| {check-mark}

| passwordChangeRequired
| If `true`, the user must change their password at the next login.
This is `null` if the user has `native` auth disabled.
| BOOLEAN
| {check-mark}
| {check-mark}

| suspended
| If `true`, the user is currently suspended.

It returns `null` in Community edition.
| BOOLEAN
| {cross-mark}
| {check-mark}

| home
| The home database configured for the user, otherwise `null`.
A home database is resolved if it is pointing to a database or a database alias.
If the configured home database is unavailable and the user does not specify another database, the login will fail.

It returns `null` in Community edition.
| STRING
| {cross-mark}
| {check-mark}
|===

[NOTE]
====
When first starting a Neo4j DBMS, there is always a single default user `neo4j` with administrative privileges.
It is possible to set the initial password using xref:configuration/set-initial-password.adoc[`neo4j-admin dbms set-initial-password <password>`], otherwise you must change the password after the first login.
====

.Show users
======
[source, cypher, role=noplay]
----
SHOW USERS
----

.Result
[role="queryresult" options="header,footer", width="100%", cols="2m,3m,3m,2m,2m"]
|===
|user
|roles
|passwordChangeRequired
|suspended
|home

|"neo4j"
|["admin","PUBLIC"]
|false
|false
|<null>
|"jake"
|["PUBLIC"]
|false
|false
|<null>
5+a|Rows: 2
|===
======

.Show user with column reorder and filtering
======
This example shows how to:

* Reorder the columns using a `YIELD` clause.
* Filter the results using a `WHERE` clause.

[source, cypher, role=noplay]
----
SHOW USER YIELD user, suspended, passwordChangeRequired, roles, home
WHERE user = 'jake'
----

.Result
[role="queryresult" options="header,footer", width="100%", cols="2m,3m,3m,2m,2m"]
|===
|user
|suspended
|passwordChangeRequired
|roles
|home
|"jake"
|false
|false
|["PUBLIC"]
|<null>
5+a|Rows: 1
|===

======

.Show user with `RETURN` clause
======
It is possible to add a `RETURN` clause to further manipulate the results after filtering.
In this example, the `RETURN` clause is used to filter out the `roles` column and rename the `user` column to `adminUser`.

[source,cypher,role=noplay]
----
SHOW USERS YIELD roles, user
WHERE 'admin' IN roles
RETURN user AS adminUser
----
.Result
[role="queryresult" options="header,footer", width="100%", cols="2m"]
|===
|adminUser
|"neo4j"
1+a|Rows: 1
|===
======

[role=label--new-5.24]
[[access-control-list-user-auth-providers]]
== Listing user auth providers

To inspect users' xref:authentication-authorization/auth-providers.adoc#access-control-list-user-auth-providers[auth providers], use `SHOW USERS WITH AUTH`.
The command produces a row per user per auth provider and yields the following two columns in addition to those output by `SHOW USERS`:

[options="header", width="100%", cols="1a,4,1m,^.^,^.^"]
|===
| Column
| Description
| Type
| Community Edition
| Enterprise Edition

| provider
| The name of the auth provider.
| STRING
| {check-mark}
| {check-mark}

| auth
| A map containing configuration for the user.
For example, dn of the user for an `ldap` auth provider, the unique external identifier for an `oidc` auth provider, or password status for a `native` auth provider.

| MAP
| {check-mark}
| {check-mark}
|===

.Show users with auth
======
[source, cypher, role=noplay]
----
SHOW USERS WITH AUTH
----

.Result
[role="queryresult" options="header,footer", width="100%", cols="2m,3m,3m,2m,2m,3m,4m"]
|===
|user
|roles
|passwordChangeRequired
|suspended
|home
|provider
|auth
|"neo4j"
|["admin","PUBLIC"]
|false
|false
|<null>
|"native"
|{
"password": "*********",
"changeRequired": false
}
|"jack"
|["PUBLIC"]
|false
|false
|<null>
|"native"
|{
"password": "*********",
"changeRequired": false
}
|"jack"
|["PUBLIC"]
|false
|false
|<null>
|"oidc1"
|{
"id": "jacksIdForOidc1"
}
7+a|Rows: 3
|===
======

.Show user with auth using filtering
======
Show all users with the `oidc` auth provider.
[source,cypher,role=noplay]
----
SHOW USERS WITH AUTH
WHERE provider = 'oidc1'
----

.Result
[role="queryresult" options="header,footer", width="100%", cols="2m,3m,3m,2m,2m,3m,4m"]
|===
|user
|roles
|passwordChangeRequired
|suspended
|home
|provider
|auth
|"jack"
|["PUBLIC"]
|false
|false
|<null>
|"oidc1"
|{
"id": "jacksIdForOidc1"
}
7+a|Rows: 1
|===

======

[[access-control-create-users]]
== Creating users

You can create users using one of the following Cypher commands, depending on whether you want to create a new user or replace an existing one.
In both cases, you can specify the user's password, whether they must change it at the next login, their status, home database, and auth provider settings.
The `SET` clauses can be applied in any order.
It is mandatory to specify a `SET PASSWORD` and/or at least one `SET AUTH` clause because users must have at least one auth provider.
`SET AUTH` is available from Neo4j 5.24 onwards.

.`CREATE USER` syntax
[source, syntax, role="noheader"]
----
CREATE USER name [IF NOT EXISTS] # <1>
  [SET [PLAINTEXT \| ENCRYPTED] PASSWORD 'password'] # <2>
  [[SET PASSWORD] CHANGE [NOT] REQUIRED] # <3>
  [SET STATUS {ACTIVE \| SUSPENDED}] # <4>
  [SET HOME DATABASE name] # <5>
  [SET AUTH [PROVIDER] 'provider' "{"{SET <key> <value>}..."}"]... # <6>
----

.`CREATE OR REPLACE USER` syntax
[source, syntax, role="noheader"]
----
CREATE OR REPLACE USER name # <1>
  [SET [PLAINTEXT \| ENCRYPTED] PASSWORD 'password'] # <2>
  [[SET PASSWORD] CHANGE [NOT] REQUIRED] # <3>
  [SET STATUS {ACTIVE \| SUSPENDED}] # <4>
  [SET HOME DATABASE name] # <5>
  [SET AUTH [PROVIDER] 'provider' "{"{SET <key> <value>}..."}"]... # <6>
----
Where:

<1> Specifies the command to create a user.
<2> Specifies the password for the user.
The `'password'` can either be a string value or a string parameter with default value length of at least 8 characters. +
The `PLAINTEXT` and `ENCRYPTED` keywords are optional and can be used to specify the format of the password, i.e. whether Neo4j needs to hash it or it has already been hashed.
By default, all passwords are encrypted (hashed) when stored in the Neo4j `system` database.
* The optional `PLAINTEXT` in `SET PLAINTEXT PASSWORD` has the same behavior as `SET PASSWORD`.
* The optional `ENCRYPTED` is used to recreate an existing user when the plaintext password is unknown, but the encrypted password is available in the _data/scripts/databasename/restore_metadata.cypher_ file of a database backup.
See xref:backup-restore/restore-backup#_restore_users_and_roles_metadata[Restore users and roles metadata]. +
With `ENCRYPTED`, the password string is expected to be in the format of `<encryption-version>,<hash>,<salt>`, where, for example:
** `0` is the first version and refers to the `SHA-256` cryptographic hash function with iterations `1`.
** `1` is the second version and refers to the `SHA-256` cryptographic hash function with iterations `1024`.

<3> Specifies whether the user must change their password at the next login.
If the optional `SET PASSWORD CHANGE [NOT] REQUIRED` is omitted but a password is given, the default is `CHANGE REQUIRED`.
The `SET PASSWORD` prefix of the `CHANGE [NOT] REQUIRED` clause is only optional if it directly follows the `SET PASSWORD 'password'` clause and is not part of a `SET AUTH` clause.

<4> The default for `SET STATUS` is `ACTIVE`.

<5> Specifies a home database for a user.
A home database is resolved if it is pointing to a database or a database alias.
If no home database is set, the DBMS default database is used as the home database for that user.

<6> label:new[Introduced in 5.24] One or more `SET AUTH` clause can be used to configure external xref:authentication-authorization/auth-providers.adoc[auth providers], such as LDAP or OIDC, which define authentication/authorization providers for that user.
`SET AUTH` can also be used as an alternative way to set the native (password-based) auth settings like `SET PASSWORD` and `SET PASSWORD CHANGE REQUIRED`.
For further informations, see the examples in this section, as well as xref:authentication-authorization/sso-integration.adoc#auth-sso-auth-providers[Configure SSO at the user level using auth providers] for OIDC, and xref:authentication-authorization/ldap-integration.adoc#auth-ldap-auth-providers[Configure authentication/authorization at the user level using auth providers] for LDAP.
+
[source, syntax, role="noheader"]
----
SET AUTH [PROVIDER] 'provider' "{"
    {
        SET ID 'id' # a unique identifier of the user in an external system.
        \| SET [PLAINTEXT \| ENCRYPTED] PASSWORD 'password' # only applicable to the 'native' provider.
        \| SET PASSWORD CHANGE [NOT] REQUIRED # only applicable to the 'native' provider.
    }
"}"
----

[NOTE]
====
Usernames are case sensitive.
The created user will appear on the list provided by `SHOW USERS`.

* In Neo4j Community Edition there are no roles, but all users have implied administrator privileges.
* In Neo4j Enterprise Edition all users are automatically assigned the xref:authentication-authorization/built-in-roles.adoc#access-control-built-in-roles-public[`PUBLIC` role], giving them a base set of privileges.
====


.Create user
======
For example, you can create the user `jake` in a suspended state, with the home database `anotherDb`, and the requirement to change the password by using the command:

[source,cypher,role=noplay]
----
CREATE USER jake
SET PASSWORD 'abcd1234' CHANGE REQUIRED
SET STATUS SUSPENDED
SET HOME DATABASE anotherDb
----

[role=label--new-5.24]
The equivalent command using the xref:authentication-authorization/auth-providers.adoc[auth providers] syntax would be:

[source,cypher,role=noplay]
----
CREATE USER jake
SET STATUS SUSPENDED
SET HOME DATABASE anotherDb
SET AUTH 'native' {SET PASSWORD 'abcd1234' SET PASSWORD CHANGE REQUIRED}
----
======


.Create user with an encrypted password
======
Or you can create the user `Jake` in an active state, with an encrypted password (taken from the _data/scripts/databasename/restore_metadata.cypher_ of a database backup), and the requirement to not change the password by running:

[source,cypher,role=noplay]
----
CREATE USER Jake
SET ENCRYPTED PASSWORD '1,6d57a5e0b3317055454e455f96c98c750c77fb371f3f0634a1b8ff2a55c5b825,190ae47c661e0668a0c8be8a21ff78a4a34cdf918cae3c407e907b73932bd16c' CHANGE NOT REQUIRED
SET STATUS ACTIVE
----

[role=label--new-5.24]
The equivalent command using the xref:authentication-authorization/auth-providers.adoc[auth providers] syntax would be:
.
[source,cypher,role=noplay]
----
CREATE USER jake
SET STATUS ACTIVE
SET AUTH 'native' {
  SET ENCRYPTED PASSWORD '1,6d57a5e0b3317055454e455f96c98c750c77fb371f3f0634a1b8ff2a55c5b825,190ae47c661e0668a0c8be8a21ff78a4a34cdf918cae3c407e907b73932bd16c'
  SET PASSWORD CHANGE NOT REQUIRED
}
----

======

[NOTE, role=label--enterprise-edition]
====
The `SET STATUS {ACTIVE | SUSPENDED}`, `SET HOME DATABASE` parts of the commands are only available in Neo4j Enterprise Edition.
The `SET AUTH` clause for external providers is only available in Neo4j Enterprise Edition.
However, `SET AUTH 'native'` can be used in Neo4j Community Edition.
====

The `CREATE USER` command is optionally idempotent, with the default behavior to throw an exception if the user already exists.
Appending `IF NOT EXISTS` to the `CREATE USER` command will ensure that no exception is thrown and nothing happens should the user already exist.


.Create user if not exists
======
[source,cypher,role=noplay]
----
CREATE USER jake IF NOT EXISTS
SET PLAINTEXT PASSWORD 'abcd1234'
----

[role=label--new-5.24]
The equivalent command using the xref:authentication-authorization/auth-providers.adoc[auth providers] syntax would be:

[source,cypher,role=noplay]
----
CREATE USER jake IF NOT EXISTS
SET AUTH 'native' {SET PLAINTEXT PASSWORD 'abcd1234'}
----
======

The `CREATE OR REPLACE USER` command will result in any existing user being deleted and a new one created.


.Create or replace user
======
[source,cypher,role=noplay]
----
CREATE OR REPLACE USER jake
SET PLAINTEXT PASSWORD 'abcd1234'
----

This is equivalent to running `DROP USER jake IF EXISTS` followed by `CREATE USER jake SET PASSWORD 'abcd1234'`.

[role=label--new-5.24]
The equivalent command using the xref:authentication-authorization/auth-providers.adoc[auth providers] syntax would be:

[source,cypher,role=noplay]
----
CREATE OR REPLACE USER jake
SET AUTH 'native' {SET PLAINTEXT PASSWORD 'abcd1234'}
----
======

[NOTE]
====
The `CREATE OR REPLACE USER` command does not allow the use of `IF NOT EXISTS`.
====


[[access-control-rename-users]]
== Renaming users

Users can be renamed with the `RENAME USER` command.

[source, cypher, role=noplay]
----
RENAME USER jake TO bob
----

To verify the change, you can use the `SHOW USERS` command:

[source, cypher, role=noplay]
----
SHOW USERS
----

.Result
[options="header,footer", width="100%", cols="2m,3m,3m,2m,2m"]
|===
|user |roles |passwordChangeRequired |suspended |home

|"bob"
|["PUBLIC"]
|true
|false
|<null>

|"neo4j"
|["admin","PUBLIC"]
|true
|false
|<null>

5+a|Rows: 2

|===

[NOTE]
====
The `RENAME USER` command is only available when using native authentication and authorization.
====


[[access-control-alter-users]]
== Modifying users

You can modify users with the `ALTER USER` command.
The command allows you to change the user's password, status, home database, and auth provider settings.
The `SET` and `REMOVE` clauses can be applied in any order.
However, all `REMOVE` clauses must come before the first `SET` clause and at least one `SET` or `REMOVE` clause is required for the command.

[source, syntax, role="noheader"]
----
ALTER USER name [IF EXISTS] # <1>
  [REMOVE HOME DATABASE] # <2>
  [REMOVE { AUTH [PROVIDER[S]] provider[, ...] \| ALL AUTH [PROVIDER[S]] }]... # <3>
  [SET [PLAINTEXT | ENCRYPTED] PASSWORD 'password'] # <4>
  [[SET PASSWORD] CHANGE [NOT] REQUIRED] # <5>
  [SET STATUS {ACTIVE | SUSPENDED}] # <6>
  [SET HOME DATABASE name] # <7>
  [SET AUTH [PROVIDER] 'provider' "{"{SET <key> <value>}..."}"]... # <8>
----
Where:

<1> Specifies the command to alter a user.
<2> Removes the home database for the user.
As a result, the DBMS default database will be used as the home database for that user.
<3> label:new[Introduced in 5.24] Removes one, several, or all existing xref:authentication-authorization/auth-providers.adoc[auth provider(s)] from a user.
However, a user must always have at least one auth provider.
Therefore, `REMOVE ALL AUTH` must be used in conjunction with at least one `SET AUTH` clause in order to meet this requirement.
<4> Specifies the password for the user.
The `'password'` can either be a string value or a string parameter with default value length of at least 8 characters. +
The `PLAINTEXT` and `ENCRYPTED` keywords are optional and can be used to specify the format of the password, i.e. whether Neo4j needs to hash it or it has already been hashed.
By default, all passwords are encrypted (hashed) when stored in the Neo4j `system` database.
* The optional `PLAINTEXT` in `SET PLAINTEXT PASSWORD` has the same behavior as `SET PASSWORD`.
* The optional `ENCRYPTED` is used to recreate an existing user when the plaintext password is unknown, but the encrypted password is available in the _data/scripts/databasename/restore_metadata.cypher_ file of a database backup.
See xref:backup-restore/restore-backup#_restore_users_and_roles_metadata[Restore users and roles metadata]. +
With `ENCRYPTED`, the password string is expected to be in the format of `<encryption-version>,<hash>,<salt>`, where, for example:
** `0` is the first version and refers to the `SHA-256` cryptographic hash function with iterations `1`.
** `1` is the second version and refers to the `SHA-256` cryptographic hash function with iterations `1024`.
<5> Specifies whether the user must change their password at the next login.
If the optional `SET PASSWORD CHANGE [NOT] REQUIRED` is omitted when adding native auth to a user (either by first removing pre-existing native auth or if the user does not have native auth to start with), the default is `CHANGE REQUIRED`.
The `SET PASSWORD` prefix of the `CHANGE [NOT] REQUIRED` clause is only optional if it directly follows the `SET PASSWORD 'password'` clause and is not part of a `SET AUTH` clause.
<6> Specifies the user's status.
The default is `ACTIVE`.
<7> Specifies a home database for a user. A home database is resolved if it is pointing to a database or a database alias. If no home database is set, the DBMS default database is used as the home database for that user.

<8> label:new[Introduced in 5.24] One or more `SET AUTH` clauses can be used to set xref:authentication-authorization/auth-providers.adoc[auth providers], which define authentication / authorization providers for that user.
This might be used to configure external auth providers like LDAP or OIDC, but can also be used as an alternative way to set the native (password-based) auth settings like `SET PASSWORD` and `SET PASSWORD CHANGE REQUIRED`.
For further informations, see the examples in this section, as well as xref:authentication-authorization/sso-integration.adoc#auth-sso-auth-providers[Configure SSO at the user level using auth providers], and xref:authentication-authorization/ldap-integration.adoc#auth-ldap-auth-providers[Configure authentication/authorization at the user level using auth providers].
+
[source, syntax, role="noheader"]
----
SET AUTH [PROVIDER] 'provider' "{"
    {
        SET ID 'id' # a unique identifier of the user in an external system
        \| SET [PLAINTEXT \| ENCRYPTED] PASSWORD 'password' # only applicable to the 'native' provider
        \| SET PASSWORD CHANGE [NOT] REQUIRED # only applicable to the 'native' provider
    }
"}"
----


.Modify a user's password and status
======
For example, you can modify the user `bob` by setting a new password and active status, and removing the requirement to change his password by running:

[source,cypher,role=noplay]
----
ALTER USER bob
SET PASSWORD 'abcd5678' CHANGE NOT REQUIRED
SET STATUS ACTIVE
----

[role=label--new-5.24]
The equivalent command using the xref:authentication-authorization/auth-providers.adoc[auth providers] syntax would be:

----
ALTER USER bob
SET AUTH 'native' {SET PASSWORD 'abcd5678' SET PASSWORD CHANGE NOT REQUIRED}
SET STATUS ACTIVE
----
======

.Modify a user to expire their current password
======
For example, you can modify the user `bob` to expire his current password so that he must change it the next time he logs in:

[source,cypher,role=noplay]
----
ALTER USER bob
SET PASSWORD CHANGE REQUIRED
----

[role=label--new-5.24]
The equivalent command using the xref:authentication-authorization/auth-providers.adoc[auth providers] syntax would be:

----
ALTER USER bob
SET AUTH 'native' {SET PASSWORD CHANGE REQUIRED}
----
======

[role=label--enterprise-edition label--new-5.24]
.Modify a user to use an external OIDC auth provider
======
For example, you can modify the user `bob` by removing his native auth provider and adding an external OIDC auth provider:

[source,cypher,role=noplay]
----
ALTER USER bob
REMOVE AUTH 'native'
SET AUTH 'oidc-mysso1' {SET ID 'bobsUniqueMySso1Id'}
----
======

[role=label--enterprise-edition label--new-5.24]
.Modify a user to use multiple external OIDC auth providers
======
For example, you can modify the user `bob` by removing all of his existing auth providers and adding two external OIDC auth providers:

[source,cypher,role=noplay]
----
ALTER USER bob
REMOVE ALL AUTH
SET AUTH 'oidc-mysso1' {SET ID 'bobsUniqueMySso1Id'}
SET AUTH 'oidc-mysso2' {SET ID 'bobsUniqueMySso2Id'}
----
======

.Assign a user a different home database
======
For example, you can modify the user `bob` by assigning him a different home database:

[source,cypher,role=noplay]
----
ALTER USER bob
SET HOME DATABASE anotherDbOrAlias
----
======

.Remove the home database from a user and set their status to suspended
======
For example, you can modify the user `bob` by removing his home database and setting his status to suspended:

[source,cypher,role=noplay]
----
ALTER USER bob
REMOVE HOME DATABASE
SET STATUS SUSPENDED
----
======

[NOTE]
====
When altering a user, it is only necessary to specify the changes required.
For example, leaving out the `CHANGE [NOT] REQUIRED` part of the query leaves that unchanged.
====

[NOTE, role=label--enterprise-edition]
====
The `SET STATUS {ACTIVE | SUSPENDED}`, `SET HOME DATABASE`, `REMOVE HOME DATABASE`, and `REMOVE AUTH` parts of the command are only available in Neo4j Enterprise Edition.
The `SET AUTH` clause for external providers is only available in Neo4j Enterprise Edition.
However, `SET AUTH 'native'` can be used in Neo4j Community Edition.
====

The changes to the user will appear on the list provided by `SHOW USERS`:

[source, cypher, role=noplay]
----
SHOW USERS
----

.Result
[options="header,footer", width="100%", cols="2m,3m,3m,2m,2m"]
|===
|user |roles |passwordChangeRequired |suspended |home

|"bob"
|["PUBLIC"]
|false
|false
|<null>

|"neo4j"
|["admin","PUBLIC"]
|true
|false
|<null>

5+a|Rows: 2

|===

The default behavior of this command is to throw an exception if the user does not exist.
Adding an optional parameter `IF EXISTS` to the command makes it idempotent and ensures that no exception is thrown.
Nothing happens should the user not exist.

[source, cypher, role=noplay]
----
ALTER USER nonExistingUser IF EXISTS SET PASSWORD 'abcd1234'
----


[[access-control-alter-password]]
== Changing the current user's password

Users can change their password using `ALTER CURRENT USER SET PASSWORD`.
The old password is required in addition to the new one, and either or both can be a string value or a string parameter.
When a user executes this command it will change their password as well as set the `CHANGE NOT REQUIRED` flag.

// can't test, don't want to hardcode test user password
[source, cypher, role=test-skip]
----
ALTER CURRENT USER
SET PASSWORD FROM 'password1' TO 'password2'
----

[NOTE]
====
This command works only for a logged-in user and cannot be run with auth disabled.
====


[[access-control-drop-users]]
== Delete users

Users can be deleted with `DROP USER`.

[source, cypher, role=noplay]
----
DROP USER bob
----

Deleting a user does not automatically terminate associated connections, sessions, transactions, or queries.

However, when a user is deleted, it no longer appears on the list provided by `SHOW USERS`:

[source, cypher, role=noplay]
----
SHOW USERS
----

.Result
[options="header,footer", width="100%", cols="2m,3m,3m,2m,2m"]
|===
|user |roles |passwordChangeRequired |suspended |home

|"neo4j"
|["admin","PUBLIC"]
|true
|false
|<null>

5+a|Rows: 1

|===
