[role=enterprise-edition]
[[rbac-terminology]]
= Terminology
:description: This section lists the relevant terminology related to authentication and authorization in Neo4j. 

The following terms are relevant to role-based access control within Neo4j:

[.compact]
[[term-active-user]]active user::
A xref:authentication-authorization/terminology.adoc#term-user[user] who is active within the system and can perform actions prescribed by any assigned xref:authentication-authorization/terminology.adoc#term-role[roles] on the data.
This is in contrast to a xref:authentication-authorization/terminology.adoc#term-suspended-user[suspended user].

[[term-administrator]]administrator::
This is a xref:authentication-authorization/terminology.adoc#term-user[user] who has been assigned the `xref:authentication-authorization/native-user-role-management/native-roles.adoc#admin-role[admin]` role.

[[term-current-user]]current user::
This is the currently logged-in xref:authentication-authorization/terminology.adoc#term-user[user] invoking the commands described in this chapter.

[[term-password-policy]]password policy::
The password policy is a set of rules of what makes up a valid password.
For Neo4j, the following rules apply:
* The password cannot be the empty string.
* When changing passwords, the new password cannot be the same as the previous password.

[[term-role]]role::
This is a collection of actions -- such as read and write -- permitted on the data.
There are two types of roles in Neo4j:
* Native roles are described in xref:authentication-authorization/native-user-role-management/native-roles.adoc[Native roles].
* Custom roles are described in xref:authentication-authorization/native-user-role-management/custom-roles.adoc[Custom roles].

[[term-suspended-user]]suspended user::
A xref:authentication-authorization/terminology.adoc#term-user[user] who has been suspended is not able to access the database in any capacity, regardless of any assigned xref:authentication-authorization/terminology.adoc#term-role[roles].

[[term-user]]user::
* A user is composed of a username and credentials, where the latter is a unit of information, such as a password, verifying the identity of a user.
* A user may represent a human, an application etc.
