:description: Monitor your Neo4j deployments using Fleet Manager, a tool that allows you to monitor all of your Neo4j instances, both Aura and self-managed, directly from the Aura console.
:keywords: fleet management, monitoring, neo4j, aura, self-managed, metrics, topology information, server configuration, database metadata, license status
:page-role: new-2025.08
= Monitor your self-managed deployments in Aura

Fleet Manager allows you to monitor *all* of your Neo4j instances, both Aura and self-managed, directly from the Aura console.
It collects the following information from your deployment and securely transmits it to Aura:

* Metrics
* Topology information (graph and tabular format)
* Server configuration
* Database metadata
* License status

In versions 2026.03 and later, Fleet Manager is enabled by default and can be used without any additional setup.

In earlier versions, it is available as a plugin that you can install in your self-managed deployment.
These includes versions Neo4j 4.4.45+, 5.26.12+, and versions between 2025.08.0 and 2026.02.2 inclusive.
For details on how to enable the Fleet management plugin in those versions, see xref:configuration/plugins.adoc#install-and-configure-plugins[Install and configure plugins].

To access and use Fleet Manager, go to *Instances* under the *Self-managed* tab in the Aura console.
See link:{neo4j-docs-base-uri}/aura/fleet-management/overview/[Fleet Manager] in the Aura documentation for more information.
To learn how to discover your local Neo4j servers and add them to Fleet Manager, see xref:monitoring/fleet-discovery.adoc[Discover local servers].

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]

endif::[]
