:description: Discover your local Neo4j servers and add them to Fleet Manager in the Aura console to monitor them alongside your Aura deployments.
:keywords: fleet management, monitoring, neo4j, aura, self-managed, discover local servers, fleet discovery, neo4j-admin fleet discover
:page-role: new-2026.05
[[discover-local-servers]]
= Discover local servers

You can use the `neo4j-admin fleet discover` command to automatically discover all Neo4j servers running on your local network and provide you with a registration code that you can use to add those servers to Fleet Manager in the Aura console.


== Syntax

The `neo4j-admin fleet discover` command has the following syntax:

[source,bash]
----
neo4j-admin fleet discover [-h] [--expand-commands] [--verbose]
                           [--filename=<filename>] [--format=<format>]
                           [--timeout=<timeout>]
----

== Description

The command listens for Neo4j fleet discovery broadcasts on the local network and lists all discovered Neo4j servers.

== Options

The `neo4j-admin fleet discover` command has the following options:

.`neo4j-admin fleet discover` options
[options="header", cols="5m,6a,2m"]
|===
| Option
| Description
| Default

|--expand-commands
|Allow command expansion in config value evaluation.
|

|--filename=<filename>
| Optional filename to which discovered servers will be written.
|

|--format=<format>
| Output format (pretty, csv, json).
| Pretty

|-h, --help
|Show this help message and exit.
|

|--timeout=<timeout>
| Timeout in seconds.
| 60

|--verbose
|Enable verbose output.
|
|===

== Example

The following example shows how to use the `neo4j-admin fleet discover` command to discover Neo4j servers on the local network:

[source,bash]
----
bin/neo4j-admin fleet discover
----

.Example output
[result]
----
Listening for Neo4j discovery broadcasts on port 8687 for a duration of 60 seconds

Discovered 1 Neo4j server

  DBMS ID:    192A83F39D18F8DA0E2CDE0EF1D1B8E7E87CF50CC82D309C88734AEC872864CF
  Address:    localhost:7687

    Server ID:    72663169-aab7-4cfc-a58e-c207d29c810d
    Version:      2026.06.0-57838
    Edition:      enterprise
    Address:      localhost:7687

To add discovered servers with Fleet Manager, log in or sign up to Neo4j Aura and open the dialog to add deployments from Neo4j Admin.
Please see the documentation at: https://neo4j.com/docs/aura/fleet-management/setup/
When prompted, paste the following code into the dialog:

W3siZGJtc0lkIjoiMTkyQTgzRjM5RDE4RjhEQTBFMkNERTBFRjFEMUI4RTdFODdDRjUwQ0M4MkQzMDlDODg3MzRBRUM4NzI4NjRDRiIsInNlcnZlckNvdW50IjoxLCJhZGRyZXNzZXMiOlsibG9jYWxob3N0Ojc2ODciXX1d
----

After pasting the code in the Aura console, you can decide which of the discovered servers you want to monitor and add them to your fleet.
For more information, see link:{neo4j-docs-base-uri}/aura/fleet-management/setup/#discover-deployments[Aura documentation -> Discover deployments].

== Configure the fleet discovery service

The fleet discovery service is enabled by default, so that you can easily discover and monitor your local Neo4j servers in Fleet Manager.
However, if you need to disable it, you can do so by setting the xref:configuration/configuration-settings.adoc#config_server.fleet_discovery.enabled[`server.fleet_discovery.enabled`] configuration parameter to `false` in your _neo4j.conf_ file.

Additionally, you can specify a custom port for the fleet discovery service to listen on by setting xref:configuration/configuration-settings.adoc#config_server.fleet_discovery.port[`server.fleet_discovery.port`] or change the delay between broadcasts by setting xref:configuration/configuration-settings.adoc#config_server.fleet_discovery.broadcast_interval[`server.fleet_discovery.broadcast_interval`].
The base value for the broadcast interval is 30 seconds, but it can be adjusted by adding a jitter interval to prevent all servers from broadcasting at the same time.
You can set the jitter interval using the xref:configuration/configuration-settings.adoc#config_server.fleet_discovery.broadcast_interval_jitter[`server.fleet_discovery.jitter_interval`] configuration setting.

ifndef::backend-pdf[]
[discrete.glossary]
== Glossary

include::partial$glossary.adoc[]

endif::[]
