:description: Monitor your Neo4j deployments using Fleet Manager, a tool that allows you to monitor all of your Neo4j instances, both Aura and self-managed, directly from the Aura console.
:keywords: fleet management, monitoring, neo4j, aura, self-managed, metrics, topology information, server configuration, database metadata, license status
= Monitor your self-managed deployments in Aura

Fleet Manager allows you to monitor *all* of your Neo4j instances, both Aura and self-managed, directly from the Aura console.
It collects the following information from your deployment and securely transmits it to Aura:

* Metrics
* Topology information (graph and tabular format)
* Server configuration
* Database metadata
* License status

In versions 2026.03 and later, Fleet Manager is enabled by default and can be used without any additional setup.

In earlier versions, it is available as a plugin that you can install in your self-managed deployment.
These includes versions Neo4j 4.4.45+, 5.26.12+, and versions between 2025.08.0 and 2026.02.2 inclusive.
For details on how to enable the Fleet management plugin in those versions, see xref:configuration/plugins.adoc#install-and-configure-plugins[Install and configure plugins].

[role=label--new-2026.05]
[[discover-local-servers]]
== Discover local servers

You can use the `neo4j-admin fleet discover` command to automatically discover all Neo4j servers running on your local network and provide you with a registration code that you can use to add those servers to Fleet Manager in the Aura console.

[source,bash]
----
bin/neo4j-admin fleet discover
----

[output]
----
Listening for Neo4j discovery broadcasts on port 8687 for a duration of 60 seconds

Discovered 1 Neo4j server

  DBMS ID:    192A83F39D18F8DA0E2CDE0EF1D1B8E7E87CF50CC82D309C88734AEC872864CF
  Address:    localhost:7687

    Server ID:    72663169-aab7-4cfc-a58e-c207d29c810d
    Version:      2026.06.0-57838
    Edition:      enterprise
    Address:      localhost:7687

To add discovered servers with Fleet Manager, log in or sign up to Neo4j Aura and open the dialog to add deployments from Neo4j Admin.
Please see the documentation at: https://neo4j.com/docs/aura/fleet-management/setup/
When prompted, paste the following code into the dialog:

W3siZGJtc0lkIjoiMTkyQTgzRjM5RDE4RjhEQTBFMkNERTBFRjFEMUI4RTdFODdDRjUwQ0M4MkQzMDlDODg3MzRBRUM4NzI4NjRDRiIsInNlcnZlckNvdW50IjoxLCJhZGRyZXNzZXMiOlsibG9jYWxob3N0Ojc2ODciXX1d
----

For more information on how to add servers to Fleet Manager, see link:{neo4j-docs-base-uri}/aura/fleet-management/setup/#discover-deployments[Discover deployments].


The fleet discovery service is enabled by default, so that you can easily discover and monitor your local Neo4j servers in Fleet Manager.
However, if you need to disable it, you can do so by setting the xref:configuration/configuration-settings.adoc#config_server.fleet_discovery.enabled[`server.fleet_discovery.enabled`] configuration parameter to `false` in your _neo4j.conf_ file. +
Additionally, you can specify a custom port for the fleet discovery service to listen on by setting xref:configuration/configuration-settings.adoc#config_server.fleet_discovery.port[`server.fleet_discovery.port`] or change the delay between broadcasts by setting xref:configuration/configuration-settings.adoc#config_server.fleet_discovery.broadcast_interval[`server.fleet_discovery.broadcast_interval`].
The base value for the broadcast interval is 30 seconds, but it can be adjusted by adding a jitter interval to prevent all servers from broadcasting at the same time.
You can set the jitter interval using the xref:configuration/configuration-settings.adoc#config_server.fleet_discovery.broadcast_interval_jitter[`server.fleet_discovery.jitter_interval`] configuration setting.


== Access and use Fleet Manager

To access and use Fleet Manager, go to *Instances* under the *Self-managed* tab in the Aura console.
See link:{neo4j-docs-base-uri}/aura/fleet-management/overview/[Fleet Manager] in the Aura documentation for more information.