:description: This section describes facilities for query management.

[[query-management]]
= Manage queries

[[query-management-list-queries]]
== List all running queries

The procedure for listing queries, `dbms.listQueries()`, is replaced by the command for listing transactions, `SHOW TRANSACTIONS`.
This command returns information about the currently executing query in the transaction.
For more information on the command, see the link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/transaction-clauses#query-listing-transactions[Cypher manual -> `SHOW TRANSACTIONS` command].

[[query-management-terminate-queries]]
== Terminate queries

Queries are terminated by terminating the transaction on which they are running.
This is done using the `TERMINATE TRANSACTIONS transactionIds` command.
The `transactionIds` can be found using the link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/transaction-clauses#query-listing-transactions[`SHOW TRANSACTIONS` command].

The xref:authentication-authorization/database-administration.adoc#access-control-database-administration-transaction[`TERMINATE TRANSACTION` privilege] determines what transactions can be terminated.
However, the xref:authentication-authorization/index.adoc#auth-terminology[current user] can always terminate all of their own transactions.

*Syntax:*

`TERMINATE TRANSACTIONS transactionIds`

*Argument:*

[options="header"]
|===
| Name | Type | Description
| `transactionIds` | Comma-separated strings | The IDs of all the transactions to be terminated.
| `transactionIds` | Single string parameter | The ID of the transaction to be terminated.
| `transactionIds` | List parameter | The IDs of all the transactions to be terminated.
|===

For more information on the command, see the link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/transaction-clauses#query-terminate-transactions[Cypher manual -> `TERMINATE TRANSACTIONS` command].