[[transaction-management]]
= Transaction management
:description: This section describes facilities for transaction management. 


[[transaction-management-transaction-timeout]]
== Configure transaction timeout

It is possible to configure Neo4j to terminate transactions whose execution time has exceeded the configured timeout.
To enable this feature, set `xref:reference/configuration-settings.adoc#config_dbms.transaction.timeout[dbms.transaction.timeout]` to some positive time interval value denoting the default transaction timeout.
Setting `dbms.transaction.timeout` to `0` -- which is the default value -- disables the feature.

.Configure transaction timeout
====
Set the timeout to ten seconds.
[source, parameters]
----
dbms.transaction.timeout=10s
----
====

Configuring transaction timeout will have no effect on transactions executed with custom timeouts (e.g. via the Java API or Neo4j Drivers), as a custom timeout will override the value set for `dbms.transaction.timeout`.
Please note that the timeout value can only be overridden to a value that is smaller than that configured by `dbms.transaction.timeout`.

The _transaction timeout_ feature is also known as the _transaction guard_.


[[transaction-management-lock-acquisition-timeout]]
== Configure lock acquisition timeout

An executing transaction may get stuck while waiting for some lock to be released by another transaction.
A transaction in such state is not desirable, and in some cases it is better for the transaction to instead give up and fail.

To enable this feature, set `xref:reference/configuration-settings.adoc#config_dbms.lock.acquisition.timeout[dbms.lock.acquisition.timeout]` to some positive time interval value denoting the maximum time interval within which any particular lock should be acquired, before failing the transaction.
Setting `dbms.lock.acquisition.timeout` to `0` -- which is the default value -- disables the lock acquisition timeout.

.Configure lock acquisition timeout
====
Set the timeout to ten seconds.
[source, parameters]
----
dbms.lock.acquisition.timeout=10s
----
====


[[transaction-management-list-transactions]]
== List all running transactions

An xref:authentication-authorization/terminology.adoc#term-administrator[administrator] is able to view all transactions that are currently executing within the instance.
Alternatively, the xref:authentication-authorization/terminology.adoc#term-current-user[current user] may view all of their own currently-executing transactions.

*Syntax:*

`CALL dbms.listTransactions()`

*Returns:*

[options="header"]
|===
| Name                        | Type    | Description
| `transactionId`             | String  | This is the ID of the transaction.
| `username`                  | String  | This is the username of the user who is executing the transaction.
| `metaData`                  | Map     | This is any metadata associated with the transaction.
| `startTime`                 | String  | This is the time at which the transaction was started.
| `protocol`                  | String  | The protocol used by connection issuing the transaction.
| `connectionId`              | String  | The ID of the connection issuing the transaction. This field will be null if the transaction was issued using embedded API.
| `clientAddress`             | String  | The client address of the connection issuing the transaction.
| `requestUri`                | String  | The request URI used by the client connection issuing the transaction.
| `currentQueryId`            | String  | This is the ID of the current query executed by transaction.
| `currentQuery`              | String  | This is the current query executed by transaction.
| `activeLockCount`           | Integer | Count of active locks held by transaction.
| `status`                    | String  | Status of the executing transaction. 
                                          Possible values: `Running`, `Closing`, `Blocked by: <additional info>`, and `Terminated with reason: <additional info>`.
| `resourceInformation`       | Map     | Information about what transaction is waiting for when it is blocked.
| `elapsedTimeMillis`         | Integer | This is the time in milliseconds that has elapsed since the transaction was started.
| `cpuTimeMillis`             | Integer | CPU time in milliseconds that has been actively spent executing the transaction.
| `waitTimeMillis`            | Integer | Wait time in milliseconds that has been spent waiting to acquire locks.
| `idleTimeMillis`            | Integer | Idle time in milliseconds.
| `allocatedBytes`            | Integer | Number of bytes allocated so far by the transaction.
                                          This column is deprecated in favor of `estimatedUsedHeapMemory`.
| `allocatedDirectBytes`      | Integer | Direct bytes used by the executing transaction.
| `pageHits`                  | Integer | Page hits occurred during the execution.
| `pageFaults`                | Integer | Page faults occurred during the execution.
| `database`                  | String  | This is the name of the database the transaction is executing against.
| `estimatedUsedHeapMemory`   | Integer | This is the current estimated heap usage of the transaction, in bytes.
|===

.Viewing transactions that are currently executing
====
The following example shows that the user '*alwood*' is currently running `dbms.listTransactions()`.
The procedure call yields specific information about the running transaction, namely `transactionId`, `username`, `currentQuery`, `elapsedTimeMillis`, `requestUri`, and `status`.

[source, cypher]
----
CALL dbms.listTransactions() YIELD transactionId, username, currentQuery, elapsedTimeMillis, requestUri, status
----

[queryresult]
----
╒═════════════════════╤═══════════╤══════════════════════════════════════╤════════════════════╤════════════════╤═══════════════════╕
│"transactionId"      │"username" │"currentQuery"                        │"elapsedTimeMillis" │"requestUri"    │"status"           │
╞═════════════════════╪═══════════╪══════════════════════════════════════╪════════════════════╪════════════════╪═══════════════════╡
│"myDb-transaction-22"│"alwood"   │"CALL dbms.listTransactions() YIELD   │"1"                 │"127.0.0.1:7687"│"Running"          │
│                     │           │ transactionId, username, currentQuery│                    │                │                   │
│                     │           │elapsedTime, requestUri, status"      │                    │                │                   │
└─────────────────────┴───────────┴──────────────────────────────────────┴────────────────────┴────────────────┴───────────────────┘
1 row
----
====
