[[causal-clustering-monitoring-procedures]]
= Procedures for monitoring a Neo4j Cluster
:description: This section covers procedures for monitoring a Neo4j Cluster. 

A number of procedures are available that provide information about a cluster.


[[dbms.routing.getRoutingTable]]
== Get routing recommendations

From the application point of view it is not interesting to know about the role a member plays in the cluster.
Instead, the application needs to know which instance can provide the wanted service.
The procedure `dbms.routing.getRoutingTable(routingContext, databaseName)` provides this information.

*Syntax:*

`CALL dbms.routing.getRoutingTable(routingContext, databaseName)`

*Arguments:*

[options="header"]
|===
| Name             | Type   | Description
| `routingContext` | Map    | The routing context used for multi-data center deployments.
It should be used in combination with xref:clustering-advanced/multi-data-center/load-balancing.adoc[multi-data center load balancing].
| `databaseName`   | String | The name of the database to get the routing table for.
|===

.Get routing recommendations
====
The following example shows how discover which instances in the cluster can provide which services for database `neo4j`.

[source, cypher]
----
CALL dbms.routing.getRoutingTable({}, "neo4j")
----

The procedure returns a map between a particular service, `READ`, `WRITE` and `ROUTE`, and the addresses of instances that provide this service.
It also returns a Time To Live (TTL) in seconds as a suggestion on how long the client could cache the response.

The result is not primarily intended for human consumption.
Expanding it this is what it looks like.

[source, json]
----
{
    "ttl": 300,
    "servers": [
        {
            "addresses": ["neo20:7687"],
            "role": "WRITE"
        },
        {
            "addresses": ["neo21:7687", "neo22:7687", "neo34:7687", "neo28:7687", "neo31:7687"],
            "role": "READ"
        },
        {
            "addresses": ["neo20:7687", "neo21:7687", "neo22:7687"],
            "role": "ROUTE"
        }
    ]
}
----
====
