:description: This section describes how to access a Neo4j cluster running on Kubernetes.
[[accessing-cluster]]
= Access a Neo4j cluster

A Neo4j cluster is accessible via Kubernetes Services.
Neo4j has a number of different interfaces for different application and operational purposes.
For more details, see xref:configuration/ports.adoc[Neo4j ports].

[[cluster-k8s-services]]
== Supported Kubernetes services

The Neo4j Helm chart publishes four K8s services:

* *Neo4j Service* -- a ClusterIP service for application `neo4j`/`bolt` and `http(s)` connections to the Neo4j database, originating from inside the Kubernetes cluster.
* *Admin Service* -- a “Headless” (DNS only) service that includes all Neo4j ports for admin connections to Neo4j inside Kubernetes.
It is only available inside the Kubernetes cluster and access to it should be guarded.
The Admin service can be used for Neo4j DBMS administration, performing backups, and collecting metrics.
* *Internal Service* — a “Headless” (DNS only) internal service that includes all Neo4j ports required for causal clustering.
* *External* -- a LoadBalancer service for application `neo4j`/`bolt` and `http(s)` connections originating from outside the Kubernetes cluster.
This service is installed using the _neo4j/neo4j-cluster-loadbalancer_ Neo4j Helm chart.


.K8s services per Neo4j interface
[cols="6", options="header"]
|===
| Neo4j Interface
| Default Port
| Neo4j Service
| Admin Service
| Internal Service
| External Service

| Bolt (`neo4j://` and `bolt://` protocols)
| `7687`
| label:Yes[]
| label:Yes[]*
| label:Yes[]
| label:Yes[]

| Neo4j Browser HTTP
| `7474`
| label:Yes[]
| label:Yes[]*
| label:Yes[]
| label:Yes[]

| Neo4j Browser HTTPS
| `7473`
| label:Yes[]
| label:Yes[]*
| label:Yes[]
| label:Yes[]

| Neo4j Cypher HTTP API
| `7474`
| label:Yes[]
| label:Yes[]*
| label:Yes[]
| label:Yes[]

| Neo4j Cypher HTTPS API
| `7473`
| label:Yes[]
| label:Yes[]*
| label:Yes[]
| label:Yes[]

| Neo4j Backup
| `6362`
| label:No[]
| label:Yes[]
| label:Yes[]
| label:No[]

| Graphite Monitoring
| `2003`
| label:No[]
| label:No[] but configurable
| label:No[] but configurable
| label:No[]

| Prometheus Metrics
| `2004`
| label:No[]
| label:No[] but configurable
| label:No[] but configurable
| label:No[]

| Java Management Extensions (JMX)
| `3637`
| label:No[]
| label:No[] but configurable
| label:No[] but configurable
| label:No[]

| Causal Cluster discovery management
| `5000`
| label:No[]
| label:No[]
| label:Yes[]
| label:No[]

| Causal Cluster transaction
| `6000`
| label:No[]
| label:No[]
| label:Yes[]
| label:No[]

| Causal Cluster RAFT
| `7000`
| label:No[]
| label:No[]
| label:Yes[]
| label:No[]

| Causal Cluster routing connector
| `7688`
| label:No[]
| label:No[]
| label:Yes[]
| label:No[]
|===
*The Admin service bypasses health checks.
This allows it to be used to make connections for administrative purposes when the database is in an unhealthy state.
However, you must not use it to connect from applications that require the database to be in a healthy state.

[[cluster-access-inside-k8s]]
== Applications accessing Neo4j from inside Kubernetes

[[cluster-access-inside-k8s-dns]]
=== Access Neo4j using DNS
//same as standalone
To access Neo4j from an application in the same Kubernetes cluster use the Neo4j service DNS address `<release-name>.<namespace>.svc.<cluster domain>`.

The default cluster domain is `cluster.local` and the default namespace is `default`.
Generally, the Neo4j service DNS address is _<release-name>.default.svc.cluster.local_.

For example, if using the release name `my-release` in the `default` namespace, the cluster's DNS address would be `my-release.default.svc.cluster.local`, and the `bolt` address for use with Neo4j drivers would be _neo4j://my-release.default.svc.cluster.local:7687_.

To allow for an application running inside Kubernetes to access the Neo4j cluster, you can also use the Neo4j headless service that is installed via the _neo4j/neo4j-cluster-headless-service_ Helm chart.
For more information and a detailed example, see xref:kubernetes/quickstart-cluster/access-inside-k8s.adoc#cc-access-headless[Access the Neo4j cluster using headless service].

[[cluster-access-inside-k8s-label]]
=== Access Neo4j using K8s label selector

Alternatively, the Neo4j service (default) in Kubernetes can be located using Kubernetes service discovery by searching with the label selector:
`helm.neo4j.com/service=default/admin/internals,helm.neo4j.com/instance=<release-name>`.

The following is an example of how to look up the installed services:

[source,shell, role=nocopy]
----
# Neo4j service:

kubectl get service -l helm.neo4j.com/service=default,helm.neo4j.com/instance=my-release

# Admin service:

kubectl get service -l helm.neo4j.com/service=admin,helm.neo4j.com/instance=my-release

# internals service:

kubectl get service -l helm.neo4j.com/service=internals,helm.neo4j.com/instance=my-release
----

[[cluster-ad-hoc-access]]
=== Ad-hoc external access using `kubectl port-forward`
//same as standalone
In most cases, it is possible to access the Neo4j service from a developer machine outside the Kubernetes cluster using `kubectl port-forward`.
To access the Neo4j service for `http(s)` and `neo4j/bolt` from a developer machine, use the following command:

[source,shell]
----
kubectl port-forward svc/<release-name> tcp-bolt tcp-http tcp-https
----

Neo4j is accessible via the Neo4j browser at _\http://localhost:7474_.

[[cluster-access-outside-k8s]]
== Applications accessing Neo4j from outside Kubernetes

To access a Neo4j cluster from outside Kubernetes, you need to install the `neo4j-cluster-loadbalancer` service using the _neo4j/neo4j-cluster-loadbalancer_ Helm chart.
For a detailed example, see xref:kubernetes/quickstart-cluster/access-outside-k8s.adoc[Access the Neo4j cluster from outside Kubernetes].

[[cluster-custom-k8s-resources]]
== Customizing Kubernetes Resources

The Neo4j Helm chart creates various Kubernetes resources.
Some of them can be customized by adding extra configuration to the helm deployment values file.

.Supported K8s resources customizations
[cols="3", options="header"]
|===
| Customization                                   | _values.yaml_ field                | Type
| Setting a pod securityContext for the Neo4j Pod | `securityContext`                  | `PodSecurityContext`
.3+| Adding annotations to Services            .1+| `services.neo4j.annotations`    .1+| Annotations object for `ClusterIP` service.
                                               .1+| `services.admin.annotations`    .1+| Annotations object for headless (DNS) service.
                                               .1+| `services.internal.annotations` .1+| Annotations object for internal service.
| Adding annotations to Load Balancer Service     | `annotations`                      | Annotations object for `LoadBalancer` service.
|===

[[cluster-access-dbms-admin]]
== Accessing Neo4j for DBMS administration and monitoring
//same as standalone
The Neo4j Helm chart creates the admin service for the purposes of Neo4j administration.
The admin service is a “Headless” service in Kubernetes and does not depend on Neo4j health checks.
Therefore, it permits connections to Neo4j even if Neo4j is not healthy.
In general, that is not desirable for applications but can be useful for administration and debugging.

[[access-dbms-admin-dns]]
=== Access Neo4j using DNS
//same as standalone
To access the admin service inside Kubernetes use the DNS address _<release-name>-admin.<namespace>.svc.<cluster domain>_.

For example, if using the release name `my-release` in the `default` namespace, the cluster's DNS address would be `my-release-admin.default.svc.cluster.local`.

The admin service can be used to access a range of Neo4j interfaces:

* Neo4j Bolt for Neo4j administration via Cypher commands
* Neo4j Backup for taking database backups
* Graphite for metrics collection
* Prometheus for metrics collection
* Java Management Extensions (JMX) for metrics collection and JVM administration

[[cluster-access-dbms-admin-kubectl]]
=== Access Neo4j using `kubectl` for troubleshooting
//same as standalone
To get an interactive `cypher-shell` console for troubleshooting, use this command:

[source,shell,subs="attributes"]
----
kubectl run -it --rm --image neo4j:{neo4j-version-exact} cypher-shell -- cypher-shell -a bolt://my-release-admin.default.svc.cluster.local
----

Generally, the `neo4j://` protocol is used for connecting to Neo4j.
For troubleshooting, though, the direct `bolt://` protocol is used because it allows a connection in some situations where a `neo4j://` connection will not succeed.
