:description: This section describes how to configure a Neo4j Helm chart and create a release name for your Neo4j instance.
[[helm-charts-setup]]
= Configure a Neo4j Helm chart and create a Neo4j Helm release
:description: This section describes how to configure a Neo4j Helm chart and create a release name for your Neo4j instance. 

[[helm-prerequisites]]
== Prerequisites

* Helm v3 (https://helm.sh).

[[helm-chart-config]]
== Configure a Neo4j Helm chart

You configure a Neo4j Helm chart to be used for deploying a Neo4j instance.

. Add the Neo4j Helm charts repository.
+
[source, shell]
----
helm repo add neo4j https://helm.neo4j.com/neo4j
----
+
. Get the latest charts from the chart repository:
+
[source, shell]
----
helm repo update
----
+
. View the available charts:
+
[source, shell]
----
helm search repo neo4j --versions
----
+
.An example result
[source, subs="attributes", role=noheader]
----
neo4j/neo4j-standalone           {neo4j-version-exact}   {neo4j-version-exact}     	Neo4j is the world's leading graph database
----

[[release-name]]
== Create a release name for your Neo4j instance

Getting everything to work in Kubernetes requires that certain K8s objects have specific names that are referenced elsewhere.
Each individual Neo4j instance is a Helm “release” and has a _release name_.
All other names derive from this _release name_.

[NOTE]
====
Release name must consist of lower case alphanumeric characters, `-` or `.`, and must start and end with an alphanumeric character.
====

Set the release name as an environment variable, so that it is available in the rest of the session:

[source, shell]
----
export RELEASE_NAME="<release-name>"
----

[[install-from-public-repo]]
== Install Neo4j from the public Helm chart repository

To install a standalone instance of Neo4j from the public Helm chart repository, run the following commands:

[source, shell]
----
helm install "${RELEASE_NAME}" neo4j/neo4j-standalone
----

[TIP]
====
For more information on how to configure and customize your Neo4j installation, see xref:kubernetes/configuration.adoc[Configure and install Neo4j using Helm].
====
