:description: Introduction to running Neo4j on a Kubernetes cluster using Neo4j Helm charts.
[[kubernetes-overview]]
= Introduction

Neo4j supports both a standalone and a cluster deployment of Neo4j on Kubernetes using the Neo4j Helm charts.

[TIP]
====
Helm (https://helm.sh/) is a “package manager for Kubernetes”.
It usually runs on a machine outside of Kubernetes and creates resources in Kubernetes by calling the Kubernetes API.
Helm installs and manages applications on Kubernetes using _Helm charts_, which are distributed via _Helm chart repositories_.
====

== The Neo4j Helm chart repository

The Neo4j Helm chart repository contains a helm chart for a Neo4j standalone server and cluster installations (_neo4j/neo4j_), and support charts to simplify configuration and operations.
For more details on how to configure the Neo4j Helm chart repository, see xref:kubernetes/helm-charts-setup.adoc[Configure the Neo4j Helm chart repository].
The https://github.com/neo4j/helm-charts[source code] of the Neo4j Helm charts is licensed under *Apache License 2.0.*

== Using the Neo4j Helm chart repository

When using the Neo4j Helm charts, you are responsible for defining _values.yaml_ files.
The YAML files specify what you want to achieve with the Helm chart and the Neo4j configuration.
There is no _neo4j.conf_ file in this setup.

Then, you run `helm install` selecting the chart to install and passing in the _values.yaml_ file to customize the behavior.
The Helm chart creates Kubernetes entities, which in some cases also spawn outside the resources in the cloud environment where they are run (e.g., cloud load balancers).

For more information about the Helm charts and the Kubernetes and Cloud resources they instantiate when installed, see xref:kubernetes/quickstart-standalone/server-setup.adoc[Neo4j standalone server setup] and xref:kubernetes/quickstart-cluster/server-setup.adoc[Neo4j cluster setup].
