:description: Introduction to running a standalone Neo4j instance on a Kubernetes cluster.
[[kubernetes-overview]]
= Introduction
:description: Introduction to running a standalone Neo4j instance on a Kubernetes cluster. 

Neo4j v4.3 supports only Neo4j standalone server deployments on Kubernetes using Neo4j Helm charts.
If you want to deploy Neo4j Causal Clusters, consult the Neo4j-Helm Labs project at https://neo4j.com/labs/.

// [[helm]]
// == What is Helm?

[NOTE]
====
Helm (https://helm.sh/) is a “package manager for Kubernetes”.
It usually runs on a machine outside of Kubernetes and creates resources in Kubernetes by calling the Kubernetes API.
Helm installs and manages applications on Kubernetes using _Helm Charts_, which are distributed via _Helm Chart Repositories_.
====

The Neo4j Helm Charts repository contains helm charts for a Neo4j standalone server (neo4j/neo4j-standalone) and support charts to simplify configuration and operations.

// [[Licensing]]
// == Licensing

// The source code in the Neo4j Helm Charts repository is licensed under the https://github.com/neo-technology/neo4j-helm-charts/blob/master/LICENSE.txt[Apache License 2.0].
