:description: The section describes some maintenance operations when running Neo4j in a Kubernetes cluster.
[[kubernetes-maintenance]]
= Kubernetes maintenance operations
:description: The section describes some maintenance operations when running Neo4j in a Kubernetes cluster. 

[[online-maintenance]]
== Online maintenance

Online maintenance does not require stopping the `neo4j` process.
It is performed using the command `kubectl exec`.

To directly run tasks:

[source, shell]
----
kubectl exec <release-name>-0 -- neo4j-admin store-info --all /var/lib/neo4j/data/databases --expand-commands
----

[NOTE]
====
All `neo4j-admin` commands need the `--expand-commands` flag to run in the Neo4j container.
This is because the Neo4j Helm chart defines the Neo4j configuration using command expansion to dynamically resolve some configuration parameters at runtime.
====

To run a series of commands, use an interactive shell:

[source, shell]
----
kubectl exec -it <release-name>-0 -- bash
----

[NOTE]
====
Processes executed using `kubectl exec` count towards the Neo4j container’s memory allocation.
Therefore, running tasks that use a significant amount of memory or running Neo4j in an extremely memory-constrained configuration could cause the Neo4j container to be terminated by the underlying Operating System.
====

[[offline-maintenance]]
== Offline maintenance

You use the Neo4j offline maintenance mode to perform maintenance tasks that require Neo4j to be offline.
In this mode, the `neo4j` process is not running.
However, the Neo4j Pod does run, but it never reaches the status `READY`.

[[put-offline-mode]]
=== Put the Neo4j instance in offline mode

. To put the Neo4j instance in offline maintenance mode, you set the `offlineMaintenanceModeEnabled: true` and upgrade the helm release.

* You can do that by using the _values.yaml_ file:
.. Open your _values.yaml_ file and add `offlineMaintenanceModeEnabled: true` to the `neo4j` object:
+
[source, properties]
----
neo4j:
 offlineMaintenanceModeEnabled: true
----
+
.. Run `helm upgrade` to apply the changes:
+
[source, shell]
----
helm upgrade <release-name> neo4j/neo4j-standalone -f values.yaml
----
* Alternatively, you can set `neo4j.offlineMaintenanceModeEnabled` to `true` as part of the `helm upgrade` command:
+
[source, shell]
----
helm upgrade <release-name> neo4j/neo4j-standalone --version={neo4j-version-exact} --set neo4j.offlineMaintenanceModeEnabled=true
----

. Poll `kubectl get pods` until the pod has restarted (`STATUS`=`Running`).
+
[source, shell]
----
kubectl get pod <release-name>-0
----
+
. Connect to the pod with an interactive shell:
+
[source, shell]
----
kubectl exec -it "<release-name>-0" -- bash
----
+
. View running java processes:
+
[source, shell]
----
jps
----
+
[queryresult]
----
19 Jps
----
+
The result shows no running java process other than `jps` itself.


[[offline-run-tasks]]
=== Run task in offline mode

Offline maintenance tasks are performed using the command `kubectl exec`.

* To directly run tasks:
+
[source, shell]
----
kubectl exec <release-name>-0 -- neo4j-admin store-info --all /var/lib/neo4j/data/databases --expand-commands
----

* To run a series of commands, use an interactive shell:
+
[source, shell]
----
kubectl exec -it <release-name>-0 -- bash
----

* For long running commands, use a shell and run tasks using `nohup` so they continue if the `kubectl exec` connection is lost:
+
[source, shell]
----
kubectl exec -it <release-name>-0 -- bash
  $ nohup neo4j-admin check-consistency --database=neo4j --expand-commands &>job.out </dev/null &
  $ tail -f job.out
----

[[put-online-mode]]
=== Put the Neo4j instance in online mode

When you finish with the maintenance tasks, return the Neo4j instance to a normal operation:

* You can do that by using the _values.yaml_ file:
. Open your _values.yaml_ file and add `offlineMaintenanceModeEnabled: false` to the `neo4j` object:
+
[source, properties]
----
neo4j:
 offlineMaintenanceModeEnabled: false
----
+
. Run `helm upgrade` to apply the changes:
+
[source, shell]
----
helm upgrade <release-name> neo4j/neo4j-standalone -f values.yaml
----

* Alternatively, you can run `helm upgrade` with the flag set to `false`:
+
[source, shell]
----
helm upgrade <release-name> neo4j/neo4j-standalone --version={neo4j-version-exact} --set neo4j.offlineMaintenanceModeEnabled=false
----

[[reset-password]]
== Reset the `neo4j` user password

You reset the `neo4j` user password by disabling authentication and then re-enabling it.

. In the _values.yaml_ file, set `dbms.security.auth_enabled:` to `false` to disable the authentication:
+
[NOTE]
====
All Neo4j `config` values must be YAML strings, not YAML booleans.
Therefore, make sure you put quotes around values, such as `"true"` or `"false"`, so that they are handled correctly by Kubernetes.
====
+
[source, properties]
----
# Neo4j Configuration (yaml format)
config:
  dbms.security.auth_enabled: "false"
----
+
. Run the following command to apply the changes:
+
[source, shell]
----
helm upgrade <release-name> neo4j/neo4j-standalone -f values.yaml
----
+
Authentication is now disabled.
+
. Connect with `cypher-shell` and set the desired password:
+
[source, cypher]
----
ALTER USER neo4j SET PASSWORD '<new-password>'
----
+
. Update the Neo4j configuration to enable authentication:
+
[source, properties]
----
# Neo4j Configuration (yaml format)
config:
  dbms.security.auth_enabled: "true"
----
+
. Run the following command to apply the update and re-enable authentication:
+
[source, shell]
----
helm upgrade <release-name> neo4j/neo4j-standalone -f values.yaml
----
+
Authentication is now enabled, and the Neo4j user password has been reset to the desired password.


[[kubernetes-neo4j-dump-load]]
== Dump and load databases (offline)

You can use the `neo4j-admin dump` command to make a full backup (an archive) of an **offline** database(s) and `neo4j-admin load` to load it back into a Neo4j deployment.
These operations are performed in xref:kubernetes/maintenance.adoc#offline-maintenance[offline maintenance mode].

[[kubernetes-neo4j-dump]]
=== Dump the `neo4j` and `system` databases

. xref:kubernetes/maintenance.adoc#put-offline-mode[Put the Neo4j instance in offline mode].
. Dump `neo4j` and `system` databases:
+
[source, shell]
----
neo4j-admin dump --expand-commands --database=system --to /backups/system.dump && neo4j-admin dump --expand-commands --database=neo4j --to /backups/neo4j.dump
----
+
. xref:kubernetes/maintenance.adoc#put-online-mode[Put the Neo4j instance in online mode].
. Verify that Neo4j is working by refreshing Neo4j Browser.

[TIP]
====
For information about the command syntax, options, and usage, see xref:backup-restore/offline-backup.adoc[Back up an offline database].
====

[[kubernetes-neo4j-load]]
=== Load the `neo4j` and  `system` databases

. xref:kubernetes/maintenance.adoc#put-offline-mode[Put the Neo4j instance in offline mode].
. Run `neo4j-admin load` commands:
+
[source, shell]
----
neo4j-admin load --expand-commands --database=system --from /backups/system.dump && neo4j-admin load --expand-commands --database=neo4j --from /backups/neo4j.dump
----
+
[TIP]
====
For information about the command syntax, options, and usage, see xref:backup-restore/restore-dump.adoc[Restore a database dump].
====
+
. xref:kubernetes/maintenance.adoc#put-online-mode[Put the Neo4j instance in online mode].
. Verify that Neo4j is working by refreshing Neo4j Browser.

[role=enterprise-edition]
[[kubernetes-neo4j-backup-restore]]
== Back up and restore a Neo4j database (online)

You can use the `neo4j-admin backup` command to make a full or incremental backup of an **online** database(s) and `neo4j-admin restore` to restore it in a live Neo4j DBMS.
These operations are performed in xref:kubernetes/maintenance.adoc#online-maintenance[online maintenance mode].

[[kubernetes-neo4j-backup]]
=== Back up the `neo4j` database

To back up the `neo4j` database, run the following command:

[source, properties]
----
kubectl exec <release-name>-0 -- neo4j-admin backup --from=localhost:6362 --database=neo4j --backup-dir=/backups --expand-commands
----

[TIP]
====
You may also want to use the option `--include-metadata=all`.
It creates a cypher script, which you can later use to restore the database's users, roles, and privileges.

For information about the command syntax, options, memory configuration, and usage, see xref:backup-restore/online-backup.adoc[Back up an online database].
====

[CAUTION]
====
Note that this operation consumes resources (CPU, RAM) in the Neo4j container (competing with Neo4j itself).
If your resources are constrained, you can run the backup in a sidecar container in the same pod or from a remote K8s Pod/Job.
====

[[kubernetes-neo4j-restore]]
=== Restore `neo4j` database
To restore the `neo4j` database, you need to execute `neo4j-admin restore` command and create the database in the `system` db.

[TIP]
====
For information about the command syntax, options, and usage, see xref:backup-restore/restore-backup.adoc[Restore a database backup].
====

. Connect to the Neo4j standalone instance:
+
[source, shell]
----
kubectl exec -it <release-name>-0 -- bash
----
+
. Connect to your `system` database using `cypher-shell`:
+
[source, shell]
----
cypher-shell -u neo4j -p <password> -d system
----
+
. Drop the `neo4j` database and exit:
+
[source, shell]
----
DROP DATABASE neo4j;
----
+
[source, shell]
----
:exit;
----
+
. Run the `neo4j-admin restore` command:
+
[source, shell]
----
neo4j-admin restore --database=neo4j --from=/backups/neo4j --expand-commands
----
+
. Connect to your `system` database using `cypher-shell`:
+
[source, shell]
----
cypher-shell -u neo4j -p <password> -d system
----
+
. Create `neo4j` database.
+
[source, shell]
----
CREATE DATABASE neo4j;
----
+
. Open the browser at _http://<external-ip>:7474/browser/_ and check that all data is successfully restored.
. Execute cypher command against `neo4j` database:
+
[source, cypher]
----
MATCH (n) RETURN n
----

[NOTE]
====
If you have backed up your database with the option `--include-metadata`, you can manually restore the users and roles metadata.
For more information, see xref:backup-restore/restore-backup.adoc#restore-backup-example[Restore a database backup -> Example].
====

[[kubernetes-upgrading]]
== Upgrade Neo4j on Kubernetes

To upgrade from Neo4j Community to Enterprise edition, run:

[source, shell]
----
helm upgrade <release-name> neo4j/neo4j-standalone --set neo4j.edition=enterprise --set neo4j.acceptNeo4jLicenseAgreement=yes
----

To upgrade to the next patch release of Neo4j, update your Neo4j _values.yaml_ file and upgrade the helm release.

. Open the _values.yaml_ file, using the code editor of your choice, and add the following line to the `image` object:
+
[source, properties, subs="attributes"]
----
image:
  customImage: neo4j:{neo4j-version-exact}
----
+
. Run `helm upgrade` to apply the changes:
+
[source, shell]
----
helm upgrade <release-name> neo4j/neo4j-standalone -f values.yaml
----

[[vertical-scaling]]
== Scale a Neo4j deployment

To increase or decrease the resources (CPU, memory) available to Neo4j, change the `neo4j.resources` object in the _values.yaml_ file to set the desired resource usage, and then perform a helm upgrade.

[NOTE]
====
If you change the memory allocated to the Neo4j container, you should also change the Neo4j's memory configuration (`dbms.memory.heap.max_size` and `dbms.memory.pagecache.size` in particular).
See xref:configure-resources[Configure Resource Allocation] for more details.
====

For example:

. Create a _values.yaml_ file for a Neo4j instance with 1 CPU and 3 GB of memory:
+
[source, properties]
----
# values.yaml
neo4j:
  resources:
    cpu: "1"
    memory: "3Gi"

# Neo4j Configuration (yaml format)
config:
  dbms.memory.heap.initial_size: "2G"
  dbms.memory.heap.max_size: "2G"
  dbms.memory.pagecache.size: "500m"
----
+
. Run `helm install` to create the instance:
+
[source, shell,subs="attributes"]
----
helm install <release-name> neo4j/neo4j-standalone -f values.yaml
----
+
. Modify the _values.yaml_ file to increase to 2 CPU and 4 GB of memory (allocating the additional memory to the pagecache):
+
[source, properties]
----
# values.yaml
neo4j:
  resources:
    cpu: "2"
    memory: "4Gi"

# Neo4j Configuration (yaml format)
config:
  dbms.memory.heap.initial_size: "2G"
  dbms.memory.heap.max_size: "2G"
  dbms.memory.pagecache.size: "1G"
----
+
. Run `helm upgrade` to apply the change:
+
[source, shell]
----
helm upgrade <release-name> neo4j/neo4j-standalone -f values.yaml
----
