:description: A quick start guide for deploying a Neo4j instance to an Azure Kubernetes Service (AKS) cluster using Neo4j Helm charts.
[[quickstart-azure-aks]]
= Quickstart: Deploy a Neo4j instance to an Azure Kubernetes Service (AKS) cluster
:description: A quick start guide for deploying a Neo4j instance to an Azure Kubernetes Service (AKS) cluster using Neo4j Helm charts. 

[[aks-prerequisites]]
== Prerequisites


* The `az` command-line interface (CLI) (https://docs.microsoft.com/en-us/cli/azure/install-azure-cli).
* The `kubectl` Kubernetes client command-line tool (https://kubernetes.io/docs/tasks/tools/).
* The `helm` command-line tool (https://helm.sh/docs/intro/install/)
  - Add the neo4j Helm repository `helm repo add neo4j https://helm.neo4j.com/neo4j`
* A Resource Group with:
  - An Azure Kubernetes Service (AKS) cluster.
  - The AKS cluster principal needs to be assigned roles that allow it to manage Microsoft.Compute/disks in the Resource Group.
* Verify that your Kubernetes nodes have sufficient CPU and memory for your Neo4j deployment.
+
[TIP]
====
We recommend using nodes with at least 4 CPUs and 4GB of memory.
This size can usually fit a Neo4j instance with 1CPU and 2GB memory.
For more information on Neo4j's system requirements, see xref:installation/requirements.adoc[System requirements].
====
* Verify that you have a valid license if you want to install Neo4j Enterprise Edition.
For more information, see https://neo4j.com/licensing/ or write to licensing@neo4j.com.
* All the shell commands in this guide assume that the Azure Resource Group and location to use have been set using the `AZURE_DEFAULTS_LOCATION` and `AZURE_DEFAULTS_GROUP` environment variables, for example:
+
[source, shell]
----
export AZURE_DEFAULTS_GROUP="myneo4jrg"
export AZURE_DEFAULTS_LOCATION="northeurope"
----


[TIP]
====
If you do not have an AKS cluster, you can create a single-node one using:

[source, shell]
----
az aks create --name my-neo4j-aks-cluster --node-count=1
----

You can add the necessary role assignments to the AKS cluster using:

[source, shell]
----
AKS_PRINCIPAL_ID="$(az aks show --name my-neo4j-aks-cluster \
   --query 'identity.principalId' --output tsv)"

az role assignment create --role "Virtual Machine Contributor" \
                          --assignee-object-id "${AKS_PRINCIPAL_ID}"

# update the AKS cluster's credentials so that it picks up the new role assignment
SP_SECRET="$(az ad sp credential reset --name "${AKS_PRINCIPAL_ID}" --query password -o tsv)"

az aks update-credentials \
    --name my-neo4j-aks-cluster \
    --reset-service-principal \
    --service-principal "${AKS_PRINCIPAL_ID}" \
    --client-secret "${SP_SECRET}"
----

You can configure kubectl to use your AKS cluster using

[source, shell]
----
az aks get-credentials --name my-neo4j-aks-cluster --admin
----
====

[[aks-quickstart-overview]]

To install Neo4j, perform the following steps:

* xref:kubernetes/quickstart-azure.adoc#aks-managed-disk[Create an Azure managed disk for the Neo4j instance].
* xref:kubernetes/quickstart-azure.adoc#aks-values-file[Create a Helm deployment values file].
* xref:kubernetes/quickstart-azure.adoc#aks-install-helm[Install Neo4j using the deployment values file and the _neo4j/neo4j-standalone_ Helm chart].


[[aks-managed-disk]]
== Create an Azure managed disk

Create an Azure managed disk using the following command.
This is a normal Azure managed disk and not Kubernetes specific:

[source, shell]
----
az disk create --name "my-neo4j-disk" --size-gb "64" --sku Premium_LRS --max-shares 1
----

Fetch the ID of the disk that was just created.

[source, shell]
----
az disk show --name "my-neo4j-disk" --query id
----

.Example result
[source, role=noheader]
----
"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myneo4jrg/providers/Microsoft.Compute/disks/my-neo4j-disk"
----

[[aks-values-file]]
== Create a Helm deployment values file

Create a new file _my-neo4j.values.yaml_ with the following content, replacing `<disk id>` with the ID of the disk you created:

[source, yaml]
----
neo4j:
  resources:
    cpu: "1"
    memory: "2Gi"

  # Uncomment to set the initial password. You cannot use `neo4j` as this is the default password. 
  #password: "my-initial-password"

  # Uncomment to use enterprise edition
  #edition: "enterprise"
  #acceptLicenseAgreement: "yes"

volumes:
  data:
    mode: "volume"
    volume:
      azureDisk:
        diskName: "my-neo4j-disk"
        diskURI: "<disk id>"
        kind: Managed

----

For details of all Neo4j Helm Chart configuration options, see xref:kubernetes/configuration.adoc[Configure and install Neo4j using a customized Helm chart].

[[aks-install-helm]]
== Install Neo4j

. Ensure your Helm Chart repositories are up to date:
+
[source, shell]
----
helm repo update
----
+
. Install Neo4j using the deployment values file created in xref:kubernetes/quickstart-azure.adoc#aks-values-file[Create a Helm deployment values file]:
+
[source, shell, subs="attributes"]
----
helm install my-neo4j-release neo4j/neo4j-standalone -f my-neo4j.values.yaml
----
+
.Example output
[source, role=noheader, subs="attributes"]
----
NAME: my-neo4j-release
LAST DEPLOYED: Wed Jul  7 19:52:58 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing neo4j-standalone.

Your release "my-neo4j-release" has been installed .

To view the progress of the rollout try:

  $ kubectl rollout status --watch --timeout=600s statefulset/my-neo4j-release


Once rollout is complete you can log in to Neo4j at "neo4j://my-neo4j-release.default.svc.cluster.local:7687". Try:

  $ kubectl run --rm -it --image "neo4j:{neo4j-version-exact}" cypher-shell \
     -- cypher-shell -a "neo4j://my-neo4j-release.default.svc.cluster.local:7687" -u neo4j

Graphs are everywhere!
----
+
. Run the `kubectl rollout` command provided in the output of `helm install` to watch the Neo4j's rollout until it is complete.
+
[source, shell, subs="attributes"]
----
kubectl rollout status --watch --timeout=600s statefulset/my-neo4j-release
----
+
[NOTE]
====
Since you have not passed a password for the `neo4j` user, the Neo4j Helm chart has set an automatically generated one.
You can find it in the Helm install output.
Please make a note of it.
====


[[aks-verify-install]]
== Verify the installation

. Check that the `statefulset` is OK.
Initially it will not be ready but just check there is something there.
+
[source, shell]
----
kubectl --namespace default get statefulsets
----
+
[source, role=noheader]
----
NAME               READY   AGE
my-neo4j-release   1/1     2m11s
----
+
. Check that the pod is `Running`:
+
[source, shell]
----
kubectl --namespace default get pods
----
+
[source, role=noheader]
----
NAME                 READY   STATUS    RESTARTS   AGE
my-neo4j-release-0   1/1     Running   0          16m
----
+
. Check that the pod logs look OK:
+
[source, shell]
----
kubectl --namespace default exec my-neo4j-release-0 -- tail -n50 /logs/neo4j.log
----
+
[source, role=noheader, subs="attributes"]
----
2021-07-28 12:45:50.267+0000 INFO  Command expansion is explicitly enabled for configuration
2021-07-28 12:45:50.280+0000 INFO  Starting...
2021-07-28 12:45:55.680+0000 INFO  ======== Neo4j {neo4j-version-exact} ========
2021-07-28 12:46:00.006+0000 INFO  Bolt enabled on [0:0:0:0:0:0:0:0%0]:7687.
2021-07-28 12:46:02.476+0000 INFO  Remote interface available at http://localhost:7474/
2021-07-28 12:46:02.478+0000 INFO  Started.
----
+
. Check that the services look OK:
+
[source, shell]
----
kubectl get services --namespace default
----
+
[source, role=noheader]
----
NAME                     TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)                                        AGE
kubernetes               ClusterIP      10.112.0.1      <none>         443/TCP                                        28h
my-neo4j-release         ClusterIP      10.112.10.159   <none>         7687/TCP,7474/TCP,7473/TCP                     41m
my-neo4j-release-admin   ClusterIP      10.112.4.73     <none>         6362/TCP,7687/TCP,7474/TCP,7473/TCP            41m
my-neo4j-release-neo4j   LoadBalancer   10.112.6.75     34.140.48.23   7474:31420/TCP,7473:31591/TCP,7687:31650/TCP   41m
----
+
. In a web browser, open the Neo4j Browser at _http://<EXTERNAL-IP>:7474/browser_.
. Use the automatically generated password (as printed in the output of the `helm install` command) or the one you have configured in the _my-neo4j.values.yaml_ file.

[[aks-uninstall-cleanup]]
== Uninstall Neo4j and clean up the created resources

[[aks-uninstall]]
=== Uninstall Neo4j Helm deployment

. Uninstall Neo4j Helm deployment.
+
[source, shell]
----
helm uninstall my-neo4j-release
----
+
[source, role=noheader]
----
release "my-neo4j-release" uninstalled
----
+
. Uninstalling the Helm release does not remove the Azure managed disk, nor does it remove the data it contains:
+
[source, shell]
----
az disk show --name "my-neo4j-disk"
----
+
[NOTE]
====
If you re-create Neo4j with the same settings, it will pick up the same disk again and all the data will still be on it.

Even if you delete the AKS cluster, the managed disk with the Neo4j data will still exist.
Note that the disk _will_ be deleted if its Resource Group is deleted.
====

[[aks-cleanup]]
=== Fully remove all the data and resources

After uninstalling the helm deployment, the only remaining step is to delete the managed disk.

. Delete the Azure managed disk:
+
[source, shell]
----
az disks delete --name "my-neo4j-disk"
----

[TIP]
====
If you are sure that you want to delete the entire AKS Kubernetes cluster, run:

[source, shell]
----
az aks delete --name my-neo4j-aks-cluster
----
====
