[[linux-open-files]]
= Setting the number of open files

Linux platforms impose an upper limit on the number of concurrent files a user may have open.
This number is reported for the current user and session with the `ulimit -n` command:

[source, shell]
----
user@localhost:~$ ulimit -n
1024
----

It is possible that the default value of 1024 may not be not enough.
This is especially true when many indexes are used or a server installation sees too many connections.
Network sockets count against the limit as well.
Users are therefore encouraged to increase the limit to a healthy value of 40000 or more, depending on usage patterns.

It is possible to set the limit with the `ulimit` command, but only for the root user, and it only affects the current session.
To set the value system wide, follow the instructions for your platform.

The following steps will set the open file descriptor limit to 60000 for user _neo4j_ under Ubuntu 16.04 LTS, Debian 8, Centos 7 or later versions of those operating systems:

. If you run Neo4j as a service, you must complete the following:
.. Run the following command, which will enable you to edit the _neo4j.service_ file:
+
[source, shell]
----
user@localhost:~$ sudo systemctl edit neo4j.service
----

.. Append the `[Service]` section in the _neo4j.service_ file:
+
[source]
----
[Service]
LimitNOFILE=60000
----

. If you run Neo4j as an interactive user (which can be the case for testing purposes), you must complete the following:
.. Run the following command, which will enable you to edit the _user.conf_ file:
+
[source, shell]
----
user@localhost:~$ sudo vi /etc/systemd/user.conf
----

.. Uncomment and define the value for `DefaultLimitNOFILE`, found in the `[MANAGER]` section:
+
[source]
----
[Manager]
...
DefaultLimitNOFILE=60000
----

.. Run the following command which will append the _/etc/security/limits.conf_ file:
+
[source, shell]
----
user@localhost:~$ sudo vi /etc/security/limits.conf
neo4j	soft	nofile	60000
neo4j	hard	nofile	60000
----

. Reload `systemd` settings with the command:
+
[source, shell]
----
user@localhost:~$ sudo systemctl daemon-reload
----

. Reboot your machine.

After completing the above procedure, the Neo4j user will have a limit of 60000 simultaneous open files.
If you continue experiencing exceptions on `Too many open files` or `Could not stat() directory`, you may have to raise the limit further.
