[[linux-open-files]]
= Setting the number of open files

Linux platforms impose an upper limit on the number of concurrently open files per user and session.
To check your limit for the current session, run the command `ulimit -n`.
The default value is 1024.

[source, shell]
----
ulimit -n
1024
----

However, if you experience exceptions on `Too many open files` or `Could not stat() directory`, you have to increase the limit to 40000 or more, depending on your usage patterns.
This is especially true when many indexes are used, or the server installation sees too many open network connections or sockets.

A quick solution is the command `ulimit -n <the-new-limit>`, but it will set a new limit only for the root user and will affect only the current session.
If you want to set the value system-wide, follow the instructions for your platform.

The following steps set the open file descriptor limit to 60000 for the user _neo4j_ under Ubuntu 16.04 LTS, Debian 8, CentOS 7, or later versions.

== Running Neo4j as a service

. Open the _neo4j.service_ file with root privileges.
+
[source, shell]
----
sudo systemctl edit neo4j.service
----

. Append the following to the `[Service]` section:
+
[source]
----
[Service]
...
LimitNOFILE=60000
----

== Running Neo4j as an interactive user (e.g., for testing purposes)

. Open the _user.conf_ file with root privileges in a text editor.
This example uses Vim:
+
[source, shell]
----
sudo vi /etc/systemd/user.conf
----

. Uncomment and define the value of `DefaultLimitNOFILE`, found in the `[Manager]` section.
+
[source]
----
[Manager]
...
DefaultLimitNOFILE=60000
----

. Open the _/etc/security/limits.conf_ file.
+
[source, shell]
----
sudo vi /etc/security/limits.conf
----

. Define the following values:
+
[source]
----
neo4j	soft	nofile	60000
neo4j	hard	nofile	60000
----

. Reload the `systemd` settings.
+
[source, shell]
----
sudo systemctl daemon-reload
----

. Reboot your machine.
