[[kubernetes-neo4j-dump-load]]
= Dump and load databases (offline)

You can use the `neo4j-admin dump` command to make a full backup (an archive) of an **offline** database(s) and `neo4j-admin load` to load it back into a Neo4j deployment.
These operations are performed in xref:kubernetes/operations/maintenance-mode.adoc#put-offline-mode[offline maintenance mode].

[[kubernetes-neo4j-dump]]
== Dump the `neo4j` and `system` databases

. Put your Neo4j in xref:kubernetes/operations/maintenance-mode.adoc#put-offline-mode[offline mode].
. Dump `neo4j` and `system` databases:
+
[source, shell]
----
neo4j-admin dump --expand-commands --database=system --to /backups/system.dump && neo4j-admin dump --expand-commands --database=neo4j --to /backups/neo4j.dump
----
+
. Put your Neo4j back to xref:kubernetes/operations/maintenance-mode.adoc#put-online-mode[online mode].
. Verify that Neo4j is working by refreshing Neo4j Browser.

[TIP]
====
For information about the command syntax, options, and usage, see xref:backup-restore/offline-backup.adoc[Back up an offline database].
====

[[kubernetes-neo4j-load]]
== Load the `neo4j` and  `system` databases

. Put your Neo4j in xref:kubernetes/operations/maintenance-mode.adoc#put-offline-mode[offline mode]..
. Run `neo4j-admin load` commands:
+
[source, shell]
----
neo4j-admin load --expand-commands --database=system --from /backups/system.dump && neo4j-admin load --expand-commands --database=neo4j --from /backups/neo4j.dump
----
+
[TIP]
====
For information about the command syntax, options, and usage, see xref:backup-restore/restore-dump.adoc[Restore a database dump].
====
+
. Put your Neo4j back to xref:kubernetes/operations/maintenance-mode.adoc#put-online-mode[online mode].
. Verify that Neo4j is working by refreshing Neo4j Browser.