[[kubernetes-neo4j-dump-load]]
= Dump and load databases (offline)

You can use the `neo4j-admin database dump` command to make a full backup (an archive) of an **offline** database(s) and `neo4j-admin database load` to load it back into a Neo4j deployment.
These operations are performed in <<offline-maintenance, offline maintenance mode>>.

[[kubernetes-neo4j-dump]]
== Dump the `neo4j` and `system` databases

. <<put-offline-mode>>.
. Dump `neo4j` and `system` databases:
+
[source, shell]
----
neo4j-admin database dump --expand-commands system --to-path=/backups && neo4j-admin database dump --expand-commands neo4j --to-path=/backups
----
+
. <<put-online-mode>>.
. Verify that Neo4j is working by refreshing Neo4j Browser.

[TIP]
====
For information about the command syntax, options, and usage, see xref:backup-restore/offline-backup.adoc[Back up an offline database].
====

[[kubernetes-neo4j-load]]
== Load the `neo4j` and  `system` databases

. <<put-offline-mode>>.
. Run `neo4j-admin database load` commands:
+
[source, shell]
----
neo4j-admin database load --expand-commands system --from-path=/backups && neo4j-admin database load --expand-commands neo4j --from-path=/backups
----
+
[TIP]
====
For information about the command syntax, options, and usage, see xref:backup-restore/restore-dump.adoc[Restore a database dump].
====
+
. <<put-online-mode>>.
. Verify that Neo4j is working by refreshing Neo4j Browser.