[[_migrate_neo4j_from_the_labs_helm_charts_to_the_neo4j_helm_charts_offline]]
= Migrate Neo4j from Labs Helm to Neo4j Helm charts

To migrate your Neo4j deployment from the Labs Helm charts to the Neo4j Helm charts offline, back up your standalone instance or cluster created with the Labs Helm chart and restore it in a standalone instance or a cluster created using the Neo4j Helm chart.

Neo4j supports the following migration paths for a single instance and a cluster:

Single instance::
* From the Labs Helm chart 3.5 or earlier to either the Neo4j Helm chart 4.3 or 4.4 -- upgrade your Neo4j deployment to whichever version you want to move to, using the steps in the https://neo4j.com/labs/neo4j-helm/1.0.0/ and then migrate from the Labs Helm chart (4.3 or 4.4) to the Neo4j Helm chart 4.3 or 4.4 using the steps described here.
* From the Labs Helm chart 4.3 to the Neo4j Helm chart 4.3 -- follow the steps described here.
* From the Labs Helm chart 4.3 to the Neo4j Helm chart 4.4 -- follow the steps described here.

Cluster::
From the Labs Helm chart 4.3 or 4.4 to the Neo4j Helm chart 4.4 -- follow the steps described here.

== Back up a Neo4j deployment created with the Labs Helm chart

To back up your Neo4j deployment created with the Labs Helm chart, follow the steps in the https://neo4j.com/labs/neo4j-helm/1.0.0/backup/[Neo4j-Helm User Guide -> Backing up Neo4j Containers].

== Restore your backup into a standalone or a cluster created with the Neo4j Helm chart

If the backup exists on a cloud provider, you can take one of the following approaches:

Approach 1::
. Create a standalone or a cluster using the Neo4j Helm chart with a custom Neo4j image that has all the cloud provider utilities to download the backup from the respective cloud provider storage to your specific mount.
. Restore the backup following the steps described in xref:kubernetes/operations/backup-restore.adoc#kubernetes-neo4j-restore[Restore a single database].

Approach 2::
. Get the backup on your local machine.
. Copy the backup to the respective mount in your new cluster created using the Neo4j Helm chart, using the command `kubectl cp <local-path> <pod>:<path>`.
For example,
+
[source, shell]
----
kubectl cp /Users/username/Desktop/backup/4.3.3/neo4j standalone-0:/tmp/
----
where the _/tmp_ directory refers to the mount.
. Restore the backup following the steps described in xref:kubernetes/operations/backup-restore.adoc#kubernetes-neo4j-restore[Restore a single database].