[[reset-password]]
= Reset the `neo4j` user password

You reset the `neo4j` user password by disabling authentication and then re-enabling it.

. In the _values.yaml_ file, set `dbms.security.auth_enabled:` to `false` to disable the authentication:
+
[NOTE]
====
All Neo4j `config` values must be YAML strings, not YAML booleans.
Therefore, make sure you put quotes around values, such as `"true"` or `"false"`, so that they are handled correctly by Kubernetes.
====
+
[source, yaml]
----
# Neo4j Configuration (yaml format)
config:
  dbms.security.auth_enabled: "false"
----
+
. Run the following command to apply the changes:
+
[source, shell]
----
helm upgrade <release-name> neo4j/neo4j-standalone -f values.yaml
----
+
Authentication is now disabled.
+
. Connect with `cypher-shell` and set the desired password:
+
[source, cypher]
----
ALTER USER neo4j SET PASSWORD '<new-password>'
----
+
. Update the Neo4j configuration to enable authentication:
+
[source, yaml]
----
# Neo4j Configuration (yaml format)
config:
  dbms.security.auth_enabled: "true"
----
+
. Run the following command to apply the update and re-enable authentication:
+
[source, shell]
----
helm upgrade <release-name> neo4j/neo4j-standalone -f values.yaml
----
+
Authentication is now enabled, and the Neo4j user password has been reset to the desired password.