:description: The page describes how to restart Neo4j pods after modifying ConfigMaps or secrets.

= How to restart a Neo4j pod after configuration change

When you update ConfigMaps or secrets (for example, updating GDS or Bloom license values), you have to restart your Neo4j pod so that the changes take effect.

You have two options for restarting: 

* To run the `kubectl delete pod` command as follows:
+
[source, shell]
----
kubectl delete pod <pod_name>
----
+
You manually delete the Neo4j pod.
Kubernetes will automatically recreate it with the updated configuration.

* To use the `kubectl rollout restart` command:
+
[source, shell]
----
kubectl rollout restart statefulset/<neo4j-statefulset-name>
----
+
A rollout restart means a gradual recreation of a pod — the old pod is not removed entirely until the new pod is running successfully.
This process is safer and ensures that your application remains available throughout the restart process.


If you need to change Neo4j password, see xref:kubernetes/operations/reset-password.adoc[].

For information on how to install and manage plugins, refer to the xref:kubernetes/plugins.adoc[].

