[[kubernetes-upgrading]]
= Upgrade Neo4j on Kubernetes


== Upgrade to a new release

To upgrade to the next release of Neo4j, update your Neo4j _values.yaml_ file and upgrade the helm release.

. Open the _values.yaml_ file, using the code editor of your choice, and add the following line to the `image` object:
+
[source, yaml, subs="attributes"]
----
image:
  customImage: neo4j:{neo4j-version-exact}
----
+
. Run `helm upgrade` to apply the changes:
+
[source, shell]
----
helm upgrade <release-name> neo4j/neo4j -f values.yaml
----

[NOTE]
====
For detailed steps on how to upgrade a standalone Neo4j across 2025-2026 releases, see link:{neo4j-docs-base-uri}/upgrade-migration-guide/current/version-2025-2026/upgrade/helm-charts/upgrade-standalone/[Upgrade and Migration Guide -> Upgrade a standalone server using Helm chart].

For instructions on how to perform a rolling upgrade of Neo4j cluster across 2025-2026 releases, see link:{neo4j-docs-base-uri}/upgrade-migration-guide/current/version-2025-2026/upgrade/helm-charts/rolling-upgrade-cluster/[Upgrade and Migration Guide -> Upgrade a cluster using Helm chart].
====


== Upgrade Community to Enterprise

To upgrade Neo4j Community to Enterprise edition, run:

[source, shell]
----
helm upgrade <release-name> neo4j/neo4j --reuse-values --set neo4j.edition=enterprise --set neo4j.acceptLicenseAgreement=yes
----