= Database internals
:description: Database internals and transactional behavior


To fully maintain data integrity and ensure good transactional behavior, Neo4j DBMS supports the **ACID** properties:

* **A**tomicity -- If a part of a transaction fails, the database state is left unchanged.
* **C**onsistency -- Every transaction leaves the database in a consistent state.
* **I**solation -- During a transaction, modified data cannot be accessed by other operations.
* **D**urability -- The DBMS can always recover the results of a committed transaction.

Specifically for Neo4j, the following transactional behavior is important to understand:

* All database operations that access the graph, indexes, or schema must be performed in a transaction.
* The default isolation level is _read-committed isolation level_.
* Data retrieved by traversals is not protected from modification by other transactions.
* Non-repeatable reads may occur (i.e., only write locks are acquired and held until the end of the transaction).
* One can manually acquire write locks on nodes and relationships to achieve a higher level of isolation -- _serialization isolation level_.
* Locks are acquired at the Node and Relationship levels.
* Deadlock detection is built into the core transaction management.

The following sections describe the transactional behavior and how to control it.

* xref:database-internals/transaction-management.adoc[]
* xref:database-internals/locks-deadlocks.adoc[]
* xref:database-internals/transaction-logs.adoc[]
* xref:database-internals/checkpointing.adoc[]