:description: Information about the `SHOW TRANSACTIONS` and `TERMINATE TRANSACTIONS` commands.
:test-skip: true
= List and terminate transactions

This page discusses how to use the `SHOW TRANSACTIONS` and `TERMINATE TRANSACTIONS` to list and terminate currently running transactions.
For general information about the `SHOW` command, see the link:{neo4j-docs-base-uri}/cypher-manual/clauses/show/[Cypher Manual -> SHOW].

[[list-transactions]]
== List transactions

The `SHOW TRANSACTIONS` command displays currently running transactions across the instance.
To track transactions on remote database aliases, run `SHOW TRANSACTIONS` while connected to the remote database alias.

[[list-transactions-syntax]]
=== Syntax

[options="header", width="100%", cols="1,5a"]
|===
| Action | Syntax

| List transactions on the current serve

a|
[source, syntax, role="noheader"]
----
SHOW TRANSACTION[S] [transaction-id[,...]]
[YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
[WHERE expression]
[RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----

[NOTE]
====
The format of `transaction-id` is `<databaseName>-transaction-<id>`.
Transaction IDs must be supplied as one or more comma-separated quoted `STRING` values, or as an expression resolving to a `STRING` or a `LIST<STRING>`.
As of Neo4j 2026.06, using Cypher 25, any transaction IDs that resolve to `null` are ignored instead of causing a type error exception.
This is consistent with returning no results when the specified transaction ID does not exist.
====

|===

[NOTE]
====
When using the `RETURN` clause, the `YIELD` clause is mandatory and must not be omitted.
====

A user with the link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/database-administration/#access-control-database-administration-transaction[`SHOW TRANSACTION`] privilege can view currently executing transactions, but only to the extent allowed by their granted permissions. 
All users can always view their own active transactions.

[[list-transactions-return-columns]]
=== Return columns

`SHOW TRANSACTIONS` will produce a table with the following columns:

.List transactions output
[options="header", cols="4,6,2"]
|===
| Column | Description | Type

m| database
a| The name of the database the transaction is executing against. label:default-output[]
m| STRING

m| transactionId
a| The transaction ID. label:default-output[]
m| STRING

m| currentQueryId
a| The ID of the query currently executing in this transaction, or `null` if no query is currently executing. label:default-output[]
m| STRING

m| connectionId
a| The ID of the database connection attached to the transaction or an empty `STRING` for embedded connections. label:default-output[]
m| STRING

m| clientAddress
a| The client address of the connection issuing the transaction or `null` if unavailable. label:default-output[]
m| STRING

m| username
a| The username of the user executing the transaction. label:default-output[]
m| STRING

m| currentQuery
a| The query text of the query currently executing in this transaction, or `null` if no query is currently executing. label:default-output[]
m| STRING

m| startTime
a| The time at which the transaction was started. label:default-output[]
m| ZONED DATETIME

m| status
a| The current status of the transaction (`Terminated`, `Blocked`, `Closing`, or `Running`). label:default-output[]
m| STRING

m| elapsedTime
a| The time that has elapsed since the transaction was started. label:default-output[]
m| DURATION

m| outerTransactionId
a|
The ID of this transaction's outer transaction, if such exists, otherwise `null`.
For details, see the link:{neo4j-docs-base-uri}/cypher-manual/current/subqueries/subqueries-in-transactions/[Cypher Manual -> `CALL` subqueries in transactions].
m| STRING

m| metaData
a| Any metadata associated with the transaction, or an empty map if there is none.
m| MAP

m| parameters
a| A map containing all the parameters used by the query currently executing in this transaction, or `null` if no query is currently executing.
m| MAP

m| planner
a|
The name of the Cypher planner used to plan the query currently executing in this transaction, or `null` if no query is currently executing.
For details, see the link:{neo4j-docs-base-uri}/cypher-manual/current/query-tuning/#cypher-planner[Cypher Manual -> Cypher planner].
m| STRING

m| runtime
a| The name of the Cypher runtime used by the query currently executing in this transaction, or `null` if no query is currently executing.
For details, see the link:{neo4j-docs-base-uri}/cypher-manual/current/planning-and-tuning/runtimes/[Cypher Manual -> Cypher runtimes].
m| STRING

m| indexes
a| The indexes utilized by the query currently executing in this transaction, or `null` if no query is currently executing.
Only indexes evaluating static node labels and relationship types are shown in this column.
m| LIST<MAP>


m| currentQueryStartTime
a| The time at which the query currently executing in this transaction was started, or `null` if no query is currently executing.
m| ZONED DATETIME

m| protocol
a|
The protocol used by the connection issuing the transaction.
This is not necessarily an internet protocol, such as _http_, etc., although it could be.
It might also be "embedded", for example, if this connection represents an embedded session.
m| STRING

m| requestUri
a| The request URI used by the client connection issuing the transaction, or `null` if the URI is not available.
m| STRING


m| currentQueryStatus
a| The current status of the query currently executing in this transaction (`parsing`, `planning`, `planned`, `running`, or `waiting`), or `null` if no query is currently executing.
m| STRING

m| statusDetails
a| Provide additional status details from the underlying transaction or an empty `STRING` if none is available.
m| STRING

m| resourceInformation
a| Information about any blocked transactions, or an empty map if there is none.
m| MAP

m| activeLockCount
a| Count of active locks held by the transaction.
m| INTEGER


m| currentQueryActiveLockCount
a| Count of active locks held by the query currently executing in this transaction.
m| INTEGER

m| cpuTime
a| CPU time that has been actively spent executing the transaction or `null` if unavailable.
m| DURATION

m| waitTime
a| Wait time that has been spent waiting to acquire locks.
m| DURATION

m| idleTime
a| Idle time for this transaction, or `null` if unavailable.
m| DURATION


m| currentQueryElapsedTime
a| The time that has elapsed since the query currently executing in this transaction was started, or `null` if no query is currently executing.
m| DURATION


m| currentQueryCpuTime
a| CPU time that has been actively spent executing the query currently executing in this transaction, or `null` if unavailable or no query is currently executing.
m| DURATION


m| currentQueryWaitTime
a| Wait time that has been spent waiting to acquire locks for the query currently executing in this transaction, or `null` if no query is currently executing.
m| DURATION


m| currentQueryIdleTime
a| Idle time for the query currently executing in this transaction, or `null` if unavailable or no query is currently executing.
m| DURATION


m| currentQueryAllocatedBytes
a| The number of bytes allocated on the heap so far by the query currently executing in this transaction, or `null` if unavailable or no query is currently executing.
m| INTEGER

m| allocatedDirectBytes
a| Amount of off-heap (native) memory allocated by the transaction in bytes or `null` if unavailable.
m| INTEGER

m| estimatedUsedHeapMemory
a| The estimated amount of used heap memory allocated by the transaction in bytes or `null` if unavailable.
m| INTEGER

m| pageHits
a| The total number of page cache hits that the transaction performed.
m| INTEGER

m| pageFaults
a| The total number of page cache faults that the transaction performed.
m| INTEGER


m| currentQueryPageHits
a| The total number of page cache hits that the query currently executing in this transaction performed.
m| INTEGER


m| currentQueryPageFaults
a| The total number of page cache faults that the query currently executing in this transaction performed.
m| INTEGER

m| initializationStackTrace
a| The initialization stacktrace for this transaction, or an empty `STRING` if unavailable.
m| STRING

m| currentQueryProgress
a| A map containing real time metrics of data modifications made by the query currently executing in this transaction, or null if the current transaction is an inner query.
The metrics of data modifications made by the inner queries are aggregated in their outer query on commit. label:cypher[Cypher 25 only] label:new[Introduced in Neo4j 2026.03]
m| MAP

|===

.`currentQueryProgress` map content
[options="header", cols="1a, 3a"]
|===
| Key | Description

| nodesCreated
| Total number of nodes created.

| nodesDeleted
| Total number of nodes deleted.

| relationshipsCreated
| Total number of relationships created.

| relationshipsDeleted
| Total number of relationships deleted.

| propertiesSet
| Total number of properties set.

| labelsAdded
| Total number of labels added.

| labelsRemoved
| Total number of labels removed.

| fileLinesRead
| Total number of CSV file lines read.

| transactionsStarted
| Total number of inner transactions started by the CIT query, if this query is an outer transaction, otherwise null. For details, see the link:{neo4j-docs-base-uri}/cypher-manual/current/subqueries/subqueries-in-transactions/[Cypher Manual -> `CALL` subqueries in transactions].

| transactionsCommitted
| Total number of inner transactions committed by the CIT query, if this query is an outer transaction, otherwise null. For details, see the link:{neo4j-docs-base-uri}/cypher-manual/current/subqueries/subqueries-in-transactions/[Cypher Manual -> `CALL` subqueries in transactions].

| transactionsRolledBack
| Total number of inner transactions rolled back by the CIT query, if this query is an outer transaction, otherwise null. For details, see see the link:{neo4j-docs-base-uri}/cypher-manual/current/subqueries/subqueries-in-transactions/[Cypher Manual -> `CALL` subqueries in transactions].

|===


[[listing-transactions-examples]]
=== Examples

.List all running transactions with default return columns
[source, cypher]
----
SHOW TRANSACTIONS
----

.List all running transactions with all return columns
[source, cypher]
----
SHOW TRANSACTIONS YIELD *
----

.List transactions by transactionId
[source, cypher]
----
SHOW TRANSACTIONS "neo4j-transaction-3"
----

.Filter `SHOW TRANSACTIONS` with `WHERE`
[source, cypher]
----
SHOW TRANSACTIONS YIELD database, currentQuery
WHERE currentQuery contains 'Mark'
----


.Return renamed `SHOW TRANSACTIONS` columns
[source, cypher]
----
SHOW TRANSACTIONS
YIELD transactionId, elapsedTime, cpuTime, waitTime, idleTime,
  currentQueryElapsedTime, currentQueryCpuTime, currentQueryWaitTime, currentQueryIdleTime
RETURN
  transactionId AS txId,
  elapsedTime.milliseconds AS elapsedTimeMillis,
  cpuTime.milliseconds AS cpuTimeMillis,
  waitTime.milliseconds AS waitTimeMillis,
  idleTime.seconds AS idleTimeSeconds,
  currentQueryElapsedTime.milliseconds AS currentQueryElapsedTimeMillis,
  currentQueryCpuTime.milliseconds AS currentQueryCpuTimeMillis,
  currentQueryWaitTime.microseconds AS currentQueryWaitTimeMicros,
  currentQueryIdleTime.seconds AS currentQueryIdleTimeSeconds
----

[role=label--new-2026.05 label--cypher-25-only]
[[composable-show-procedures]]
=== Combine `SHOW TRANSACTIONS` with other Cypher commands

`SHOW TRANSACTIONS` can be combined with other Cypher commands to form a single query.
(In versions earlier than 2026.06 and with using Cypher 5

It has been possible to combine `SHOW TRANSACTIONS` with `TERMINATE TRANSACTIONS` since Neo4j 5.0.
For more information, see xref:database-internals/list-and-terminate-transactions.adoc#combine-transaction-commands[Combine transaction commands] below).


[[terminate-transactions]]
== Terminate transactions

The `TERMINATE TRANSACTIONS` command is used to terminate running transactions by their IDs.

[[terminate-transactions-syntax]]
=== Syntax

[options="header", width="100%", cols="1,5a"]
|===
| Action | Syntax

| Terminate transactions by ID on the current server

a|
[source, syntax, role="noheader"]
----
TERMINATE TRANSACTION[S] transaction_id[, ...]
[YIELD { * \| field[, ...] }
  [ORDER BY field[, ...]]
  [SKIP n]
  [LIMIT n]
  [WHERE expression]
  [RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
]
----

[NOTE]
====
The format of `transaction-id` is `<databaseName>-transaction-<id>`.
Transaction IDs must be supplied as one or more comma-separated quoted `STRING` values, or as an expression resolving to a `STRING` or a `LIST<STRING>`.
As of Neo4j 2026.06, using Cypher 25, any transaction IDs that resolve to `null` are ignored instead of causing a type error exception.
This is consistent with returning no results when the specified transaction ID does not exist.
====
|===

[NOTE]
====
When using the `WHERE` or `RETURN` clauses, the `YIELD` clause is mandatory and must not be omitted.
====

A user with the link:{neo4j-docs-base-uri}/operations-manual/current/authentication-authorization/database-administration/#access-control-database-administration-transaction[`TERMINATE TRANSACTION`] privilege can terminate transactions, subject to the scope of their granted permissions.
All users may terminate their own currently executing transactions.

[[terminate-transactions-return-columns]]
=== Return columns

All columns are returned by default for `TERMINATE TRANSACTIONS`.
As a result, appending `YIELD *` to `TERMINATE TRANSACTIONS` does not return any additional information.


`TERMINATE TRANSACTIONS` returns the following columns:

.Terminate transactions output
[options="header", cols="4,6,2"]
|===
| Column | Description | Type

m| transactionId
a| The transaction ID.
m| STRING

m| username
a| The username of the user executing the transaction.
m| STRING

m| message
a| The result of the `TERMINATE TRANSACTION` command as applied to this transaction.
m| STRING

|===


[[terminate-transactions-examples]]
=== Examples

.Terminate transactions by transaction ID
[source, cypher]
----
TERMINATE TRANSACTIONS "neo4j-transaction-1","neo4j-transaction-2"
----

.Filter `TERMINATE TRANSACTIONS` with `WHERE`
[source, cypher]
----
TERMINATE TRANSACTIONS "neo4j-transaction-1","neo4j-transaction-2"
YIELD transactionId, message
WHERE message <> "Transaction terminated."
----

[NOTE]
====
Unlike the `SHOW` commands, `TERMINATE TRANSACTIONS` does not allow `WHERE` without `YIELD`.
====

[[combine-transaction-commands]]
== Combine transaction commands

`SHOW TRANSACTIONS` can be combined with `TERMINATE TRANSACTIONS` to identify and terminate transactions in the same statement.

[NOTE]
====
When combining `SHOW TRANSACTIONS` and `TERMINATE TRANSACTIONS`, the `YIELD` clause is mandatory and must not be omitted.
In addition, `YIELD *` is not permitted.
Instead, the `YIELD` clause needs to explicitly list the yielded columns.
The query must also end with a valid last clause (like a `RETURN` or an updating clause).
====

.Show all transactions run by user `Alice` and terminate them
[source, cypher]
----
SHOW TRANSACTIONS
YIELD transactionId AS txId, username AS user
WHERE user = "Alice"
TERMINATE TRANSACTIONS txId
YIELD message
RETURN txId, message
----

.Show all transactions running for more than 30 minutes and terminate them
[source, cypher]
----
SHOW TRANSACTIONS
YIELD transactionId, waitTime
WHERE waitTime > duration({minutes: 30})
TERMINATE TRANSACTIONS transactionId
YIELD username, message
RETURN *
----
 
.Listing other transactions by the same user that were terminated
[source, cypher]
----
TERMINATE TRANSACTION 'neo4j-transaction-1', 'neo4j-transaction-2'
YIELD username AS terminatedUser
SHOW TRANSACTIONS
YIELD username AS showUser, transactionId AS txId, database, currentQuery, status
WHERE showUser = terminatedUser AND NOT status STARTS WITH 'Terminated'
RETURN txId, showUser AS user, database, currentQuery
----

.Listing other transactions by the same user as a given transaction
[source, cypher]
----
SHOW TRANSACTION 'neo4j-transaction-1'
YIELD username AS originalUser, transactionId AS originalTxId
SHOW TRANSACTIONS
YIELD username AS newUser, transactionId AS txId, database, currentQuery, status
WHERE newUser = originalUser AND NOT txId = originalTxId
RETURN txId, newUser AS user, database, currentQuery, status
----


[role=label--new-2026.05 label--cypher-25-only]
== Combine transaction commands with other Cypher commands

`SHOW TRANSACTIONS` and `TERMINATE TRANSACTIONS` can be combined with other Cypher commands to form a single query.

[NOTE]
====
When combining a `SHOW` command with other clauses, the `YIELD` clause is mandatory and must not be omitted.
In addition, `YIELD *` is not permitted.
Instead, the `YIELD` clause needs to explicitly list the yielded columns.
The query must also end with a valid last clause (like a `RETURN` or an updating clause).
====

.Transaction commands combined with other Cypher commands
[source, cypher, role=test-result-skip]
----
WITH ['neo4j-transaction-1', 'neo4j-transaction-2', 'mydb-transaction-1'] AS idsToTerminate
TERMINATE TRANSACTION idsToTerminate
YIELD username AS terminatedUser
WITH DISTINCT terminatedUser, idsToTerminate // <1>
SHOW TRANSACTIONS
YIELD username AS showUser, transactionId AS txId, database, currentQuery
WHERE showUser = terminatedUser AND NOT txId IN idsToTerminate
RETURN txId, showUser AS user, database, currentQuery
----

<1> `WITH` is used here to remove any duplicate users and transaction IDs and to bind those values to new variables, `terminatedUser` and `idsToTerminate`.