:description: This chapter describes the `neo4j-admin database info` command.

[[neo4j-admin-store-info]]
= Display store information

You can use the `neo4j-admin database info` command to print information about a Neo4j database store.
The following information about the _store format_ of a given _database store_ can be retrieved:

* The store format version.
* When the store format version was introduced.
* Whether the store format needs to be migrated to a newer version.

For more information on database store formats, see xref:database-internals/store-formats.adoc[Store formats].

The `neo4j-admin database info` command is located in the xref:configuration/file-locations.adoc[_bin_] directory.

[[neo4j-admin-store-info-syntax]]
== Syntax

The `neo4j-admin database info` command should be invoked against an *offline* database store or a backup and has the following syntax:

----
neo4j-admin database info [-h] [--expand-commands] [--verbose]
                          [--additional-config=<file>]
                          [--format=text|json]
                          [--from-path=<path>] [<database>]
----

=== Parameters

.`neo4j-admin database info` parameters
[options="header", cols="1m,3a,1m"]
|===
| Parameter
| Description
| Default

|[<database>]
|Name of the database to show info for.
Can contain * and ? for globbing.
Note that * and ? have special meaning in some shells and might need to be escaped or used with quotes.
| *
|===

=== Options

The `neo4j-admin database info` command has the following options:

.`neo4j-admin database info` options
[options="header", cols="5m,6a,4m"]
|===
| Option
| Description
| Default

|--additional-config=<file>footnote:[See xref:neo4j-admin-neo4j-cli.adoc#_configuration[Neo4j Admin and Neo4j CLI -> Configuration] for details.]
|Configuration file with additional configuration.
|

|--expand-commands
| Allow command expansion in config value evaluation.
|

|--format=text\|json
|The format of the returned information.
|text

|--from-path=<path>
|Path to databases directory.
|

|-h, --help
| Show this help message and exit.
|

|--verbose
| Enable verbose output.
|
|===


== Examples

.Invoke `neo4j-admin database info` against a database store
====
[source, shell]
----
bin/neo4j-admin database info healthcare
----

.Output
[results]
----
Database name:                healthcare
Database in use:              false
Store format version:         block-block-1.1
Store format introduced in:   5.14.0
Last committed transaction id:29
Store needs recovery:         false
----
====

[role=enterprise-edition]
.Invoke `neo4j-admin database info` against all databases
====
[source, shell]
----
bin/neo4j-admin database info --from-path=../data/databases
----

.Output
[results]
----
Database name:                healthcare
Database in use:              false
Store format version:         block-block-1.1
Store format introduced in:   5.14.0
Last committed transaction id:29
Store needs recovery:         false

Database name:                neo4j
Database in use:              false
Store format version:         block-block-1.1
Store format introduced in:   5.14.0
Last committed transaction id:27
Store needs recovery:         false

Database name:                system
Database in use:              false
Store format version:         record-aligned-1.1
Store format introduced in:   5.0.0
Last committed transaction id:213
Store needs recovery:         false
----
====

[NOTE]
====
When the command is invoked against several databases, if some are *online* they will simply report as `in use` and exclude all other information.
====


[role=enterprise-edition]
.Invoke `neo4j-admin database info` against a database and output JSON
====

If you are parsing the results of this command, you may use the `--format=json` option to receive the output as JSON.
All the same fields are included and all values are strings.

[source, shell]
----
bin/neo4j-admin database info --from-path ../data/databases --format=json foo
----

.Output
[results]
----
{"databaseName":"healthcare","inUse":"false","storeFormat":"block-block-1.1","storeFormatIntroduced":"5.14.0","storeFormatSuperseded":null,"lastCommittedTransaction":"29","recoveryRequired":"false"}
----
====