= Store formats
:description: This page describes store formats in Neo4j.

Store formats are responsible for how data is written to disk and how it is read.
The choice of store format can affect the performance and resource consumption of read and write transactions, the size of database files on disk, and the amount of data that can be stored.

// * Which files/filenames exist in the database directory.
// * Performance in memory-constrained environments.
// The same query on different formats may have a different page cache hit ratio when the database does not entirely fit in the page cache.
// * The order of query results when the order is not specified.
// Different store formats may traverse and return data in different order.
// * Algorithms used by the Neo4j Admin tools.
// Especially `neo4j-admin database check` and `neo4j-admin database import` commands.
// Performance and resource utilization may differ.

[[store-format-overview]]
== Available store formats

Here’s an overview of the available formats and their features:

Block:: label:enterprise-edition[] label:version-number[GA in Neo4j 5.16] +
* Default format from Neo4j 5.22 for new databases (unless xref:configuration/configuration-settings.adoc##config_db.format[`db.format`] is specified).
* Best performance, supports the highest limits, uses advanced data structures and inlining techniques for better data locality.
* Allows more related data to be fetched by fewer read operations, enhancing resource utilization.
* Able to run graphs at large scales.
* For store format version compatibility and limits, see <<block-format, Block format>>.

Aligned::
* Default format in Community Edition and for all new databases in Enterprise Edition prior to Neo4j 5.22.
* Based on `standard`.
* Performs better than `standard` but requires slightly more disk space.
* Stores graph data in linked list-like structures on disk.
* For store format version compatibility and limits, see <<aligned-format, Aligned format>>.

Standard:: label:deprecated[Deprecated in 5.23]
* Basic, foundational format.
* Stores graph data in linked list-like structures on disk.
* For store format version compatibility and limits, see <<standard-format, Standard format>>.

High_limit:: label:enterprise-edition[] label:deprecated[Deprecated in 5.23]
* Based on `standard` but allows more nodes and relationships.
* Performs slightly slower than `standard` and requires more disk space.
* Stores graph data in linked list-like structures on disk.
* For store format version compatibility and limits, see <<high-limit-format, High_limit format>>.

[[store-format-comparison]]
== Which store format to choose

Starting from 5.23, the `block` format is the preferred format for Enterprise Edition due to its superior performance and scalability.
Therefore, migrating all databases to the `block` format is recommended to ensure optimal performance.
This format uses advanced data structures and inlining techniques to enhance data locality, which leads to better resource utilization.

`aligned` is the only format available in Community Edition and allows a smooth transition from Community to Enterprise Edition.

`standard` and `high_limit` formats are deprecated starting from Neo4j 5.23. +
However, they will remain part of the product throughout the Neo4j 5 and vNext server lifecycles.
The last version of Neo4j to include these formats will be vNext.LTS, which is planned for release in November 2026 and will be supported for three years.

[role="enterprise-edition"]
[[store-format-faq]]
Questions to consider when selecting a store format for your Enterprise Edition database::
. What should I consider before deciding on a store format? +
Evaluate the performance needs, scalability requirements, and compatibility with existing systems.
Consider future-proofing by choosing a format that will be supported long-term.
+
. What if I am on X format? +
If you are on `aligned`, you can stay on it unless you need to migrate to `block` for better performance and scalability.
If you are on `standard` or `high_limit`, consider migrating to `block`.
+
. Which format to choose if I want to migrate from Community to Enterprise Edition? +
If you are migrating from Community to Enterprise Edition, you can stay on the `aligned` format as it allows a smooth transition.
Then, at a later stage, you can migrate to `block` for better performance and scalability.
+
. When should I plan to migrate from deprecated formats? +
It’s best to migrate sooner rather than later to ensure ongoing support and take advantage of the enhanced performance offered by the `block` format.
+
. Can I have zero downtime migration?
No, changing the store format requires the database to be offline.
For more information on how to change the store format of an existing database, see <<change-store-format, Changing the store format of existing databases>>.
+
. How long does it take to migrate to `block`? +
Migrating to `block` format is an IO-intensive offline operation.
The duration of the migration process depends on several factors:
+
* Database Size: Larger databases take longer to migrate.
* Graph Complexity: More complex graphs require more processing time.
* Hardware Performance: Faster hardware can significantly reduce migration time.
+
Therefore, it is recommended to perform a dry run on a backup to estimate the required time for the migration.
Under optimal conditions, migrating 100GB of data typically takes around 10 minutes.
+
. How much disk space is required for migrating to `block` format? +
The database is inherently compacted during the migration process.
Therefore, the disk space required for the migration is approximately the same as the size of the database.
You can use the xref:monitoring/metrics/reference.adoc#db-store-size-metrics[database store size metrics] to determine your available disk space and potentially reusable space.

[[how-to-set-store-format]]
== How to set the database store format

You can either set the store format when creating a new database or change the store format of an existing database.

[role="enterprise-edition"]
[[create-new-databases]]
=== Creating new databases

In versions previous to Neo4j 5.22, the default store format for all new databases is `aligned`.
From Neo4j 5.22, `block` is the default format for all newly-created databases as long as they do not have the xref:configuration/configuration-settings.adoc#config_db.format[`db.format`] setting specified. +
If you want to change it, you can set a new value for the xref:configuration/configuration-settings.adoc#config_db.format[`db.format`] configuration in the _neo4j.conf_ file. +
You can also create a new database on a specific store format by passing the new format as an argument to the command creating the database, for example, xref:tools/neo4j-admin/neo4j-admin-import.adoc#import-tool-full[`neo4j-admin database import full`] or xref:backup-restore/copy-database.adoc[`neo4j-admin database copy`] commands, or by using `storeFormat:` option in the Cypher command `CREATE DATABASE`.

The following examples show how to create a new database on the `block` store format.
However, the same applies to other formats.

.Specify the store format when importing a database using the `neo4j-admin database import full` command
[source,shell]
----
bin/neo4j-admin database import full ... --format=block blockdb
----

.Specify the store format when copying a database using the `neo4j-admin database copy` command
[source,shell]
----
bin/neo4j-admin database copy --to-format="block" mydb blockdb
----

.Specify the store format when creating a new database using the `CREATE DATABASE` Cypher statement
[source,cypher]
----
CREATE DATABASE blockdb OPTIONS {storeFormat: 'block'}
----

[[change-store-format]]
=== Changing the store format of existing databases

Changing the store format is possible by re-writing all data in the new format.
Therefore, it requires that:

* There is enough disk space for both old and new copies of the database.
* The graph fits within the new <<store-formats-entity-limits, format's entity limits>>.

[NOTE]
====
Changing the store format can be a time-consuming operation, depending on the size and complexity of the data in the database.
Performance heavily depends on the speed of the disk and the amount of available memory.
For more information see <<store-format-faq, Questions to consider when selecting a store format for your Enterprise Edition database>>.
====

[[change-store-format-standalone]]
==== In a standalone server

Changing the store format of an existing database in a standalone server requires the database to be offline.
The following steps assume that you want to migrate the database called `mydb` to `block` format but the same steps apply to other formats.

. Stop the database using the Cypher command `STOP DATABASE mydb`.
. Change the store format of the stopped database using *one* of the following options:

* Migrate an existing database using xref:tools/neo4j-admin/migrate-database.adoc[`neo4j-admin database migrate`] command.
+
[IMPORTANT]
====
You do not need to run `neo4j-admin database copy` with the `--compact-node-store` option prior to running `neo4j-admin database migrate`.
The database is inherently compacted during the migration process.
====
+
For example:
+
[source,shell]
----
bin/neo4j-admin database migrate --to-format="block" mydb
----

* Pass the new store format as an argument when using the xref:backup-restore/copy-database.adoc[`neo4j-admin database copy`] command to create a copy of an existing database.
You can also set the `--copy-schema` option to automatically copy the schema definitions.
For example:
+
[source,shell]
----
bin/neo4j-admin database copy --to-format="block" mydb blockdb --copy-schema
----
. After the successful completion, start the database using the Cypher command `START DATABASE mydb`.
Indexes are populated the first time the database is started, which might take some time if there are uniqueness constraints.

[[change-store-format-cluster]]
==== In a cluster

Changing the store format of an existing database in a cluster requires that you restore a backup of the database that you want to migrate on one of the servers, and then, use that server as a xref:clustering/databases.adoc#cluster-designated-seeder[designated seeder] for the other cluster members to copy that database from.

The following steps assume that you want to migrate the database called `mydb` to `block` format but the same steps apply to other formats.
The database is hosted on three servers in primary mode.

**On one of the servers, `server01`**

. In Cypher Shell, put the database that you want to migrate in read-only mode using the Cypher command xref:database-administration/standard-databases/alter-databases.adoc#manage-databases-alter[`ALTER DATABASE databasename​ SET ACCESS READ ONLY`].
For example:
+
[source,cypher]
----
@system> ALTER DATABASE mydb SET ACCESS READ ONLY;
----
. In your command-line tool, back up that database using the xref:backup-restore/online-backup.adoc[`neo4j-admin database backup`] command.
For example:
+
[source,shell]
----
bin/neo4j-admin database backup mydb --to-path=/path/to/your-backup-folder --include-metadata=all
----
. Back in Cypher Shell, drop the database to delete it and all users and roles associated with it:
+
[source,cypher]
----
@system> DROP DATABASE mydb;
----
. In the command-line tool, restore the backup that you created using the xref:backup-restore/restore-backup.adoc[`neo4j-admin database restore`] command:
+
[source,shell]
----
bin/neo4j-admin database restore --from-path=/path/to/your-backup-folder/mydb-2024-03-05T11-26-38.backup mydb
----
. Migrate the restored database to `block` format:
+
[IMPORTANT]
====
You do not need to run `neo4j-admin database copy` with the `--compact-node-store` option prior to running `neo4j-admin database migrate`.
The database is inherently compacted during the migration process.
====
+
[source,shell]
----
bin/neo4j-admin database migrate --to-format="block" mydb
----
. In Cypher Shell, run `SHOW SERVERS` to find the server ID of `server01`.
Cross-reference the address to find the server ID.
Use any database to connect.
+
[source,shell]
----
SHOW SERVERS YIELD serverId, name, address, state, health, hosting
----

**On one of the servers:**

. Use the `system` database and create the migrated database `mydb` using the server ID of `server01`.
The topology of `mydb` is stored in the `system` database and when you create it, it is allocated according to the default topology (which can be shown with `CALL dbms.showTopologyGraphConfig`).
For more information, see xref:clustering/databases.adoc#cluster-designated-seeder[Designated seeder].
+
[source,cypher]
----
CREATE DATABASE mydb OPTIONS {existingData: 'use', existingDataSeedInstance: '<server01 id>'}
----
. Verify that the database is created and available using the Cypher command `SHOW DATABASE mydb`.
. After the successful completion, restore the roles and permissions.
For more information, see xref:backup-restore/restore-backup.adoc#_restore_users_and_roles_metadata[Restore users and roles metadata].

[[verify-store-format]]
=== Verify the store format

You can verify the store format of a database using the following Cypher:

[source,cypher]
----
SHOW DATABASES YIELD name, store
----

.Result
[role="queryresult"]
----
+----------------------------------+
| name      | store                |
+----------------------------------+
| "blockdb" | "block-block-1.1"    |
| "neo4j"   | "record-aligned-1.1" |
| "system"  | "record-aligned-1.1" |
+----------------------------------+
----

Additionally, you can use the `neo4j-admin database info` command to get detailed information about the store format of a database.
For details, see xref:tools/neo4j-admin/neo4j-admin-store-info.adoc[Display store information].

[[store-formats-entity-limits]]
== Store formats and entity limits

The following tables show the format and Neo4j version compatibility and the limits of the different store formats:

[role=enterprise-edition]
[[block-format]]
=== Block format

.Block format and Neo4j version compatibility
[options="header"]
|===
| Name | Store format version | Introduced in | GA from | Default in

| `BLOCK_V1`
| `block-block-1.1`
| `5.14.0`
| `5.16.0`
| `5.22.0`

|===


[[block-format-limits]]
.Block format entity limits
[options="header"]
|===
| Name | Limit

| Nodes
| `2^48` (281 474 976 710 656)

| Relationships
| `∞` (no defined upper bound)

| Properties
| `∞` (no defined upper bound)

| Labels
| `2^31` (2 147 483 648)

| Relationship types
| `2^30` (1 073 741 824)

| Property keys
| `2^31` (2 147 483 648)

|===

[[aligned-format]]
=== Aligned format

.Aligned format and Neo4j version compatibility
[options="header"]
|===
| Name | Store format version | Introduced in | Default in | Unsupported from

| `ALIGNED_V5_0`
| `record-aligned-1.1`
| `5.0.0`
| CE, EE < Neo4j 5.22
|

| `ALIGNED_V4_3`
| `AF4.3.0`
| `4.3.0`
| `5.0.0`
|

| `ALIGNED_V4_1`
| `AF4.1.a`
| `4.1.0`
| `5.0.0`
|
|===


[[aligned-limits]]
.Aligned format entity limits
[options="header"]
|===
| Name | Limit

| Property keys
| `2^24` (16 777 216)

| Nodes
| `2^35` (34 359 738 368)

| Relationships
| `2^35` (34 359 738 368)

| Properties
| `2^36` (68 719 476 736)

| Labels
| `2^31` (2 147 483 648)

| Relationship types
| `2^16` (65 536)

| Relationship groups
| `2^35` (34 359 738 368)
|===


[role=label--deprecated-5.23]
[[standard-format]]
=== Standard format


.Standard format and Neo4j version compatibility
[options="header"]
|===
| Name | Store format version | Introduced in | Unsupported from

| `STANDARD_V5_0`
| `record-standard-1.1`
| `5.0.0`
|

| `STANDARD_V4_3`
| `SF4.3.0`
| `4.3.0`
| `5.0.0`

| `STANDARD_V4_0`
| `SF4.0.0`
| `4.0.0`
| `5.0.0`

| `STANDARD_V3_4`
| `v0.A.9`
| `3.4.0`
| `5.0.0`
|===


[[standard-limits]]
.Standard format entity limits
[options="header"]
|===
| Name | Limit

| Property keys
| `2^24` (16 777 216)

| Nodes
| `2^35` (34 359 738 368)

| Relationships
| `2^35` (34 359 738 368)

| Properties
| `2^36` (68 719 476 736)

| Labels
| `2^31` (2 147 483 648)

| Relationship types
| `2^16` (65 536)

| Relationship groups
| `2^35` (34 359 738 368)
|===

[role=enterprise-edition label--deprecated-5.23]
[[high-limit-format]]
=== High_limit format


.High_limit format and Neo4j version compatibility
[options="header"]
|===
| Name | Store format version | Introduced in | Unsupported from

| `HIGH_LIMIT_V5_0`
| `record-high_limit-1.1`
| `5.0.0`
|

| `HIGH_LIMIT_V4_3_0`
| `HL4.3.0`
| `4.3.0`
| `5.0.0`

| `HIGH_LIMIT_V4_0_0`
| `HL4.0.0`
| `4.0.0`
| `5.0.0`

| `HIGH_LIMIT_V3_4_0`
| `vE.H.4`
| `3.4.0`
| `5.0.0`

| `HIGH_LIMIT_V3_2_0`
| `vE.H.3`
| `3.2.0`
| `5.0.0`

| `HIGH_LIMIT_V3_1_0`
| `vE.H.2`
| `3.1.0`
| `5.0.0`

| `HIGH_LIMIT_V3_0_6`
| `vE.H.0b`
| `3.0.6`
| `5.0.0`

| `HIGH_LIMIT_V3_0_0`
| `vE.H.0`
| `3.0.0`
| `5.0.0`
|===


[[high-format-limits]]
.High_limit format entity limits
[options="header"]
|===
| Name | Limit

| Property keys
| `2^24` (16 777 216)

| Nodes
| `2^50` (1 Quadrillion)

| Relationships
| `2^50` (1 Quadrillion)

| Properties
| `2^50` (1 Quadrillion)

| Labels
| `2^31` (2 147 483 648)

| Relationship types
| `2^24` (16 777 216)

| Relationship groups
| `2^50` (1 Quadrillion)
|===
