[[transaction-management]]
= Transaction management

== Transactions

Database operations that access the graph, indexes, or schema are performed in a transaction to ensure the ACID properties.
Transactions are single-threaded, confined, and independent.
Multiple transactions can be started in a single thread and they are independent of each other.

The interaction cycle of working with transactions follows the steps:

. Begin a transaction.
. Perform database operations.
. Commit or roll back the transaction.

It is crucial to finish each transaction because the xref:/database-internals/locks-deadlocks.adoc#_locks[locks] or memory acquired by a transaction are only released upon completion.
All non-committed transactions are rolled back as part of resource cleanup at the end of the statement.
No resource cleanup is required for a transaction that is explicitly committed or rolled back, and the transaction closure is an empty operation.

[NOTE]
====
All modifications performed in a transaction are kept in memory.
This means that very large updates must be split into several transactions to avoid running out of memory.
====

== Configure transactional behavior

The transaction settings help you manage the transactions in your database, for example, the transaction timeout, the maximum number of concurrently running transactions, how much time to allow Neo4j to wait for running transactions to complete before allowing initiated database shutdown to continue, and so on.
For all available settings, see xref:/configuration/configuration-settings.adoc#_transaction_settings[Transaction settings].

=== Configure the maximum number of concurrently running transactions

By default, Neo4j can run a maximum of 1000 concurrent transactions.
To change this value, use the xref:configuration/configuration-settings.adoc#config_db.transaction.concurrent.maximum[`db.transaction.concurrent.maximum`] setting.
If set to `0`, the limit is disabled.

[[transaction-management-transaction-timeout]]
=== Configure transaction timeout

It is recommended to configure Neo4j to terminate transactions whose execution time has exceeded the configured timeout.

* Set `xref:configuration/configuration-settings.adoc#config_db.transaction.timeout[db.transaction.timeout]` to some positive time interval value (e.g.,`10s`) denoting the default transaction timeout.
Setting `db.transaction.timeout` to `0` -- which is the default value -- disables the feature.

* You can also set this dynamically on each primary server using the procedure `dbms.setConfigValue('db.transaction.timeout','10s')`.

.Configure transaction timeout
====
Set the timeout to ten seconds.
[source, parameters]
----
db.transaction.timeout=10s
----
====

Configuring transaction timeout does not affect transactions executed with custom timeouts (e.g., via the Java API or Neo4j Drivers), as the custom timeout overrides the value set for `db.transaction.timeout`.
Note that the timeout value can only be overridden to a value that is smaller than that configured by `db.transaction.timeout`.
The _transaction timeout_ feature is also known as the _transaction guard_.


== Manage transactions

Transactions can be managed using the Cypher commands `SHOW TRANSACTIONS` and `TERMINATE TRANSACTIONS`.
The `TERMINATE TRANSACTIONS` command can be combined with multiple `SHOW TRANSACTIONS` and `TERMINATE TRANSACTIONS` commands in the same query.

For more information, see link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/clauses/transaction-clauses/[Cypher manual -> Transaction commands].

// [[transaction-management-list-transactions]]
// === List all running transactions

// To list all running transactions on the current server, use the `SHOW TRANSACTIONS` command.

// [NOTE]
// ====
// The command `SHOW TRANSACTIONS` returns only the default output.
// For a full output use `SHOW TRANSACTIONS YIELD *`.

// For more information on this command, such as syntax, output fields, filtering, and examples, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/clauses/transaction-clauses#query-listing-transactions[Cypher manual -> `SHOW TRANSACTIONS` command].
// ====

// A user with the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/administration/access-control/database-administration#access-control-database-administration-transaction[`SHOW TRANSACTION` privilege] can view the currently executing transactions per the privilege grants.

// All users may view all of their own currently executing transactions.

// === Terminata a transaction

// To terminate a transaction, use the `TERMINATE TRANSACTIONS` command.

// [[query-management-terminate-queries]]
// == Terminate queries

// Queries are terminated by terminating the transaction on which they are running. This is done using the `TERMINATE TRANSACTIONS transactionIds` command.
// The `transactionIds` can be found using the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/clauses/transaction-clauses#query-listing-transactions[`SHOW TRANSACTIONS` command].

// The link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/administration/access-control/database-administration#access-control-database-administration-transaction[`TERMINATE TRANSACTION` privilege] determines what transactions can be terminated.
// However, the xref:authentication-authorization/terminology.adoc#term-current-user[current user] can always terminate all of their own transactions.

// *Syntax:*

// `TERMINATE TRANSACTIONS transactionIds`

// *Argument:*

// [options="header"]
// |===
// | Name | Type | Description
// | `transactionIds` | Comma-separated strings | The IDs of all the transactions to be terminated.
// | `transactionIds` | Single string parameter | The ID of the transaction to be terminated.
// | `transactionIds` | List parameter | The IDs of all the transactions to be terminated.
// |===

// For more information on the command, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/clauses/transaction-clauses#query-terminate-transactions[Cypher manual -> `TERMINATE TRANSACTIONS` command].
