:description: How to use Cypher to manage database aliases in composite databases in Neo4j.
[role=enterprise-edition aura-db-enterprise]
[[manage-aliases-composite-databases]]
= Managing database aliases for composite databases

Both local and remote database aliases can be created as part of a composite database.

[[alias-management-escaping]]
== Alias names and escaping
////
[source, cypher, role=test-setup]
----
CREATE DATABASE `northwind-graph`;
CREATE COMPOSITE DATABASE `my-composite-database-with-dashes`;
CREATE COMPOSITE DATABASE `my.composite.database.with.dots`;
CREATE COMPOSITE DATABASE mySimpleCompositeDatabase;
CREATE COMPOSITE DATABASE `myCompositeDatabase.withDot`;
----
////

Naming database aliases in composite databases follows the same rule as xref:database-administration/aliases/naming-aliases.adoc[naming aliases for standard databases].
However, when it comes to escaping names using backticks, there are some additional things to consider:

=== Escaping database alias and composite database names

The composite database name and the database alias name need to be escaped individually.
Backticks may be added regardless of whether the name contains special characters or not, so it is good practice to always backtick both names, e.g.  `++`composite`++.++`alias`++`.

The following example creates a database alias named `my alias with spaces` as a constituent in the composite database named `my-composite-database-with-dashes`:

.Query
[source, cypher]
----
CREATE ALIAS `my-composite-database-with-dashes`.`my alias with spaces` FOR DATABASE `northwind-graph`
----

When not escaped individually, a database alias with the full name `my alias with.dots and spaces` gets created instead:

.Query
[source, cypher]
----
CREATE ALIAS `my alias with.dots and spaces` FOR DATABASE `northwind-graph`
----

=== Handling multiple dots

//Examples where dots are not separators between composite name and alias name are impossible to test, because the right escaping cannot be inferred automatically.

Database alias names may also include dots.
Though these always need to be escaped in order to avoid ambiguity with the composite database and database alias split character.

.Query
[source, cypher, role=test-skip]
----
CREATE ALIAS `my.alias.with.dots` FOR DATABASE `northwind-graph`
----

.Query
[source, cypher, role=test-skip]
----
CREATE ALIAS `my.composite.database.with.dots`.`my.other.alias.with.dots` FOR DATABASE `northwind-graph`
----

=== Single dots and local database aliases

label:deprecated[]

There is a special case for local database aliases with a single dot without any existing composite database.
If a composite database `some` exists, the query below will create a database alias named `alias` within the composite database `some`.
If no such database exists, however, the same query will instead create a database alias named `some.alias`:

.Query
[source, cypher]
----
CREATE ALIAS some.alias FOR DATABASE `northwind-graph`
----

=== Handling parameters

When using parameters, names cannot be escaped.
When the given parameter includes dots, the first dot will be considered the divider for the composite database.

Consider the query with parameter:

.Parameters
[source, javascript]
----
{
  "aliasname": "mySimpleCompositeDatabase.myAlias"
}
----

.Query
[source, cypher]
----
CREATE ALIAS $aliasname FOR DATABASE `northwind-graph`
----

If the composite database `mysimplecompositedatabase` exists, then a database alias `myalias` will be created in that composite database.
If no such composite database exists, then a database alias `mysimplecompositedatabase.myalias` will be created.

On the contrary, a database alias `myalias` cannot be created in composite `mycompositedatabase.withdot` using parameters.
Consider the same query but with the following parameter:

.Parameters
[source, javascript]
----
{
  "aliasname": "myCompositeDatabase.withDot.myAlias"
}
----

Since the first dot will be used as a divider, the command will attempt to create the database alias `withdot.myalias` in the composite database `mycompositedatabase`.
If `mycompositedatabase` doesn't exist, the command will create a database alias with the name `mycompositedatabase.withdot.myalias`, which is not part of any composite database.

In these cases, it is recommended to avoid parameters and explicitly escape the composite database name and alias name separately to avoid ambiguity.

=== Handling parameters

Further special handling with parameters is needed for database aliases and similarly named composite databases.

Consider the setup:

.Query
[source, cypher, role="noheader test-skip"]
----
CREATE COMPOSITE DATABASE foo
CREATE ALIAS `foo.bar` FOR DATABASE `northwind-graph`
----

The alias `foo.bar` does not belong to the composite database `foo`.

Dropping this alias using parameters fails with an error about a missing alias:

.Parameters
[source, javascript]
----
{
  "aliasname": "foo.bar"
}
----

.Query
[source, cypher, role=test-fail]
----
DROP ALIAS $aliasname FOR DATABASE
----

.Error message
[source, output, role="noheader"]
----
Failed to delete the specified database alias 'foo.bar': Database alias does not exist.
----

Had the composite database `foo` not existed, the database alias `foo.bar` would have been dropped.

In these cases, it is recommended to avoid parameters and explicitly escape the composite database name and alias name separately to avoid ambiguity.

[[create-composite-database-alias]]
== Create database aliases in composite databases

Both local and remote database aliases can be part of a xref::database-administration/composite-databases/manage-composite-databases.adoc[composite database].

The database alias is made of two parts, separated by a dot: the namespace and the alias name.

The namespace must be the name of the composite database.

.Query
[source, cypher]
----
CREATE ALIAS garden.flowers
FOR DATABASE `perennial-flowers`
----

.Query
[source, cypher]
----
CREATE ALIAS garden.trees
FOR DATABASE trees AT 'neo4j+s://location:7687'
USER alice PASSWORD 'password'
----

When a database alias has been created in a composite database, it will show up in the `constituents` column provided by the command `SHOW DATABASES` and in the `SHOW ALIASES FOR DATABASE` command.

.Query
[source, cypher]
----
SHOW DATABASE garden YIELD name, type, constituents
----

.Result
[role="queryresult"]
----
+-------------------------------------------------------------+
| name     | type        | constituents                       |
+-------------------------------------------------------------+
| "garden" | "composite" | ["garden.flowers", "garden.trees"] |
+-------------------------------------------------------------+
----

.Query
[source, cypher]
----
SHOW ALIASES FOR DATABASE WHERE name STARTS WITH 'garden'
----

.Result
[role="queryresult"]
----
+-----------------------------------------------------------------------------------------------------+
| name             | composite | database            | location | url                       | user    |
+-----------------------------------------------------------------------------------------------------+
| "garden.flowers" | "garden"  | "perennial-flowers" | "local"  | NULL                      | NULL    |
| "garden.trees"   | "garden"  | "trees"             | "remote" | "neo4j+s://location:7687" | "alice" |
+-----------------------------------------------------------------------------------------------------+
----

Database aliases cannot target a composite database.

.Query
[source, cypher, role=test-fail]
----
CREATE ALIAS yard FOR DATABASE garden
----

.Error message
[source, output, role="noheader"]
----
Failed to create the specified database alias 'yard': Database 'garden' is composite.
----

== Alter local and remote aliases in composite databases

Examples of altering local and remote database alias in composite databases.

.Query
[source, cypher]
----
ALTER ALIAS garden.flowers SET DATABASE PROPERTIES { perennial: true }
----

.Query
[source, cypher]
----
ALTER ALIAS garden.trees SET DATABASE TARGET updatedTrees AT 'neo4j+s://location:7687' PROPERTIES { treeVersion: 2 }
----

The updated properties can then be used in queries with the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/functions/graph/#functions-graph-propertiesByName[`graph.propertiesByName()` function].

The changes for all database aliases will show up in the `SHOW ALIASES FOR DATABASE` command.

.Query
[source, cypher]
----
SHOW ALIASES FOR DATABASE YIELD *
WHERE name IN ['northwind', 'remote-northwind', 'remote-with-driver-settings', 'movie scripts',
'motion pictures', 'garden.flowers', 'garden.trees']
----

.Result
[role="queryresult"]
----
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| name                          | composite | database               | location | url                             | user    | driver                                             | properties                                            |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "garden.flowers"              | "garden"  | "perennial-flowers"    | "local"  | NULL                            | NULL    | NULL                                               | {perennial: TRUE}                                     |
| "garden.trees"                | "garden"  | "updatedtrees"         | "remote" | "neo4j+s://location:7687"       | "alice" | {}                                                 | {treeversion: 2}                                      |
| "motion pictures"             | NULL      | "movies"               | "local"  | NULL                            | NULL    | NULL                                               | {namecontainsspace: TRUE, moreinfo: "no, not really"} |
| "movie scripts"               | NULL      | "scripts"              | "remote" | "neo4j+s://location:7687"       | "alice" | {}                                                 | {namecontainsspace: TRUE}                             |
| "northwind"                   | NULL      | "northwind-graph-2021" | "local"  | NULL                            | NULL    | NULL                                               | {}                                                    |
| "remote-northwind"            | NULL      | "northwind-graph-2020" | "remote" | "neo4j+s://other-location:7687" | "alice" | {}                                                 | {}                                                    |
| "remote-with-driver-settings" | NULL      | "northwind-graph-2020" | "remote" | "neo4j+s://location:7687"       | "bob"   | {logging_level: "DEBUG", connection_timeout: PT1M} | {}                                                    |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
----

== Delete aliases in composite databases

Delete an alias in a composite database.

.Query
[source, cypher]
----
DROP ALIAS garden.flowers FOR DATABASE
----

When a database alias has been deleted, it will no longer show up in the `SHOW ALIASES FOR DATABASE` command.

.Query
[source, cypher]
----
SHOW ALIASES FOR DATABASE
----

.Result
[role="queryresult"]
----
+---------------------------------------------------------------------------------------------------------------------+
| name                          | composite | database               | location | url                       | user    |
+---------------------------------------------------------------------------------------------------------------------+
| "films"                       | NULL      | "movies"               | "local"  | NULL                      | NULL    |
| "garden.trees"                | "garden"  | "updatedtrees"         | "remote" | "neo4j+s://location:7687" | "alice" |
| "library.romance"             | "library" | "romance-books"        | "remote" | "neo4j+s://location:7687" | "alice" |
| "library.sci-fi"              | "library" | "sci-fi-books"         | "local"  | NULL                      | NULL    |
| "motion pictures"             | NULL      | "movies"               | "local"  | NULL                      | NULL    |
| "movie scripts"               | NULL      | "scripts"              | "remote" | "neo4j+s://location:7687" | "alice" |
| "northwind-2022"              | NULL      | "northwind-graph-2022" | "local"  | NULL                      | NULL    |
| "remote-northwind-2021"       | NULL      | "northwind-graph-2021" | "remote" | "neo4j+s://location:7687" | "alice" |
| "remote-with-driver-settings" | NULL      | "northwind-graph-2020" | "remote" | "neo4j+s://location:7687" | "bob"   |
+---------------------------------------------------------------------------------------------------------------------+
----