:description: Rules for naming database aliases in Neo4j.
:page-role: enterprise-edition aura-db-business-critical aura-db-dedicated
= Naming rules for database aliases

Database alias names are subject to the standard Cypher restrictions on valid identifiers.
See link:{neo4j-docs-base-uri}/cypher-manual/5/syntax/naming[Cypher Manual -> Naming rules and recommendations].

The following naming rules apply:

* A name is a valid identifier.
* Name length can be up to 65534 characters.
* Names cannot end with dots.
* Unquoted dots signify that the database alias belongs to a composite database, separating the composite database name and the alias name.
* Names that begin with an underscore or with the prefix `system` are reserved for internal use.
* Non-alphabetic characters, including numbers, symbols, dots, and whitespace characters, can be used in names, but must be quoted using backticks.

The name restrictions and escaping rules apply to all the different database alias commands.

[NOTE]
====
Having dots (`.`) in the database alias names is not recommended.
This is due to the difficulty of determining if a dot is part of the database alias name or a delimiter for a database alias in a composite database.
For more details, see xref:database-administration/aliases/manage-aliases-composite-databases.adoc#alias-management-escaping[names and escaping for database aliases targeting composite databases].
====