[[si-create-pv]]
= Create a persistent volume

You create a persistent volume to be used for the `data` volume mount.
For more information on persistent volumes and mounts, see xref:kubernetes/persistent-volumes.adoc[Volume mounts and persistent volumes].

[.tabbed-example]
=====
[.include-with-gke]
======
Create a GCP persistent disk using the following command.
This is a normal GCP persistent disk and not Kubernetes specific:

[source, shell]
----
gcloud compute disks create --size 128Gi --type pd-ssd "my-neo4j-disk"
----

[source, role=noheader]
----
Created [https://www.googleapis.com/compute/v1/projects/my-neo4j-project/zones/europe-west2-a/disks/my-neo4j-disk].
NAME           ZONE            SIZE_GB  TYPE    STATUS
my-neo4j-disk  europe-west2-a  128      pd-ssd  READY

New disks are unformatted. You must format and mount a disk before it
can be used. You can find instructions on how to do this at:

https://cloud.google.com/compute/docs/disks/add-persistent-disk#formatting
----

[NOTE]
====
The message `New disks are unformatted. You must format and mount a disk before it can be used.` _should not_ be a cause for concern, and *_there is no need to take action to format the disk_*.
If necessary, the disk will be formatted automatically when used in Kubernetes.
====
======

[.include-with-aws]
======
Create an AWS EBS disk using the following command.
This is a normal AWS EBS disk and not Kubernetes specific:

[source, shell]
----
aws ec2 create-volume --availability-zone=${AWS_AVAILABILITY_ZONE} --size=64 --volume-type=gp3 --tag-specifications 'ResourceType=volume,Tags=[{Key=volume,Value=neo4j-k8s}]'
----

Fetch the ID of the disk that was just created.

[source, shell]
----
aws ec2 describe-volumes --filters Name=tag:volume,Values=neo4j-k8s --query "Volumes[*].{ID:VolumeId}" --output text
----

[source, role=noheader]
----
vol-0795be227aff63b2a
----
======

[.include-with-azure]
======
. Get the node resource group name by running the following command:
+
[source, shell]
----
MC_RG_NAME="$(az aks show --name my-neo4j-aks-cluster --query nodeResourceGroup --output tsv)"
----
. Create an Azure-managed disk for your Neoj4 standalone instance using the following commands.
This is a normal Azure managed disk and not Kubernetes specific:
+
[source, shell]
----
az disk create --name "my-neo4j-disk" --size-gb "64" --sku Premium_LRS --max-shares 1 --resource-group "${MC_RG_NAME}"
----

. Fetch the ID of the disk that was just created, for example:
+
[source, shell]
----
az disk show --name "my-neo4j-disk" --query id --resource-group "${MC_RG_NAME}"
----

. Make a note of it.
+
[source, role=noheader]
----
"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MC_myneo4jrg_my-neo4j-aks-cluster_westus2/providers/Microsoft.Compute/disks/my-neo4j-disk"
----
======

[.include-with-docker-desktop]
======

[NOTE]
====
For Docker Desktop for macOS, this Quickstart guide leans on a dynamically provisioned volume. +
The Neo4j helm command creates a Neo4j StatefulSet that relies on the default Kubernetes `StorageClass` to dynamically provision a persistent volume.
As a consequence, the volume will not survive a Kubernetes restart.
====
======
=====
