:description: Install a Neo4j standalone instance.
[[si-install-neo4j]]
= Install a Neo4j standalone instance

Getting everything to work in Kubernetes requires that certain K8s objects have specific names that are referenced elsewhere.
Each individual Neo4j instance is a Helm “release” and has a _release name_.
All other names derive from this _release name_. +
Release name must consist of lower case alphanumeric characters, `-` or `.`, and must start and end with an alphanumeric character.
This guide assumes the release name is `my-neo4j-release`.

. Install Neo4j using the deployment _values.yaml_ file, created in xref:kubernetes/quickstart-standalone/create-value-file.adoc[Create a value.yaml file], and the `neo4j/neo4j-standalone` Helm Chart:
+
[source, shell, subs="attributes"]
----
helm install my-neo4j-release neo4j/neo4j-standalone -f my-neo4j.values.yaml
----
+
.Example output
[source, role=noheader, subs="attributes"]
----
NAME: my-neo4j-release
LAST DEPLOYED: Wed Jul 28 13:16:39 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing neo4j-standalone.

Your release "my-neo4j-release" has been installed .

To view the progress of the rollout try:

  $ kubectl rollout status --watch --timeout=600s statefulset/my-neo4j-release


The neo4j user's password has been set to "bO7YDTVOgs7CS1".

Once rollout is complete you can log in to Neo4j at "neo4j://my-neo4j-release.default.svc.cluster.local:7687". Try:

  $ kubectl run --rm -it --image "neo4j:{neo4j-version-exact}" cypher-shell \
     -- cypher-shell -a "neo4j://my-neo4j-release.default.svc.cluster.local:7687" -u neo4j -p "bO7YDTVOgs7CS1"

Graphs are everywhere!
----
+
. Run the `kubectl rollout` command provided in the output of `helm install` to watch the Neo4j's rollout until it is complete.
+
[source, shell]
----
kubectl rollout status --watch --timeout=600s statefulset/my-neo4j-release
----
+
[NOTE]
====
Since you have not passed a password for the `neo4j` user, the Neo4j Helm Chart has set an automatically generated one.
You can find it in the Helm install output.
Please make a note of it.
====
