:description: Neo4j Helm chart for standalone server deployments.
[[si-server-setup]]
= Neo4j Helm chart for standalone server deployments

In the standalone server setup, the user is responsible for defining a single YAML file, containing all the configurations for the Neo4j standalone server, and for running the `helm install my-neo4j-release neo4j/neo4j -f values.yaml` command to deploy the Neo4j DBMS.

.Example of a _values.yaml_ file
[source, yaml]
----
neo4j:
  edition: community
  name: my-neo4j
volumes:
  data:
    mode: "defaultStorageClass"
----


.Example of a Helm install command for deploying a standalone server
[source,shell]
--
helm install my-neo4j neo4j/neo4j -f values.yaml
--

Then, the Neo4j Helm chart creates Kubernetes entities needed for running and accessing Neo4j.

The following diagram is a schematic representation of the Helm chart involved and the Kubernetes and Cloud resources it instantiates when installed:

.Neo4j standalone setup
image::standalone-on-k8s.svg[Example of Neo4j standalone setup in Kubernetes,width=700,role=popup]