[[si-uninstall-cleanup]]
= Uninstall Neo4j and clean up the created resources

[[uninstall-neo4j]]
== Uninstall Neo4j Helm deployment

[source, shell]
----
helm uninstall my-neo4j-release
----

.Example output
[source, role=noheader]
----
release "my-neo4j-release" uninstalled
----

[[si-cleanup-resources]]
== Fully remove all the data and resources

Uninstalling the Helm release does not remove the created resources and data.
Therefore, after uninstalling the helm deployment, you also have to delete all the data and resources.

. Delete all persistent volume claims in the neo4j namespace:
+
[source, shell]
----
kubectl delete pvc --all --namespace neo4j
----
. Delete the entire Kubernetes cluster in your cloud provider:
+
[.tabbed-example]
=====
[.include-with-gke]
======
[source, shell]
----
gcloud container clusters delete my-neo4j-gke-cluster
----
======

[.include-with-aws]
======
[source, shell]
----
eksctl delete cluster --name=my-neo4j-eks-cluster
----
======

[.include-with-azure]
======
[source, shell]
----
az aks delete --name my-neo4j-aks-cluster --resource-group <MyResourceGroup>
----
======

[.include-with-digitalocean]

======

[.include-with-docker-desktop]
======

. Check the name of the `PersistentVolumeClaim` (`pvc`):
+
[source, shell]
----
kubectl get pvc
----
+
[source, role=noheader]
----
NAME                      STATUS   VOLUME                CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-my-neo4j-release-0   Bound    my-neo4j-release-pv   1Ti        RWO            manual         43h
----
+
[NOTE]
====
If you re-create Neo4j with the same settings, it will pick up the PVC again, and all the data is still on it.
If you use manually provisioned volumes and delete the `PersistentVolumeClaim` and the `PersistentVolume` in Kubernetes, the `hostPath` directory with the Neo4j data will still exist.

When you use dynamically provisioned volumes and delete the `PersistentVolume`, the underlying data may or may not be removed, depending on the Docker Desktop version and configuration.
====
+
. To fully remove all the data and resources, delete the `PersistentVolumeClaim` in Kubernetes.
The dynamically provisioned volumes are automatically removed when the `PersistentVolumeClaim` is deleted.
======

=====
