[[si-verify-installation]]
= Verify the installation

[.tabbed-example]
=====
[.include-with-cloud-environments]
======
. Check that the `statefulset` is OK.
+
[source, shell]
----
kubectl get statefulsets
----
+
[source, role=noheader]
----
NAME               READY   AGE
my-neo4j-release   1/1     2m11s
----
+
. Check that the pod is `Running`:
+
[source, shell]
----
kubectl get pods
----
+
[source, role=noheader]
----
NAME                 READY   STATUS    RESTARTS   AGE
my-neo4j-release-0   1/1     Running   0          16m
----
+
. Check that the pod logs look OK:
+
[source, shell]
----
kubectl exec my-neo4j-release-0 -- tail -n50 /logs/neo4j.log
----
+
[source, role=noheader, subs="attributes"]
----
2021-07-28 12:45:50.267+0000 INFO  Command expansion is explicitly enabled for configuration
2021-07-28 12:45:50.280+0000 INFO  Starting...
2021-07-28 12:45:55.680+0000 INFO  ======== Neo4j {neo4j-version-exact} ========
2021-07-28 12:46:00.006+0000 INFO  Bolt enabled on [0:0:0:0:0:0:0:0%0]:7687.
2021-07-28 12:46:02.476+0000 INFO  Remote interface available at _\http://localhost:7474_/
2021-07-28 12:46:02.478+0000 INFO  Started.
----
+
. Check that the services look OK:
+
[source, shell]
----
kubectl get services
----
+
[source, role=noheader]
----
NAME                     TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)                                        AGE
kubernetes               ClusterIP      10.112.0.1      <none>         443/TCP                                        28h
my-neo4j-release         ClusterIP      10.112.10.159   <none>         7687/TCP,7474/TCP                     41m
my-neo4j-release-admin   ClusterIP      10.112.4.73     <none>         6362/TCP,7687/TCP,7474/TCP          41m
my-neo4j-release-neo4j   LoadBalancer   10.112.6.75     34.140.48.23   7474:31420/TCP,7687:31650/TCP   41m
----
+
. In a web browser, open the Neo4j Browser at _\http://<EXTERNAL-IP>:7474/browser_.
. Use the automatically-generated password (as printed in the output of the `helm install` command) or the one you have configured in the _my-neo4j.values.yaml_ file.
======

[.include-with-docker-desktop]
======
. Check that `statefulset` is OK.
+
[source, shell]
----
kubectl get statefulsets
----
+
[source, role=noheader]
----
NAME               READY   AGE
my-neo4j-release   1/1     5m11s
----
+
. Check that the PVC is OK (the `STATUS` must be `Bound`):
+
[source, shell]
----
kubectl get pvc
----
+
[source, role=noheader]
----
NAME                       STATUS   VOLUME                CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-my-neo4j-release -0   Bound    my-neo4j-release -pv   10Gi      RWO            manual         8m36s
----
+
. Check that the pod is `READY`:
+
[source, shell]
----
kubectl get pods
----
+
[source, role=noheader]
----
NAME                  READY   STATUS       RESTARTS   AGE
my-neo4j-release-0   1/1     Running      0          5m53s
----
+
. Check that the pod logs look OK:
+
[source, shell]
----
kubectl exec my-neo4j-release-0 -- tail -n50 /logs/neo4j.log
----
+
[source, subs="attributes", role=noheader]
----
Changed password for user 'neo4j'.
Directories in use:
  home:         /var/lib/neo4j
  config:       /config/
  logs:         /data/logs
  plugins:      /var/lib/neo4j/plugins
  import:       /var/lib/neo4j/import
  data:         /var/lib/neo4j/data
  certificates: /var/lib/neo4j/certificates
  run:          /var/lib/neo4j/run
Starting Neo4j.
2021-06-02 17:38:27.791+0000 INFO  Command expansion is explicitly enabled for configuration
2021-06-02 17:38:27.819+0000 INFO  Starting...
2021-06-02 17:38:31.195+0000 INFO  ======== Neo4j {neo4j-version-exact} ========
2021-06-02 17:38:34.168+0000 INFO  Initializing system graph model for component 'security-users' with version -1 and status UNINITIALIZED
2021-06-02 17:38:34.188+0000 INFO  Setting up initial user from `auth.ini` file: neo4j
2021-06-02 17:38:34.190+0000 INFO  Creating new user 'neo4j' (passwordChangeRequired=false, suspended=false)
2021-06-02 17:38:34.205+0000 INFO  Setting version for 'security-users' to 2
2021-06-02 17:38:34.214+0000 INFO  After initialization of system graph model component 'security-users' have version 2 and status CURRENT
2021-06-02 17:38:34.223+0000 INFO  Performing postInitialization step for component 'security-users' with version 2 and status CURRENT
2021-06-02 17:38:34.561+0000 INFO  Bolt enabled on 0.0.0.0:7687.
2021-06-02 17:38:36.910+0000 INFO  Remote interface available at _\http://localhost:7474_/
2021-06-02 17:38:36.912+0000 INFO  Started.
----
+
. Check that the services look OK:
+
[source, shell]
----
kubectl get services
----
+
[source, role=noheader]
----
NAME                     TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                                        AGE
kubernetes               ClusterIP      10.96.0.1        <none>        443/TCP                                        3d1h
my-neo4j-release         ClusterIP      10.103.103.142   <none>        7687/TCP,7474/TCP                    2d8h
my-neo4j-release-admin   ClusterIP      10.99.11.122     <none>        6362/TCP,7687/TCP,7474/TCP            2d8h
my-neo4j-release-neo4j   LoadBalancer   10.110.138.165   localhost     7474:31237/TCP,7687:32169/TCP   2d3h
----
+
. Use xref:kubernetes/accessing-neo4j.adoc#ad-hoc-access[port forwarding] to get access to the browser:
+
[source, shell]
----
kubectl port-forward svc/my-neo4j-release tcp-bolt tcp-http tcp-https
----
+
. In a web browser, open the Neo4j Browser at _\http://localhost:7474_.
. Use the automatically-generated password (as printed in the output of the `helm install` command) or the one you have set up with the `helm install` command.

======
=====
