:page-role: new-2025.12 enterprise-edition not-on-aura
:description: This page describes the system requirements and configuration settings for sharded property databases.
= System requirements and configuration

== System requirements

The sharded property database requires the same xref:installation/requirements.adoc[system requirements] as Neo4j 2025.10 and later versions.

== Configuration settings

To enable the property sharding in your cluster, you must also ensure that the default Cypher version is set to Cypher 25 by adding `db.query.default_language=CYPHER_25` parameter to the `neo4j.conf` file on each server or by prefixing your Cypher queries with `CYPHER_25`.

[NOTE]
====
Starting with Neo4j 2026.02,  the setting `db.query.default_language` is set to `CYPHER_25` in the _neo4j.conf_ file, which means all newly created databases will get Cypher 25 version.
If you are using an older version of Neo4j, you need to explicitly set the default Cypher version to Cypher 25 when creating the database or by prefixing your Cypher queries with `CYPHER_25` to be able to use the sharding features.
For details on configuring the Cypher version, see xref:configuration/cypher-version-configuration.adoc[Configure the Cypher default version] and link:https://neo4j.com/docs/cypher-manual/current/queries/select-version/[Cypher Manual -> Select Cypher version].
====