:description: This page describes how to create a sharded property database using the `CREATE DATABASE` command.
:page-role: new-2025.10 enterprise-edition not-on-aura
:keywords: sharded property database, CREATE DATABASE, Cypher 25
= `CREATE DATABASE` command with sharded databases

You can create a sharded database using the Cypher command `CREATE DATABASE` (requires Cypher 25, introduced alongside Neo4j 2025.06.0).
For details on configuring the Cypher version, see xref:configuration/cypher-version-configuration.adoc[Configure the Cypher default version].


== Syntax

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax

| CREATE DATABASE
|
[source, syntax, role="noheader"]
----
CREATE DATABASE name [IF NOT EXISTS]
[[SET] GRAPH SHARD {
  [TOPOLOGY n PRIMAR{Y\|IES} [m SECONDAR{Y\|IES}]]
}]
[SET] PROPER{TY\|IES} {
  COUNT n [TOPOLOGY m REPLICA[S]]
}
[OPTIONS "{" option: value[, ...] "}"]
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----
|===

When creating a sharded database, the following are created:

* A virtual sharded database `<name>`.
* A single graph shard with the name `<name>-g000`.
* A number of property shards with the name `<name>-p000<index>`.
The count property in `SET PROPERTY SHARDS` specifies the number of property shards.

[NOTE]
====
`CREATE OR REPLACE` does not replace an existing sharded database.
====

== Options

The `CREATE DATABASE` command can have a map of options, e.g., `OPTIONS {key: 'value'}`.
For sharded databases, only the seeding option is supported.

The following table describes the `seedUri` option:

[frame="topbot", grid="cols", cols="<1s,<4"]
|===
| *Key*
m| seedURI
| *Value*
a| URI to a folder containing all the backups or a list of dumps/backups.

[NOTE]
The folder notation only works for backups, not dumps.

When specifying each artifact manually the key of the map is the name of the shard.
Where shard name = `databaseName-g000` or `databaseName-p000` for property shards where the last shard name would be `databaseName-px` where `x = numShards -1`.
| *Description*
a| Defines an identical seed from an external source, which will be used to seed all servers. For more information, see xref::database-administration/standard-databases/seed-from-uri.adoc[Seed from a URI].
| *Example*
|
[source, syntax, role="noheader"]
----
seedUri: {
  `foo-sharded-g000`: "s3://bucket/folder/foo-g000.backup",
  `foo-sharded-p000`: "s3://bucket/folder/foo-p001.backup",
  `foo-sharded-p001`: "s3://bucket/folder/foo-p002.backup"
 }
----
Or
[source, syntax, role="noheader"]
----
seedUri: "s3://bucket/folder/"
----
|===

== Default numbers for topology

The sharded property databases use the Neo4j cluster topology.
Therefore, you need to consider how the following settings will affect the creation of your sharded property database.

[options="header", width="100%", cols="4m,1m,1m,3a"]
|===
| Configuration settings with their default value
| Default value
| Valid values
| Description

|initial.dbms.default_primaries_count
| 1
| [1-10]
| The default number of primaries for the graph shard when the database is created.

|initial.dbms.default_secondaries_count
| 0
| [0-19]
| The default number of secondaries for the graph shard when the database is created.
|===