:page-role: new-2025.12 infinigraph not-on-aura
:description: Methods for ingesting or importing data into a sharded property database.
:keywords: sharded property database, data ingestion, import, neo4j-admin, LOAD CSV, CREATE DATABASE
= Data import

There are several ways to import data into a sharded property database, depending on your use case and the size of your dataset.

* Initial import from delimited files into a sharded property database using `neo4j-admin database import full`.
* Loading data incrementally into an existing sharded property database using `neo4j-admin database import incremental`.
* Importing data using `LOAD CSV` for small to medium-sized datasets.

For creating a sharded property database from an existing database or backup, see xref:scalability/sharded-property-databases/creating-sharded-databases.adoc#creating-sharded-db-from-uri[Creating a sharded database from a URI (online)] and xref:scalability/sharded-property-databases/resharding-databases.adoc[Resharding databases].

== Initial import from delimited files (offline)

You can use the xref:import.adoc#import-tool-full[`neo4j-admin database import full`] command to import data from delimited files into a sharded property database as in a standard Neo4j database.
This is particularly useful for large datasets that you want to import in bulk before starting your application or for incremental imports later on.
You can specify the `--property-shard-count` option to define the number of property shards you want to create.
This will help distribute the data across multiple servers in a Neo4j cluster.

[NOTE]
====
If you are creating the property shards on a self-managed server, the server that executes the `neo4j-admin database import` command must have sufficient storage space available for all of the property shards that will be created.
====

=== Import using S3 (offline)

The following example shows how to import a set of CSV files, back them up to S3 using the `--target-location` and `--target-format` options, and then create a database using those seeds in S3.
Optionally, you can use the `--compress` option label:new[Introduced in 2026.04] to produce compressed backup artifacts.
See xref:import.adoc#import-tool-full[Import -> Full import] for more information.

. Using the `neo4j-admin database import` command, import data into the `foo-sharded` database, creating one graph shard and three property shards.
If the `neo4j-admin` process is running on the same server as a Neo4j DBMS process, the Neo4j DBMS process must be stopped.
The `--target-location` and `--target-format` options take the outputs of the import, turn them into uncompressed backups, and upload them to a location ready to be seeded from.
+
[source, shell]
----
neo4j-admin database import full foo-sharded --nodes=nodes.csv --nodes=movies.csv --relationships=relationships.csv --input-type=csv --property-shard-count=3 --schema=schema.cypher --target-location=s3://bucket/folder/ --target-format=backup
----

. Create the database `foo-sharded` as a sharded property database by seeding it from your backups in the AWS S3 bucket:
+
[source, cypher]
----
CREATE DATABASE `foo-sharded`
DEFAULT LANGUAGE CYPHER 25
PROPERTY SHARDS { COUNT 3 }
OPTIONS {
 seedUri: `s3://bucket/folder/`
};
----

=== Import using local file system (offline)
You can import data into a Neo4j cluster that has no access to any cloud.

. Using the `neo4j-admin database import` command, import data into the `foo-sharded` database, creating one graph shard and three property shards.
If the `neo4j-admin` process is running on the same server as a Neo4j DBMS process, the Neo4j DBMS process must be stopped.
Optionally, you can use the `--compress` option label:new[Introduced in 2026.04] to produce compressed backup artifacts.
See xref:import.adoc#import-tool-full[Import -> Full import] for more information.
+
[source, shell]
----
neo4j-admin database import full foo-sharded --nodes=nodes.csv --nodes=movies.csv --relationships=relationships.csv --input-type=csv --property-shard-count=3 --schema=schema.cypher --target-format=backup
----

. Using allow and deny database allocate a single shard to each server in the cluster.
See xref:clustering/databases.adoc#cluster-allow-deny-db[Controlling locations with allowed/denied databases]
. Move the produced backups from the local file system of the machine used for the import to the servers hosting each of the shards.
Each server should have one backup, and the backups must reside in the same path on each server.
. On each server, update the _neo4j.conf_ to include the correct settings for file seeding as outlined in xref:database-administration/standard-databases/seed-from-uri.adoc[Create a database from a URI].
. Create the database `foo-sharded` as a sharded property database by seeding it from your backups in the servers file systems:
+
[source, cypher]
----
CREATE DATABASE `foo-sharded`
DEFAULT LANGUAGE CYPHER 25
PROPERTY SHARDS { COUNT 3 }
OPTIONS {
 seedUri: `file:/backusp/`, seedOptions: 'NO_CHECK'
};
----

In this context, `NO_CHECK` prevents the seeding process from verifying that all backups are present on all servers.

The cluster automatically distributes the data across its servers.
For more information on seed providers, see xref:database-administration/standard-databases/seed-from-uri.adoc[Create a database from a URI].

== Incremental import / offline updates

You can use the `neo4j-admin database import incremental` command to import data into an existing database.
This is particularly useful for large batches of data that you want to add to an existing sharded property database.
It allows you to do faster updates than is possible transactionally.

. Stop the `foo-sharded` database if it is running.
See xref:scalability/sharded-property-databases/starting-stopping-sharded-databases.adoc[Starting and stopping a sharded property database] for instructions.

. Run the `neo4j-admin database import incremental` command by specifying the `--property-shard-count` option to define the number of property shards you want to create, the `--target-location` and `--target-format` options to upload the resulting stores to a location ready for re-creating the databases from, and the CSV files that you wish to update your existing data with.
Optionally, you can use the `--compress` option label:new[Introduced in 2026.04] to produce compressed backup artifacts.
See xref:import.adoc#import-tool-incremental[Incremental import] for more information and instructions.
+
[source, shell]
----
neo4j-admin database import incremental foo-sharded --nodes=nodes.csv --nodes=movies.csv --relationships=relationships.csv --input-type=csv --property-shard-count=3 --schema=schema.cypher --target-location=s3://bucket/folder/ --target-format=backup
----

. Re-create your database using the `dbms.recreateDatabase()` or follow step 2 of xref:scalability/sharded-property-databases/resharding-databases.adoc#splitting-existing-db-into-shards[Splitting an existing database into shards] and creating a new database with the resulting stores the same way you would for a normal offline incremental import.


== Importing data using `LOAD CSV` (online)

You can use `LOAD CSV` to import data into a sharded property database.
This is especially useful when you want to import small to medium-sized datasets (up to 10 million records) from local and remote files, including cloud URIs.
For more information, see link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/load-csv/[Cypher Manual -> `LOAD CSV`] and link:https://neo4j.com/docs/getting-started/cypher-intro/load-csv/[Getting Started guide -> Tutorial: Import CSV data using `LOAD CSV`].

[NOTE]
====
Transactional Cypher statements involving `MERGE` or `RELATIONSHIP` creation have not yet been optimized. Using `LOAD CSV` will not be performant for anything larger than 100K records.
====
