:page-role: new-2025.12 enterprise-edition not-on-aura
:description: Listing sharded property databases
= Listing sharded property databases

Sharded databases are listed as standard databases in the `type column` when you execute `SHOW DATABASES`.

* The status is either:
** Equal to the status shared by all shards.
** “Mixed”, if some shards have a different status.
The `statusMessage` indicates the number of shards with different statuses, e.g., online (4) and starting (1).
//To add an example table with a mixed status. Conor will provide an example output with mixed status.
* The associated graph shard is listed as `graph shard` in the `type column`.
* The associated property shards are listed as `property shard` in the `type column`.
* The `shardTxnLag` column displays the number of transactions the current shard is behind compared to the most up-to-date shard allocation of the sharded database.
The lag is expressed in negative integers, whereas the column `replicationLag` shows the number of transactions the current database is behind compared to the most up-to-date allocation of that database.

.Command output
[result]
----
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| name       | type             | aliases | access       | address          | role                     | writer | requestedStatus | statusMessage | default | home  | constituents | shardTxnLag |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "spd"      | "standard"       | []      | "read-write" | "localhost:7687" | "primary"                | TRUE   | "online"        | ""            | FALSE   | FALSE | []           | NULL        |
| "spd-g000" | "graph shard"    | []      | "read-write" | "localhost:7687" | "primary"                | TRUE   | "online"        | ""            | FALSE   | FALSE | []           | 0           |
| "spd-p000" | "property shard" | []      | "read-write" | "localhost:7687" | "property shard replica" | FALSE  | "online"        | ""            | FALSE   | FALSE | []           | 0           |
| "spd-p001" | "property shard" | []      | "read-write" | "localhost:7687" | "property shard replica" | FALSE  | "online"        | ""            | FALSE   | FALSE | []           | 0           |
| "spd-p002" | "property shard" | []      | "read-write" | "localhost:7687" | "property shard replica" | FALSE  | "online"        | ""            | FALSE   | FALSE | []           | 0           |
| "system"   | "system"         | []      | "read-write" | "localhost:7687" | "primary"                | TRUE   | "online"        | ""            | FALSE   | FALSE | []           | NULL        |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
----

[NOTE]
====
Some columns are empty for the virtual sharded database (with the name passed into the create command) and can be found on the rows of the associated graph shard instead, e.g., `lastCommittedTxn` or `replicationLag`.
These rows are only visible if the user has either `CREATE/DROP/ALTER DATABASE`,  `SET DATABASE ACCESS`, or `DATABASE MANAGEMENT` privileges.
These rows can be distinguished by the type, which has values `graph shard` and `property shard`, respectively.
====

