:description: How to recreate your sharded property database in Neo4j.
:page-role: new-2026.08 enterprise-edition not-on-aura

= Recreating sharded property databases

You can use the xref:procedures/built-in-procedures.adoc#procedure_dbms_recreateDatabase[`dbms.recreateDatabase()`] procedure to recreate a sharded property database in Neo4j.

It allows you to:

* Change the database store to a specified backup, while keeping all the associated privileges for the database.

* Make your database write-available again after it has been lost (for example, due to a disaster).
See xref:clustering/multi-region-deployment/disaster-recovery.adoc[Disaster recovery] for more information.

* Delete the data and schema for a database, while keeping the database privileges assigned to each role.

[IMPORTANT]
====
* The recreate procedure *must* target the virtual sharded property database.
* Altering the store format of a sharded property database is not supported.
====

[CAUTION]
====
Remember that the recreate procedure results in downtime while the stores get updated.
The time is unbounded and may depend on different factors -- for example, the size of the store, network speed, etc.
====

For general usage, prerequisites, and seeding options, see xref:database-administration/standard-databases/recreate-database.adoc[Recreate a database].

This page describes options and considerations specific to sharded property databases.

== Syntax and options

The syntax of the `dbms.recreateDatabase()` procedure is the same as the syntax of the `dbms.recreateDatabase()` procedure for standard databases, with some additional options for sharded property databases.

It takes two arguments: the database name and a map of options.

.General syntax
[source, shell]
----
dbms.recreateDatabase(database :: STRING, options = {} :: MAP)
----

.Sharded property database topology options
[cols="2a,4",frame="topbot",options="header"]
|===
|Option
|Description

|seedingServers
|A list of possible seeding servers.
You can define available servers or provide an empty list.
For details, see xref:database-administration/standard-databases/recreate-database.adoc#seed-servers[Use available servers as a seed].

|seedURI
|External source specified by URI.

|clearData
|Allows you to delete the data and schema for a database, while keeping the database privileges assigned to each role.

|graphShardPrimaries
|Number of primary allocations for the recreated sharded property database.
If you set number of primaries without secondaries, then secondaries is set to `0`.

|graphShardSecondaries
|Number of secondary allocations for the recreated sharded property database.
You cannot set secondaries without primaries.

|propertyShardReplicas
|Number of copies for each property shard in the recreated sharded property database.

|===

[NOTE]
====
When using `seedURI`, the URI must point to a folder containing valid backup artifacts for all shards -- the graph shard and all property shards.
The backup artifacts are produced using `neo4j-admin database backup` or `neo4j-admin database copy --target-format=backup`.
For details on backing up a sharded property database, see xref:scalability/sharded-property-databases/admin-operations.adoc#backup-and-restore[Admin operations -> Backup and restore].

The `seedURI` option also supports:

* A map of shard names to URIs, for example, `{seedURI: {"foo-g000": "s3://bucket/foo-g000.backup", "foo-p000": "s3://bucket/foo-p000.backup"}}`.
* A list of server URIs, for example, `{seedURI: ["server://server0/seeds/", "server://server1/seeds/"]}`.
See xref:database-administration/standard-databases/seed-from-uri.adoc#server-seed-provider[`ServerSeedProvider`] for details.
====

== Examples



=== Recreate from available servers

To recreate the database and let Neo4j automatically select the most up-to-date available shard stores, provide an empty `seedingServers` list.
Before running this command, cordon any unavailable servers.
For details, see xref:database-administration/standard-databases/recreate-database.adoc#undefined-servers[Use available servers as a seed -> Undefined servers].

[source, cypher]
----
CALL dbms.recreateDatabase("foo", {seedingServers: []});
----

=== Recreate from a backup URI

To replace all shard stores from a backup, use the `seedURI` option pointing to a folder containing valid backup artifacts for all shards.

[source, cypher]
----
CALL dbms.recreateDatabase("foo", {seedURI: "s3://my-bucket/backups/foo/"});
----

=== Recreate with a changed topology

During disaster recovery, fewer servers may be available than the original topology requires.
You can change the topology of the recreated database by combining seeding options with the topology options above.
For details, see xref:database-administration/standard-databases/recreate-database.adoc#alter-topology-recreate[Change the topology].

[NOTE]
====
Keep in mind that the number of property shards cannot be changed using the recreate procedure.
See xref:scalability/sharded-property-databases/resharding-databases.adoc[Resharding and consolidating databases] for details on how to reshard a sharded property database.
====

[source, cypher]
----
CALL dbms.recreateDatabase("foo", {seedingServers: [], graphShardPrimaries: 2, graphShardSecondaries: 1, propertyShardReplicas: 3});
----

=== Clear data and schema

To delete the data (e.g., nodes and relationships) and the schema (e.g., constraints and indexes) while keeping database privileges, use the `clearData` option.
For details, see xref:database-administration/standard-databases/recreate-database.adoc#clear-data-recreate[Clear data option].

[source, cypher]
----
CALL dbms.recreateDatabase("foo", {clearData: true});
----

[NOTE]
====
Using the clear data option means the data and schema will be deleted *permanently*.
If you want to have the option of getting them back later, make sure to take a backup before clearing the database.
See xref:scalability/sharded-property-databases/admin-operations.adoc#backup-and-restore[Admin operations -> Backup and restore] for details.
====