[[neo4j-admin-dump-load]]
= Dump and load databases
:description: This section describes the dump and load commands of Neo4j Admin. 

A Neo4j database can be dumped and loaded using the following commands:

`neo4j-admin dump --database=<database> --to=<destination-path>`

`neo4j-admin load --from=<archive-path> --database=<database> [--force]`


*Limitations*

* The database should be shutdown before running the `dump` and `load` commands.
* `neo4j-admin` must be invoked as the `neo4j` user in order to ensure the appropriate file permissions.

*Examples of usage*

* Moving databases from one environment to another.
+
Using the `dump` and `load` commands is the recommended, and safe, way of transferring databases between environments.
They understand which files need to be exported and imported and which should not.
+
By contrast, file system copy-and-paste of databases is not supported.

* Offline backups.
+
For a discussion of online versus offline backups, see xref:backup/planning.adoc#backup-planning-online-vs-offline[Online and offline backups].

*Examples*

.Use the `dump` command of neo4j-admin
====

Dump the database called `graph.db` into a file called `/backups/graph.db/2016-10-02.dump`.
The destination directory for the dump file -- in this case _/backups/graph.db_ -- must exist before calling the command.

----
$neo4j-home> bin/neo4j-admin dump --database=graph.db --to=/backups/graph.db/2016-10-02.dump

$neo4j-home> ls /backups/graph.db

$neo4j-home> 2016-10-02.dump
----
====

.Use the `load` command of neo4j-admin
====

Load the backed-up database contained in the file `/backups/graph.db/2016-10-02.dump` into database `graph.db`.
Since we have a database running, we first have to shut it down.
When we use the `--force` option, any existing database gets overwritten.

----
$neo4j-home> bin/neo4j stop

Stopping Neo4j.. stopped

$neo4j-home> bin/neo4j-admin load --from=/backups/graph.db/2016-10-02.dump --database=graph.db --force
----

====

[NOTE]
====
If using the `load` command to seed a Causal Cluster, you must first perform `xref:tools/unbind.adoc[neo4j-admin unbind]` on each of the cluster instances.
The procedure is described in xref:clustering/seed-cluster.adoc#causal-clustering-seeding-from-dump[Seed from an offline backup].
====


[IMPORTANT]
====
Version 4.0::
The content on this page is available at: link:https://neo4j.com/docs/operations-manual/4.0/backup-restore/offline-backup/[].
====
