[[neo4j-admin]]
= Neo4j Admin
:description: This section describes the Neo4j Admin tool. 

This section describes the following:

* xref:tools/neo4j-admin.adoc#neo4j-admin-introduction[Introduction]
* xref:tools/neo4j-admin.adoc#neo4j-admin-syntax-and-commands[Syntax and commands]
* xref:tools/neo4j-admin.adoc#neo4j-admin-environment-variables[Environment variables]
* xref:tools/neo4j-admin.adoc#neo4j-admin-exit-codes[Exit codes]


[[neo4j-admin-introduction]]
== Introduction

Neo4j Admin is the primary tool for managing a Neo4j DBMS.
It is a command-line tool that is installed as part of the product and can be executed with a number of commands.
Some of the commands are described in more detail in separate sections.

[NOTE]
====
The Neo4j Admin commands must be invoked with the same user as Neo4j runs as. 
This guarantees that Neo4j will have full rights to start and work with the database files you use.
====

[[neo4j-admin-syntax-and-commands]]
== Syntax and commands

*Syntax*

Neo4j Admin is located in the xref:configuration/file-locations.adoc[_bin_] directory and is invoked as:

`neo4j-admin <command>`

*Commands*

[options="header", cols="25,25a,50a"]
|===
| Functionality area
| Command
| Description

.7+| General
| `help <command>`
| Display help text for `<command>`
| `check-consistency`
| Check the consistency of a database.

For details, see xref:tools/consistency-checker.adoc[Consistency checker].
| `report`
| Collect the most common information needed for remote assessments.

For details, see xref:tools/neo4j-admin-report.adoc[Report tool].
| `store-info`
| Print information about a Neo4j database store.

For details, see xref:tools/store-info.adoc[Display store information].
| `memrec`
| Print Neo4j heap and pagecache memory settings recommendations.

For details, see xref:tools/neo4j-admin-memrec.adoc[Memory recommendations].
| `import`
| Import from a collection of CSV files or a pre-3.0 database.

For details, see xref:tools/import/index.adoc[Import].
| `push-to-cloud`
| Dumps a local database, and imports into a specified Neo4j AuraDB instance.

For details, see xref:tools/push-to-cloud.adoc[Push to Neo4j AuraDB].

.2+| Authentication
| `set-default-admin`
| Sets the default admin user when no roles are present.
| `set-initial-password`
| Sets the initial password of the initial admin user (`neo4j`).

.2+| Offline backup

For details see xref:tools/dump-load.adoc[Dump and load databases].
| `dump`
| Dump a database into a single-file archive.
| `load`
| Load a database from an archive created with the dump command.

.2+| Online backup

For details see xref:backup/index.adoc[Backup].
| `backup`
| Perform an online backup from a running Neo4j server.
| `restore`
| Restore a backed-up database.

| Clustering
| `unbind`
| Removes cluster state data for the specified database.

For details, see xref:tools/unbind.adoc[Unbind a Core Server].
|===

[[neo4j-admin-environment-variables]]
== Environment variables

Neo4j Admin can utilize the following environment variables:

[horizontal]
NEO4J_DEBUG:: Set to anything to enable debug output.
NEO4J_HOME::  Neo4j home directory.
NEO4J_CONF::  Path to directory which contains _neo4j.conf_.
HEAP_SIZE::   Set JVM maximum heap size during command execution.
              Takes a number and a unit, for example 512m.
JAVA_OPTS::   Additional JVM arguments.


[[neo4j-admin-exit-codes]]
== Exit codes

When `neo4j-admin` finishes as expected, it returns an exit code of `0`.
A non-zero exit code means something undesired happened during command execution.
The non-zero exit code can contain further information about the error, such as the `backup` command's xref:backup/performing.adoc#backup-performing-exit-codes[exit codes].
