[[neo4j-admin-report]]
= Neo4j Admin report
:description: This chapter describes the `report` command of Neo4j Admin. 

Use the `report` command of `neo4j-admin` to gather information about a Neo4j installation and save it to an archive.

`neo4j-admin report [--force] [--list] [--verbose] [--pid=<pid>] [--to=<path>] [<classifier>...]`

The intended usage of the report tool is to simplify the support process by collecting the relevant information in a standard way.
This tool does not send any information automatically.
To share this information with the Neo4j Support organization, you will have to send it manually.

*Options*

[options="header"]
|===
| Option    | Default  | Description
| --to      | reports/ | Specifies to target directory where the report should be written to.
| --list    |          | Will list available classifiers.
| --verbose |          | Will instruct the tool to print more verbose output.
| --force   |          | Will disable the available disk space check.
| --pid     |          | Specify process id of running Neo4j instance. Only applicable when used together with classifiers indicated as _Online_ in the table below.
|===

By default, the tool tries to estimate the final size of the report and use that to assert that there is enough disk space available for it.
If there is not enough available space the tool will abort. 
However, this estimation is pessimistic and does not take the compression into consideration, so if you are confident that you do have enough disk space, you can disable this check with the option `--force`.

*Classifiers*

[cols="<,^,<", options="header"]
|===
| Classifier   | Online | Description
|  `all`       |        |  Include all of the available classifiers listed below.
|  `ccstate`   |        |  Include the current cluster state.
|  `config`    |        |  Include the `neo4j.conf` file.
|  `heap`      |  X     |  Include a heap dump.
|  `logs`      |        |  Include log files, e.g `debug.log`, `neo4j.log` etc.
|  `metrics`   |        |  Include the collected metrics.
|  `plugins`   |        |  Include a text view of the plugin directory (no files are collected).
|  `ps`        |        |  include a list of running processes.
|  `raft`      |        |  Include the raft log.
|  `sysprop`   |  X     |  Include a list of Java system properties.
|  `threads`   |  X     |  Include a thread dump of the running instance.
|  `tree`      |        |  Include a text view of the folder structure of the data directory (no files are collected).
|  `tx`        |        |  Include transaction logs.
|===

The classifiers indicated as _Online_ only work when you have a running Neo4j instance that the tool can find.

If no classifiers are specified, the following classifiers will be used: `logs`, `config`, `plugins`, `tree`, `metrics`, `threads`, `sysprop` and `ps`.

The report tool does not read any data from your database.
However, the heap, the raft logs, and the transaction logs may contain data.
Additionally while the standard `neo4j.conf` file does not contain password information, for certain configurations it may have this type of information.
Therefore, be aware of your organization's data security rules before using the classifiers `heap`, `tx`, `raft` and `config`. 

[NOTE]
====
This tool uses the https://docs.oracle.com/javase/8/docs/technotes/guides/attach/index.html[Java Attach API] to gather data from a running Neo4j instance.
Therefore, it requires the Java JDK in order to execute properly.
====

