[[neo4j-admin-memrec]]
= Memory recommendations
:description: This chapter describes the `memrec` command of Neo4j Admin. 

Use the `memrec` command of `neo4j-admin` to get an initial recommendation on how to configure memory parameters for Neo4j:

`neo4j-admin memrec [--memory=<memory dedicated to Neo4j>] [--database=<name>]`

The recommendations will be given in a format such that it can be copied and pasted straight into xref:configuration/file-locations.adoc[_neo4j.conf_].

*Options*

[options="header"]
|===
| Option                    | Default                            | Description
|  --memory                 | The memory capacity of the machine | The amount of memory to allocate to Neo4j. Valid units are: `k`, `K`, `m`, `M`, `g`, `G`.
|  --database               | graph.db                           | The name of the database.
                                                                   This option will generate numbers for Lucene indexes, and for data volume and native indexes in the database.
                                                                   These can be used as an input into more detailed memory analysis.
|===

*Considerations*

The `neo4j-admin memrec` command calculates a valid starting point for Neo4j memory settings, based on the provided memory.
The specific conditions for your use case may warrant adjustment of these values.
See xref:performance/memory-configuration.adoc[Memory configuration] for a description of the memory settings in Neo4j.


.Use the `memrec` command of `neo4j-admin`
====
The following example illustrates how `neo4j-admin memrec` provides a recommendation on how to use 16g of memory:

[source, shell]
----
$neo4j-home> bin/neo4j-admin memrec --memory=16g

...
...
...
# Based on the above, the following memory settings are recommended:
dbms.memory.heap.initial_size=5g
dbms.memory.heap.max_size=5g
dbms.memory.pagecache.size=7g
----
====
