[[neo4j-admin-store-info]]
= Display store information
:description: This chapter describes the `store-info` command of Neo4j Admin. 

The `store-info` command outputs the version of a database store format.
It provides information about the xref:reference/configuration-settings.adoc#config_dbms.record_format[record format] of the database store (`standard` or `high_limit`), the store format xref:tools/store-info.adoc#neo4j-admin-store-format-versions[version], when the version was introduced, and whether it needs to be migrated to a newer version.


[[neo4j-admin-store-info-syntax]]
== Syntax and examples

The `neo4j-admin store-info` command is located in the xref:configuration/file-locations.adoc[_bin_] directory.
It is invoked against an *offline* database or a backup as follows:

`neo4j-admin store-info --store=<path-to-store>`

.Invoke `neo4j-admin store-info` against a database
====
[source, shell]
----
$neo4j-home> /bin/neo4j-admin store-info --store=data/databases/graph.db
Store format version:         v0.A.9
Store format introduced in:   3.4.0
----
====

[role=enterprise-edition]
.Invoke `neo4j-admin store-info` against a database backup
====
You can run the `store-info` command to see if the store format of the backup that you want to restore, is compatible with your running Neo4j instance.
For example, if you want to restore the database backup _/tmp/3518/mygraph.db_ into a 4.x Neo4j instance:

[source, shell]
----
$neo4j-home> bin/neo4j-admin store-info /tmp/3518/mygraph.db
Store format version:         vE.H.4 \ #<1>
Store format introduced in:   3.4.0 \ #<2>
Store format superseded in:   4.0.0 \ #<3>
----

<1> The store format version reveals that the database is configured to use the `high-limit` xref:reference/configuration-settings.adoc#config_dbms.record_format[record format] .
<2> The store format version was introduced in Neo4j 3.4.0.
<3> The store format of the current instance is 4.0.0, which means that a format migration must be performed if you want to restore this backup into the current instance.

[NOTE]
For more information on how to migrate a single database, see https://neo4j.com/docs/migration-guide/current/online-backup-restore-database/#tutorial-online-backup-restore-database[Migration Guide -> Tutorial: Migrate a single database].

====

[[neo4j-admin-store-format-versions]]
== Store format versions and limits

Neo4j supports standard and high limit store versions.

The following is the mapping of store format versions to Neo4j Server versions, and the maximum numbers of nodes, relationships, and properties that each of the formats supports.

[[neo4j-admin-store-standard]]
=== Store format -- `standard`

.Store versions -- `standard`
[options="header"]
|===
| Store Format Name | Store Format Version | Neo4j Version

| STANDARD_V2_0
| v0.A.1
| 2.0.0

| STANDARD_V2_1
| v0.A.3
| 2.1.0

| STANDARD_V2_2
| v0.A.5
| 2.2.0

| STANDARD_V2_3
| v0.A.6
| 2.3.0

| STANDARD_V3_0
| v0.A.7
| 3.0.0

| STANDARD_V3_2
| v0.A.8
| 3.2.0

| STANDARD_V3_4
| v0.A.9
| 3.4.0
|===

.Store limits -- `standard`
[options="header"]
|===
| Name | Limit

| Property keys
| 2^24 (16 777 216)

| Nodes
| 2^35 (34 359 738 368)

| Relationships
| 2^35 (34 359 738 368)

| Properties
| 2^36 (68 719 476 736)

| Labels
| 2^32 (4 294 967 296)

| Relationship types
| 2^16 (65 536)

| Relationship groups
| 2^35 (34 359 738 368)
|===

[[neo4j-admin-store-high-limit]]
=== Store format -- `high_limit`

.Store versions -- `high_limit`
[options="header"]
|===
| Store Format Name | Store Format Version | Neo4j Version

| HIGH_LIMIT_V3_0_0
| vE.H.0
| 3.0.0

| HIGH_LIMIT_V3_0_6
| vE.H.0b
| 3.0.6

| HIGH_LIMIT_V3_1_0
| vE.H.2
| 3.1.0

| HIGH_LIMIT_V3_2_0
| vE.H.3
| 3.2.0

| HIGH_LIMIT_V3_4_0
| vE.H.4
| 3.4.0
|===

.Store limits -- `high_limit`
[options="header"]
|===
| Name | Limit

| Property keys
| 2^24 (16 777 216)

| Nodes
| 2^50 (1 Quadrillion)

| Relationships
| 2^50 (1 Quadrillion)

| Properties
| 2^50 (1 Quadrillion)

| Labels
| 2^32 (4 294 967 296)

| Relationship types
| 2^24 (16 777 216)

| Relationship groups
| 2^50 (1 Quadrillion)
|===
