[[neo4j-admin-unbind]]
= Unbind a Core Server
:description: This section describes how to remove cluster state data for a Neo4j server. 

The cluster state of a Causal Cluster member can be removed by using the following command:

`neo4j-admin unbind`

*Limitations*

The Neo4j server process should be shutdown before running the `unbind` command.

*Examples of usage*

* When transforming a Causal Cluster member to a standalone server:
+
The `unbind` command can be used to turn a Causal Cluster server into a standalone server.
To start the database in single (standalone) mode after unbinding it from the cluster, first set xref:reference/configuration-settings.adoc#config_dbms.mode[`dbms.mode=SINGLE`] in _xref:configuration/file-locations.adoc[neo4j.conf]_.

* When seeding a Causal Cluster with existing store files:
+
If you wish to seed a new Causal Cluster using the store files of a previous cluster, you must first run `neo4j-admin unbind` on each server.
For more information about seeding Causal Clusters, see xref:clustering/seed.adoc[Seed a cluster].

[WARNING]
If a cluster holds a previous version of any of the databases being seeded, you must `DROP` those databases before seeding.
Alternatively, you can stop every instance, unbind them from the cluster using xref:tools/unbind.adoc[neo4j-admin unbind] and then forcefully restore the correct seeds (backups) for the databases in question.
If you do not `DROP` or `unbind` before seeding, either with `neo4j-admin restore` or `neo4j-admin load`, the database's store files and cluster state will be out of sync, potentially leading to logical corruptions.

* When recovering a Causal Cluster:
+
In the event of serious failures you may need to recover an entire Causal Cluster from backups.
Before restoring those backups, you must first run `neo4j-admin unbind` on each server.
For more information about recovering databases from online backups, see xref:backup-restore/restore-backup.adoc[Restore a database backup].

[NOTE]
Unlike versions of Neo4j prior to v4.0.0, you *must* run the `unbind` command on both Read Replicas and Core members.
