[[neo4j-admin-unbind]]
= Unbind a Core Server
:description: This section describes how to remove cluster state data for a Core Server. 

The cluster state of a Causal Cluster Core member can be removed by using the following command:

`neo4j-admin unbind [--database=<name>]`

*Limitations*

The database should be shutdown before running the `unbind` command.

*Examples of usage*

* When downgrading a Causal Cluster member:
+
The `unbind` command can be used to turn a Causal Cluster Core Server into a standalone server.
To start the database in single mode after unbinding it from the cluster, first set xref:reference/configuration-settings.adoc#config_dbms.mode[`dbms.mode=SINGLE`] in _xref:configuration/file-locations.adoc[neo4j.conf]_.

* When seeding a Causal Cluster:
+
If you wish to seed a Causal Cluster with a database, and that cluster has previously been started, you must first run `neo4j-admin unbind` on each of the Core Servers.
For more information about seeding Causal Clusters, see xref:clustering/seed-cluster.adoc[Seed a cluster].

* When recovering a Causal Cluster:
+
If you need to recover a Causal Cluster from a backup, you must first run `neo4j-admin unbind` on each of the Core Servers.
For more information about recovering a database from online backups, see xref:backup/restoring.adoc[Restore a backup].

[NOTE]
Since Read Replicas are not members of the Core cluster, and therefore do not have a cluster state, the `unbind` command is not applicable for Read Replicas.
