[[causal-cluster-azure]]
= Causal Clusters (VM-based)
:description: This chapter describes how to deploy and run Neo4j Causal Cluster on Azure. 

The following page describes how to deploy and run a Neo4j cluster on Azure.

== Prerequisites

* You have a Neo4j Enterprise or https://neo4j.com/lp/enterprise-cloud/?utm_content=azure-marketplace[a trial license for Azure^].
* You are familiar with the xref:clustering/index.adoc[Causal Cluster architecture].
* You know how to access cloud-hosted Neo4j from your application. See the https://neo4j.com/docs/driver-manual/4.0/[Driver Manual^].


== Deploy Neo4j from the Azure Marketplace

Deploy Neo4j Enterprise Causal Cluster from the https://azuremarketplace.microsoft.com/en-us/marketplace/apps/neo4j.neo4j-ee?tab=Overview[Azure Marketplace^] following the interactive prompts.
Create a new resource group to hold the artifacts of your deployment, as the admin account name is used for SSH access to the machines in your cluster.

Once the deploy finishes, save the URL, username, and password.

[NOTE]
At the end of the deployment process, Azure runs a validation.
If the validation fails, it might be because you have chosen VMs that are too large and exceed your Azure quota.
Choose smaller VMs or increase your VM quota.


== Start using Neo4j Browser

Use your browser to access the cloud-based database URL, and log in with the initial username and password provided.
You may see an SSL warning screen because the out-of-the-box deployment uses an unsigned SSL certificate.

To verify that the cluster has formed correctly, run the following Cypher statement:

[source, cypher]
--
CALL dbms.cluster.overview().
--


== Access your instance via SSH

You can SSH into any of the machines using the configured hostname and admin credentials.

== Your cluster default configuration
The following notes are provided on your default cluster configuration.

* Ports `7687` (bolt) and `7473` (HTTPS access) are the only ports exposed to the entire internet.
Consider narrowing the access to these ports to only your needed networks.
External unencrypted HTTP access is disabled by default.
* Ports `5000`, `6000`, and `7000` are enabled only for internal network access (`10.0.0.8`), between the cluster nodes.


== What’s next

* Visit xref:clustering/index.adoc[Clustering] for more information on how to configure your cluster.
* Add users and change passwords as necessary.
* Consider creating DNS entries with Google to be able to address your cluster with client applications under a single hostname.


== Terminating the deployment

You can remove the infrastructure by deleting the entire resource group you created as part of the deployment.
