[[single-instance-azure]]
= Single instances (VM-based)
:description: This chapter describes how to launch a single instance from an image on Azure. 


== Prerequisites

* You know how to run and operate Neo4j locally.
* You have a Neo4j Enterprise or https://neo4j.com/lp/enterprise-cloud/?utm_content=azure-marketplace[a trial license for Azure^].
* You know how to access cloud-hosted Neo4j from your application. See the https://neo4j.com/docs/driver-manual/4.0/[Driver Manual^].
* You have https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest[installed and set up Azure Command Line Interface^].


== Deploy Neo4j via the Azure Marketplace

Deploy Neo4j Enterprise VM from the https://azuremarketplace.microsoft.com/en-us/marketplace/apps/neo4j.neo4j-enterprise?tab=Overview[Azure Marketplace^] following the interactive prompts.

[TIP]
The most important setting to consider are `Size`, which controls the available CPU and memory, and optionally `Disks`, where you configure high-speed SSDs and larger disk capacity sizes.
It is recommended to create a new resource group to hold the artifacts of your deployment.

Once the deploy finishes, save the URL, username, and password.


== Access your new instance

Navigate to `https://[MY_Azure_IP]:7473` and log in with the username `neo4j` and password `neo4j`.
You will be prompted to change the password immediately.

Because you do not have a hostname or a valid SSL certificate configured by default, your browser will warn you that the certificate is not trusted.
You can configure the certificate later.


== Access your instance via SSH

You can use any SSH client as normal to connect to the public IP of your instance.
Use the administrative user credentials (password or SSH key) configured during the launch.
This user has `sudo` access on the machine.

Inside the VM, you can check the status of the `neo4j` service:

[source, shell]
--
$ sudo systemctl status neo4j
neo4j.service - Neo4j Graph Database
   Loaded: loaded (/etc/systemd/system/neo4j.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-03-14 11:19:56 UTC; 15min ago
 Main PID: 1290 (pre-neo4j.sh)
    Tasks: 46
   Memory: 325.7M
      CPU: 20.690s
   CGroup: /system.slice/neo4j.service
           ├─1290 /bin/bash /etc/neo4j/pre-neo4j.sh
           └─1430 /usr/bin/java -cp /var/lib/neo4j/plugins:/etc/neo4j:/usr/share/neo4j/lib/*:/var/lib/neo4j/plugins/* -server -XX:+UseG1GC
--

For details on internals of Azure VMs, including how to stop and start system services, configure Neo4j from the VM, etc., consult xref:cloud-deployments/cloudVms.adoc[Neo4j cloud VMs].


== Deleting the instance

You can remove the infrastructure by deleting the entire resource group you created as part of the deployment.
If you deployed into an existing resource group, you have to individually delete the resources that are part of the deployment.
