:description: Deploy Neo4j on Google Cloud Platform (GCP) directly from the GCP Marketplace or by using the Neo4j Deployment Manager templates hosted on GitHub.
[[gcp]]
= Neo4j on GCP

Neo4j Edition can be easily deployed on Virtual Machines in Google Cloud Platform (GCP) by using the link:https://console.cloud.google.com/marketplace/product/neo4j/neo4j-enterprise-edition[official listing for Neo4j Enterprise Edition] or https://console.cloud.google.com/marketplace/product/neo4j/neo4j-community-edition?project=cohesive-point-368015[Neo4j Community Edition] on the GCP Marketplace].

The GCP Marketplace listing uses a Deployment Manager template maintained by Neo4j.
The template's code is available on link:https://github.com/neo4j-partners/google-deployment-manager-neo4j[GitHub^] and can be customized to meet more complex or bespoke use cases.


[NOTE]
====
Neo4j does not provide pre-built Virtual Machine (VM) images with a pre-installed version of the product.
The Neo4j GCP Marketplace listings (and listings on GitHub) use Deployment Manager templates that deploy and configure Neo4j dynamically with a shell script.
====

== Supported Neo4j versions

The Neo4j link:https://console.cloud.google.com/marketplace/product/neo4j/neo4j-enterprise-edition[GCP marketplace listing^] can be configured to deploy either Neo4j Enterprise Edition 5, or 4.4, or Neo4j Community Edition 5.
The Deployment Manager template always installs the latest available version.

== Neo4j Deployment Manager template
Google Cloud Deployment Manager is an infrastructure deployment service that automates the creation and management of Google Cloud resources.

The Neo4j Deployment Manager template takes several parameters as inputs, deploys a set of cloud resources, and provides outputs that can be used to connect to a Neo4j DBMS.

=== Important considerations

* The deployment of cloud resources incurs costs.
** Refer to the link:https://cloud.google.com/products/calculator/[GCP pricing calculator^]for more information.

* The Neo4j Deployment Manager template deploys a new VPC, containing a single subnet based in the requested region.
** Unlike Azure and AWS where subnets are aligned to specific zones, GCP subnets are regional (and VPCs are global).

* The Neo4j Deployment Manager template uses an Instance Group to deploy VM instances.
** To stop a VM managed by a group, you must first remove it from that group.

* Instances can be connected via SSH, using SSH-in-browser (via the GCP console).
** Click the *SSH* button in the GCP console.

=== Input parameters

[cols="<31s,69",frame="topbot",options="header"]
|===

| Parameter Name
| Description

| Deployment name
| A name for the deployment, e.g., `neo4j-enterprise-edition`.  The deployment name can include letters (A-Z and a-z), numbers (0-9), and dashes (-).

| Graph Database Version
| Select either 4.4 or 5.

| Node Count
| Specify the number of desired VMs to be used to form a Neo4j cluster (a minimum of 3 instances is required to form a cluster).

| Node Type
| The class of VM to use.

| Disk Type
| The type of disk volume to use on each VM instance.

| Disk Size in GB
| Size (in GB) of the disk volume on each VM instance. Persistent disk performance is tied to the size of the persistent disk volume. You are charged by GCP for the actual amount of provisioned disk space.

| Admin Password
| A password for the `neo4j` user (minimum of 8 characters).

| Install Graph Data Science
| An option (checkbox) to install Graph Data Science (GDS).

| Graph Data Science License Key
| A valid GDS license key can be pasted into this field. License keys are sent to and stored by Neo4j. This information is used only for product activation purposes.

| Install Bloom
| An option (checkbox) to install Neo4j Bloom.

| Bloom License Key
| A valid Bloom license key can be pasted into this field. License keys are sent to and stored by Neo4j. This information is used only for product activation purposes.

|===

=== Deployed cloud resources

The environment created by the Deployment Manager template consists of the following GCP resources:

* 1 subnet with a CIDR range (address space) of `10.128.0.0/20`.
** Internal and external firewall rulesets.
* An Instance Group (and Instance Group template) which creates:
** 1, or between 3 and 10 VM instances (Depending on whether a single instance or an autonomous cluster is selected).
* 1 TCP (Layer 4) Load Balancer.

=== Template outputs

After the installation finishes successfully, the Deployment Manager template provides the following outputs:

[cols="<31s,69",frame="topbot",options="header"]
|===

| Output Name
| Description

| Neo4j Browser address
| The http URL of the Neo4j Browser.

| Database region
| The region in which the Neo4j cluster has been deployed.

| Database machine type
| The class of VMs that have been deployed.

|===

[NOTE]
====
The Neo4j Browser can be easily launched in a new window by clicking the button entitled *Log into the Neo4j Browser*.
====


[role=label--enterprise-edition]
== Licensing

// label:Enterprise[]

Installing and starting Neo4j from the GCP marketplace constitutes an acceptance of the Neo4j license agreement.
When deploying Neo4j, you are required to confirm that you either have an Enterprise license or accept the terms of the Neo4j evaluation license.

If you require the Enterprise version of either Graph Data Science or Bloom, you need to provide a key issued by Neo4j as this is required during the installation.

To obtain a valid license for either Neo4j, Bloom, or GDS, reach out to your Neo4j account representative or get in touch using the link:https://neo4j.com/contact-us/[contact form^].

== Delete deployment and destroy resources

Navigate to the Deployment Manager section of the GCP console, select the deployment you wish to delete, and click the *Delete* button.
