:description: Deploy Neo4j on Amazon Web Services (AWS) directly from the AWS Marketplace or by using the Neo4j CloudFormation templates hosted on GitHub.
[role=enterprise-edition]
[[aws]]
= Neo4j on AWS

Neo4j Enterprise Edition can be easily deployed on EC2 instances in Amazon Web Services (AWS) by using the link:https://aws.amazon.com/marketplace/pp/prodview-akmzjikgawgn4?sr=0-1&ref_=beagle&applicationId=AWSMPContessa[official listing for Neo4j Enterprise in the AWS Marketplace].

The AWS Marketplace listing uses the official Neo4j AWS CloudFormation template. An up to date copy of this template can be found in the link:https://github.com/neo4j-partners/amazon-cloud-formation-neo4j/tree/main/marketplace[neo4j-partners public GitHub repository], which can be used independently of the cloud marketplace if needed. It can be downloaded and customized to meet more complex or bespoke use cases.

[NOTE]
====
Note that Neo4j does not provide Amazon Machine Images (AMIs) with a pre-installed version of the product. The Neo4j Marketplace listings and custom listings on Github utilise CloudFormation templates and a user-data (post-install) script to deploy and configure Neo4j.
====

== Supported Neo4j Versions

=== Major Versions
Both Neo4j Enterprise Edition v5 and v4.4 can be deployed from the Neo4j Enterprise Edition listing on the AWS Marketplace.  CloudFormation templates for Neo4j v4.4 can be found in the Neo4j-4.4 branch of the amazon-cloud-formation-neo4j repository (the main branch hosts the CloudFormation template for Neo4j v5):

* link:https://github.com/neo4j-partners/amazon-cloud-formation-neo4j/tree/main/marketplace[CloudFormation template for Neo4j v5]. 
* link:https://github.com/neo4j-partners/amazon-cloud-formation-neo4j/tree/Neo4j-4.4/marketplace[CloudFormation template for Neo4j v4.4].

=== Minor Versions
The Neo4j CloudFormation template will deploy the latest available minor version of either version 4.4 or 5, which is stored in an s3 hosted,  link:http://versions.neo4j-templates.com[json data file].  This file is updated automatically by Neo4j when new versions of the database are released.

When a Neo4j cluster is created, the auto-scaling group (ASG) is tagged with the version of Neo4j which was installed when the environment was created.  If additional nodes are added to an existing cluster, they will query the ASG to retrieve the version of Neo4j to be installed.  This ensures that all cluster nodes remain on the same version of Neo4j.

== Licensing

By installing and starting Neo4j from the AWS marketplace customers are accepting the terms of the Neo4j enterprise agreement and confirming they have either have an enterprise license, or accept the terms of the Neo4j evaluation license.

If you require the Enterprise version of Graph Data Science or Bloom, you will need to provide a key issued by Neo4j as this will be required during the installation.

To obtain a valid license for either Neo4j, Bloom or GDS reach out to your Neo4j account representative or get in touch using the link:https://neo4j.com/contact-us/[contact form]

== Neo4j CloudFormation template

AWS CloudFormation is a declarative Infrastructure as Code (IaC) language that instructs AWS to deploy a set of cloud resources.

The Neo4j CloudFormation template takes a number of parameters as inputs, deploys a set of cloud resources and provides outputs:

=== Input Parameters (for Neo4j v5)

[cols="<31,69",frame="topbot",options="header"]
|===

^s| Parameter Name
^s| Parameter Description

| Stack Name
| _A name for the CloudFormation stack to be deployed, eg: my-neo4j-cluster. Stack name can include letters (A-Z and a-z), numbers (0-9), and dashes (-)._

| Install Graph Data Science
| _Optionally install Graph Data Science (GDS)_

| Graph Data Science License Key
| _License keys will be sent to and stored by Neo4j. This information will only be used for the purposes of product activation._

| Install Bloom
| _Optionally install Neo4j Bloom_

| Bloom License Key
| _License Key for Bloom (License keys will be sent to and stored by Neo4j. This information will only be used for the purposes of product activation.)_

| Password
| _A password for the 'neo4j' user.  Must be a minimum of 8 characters_

| Number of Servers
| _Specify the number of desired EC2 intances which will be used to form a Neo4j cluster (a minimum of 3 instances is required to form a cluster.)_  

| Instance type
| _The class of EC2 Instance to use_

| Disk Size
| _Size in GB of the EBS volume on each node.  Larger EBS volumes will typically be faster than smaller ones, therefore 100GB is a recommended minimum size._

| SSH CIDR
| _SSH CIDR (Specify an address range from which ec2 instances are accessible on port 22. You can use 0.0.0.0/0 to allow access from any IP address). This field must also be correctly populated to allow the use of ec2 instance-connect._

|===

=== Deployed Cloud Resources

Users are reminded that the deployment of cloud resources will incur costs.

[NOTE]
====
The Neo4j CloudFormation Template uses an auto-scaling group (ASG) to deploy EC2 instances.  This means that if stopped or teminated, EC2 instances will be automatically re-created.  In order to stop or terminate EC2 instances, they would first need to be removed from the ASG.
====

* 1 VPC, with a CIDR range of 10.0.0.0/16
** 3 Subnets, distributed evenly across 3 Availability zones, with the following CIDR Ranges:
*** 10.0.1.0/24
*** 10.0.2.0/24
*** 10.0.3.0/24
* An auto-scaling group and launch configuration, which creates:
** 1, or between 3 and 10 EC2 instances (Depending on whether a single instance, or an autonomous cluster is selected)
* 1 Network (Layer 4) Load Balancer

=== Template Outputs

[cols="<31,69",frame="topbot",options="header"]
|===

^s| Output Name
^s| Output Description

| Neo4jBrowserURL
| The http URL of the Neo4j Browser

| Neo4jURI
| The Bolt URL of the Neo4j Browser

| Neo4jUsername	
| The username 'neo4j' 

|===

== Verify that Neo4j is running

When the CloudFormation stack is created, navigate to the *Outputs* tab and click the *Neo4jLoadBalancerURL*.

The URL points to the Neo4j Browser, where the specified credentials can be used to log in to Neo4j.

== Clean up the resources and remove your stack

Select the CloudFormation stack to be removed and click the *Delete* button.
The stack deletion cleans up all AWS resources deployed by it.