:description: Deploy Neo4j on Amazon Web Services (AWS) directly from the AWS Marketplace or by using the Neo4j CloudFormation templates hosted on GitHub.
[role=enterprise-edition]
[[aws]]
= Neo4j on AWS

Neo4j Enterprise Edition can be easily deployed on EC2 instances in Amazon Web Services (AWS) by using our link:https://aws.amazon.com/marketplace/pp/prodview-akmzjikgawgn4?sr=0-1&ref_=beagle&applicationId=AWSMPContessa[listing for Neo4j Enterprise on the AWS Marketplace].

The AWS Marketplace listing uses a CloudFormation template maintained by Neo4j. 
The template's code is available on link:https://github.com/neo4j-partners/amazon-cloud-formation-neo4j/tree/main/marketplace[GitHub] and can be customized to meet more complex or bespoke use cases. 
See <<cloudformation_template>>.

// Does this matter? Is the purpose of a note for additional technical information? Or about calling your attention to an important caveat?
[NOTE]
====
Neo4j does not provide Amazon Machine Images (AMIs) with a pre-installed version of the product. The Neo4j Marketplace listings and custom listings on Github use CloudFormation templates and user-data (post-install) scripts to deploy and configure Neo4j.
====

== Supported Neo4j Versions

Our link:https://aws.amazon.com/marketplace/seller-profile?id=23ec694a-d2af-4641-b4d3-b7201ab2f5f9[AWS marketplace listing] can be configured to deploy either Neo4j Enterprise Edition v5 or v4.4. 
The  CloudFormation template will always install the latest minor version of Neo4j v5 or v4.4.

=== Clusters

//does this get updated when the cluster is upgraded?
//try to avoid the word "nodes".
When a Neo4j cluster is created, the auto-scaling group (ASG) is tagged with the minor version of the installed Neo4j. When additional instances are added they will query the ASG's tag to ensure that all cluster nodes are on the same version regardless of when the EC2 instances were created.

== Licensing

Installing and starting Neo4j from the AWS marketplace constitutes an acceptance of the Neo4j license agreement.  By deploying Neo4j, users are therefore confirming they either have an enterprise license or accept the terms of the Neo4j evaluation license.

If you require the Enterprise version of either Graph Data Science or Bloom, you will need to provide a key issued by Neo4j as this will be required during the installation.

To obtain a valid license for either Neo4j, Bloom or GDS reach out to your Neo4j account representative or get in touch using the link:https://neo4j.com/contact-us/[contact form]

== Neo4j CloudFormation template [[cloudformation_template]]

AWS CloudFormation is a declarative Infrastructure as Code (IaC) language that is based on yaml and instructs AWS to deploy a set of cloud resources.
The CloudFormation template repository has v5 on the main branch and v4 on the ```Neo4j-4.4``` branch:

* link:https://github.com/neo4j-partners/amazon-cloud-formation-neo4j/tree/main/marketplace[CloudFormation template for Neo4j v5]. 
* link:https://github.com/neo4j-partners/amazon-cloud-formation-neo4j/tree/Neo4j-4.4/marketplace[CloudFormation template for Neo4j v4.4].

The Neo4j CloudFormation template takes several parameters as inputs, deploys a set of cloud resources and provides outputs:

=== Input Parameters

[cols="<31,69",frame="topbot",options="header"]
|===

^s| Parameter Name
^s| Parameter Description

| Stack Name
| _A name for the CloudFormation stack to be deployed, eg: my-neo4j-cluster. Stack name can include letters (A-Z and a-z), numbers (0-9), and dashes (-)._

| Install Graph Data Science
| _Optionally install Graph Data Science (GDS)_

| Graph Data Science License Key
| _License keys will be sent to and stored by Neo4j. This information will only be used for product activation._

| Install Bloom
| _Optionally install Neo4j Bloom_

| Bloom License Key
| _License Key for Bloom (License keys will be sent to and stored by Neo4j. This information will only be used for product activation.)_

| Password
| _A password for the 'neo4j' user.  Must be a minimum of 8 characters_

| Number of Servers
| _Specify the number of desired EC2 instances that will be used to form a Neo4j cluster (a minimum of 3 instances is required to form a cluster.)_  

| Instance type
| _The class of EC2 Instance to use_

| Disk Size
| _Size in GB of the EBS volume on each node.  Larger EBS volumes will typically be faster than smaller ones, therefore 100GB is a recommended minimum size._

| SSH CIDR
| _SSH CIDR (Specify an address range from which ec2 instances are accessible on port 22. You can use 0.0.0.0/0 to allow access from any IP address). This field must also be correctly populated to allow the use of ec2 instance-connect._

|===

=== Deployed Cloud Resources

*Users are reminded that the deployment of cloud resources will incur costs.*

[NOTE]
====
The Neo4j CloudFormation Template uses an auto-scaling group (ASG) to deploy EC2 instances.  This means that if stopped or terminated, EC2 instances will be automatically replaced.  To stop or terminate EC2 instances, they would first need to be removed from the ASG.
====

The environment which is created by the CloudFormation template, consists of the following AWS resources:

* 1 VPC, with a CIDR range of 10.0.0.0/16
** 3 Subnets, distributed evenly across 3 Availability zones, with the following CIDR Ranges:
*** 10.0.1.0/24
*** 10.0.2.0/24
*** 10.0.3.0/24
** An internet gateway
** Routing tables (and associations) for all subnets
* An auto-scaling group and launch configuration, which creates:
** 1, or between 3 and 10 EC2 instances (Depending on whether a single instance, or an autonomous cluster is selected)
* 1 Network (Layer 4) Load Balancer
** A target group for the EC2 instances

=== Template Outputs

When installation has successfully been completed, the CloudFormation template provides the following outputs.  They can be found in the *Outputs* tab of the CloudFormation page on the AWS console.

[cols="<31,69",frame="topbot",options="header"]
|===

^s| Output Name
^s| Output Description

| Neo4jBrowserURL
| The http URL of the Neo4j Browser

| Neo4jURI
| The Bolt URL of the Neo4j Browser

| Neo4jUsername	
| The username *neo4j* and a reminder to use the password which was specified earlier when filling out the CloudFormation template 

|===

== Verify that Neo4j is running

When the CloudFormation stack is created, navigate to the *Outputs* and open the *Neo4jLoadBalancerURL* in a new tab.

The URL points to the Neo4j Browser, where the specified credentials can be used to log in to Neo4j.

== Clean up the resources and remove your stack

Select the CloudFormation stack to be removed and click the *Delete* button.
The stack deletion cleans up all AWS resources deployed by it.