:description: Deploy Neo4j on Google Cloud Platform (GCP) directly from the GCP Marketplace or by using the Neo4j Deployment Manager templates hosted on GitHub.
:page-role: enterprise-edition
[[gcp]]
= Neo4j on GCP

Neo4j can be easily deployed on Virtual Machines in Google Cloud Platform (GCP) by using the link:https://console.cloud.google.com/marketplace/product/neo4j-mp-public/neo4j-enterprise-edition[official listing] on the GCP Marketplace.

The GCP Marketplace listing uses HashiCorp Terraform IaC tool to deploy Neo4j Enterprise Edition on GCP.
You can find the repository for the Terraform configuration files on link:https://github.com/neo4j-partners/gcp-tf-neo4j[GitHub].

== Supported Neo4j versions

The Neo4j link:https://console.cloud.google.com/marketplace/product/neo4j/neo4j-enterprise-edition[GCP marketplace listing] can be configured to deploy only Neo4j Enterprise Edition 2025.x, both standalone and cluster (1, 3, 4, 5, 6, or 7 servers).
Previous versions of Neo4j, such as 4.4 and 5.26 LTS are no longer supported.

== Neo4j Terraform deployment module

HashiCorp Terraform is an infrastructure deployment module, which automates the creation and management of Google Cloud resources.
It takes several parameters as inputs, deploys a set of cloud resources, and provides outputs that can be used to connect to a Neo4j DBMS.

== Prerequisites

Before deploying Neo4j using the Terraform module, ensure you have the following prerequisites in place:

* Terraform 1.2.0 or newer.
See the link:https://developer.hashicorp.com/terraform/install[official Terraform installation guide] for instructions.
* Google Cloud SDK
* A GCP project with billing enabled
* Appropriate permissions to create resources in GCP
* Default project configured in `gcloud` CLI (`gcloud config set project YOUR_PROJECT_ID`)

=== Important considerations

* The deployment of cloud resources incurs costs.
Refer to the link:https://cloud.google.com/products/calculator[GCP pricing calculator]for more information.

* The Neo4j Terraform module deploys a new VPC, containing a single subnet based in the requested region.
Unlike Azure and AWS where subnets are aligned to specific zones, GCP subnets are regional (and VPCs are global).

* The Neo4j Terraform module uses an Instance Group to deploy VM instances.
To stop a VM managed by a group, you must first remove it from that group.

* Instances can be connected via SSH, using SSH-in-browser (via the GCP console).
Click the *SSH* button in the GCP console.

=== Input parameters

[cols="2,4a,2m",frame="topbot",options="header"]
|===

| Parameter Name
| Description
| Default Value

| Project ID
| The ID of the project in which to provision resources.
|

| License type
| Neo4j license type (enterprise-byol or evaluation).
| enterprise-byol

| Region
| The GCP region where resources will be created.
| us-central1

| Zone
| The zone for the solution to be deployed.
| us-central1-a

| Deployment Name
| The name of the deployment and VM instances.
| neo4j

| Image version
| The image name for the disk for the VM instance.
| projects/neo4j-mp-public/global/images/neo4j-enterprise-edition

| Network name
| The name of the VPC network to use or create.
| neo4j-network

| Subnetwork name
| The name of the subnetwork to use or create.
| neo4j-subnet

| Create a new network
| Whether to create a new network or use an existing one
| true

| Subnetwork CIDR
| CIDR range for the subnetwork.
| 10.10.10.0/24

| Number of nodes
| Number of Neo4j nodes to deploy. Node count must be 1 (standalone) or 3/5/7 (cluster)
| 3

| Machine type
| GCP machine type for Neo4j nodes.
| c3-standard-4

| Disk size in GB
| Size of the data disk in GB.
| 100

| Admin password
| Password for the Neo4j admin user. The password must be at least 8 characters long.
| Neo4j1234

| Install Neo4j Bloom
| Whether to install Neo4j Bloom.
| false

| Bloom License Key
| License key for Neo4j Bloom (if installing).
| ""

| Source IP ranges for firewall rules
| Source IP ranges for external access. Traffic is only allowed from sources within these IP address ranges. Use CIDR notation when entering ranges.
| 0.0.0.0/0

|===

=== Deployed cloud resources

The environment created by the Terraform module consists of the following GCP resources:

* 1 subnet with a CIDR range (address space) of `10.128.0.0/20`. Internal and external firewall rulesets.
* An Instance Group (and Instance Group template) which creates 1, or between 3 and 10 VM instances, depending on whether a single instance or an autonomous cluster is selected.
* 1 TCP (Layer 4) Load Balancer.

=== Template outputs

After the installation finishes successfully, the Terraform module provides the following outputs:

[cols="<31s,69",frame="topbot",options="header"]
|===

| Output Name
| Description

| neo4j_url
| URL to access Neo4j Browser.

| neo4j_bolt_url
| Bolt URL to connect to Neo4j.

| neo4j_ip_addresses
| IP addresses of the Neo4j nodes.

| neo4j_instance_names
| Names of the Neo4j instances.

| neo4j_instance_zones
| Zones where Neo4j instances are deployed.

| neo4j_instance_machine_types
| Machine types of Neo4j instances.
|===

[NOTE]
====
The Neo4j Browser can be easily launched in a new window by clicking the button entitled *Log into the Neo4j Browser*.
====

== Licensing

Installing and starting Neo4j from the GCP marketplace constitutes an acceptance of the Neo4j license agreement.
When deploying Neo4j, you are required to confirm that you either have an Enterprise license or accept the terms of the Neo4j evaluation license.

If you require the Enterprise version of Bloom, you need to provide a key issued by Neo4j as this is required during the installation.

To obtain a valid license for Bloom reach out to your Neo4j account representative or get in touch using the link:https://neo4j.com/contact-us/[contact form].

== Delete deployment and destroy resources

To delete the deployment and destroy all associated resources, you can use the following Terraform command:

[source,console]
----
terraform destroy
----

This command will prompt you to confirm the destruction of all resources defined in your Terraform configuration.
Review the proposed changes carefully before confirming.
For detailed information on the `terraform destroy` command, refer to the link:https://developer.hashicorp.com/terraform/cli/commands/destroy[official Terraform documentation].
