:description: How to deploy a Neo4j cluster to a cloud or a local Kubernetes cluster using Neo4j Helm Charts.
[role=enterprise-edition]
[[quick-start-cluster]]
= Quickstart: Deploy a cluster

The quickstart for deploying a Neo4j cluster contains the following:

[NOTE]
====
This guide shows how to deploy a cluster with three core members and one read replica.
====

* <<cc-server-setup, Neo4j Helm Charts for cluster deployments>> -- A schematic representation of how to use the Neo4j Helm Charts for deploying a cluster.
* <<cc-prerequisites, Prerequisites>> -- Set up your environment for deploying a Neo4j cluster on Kubernetes.
* <<cc-create-pv, Create a persistent volume for each cluster member>> -- Create a persistent volume for each Neo4j cluster member to be used for its `data` volume mount.
* <<cc-create-value-file, Create Helm deployment values files>> -- Create a Helm deployment _values.yaml_ file for each Neo4j cluster member.
* <<cc-install-cores, Install Neo4j core members>> -- Install each of your Neo4j core members using its deployment YAML file and the `neo4j/neo4j-cluster-core` Helm Chart.
* <<cc-install-rr, Install Neo4j read replicas>> -- Install your Neo4j read replica using its deployment YAML file and the `neo4j/neo4j-cluster-read-replica` Helm Chart.
* <<cc-verify-cluster, Verify cluster formation>> -- Verify that the Neo4j core members and read replica have formed a cluster.
* <<cc-access-inside-k8s, Access the Neo4j cluster from inside Kubernetes>> -- Access the Neo4j cluster from inside Kubernetes using a specific core or the headless service.
* <<cc-access-outside-k8s, Access the Neo4j cluster from outside Kubernetes>> -- Access the Neo4j cluster from outside Kubernetes using a load balancer.
* <<cc-uninstall-cleanup, Uninstall the Neo4j cluster and clean up the created resources>> -- Uninstall all Neo4j Helm deployments and clean up the created resources.
