[role=deprecated]
[[backup-restore-ha-cluster]]
= Backup and restore
:description: The steps required to backup and restore a Neo4j HA cluster. 


Review xref:backup/planning.adoc[Backup planning] for a discussion about backup strategies.

The applicable configuration options for backups in a Neo4j HA cluster are the same as for a standalone database.
See xref:backup/standalone.adoc#backup-standalone-parameters[Configuration parameters].

To back up an HA cluster, follow the instructions in xref:backup/performing.adoc[Perform a backup].

To restore from backup in an HA cluster environment, follow these steps:

. Shut down all database instances in the cluster.
. Restore the backup on each instance, using `xref:backup/restoring.adoc#backup-restoring-command[neo4j-admin restore]`.
. If you are restoring onto new hardware, please review the _HA_ settings in _neo4j.conf_.
+
In particular, check the `xref:reference/configuration-settings.adoc#config_ha.initial_hosts[ha.initial_hosts]` setting to ensure that the servers listed reflect the servers on which the restores are being made.
. Start the database instances, beginning with the master.
