[role=deprecated]
[[ha-basic-installation]]
= Basic installation
:description: This appendix outlines the steps for a basic installation of an HA cluster. 

Neo4j can be configured in cluster mode to accommodate differing requirements for load, fault tolerance and available hardware.

Follow these steps in order to configure a Neo4j HA cluster:

. Download and install the Neo4j Enterprise Edition on each of the servers to be included in the cluster.
. If applicable, decide which server(s) that are to be configured as arbiter instance(s).
. Edit the Neo4j configuration file on each of the servers to accommodate the design decisions.
. Follow installation instructions for a xref:installation/index.adoc[single instance installation].
. Modify the configuration files on each server as outlined in the section below.
  There are many parameters that can be modified to achieve a certain behavior.
  However, the only ones mandatory for an initial cluster are: `xref:reference/configuration-settings.adoc#config_dbms.mode[dbms.mode]`, `xref:reference/configuration-settings.adoc#config_ha.server_id[ha.server_id]` and `xref:reference/configuration-settings.adoc#config_ha.initial_hosts[ha.initial_hosts]`.
