:description: How to deploy a Neo4j standalone instance to a cloud or a local Kubernetes cluster using Neo4j Helm Charts.

[[quick-start-standalone]]
= Quickstart: Deploy a standalone instance

This quickstart guide walks through the basics of deploying a Neo4j standalone instance to a cloud or a local Kubernetes cluster using the Neo4j Helm Charts.

The quickstart for deploying a Neo4j standalone server contains the following:

* <<si-server-setup, Neo4j Helm Charts for standalone server deployments>> -- A schematic representation of how to use the Neo4j Helm Charts for deploying a standalone server.
* <<si-prerequisites, Prerequisites>> -- Set up your environment for deploying a Neo4j standalone instance on Kubernetes.
* <<si-create-pv, Create a persistent volume>> -- Create a persistent volume for the Neo4j instance.
* <<si-create-value-file, Create a Helm deployment _values.yaml_ file>> -- Create a Helm deployment _values.yaml_ file with all Neo4j configurations.
* <<si-install-neo4j, Install a Neo4j standalone instance>> -- Install a Neo4j standalone instance using the deployment _values.yaml_ file and the `neo4j/neo4j-standalone` Helm Chart.
* <<si-verify-installation, Verify the installation>> -- Verify the Neo4j installation.
* <<si-uninstall-cleanup, Uninstall Neo4j and clean up the created resources>> -- Uninstall Neo4j and clean up the created resources.
