:description: This page gives an introduction to database administration using Neo4j.
:page-aliases: manage-databases/introduction.adoc, manage-databases/index.adoc
[database-administration]
= Database administration

Neo4j is a Database Management System, or DBMS, capable of managing multiple databases.
The DBMS can manage a standalone server, or a group of servers in a cluster.

A database is an administrative partition of a DBMS.
In practical terms, it is a physical structure of files organized within a directory or folder, that has the same name of the database.

This chapter describes how to manage standard databases, composite databases, and local and remote database aliases.
All databases and database aliases are managed using the Cypher administration commands.
For more information on the Cypher administration commands syntax, see xref:database-administration/syntax.adoc[Database management command syntax].

[WARNING]
====
Cypher administration commands must not be used during a rolling upgrade.
For more information, see link:{neo4j-docs-base-uri}/upgrade-migration-guide/current/version-2025/#_clusters[Upgrade and Migration Guide -> Upgrade to a Neo4j 2025 release -> Clusters].
====

== Standard databases

In Neo4j {neo4j-version}, each standard database contains a single graph.
Many administrative commands refer to a specific graph by using the database name.

A database defines a _transaction domain_ (a collection of graphs that can be updated within the context of a single transaction) and an _execution context_ (a runtime environment for the execution of a request).
This means that a transaction cannot span across multiple databases.
Similarly, a procedure is called within a database, although its logic may access data that is stored in other databases.

=== Standard databases per Neo4j edition

The edition of Neo4j determines the number of possible databases:

* Installations of Community Edition can have exactly *one* standard database.
* Installations of Enterprise Edition can have any number of standard databases.

[[manage-databases-default]]
=== Default database

A default installation of Neo4j {neo4j-version} contains one standard database, named `neo4j`, which is the default database for the DBMS.
A different name can be configured before starting Neo4j for the first time.
For details, see xref:database-administration/standard-databases/configuration-parameters.adoc[Configuration parameters].

The following image illustrates an installation of Neo4j containing the three standard databases, named `marketing`, `sales`, and `hr`, and the `system` database.
The default database is `sales`:

image::manage-dbs-default.svg[title="A multiple database Neo4j installation, with a default database.",role=popup]

[NOTE]
====
Be aware that the automatically created _initial_ default database may have a different topology to the default configuration values.
See xref:clustering/databases.adoc#cluster-default-database[Default database in a cluster] for more information.
====

[role=enterprise-edition]
[[manage-databases-home]]
=== Per-user home databases

The home database is the database that you connect to by default when no database is specified.
It is different from the default database, which is the database that the server uses when no home database is specified.

Per-user home databases are controlled via the Cypher administration commands.

To set a home database for a user, this user must exist as a record in Neo4j.
Therefore, for deployments using xref:authentication-authorization/index.adoc[auth providers] other than native, you create a native user with a matching username and then set a home database for that user.
For more information on creating native users and configuring a home database for a user, see xref:authentication-authorization/manage-users.adoc[Manage users].

[[manage-databases-system]]
== The `system` database

All installations include a built-in database named `system`, which contains metadata on the DBMS and security configuration.

The `system` database behaves differently than all other databases.
In particular, when connected to this database you can only perform a specific set of administrative tasks, such as managing databases, aliases, servers, and access control.

Most of the available administrative commands are restricted to users with specific administrative privileges.
An example of configuring security privileges is described in xref:tutorial/access-control.adoc[Fine-grained access control].

.A default installation, including the `system` database and a single standard database named `neo4j`:
image::manage-dbs-community.svg[title="A default Neo4j installation.",role=popup]

.An installation of Neo4j with multiple active databases, named `marketing`, `sales`, and `hr`:
image::manage-dbs-enterprise.svg[title="A multiple database Neo4j installation.",role=popup]

For details about the `system` database in a clustered environment, refer to the xref:clustering/databases.adoc#cluster-system-db[Managing databases in a cluster -> The `system` database]. 

== Composite databases

A Composite database is a logical grouping of multiple graphs contained in other, standard databases.
A Composite database defines an _execution context_ and a (limited) _transaction domain_.
For more information, see xref:database-administration/composite-databases/concepts.adoc[Composite databases].