:description: This page provides the syntax for the Cypher administration commands.
[[administration-syntax]]
= Database management command syntax

Almost all administration commands have variations.
The most common are parts of the command that are optional or that can have multiple values.

See below a summary of the syntax used to describe all versions of a command.
These summaries use some special characters to indicate such variations.

[[administration-syntax-reading]]
== Reading the administration commands syntax

.Special characters in syntax summaries
[options="header", width="100%", cols="1a,3a,3a"]
|===
| Character | Meaning | Example

| `\|`
|
Used to indicate alternative parts of a command (i.e. `or`).
Needs to be part of a grouping.
| If the syntax needs to specify either a name or `+*+`, this can be indicated with `+* \| name+`.

| `+{+` and `+}+`
| Used to group parts of the command. Commonly found together with `\|`.
| In order to use the `or` in the syntax summary, it needs to be in a group: `+{* \| name}+`.

| `[` and `]`
| Used to indicate an optional part of the command.
It also groups alternatives together, when there can be either of the alternatives or nothing.
| If a keyword in the syntax can either be in singular or plural, we can indicate that the `S` is optional with `GRAPH[S]`.

| `+...+`
|
Repeated pattern.
Related to the command part immediately before this is repeated.
| A comma separated list of names would be `+name[, ...]+`.

| `"`
| When a special character is part of the syntax itself, we surround it with `"` to indicate this.
|
To include `+{+` in the syntax use `+"{" { * \| name } "}"+`.
In this case, you will get either `+{ * }+` or `+{ name }+`.

|===

The special characters in the table above are the only ones that need to be escaped using `"` in the syntax summaries.

Here is an example that uses all the special characters.
It grants the `READ` privilege:

[source, syntax, role="noheader"]
----
GRANT READ
  "{" { * | property[, ...] } "}"
  ON {HOME GRAPH | GRAPH[S] { * | name[, ...] }}
    [ ELEMENT[S] { * | label-or-rel-type[, ...] }
    | NODE[S] { * | label[, ...] }
    | RELATIONSHIP[S] { * | rel-type[, ...] }]
  TO role[, ...]
----

Note that this command includes `+{+` and `+}+` in the syntax, and between them there can be a grouping of properties or the character `+*+`.
It also has multiple optional parts, including the entity part of the command which is the grouping following the graph name.
For details about the graph privilege commands syntax, see xref:/authentication-authorization/manage-privileges.adoc#components-of-the-graph-privilege-commands[Components of the graph privilege commands].

However, there is no need to escape any characters when creating a constraint for a node property.
This is because `(` and `)` are not special characters, and `[` and `]` indicate that the constraint name and the `IF NOT EXISTS` parts are optional, and therefore not part of the command.

[source, syntax, role="noheader"]
----
CREATE CONSTRAINT [constraint_name] [IF NOT EXISTS]
FOR (n:LabelName)
REQUIRE n.propertyName IS NOT NULL
----

[[administration-syntax-database-management]]
== Database management command syntax

The database management commands are used to manage standard or composite databases.

=== Show databases

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax

| SHOW DATABASE
|
[source, syntax, role="noheader"]
----
SHOW { DATABASE[S] name \| DATABASE[S] \| DEFAULT DATABASE \| HOME DATABASE }
[WHERE expression]
----

[source, syntax, role="noheader"]
----
SHOW { DATABASE[S] name \| DATABASE[S] \| DEFAULT DATABASE \| HOME DATABASE }
YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]
[WHERE expression]
[RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----
|===

=== Create a database

[.tabbed-example]
=====
[role=include-with-Cypher-5]
======
[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax

| CREATE DATABASE
|
[source, syntax, role="noheader"]
----
CREATE DATABASE name [IF NOT EXISTS]
[DEFAULT LANGUAGE CYPHER {5\|25}]
[TOPOLOGY n PRIMAR{Y\|IES} [m SECONDAR{Y\|IES}]]
[OPTIONS "{" option: value[, ...] "}"]
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----

[source, syntax, role="noheader"]
----
CREATE OR REPLACE DATABASE name
[DEFAULT LANGUAGE CYPHER {5\|25}]
[TOPOLOGY n PRIMAR{Y\|IES} [m SECONDAR{Y\|IES}]]
[OPTIONS "{" option: value[, ...] "}"]
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----
|===

======

[role=include-with-Cypher-25]
======

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax
| CREATE DATABASE
|
[source, syntax, role="noheader"]
----
CREATE DATABASE name [IF NOT EXISTS]
[[SET] TOPOLOGY n PRIMAR{Y\|IES} [m SECONDAR{Y\|IES}]]
[OPTIONS "{" option: value[, ...] "}"]
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----

[source, syntax, role="noheader"]
----
CREATE OR REPLACE DATABASE name
[[SET] TOPOLOGY n PRIMAR{Y\|IES} [m SECONDAR{Y\|IES}]]
[OPTIONS "{" option: value[, ...] "}"]
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----
|===

======
=====
=== Create a composite database

[options="header", width="100%", cols="2m,4a"]
|===
| Command | Syntax

| CREATE COMPOSITE DATABASE
|
[source, synatx, role="noheader"]
----
CREATE COMPOSITE DATABASE name [IF NOT EXISTS]
[DEFAULT LANGUAGE CYPHER {5\|25}]
[OPTIONS "{" "}"]
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----

[source, syntax, role="noheader"]
----
CREATE OR REPLACE COMPOSITE DATABASE name
[DEFAULT LANGUAGE CYPHER {5\|25}]
[OPTIONS "{" "}"]
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----
|===

=== Alter a database

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax

| ALTER DATABASE
|
[source, syntax, role="noheader"]
----
ALTER DATABASE name [IF EXISTS]
{
SET ACCESS {READ ONLY \| READ WRITE} \|
SET TOPOLOGY n PRIMAR{Y\|IES} [m SECONDAR{Y\|IES}] \|
SET OPTION option value \|
SET DEFAULT LANGUAGE CYPHER {5\|25}
}
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----

[source, syntax]
----
ALTER DATABASE name [IF EXISTS]
REMOVE OPTION option
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----

[NOTE]
====
There can be multiple `SET OPTION` or `REMOVE OPTION` clauses for different option keys.
====
|===

=== Stop a database

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax

| STOP DATABASE
|
[source, syntax, role="noheader"]
----
STOP DATABASE name [WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----
|===

=== Start a database

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax

| START DATABASE
|
[source, syntax, role="noheader"]
----
START DATABASE name [WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----
|===

=== Delete a database

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax

| DROP DATABASE
|
[source, syntax, role="noheader"]
----
DROP [COMPOSITE] DATABASE name [IF EXISTS] [RESTRICT \| CASCADE ALIAS[ES]] [{DUMP\|DESTROY} [DATA]] [WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----

|===

[[administration-syntax-database-alias-management]]
== Database alias management command syntax

The database alias management commands are used to manage local or remote database aliases.

=== Show aliases

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax
| SHOW ALIAS
|
[source, syntax, role=noheader]
-----
SHOW ALIAS[ES] [name] FOR DATABASE[S]
[WHERE expression]
-----
[source, syntax, role=noheader]
-----
SHOW ALIAS[ES] [name] FOR DATABASE[S]
YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]
[WHERE expression]
[RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
-----
Lists both local and remote database aliases, optionally filtered on the alias name.
|===

=== Create a local alias

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax

| CREATE ALIAS
|
[source, syntax, role=noheader]
-----
CREATE ALIAS name [IF NOT EXISTS] FOR DATABASE targetName
[PROPERTIES "{" key: value[, ...] "}"]
-----
[source, syntax, role=noheader]
-----
CREATE OR REPLACE ALIAS name FOR DATABASE targetName
[PROPERTIES "{" key: value[, ...] "}"]
-----
|===

=== Create a remote alias

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax

| CREATE ALIAS
|
[source, syntax, role=noheader]
-----
CREATE ALIAS name [IF NOT EXISTS] FOR DATABASE targetName
AT 'url' USER username PASSWORD 'password'
[DRIVER "{" setting: value[, ...] "}"]
[DEFAULT LANGUAGE CYPHER {5\|25}]
[PROPERTIES "{" key: value[, ...] "}"]
-----
[source, syntax, role=noheader]
-----
CREATE OR REPLACE ALIAS name FOR DATABASE targetName
AT 'url' USER username PASSWORD 'password'
[DRIVER "{" setting: value[, ...] "}"]
[DEFAULT LANGUAGE CYPHER {5\|25}]
[PROPERTIES "{" key: value[, ...] "}"]
-----
|===

=== Alter a local alias

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax

|ALTER ALIAS
|
[source, syntax, role=noheader]
-----
ALTER ALIAS name [IF EXISTS] SET DATABASE
[TARGET targetName]
[PROPERTIES "{" key: value[, ...] "}"]
-----
|===

=== Alter a remote alias

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax
|ALTER ALIAS
|
[source, syntax, role=noheader]
-----
ALTER ALIAS name [IF EXISTS] SET DATABASE
[TARGET targetName AT 'url']
[USER username]
[PASSWORD 'password']
[DRIVER "{" setting: value[, ...] "}"]
[DEFAULT LANGUAGE CYPHER {5\|25}]
[PROPERTIES "{" key: value[, ...] "}"]
-----

|===

=== Delete an alias

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax

| DROP ALIAS
|
[source, syntax, role=noheader]
-----
DROP ALIAS name [IF EXISTS] FOR DATABASE
-----
Drop either a local or remote database alias.

|===