:description: This page provides the syntax for the Cypher administration commands.
[[administration-syntax]]
= Database management command syntax

Almost all administration commands have variations.
The most common variations include parts of the commands that are optional, or that can have multiple values.
Some variations are indicated using special characters.
See <<administration-syntax-reading,Reading the administration commands syntax>> for details.

This page summarizes the various command syntax options.
It also includes examples for both Cypher 5 and Cypher 25 when available.

include::partial$/cypher-versions.adoc[]


[[administration-syntax-reading]]
== Reading the administration commands syntax

.Special characters in syntax summaries
[options="header", width="100%", cols="1a,3a,3a"]
|===
| Character | Meaning | Example

| `\|`
|
Used to indicate alternative parts of a command (i.e. `or`).
Needs to be part of a grouping.
| If the syntax needs to specify either a name or `+*+`, this can be indicated with `+* \| name+`.

| `+{+` and `+}+`
| Used to group parts of the command. Commonly found together with `\|`.
| In order to use the `or` in the syntax summary, it needs to be in a group: `+{* \| name}+`.

| `[` and `]`
| Used to indicate an optional part of the command.
It also groups alternatives together, when there can be either of the alternatives or nothing.
| If a keyword in the syntax can either be in singular or plural, you can indicate that the `S` is optional with `GRAPH[S]`.

| `+...+`
|
Repeated pattern.
Related to the command part immediately before this is repeated.
| A comma separated list of names would be `+name[, ...]+`.

| `"`
| When a special character is part of the syntax itself, surround it with `"` to indicate this.
|
To include `+{+` in the syntax use `+"{" { * \| name } "}"+`.
In this case, you will get either `+{ * }+` or `+{ name }+`.

|===

The special characters in the table above are the only ones that need to be escaped using `"` in the syntax summaries.

Here is an example that uses all the special characters.
It grants the `READ` privilege:

[source, syntax, role="noheader"]
----
GRANT READ
  "{" { * | property[, ...] } "}"
  ON {HOME GRAPH | GRAPH[S] { * | name[, ...] }}
    [ ELEMENT[S] { * | label-or-rel-type[, ...] }
    | NODE[S] { * | label[, ...] }
    | RELATIONSHIP[S] { * | rel-type[, ...] }]
  TO role[, ...]
----

Note that this command includes `+{+` and `+}+` in the syntax, and between them there can be a grouping of properties or the character `+*+`.
It also has multiple optional parts, including the entity part of the command which is the grouping following the graph name.
For details about the graph privilege commands syntax, see xref:/authentication-authorization/manage-privileges.adoc#components-of-the-graph-privilege-commands[Components of the graph privilege commands].

However, there is no need to escape any characters when creating a constraint for a node property.
This is because `(` and `)` are not special characters, and `[` and `]` indicate that the constraint name and the `IF NOT EXISTS` parts are optional, and therefore not part of the command.

[source, syntax, role="noheader"]
----
CREATE CONSTRAINT [constraint_name] [IF NOT EXISTS]
FOR (n:LabelName)
REQUIRE n.propertyName IS NOT NULL
----

[[administration-syntax-database-management]]
== Database management command syntax

The database management commands are used to manage standard or composite databases.

=== Show databases

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax

| SHOW DATABASE
|
[source, syntax, role="noheader"]
----
SHOW { DATABASE[S] name \| DATABASE[S] \| DEFAULT DATABASE \| HOME DATABASE }
[WHERE expression]
----

[source, syntax, role="noheader"]
----
SHOW { DATABASE[S] name \| DATABASE[S] \| DEFAULT DATABASE \| HOME DATABASE }
YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]
[WHERE expression]
[RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----
|===

=== Create a database

[.tabbed-example]
=====
[role=include-with-cypher-5]
======
[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax
| CREATE DATABASE
|
[source, syntax, role="noheader"]
----
CREATE DATABASE name [IF NOT EXISTS]
[DEFAULT LANGUAGE CYPHER {5\|25}]
[TOPOLOGY n PRIMAR{Y\|IES} [m SECONDAR{Y\|IES}]]
[OPTIONS "{" option: value[, ...] "}"]
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----

[source, syntax, role="noheader"]
----
CREATE OR REPLACE DATABASE name
[DEFAULT LANGUAGE CYPHER {5\|25}]
[TOPOLOGY n PRIMAR{Y\|IES} [m SECONDAR{Y\|IES}]]
[OPTIONS "{" option: value[, ...] "}"]
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----
|===

[NOTE]
====
`[DEFAULT LANGUAGE CYPHER {5|25}]` is available from Neo4j 2025.06 onwards.
====
======

[role=include-with-cypher-25]
======

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax
| CREATE DATABASE
|
[source, syntax, role="noheader"]
----
CREATE DATABASE name [IF NOT EXISTS]
[[SET] DEFAULT LANGUAGE CYPHER {5\|25}]
[[SET] TOPOLOGY n PRIMAR{Y\|IES} [m SECONDAR{Y\|IES}]]
[OPTIONS "{" option: value[, ...] "}"]
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----

[source, syntax, role="noheader"]
----
CREATE OR REPLACE DATABASE name
[[SET] DEFAULT LANGUAGE CYPHER {5\|25}]
[[SET] TOPOLOGY n PRIMAR{Y\|IES} [m SECONDAR{Y\|IES}]]
[OPTIONS "{" option: value[, ...] "}"]
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----
|===

[NOTE]
====
`[[SET] DEFAULT LANGUAGE CYPHER {5|25}]` is available from Neo4j 2025.06 onwards. +
`[TOPOLOGY n PRIMAR{Y\|IES} [m SECONDAR{Y\|IES}]]` is replaced by `[[SET] TOPOLOGY n PRIMAR{Y\|IES} [m SECONDAR{Y\|IES}]]` in Cypher 25.
====
======
=====

=== Create a composite database

[.tabbed-example]
=====
[role=include-with-cypher-5]
======
[options="header", width="100%", cols="2m,4a"]
|===
| Command | Syntax

| CREATE COMPOSITE DATABASE
|
[source, synatx, role="noheader"]
----
CREATE COMPOSITE DATABASE name [IF NOT EXISTS]
[DEFAULT LANGUAGE CYPHER {5\|25}]
[OPTIONS "{" "}"]
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----

[source, syntax, role="noheader"]
----
CREATE OR REPLACE COMPOSITE DATABASE name
[DEFAULT LANGUAGE CYPHER {5\|25}]
[OPTIONS "{" "}"]
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----
|===

[NOTE]
====
`[DEFAULT LANGUAGE CYPHER {5|25}]` is available from Neo4j 2025.06 onwards.
====
======

[role=include-with-cypher-25]
======
[options="header", width="100%", cols="2m,4a"]
|===
| Command | Syntax

| CREATE COMPOSITE DATABASE
|
[source, synatx, role="noheader"]
----
CREATE COMPOSITE DATABASE name [IF NOT EXISTS]
[[SET] DEFAULT LANGUAGE CYPHER {5\|25}]
[OPTIONS "{" "}"]
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----

[source, syntax, role="noheader"]
----
CREATE OR REPLACE COMPOSITE DATABASE name
[[SET] DEFAULT LANGUAGE CYPHER {5\|25}]
[OPTIONS "{" "}"]
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----
|===

[NOTE]
====
`[[SET] DEFAULT LANGUAGE CYPHER {5|25}]` is available from Neo4j 2025.06 onwards.
====
======
=====

[role=label--new-2025.12 label-cypher-25]
[[create-sharded-property-database]]
=== Create a sharded property database

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax

| CREATE DATABASE
|
[source, syntax, role="noheader"]
----
CREATE DATABASE name [IF NOT EXISTS]
[[SET] DEFAULT LANGUAGE CYPHER {5\|25}]
[[SET] GRAPH SHARD {
  [TOPOLOGY n PRIMAR{Y\|IES} [m SECONDAR{Y\|IES}]]
}]
[SET] PROPERTY SHARD[S] {
  COUNT n [TOPOLOGY m REPLICA[S]]
}
[OPTIONS "{" option: value[, ...] "}"]
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----
|===

When creating a sharded property database, the following are created:

* A virtual sharded property database `<name>`.
* A single graph shard with the name `<name>-g000`.
* A number of property shards with the name `<name>-p000<index>`.
The count property in `SET PROPERTY SHARDS` specifies the number of property shards.

[NOTE]
====
The `CREATE DATABASE` command for sharded property databases supports only the `seedURI` option.
See xref:scalability/sharded-property-databases/creating-sharded-databases.adoc#create-sharded-property-database-options[Creating sharded property databases] for details.

`CREATE OR REPLACE` does not replace an existing sharded property database.
====


=== Alter a database

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax

| ALTER DATABASE
|
[source, syntax, role="noheader"]
----
ALTER DATABASE name [IF EXISTS]
{
SET ACCESS {READ ONLY \| READ WRITE} \|
SET TOPOLOGY n PRIMAR{Y\|IES} [m SECONDAR{Y\|IES}] \|
SET OPTION option value \|
SET DEFAULT LANGUAGE CYPHER {5\|25}
}
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----

[source, syntax, role="noheader"]
----
ALTER DATABASE name [IF EXISTS]
REMOVE OPTION option
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----
|===


[NOTE]
====
There can be multiple `SET OPTION` or `REMOVE OPTION` clauses for different option keys.

`SET DEFAULT LANGUAGE CYPHER {5|25}` is available from Neo4j 2025.06 onwards.
====

[role=label--new-2025.06]
=== Alter a composite database


[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax
| ALTER DATABASE
|
[source, syntax, role="noheader"]
----
ALTER DATABASE name [IF EXISTS]
SET DEFAULT LANGUAGE CYPHER {5\|25}
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----
|===

[role=label--new-2025.12 label-cypher-25]
[[alter-sharded-property-database]]
=== Alter a sharded property database

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax

| ALTER DATABASE <name>
|
[source, syntax, role="noheader"]
----
ALTER DATABASE name [IF EXISTS]
{
  SET ACCESS {READ ONLY \| READ WRITE} \|
  SET OPTION option value \|
  SET DEFAULT LANGUAGE CYPHER {5\|25} \|
  SET GRAPH SHARD {
    SET TOPOLOGY ((n PRIMAR{Y\|IES}) \| (m SECONDAR{Y\|IES}))+
  } \|
  SET PROPERTY SHARD[S] {
    SET TOPOLOGY n REPLICA[S]
  }
}
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----

| ALTER DATABASE <graph-shard>
|
[source, syntax, role="noheader"]
----
ALTER DATABASE name [IF EXISTS]
SET TOPOLOGY (
  (n PRIMAR{Y\|IES}) \|
  (m SECONDAR{Y\|IES})
)
[WAIT [n [SEC[OND[S]]]] \| NOWAIT]
----

| ALTER DATABASE <property-shard>
|
[source, syntax, role="noheader"]
----
ALTER DATABASE name [IF EXISTS]
SET TOPOLOGY (
  n REPLICA[S]
)
[WAIT [n [SEC[OND[S]]]] \| NOWAIT]
----

|===

=== Stop a database

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax

| STOP DATABASE
|
[source, syntax, role="noheader"]
----
STOP DATABASE name [WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----
|===

=== Start a database

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax

| START DATABASE
|
[source, syntax, role="noheader"]
----
START DATABASE name [WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----
|===

=== Delete a database

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax

| DROP DATABASE
|
[source, syntax, role="noheader"]
----
DROP [COMPOSITE] DATABASE name [IF EXISTS] [RESTRICT \| CASCADE ALIAS[ES]] [{DUMP\|DESTROY} [DATA]] [WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----

|===

[[administration-syntax-database-alias-management]]
== Database alias management command syntax

The database alias management commands are used to manage local or remote database aliases.

=== Show aliases

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax
| SHOW ALIAS
|
[source, syntax, role=noheader]
-----
SHOW ALIAS[ES] [name] FOR DATABASE[S]
[WHERE expression]
-----
[source, syntax, role=noheader]
-----
SHOW ALIAS[ES] [name] FOR DATABASE[S]
YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]
[WHERE expression]
[RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
-----
Lists both local and remote database aliases, optionally filtered on the alias name.
|===

=== Create a local alias

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax

| CREATE ALIAS
|
[source, syntax, role=noheader]
-----
CREATE ALIAS name [IF NOT EXISTS] FOR DATABASE targetName
[PROPERTIES "{" key: value[, ...] "}"]
-----
[source, syntax, role=noheader]
-----
CREATE OR REPLACE ALIAS name FOR DATABASE targetName
[PROPERTIES "{" key: value[, ...] "}"]
-----
|===

=== Create a remote alias

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax

| CREATE ALIAS
|
[source, syntax, role=noheader]
-----
CREATE ALIAS name [IF NOT EXISTS] FOR DATABASE targetName
AT 'url' USER username PASSWORD 'password'
[DRIVER "{" setting: value[, ...] "}"]
[DEFAULT LANGUAGE CYPHER {5\|25}]
[PROPERTIES "{" key: value[, ...] "}"]
-----
[source, syntax, role=noheader]
-----
CREATE OR REPLACE ALIAS name FOR DATABASE targetName
AT 'url' USER username PASSWORD 'password'
[DRIVER "{" setting: value[, ...] "}"]
[DEFAULT LANGUAGE CYPHER {5\|25}]
[PROPERTIES "{" key: value[, ...] "}"]
-----
|===

[NOTE]
====
`[DEFAULT LANGUAGE CYPHER {5|25}]` is available from Neo4j 2025.06 onwards.
====

=== Alter a local alias

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax

|ALTER ALIAS
|
[source, syntax, role=noheader]
-----
ALTER ALIAS name [IF EXISTS] SET DATABASE
[TARGET targetName]
[PROPERTIES "{" key: value[, ...] "}"]
-----
|===

=== Alter a remote alias

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax
|ALTER ALIAS
|
[source, syntax, role=noheader]
-----
ALTER ALIAS name [IF EXISTS] SET DATABASE
[TARGET targetName AT 'url']
[USER username]
[PASSWORD 'password']
[DRIVER "{" setting: value[, ...] "}"]
[DEFAULT LANGUAGE CYPHER {5\|25}]
[PROPERTIES "{" key: value[, ...] "}"]
-----
|===

[NOTE]
====
`[DEFAULT LANGUAGE CYPHER {5|25}]` is available from Neo4j 2025.06 onwards.
====

=== Delete an alias

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax

| DROP ALIAS
|
[source, syntax, role=noheader]
-----
DROP ALIAS name [IF EXISTS] FOR DATABASE
-----
Drop either a local or remote database alias.

|===