:description: This page provides the syntax for the Cypher administration commands.
[[administration-syntax]]
= Cypher syntax for administration commands

Almost all administration commands have variations.
The most common are parts of the command that are optional or that can have multiple values.

See below a summary of the syntax used to describe all versions of a command.
These summaries use some special characters to indicate such variations.

[[administration-syntax-reading]]
== Reading the administration commands syntax

.Special characters in syntax summaries
[options="header", width="100%", cols="1a,3a,3a"]
|===
| Character | Meaning | Example

| `\|`
|
Used to indicate alternative parts of a command (i.e. `or`).
Needs to be part of a grouping.
| If the syntax needs to specify either a name or `+*+`, this can be indicated with `+* \| name+`.

| `+{+` and `+}+`
| Used to group parts of the command. Commonly found together with `\|`.
| In order to use the `or` in the syntax summary, it needs to be in a group: `+{* \| name}+`.

| `[` and `]`
| Used to indicate an optional part of the command.
It also groups alternatives together, when there can be either of the alternatives or nothing.
| If a keyword in the syntax can either be in singular or plural, we can indicate that the `S` is optional with `GRAPH[S]`.

| `+...+`
|
Repeated pattern.
Related to the command part immediately before this is repeated.
| A comma separated list of names would be `+name[, ...]+`.

| `"`
| When a special character is part of the syntax itself, we surround it with `"` to indicate this.
|
To include `+{+` in the syntax use `+"{" { * \| name } "}"+`.
In this case, you will get either `+{ * }+` or `+{ name }+`.

|===

The special characters in the table above are the only ones that need to be escaped using `"` in the syntax summaries.

Here is an example that uses all the special characters. It grants the `READ` privilege:

[source, syntax, role="noheader"]
----
GRANT READ
  "{" { * | property[, ...] } "}"
  ON {HOME GRAPH | GRAPH[S] { * | name[, ...] }}
    [ ELEMENT[S] { * | label-or-rel-type[, ...] }
    | NODE[S] { * | label[, ...] }
    | RELATIONSHIP[S] { * | rel-type[, ...] }]
  TO role[, ...]
----

Note that this command includes `+{+` and `+}+` in the syntax, and between them there can be a grouping of properties or the character `+*+`.
It also has multiple optional parts, including the entity part of the command which is the grouping following the graph name.

However, there is no need to escape any characters when creating a constraint for a node property.
This is because `(` and `)` are not special characters, and `[` and `]` indicate that the constraint name and the `IF NOT EXISTS` parts are optional, and therefore not part of the command.

[source, syntax, role="noheader"]
----
CREATE CONSTRAINT [constraint_name] [IF NOT EXISTS]
FOR (n:LabelName)
REQUIRE n.propertyName IS NOT NULL
----

[[administration-syntax-database-management]]
== Database management command syntax

The below table covers both standard and composite databases.

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax

| SHOW DATABASE
|
[source, syntax, role="noheader"]
----
SHOW { DATABASE[S] name \| DATABASE[S] \| DEFAULT DATABASE \| HOME DATABASE }
[WHERE expression]
----

[source, syntax, role="noheader"]
----
SHOW { DATABASE[S] name \| DATABASE[S] \| DEFAULT DATABASE \| HOME DATABASE }
YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]
[WHERE expression]
[RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
----

| CREATE DATABASE
|
[source, syntax, role="noheader"]
----
CREATE DATABASE name [IF NOT EXISTS]
[TOPOLOGY n PRIMAR{Y\|IES} [m SECONDAR{Y\|IES}]]
[OPTIONS "{" option: value[, ...] "}"]
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----

[source, syntax, role="noheader"]
----
CREATE OR REPLACE DATABASE name
[TOPOLOGY n PRIMAR{Y\|IES} [m SECONDAR{Y\|IES}]]
[OPTIONS "{" option: value[, ...] "}"]
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----

| CREATE COMPOSITE DATABASE
|
[source, synatx, role="noheader"]
----
CREATE COMPOSITE DATABASE name [IF NOT EXISTS]
[OPTIONS "{" "}"]
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----

[source, syntax, role="noheader"]
----
CREATE OR REPLACE COMPOSITE DATABASE name
[OPTIONS "{" "}"]
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----

| ALTER DATABASE
|
[source, syntax, role="noheader"]
----
ALTER DATABASE name [IF EXISTS]
{
SET ACCESS {READ ONLY \| READ WRITE} \|
SET TOPOLOGY n PRIMAR{Y\|IES} [m SECONDAR{Y\|IES}] \|
SET OPTION option value
}
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----

[source, syntax]
----
ALTER DATABASE name [IF EXISTS]
REMOVE OPTION option
[WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----

[NOTE]
====
There can be multiple `SET OPTION` or `REMOVE OPTION` clauses for different option keys.
====


| STOP DATABASE
|
[source, syntax, role="noheader"]
----
STOP DATABASE name [WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----

| START DATABASE
|
[source, syntax, role="noheader"]
----
START DATABASE name [WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----

| DROP DATABASE
|
[source, syntax, role="noheader"]
----
DROP [COMPOSITE] DATABASE name [IF EXISTS] [RESTRICT \| CASCADE ALIAS[ES]] [{DUMP\|DESTROY} [DATA]] [WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----

|===

[[administration-syntax-database-alias-management]]
== Database alias management command syntax

[options="header", width="100%", cols="1,5a"]
|===
| Command | Syntax
| Show Database Alias
|
[source, syntax, role=noheader]
-----
SHOW ALIAS[ES] [name] FOR DATABASE[S]
[WHERE expression]
-----
[source, syntax, role=noheader]
-----
SHOW ALIAS[ES] [name] FOR DATABASE[S]
YIELD { * \| field[, ...] } [ORDER BY field[, ...]] [SKIP n] [LIMIT n]
[WHERE expression]
[RETURN field[, ...] [ORDER BY field[, ...]] [SKIP n] [LIMIT n]]
-----
Lists both local and remote database aliases, optionally filtered on the alias name.

| Create Local Alias
|
[source, syntax, role=noheader]
-----
CREATE ALIAS name [IF NOT EXISTS] FOR DATABASE targetName
[PROPERTIES "{" key: value[, ...] "}"]
-----
[source, syntax, role=noheader]
-----
CREATE OR REPLACE ALIAS name FOR DATABASE targetName
[PROPERTIES "{" key: value[, ...] "}"]
-----

| Create Remote Alias
|
[source, syntax, role=noheader]
-----
CREATE ALIAS name [IF NOT EXISTS] FOR DATABASE targetName
AT 'url' USER username PASSWORD 'password'
[DRIVER "{" setting: value[, ...] "}"]
[PROPERTIES "{" key: value[, ...] "}"]
-----
[source, syntax, role=noheader]
-----
CREATE OR REPLACE ALIAS name FOR DATABASE targetName
AT 'url' USER username PASSWORD 'password'
[DRIVER "{" setting: value[, ...] "}"]
[PROPERTIES "{" key: value[, ...] "}"]
-----

| Alter Local Alias
|
[source, syntax, role=noheader]
-----
ALTER ALIAS name [IF EXISTS] SET DATABASE
[TARGET targetName]
[PROPERTIES "{" key: value[, ...] "}"]
-----

| Alter Remote Alias
|
[source, syntax, role=noheader]
-----
ALTER ALIAS name [IF EXISTS] SET DATABASE
[TARGET targetName AT 'url']
[USER username]
[PASSWORD 'password']
[DRIVER "{" setting: value[, ...] "}"]
[PROPERTIES "{" key: value[, ...] "}"]
-----

| Drop Alias
|
[source, syntax, role=noheader]
-----
DROP ALIAS name [IF EXISTS] FOR DATABASE
-----
Drop either a local or remote database alias.

|===