:description: This page describes the relevant configuration parameters for managing databases with Neo4j.
:page-aliases: manage-databases/configuration.adoc
[[manage-databases-parameters]]
= Configuration parameters

Configuration parameters are defined in the xref:configuration/neo4j-conf.adoc[neo4j.conf] file.

The following configuration parameters are applicable for managing databases:

[options="header", cols="40,60a"]
|===
| Parameter name
| Description

| xref:configuration/configuration-settings.adoc#config_initial.dbms.default_database[`initial.dbms.default_database`]
a|
Name of the default database for the Neo4j instance.
The database is created if it does not exist when the instance starts.

*Default value:* `neo4j`

[NOTE]
====
In a clustered setup, the value of `initial.dbms.default_database` is only used to set the initial default database.
To change the default database at a later point, see xref:clustering/databases.adoc#cluster-default-database[Change the default database].
====

[NOTE]
====
Be aware that the automatically created _initial_ default database may have a different topology to the default configuration values.
See xref:clustering/databases.adoc#cluster-default-database[Default database in a cluster] for more information.
====

| xref:configuration/configuration-settings.adoc#config_dbms.max_databases[`dbms.max_databases`]
a|
Maximum number of databases that can be used in a Neo4j single instance or cluster.
The number includes all the online and offline databases.
The value is an integer with a minimum value of 2.
label:enterprise-edition[]

*Default value:* `100`

[NOTE]
====
Once the limit has been reached, it is not possible to create any additional databases.
Similarly, if the limit is changed to a number lower than the total number of existing databases, no additional databases can be created.
====

| xref:configuration/configuration-settings.adoc#config_server.databases.default_to_read_only[`server.databases.default_to_read_only`]
a|
Default mode of all databases.
If this setting is set to `true` all existing and new databases will be in read only mode, and so will prevent write queries.

*Default value:* `false`

| xref:configuration/configuration-settings.adoc#config_server.databases.read_only[`server.databases.read_only`]
a|
List of database names for which to prevent write queries.
This set can contain also not yet existing databases, but not the `system` database.

[NOTE]
====
Regardless of settings of `server.databases.default_to_read_only`, `server.databases.read_only` and `server.databases.writable` the `system` database will never be read-only and will always accept write queries.
====

[NOTE]
====
Another way of preventing writes is to set the database access to read-only using the xref:database-administration/standard-databases/alter-databases.adoc#manage-databases-alter[ALTER DATABASE] command.
====


Example configuration:
[source, example, role="noheader"]
----
server.databases.read_only=["foo", "bar"]
----

| xref:configuration/configuration-settings.adoc#config_server.databases.writable[`server.databases.writable`]
a|
List of database names for which to accept write queries.
This set can contain also not yet existing databases. +
The value of this setting is ignored if `server.databases.default_to_read_only` is set to `false`. +
If a database name is present in both sets, the database will be read-only and prevent write queries.

[[config-param-note-3]]
[TIP]
====
If most of your databases would read-only with a few exceptions, it can be easier to set `server.databases.default_to_read_only` to `true`, and then put the names of the non read-only databases into `server.databases.writable`.
====

Example configuration:
[source, example, role="noheader"]
----
server.databases.writable=["foo", "bar"]
----
|===

[NOTE]
====
Although it is possible to achieve the same goal, i.e. set a database to read-only, both by using the Cypher command `ALTER DATABASE` and by using configuration parameters in `neo4j.conf`, it is important to understand the difference between the two.
`ALTER DATABASE foo SET ACCESS READ ONLY` effectively sets the database `foo` to read-only _across the entire DBMS_.

Using configuration parameters is more subtle and allows you to configure access on each instance separately, in case of a cluster for example.
If you use `server.databases.default_to_read_only` _all databases on that instance_ are set to read-only.

If both the Cypher command and the configuration parameters are used and they contain conflicting information, the database in question is set to read-only.
====
