:description: how to delete databases in Neo4j.
[role=enterprise-edition not-on-aura]
[[manage-databases-delete]]
= Delete databases

Databases can be deleted by using the command `DROP DATABASE`.
Note that all database aliases must be dropped before dropping a database.

[[drop-database-syntax]]
== Syntax

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax

| DROP DATABASE
|
[source, syntax, role="noheader"]
----
DROP [COMPOSITE] DATABASE name [IF EXISTS] [{DUMP\|DESTROY} [DATA]] [WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----

|===

== Examples

=== Delete a database

To delete the database `customers`, run the following command:

[source, cypher]
----
DROP DATABASE customers
----

[NOTE]
====
Both standard databases and composite databases can be deleted using this command.
====

The `DROP DATABASE` command removes a database entirely.
Therefore, it no longer shows up in the listing provided by the command `SHOW DATABASES`:

[source, cypher]
----
SHOW DATABASES YIELD name
----

.Result
[role="queryresult]
----
+---------------------+
| name                |
+---------------------+
| "movies"            |
| "neo4j"             |
| "system"            |
+---------------------+
----


[[delete-databases-existing]]
=== Delete a database with `IF EXISTS`

The `DROP DATABASE` command is optionally idempotent, with the default behavior to fail with an error if the database does not exist.
Appending `IF EXISTS` to the command ensures that no error is returned and nothing happens should the database not exist.
It always returns an error if there is an existing alias that targets the database.
In that case, the alias needs to be dropped before dropping the database.

[source, cypher]
----
DROP DATABASE customers IF EXISTS
----

[[manage-databases-dump]]
=== Delete a database with `DUMP DATA` or `DESTROY DATA`

You can request a dump of the store files to be created first and stored in the directory specified by the xref:configuration/configuration-settings.adoc#config_server.directories.dumps.root[`server.directories.dumps.root`] setting (by default, the path is xref:configuration/file-locations.adoc#data[`<neo4j-home>/data/dumps`]).

This can be achieved by appending `DUMP DATA` to the command (or `DESTROY DATA` to explicitly request the default behavior).
These dumps are equivalent to those produced by xref:backup-restore/offline-backup.adoc[`neo4j-admin database dump`] and can be similarly restored using xref:backup-restore/restore-dump.adoc[`neo4j-admin database load`].

////
[source, cypher, role=test-setup]
----
DROP ALIAS `films` FOR DATABASE;
DROP ALIAS `motion pictures` FOR DATABASE;
----
////


[source, cypher]
----
DROP DATABASE movies DUMP DATA
----

[[delete-existing-db-with-dump]]
=== Delete a database with `IF EXISTS` and  `DUMP DATA`/ `DESTROY DATA`

The options `IF EXISTS` and  `DUMP DATA`/ `DESTROY DATA` can also be combined.

An example could look like this:

[source, cypher]
----
DROP DATABASE customers IF EXISTS DUMP DATA
----


