:description: how to delete databases in Neo4j.
[role=enterprise-edition not-on-aura]
[[manage-databases-delete]]
= Delete databases

Databases can be deleted by using the command `DROP DATABASE`.
Note that all database aliases must be dropped before dropping a database.

[[drop-database-syntax]]
== Syntax

[options="header", width="100%", cols="1m,5a"]
|===
| Command | Syntax

| DROP DATABASE
|
[source, syntax, role="noheader"]
----
DROP [COMPOSITE] DATABASE name [IF EXISTS] [RESTRICT \| CASCADE ALIAS[ES]] [{DUMP\|DESTROY} [DATA]] [WAIT [n [SEC[OND[S]]]]\|NOWAIT]
----

|===

== Examples

[[delete-database]]
=== Delete a database

To delete the database `customers`, run the following command:

[source, cypher]
----
DROP DATABASE customers
----

[NOTE]
====
Both standard databases and composite databases can be deleted using this command.
====

The `DROP DATABASE` command removes a database entirely.
Therefore, it no longer shows up in the listing provided by the command `SHOW DATABASES`:

[source, cypher]
----
SHOW DATABASES YIELD name
----

.Result
[role="queryresult]
----
+---------------------+
| name                |
+---------------------+
| "movies"            |
| "neo4j"             |
| "system"            |
+---------------------+
----


[[delete-databases-existing]]
=== Delete a database with `IF{nbsp}EXISTS`

The `DROP DATABASE` command is optionally idempotent, with the default behavior to fail with an error if the database does not exist.

Appending `IF EXISTS` to the command ensures that no error is returned and nothing happens if the database does not exist.

It always returns an error if there is an existing alias that targets the database.
In that case, the alias needs to be dropped before dropping the database.

[source, cypher]
----
DROP DATABASE customers IF EXISTS
----

[[manage-databases-dump]]
=== Delete a database with `DUMP DATA` or `DESTROY DATA`

By appending `DUMP DATA` to the command `DROP DATABASE`, you can create a dump of the store files before deleting the database:

[source, cypher]
----
DROP DATABASE movies DUMP DATA
----

These dumps are equivalent to those produced by xref:backup-restore/offline-backup.adoc[`neo4j-admin database dump`] and can be similarly restored using the xref:backup-restore/restore-dump.adoc[`neo4j-admin database load`] command.

In Neo4j, dumps can be stored in the directory specified by the xref:configuration/configuration-settings.adoc#config_server.directories.dumps.root[`server.directories.dumps.root`] setting (by default, the path for storing dumps is xref:configuration/file-locations.adoc#data[`<neo4j-home>/data/dumps`]).

The option `DESTROY DATA` explicitly requests the default behavior of the command.

[[delete-existing-db-with-dump]]
=== Delete a database with `IF{nbsp}EXISTS` and  `DUMP DATA`/`DESTROY DATA`

The options `IF EXISTS` and `DUMP DATA`/`DESTROY DATA` can also be combined.

An example could look like this:

[source, cypher]
----
DROP DATABASE customers IF EXISTS DUMP DATA
----

[[delete-databases-with-aliases]]
=== Delete a database with local database aliases targeting it

In general, deleting a database that is the target of any local database aliases will fail due as these aliases need to be dropped first.
Remote database aliases targeting the database do not affect the deletion of the database.

By appending `CASCADE ALIASES` to the command `DROP DATABASE`, those local database aliases can be dropped alongside the database.
Any remote database aliases targeting the database will not be affected of the `CASCADE ALIASES`, they will simply no longer resolve their targets (which is the same behavior as if they are created targeting a non-existing database).
However, the behavior does not cascade further, if any of the dropped database aliases are constituents to any composite database, those composite databases are not dropped.

Using `CASCADE ALIASES` requires the `DROP ALIAS` privilege (see xref:authentication-authorization/dbms-administration.adoc#access-control-dbms-administration-alias-management[ALIAS MANAGEMENT privileges]).

Given database and database alias:
[source, cypher]
----
CREATE DATABASE movies
CREATE ALIAS films FOR DATABASE movies
----

Then both the database alias `films` and the database `movies` will be dropped with:
[source, cypher]
----
DROP DATABASE movies CASCADE ALIASES
----

The option `RESTRICT` explicitly requests the default behavior of the command.

[NOTE]
====
For standard databases, the aliases that will be dropped when using the `CASCADE ALIASES` option can be found in the `aliases` column of `SHOW DATABASE`.
====

[[delete-existing-databases-with-aliases]]
=== Delete a database with `RESTRICT`/`CASCADE ALIASES` and other command parts

The options `RESTRICT`/`CASCADE ALIASES` can also be combined with `IF EXISTS` and `DUMP DATA`/`DESTROY DATA`.

An example could look like this:

[source, cypher]
----
DROP DATABASE movies IF EXISTS CASCADE ALIASES DUMP DATA
----

