:description: This chapter describes the `neo4j-admin database migrate` command.
:page-aliases: tools/neo4j-admin/migrate-database.adoc
[[neo4j-admin-migrate]]
= Migrate a database

You can use the `neo4j-admin database migrate` command to migrate a Neo4j database from one store format to another or to a later `MAJOR` version of the same format.

A store format defines how the data of a database is stored on the file system.

The store format of a database is versioned with the `MAJOR.MINOR` scheme, independent of the xref:introduction.adoc#versioning[Neo4j calendar versioning].
An upgrade to the latest `MINOR` format version is an automatic operation performed on database startup.
A migration to a higher `MAJOR` format version or another format is a manual action performed with the `migrate` command.

The store format for new databases can be set with the xref:configuration/configuration-settings.adoc#config_db.format[`db.format`] configuration setting.

The table below shows supported migration paths between different Neo4j store formats.
However, the `standard` and `high_limit` store formats are deprecated starting with Neo4j 5.23, meaning that migration to these formats is not recommended from this version onward.

[[supported-migration-paths]]
.Migration paths between Neo4j store formats
[options="noheader"]
|===
.2+.>|*Store format*              4+^|*Migration paths*
                                   ^|To `block`  ^|To `aligned`  ^|To `high_limit`  ^|To `standard`

|`block` footnote:1[The `block` format is the default in Enterprise Edition starting from Neo4j 5.22.]     |  |{check-mark} Not recommended  |{check-mark} Not recommended |  

|`aligned` footnote:2[The `aligned` format is the default in Community Edition. In Enterprise Edition, it was default before Neo4j 5.22.]     ^|{check-mark}                |                             |{check-mark} Not recommended | 

|`high_limit` footnote:3[label:enterprise[Enterprise Edition] The `high_limit` format is deprecated in 5.23.]  ^|{check-mark} |  |  |  

|`standard` footnote:4[label:community[Community Edition] The `standard` format is deprecated in 5.23.]    ^|{check-mark} ^|{check-mark} |{check-mark} Not recommended | 
|===

Before migrating from `block` to the `aligned` format, you have to ensure that your graph fits in the `aligned` since the `block` format has higher limits. 
For details, see xref:database-internals/store-formats.adoc#store-formats-entity-limits[Database internals and transactional behavior -> Store formats].

== Syntax

The `neo4j-admin database  migrate` has the following syntax:

----
neo4j-admin database migrate [-h] [--expand-commands]
                             [--force-btree-indexes-to-range]
                             [--verbose] [--additional-config=<file>]
                             [--max-off-heap-memory=<size>] [--pagecache=<size>]
                             [--to-format=standard|high_limit|aligned|block] <database>
----

[NOTE]
====
The `neo4j-admin database migrate` command is run only on a stopped database.
====

=== Parameters

.`neo4j-admin database migrate` parameters
[options="header", cols="1m,3a"]
|===
| Parameter
| Description

|<database>
|Name of the database to migrate. Can contain * and ? for globbing. Note that * and ? have special meaning in some shells and might need to be escaped or used with quotes.
|===

=== Options

The `neo4j-admin database migrate` command has the following options:

.`neo4j-admin database migrate` options
[options="header", cols="5m,6a,1m"]
|===
| Option
| Description
| Default

|--additional-config=<file>footnote:[See xref:neo4j-admin-neo4j-cli.adoc#_configuration[Neo4j Admin and Neo4j CLI -> Configuration] for details.]
|Configuration file with additional configuration.
|

|--expand-commands
|Allow command expansion in config value evaluation.
|

|--force-btree-indexes-to-range
|Special option for automatically turning all BTREE indexes/constraints into RANGE. Be aware that RANGE indexes are not always the optimal replacement of BTREEs and performance may be affected while the new indexes are populated.
See the Neo4j v5 migration guide online for more information.
The newly created indexes will be populated in the background on the first database start up following the migration and users should monitor the successful completion of that process.
[NOTE]
This option is only relevant when migrating from Neo4j 4.4.
|

|-h, --help
|Show this help message and exit.
|

|--max-off-heap-memory=<size> label:new[Introduced in Neo4j 2025.04]
|Maximum memory that the command can use for page cache and various caching data structures to improve performance.
Values can be plain numbers, such as 10000000, or, for example, 20G for 20 gigabytes, or 70%, which will amount to 70% of currently free memory on the machine.
|90%

|--pagecache=<size> label:deprecated[Deprecated in Neo4j 2025.04]
|The size of the page cache to use for the migration process. The general rule is that values up to the size of the database proportionally increase performance.
|

|--to-format=standard\|high_limit\|aligned\|block
|Name of the format to migrate the store to.
If the format is specified, the target database is migrated to the latest known combination of `MAJOR` and `MINOR` versions of the specified format.
If not specified, the tool migrates the target database to the latest known combination of `MAJOR` and `MINOR` versions of the current format.
|

|--verbose
|Enable verbose output.
|
|===

[NOTE]
====
The block format is the default format for all databases in Enterprise Edition as long as they do not have the xref:configuration/configuration-settings.adoc#config_db.format[`db.format`] setting specified.
For more information on the block format, see xref:database-internals/store-formats.adoc[Store formats].
====

== Example

The following example migrates the `movies` database to the latest known combination of `MAJOR` and `MINOR` versions of the `block` format:

[source, shell, subs="attributes+"]
----
bin/neo4j-admin database migrate --to-format=block movies
----

.Example output
[source, shell, subs="attributes+"]
----
2025-01-22 18:03:21.842+0000 INFO  [c.n.c.d.EnterpriseMigrateStoreCommand] Starting migration for database 'movies'
2025-01-22 18:03:22.504+0000 INFO  [o.n.k.i.s.StoreMigrator] 'record-aligned-1.1' has been identified as the current version of the store
2025-01-22 18:03:22.504+0000 INFO  [o.n.k.i.s.StoreMigrator] 'block-block-1.1' has been identified as the target version of the store migration
2025-01-22 18:03:22.506+0000 INFO  [o.n.k.i.s.StoreMigrator] Starting migration of database
2025-01-22 18:03:22.586+0000 INFO  [o.n.k.i.s.StoreMigrator] Migrating Store files (1/1):
2025-01-22 18:03:22.588+0000 INFO  [o.n.k.i.s.StoreMigrator] Store files
2025-01-22 18:03:23.270+0000 INFO  [c.n.i.b.i.BlockBatchImporter] Import completed successfully, took 654ms.
2025-01-22 18:03:23.708+0000 INFO  [o.n.k.i.s.StoreMigrator]  10% completed
2025-01-22 18:03:23.708+0000 INFO  [o.n.k.i.s.StoreMigrator]  20% completed
2025-01-22 18:03:23.708+0000 INFO  [o.n.k.i.s.StoreMigrator]  30% completed
2025-01-22 18:03:23.708+0000 INFO  [o.n.k.i.s.StoreMigrator]  40% completed
2025-01-22 18:03:23.709+0000 INFO  [o.n.k.i.s.StoreMigrator]  50% completed
2025-01-22 18:03:23.709+0000 INFO  [o.n.k.i.s.StoreMigrator]  60% completed
2025-01-22 18:03:23.709+0000 INFO  [o.n.k.i.s.StoreMigrator]  70% completed
2025-01-22 18:03:23.709+0000 INFO  [o.n.k.i.s.StoreMigrator]  80% completed
2025-01-22 18:03:23.709+0000 INFO  [o.n.k.i.s.StoreMigrator]  90% completed
2025-01-22 18:03:23.709+0000 INFO  [o.n.k.i.s.StoreMigrator] 100% completed
2025-01-22 18:03:23.761+0000 INFO  [o.n.k.i.s.StoreMigrator] Starting transaction logs migration.
2025-01-22 18:03:23.800+0000 INFO  [o.n.k.i.s.StoreMigrator] Transaction logs migration completed.
2025-01-22 18:03:23.802+0000 INFO  [o.n.k.i.s.StoreMigrator] Successfully finished migration of database, took 1s 296ms
2025-01-22 18:03:23.804+0000 INFO  [c.n.c.d.EnterpriseMigrateStoreCommand] Database migration completed successfully
----
