:page-role: enterprise-edition
:description: How to create a database using a seed from URI.

[[database-seed-uri]]
= Create a database from a URI

This method seeds all databases with an identical seed from an external source, specified by a URI.

You specify the seed URI as an argument of the `CREATE DATABASE` command:

[source, cypher, role="noplay"]
----
CREATE DATABASE foo OPTIONS {existingData: 'use', seedURI:'s3://myBucket/myBackup.backup'}
----

Download and validation of the seed is only performed as the new database is started.
If it fails, the database is not available and it has the `statusMessage`: `Unable to start database` of the `SHOW DATABASES` command.

[source, cypher, role="noplay"]
----
neo4j@neo4j> SHOW DATABASES;
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| name    | type       | aliases | access       | address          | role      | writer | requestedStatus | currentStatus | statusMessage                                            | default | home  | constituents |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "seed3" | "standard" | []      | "read-write" | "localhost:7682" | "unknown" | FALSE  | "online"        | "offline"     | "Unable to start database `DatabaseId{3fe1a59b[seed3]}`" | FALSE   | FALSE | []           |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
----

To determine the cause of the problem, it is recommended to look at the `debug.log`.


[[neo4j-seed-providers]]
== Seed providers in Neo4j

The seed can be a full backup, a differential backup (see <<cloud-seed-provider, `CloudSeedProvider`>>, starting from Neo4j 5.26), or a dump from an existing database.
When using `CloudSeedProvider`, the URI can point also to a folder which contains a backup chain.
The sources of seeds are called _seed providers_.

Backups have a `.backup` extension, while the dump file can have whatever extension the user chooses.
For example, the backup file can be called `myBackup.backup`, while the dump can be called `myDump.dump` or also `myBackup.backup`, or any other name.

The mechanism is pluggable, allowing new sources of seeds to be supported (see link:https://www.neo4j.com/docs/java-reference/5/extending-neo4j/project-setup/#extending-neo4j-plugin-seed-provider[Java Reference -> Implement custom seed providers] for more information).

The product has built-in support for seed from a mounted file system (file), FTP server, HTTP/HTTPS server, Amazon S3, Google Cloud Storage (from Neo4j 5.25), and Azure Cloud Storage (from Neo4j 5.25).

[NOTE]
====
Amazon S3 is supported by default.
Starting from Neo4j 5.26, the default support extends also to Google Cloud Storage and Azure Cloud Storage.

To enable other providers, you need to configure xref:configuration/configuration-settings.adoc#config_dbms.databases.seed_from_uri_providers[`dbms.databases.seed_from_uri_providers`].
====

[role=label--new-5.26]
[[file-seed-provider]]
=== FileSeedProvider

The `FileSeedProvider`  supports:

** `file:`

[[url-connection-seed-provider]]
=== URLConnectionSeedProvider

The `URLConnectionSeedProvider` supports the following:

** `file:` label:deprecated[Deprecated in 5.26]
** `ftp:`
** `http:`
** `https:`

[role=label--new-5.25]
[[cloud-seed-provider]]
=== CloudSeedProvider

The `CloudSeedProvider` supports:

** `s3:`
** `gs:`
** `azb:`

Starting from Neo4j 5.26, the `CloudSeedProvider` supports using xref:backup-restore/modes.adoc#differential-backup[differential backup] files as seeds.
With the provided differential backup file, the `CloudSeedProvider` searches the directory containing differential backup files for a xref:backup-restore/online-backup.adoc#backup-chain[backup chain] ending at the specified differential backup, and then seeds using this backup chain.

[.tabbed-example]
=====
[role=include-with-AWS-S3 label--new-5.25]
======

include::partial$/aws-s3-overrides.adoc[]

include::partial$/aws-s3-credentials.adoc[]

. Create database from `myBackup.backup`.
This backup can be a full backup, a differential backup, or a dump file.
+
[source,shell, role="nocopy"]
----
CREATE DATABASE foo OPTIONS { existingData: 'use', seedURI: 's3://myBucket/myBackup.backup' }
----

======
[role=include-with-Google-cloud-storage label--new-5.25]
======

include::partial$/gcs-credentials.adoc[]

. Create database from `myBackup.backup`.
This backup can be a full backup, a differential backup, or a dump file.
+
[source,shell]
----
CREATE DATABASE foo OPTIONS { existingData: 'use', seedURI: 'gs://myBucket/myBackup.backup' }
----
======
[role=include-with-Azure-cloud-storage label--new-5.25]
======

include::partial$/azb-credentials.adoc[]

. Create database from `myBackup.backup`.
This backup can be a full backup, a differential backup, or a dump file.
+
[source,shell]
----
CREATE DATABASE foo OPTIONS { existingData: 'use', seedURI: 'azb://myStorageAccount/myContainer/myBackup.backup' }
----
======
=====


[[s3-seed-provider]]
=== S3SeedProvider

The `S3SeedProvider` supports:

** `s3:` label:deprecated[Deprecated in 5.26]


[NOTE]
====
Neo4j 5 comes bundled with necessary libraries for AWS S3 connectivity.
Therefore, if you use `S3SeedProvider`,`aws cli` is not required but can be used with the `CloudSeedProvider`.
====

The `S3SeedProvider` requires additional configuration.
This is specified with the `seedConfig` option.
This option expects a comma-separated list of configurations.
Each configuration value is specified as a name followed by `=` and the value, as such:

[source, cypher, role="noplay"]
----
CREATE DATABASE foo OPTIONS { existingData: 'use', seedURI: 's3://myBucket/myBackup.backup', seedConfig: 'region=eu-west-1' }
----

`S3SeedProvider` also requires passing in credentials.
These are specified with the `seedCredentials` option.
Seed credentials are securely passed from the Cypher command to each server hosting the database.
For this to work, Neo4j on each server in the cluster must be configured with identical keystores.
This is identical to the configuration required by remote aliases, see xref:database-administration/aliases/remote-database-alias-configuration.adoc#remote-alias-config-DBMS_admin-A[Configuration of DBMS with remote database alias].
If this configuration is not performed, the `seedCredentials` option fails.

[source, cypher, role="noplay"]
----
CREATE DATABASE foo OPTIONS { existingData: 'use', seedURI: 's3://myBucket/myBackup.backup', seedConfig: 'region=eu-west-1', seedCredentials: [accessKey];[secretKey] }
----
Where `accessKey` and `secretKey` are provided by AWS.

=== Seed provider reference

[cols="1,2,2",options="header"]
|===
| URL scheme
| Seed provider
| URI example

| `file:`
| `URLConnectionSeedProvider` label:deprecated[Deprecated in 5.26], +
`FileSeedProvider` label:new[Introduced in 5.26]
| `file:/tmp/backup1.backup`
 `file:/tmp/backup1.dump`

| `ftp:`
| `URLConnectionSeedProvider`
| `\ftp://myftp.com/backups/backup1.backup`
`\ftp://myftp.com/backups/backup1.dump`

| `http:`
| `URLConnectionSeedProvider`
| `\http://myhttp.com/backups/backup1.backup`
`\http://myhttp.com/backups/backup1.dump`

| `https:`
| `URLConnectionSeedProvider`
| `\https://myhttp.com/backups/backup1.backup`
`\https://myhttp.com/backups/backup1.dump`

| `s3:`
| `S3SeedProvider` label:deprecated[Deprecated in 5.26], +
`CloudSeedProvider` label:new[Introduced in 5.25]
| `s3://mybucket/backups/backup1.backup`
`s3://mybucket/backups/backup1.dump`
`s3://mybucket/backups/` (folder containing a backup chain, only used by `CloudSeedProvider`)

| `gs:`
| `CloudSeedProvider` label:new[Introduced in 5.25]
| `gs://mybucket/backups/backup1.backup`
`gs://mybucket/backups/backup1.dump`
`gs://mybucket/backups/` (folder containing a backup chain)

| `azb:`
| `CloudSeedProvider` label:new[Introduced in 5.25]
| `azb://mystorageaccount.blob/backupscontainer/backup1.backup`
`azb://mystorageaccount.blob/backupscontainer/backup1.dump`
`azb://mystorageaccount.blob/backupscontainer/` (folder containing a backup chain)
|===

