:page-role: enterprise-edition
:description: How to create a database using a seed from URI.

= Create a database from a URI

This method seeds all databases with an identical seed from an external source, specified by a URI.

You specify the seed URI as an argument of the `CREATE DATABASE` command:

[.tabbed-example]
=====
[role=include-with-Cypher-5]
======

[source, cypher5]
----
CREATE DATABASE foo OPTIONS { existingData: 'use', seedURI:'s3://myBucket/myBackup.backup' }
----

======
[role=include-with-Cypher-25 label--new-2025.06]
======

[source, cypher25]
----
CREATE DATABASE foo OPTIONS { seedURI:'s3://myBucket/myBackup.backup' }
----
======
=====

[NOTE]
====
The `existingData` option is required in Cypher 5 and deprecated in Cypher 25.
====

Download and validation of the seed is only performed as the new database is started.
If it fails, the database is not available and it has the `statusMessage`: `Unable to start database` of the `SHOW DATABASES` command.

.Example failure output for `SHOW DATABASES`
[source, role="queryresult"]
----
| name    | type       | aliases | access       | address          | role      | writer | requestedStatus | currentStatus | statusMessage                                            | default | home  | constituents |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "seed3" | "standard" | []      | "read-write" | "localhost:7682" | "unknown" | FALSE  | "online"        | "offline"     | "Unable to start database `DatabaseId{3fe1a59b[seed3]}`" | FALSE   | FALSE | []           |
----

To determine the cause of the problem, check the `debug.log` file.

[NOTE]
====
Starting from Neo4j 2025.01, seed from URI can also be used in combination with xref:database-administration/standard-databases/create-databases.adoc[`CREATE OR REPLACE DATABASE`].
====

[[neo4j-seed-providers]]
== Seed providers in Neo4j

The seed can be a full backup, a differential backup (see <<cloud-seed-provider, `CloudSeedProvider`>>), or a dump from an existing database.
When using `CloudSeedProvider`, the URI can point also to a folder which contains a backup chain.
The sources of seeds are called _seed providers_.

Backups have a `.backup` extension, while the dump file can have whatever extension the user chooses.
For example, the backup file can be called `myBackup.backup`, while the dump can be called `myDump.dump` or also `myBackup.backup`, or any other name.

The mechanism is pluggable, allowing new sources of seeds to be supported (see link:https://www.neo4j.com/docs/java-reference/current/extending-neo4j/project-setup/#extending-neo4j-plugin-seed-provider[Java Reference -> Implement custom seed providers] for more information).

The product has built-in support for seed from a mounted file system (file), FTP server, HTTP/HTTPS server, Amazon S3, Google Cloud Storage, and Azure Cloud Storage.

[NOTE]
====
Amazon S3, Google Cloud Storage, and Azure Cloud Storage are supported by default, but the other providers require configuration of xref:configuration/configuration-settings.adoc#config_dbms.databases.seed_from_uri_providers[`dbms.databases.seed_from_uri_providers`].
====


[role=label--new-2026.04]
[[server-seed-provider]]
=== ServerSeedProvider

The `ServerSeedProvider` supports:

** `server:` 

The `server://` scheme allows you to seed a database from a backup artifact located on a server in the cluster's file system.
This can be either a directory or a specific artifact within this directory.

Artifact(s) have to be placed in the seeds directory on a server, which is configured via the xref:configuration/configuration-settings.adoc#config_server.directories.seeds[`server.directories.seeds`] setting.

[IMPORTANT]
====
This seeding mechanism is intended only for database (re)creation.
It is not recommended to use production servers as long-term backup storage.
Backup artifacts placed in the seeds directory should be removed after the database has been (re)created.
====

The URI must identify:

* A server:
The URI begins with the server scheme and identifier: `server://<server-id-or-name>`. +
<server-id-or-name> can be the server ID or its human-readable name.
* An artifact (optional):
You can specify an artifact: `server://<server-id-or-name>/<artifact-name>`. +
`.backup` or `.dump` file types are supported.
For example, `server://server-id/foo-2026-01-01.backup`.

If no artifact is specified, the system automatically looks for the most recent backup chain with the target database name defined in the `CREATE DATABASE` part of the command.

If `seedSourceDatabase` is specified, then this value is used instead of the target database name.
See <<example-directory-seedSourceDatabase, Example 3>> for details.

`ServerSeedProvider` can also be used with the xref:database-administration/standard-databases/recreate-database.adoc#uri-seed[`dbms.recreateDatabase` procedure].


[[example-specific-artifact]]
Example 1: Using a specific artifact::
Create database `foo` from seed called `foo.backup` that exists in the seed directory on server `server-id`:
+
[.tabbed-example]
=====
[role=include-with-Cypher-5]
======

[source,cypher5]
----
CREATE DATABASE foo
OPTIONS { existingData: 'use', seedURI: 'server://server-id/foo.backup' };
----

======
[role=include-with-Cypher-25]
======

[source,cypher25]
----
CREATE DATABASE foo
OPTIONS { seedURI: 'server://server-id/foo.backup' };
----

======
=====
+
If `foo.backup` is a differential backup, the system attempts to find a valid backup chain in the seed directory and download this chain.
+
Dumps are also supported, e.g., `foo.dump`.


[[example-directory]]
Example 2: Using a directory::
Create database `foo` from the most recent backup chain found in the seed directory on the server `server-id`:
+
[.tabbed-example]
=====
[role=include-with-Cypher-5]
======

[source,cypher5]
----
CREATE DATABASE foo
OPTIONS { existingData: 'use', seedURI: 'server://server-id/' };
----

======
[role=include-with-Cypher-25]
======

[source,cypher25]
----
CREATE DATABASE foo
OPTIONS { seedURI: 'server://server-id/' };
----
======
=====
+
Fails if no valid backup chain can be found for `foo`.
+
Note that if a directory is specified, only backup chains are used.
To use a `.dump` file, you must reference it explicitly. 


[[example-directory-seedSourceDatabase]]
Example 3: Using a directory and `seedSourceDatabase`::
Create database `foo` from the most recent backup chain found for database `bar` in the seed directory on the server `server-id`:
+
[.tabbed-example]
=====
[role=include-with-Cypher-5]
======

----
CREATE DATABASE foo OPTIONS { 
    existingData: 'use',
    seedURI: 'server://server-id/',
    seedSourceDatabase: 'bar'
};
----

======
[role=include-with-Cypher-25]
======

[source,cypher25]
----
CREATE DATABASE foo OPTIONS { 
    seedURI: 'server://server-id/',
    seedSourceDatabase: 'bar' 
};
----
======
=====



[[file-seed-provider]]
=== FileSeedProvider

The `FileSeedProvider`  supports:

** `file:`

[NOTE]
====
Local file paths must be absolute paths.
====


[[url-connection-seed-provider]]
=== URLConnectionSeedProvider

The `URLConnectionSeedProvider` supports the following:

** `ftp:`
** `http:`
** `https:`

Starting from Neo4j 2025.01, the `URLConnectionSeedProvider` does not support `file`.
This is true for both Cypher 5 and Cypher 25.


[[cloud-seed-provider]]
=== CloudSeedProvider

The `CloudSeedProvider` supports:

** `s3:`
** `gs:`
** `azb:`

The `CloudSeedProvider` supports using xref:backup-restore/modes.adoc#differential-backup[differential backup] files as seeds.
With the provided differential backup file, the `CloudSeedProvider` searches the directory containing differential backup files for a xref:backup-restore/online-backup.adoc#backup-chain[backup chain] ending at the specified differential backup, and then seeds using this backup chain.

[.tabbed-example]
=====
[role=include-with-AWS-S3]
======

include::partial$/aws-s3-overrides.adoc[]

include::partial$/aws-s3-credentials.adoc[]

. Create database from `myBackup.backup`.
This backup can be a full backup, a differential backup, or a dump file.
+
Using Cypher 5:
+
[source,cypher5]
----
CREATE DATABASE foo OPTIONS { existingData: 'use', seedURI: 's3://myBucket/myBackup.backup' }
----
+
Using Cypher 25 label:new[Introduced in 2025.06]:
+
[source,cypher25]
----
CREATE DATABASE foo OPTIONS { seedURI: 's3://myBucket/myBackup.backup' }
----

======
[role=include-with-Google-cloud-storage]
======

include::partial$/gcs-credentials.adoc[]

. Create database from `myBackup.backup`.
This backup can be a full backup, a differential backup, or a dump file.
+
Using Cypher 5:
+
[source,cypher5]
----
CREATE DATABASE foo OPTIONS { existingData: 'use', seedURI: 'gs://myBucket/myBackup.backup' }
----
+
Using Cypher 25 label:new[Introduced in 2025.06]:
+
[source,cypher25]
----
CREATE DATABASE foo OPTIONS { seedURI: 'gs://myBucket/myBackup.backup' }
----

======
[role=include-with-Azure-cloud-storage]
======

include::partial$/azb-credentials.adoc[]

. Create database from `myBackup.backup`.
This backup can be a full backup, a differential backup, or a dump file.
+
Using Cypher 5:
+
[source,cypher5]
----
CREATE DATABASE foo OPTIONS { existingData: 'use', seedURI: 'azb://myStorageAccount/myContainer/myBackup.backup' }
----
+
Using Cypher 25 label:new[Introduced in 2025.06]:
+
[source,cypher25]
----
CREATE DATABASE foo OPTIONS { seedURI: 'azb://myStorageAccount/myContainer/myBackup.backup' }
----
======
=====


[role=label--deprecated-5.26 label--cypher-5]
[[s3-seed-provider]]
=== S3SeedProvider

The `S3SeedProvider` supports:

** `s3:`


[NOTE]
====
Neo4j comes bundled with necessary libraries for AWS S3 connectivity.
Therefore, if you use `S3SeedProvider`, `aws cli` is not required as it is for `CloudSeedProvider`.
====

The `S3SeedProvider` requires additional configuration.
This is specified with the `seedConfig` option, which expects a comma-separated list of configurations.
Each configuration entry is specified in the format `key=value`, as such:

[source, cypher]
----
CREATE DATABASE foo OPTIONS {
    existingData: 'use',
    seedURI: 's3://myBucket/myBackup.backup',
    seedConfig: 'region=eu-west-1'
}
----

`S3SeedProvider` also requires passing in credentials.
These are specified with the `seedCredentials` option.
Seed credentials are securely passed from the Cypher command to each server hosting the database.
For this to work, Neo4j on each server in the cluster must be configured with identical keystores.
This is identical to the configuration required by remote aliases, see xref:database-administration/aliases/remote-database-alias-configuration.adoc#remote-alias-config-DBMS_admin-A[Configuration of DBMS with remote database alias].
Without this configuration, the `seedCredentials` option fails.

[source, cypher5]
----
CREATE DATABASE foo OPTIONS {
    existingData: 'use',
    seedURI: 's3://myBucket/myBackup.backup',
    seedConfig: 'region=eu-west-1',
    seedCredentials: <accessKey>;<secretKey>
}
----
Where `<accessKey>` and `<secretKey>` are provided by AWS.

[[seed-provider-reference]]
=== Seed provider reference

[cols="1,2,2",options="header"]
|===
| URL scheme
| Seed provider
| URI example

| `server:`
| label:new[Introduced in 2026.04] `ServerSeedProvider`
| `server://server-id/backup1.backup` +
`server://server-name/`

| `file:`
| `FileSeedProvider`
| `file:/tmp/backup1.backup`
 `file:/tmp/backup1.dump`

| `ftp:`
| `URLConnectionSeedProvider`
| `\ftp://myftp.com/backups/backup1.backup`
`\ftp://myftp.com/backups/backup1.dump`

| `http:`
| `URLConnectionSeedProvider`
| `\http://myhttp.com/backups/backup1.backup`
`\http://myhttp.com/backups/backup1.dump`

| `https:`
| `URLConnectionSeedProvider`
| `\https://myhttp.com/backups/backup1.backup`
`\https://myhttp.com/backups/backup1.dump`

| `s3:`
| label:deprecated[Deprecated in 5.26] `S3SeedProvider`, +
`CloudSeedProvider`
| `s3://mybucket/backups/backup1.backup`
`s3://mybucket/backups/backup1.dump`
`s3://mybucket/backups/` (folder containing a backup chain, only used by `CloudSeedProvider`)

| `gs:`
| `CloudSeedProvider`
| `gs://mybucket/backups/backup1.backup`
`gs://mybucket/backups/backup1.dump`
`gs://mybucket/backups/` (folder containing a backup chain)

| `azb:`
| `CloudSeedProvider`
| `azb://mystorageaccount.blob/backupscontainer/backup1.backup`
`azb://mystorageaccount.blob/backupscontainer/backup1.dump`
`azb://mystorageaccount.blob/backupscontainer/` (folder containing a backup chain)
|===


[[seed-restore-until-option]]
== Support for seeding up to a date or a transaction ID

Starting from Neo4j 2025.01, when creating a database you can seed up to a specific date or transaction ID via the `seedRestoreUntil` option.

The `seedRestoreUntil` option is supported by the `CloudSeedProvider` and the `FileSeedProvider`.

Seed up to a specific date::

To seed up to a specific date, provide the differential backup containing the data up to that date.
+
[.tabbed-example]
=====
[role=include-with-Cypher-5]
======
[source,cypher5]
----
CREATE DATABASE foo OPTIONS {
    existingData: 'use',
    seedURI: 's3://myBucket/myBackup.backup',
    seedRestoreUntil: datetime('2019-06-01T18:40:32.142+0100')
}
----
======
[role=include-with-Cypher-25 label--new-2025.06]
======

[source,cypher25]
----
CREATE DATABASE foo OPTIONS {
    seedURI: 's3://myBucket/myBackup.backup',
    seedRestoreUntil: datetime('2019-06-01T18:40:32.142+0100')
}
----
======
=====
+
This will seed the database with transactions committed before the provided timestamp.


Seed up to a specific transaction ID::

To seed up to a specific transaction ID, provide the differential backup containing the data up to that transaction ID.
+
[.tabbed-example]
=====
[role=include-with-Cypher-5]
======
[source,cypher5]
----
CREATE DATABASE foo OPTIONS {
    existingData: 'use',
    seedURI: 's3://myBucket/myBackup.backup',
    seedRestoreUntil: 123
}
----
======
[role=include-with-Cypher-25 label--new-2025.06]
======
[source,cypher25]
----
CREATE DATABASE foo OPTIONS {
    seedURI: 's3://myBucket/myBackup.backup',
    seedRestoreUntil: 123
}
----
======
=====
+
This will seed the database with transactions up to (but not including) transaction 123.

