:page-role: enterprise-edition
:description: How to create a database using a seed from URI.

= Create a database from a URI

This method seeds all databases with an identical seed from an external source, specified by a URI.

You specify the seed URI as an argument of the `CREATE DATABASE` command:

[.tabbed-example]
=====
[role=include-with-Cypher-5]
======

[source, cypher5]
----
CREATE DATABASE foo OPTIONS { existingData: 'use', seedURI:'s3://myBucket/myBackup.backup' }
----

======
[role=include-with-Cypher-25 label--new-2025.06]
======

[source, cypher25]
----
CREATE DATABASE foo OPTIONS { seedURI:'s3://myBucket/myBackup.backup' }
----
======
=====

[NOTE]
====
The `existingData` option is required in Cypher 5 and deprecated in Cypher 25.
====

Download and validation of the seed is only performed as the new database is started.
If it fails, the database is not available and it has the `statusMessage`: `Unable to start database` of the `SHOW DATABASES` command.

.Example failure output for `SHOW DATABASES`
[source, role="queryresult"]
----
| name    | type       | aliases | access       | address          | role      | writer | requestedStatus | currentStatus | statusMessage                                            | default | home  | constituents |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| "seed3" | "standard" | []      | "read-write" | "localhost:7682" | "unknown" | FALSE  | "online"        | "offline"     | "Unable to start database `DatabaseId{3fe1a59b[seed3]}`" | FALSE   | FALSE | []           |
----

To determine the cause of the problem, check the `debug.log` file.

[NOTE]
====
Starting from Neo4j 2025.01, seed from URI can also be used in combination with xref:database-administration/standard-databases/create-databases.adoc[`CREATE OR REPLACE DATABASE`].
====


[[neo4j-seed-providers]]
== Seed providers in Neo4j

The seed can either be a full backup, a differential backup (see <<cloud-seed-provider, `CloudSeedProvider`>>), or a dump from an existing database.
The sources of seeds are called _seed providers_.

The mechanism is pluggable, allowing new sources of seeds to be supported (see link:https://www.neo4j.com/docs/java-reference/current/extending-neo4j/project-setup/#extending-neo4j-plugin-seed-provider[Java Reference -> Implement custom seed providers] for more information).

The product has built-in support for seed from a mounted file system (file), FTP server, HTTP/HTTPS server, Amazon S3, Google Cloud Storage, and Azure Cloud Storage.

[NOTE]
====
Amazon S3, Google Cloud Storage, and Azure Cloud Storage are supported by default, but the other providers require configuration of xref:configuration/configuration-settings.adoc#config_dbms.databases.seed_from_uri_providers[`dbms.databases.seed_from_uri_providers`].
====


[[file-seed-provider]]
=== FileSeedProvider

The `FileSeedProvider`  supports:

** `file:`

[NOTE]
====
Local file paths must be absolute paths.
====


[[url-connection-seed-provider]]
=== URLConnectionSeedProvider

The `URLConnectionSeedProvider` supports the following:

** `ftp:`
** `http:`
** `https:`

Starting from Neo4j 2025.01, the `URLConnectionSeedProvider` does not support `file`.
This is true for both Cypher 5 and Cypher 25.


[[cloud-seed-provider]]
=== CloudSeedProvider

The `CloudSeedProvider` supports:

** `s3:`
** `gs:`
** `azb:`

The `CloudSeedProvider` supports using xref:backup-restore/modes.adoc#differential-backup[differential backup] files as seeds.
With the provided differential backup file, the `CloudSeedProvider` searches the directory containing differential backup files for a xref:backup-restore/online-backup.adoc#backup-chain[backup chain] ending at the specified differential backup, and then seeds using this backup chain.

[.tabbed-example]
=====
[role=include-with-AWS-S3]
======

include::partial$/aws-s3-overrides.adoc[]

include::partial$/aws-s3-credentials.adoc[]

. Create database from `myBackup.backup`.
+
Using Cypher 5:
+
[source,cypher5]
----
CREATE DATABASE foo OPTIONS { existingData: 'use', seedURI: 's3://myBucket/myBackup.backup' }
----
+
Using Cypher 25 label:new[Introduced in 2025.06]:
+
[source,cypher25]
----
CREATE DATABASE foo OPTIONS { seedURI: 's3://myBucket/myBackup.backup' }
----

======
[role=include-with-Google-cloud-storage]
======

include::partial$/gcs-credentials.adoc[]

. Create database from `myBackup.backup`.
+
Using Cypher 5:
+
[source,cypher5]
----
CREATE DATABASE foo OPTIONS { existingData: 'use', seedURI: 'gs://myBucket/myBackup.backup' }
----
+
Using Cypher 25 label:new[Introduced in 2025.06]:
+
[source,cypher25]
----
CREATE DATABASE foo OPTIONS { seedURI: 'gs://myBucket/myBackup.backup' }
----
======
[role=include-with-Azure-cloud-storage]
======

include::partial$/azb-credentials.adoc[]

. Create database from `myBackup.backup`.
+
Using Cypher 5:
+
[source,cypher5]
----
CREATE DATABASE foo OPTIONS { existingData: 'use', seedURI: 'azb://myStorageAccount/myContainer/myBackup.backup' }
----
+
Using Cypher 25 label:new[Introduced in 2025.06]:
+
[source,cypher25]
----
CREATE DATABASE foo OPTIONS { seedURI: 'azb://myStorageAccount/myContainer/myBackup.backup' }
----
======
=====


[role=label--deprecated label--cypher-5]
[[s3-seed-provider]]
=== S3SeedProvider

// When Cypher 25 is released, we have to label this section 'Cypher 5' as this functionality is only available in Cypher 5.

The `S3SeedProvider` supports:

** `s3:`


[NOTE]
====
Neo4j comes bundled with necessary libraries for AWS S3 connectivity.
Therefore, if you use `S3SeedProvider`, `aws cli` is not required (as it instead is with `CloudSeedProvider`).
====

The `S3SeedProvider` requires additional configuration.
This is specified with the `seedConfig` option, which expects a comma-separated list of configurations.
Each configuration entry is specified in the format `key=value`, as such:

[source, cypher5]
----
CREATE DATABASE foo OPTIONS {
    existingData: 'use',
    seedURI: 's3://myBucket/myBackup.backup',
    seedConfig: 'region=eu-west-1'
}
----

`S3SeedProvider` also requires passing in credentials.
These are specified with the `seedCredentials` option.
Seed credentials are securely passed from the Cypher command to each server hosting the database.
For this to work, Neo4j on each server in the cluster must be configured with identical keystores.
This is identical to the configuration required by remote aliases, see xref:database-administration/aliases/remote-database-alias-configuration.adoc#remote-alias-config-DBMS_admin-A[Configuration of DBMS with remote database alias].

Without this configuration, the `seedCredentials` option fails.

[source, cypher5]
----
CREATE DATABASE foo OPTIONS {
    existingData: 'use',
    seedURI: 's3://myBucket/myBackup.backup',
    seedConfig: 'region=eu-west-1',
    seedCredentials: <accessKey>;<secretKey>
}
----
Where `<accessKey>` and `<secretKey>` are provided by AWS.


=== Seed provider reference

[cols="1,2,2",options="header"]
|===
| URL scheme
| Seed provider
| URI example

| `file:`
| `FileSeedProvider`
| `file:/tmp/backup1.backup`

| `ftp:`
| `URLConnectionSeedProvider`
| `\ftp://myftp.com/backups/backup1.backup`

| `http:`
| `URLConnectionSeedProvider`
| `\http://myhttp.com/backups/backup1.backup`

| `https:`
| `URLConnectionSeedProvider`
| `\https://myhttp.com/backups/backup1.backup`

| `s3:`
| `S3SeedProvider` label:deprecated[Deprecated in 5.26], +
`CloudSeedProvider`
| `s3://mybucket/backups/backup1.backup`

| `gs:`
| `CloudSeedProvider`
| `gs://mybucket/backups/backup1.backup`

| `azb:`
| `CloudSeedProvider`
| `azb://mystorageaccount.blob/backupscontainer/backup1.backup`
|===


[[seed-restore-until-option]]
== Support for seeding up to a date or a transaction ID

Starting from Neo4j 2025.01, when creating a database you can seed up to a specific date or transaction ID via the `seedRestoreUntil` option.

The `seedRestoreUntil` option is supported by the `CloudSeedProvider` and the `FileSeedProvider`.

Seed up to a specific date::

To seed up to a specific date, provide the differential backup containing the data up to that date.
+
[.tabbed-example]
=====
[role=include-with-Cypher-5]
======
[source,cypher5]
----
CREATE DATABASE foo OPTIONS {
    existingData: 'use',
    seedURI: 's3://myBucket/myBackup.backup',
    seedRestoreUntil: datetime('2019-06-01T18:40:32.142+0100')
}
----
======
[role=include-with-Cypher-25 label--new-2025.06]
======

[source,cypher25]
----
CREATE DATABASE foo OPTIONS {
    seedURI: 's3://myBucket/myBackup.backup',
    seedRestoreUntil: datetime('2019-06-01T18:40:32.142+0100')
}
----
======
=====
+
This will seed the database with transactions committed before the provided timestamp.


Seed up to a specific transaction ID::

To seed up to a specific transaction ID, provide the differential backup containing the data up to that transaction ID.
+
[.tabbed-example]
=====
[role=include-with-Cypher-5]
======
[source,cypher5]
----
CREATE DATABASE foo OPTIONS {
    existingData: 'use',
    seedURI: 's3://myBucket/myBackup.backup',
    seedRestoreUntil: 123
}
----
======
[role=include-with-Cypher-25 label--new-2025.06]
======
[source,cypher25]
----
CREATE DATABASE foo OPTIONS {
    seedURI: 's3://myBucket/myBackup.backup',
    seedRestoreUntil: 123
}
----
======
=====
+
This will seed the database with transactions up to (but not including) transaction 123.

