
. Install the AWS CLI by following the instructions in the AWS official documentation -- link:https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html[Install the AWS CLI version 2].
. Create an S3 bucket and a directory to store the backup files using the AWS CLI:
+
[source,shell]
----
aws s3 mb --region=us-east-1 s3://myBucket
aws s3api put-object --bucket myBucket --key myDirectory/
----
+
For more information on how to create a bucket and use the AWS CLI, see the AWS official documentation -- link:https://docs.aws.amazon.com/cli/latest/userguide/cli-services-s3-commands.html#using-s3-commands-prereqs[Use Amazon S3 with the AWS CLI] and link:https://docs.aws.amazon.com/cli/latest/userguide/cli-services-s3.html[Use high-level (s3) commands with the AWS CLI].
. Verify that the `~/.aws/config` file is correct by running the following command:
+
[source,shell]
----
cat ~/.aws/config
----
The output should look like this:
+
[result,shell]
----
[default]
region=us-east-1
----
. Configure the access to your AWS S3 bucket by setting the `aws_access_key_id` and `aws_secret_access_key` in the `~/.aws/credentials` file and, if needed, using a bucket policy.
For example:

.. Use `aws configure set aws_access_key_id aws_secret_access_key` command to set your IAM credentials from AWS and verify that the `~/.aws/credentials` is correct:
+
[source,shell]
----
cat ~/.aws/credentials
----
The output should look like this:
+
[result,shell]
----
[default]
aws_access_key_id=this.is.secret
aws_secret_access_key=this.is.super.secret
----

.. Additionally, you can use a resource-based policy to grant access permissions to your S3 bucket and the objects in it.
Create a policy document with the following content and attach it to the bucket.
Note that both resource entries are important to be able to download and upload files.
+
[source, json]
----
{
    "Version": "2012-10-17",
    "Id": "Neo4jBackupAggregatePolicy",
    "Statement": [
        {
            "Sid": "Neo4jBackupAggregateStatement",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::myBucket/*",
                "arn:aws:s3:::myBucket"
            ]
        }
    ]
}
----
