. Ensure you have a Azure account, an Azure storage account, and a blob container.
.. You can create a storage account using the Azure portal. +
For more information, see the Azure official documentation on link:https://learn.microsoft.com/en-us/azure/storage/common/storage-account-create?tabs=azure-portal[Create a storage account].
.. Create a blob container in the Azure portal. +
For more information, see the Azure official documentation on link:https://learn.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-portal[Quickstart: Upload, download, and list blobs with the Azure portal].
. Install the Azure CLI by following the instructions in the Azure official documentation -- link:https://docs.microsoft.com/en-us/cli/azure/install-azure-cli[Azure official documentation].
. Authenticate the neo4j or neo4j-admin process against Azure using the default Azure credentials. +
See the Azure official documentation on link:https://learn.microsoft.com/en-us/java/api/com.azure.identity.defaultazurecredential?view=azure-java-stable[default Azure credentials] for more information. +
+
[source,shell]
----
az login
----
+
Then you should be ready to use Azure URLs in either neo4j or neo4j-admin.

. To validate that you have access to the container with your login credentials, run the following commands:
+
[source,shell]
----
# Upload a file:
az storage blob upload --file someLocalFile  --account-name accountName - --container someContainer --name remoteFileName  --auth-mode login

# Download the file
az storage blob download  --account-name accountName --container someContainer --name remoteFileName --file downloadedFile --auth-mode login

# List container files
az storage blob list  --account-name someContainer --container someContainer  --auth-mode login
----
