[role=label--new-2025.06]
== Cypher® versions

The Cypher language has been decoupled from the Neo4j server versioning and now has its own versioning system.
You can choose between Cypher 5 and Cypher 25:

* Cypher 5 is the language version with which all queries written for Neo4j 2025.05 and earlier versions are compatible.
It remains the default version for all newly created databases; however, as of Neo4j 2025.06, it is frozen and will only receive performance enhancements and bug fixes in future server releases.

* Cypher 25 is the new version of the Cypher language.
It builds upon Cypher 5 and includes new and improved features, as well as some removals.
Any new Cypher features introduced in Neo4j 2025.06 or later will be added only to Cypher 25.

For more information about the Cypher versioning, see link:{neo4j-docs-base-uri}/cypher-manual/25/queries/select-version/[Cypher Manual -> Select Cypher version].

You can specify the version of Cypher in which you want to run your queries (Cypher 5 or Cypher 25) by configuring a default Cypher version for the whole DBMS, for a database, or by setting it on a per-query basis.
For details, see the xref:configuration/cypher-version-configuration.adoc[].
