[role=label--new-2025.06]
== Cypher® versions

The Cypher language has been decoupled from the Neo4j server versioning and now has its own versioning system.
You can choose between Cypher 25 and Cypher 5:

* Cypher 25 is the new version of the Cypher language.
It builds upon Cypher 5 and includes new and improved features, as well as some removals.
Any new Cypher features introduced in Neo4j 2025.06 or later are added only to Cypher 25.
Starting with Neo4j 2026.02, Cypher 25 is the default version for all newly created databases.

* Cypher 5 is the language version with which all queries written for Neo4j 2025.05 and earlier versions are compatible.
However, as of Neo4j 2025.06, it is frozen and will only receive performance enhancements and bug fixes in future server releases.
Cypher 5 remains the default version for all newly created databases in versions prior to 2026.02.

For more information about the Cypher versioning, see link:{neo4j-docs-base-uri}/cypher-manual/current/queries/select-version/[Cypher Manual -> Select Cypher version].

You can specify the version of Cypher in which you want to run your queries (Cypher 5 or Cypher 25) by configuring a default Cypher version for the whole DBMS, for a database, or by setting it on a per-query basis.
For details, see the xref:configuration/cypher-version-configuration.adoc[].