[role=label--new-2025.06]
== Cypher® versions

As of Neo4j 2025.06, the Cypher language is decoupled from the Neo4j server and follows its own versioning.
Currently, there are two versions of Cypher available: Cypher 5 and Cypher 25.
You can specify the version of Cypher by configuring a default Cypher version for the whole DBMS by explicitely setting `db.query.default_language` configuration in the _neo4j.conf_ file, per database when using `CREATE DATABASE` or `ALTER DATABASE`, or by prepending the query with `CYPHER 5` or `CYPHER 25` on a per-query basis to override the default.
For more information, see the xref:configuration/cypher-version-configuration.adoc[Configure the Cypher default version] and link:{neo4j-docs-base-uri}/cypher-manual/current/queries/select-version/[Cypher Manual -> Select Cypher version].

Cypher 5::
Cypher 5 is the language version with which all queries written for Neo4j 2025.05 and earlier versions are compatible.
However, as of Neo4j 2025.06, it is frozen and will only receive performance enhancements and bug fixes in future server releases. +
Setting the default language to `CYPHER 5` ensures that all queries run on that database use the version of `Cypher 5` as it existed at the time of the Neo4j 2025.06 release (unless you prepend your queries with `CYPHER 25`, which overrides this default).
Any changes introduced after the 2025.06 release do not affect the semantics of the query. +
Cypher 5 remains the default version for all newly created databases unless `db.query.default_language=CYPHER_25` *is explicitly set* on the DBMS level or overridden using `CREATE DATABASE` or `ALTER DATABASE`, or by prepending queries with `CYPHER 25`.

Cypher 25::
Cypher 25 builds upon Cypher 5 and includes new and improved features, as well as some removals.
Any new Cypher features introduced in Neo4j 2025.06 or later are added only to Cypher 25.
Setting the default language to `CYPHER 25` ensures that all queries run on that database use the version of `Cypher 25` that the database is currently running (unless you prepend your queries with `CYPHER 5`, which overrides this default).
For example, a Neo4j 2025.10 database with default language `Cypher 25` will use `Cypher 25` as it exists in Neo4j 2025.10, including any changes introduced in Neo4j 2025.06, 2025.07, 2025.08, and 2025.09.
+
[IMPORTANT]
====
Starting from Neo4j 2026.02,the distributed _neo4j.conf_ *explicitly sets* `db.query.default_language=CYPHER_25`.
As a result, new deployments using the provided configuration file default to Cypher 25 for newly created databases.
The Cypher version can still be explicitly specified in the `CREATE DATABASE` command or can be changed at any time using `ALTER DATABASE`.

If you want to use Cypher 5 as the default for new databases, you can remove or comment out that configuration entry, which is equivalent to setting `db.query.default_language=CYPHER_5`.
Existing databases retain their existing default language.
====