. Ensure you have a Google account and a project created in the Google Cloud Platform (GCP).
.. Install the `gcloud` CLI by following the instructions in the Google official documentation -- link:https://cloud.google.com/sdk/docs/install[Install the gcloud CLI].
.. Create a service account and a service account key using Google official documentation -- link:https://cloud.google.com/iam/docs/service-accounts-create[Create service accounts] and link:https://cloud.google.com/iam/docs/keys-create-delete[Creating and managing service account keys].
.. Download the JSON key file for the service account.
.. Set the `GOOGLE_APPLICATION_CREDENTIALS` and `GOOGLE_CLOUD_PROJECT` environment variables to the path of the JSON key file and the project ID, respectively:
+
[source,shell]
----
export GOOGLE_APPLICATION_CREDENTIALS="/path/to/keyfile.json"
export GOOGLE_CLOUD_PROJECT=YOUR_PROJECT_ID
----
.. Authenticate the `gcloud` CLI with the e-mail address of the service account you have created, the path to the JSON key file, and the project ID:
+
[source,shell]
----
gcloud auth activate-service-account service-account@example.com --key-file=$GOOGLE_APPLICATION_CREDENTIALS --project=$GOOGLE_CLOUD_PROJECT
----
+
For more information, see the Google official documentation -- link:https://cloud.google.com/sdk/gcloud/reference/auth/activate-service-account[gcloud auth activate-service-account].
.. Create a bucket in the Google Cloud Storage using Google official documentation -- link:https://cloud.google.com/storage/docs/creating-buckets[Create buckets].
.. Verify that the bucket is created by running the following command:
+
[source,shell]
----
gcloud storage ls
----
The output should list the created bucket.

