[role=enterprise-edition]
[[backup-restoring]]
= Restore a backup
:description: This section describes how to restore from a backup of a Neo4j database. 

This section includes:

* xref:backup/restoring.adoc#backup-restoring-command[Restore commands]
* xref:backup/restoring.adoc#backup-restoring-single[Restore a single database]
* xref:backup/restoring.adoc#backup-restoring-causal-cluster[Restore a Causal Cluster]

[[backup-restoring-command]]
== Restore commands

A Neo4j database can be restored using the `restore` command of `neo4j-admin`.

*Syntax*

`neo4j-admin restore --from=<backup-directory> [--database=<name>]
                           [--force[=<true|false>]]`

*Options*

[options="header"]
|===
| Option                   | Default        | Description
|  --from                  |                | Path to backup to restore from.
|  --database              | graph.db       | Name of database.
|  --force                 | false          | If an existing database should be replaced.
|===


[[backup-restoring-single]]
== Restore a single database

To restore from a backup, follow these steps:

. If the database is running, shut it down.
. Run `neo4j-admin restore`.
. Start up the database.

.Restore a single database
====

Restore the database `graph.db` from the backup located in _/mnt/backup/graph.db-backup_.
Note that the database to be restored must be shut down.
[source,shell]
----
neo4j-home> bin/neo4j stop
neo4j-home> bin/neo4j-admin restore --from=/mnt/backup/graph.db-backup --database=graph.db --force
neo4j-home> bin/neo4j start
----
====


[[backup-restoring-causal-cluster]]
== Restore a Causal Cluster

To restore from a backup in a Causal Cluster, follow these steps:

. Shut down all database instances in the cluster.
. Run the `xref:tools/unbind.adoc[neo4j-admin unbind]` command on each of the Core Servers.
. Restore the backup on each instance, using `neo4j-admin restore`.
. If you are restoring onto new hardware, please review the _Causal Clustering_ settings in _neo4j.conf_.
+
In particular, check the settings `xref:reference/configuration-settings.adoc#config_causal_clustering.initial_discovery_members[causal_clustering.initial_discovery_members]`, `xref:reference/configuration-settings.adoc#config_causal_clustering.minimum_core_cluster_size_at_formation[causal_clustering.minimum_core_cluster_size_at_formation]`, and `xref:reference/configuration-settings.adoc#config_causal_clustering.minimum_core_cluster_size_at_runtime[causal_clustering.minimum_core_cluster_size_at_runtime]`,
and ensure that they correctly reflect the new setup.
. Start the database instances.
