[role=enterprise-edition]
[[backup-standalone]]
= Standalone databases
:description: This section discusses configuration options for backups of standalone databases. 

This section includes:

* xref:backup/standalone.adoc#backup-standalone-parameters[Configuration parameters]
* xref:backup/standalone.adoc#backup-standalone-separate[Running backups from a separate server]
* xref:backup/standalone.adoc#backup-standalone-local[Running backups from the local server]


[[backup-standalone-parameters]]
== Configuration parameters

The table below lists the configuration parameters relevant to backups:

[[table-backup-introduction-options-standalone-parameters]]
.Configuration parameters backups; standalone databases
[options="header"]
|===
| Parameter name | Default value | Description
| `xref:reference/configuration-settings.adoc#config_dbms.backup.enabled[dbms.backup.enabled]` | `true` | Enable support for running online backups.
| `xref:reference/configuration-settings.adoc#config_dbms.backup.address[dbms.backup.address]` | `127.0.0.1:6362-6372` | Listening server for online backups.
|===

[[backup-standalone-separate]]
== Running backups from a separate server

Consider the image below:

image::backup-separate-server.svg[role="middle"]

In this configuration, the backup client is run on a separate server.
This is the recommended configuration for a standalone database.

The server that runs the backup client must have Neo4j installed, but does not need to host a database.

[NOTE]
It is strongly recommended to run backups from a different server than the production server.

[[backup-standalone-local]]
== Running backups from the local server

Consider the image below:

image::backup-local_server.svg[role="middle"]

In this configuration, the backup program is run on the same server that hosts the Neo4j production database.

When the backup program is started, it will start up a new Java process.
If there is a running Neo4j database, this will run in parallel to the Neo4j process.
On a production system, Neo4j is typically configured to take maximum advantage of the system's available RAM.
If you run backups on a production system, the overall performance can be negatively affected, and in extreme cases can cause failure with an out-of-memory error.
It is therefore strongly recommended to run backups from a different server than the production server.

If it is not possible to use a separate backup server, you can control the impact on the production system by explicitly defining how much memory to allocate to the backup process.
See xref:backup/planning.adoc#backup-planning-memory-considerations[Memory configuration].
