:description: How to use your own procedures in Neo4j.
:keywords: user-defined procedure, customized code, `DEFINE`, `DEFINE PROCEDURE`
= Define procedures

You can use your own procedures in Neo4j in two ways:

 * label:new[Introduced in 2026.09] label:cypher[Cypher 25] Define them locally, within a Cypher query, using the Cypher `DEFINE PROCEDURE` clause.
 * Write them as customized code that extends Neo4j.
 See link:{neo4j-docs-base-uri}/java-reference/{page-version}/extending-neo4j/user-defined-procedures-functions/[Java Reference -> User-defined procedures and functions] for details.

[role=label--new-yyyy.mm label--cypher-25]
[[define-local-procedures]]
== Define local procedures

You can define a procedure within a query using the Cypher clause `DEFINE PROCEDURE`.
You can only call it locally and within the scope of the query in which it is defined.

For example, the following query defines a local procedure `buyProduct` and calls it twice within the same query:

[source, cypher]
----
DEFINE PROCEDURE buyProduct(customerName, productName, purchaseDate) {
  MATCH (c:Customer {firstName: customerName})
  MATCH (p:Product {name: productName})
  CREATE (c)-[:BUYS {date: purchaseDate}]->(p)
  RETURN p.name AS product, purchaseDate AS date
}
CALL buyProduct('Mateo', 'Phone', date('2025-05-01')) 
YIELD product AS firstProduct,
      date AS firstDate
CALL buyProduct('Mateo', 'Headphones', firstDate + duration('P7D'))
YIELD product AS secondProduct,
      date AS secondDate
RETURN firstProduct, firstDate, secondProduct, secondDate
----

For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/define/[Cypher Manual -> `DEFINE`].

[[write-procedures-with-customized-code]]
== Write procedures with customized code

You can write procedures with customized code to extend the Neo4j functionality.
Procedures should be implemented in a language within the JVM ecosystem and packaged into a JAR file.
After deploying the JAR file as a plugin, a procedure becomes available for use in Cypher queries with a fully-qualified name.
For details, see link:{neo4j-docs-base-uri}/java-reference/current/extending-neo4j/user-defined-procedures-functions/[Java Reference -> User-defined procedures and functions].

The following is an example of calling a customized-code procedure:

[source, cypher]
----
CALL org.neo4j.examples.findDenseNodes(1000);
----


