:description: An overview of user-defined procedures in Neo4j.
:keywords: user-defined procedure, custom code, `DEFINE`
= Define procedures

Neo4j supports two ways of defining your own procedures:

 * label:new[Introduced in 2026.09] label:cypher[Cypher 25] Locally, within a Cypher query, using the Cypher `DEFINE` clause.
 * Writing them as custom code that extends Neo4j.
 See link:{neo4j-docs-base-uri}/java-reference/{page-version}/extending-neo4j/user-defined-procedures-functions/[Java Reference -> User-defined procedures and functions] for details.

[role=label--new-yyyy.mm label--cypher-25]
[[define-procedures-within-a-cypher-query]]
== Define procedures within a Cypher query

You can define a procedure within a query using the Cypher clause`DEFINE`.
You can only call it locally and within the scope of the query in which it is defined.

For example:

.Defining and calling a local procedure
[source, cypher]
----
DEFINE PROCEDURE isEven(from, to) {
  UNWIND range(from, to) AS x
  RETURN x, x % 2 = 0 AS even
}
CALL isEven(1, 4) YIELD x, even
RETURN x, even;
----

For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/define/[Cypher Manual -> `DEFINE`].

[[defining-procedures-with-customized-code]]
== Defining procedures with customized code

You can define procedures with customized code to extend the Neo4j functionality.
Procedures should be implemented in a language within the JVM ecosystem and packaged into a JAR file.
After deploying the JAR file as a plugin, a procedure becomes available for use in Cypher queries with a fully-qualified name.
For details, see link:{neo4j-docs-base-uri}/java-reference/current/extending-neo4j/user-defined-procedures-functions/[Java Reference -> User-defined procedures and functions].

The following is an example of calling a custom-code procedure:

.Calling a custom-code procedure
[source, cypher]
----
CALL org.neo4j.examples.findDenseNodes(1000);
----


