= User-defined procedures
:description: This page provides an overview of using user-defined procedures with Neo4j.

Neo4j supports two ways of defining your own procedures: defining them locally within a Cypher query, or writing them as custom code that extends Neo4j itself.

[role=label--new-Neo4j-yyyy.mm label--cypher-25]
[[define-query-local-procedures-with-cypher]]
== Define query-local procedures with Cypher

A procedure can be defined locally, scoped to the single query it is used in, using the `DEFINE` clause in Cypher.
This does not require writing or deploying any code, and the procedure is only available within the query that defines it.

.Local procedure defined with `DEFINE`
[source, cypher]
----
DEFINE PROCEDURE isEven(from, to) {
  UNWIND range(from, to) AS x
  RETURN x, x % 2 = 0 AS even
}
CALL isEven(1, 4) YIELD x, even
RETURN x, even
----

For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/current/clauses/define/[Cypher Manual -> `DEFINE`].

[[defining-procedures-with-customized-code]]
== Defining procedures with customized code

Neo4j can also be extended by writing a procedure as custom Java code, which is compiled, deployed as a plugin, and then made available to every query run against that database instance, using a fully-qualified name.

.Calling a custom-code procedure
[source, cypher]
----
CALL org.neo4j.examples.findDenseNodes(1000)
----

For more information, see link:{neo4j-docs-base-uri}/java-reference/current/extending-neo4j/user-defined-procedures-functions/[Java Reference -> User-defined procedures and functions].
