[[osx-installation]]
= macOS installation
:description: This section describes how to install Neo4j on macOS. Check xref:installation/requirements.adoc[System Requirements] to see if your setup is suitable. 


[[osx-console]]
== Unix console application

. If it is not already installed, get link:https://openjdk.java.net/[OpenJDK 11] or link:https://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle Java 11].
. Download the latest release from {neo4j-download-center-uri}[Neo4j Download Center].
+
Select the appropriate tar.gz distribution for your platform.
. Make sure to download Neo4j from {neo4j-download-center-uri}[Neo4j Download Center] and always check that the SHA hash of the downloaded file is correct:
.. To find the correct SHA hash, go to Neo4j Download Center and click on `SHA-256` which will be located below your downloaded file.
.. Using the appropriate commands for your platform, display the `SHA-256` hash for the file that you downloaded.
.. Ensure that the two are identical.
. Extract the contents of the archive, using `tar -xf` <filename>.
For example, `tar -xf neo4j-community-{neo4j-version-exact}-unix.tar.gz`.
. Place the extracted files in a permanent home on your server.
The top level directory is referred to as NEO4J_HOME.
.. To run Neo4j as a console application, use: `<NEO4J_HOME>/bin/neo4j console`.
.. To run Neo4j in a background process, use: `<NEO4J_HOME>/bin/neo4j start`.
. Visit http://localhost:7474 in your web browser.
. Connect using the username 'neo4j' with default password 'neo4j'.
You'll then be prompted to change the password.
. Stop the server by typing `Ctrl-C` in the console.


When Neo4j runs in console mode, logs are printed to the terminal.


== macOS service

Use the standard macOS system tools to create a service based on the `neo4j` command.


== macOS file descriptor limits

The limit of _open file descriptors_ may have to be increased if a database has many indexes or if there are many connections to the database.
The currently configured open file descriptor limitation on your macOS system can be inspected with the `launchctl limit maxfiles` command.
The method for changing the limit may differ depending on the version of macOS.
Consult the documentation for your operating system in order to find out the appropriate command.

If you raise the limit above 10240, then you must also add the following setting to your xref:configuration/file-locations.adoc[_neo4j.conf_] file:

[source, properties]
----
dbms.jvm.additional=-XX:-MaxFDLimit
----

Without this setting, the file descriptor limit for the JVM will not be increased beyond 10240.
Note, however, that this only applies to macOS.
On all other operating systems, you should always leave the `MaxFDLimit` JVM setting enabled.

== Uninstall Neo4j

Here are the steps to uninstall Neo4j on macOS:

. (Optional) Create a xref:/backup-restore/index.adoc[backup] to avoid losing your data.
. Stop all Neo4j running services:
+
[source, shell]
---
sudo systemctl stop neo4j
sudo systemctl disable neo4j
---
. Delete _NEO4J_HOME_ and the file _/lib/systemd/system/neo4j.service_:
+
[source, shell]
---
rm /lib/systemd/system/neo4j.service
rm -rf NEO4J_HOME
---