:description: Install Neo4j on macOS.
[[osx-installation]]
= macOS installation

Before you install Neo4j on macOS, check xref:installation/requirements.adoc[System Requirements] to see if your setup is suitable.
If it is not already installed, get link:https://openjdk.org/[OpenJDK 21] or link:https://www.azul.com/downloads/[ZuluJDK 21].

[[osx-console]]
== Install Neo4j as a console application

You can run Neo4j as a console application on macOS.

. Download the Linux/Mac Executable {neo4j-version-exact} (tar) release from link:{neo4j-download-center-uri}[Neo4j Deployment Center].
. Verify the integrity of the downloaded file by checking the SHA-256 hash.
It must match the hash provided on the download page below the download link.
. Extract the contents of the archive, using `tar -xf` <filename> or by double-clicking the archive in Finder.
. Place the extracted files in a permanent home on your server and set the environment variable `NEO4J_HOME` to point to the extracted directory, for example, `export NEO4J_HOME=/path/to/_<NEO4J_HOME>` to make it easier to refer to it later.
. (Optional) xref:configuration/file-locations.adoc#file-locations-file-locations[Change the default locations] of the _data_, _conf_, _certificates_, _licenses_, and _plugins_ (if you plan to use custom plugins) directories by setting the environment variable `NEO4J_CONF` and the respective xref:configuration/configuration-settings.adoc#_server_directories_settings[`server.directories.*`] settings to point to the desired locations.
+
[NOTE]
====
Storing your Neo4j files outside `NEO4J_HOME` will simplify the upgrade process later because you will be able to replace the DBMS binaries without affecting the configuration and state.
Otherwise, these Neo4j files will remain in the old installation folder and may be accidentally overwritten during an upgrade or deleted during a subsequent uninstall.
====
. label:enterprise[Enterprise Edition] Accept either the commercial or the evaluation license agreement by one of the following methods:
* Commercial license agreement (See the link:https://legal.neo4j.com/[Neo4j licensing] page for details on the available agreements.):
** Set the environment variable `NEO4J_ACCEPT_LICENSE_AGREEMENT=yes`.
** Run `$NEO4J_HOME/bin/neo4j-admin server license --accept-commercial`
* link:https://neo4j.com/terms/enterprise_us/[Neo4j Evaluation Agreement for Neo4j Software]:
** Set the environment variable `NEO4J_ACCEPT_LICENSE_AGREEMENT=eval`.
** Run `$NEO4J_HOME/bin/neo4j-admin server license --accept-evaluation`.
. Before starting up the database for the first time, it is recommended to use the `set-initial-password` command of `neo4j-admin` to define the password for the native user `neo4j`.
+
If the password is not set explicitly using this method, it will be set to the default password `neo4j`.
In that case, you will be prompted to change the default password at first login. +
For more information, see xref:configuration/set-initial-password.adoc[].
. Start Neo4j:
* To run Neo4j as a console application, use: `$NEO4J_HOME/bin/neo4j console`.
* To run Neo4j in a background process, use: `$NEO4J_HOME/bin/neo4j start`.

== Install Neo4j as a macOS service

The easiest way to install Neo4j as a service on macOS is to use the Homebrew package manager (see https://brew.sh/[Homebrew installation instructions]).

. Install Neo4j using Homebrew:
+
[source, shell]
----
brew install neo4j
----
+
This command installs Neo4j Community Edition and sets it up as a service that can be managed using Homebrew.
. (Optional) If you want to change the default directories or other settings, you can do so in the `neo4j.conf` file located at `/opt/homebrew/Cellar/neo4j/{neo4j-version-exact}/libexec/conf/neo4j.conf`.
If already started, changes to the configuration file will not take effect until you restart the Neo4j service using `brew services restart neo4j`.
. Start Neo4j as a macOS service:
+
[source, shell]
----
brew services start neo4j
----
+
This command starts the Neo4j service and sets it to launch automatically at system startup.
. To check the status of the Neo4j service, use:
+
[source, shell]
----
brew services list
----

Alternatively, if you prefer to install Neo4j manually, you can use the standard macOS system tools to create a service based on the `neo4j` command.


== Access Neo4j

After starting Neo4j, you can access it using the Neo4j Aura console, Neo4j Browser, or Cypher Shell.

=== Using the Neo4j Aura console

By default, Neo4j Community Edition does not include graph tools such as visualization, data exploration, and monitoring.
However, you can use the Neo4j Aura console to access these features in a cloud environment.

. Log in to the Aura Console at https://console.neo4j.io/.
. Connect to your Neo4j server by entering the connection details, such as the server address and port.
//To add an example.
. Connect using the username `neo4j` with your password or the default password `neo4j`.
If the default password is used, you will be prompted to change it upon first login.
. Once connected, you can use the Aura Console to run Cypher queries, visualize graphs, and monitor your local Neo4j in the cloud environment.

=== Using Neo4j Browser (default)
The Neo4j Browser is a web-based user interface for interacting with Neo4j.
To access the Neo4j Browser, open a web browser and navigate to:

. _\http://localhost:7474/_ or the URL specified in your configuration.
. Connect using the username `neo4j` with your password or the default password `neo4j`.
If the default password is used, you will be prompted to change it upon first login.

=== Using Cypher Shell
Cypher Shell is a command-line tool for executing Cypher queries against a Neo4j database.
To use Cypher Shell, run the following command in your terminal:
[source, shell]
----
$NEO4J_HOME/bin/cypher-shell -u neo4j -p <your_password>
----
Replace `<your_password>` with the password you set for the `neo4j` user.
If you did not set a password, use `neo4j` as the password.
If you are running Neo4j in console mode, you can also run Cypher Shell in the same terminal session:
[source, shell]
----
$NEO4J_HOME/bin/cypher-shell
----
This will connect to the Neo4j instance running in the same terminal.

== Logging
Neo4j logs are written to the _logs_ directory under _NEO4J_HOME_.
For detailed information about the log files, see xref:monitoring/logging.adoc[Logging].

When Neo4j runs in console mode, logs are printed to the terminal.

== macOS file descriptor limits

The limit of _open file descriptors_ may have to be increased if a database has many indexes or if there are many connections to the database.
The currently configured open file descriptor limitation on your macOS system can be inspected with the `launchctl limit maxfiles` command.
The method for changing the limit may differ depending on the version of macOS.
Consult the documentation for your operating system in order to find out the appropriate command.

If you raise the limit above 10240, then you must also add the following setting to your xref:configuration/file-locations.adoc[_neo4j.conf_] file:

[source, properties]
----
server.jvm.additional=-XX:-MaxFDLimit
----

Without this setting, the file descriptor limit for the JVM will not be increased beyond 10240.
Note, however, that this only applies to macOS.
On all other operating systems, you should always leave the `MaxFDLimit` JVM setting enabled.

== Uninstall Neo4j

Here are the steps to uninstall Neo4j on macOS:

. (Optional) Create a xref:/backup-restore/index.adoc[backup] to avoid losing your data.
. Stop all Neo4j running services:
+
[source, shell]
---
sudo systemctl stop neo4j
sudo systemctl disable neo4j
---
. Delete _NEO4J_HOME_ and the file _/lib/systemd/system/neo4j.service_:
+
[source, shell]
---
rm /lib/systemd/system/neo4j.service
rm -rf NEO4J_HOME
---