[[deployment-requirements]]
= System requirements
:description: This section provides an overview of the system requirements for running Neo4j in a production environment. 

[TIP]
====
*Neo4j AuraDB* is a fully managed Neo4j database, hosted in the cloud and requires no installation.
For more information, see https://neo4j.com/aura/[the AuraDB product^] and https://aura.support.neo4j.com/[support pages^].
====


[discrete]
= CPU
:description: This section provides an overview of the system requirements for running Neo4j in a production environment. 

Performance is generally memory or I/O bound for large graphs, and compute bound for graphs that fit in memory.

Minimum::

* Intel Core i3

Recommended::

* Intel Core i7
* IBM POWER8


[discrete]
= Memory
:description: This section provides an overview of the system requirements for running Neo4j in a production environment. 

More memory allows for larger graphs, but it needs to be configured properly to avoid disruptive garbage collection operations.
See xref:performance/memory-configuration.adoc[Memory configuration] for suggestions.

Minimum::

* 2GB

Recommended::

* 16--32GB or more


[discrete]
= Disk
:description: This section provides an overview of the system requirements for running Neo4j in a production environment. 

Aside from capacity, the performance characteristics of the disk are the most important when selecting storage.
Neo4j workloads tend significantly toward random reads.
Select media with low average seek time: SSD over spinning disks.
Consult xref:performance/disks-ram-and-other-tips.adoc[Disks, RAM and other tips] for more details.

Minimum::

* 10GB SATA

Recommended::

* SSD w/ SATA Express, or NVMe

[discrete]
= Filesystem
:description: This section provides an overview of the system requirements for running Neo4j in a production environment. 

For proper ACID behavior, the filesystem must support flush (_fsync_, _fdatasync_).
See xref:performance/linux-file-system-tuning.adoc[Linux file system tuning] for a discussion on how to configure the filesystem in Linux for optimal performance.

Minimum::

* EXT4 (or similar)

Recommended::

* EXT4
* ZFS

[discrete]
= Software
:description: This section provides an overview of the system requirements for running Neo4j in a production environment. 

xref:installation/neo4j-desktop.adoc[Neo4j Desktop] includes a Java Virtual Machine, _JVM_, for convenience.
All other versions of Neo4j require Java to be pre-installed.
The minimum requirement is the Java Runtime Environment, _JRE_.

The Java Development Kit, _JDK_, is required in order to run some commands of the xref:tools/neo4j-admin-report.adoc[Report tool].
This is a tool that lets you send logs and performance data to Neo4j Customer Success in a convenient way, in case of a production issue.
For this reason, JDK is recommended for all production environments that allow it.

Java::

* OpenJDK 8footnote:[https://www.azul.com/downloads/zulu/[Zulu OpenJDK] or a http://openjdk.java.net/[Debian distribution].]
* http://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle Java 8]
* http://www.ibm.com/developerworks/java/jdk/[IBM Java 8]

[NOTE]
--
Java 11 is supported as a runtime platform, but any custom provided code should remain Java 8 compatible.
--

Operating Systems::

* Ubuntu 18.04, 16.04, 14.04
* Debian 10, 9, 8
* CentOS 7, 6
* Red Hat Enterprise Linux 7.9+
* Amazon Linux 2
* Windows Server 2016

Architectures::

* x86
* OpenPOWER (POWER8)
