[[windows-installation]]
= Windows installation
:description: This section describes how to install Neo4j on Windows. Check xref:installation/requirements.adoc[System Requirements] to see if your setup is suitable. 


[[windows-console]]
== Windows console application

. If it is not already installed, get link:https://openjdk.java.net/[OpenJDK 11] or link:https://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle Java 11].
. Download the latest release from {neo4j-download-center-uri}[Neo4j Download Center].
+
Select the appropriate ZIP distribution.
. Make sure to download Neo4j from {neo4j-download-center-uri}[Neo4j Download Center] and always check that the SHA hash of the downloaded file is correct:
.. To find the correct SHA hash, go to Neo4j Download Center and click on `SHA-256` which will be located below your downloaded file.
.. Using the appropriate commands for your platform, display the `SHA-256` hash for the file that you downloaded.
.. Ensure that the two are identical.
. Right-click the downloaded file, click Extract All.
. Place the extracted files in a permanent home on your server, for example `D:\neo4j\`.
The top level directory is referred to as NEO4J_HOME.
.. To run Neo4j as a console application, use: `<NEO4J_HOME>\bin\neo4j console`.
.. To install Neo4j as a service use: `<NEO4J_HOME>\bin\neo4j install-service`.
.. For additional commands and to learn about the Windows PowerShell module included in the Zip file, see xref:installation/windows.adoc#powershell[Windows PowerShell module].
. Visit http://localhost:7474 in your web browser.
. Connect using the username 'neo4j' with default password 'neo4j'.
You'll then be prompted to change the password.
. Stop the server by typing `Ctrl-C` in the console.


[[windows-service]]
== Windows service

Neo4j can also be run as a Windows service.
Install the service with `bin\neo4j install-service`, and start it with `bin\neo4j start`.

The available commands for `bin\neo4j` are: `help`, `start`, `stop`, `restart`, `status`, `install-service`, `uninstall-service`, and `update-service`.

[NOTE]
====
When installing a new release of Neo4j, you must first run `bin\neo4j uninstall-service` on any previously installed versions.
====

[[windows-update-service]]
=== Java options

When Neo4j is installed as a service, Java options are stored in the service configuration.
Changes to these options after the service is installed will not take effect until the service configuration is updated.
For example, changing the setting `dbms.memory.heap.max_size` in xref:configuration/file-locations.adoc[_neo4j.conf_] will not take effect until the service is updated and restarted.
To update the service, run `bin\neo4j update-service`.
Then restart the service to run it with the new configuration.

The same applies to the path to where Java is installed on the system.
If the path changes, for example when upgrading to a new version of Java, it is necessary to run the `update-service` command and restart the service.
Then the new Java location will be used by the service.

.Update service example
====
. Install service
+
----
bin\neo4j install-service
----

. Change memory configuration
+
----
echo dbms.memory.heap.initial_size=8g >> conf\neo4j.conf
echo dbms.memory.heap.max_size=16g >> conf\neo4j.conf
----

. Update service
+
----
bin\neo4j update-service
----

. Restart service
+
----
bin\neo4j restart
----
====


include::partial$/installation/windows/powershell.adoc[leveloffset=+1]

== Uninstall Neo4j

Here are the steps to uninstall Neo4j on Windows:

. (Optional) Create a xref:/backup-restore/index.adoc[backup] to avoid losing your data.
. Stop all Neo4j processes by using the Task Manager.
. Uninstall the Neo4j Windows service:
+
[source, shell]
---
bin\neo4j windows-service uninstall
---
. Delete _NEO4J_HOME_:
+
[source, shell]
---
rmdir NEO4J_HOME
---