:description: How to install Neo4j on Windows.
[[windows-installation]]
= Windows installation

Before you install Neo4j on Windows, check xref:installation/requirements.adoc[System Requirements] to see if your setup is suitable.


[[windows-console]]
== Windows console application

. If it is not already installed, get link:http://openjdk.java.net/[OpenJDK 17] or link:http://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle Java 17].
. Download the latest release from {neo4j-download-center-uri}[Neo4j Download Center].
+
Select the appropriate ZIP distribution.
. Make sure to download Neo4j from {neo4j-download-center-uri}[Neo4j Download Center] and always check that the SHA hash of the downloaded file is correct:
.. To find the correct SHA hash, go to Neo4j Download Center and click on `SHA-256` which will be located below your downloaded file.
.. Using the appropriate commands for your platform, display the `SHA-256` hash for the file that you downloaded.
.. Ensure that the two are identical.
. Right-click the downloaded file and click Extract All.
. Place the extracted files in a permanent home on your server, for example, `D:\neo4j\`.
The top-level directory is referred to as NEO4J_HOME.
. From Neo4j v5.4 onwards, you are required to accept either the commercial or the evaluation license agreement before running the Neo4j Enterprise Edition.
If you are using Community Edition, you can skip this step.
* Use one of the following options to accept the commercial license agreement.
See the link:https://neo4j.com/terms/licensing/[Neo4j licensing] page for details on the available agreements.
+
** Set it as an environment variable using `set NEO4J_ACCEPT_LICENSE_AGREEMENT=yes`.
** Run `<NEO4J_HOME>\bin\neo4j-admin server license --accept-commercial`
* Use one of the following options to accept the link:https://neo4j.com/terms/enterprise_us/[Neo4j Evaluation Agreement for Neo4j Software].
+
** Set it as an environment variable using `set NEO4J_ACCEPT_LICENSE_AGREEMENT=eval`.
** Run `<NEO4J_HOME>\bin\neo4j-admin server license --accept-evaluation`.
. Start Neo4j:
* To run Neo4j as a console application, use: `<NEO4J_HOME>\bin\neo4j console`.
* To install Neo4j as a service use: `<NEO4J_HOME>\bin\neo4j windows-service install`.
For additional commands and to learn about the Windows PowerShell module included in the Zip file, see xref:installation/windows.adoc#powershell[Windows PowerShell module].
. Open http://localhost:7474 in your web browser.
. Connect using the username `neo4j` with the default password `neo4j`.
You will then be prompted to change the password.
. Stop the server by typing `Ctrl-C` in the console.


[[windows-service]]
== Windows service

Neo4j can also be run as a Windows service.
Install the service with `bin\neo4j windows-service install`, and start it with `bin\neo4j start`.

The available commands for `bin\neo4j` are: `version`, `help`, `console`, `start`, `stop`, `restart`, `status`, and `windows-service`.

[NOTE]
====
When installing a new release of Neo4j, you must first run `bin\neo4j windows-service uninstall` on any previously installed versions.
====

[[windows-update-service]]
=== Java options

When Neo4j is installed as a service, Java options are stored in the service configuration.
Changes to these options after the service is installed will not take effect until the service configuration is updated.
For example, changing the setting `server.memory.heap.initial_size` in xref:configuration/file-locations.adoc[_neo4j.conf_] will not take effect until the service is updated and restarted.
To update the service, run `bin\neo4j update-service`.
Then restart the service to run it with the new configuration.
To update the service, run `bin\neo4j windows-service update`.

The same applies to the path to where Java is installed on the system.
If the path changes, for example when upgrading to a new version of Java, it is necessary to run the `update-service` command and restart the service.
Then the new Java location will be used by the service.

.Update service example
====
. Install service
+
----
bin\neo4j windows-service install
----

. Change memory configuration
+
----
echo server.memory.heap.initial_size=8g >> conf\neo4j.conf
echo server.memory.heap.initial_size=16g >> conf\neo4j.conf
----

. Update service
+
----
bin\neo4j windows-service update
----

. Restart service
+
----
bin\neo4j restart
----
====

[[powershell]]
== Windows PowerShell module

The Neo4j PowerShell module allows administrators to:

* Install, start and stop Neo4j Windows® Services.
* Start tools, such as `Neo4j Admin` and `Cypher Shell`.

The PowerShell module is installed as part of the https://neo4j.com/download/other-releases/#releases[ZIP file] distributions of Neo4j.


[[powershell-requirements]]
=== System requirements

* Requires PowerShell v2.0 or above.
* Supported on either 32 or 64 bit operating systems.


[[powershell-windows]]
=== Managing Neo4j on Windows

On Windows, it is sometimes necessary to _Unblock_ a downloaded ZIP file before you can import its contents as a module.
If you right-click on the ZIP file and choose "Properties" you will get a dialog which includes an "Unblock" button, which will enable you to import the module.

Running scripts has to be enabled on the system.
This can, for example, be achieved by executing the following from an elevated PowerShell prompt:

[source,powershell]
----
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned
----
For more information, see https://technet.microsoft.com/en-us/library/hh847748.aspx[About execution policies].

The PowerShell module will display a warning if it detects that you do not have administrative rights.


[[powershell-module-import]]
=== How do I import the module?

The module file is located in the _bin_ directory of your Neo4j installation, i.e. where you unzipped the downloaded file.
For example, if Neo4j was installed in _C:\Neo4j_ then the module would be imported like this:

[source,powershell]
----
Import-Module C:\Neo4j\bin\Neo4j-Management.psd1
----

This will add the module to the current session.

Once the module has been imported you can start an interactive console version of a Neo4j Server like this:

[source,powershell]
----
Invoke-Neo4j console
----

To stop the server, issue `Ctrl-C` in the console window that was created by the command.


[[powershell-help]]
=== How do I get help about the module?

Once the module is imported you can query the available commands like this:

[source,powershell]
----
Get-Command -Module Neo4j-Management
----

The output should be similar to the following:

[source, shell, subs="attributes"]
----
CommandType     Name                                Version    Source
-----------     ----                                -------    ------
Function        Invoke-Neo4j                        {neo4j-version-exact}      Neo4j-Management
Function        Invoke-Neo4jAdmin                   {neo4j-version-exact}      Neo4j-Management
Function        Invoke-Neo4jBackup                  {neo4j-version-exact}      Neo4j-Management
Function        Invoke-Neo4jImport                  {neo4j-version-exact}      Neo4j-Management
Function        Invoke-Neo4jShell                   {neo4j-version-exact}      Neo4j-Management
----

The module also supports the standard PowerShell help commands.

[source,powershell]
----
Get-Help Invoke-Neo4j
----

Run the following to see examples of help commands:

[source,powershell]
----
Get-Help Invoke-Neo4j -examples
----


[[powershell-examples]]
=== Example usage

* List of available commands:
+
[source,powershell]
----
Invoke-Neo4j
----

* Current status of the Neo4j service:
+
[source,powershell]
----
Invoke-Neo4j status
----

* Install the service with verbose output:
+
[source,powershell]
----
Invoke-Neo4j windows-service -Verbose
----

* Available commands for administrative tasks:
+
[source,powershell]
----
Invoke-Neo4jAdmin
----


[[powershell-common-parameters]]
=== Common PowerShell parameters

The module commands support the common PowerShell parameter of `Verbose`.
