[[windows-installation]]
= Windows installation
:description: This section describes how to install Neo4j on Windows. 


[[windows-console]]
== Windows console application

. Download the latest release from {neo4j-download-center-uri}[Neo4j Download Center].
+
Select the appropriate ZIP distribution.
. Check that the SHA hash of the downloaded file is correct:
.. To find the correct SHA hash, go to Neo4j Download Center and click on `SHA-256` which will be located below your downloaded file.
.. Using the appropriate commands for your platform, display the `SHA-256` hash for the file that you downloaded.
.. Ensure that the two are identical.
. Right-click the downloaded file, click Extract All.
. Change directory to the top-level extracted directory.
+
Run `bin\neo4j console`
. Stop the server by typing `Ctrl-C` in the console.


[[windows-service]]
== Windows service

Neo4j can also be run as a Windows service.
Install the service with `bin\neo4j install-service`, and start it with `bin\neo4j start`.

The available commands for `bin\neo4j` are: `help`, `start`, `stop`, `restart`, `status`, `install-service`, `uninstall-service`, and `update-service`.


[[windows-update-service]]
=== Java options

When Neo4j is installed as a service, Java options are stored in the service configuration.
Changes to these options after the service is installed will not take effect until the service configuration is updated.
For example, changing the setting `dbms.memory.heap.max_size` in xref:configuration/file-locations.adoc[_neo4j.conf_] will not take effect until the service is updated and restarted.
To update the service, run `bin\neo4j update-service`.
Then restart the service to run it with the new configuration.

The same applies to the path to where Java is installed on the system.
If the path changes, for example when upgrading to a new version of Java, it is necessary to run the `update-service` command and restart the service.
Then the new Java location will be used by the service.

.Update service example
====
. Install service
+
----
bin\neo4j install-service
----

. Change memory configuration
+
----
echo dbms.memory.heap.initial_size=8g >> conf\neo4j.conf
echo dbms.memory.heap.max_size=16g >> conf\neo4j.conf
----

. Update service
+
----
bin\neo4j update-service
----

. Restart service
+
----
bin\neo4j restart
----
====


include::partial$/installation/windows/powershell.adoc[leveloffset=+1]
