:description: How to install Neo4j on Windows.
[[windows-installation]]
= Windows installation

Before you install Neo4j on Windows, check xref:installation/requirements.adoc[System Requirements] to see if your setup is suitable.


[[windows-console]]
== Windows console application

. If it is not already installed, get link:https://openjdk.java.net/[OpenJDK 17] or link:https://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle Java 17].
From version 5.14 onwards, Neo4j also supports JDK 21.
. Download the latest release from {neo4j-download-center-uri}[Neo4j Deployment Center].
+
Select the appropriate ZIP distribution.
. Check that the SHA hash of the downloaded file is correct:
.. To find the correct SHA hash, go to Neo4j Deployment Center and click `SHA-256`, which is located below your downloaded file.
.. Using the appropriate commands for your platform, display the `SHA-256` hash for the file that you downloaded.
.. Ensure that the two are identical.
. Right-click the downloaded file and click *Extract All*.
. Place the extracted files in a permanent home on your server and set the environment variable `NEO4J_HOME` to point to the extracted directory, for example, `export NEO4J_HOME=\path\to\_<NEO4J_HOME>` to make it easier to refer to it later.
. xref:configuration/file-locations.adoc#file-locations-file-locations[Change the default locations] of the _data_, _conf_, _certificates_, _licenses_, and _plugins_ (if you plan to use custom plugins) directories by setting the environment variable `NEO4J_CONF` and the respective xref:configuration/configuration-settings.adoc#_server_directories_settings[`server.directories.*`] settings to point to the desired locations.
+
[NOTE]
====
Storing your Neo4j files outside `NEO4J_HOME` will simplify the upgrade process later because you will be able to replace the DBMS binaries without affecting the configuration and state.
Otherwise, these Neo4j files will remain in the old installation folder and may be accidentally overwritten during an upgrade or deleted during a subsequent uninstall.
====
. Accept either the commercial or the evaluation license agreement before running the Neo4j Enterprise Edition.
If you are using Community Edition, you can skip this step.
* Use one of the following options to accept the commercial license agreement.
See the link:https://neo4j.com/terms/licensing/[Neo4j licensing] page for details on the available agreements.
+
** Set it as an environment variable using `set NEO4J_ACCEPT_LICENSE_AGREEMENT=yes`.
** Run `$NEO4J_HOME\bin\neo4j-admin server license --accept-commercial`
* Use one of the following options to accept the link:https://neo4j.com/terms/enterprise_us/[Neo4j Evaluation Agreement for Neo4j Software].
+
** Set it as an environment variable using `set NEO4J_ACCEPT_LICENSE_AGREEMENT=eval`.
** Run `$NEO4J_HOME\bin\neo4j-admin server license --accept-evaluation`.
. Before starting up the database for the first time, it is recommended to use the `set-initial-password` command of `neo4j-admin` to define the password for the native user `neo4j`.
+
If the password is not set explicitly using this method, it will be set to the default password `neo4j`.
In that case, you will be prompted to change the default password at first login. +
For more information, see xref:configuration/set-initial-password.adoc[].
. Start Neo4j:
* To run Neo4j as a console application, use: `$NEO4J_HOME\bin\neo4j console`.
* To install Neo4j as a service use: `$NEO4J_HOME\bin\neo4j windows-service install`.
For additional commands and to learn about the Windows PowerShell module included in the Zip file, see xref:installation/windows.adoc#powershell[Windows PowerShell module].
. Open _\http://localhost:7474/_ in your web browser.
. Connect using the username `neo4j` with your password or the default password `neo4j`.
You will then be prompted to change the password.
. Stop the server by typing `Ctrl-C` in the console.


[[windows-service]]
== Windows service

Neo4j can also be run as a Windows service.

[WARNING]
====
By default, the Neo4j Windows service runs as the LocalSystem account, which has full access to the system.
This is a security risk, and it is recommended to run the service as a user without full LocalSystem privileges.
====

=== Install the Windows service

Install the service with `bin\neo4j windows-service install`, and start it with `bin\neo4j start`.

The available commands for `bin\neo4j` are: `version`, `help`, `console`, `start`, `stop`, `restart`, `status`, and `windows-service`.

[NOTE]
====
When installing a new release of Neo4j, you must first run `bin\neo4j windows-service uninstall` on any previously installed versions.
====

[[windows-update-service]]
=== Change the Windows service configuration

When Neo4j is installed as a service, the Java options are stored in the service configuration file.
If you want to change any of these options or environment variables after the service is installed, you must update and restart the service for the changes to take effect.
For example, updating the value of `server.memory.heap.initial_size` in the default xref:configuration/file-locations.adoc[_neo4j.conf_] file or by using the `NEO4J_CONF` environment variable will not automatically apply the changes.
The service needs to be updated and restarted to pick them up.
To update the service, run `bin\neo4j windows-service update`.
Then restart the service to run it with the new configuration.

The same applies to the path to where Java is installed on the system.
If the path changes, for example when upgrading to a new version of Java, it is necessary to run the `update-service` command and restart the service.
Then, the new Java location will be used by the service.

.Update service example
====
. Install service
+
----
bin\neo4j windows-service install
----

. Change memory configuration
+
----
echo server.memory.heap.initial_size=8g >> conf\neo4j.conf
echo server.memory.heap.initial_size=16g >> conf\neo4j.conf
----

. Update service
+
----
bin\neo4j windows-service update
----

. Restart service
+
----
bin\neo4j restart
----
====

[[powershell]]
== Windows PowerShell module

The Neo4j PowerShell module allows administrators to:

* Install, start, and stop Neo4j Windows® Services.
* Start tools, such as `Neo4j Admin` and `Cypher Shell`.

The PowerShell module is installed as part of the https://neo4j.com/deployment-center/[ZIP file] distributions of Neo4j.


[[powershell-requirements]]
=== System requirements

* Requires PowerShell v2.0 or above.
* Supported on either 32 or 64-bit operating systems.


[[powershell-windows]]
=== Manage Neo4j on Windows

On Windows, it is sometimes necessary to _Unblock_ a downloaded ZIP file before you can import its contents as a module.

. Right-click on the ZIP file and choose *Properties*. +
A dialog appears with an *Unblock* button.
. Click the *Unblock* button to enable the import of the module.
+
Running scripts has to be enabled on the system.
This can, for example, be achieved by executing the following from an elevated PowerShell prompt:
+
[source,powershell]
----
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned
----
+
For more information, see https://technet.microsoft.com/en-us/library/hh847748.aspx[About execution policies].

The PowerShell module displays a warning if it detects that you do not have administrative rights.


[[powershell-module-import]]
=== Import the module file

The module file is located in the _bin_ directory of your Neo4j installation.

. Assuming that Neo4j is installed in _C:\Neo4j_, run the following command to import the module:
+
[source,powershell]
----
Import-Module C:\Neo4j\bin\Neo4j-Management.psd1
----
+
This adds the module to the current session.

. Once the module is imported, you can start an interactive console version of a Neo4j Server:
+
[source,powershell]
----
Invoke-Neo4j console
----

To stop the server, use `Ctrl-C` in the console window, created by the command.


[[powershell-help]]
=== Inspect the module

You can get all available commands in the module by running the following command:

[source,powershell]
----
Get-Command -Module Neo4j-Management
----

The output should be similar to the following:

[source, shell, subs="attributes"]
----
CommandType     Name                                Version    Source
-----------     ----                                -------    ------
Function        Invoke-Neo4j                        {neo4j-version-exact}      Neo4j-Management
Function        Invoke-Neo4jAdmin                   {neo4j-version-exact}      Neo4j-Management
Function        Invoke-Neo4jBackup                  {neo4j-version-exact}      Neo4j-Management
Function        Invoke-Neo4jImport                  {neo4j-version-exact}      Neo4j-Management
Function        Invoke-Neo4jShell                   {neo4j-version-exact}      Neo4j-Management
----

The module also supports the standard PowerShell help commands

[source,powershell]
----
Get-Help Invoke-Neo4j
----

Run the following to see examples of help commands:

[source,powershell]
----
Get-Help Invoke-Neo4j -examples
----


[[powershell-examples]]
=== Example usage

* List of available commands:
+
[source,powershell]
----
Invoke-Neo4j
----

* Current status of the Neo4j service:
+
[source,powershell]
----
Invoke-Neo4j status
----

* Install the service with verbose output:
+
[source,powershell]
----
Invoke-Neo4j windows-service -Verbose
----

* Available commands for administrative tasks:
+
[source,powershell]
----
Invoke-Neo4jAdmin
----


[[powershell-common-parameters]]
=== Common PowerShell parameters

The module commands support the common PowerShell parameter of `Verbose`.

== Uninstall Neo4j

Here are the steps to uninstall Neo4j on Windows:

. (Optional) Create a xref:/backup-restore/index.adoc[backup] to avoid losing your data.
. Stop all Neo4j processes by using the Task Manager.
. Uninstall the Neo4j Windows service:
+
[source, shell]
---
bin\neo4j windows-service uninstall
---
. Delete _NEO4J_HOME_:
+
[source, shell]
---
rmdir NEO4J_HOME
---