:description: How to install Neo4j on Windows.
[[windows-installation]]
= Windows installation

Before you install Neo4j on Windows, check xref:installation/requirements.adoc[System Requirements] to see if your setup is suitable.


[[windows-console]]
== Windows console application

. If it is not already installed, get link:http://openjdk.java.net/[OpenJDK 17] or link:http://www.oracle.com/technetwork/java/javase/downloads/index.html[Oracle Java 17].
. Download the latest release from {neo4j-download-center-uri}[Neo4j Download Center].
+
Select the appropriate ZIP distribution.
. Make sure to download Neo4j from {neo4j-download-center-uri}[Neo4j Download Center] and always check that the SHA hash of the downloaded file is correct:
.. To find the correct SHA hash, go to Neo4j Download Center and click on `SHA-256` which will be located below your downloaded file.
.. Using the appropriate commands for your platform, display the `SHA-256` hash for the file that you downloaded.
.. Ensure that the two are identical.
. Right-click the downloaded file, click Extract All.
. Place the extracted files in a permanent home on your server, for example `D:\neo4j\`.
The top level directory is referred to as NEO4J_HOME.
.. To run Neo4j as a console application, use: `<NEO4J_HOME>\bin\neo4j console`.
.. To install Neo4j as a service use: `<NEO4J_HOME>\bin\neo4j windows-service install`.
.. For additional commands and to learn about the Windows PowerShell module included in the Zip file, see xref:installation/windows.adoc#powershell[Windows PowerShell module].
. Visit http://localhost:7474 in your web browser.
. Connect using the username 'neo4j' with default password 'neo4j'.
You'll then be prompted to change the password.
. Stop the server by typing `Ctrl-C` in the console.


[[windows-service]]
== Windows service

Neo4j can also be run as a Windows service.
Install the service with `bin\neo4j windows-service install`, and start it with `bin\neo4j start`.

The available commands for `bin\neo4j` are: `version``, `help`, `console`, `start`, `stop`, `restart`, `status`, and `windows-service`.

[NOTE]
====
When installing a new release of Neo4j, you must first run `bin\neo4j windows-service uninstall` on any previously installed versions.
====

[[windows-update-service]]
=== Java options

When Neo4j is installed as a service, Java options are stored in the service configuration.
Changes to these options after the service is installed will not take effect until the service configuration is updated.
<<<<<<< HEAD:modules/ROOT/pages/installation/windows.adoc
For example, changing the setting `server.memory.heap.initial_size` in xref:configuration/file-locations.adoc[_neo4j.conf_] will not take effect until the service is updated and restarted.
To update the service, run `bin\neo4j windows-service update`.
=======
For example, changing the setting `server.memory.heap.initial_size` in <<file-locations, _neo4j.conf_>> will not take effect until the service is updated and restarted.
Then restart the service to run it with the new configuration.

----
bin\neo4j windows-service install
----

. Change memory configuration
+
----
echo server.memory.heap.initial_size=8g >> conf\neo4j.conf
echo server.memory.heap.initial_size=16g >> conf\neo4j.conf
----

. Update service
+
----
bin\neo4j windows-service update
----

. Restart service
+
----
bin\neo4j restart
----
====


include::partial$/installation/windows/powershell.adoc[leveloffset=+1]
