[role=enterprise-edition]
[[dynamic-settings-reference]]
= Dynamic configuration settings
:description: This page provides a complete reference to the Neo4j dynamic configuration settings. 


This page provides a complete reference to the Neo4j dynamic configuration settings, which can be changed at runtime, without restarting the service.

[NOTE]
====
Changes to the configuration at runtime are not persisted.
To avoid losing changes when restarting Neo4j, make sure you update xref:configuration/file-locations.adoc[_neo4j.conf_] as well.

In a clustered environment, `CALL dbms.setConfigValue` affects only the server it is run against, and it is not propagated to other members.
If you want to change the configuration settings on all cluster members, you have to run the procedure against each of them and update their _neo4j.conf_ file.

For more information on how to update dynamic configuration settings, see xref:configuration/dynamic-settings.adoc[Update dynamic settings].
====

include::partial$/neo4j-config/dynamic-settings.adoc[]

