[[neo4j-procedures]]
= Procedures
:description: This section provides a complete reference to the Neo4j procedures. 

:decription: Reference for Neo4j procedures.

== Procedures, editions and modes

Available procedures depends on the type of installation you have:

* Neo4j Enterprise Edition provides a larger set of procedures than Neo4j Community Edition.
* Cluster members have procedures that are not available in standalone mode.

To check which procedures are available in your Neo4j instance, use xref:reference/procedures.adoc#procedure_dbms_procedures[`dbms.procedures()`].


.List available procedures
====
To list the procedures available on your particular installation, run the following Cypher query:

[source, cypher]
----
CALL dbms.procedures()
----
====


== List of procedures

.Neo4j procedures
[options=header, cols="<70,<30"]
|===
| Name |

| xref:reference/procedures.adoc#procedure_db_awaitindex[`db.awaitIndex()`]
|

| xref:reference/procedures.adoc#procedure_db_awaitindexes[`db.awaitIndexes()`]
|

| xref:reference/procedures.adoc#procedure_db_checkpoint[`db.checkpoint()`]
| [enterprise-edition]#&#32;#

| xref:reference/procedures.adoc#procedure_db_clearquerycaches[`db.clearQueryCaches()`]
|

// Signature changed in 4.1
// db.constraints() :: (name :: STRING?, description :: STRING?, details :: STRING?)
// Deprecated in 4.2
// Replaced by Cypher: SHOW CONSTRAINTS
| xref:reference/procedures.adoc#procedure_db_constraints[`db.constraints()`]
| [deprecated]#&#32;#

// Deprecated in 4.2
// Replaced by Cypher: CREATE INDEX
| xref:reference/procedures.adoc#procedure_db_createindex[`db.createIndex()`]
| [deprecated]#&#32;#

| xref:reference/procedures.adoc#procedure_db_createlabel[`db.createLabel()`]
|

// Deprecated in 4.2
// Replaced by Cypher: CREATE CONSTRAINT ... IS NODE KEY
| xref:reference/procedures.adoc#procedure_db_createnodekey[`db.createNodeKey()`]
| [enterprise-edition]#&#32;# [deprecated]#&#32;#

| xref:reference/procedures.adoc#procedure_db_createproperty[`db.createProperty()`]
|

| xref:reference/procedures.adoc#procedure_db_createrelationshiptype[`db.createRelationshipType()`]
|

// Deprecated in 4.2
// Replaced by Cypher: CREATE CONSTRAINT ... IS UNIQUE
| xref:reference/procedures.adoc#procedure_db_createuniquepropertyconstraint[`db.createUniquePropertyConstraint()`]
| [deprecated]#&#32;#

| xref:reference/procedures.adoc#procedure_db_index_fulltext_awaiteventuallyconsistentindexrefresh[`db.index.fulltext.awaitEventuallyConsistentIndexRefresh()`]
|

| xref:reference/procedures.adoc#procedure_db_index_fulltext_createnodeindex[`db.index.fulltext.createNodeIndex()`]
|

| xref:reference/procedures.adoc#procedure_db_index_fulltext_createrelationshipindex[`db.index.fulltext.createRelationshipIndex()`]
|

| xref:reference/procedures.adoc#procedure_db_index_fulltext_drop[`db.index.fulltext.drop()`]
|

| xref:reference/procedures.adoc#procedure_db_index_fulltext_listavailableanalyzers[`db.index.fulltext.listAvailableAnalyzers()`]
|

// Signature changed in 4.1
// db.index.fulltext.queryNodes(indexName :: STRING?, queryString :: STRING?, options = {} :: MAP?) :: (node :: NODE?, score :: FLOAT?)
| xref:reference/procedures.adoc#procedure_db_index_fulltext_querynodes[`db.index.fulltext.queryNodes()`]
|

// Signature changed in 4.1
// db.index.fulltext.queryRelationships(indexName :: STRING?, queryString :: STRING?, options = {} :: MAP?) :: (relationship :: RELATIONSHIP?, score :: FLOAT?)
| xref:reference/procedures.adoc#procedure_db_index_fulltext_queryrelationships[`db.index.fulltext.queryRelationships()`]
|

// Deprecated in 4.2
// Replaced by Cypher: SHOW INDEXES VERBOSE OUTPUT
| xref:reference/procedures.adoc#procedure_db_indexdetails[`db.indexDetails()`]
| [deprecated]#&#32;#

// Deprecated in 4.2
// Replaced by Cypher: SHOW INDEXES
| xref:reference/procedures.adoc#procedure_db_indexes[`db.indexes()`]
| [deprecated]#&#32;#

| xref:reference/procedures.adoc#procedure_db_info[`db.info()`]
|

| xref:reference/procedures.adoc#procedure_db_labels[`db.labels()`]
|

// Signature changed in 4.2
// db.listLocks() :: (mode :: STRING?, resourceType :: STRING?, resourceId :: INTEGER?, transactionId :: STRING?)
| xref:reference/procedures.adoc#procedure_db_listlocks[`db.listLocks()`]
| [enterprise-edition]#&#32;#

| xref:reference/procedures.adoc#procedure_db_ping[`db.ping()`]
|

// Bugfix in 4.0
// Default users are: admin
| xref:reference/procedures.adoc#procedure_db_prepareforreplanning[`db.prepareForReplanning()`]
|

| xref:reference/procedures.adoc#procedure_db_propertykeys[`db.propertyKeys()`]
|

| xref:reference/procedures.adoc#procedure_db_relationshiptypes[`db.relationshipTypes()`]
|

| xref:reference/procedures.adoc#procedure_db_resampleindex[`db.resampleIndex()`]
|

| xref:reference/procedures.adoc#procedure_db_resampleoutdatedindexes[`db.resampleOutdatedIndexes()`]
|

| xref:reference/procedures.adoc#procedure_db_schema_nodetypeproperties[`db.schema.nodeTypeProperties()`]
|

| xref:reference/procedures.adoc#procedure_db_schema_reltypeproperties[`db.schema.relTypeProperties()`]
|

| xref:reference/procedures.adoc#procedure_db_schema_visualization[`db.schema.visualization()`]
|

// Deprecated in 4.2
// Replaced by Cypher: SHOW INDEXES VERBOSE OUTPUT
// Replaced by Cypher: SHOW CONSTRAINTS VERBOSE OUTPUT
| xref:reference/procedures.adoc#procedure_db_schemastatements[`db.schemaStatements()`]
| [deprecated]#&#32;#

// Bugfix in 4.0
// Default users are: admin
| xref:reference/procedures.adoc#procedure_db_stats_clear[`db.stats.clear()`]
|

// Bugfix in 4.0
// Default users are: admin
| xref:reference/procedures.adoc#procedure_db_stats_collect[`db.stats.collect()`]
|

// Bugfix in 4.0
// Default users are: admin
| xref:reference/procedures.adoc#procedure_db_stats_retrieve[`db.stats.retrieve()`]
|

// Bugfix in 4.0
// Default users are: admin
| xref:reference/procedures.adoc#procedure_db_stats_retrieveallanonymized[`db.stats.retrieveAllAnonymized()`]
|

// Bugfix in 4.0
// Default users are: admin
| xref:reference/procedures.adoc#procedure_db_stats_status[`db.stats.status()`]
|

// Bugfix in 4.0
// Default users are: admin
| xref:reference/procedures.adoc#procedure_db_stats_stop[`db.stats.stop()`]
|

// Clustering is an Enterprise feature, the naming is weird.
// dbms.routing.getRoutingTable() does the same thing.
| xref:reference/procedures.adoc#procedure_dbms_cluster_routing_getroutingtable[`dbms.cluster.routing.getRoutingTable()`]
|

// New in 4.0
// com.neo4j.causaulclustering.discovery.procedures.ClusterOverviewProcedure
| xref:reference/procedures.adoc#procedure_dbms_cluster_overview[`dbms.cluster.overview()`]
| [enterprise-edition]#&#32;#

// New in 4.0
// com.neo4j.causaulclustering.discovery.procedures.InstalledProtocolsProcedure
| xref:reference/procedures.adoc#procedure_dbms_cluster_protocols[`dbms.cluster.protocols()`]
| [enterprise-edition]#&#32;#

// New in 4.2
// com.neo4j.dbms.procedures.QuarantineProcedure
| xref:reference/procedures.adoc#procedure_dbms_cluster_quarantinedatabase[`dbms.cluster.quarantineDatabase()`]
| [enterprise-edition]#&#32;#

// New in 4.2
// com.neo4j.causaulclustering.discovery.procedures.ReadReplicaToggleProcedure
| xref:reference/procedures.adoc#procedure_dbms_cluster_readreplicatoggle[`dbms.cluster.readReplicaToggle()`]
| [enterprise-edition]#&#32;#

// New in 4.0
// com.neo4j.causaulclustering.discovery.procedures.RoleProcedure
| xref:reference/procedures.adoc#procedure_dbms_cluster_role[`dbms.cluster.role()`]
| [enterprise-edition]#&#32;#

// New in 4.1
// com.neo4j.dbms.procedures.ClusterSetDefaultDatabaseProcedure
| xref:reference/procedures.adoc#procedure_dbms_cluster_setdefaultdatabase[`dbms.cluster.setDefaultDatabase()`]
| [enterprise-edition]#&#32;#

| xref:reference/procedures.adoc#procedure_dbms_components[`dbms.components()`]
|

| xref:reference/procedures.adoc#procedure_dbms_database_state[`dbms.database.state()`]
|

// Signature changed in 4.2
// dbms.functions() :: (name :: STRING?, signature :: STRING?, category :: STRING?, description :: STRING?, aggregating :: BOOLEAN?, defaultBuiltInRoles :: LIST? OF STRING?)
| xref:reference/procedures.adoc#procedure_dbms_functions[`dbms.functions()`]
|

| xref:reference/procedures.adoc#procedure_dbms_info[`dbms.info()`]
|

// Community Edition in 4.2
| xref:reference/procedures.adoc#procedure_dbms_killconnection[`dbms.killConnection()`]
|

// Community Edition in 4.2
| xref:reference/procedures.adoc#procedure_dbms_killconnections[`dbms.killConnections()`]
|

// Community Edition in 4.2
| xref:reference/procedures.adoc#procedure_dbms_killqueries[`dbms.killQueries()`]
|

// Community Edition in 4.2
| xref:reference/procedures.adoc#procedure_dbms_killquery[`dbms.killQuery()`]
|

// Community Edition in 4.2
| xref:reference/procedures.adoc#procedure_dbms_killtransaction[`dbms.killTransaction()`]
|

// Community Edition in 4.2
| xref:reference/procedures.adoc#procedure_dbms_killtransactions[`dbms.killTransactions()`]
|

| xref:reference/procedures.adoc#procedure_dbms_listactivelocks[`dbms.listActiveLocks()`]
|

| xref:reference/procedures.adoc#procedure_dbms_listConfig[`dbms.listConfig()`]
|

// Community Edition in 4.2
| xref:reference/procedures.adoc#procedure_dbms_listconnections[`dbms.listConnections()`]
|

// New in 4.1
| xref:reference/procedures.adoc#procedure_dbms_listpools[`dbms.listPools()`]
| [enterprise-edition]#&#32;#

// Changed in 4.1
// The queryId procedure format has changed, and no longer includes the database name.
// For example, mydb-query-123 is now query-123.
// Community Edition in 4.2
| xref:reference/procedures.adoc#procedure_dbms_listqueries[`dbms.listQueries()`]
|

// Signature changed in 4.1
// dbms.listTransactions() :: (transactionId :: STRING?, username :: STRING?, metaData :: MAP?, startTime :: STRING?, protocol :: STRING?, clientAddress :: STRING?, requestUri :: STRING?, currentQueryId :: STRING?, currentQuery :: STRING?, activeLockCount :: INTEGER?, status :: STRING?, resourceInformation :: MAP?, elapsedTimeMillis :: INTEGER?, cpuTimeMillis :: INTEGER?, waitTimeMillis :: INTEGER?, idleTimeMillis :: INTEGER?, allocatedBytes :: INTEGER?, allocatedDirectBytes :: INTEGER?, pageHits :: INTEGER?, pageFaults :: INTEGER?, connectionId :: STRING?, initializationStackTrace :: STRING?, database :: STRING?, estimatedUsedHeapMemory :: INTEGER?)
// Community Edition in 4.2
| xref:reference/procedures.adoc#procedure_dbms_listtransactions[`dbms.listTransactions()`]
|

| xref:reference/procedures.adoc#procedure_dbms_procedures[`dbms.procedures()`]
|

| xref:reference/procedures.adoc#procedure_dbms_queryjmx[`dbms.queryJmx()`]
|

| xref:reference/procedures.adoc#procedure_dbms_routing_getroutingtable[`dbms.routing.getRoutingTable()`]
|

// New in 4.2
| xref:reference/procedures.adoc#procedure_dbms_scheduler_failedjobs[`dbms.scheduler.failedJobs()`]
| [enterprise-edition]#&#32;#

| xref:reference/procedures.adoc#procedure_dbms_scheduler_groups[`dbms.scheduler.groups()`]
| [enterprise-edition]#&#32;#

// New in 4.2
| xref:reference/procedures.adoc#procedure_dbms_scheduler_jobs[`dbms.scheduler.jobs()`]
| [enterprise-edition]#&#32;#

| xref:reference/procedures.adoc#procedure_dbms_scheduler_profile[`dbms.scheduler.profile()`]
| [enterprise-edition]#&#32;#

// Deprecated in 4.0
// Replaced by Cypher: ALTER USER
// Changed in 4.1
// Mode is now WRITE
| xref:reference/procedures.adoc#procedure_dbms_security_activateuser[`dbms.security.activateUser()`]
| [enterprise-edition]#&#32;# [deprecated]#&#32;#

// Deprecated in 4.0
// Replaced by Cypher: GRANT ROLE TO USER
// Changed in 4.1
// Mode is now WRITE
| xref:reference/procedures.adoc#procedure_dbms_security_addroletouser[`dbms.security.addRoleToUser()`]
| [enterprise-edition]#&#32;# [deprecated]#&#32;#

// Deprecated in 4.0
// Replaced by Cypher: ALTER CURRENT USER SET PASSWORD
// Changed in 4.1
// Mode is now WRITE
// newSet( READER, EDITOR, PUBLISHER, ARCHITECT, ADMIN )
| xref:reference/procedures.adoc#procedure_dbms_security_changepassword[`dbms.security.changePassword()`]
| [deprecated]#&#32;#

// Deprecated in 4.0
// Replaced by Cypher: ALTER USER
// Changed in 4.1
// Mode is now WRITE
| xref:reference/procedures.adoc#procedure_dbms_security_changeuserpassword[`dbms.security.changeUserPassword()`]
| [enterprise-edition]#&#32;# [deprecated]#&#32;#

| xref:reference/procedures.adoc#procedure_dbms_security_clearauthcache[`dbms.security.clearAuthCache()`]
| [enterprise-edition]#&#32;#

// Deprecated in 4.0
// Replaced by Cypher: CREATE ROLE
// Changed in 4.1
// Mode is now WRITE
| xref:reference/procedures.adoc#procedure_dbms_security_createrole[`dbms.security.createRole()`]
| [enterprise-edition]#&#32;# [deprecated]#&#32;#

// Deprecated in 4.0
// Replaced by Cypher: CREATE USER
// Changed in 4.1
// Mode is now WRITE
| xref:reference/procedures.adoc#procedure_dbms_security_createuser[`dbms.security.createUser()`]
| [deprecated]#&#32;#

// Deprecated in 4.0
// Replaced by Cypher: DROP ROLE
// Changed in 4.1
// Mode is now WRITE
| xref:reference/procedures.adoc#procedure_dbms_security_deleterole[`dbms.security.deleteRole()`]
| [enterprise-edition]#&#32;# [deprecated]#&#32;#

// Deprecated in 4.0
// Replaced by Cypher: DROP USER
// Changed in 4.1
// Mode is now WRITE
| xref:reference/procedures.adoc#procedure_dbms_security_deleteuser[`dbms.security.deleteUser()`]
| [deprecated]#&#32;#

// Deprecated in 4.0
// Replaced by Cypher: SHOW ROLES
// Changed in 4.1
// Mode is now READ
| xref:reference/procedures.adoc#procedure_dbms_security_listroles[`dbms.security.listRoles()`]
| [enterprise-edition]#&#32;# [deprecated]#&#32;#

// Deprecated in 4.0
// Replaced by Cypher: SHOW USERS
// Changed in 4.1
// Mode is now READ
| xref:reference/procedures.adoc#procedure_dbms_security_listrolesforuser[`dbms.security.listRolesForUser()`]
| [enterprise-edition]#&#32;# [deprecated]#&#32;#

// Deprecated in 4.0
// Replaced by Cypher: SHOW USERS
// Changed in 4.1
// Mode is now READ
| xref:reference/procedures.adoc#procedure_dbms_security_listusers[`dbms.security.listUsers()`]
| [deprecated]#&#32;#

// Deprecated in 4.0
// Replaced by Cypher: SHOW ROLES WITH USERS
// Changed in 4.1
// Mode is now READ
| xref:reference/procedures.adoc#procedure_dbms_security_listusersforrole[`dbms.security.listUsersForRole()`]
| [enterprise-edition]#&#32;# [deprecated]#&#32;#

// Deprecated in 4.0
// Replaced by Cypher: REVOKE ROLE FROM USER
// Changed in 4.1
// Mode is now WRITE
| xref:reference/procedures.adoc#procedure_dbms_security_removerolefromuser[`dbms.security.removeRoleFromUser()`]
| [enterprise-edition]#&#32;# [deprecated]#&#32;#

// Deprecated in 4.0
// Replaced by Cypher: ALTER USER
// Changed in 4.1
// Mode is now WRITE
| xref:reference/procedures.adoc#procedure_dbms_security_suspenduser[`dbms.security.suspendUser()`]
| [enterprise-edition]#&#32;# [deprecated]#&#32;#

| xref:reference/procedures.adoc#procedure_dbms_setconfigvalue[`dbms.setConfigValue()`]
| [enterprise-edition]#&#32;#

| xref:reference/procedures.adoc#procedure_dbms_showcurrentuser[`dbms.showCurrentUser()`]
|

// New in 4.1
| xref:reference/procedures.adoc#procedure_dbms_upgrade[`dbms.upgrade()`]
|

// New in 4.1
| xref:reference/procedures.adoc#procedure_dbms_upgradestatus[`dbms.upgradeStatus()`]
|

| xref:reference/procedures.adoc#procedure_tx_getmetadata[`tx.getMetaData()`]
|

| xref:reference/procedures.adoc#procedure_tx_setmetadata[`tx.setMetaData()`]
|

|===


== Procedure descriptions


[NOTE]
====
The role-based access control is an Enterprise Edition feature.

Each procedure lists the default roles that can access the procedure.
====


[[procedure_db_awaitindex]]
.db.awaitIndex()
[cols="<15s,<85"]
|===
| Description
a|
Wait for an index to come online.

Example: `CALL db.awaitIndex("MyIndex", 300)`
| Signature
m| db.awaitIndex(indexName :: STRING?, timeOutSeconds = 300 :: INTEGER?) :: VOID
| Mode
m| READ
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_db_awaitindexes]]
.db.awaitIndexes()
[cols="<15s,<85"]
|===
| Description
a|
Wait for all indexes to come online.

Example: `CALL db.awaitIndexes(300))`
| Signature
m| db.awaitIndexes(timeOutSeconds = 300 :: INTEGER?) :: VOID
| Mode
m| READ
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_db_checkpoint]]
.[enterprise-edition]#db.checkpoint()#
[cols="<15s,<85"]
|===
| Description
a|
Initiate and wait for a new check point, or wait any already on-going check point to complete.

Note that this temporarily disables the `dbms.checkpoint.iops.limit` setting in order to make the check point complete faster.
This might cause transaction throughput to degrade slightly, due to increased IO load.
| Signature
m| db.checkpoint() :: (success :: BOOLEAN?, message :: STRING?)
| Mode
m| DBMS
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_db_clearquerycaches]]
.db.clearQueryCaches()
[cols="<15s,<85"]
|===
| Description
a|
Clears all query caches.
| Signature
m| db.clearQueryCaches() :: (value :: STRING?)
| Mode
m| DBMS
| Default roles
m| admin
|===


[[procedure_db_constraints]]
.[deprecated]#db.constraints()#
[cols="<15s,<85"]
|===
| Description
a|
List all constraints in the database.
| Signature
m| db.constraints() :: (name :: STRING?, description :: STRING?, details :: STRING?)
| Mode
m| READ
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_db_createindex]]
.[deprecated]#db.createIndex()#
[cols="<15s,<85"]
|===
| Description
a|
Create a named schema index with specified index provider and configuration (optional).

Yield: name, labels, properties, providerName, status
| Signature
m| db.createIndex(indexName :: STRING?, labels :: LIST? OF STRING?, properties :: LIST? OF STRING?, providerName :: STRING?, config = {} :: MAP?) :: (name :: STRING?, labels :: LIST? OF STRING?, properties :: LIST? OF STRING?, providerName :: STRING?, status :: STRING?)
| Mode
m| SCHEMA
| Default roles
m| architect, admin
|===


[[procedure_db_createlabel]]
.db.createLabel()
[cols="<15s,<85"]
|===
| Description
a|
Create a label
| Signature
m| db.createLabel(newLabel :: STRING?) :: VOID
| Mode
m| WRITE
| Default roles
m| publisher, architect, admin
|===


[[procedure_db_createnodekey]]
.[enterprise-edition]#db.createNodeKey()# [deprecated]#&#32;#
[cols="<15s,<85"]
|===
| Description
a|
Create a named node key constraint.
Backing index will use specified index provider and configuration (optional).

Yield: name, labels, properties, providerName, status
| Signature
m| db.createNodeKey(constraintName :: STRING?, labels :: LIST? OF STRING?, properties :: LIST? OF STRING?, providerName :: STRING?, config = {} :: MAP?) :: (name :: STRING?, labels :: LIST? OF STRING?, properties :: LIST? OF STRING?, providerName :: STRING?, status :: STRING?)
| Mode
m| SCHEMA
| Default roles
m| architect, admin
|===


[[procedure_db_createproperty]]
.db.createProperty()
[cols="<15s,<85"]
|===
| Description
a|
Create a Property
| Signature
m| db.createProperty(newProperty :: STRING?) :: VOID
| Mode
m| WRITE
| Default roles
m| publisher, architect, admin
|===


[[procedure_db_createrelationshiptype]]
.db.createRelationshipType()
[cols="<15s,<85"]
|===
| Description
a|
Create a RelationshipType
| Signature
m| db.createRelationshipType(newRelationshipType :: STRING?) :: VOID
| Mode
m| WRITE
| Default roles
m| publisher, architect, admin
|===


[[procedure_db_createuniquepropertyconstraint]]
.[deprecated]#db.createUniquePropertyConstraint()#
[cols="<15s,<85"]
|===
| Description
a|
Create a named unique property constraint.

Backing index will use specified index provider and configuration (optional).

Yield: name, labels, properties, providerName, status
| Signature
m| db.createUniquePropertyConstraint(constraintName :: STRING?, labels :: LIST? OF STRING?, properties :: LIST? OF STRING?, providerName :: STRING?, config = {} :: MAP?) :: (name :: STRING?, labels :: LIST? OF STRING?, properties :: LIST? OF STRING?, providerName :: STRING?, status :: STRING?)
| Mode
m| SCHEMA
| Default roles
m| architect, admin
|===


[[procedure_db_index_fulltext_awaiteventuallyconsistentindexrefresh]]
.db.index.fulltext.awaitEventuallyConsistentIndexRefresh()
[cols="<15s,<85"]
|===
| Description
a|
Wait for the updates from recently committed transactions to be applied to any eventually-consistent full-text indexes.
| Signature
m| db.index.fulltext.awaitEventuallyConsistentIndexRefresh() :: VOID
| Mode
m| READ
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_db_index_fulltext_createnodeindex]]
.db.index.fulltext.createNodeIndex()
[cols="<15s,<85"]
|===
| Description
a|
Create a node full-text index for the given labels and properties.

The optional 'config' map parameter can be used to supply settings to the index. Supported settings are 'analyzer', for specifying what analyzer to use when indexing and querying. Use the `db.index.fulltext.listAvailableAnalyzers` procedure to see what options are available. And 'eventually_consistent' which can be set to 'true' to make this index eventually consistent, such that updates from committing transactions are applied in a background thread.
| Signature
m| db.index.fulltext.createNodeIndex(indexName :: STRING?, labels :: LIST? OF STRING?, properties :: LIST? OF STRING?, config = {} :: MAP?) :: VOID
| Mode
m| SCHEMA
| Default roles
m| architect, admin
|===


[[procedure_db_index_fulltext_createrelationshipindex]]
.db.index.fulltext.createRelationshipIndex()
[cols="<15s,<85"]
|===
| Description
a|
Create a relationship full-text index for the given relationship types and properties.

The optional 'config' map parameter can be used to supply settings to the index. Supported settings are 'analyzer', for specifying what analyzer to use when indexing and querying. Use the `db.index.fulltext.listAvailableAnalyzers` procedure to see what options are available. And 'eventually_consistent' which can be set to 'true' to make this index eventually consistent, such that updates from committing transactions are applied in a background thread.
| Signature
m| db.index.fulltext.createRelationshipIndex(indexName :: STRING?, relationshipTypes :: LIST? OF STRING?, properties :: LIST? OF STRING?, config = {} :: MAP?) :: VOID
| Mode
m| SCHEMA
| Default roles
m| architect, admin
|===


[[procedure_db_index_fulltext_drop]]
.db.index.fulltext.drop()
[cols="<15s,<85"]
|===
| Description
a|
Drop the specified index.
| Signature
m| db.index.fulltext.drop(indexName :: STRING?) :: VOID
| Mode
m| SCHEMA
| Default roles
m| architect, admin
|===


[[procedure_db_index_fulltext_listavailableanalyzers]]
.db.index.fulltext.listAvailableAnalyzers()
[cols="<15s,<85"]
|===
| Description
a|
List the available analyzers that the full-text indexes can be configured with.
| Signature
m| db.index.fulltext.listAvailableAnalyzers() :: (analyzer :: STRING?, description :: STRING?, stopwords :: LIST? OF STRING?)
| Mode
m| READ
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_db_index_fulltext_querynodes]]
.db.index.fulltext.queryNodes()
[cols="<15s,<85"]
|===
| Description
a|
Query the given full-text index.

Returns the matching nodes, and their Lucene query score, ordered by score.

Valid keys for the options map are: 'skip' to skip the top N results; 'limit' to limit the number of results returned.
| Signature
m| db.index.fulltext.queryNodes(indexName :: STRING?, queryString :: STRING?, options = {} :: MAP?) :: (node :: NODE?, score :: FLOAT?)
| Mode
m| READ
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_db_index_fulltext_queryrelationships]]
.db.index.fulltext.queryRelationships()
[cols="<15s,<85"]
|===
| Description
a|
Query the given full-text index.

Returns the matching relationships, and their Lucene query score, ordered by score.

Valid keys for the options map are: 'skip' to skip the top N results; 'limit' to limit the number of results returned.
| Signature
m| db.index.fulltext.queryRelationships(indexName :: STRING?, queryString :: STRING?, options = {} :: MAP?) :: (relationship :: RELATIONSHIP?, score :: FLOAT?)
| Mode
m| READ
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_db_indexdetails]]
.[deprecated]#db.indexDetails()#
[cols="<15s,<85"]
|===
| Description
a|
Detailed description of specific index.
| Signature
m| db.indexDetails(indexName :: STRING?) :: (id :: INTEGER?, name :: STRING?, state :: STRING?, populationPercent :: FLOAT?, uniqueness :: STRING?, type :: STRING?, entityType :: STRING?, labelsOrTypes :: LIST? OF STRING?, properties :: LIST? OF STRING?, provider :: STRING?, indexConfig :: MAP?, failureMessage :: STRING?)
| Mode
m| READ
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_db_indexes]]
.[deprecated]#db.indexes()#
[cols="<15s,<85"]
|===
| Description
a|
List all indexes in the database.
| Signature
m| db.indexes() :: (id :: INTEGER?, name :: STRING?, state :: STRING?, populationPercent :: FLOAT?, uniqueness :: STRING?, type :: STRING?, entityType :: STRING?, labelsOrTypes :: LIST? OF STRING?, properties :: LIST? OF STRING?, provider :: STRING?)
| Mode
m| READ
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_db_info]]
.db.info()
[cols="<15s,<85"]
|===
| Description
a|
Provides information regarding the database.
| Signature
m| db.info() :: (id :: STRING?, name :: STRING?, creationDate :: STRING?)
| Mode
m| READ
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_db_labels]]
.db.labels()
[cols="<15s,<85"]
|===
| Description
a|
List all available labels in the database.
| Signature
m| db.labels() :: (label :: STRING?)
| Mode
m| READ
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_db_listlocks]]
.[enterprise-edition]#db.listLocks()#
[cols="<15s,<85"]
|===
| Description
a|
List all locks at this database.
| Signature
m| db.listLocks() :: (mode :: STRING?, resourceType :: STRING?, resourceId :: INTEGER?, transactionId :: STRING?)
| Mode
m| DBMS
| Default roles
m| admin
|===


[[procedure_db_ping]]
.db.ping()
[cols="<15s,<85"]
|===
| Description
a|
This procedure can be used by client side tooling to test whether they are correctly connected to a database.
The procedure is available in all databases and always returns true.
A faulty connection can be detected by not being able to call this procedure.
| Signature
m| db.ping() :: (success :: BOOLEAN?)
| Mode
m| READ
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_db_prepareforreplanning]]
.db.prepareForReplanning()
[cols="<15s,<85"]
|===
| Description
a|
Triggers an index resample and waits for it to complete, and after that clears query caches.
After this procedure has finished queries will be planned using the latest database statistics.
| Signature
m| db.prepareForReplanning(timeOutSeconds = 300 :: INTEGER?) :: VOID
| Mode
m| READ
| Default roles
m| admin
|===


[[procedure_db_propertykeys]]
.db.propertyKeys()
[cols="<15s,<85"]
|===
| Description
a|
List all property keys in the database.
| Signature
m| db.propertyKeys() :: (propertyKey :: STRING?)
| Mode
m| READ
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_db_relationshiptypes]]
.db.relationshipTypes()
[cols="<15s,<85"]
|===
| Description
a|
List all available relationship types in the database.
| Signature
m| db.relationshipTypes() :: (relationshipType :: STRING?)
| Mode
m| READ
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_db_resampleindex]]
.db.resampleIndex()
[cols="<15s,<85"]
|===
| Description
a|
Schedule resampling of an index.

Example: `CALL db.resampleIndex("MyIndex"))`
| Signature
m| db.resampleIndex(indexName :: STRING?) :: VOID
| Mode
m| READ
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_db_resampleoutdatedindexes]]
.db.resampleOutdatedIndexes()
[cols="<15s,<85"]
|===
| Description
a|
Schedule resampling of all outdated indexes.
| Signature
m| db.resampleOutdatedIndexes() :: VOID
| Mode
m| READ
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_db_schema_nodetypeproperties]]
.db.schema.nodeTypeProperties()
[cols="<15s,<85"]
|===
| Description
a|
Show the derived property schema of the nodes in tabular form.
| Signature
m| db.schema.nodeTypeProperties() :: (nodeType :: STRING?, nodeLabels :: LIST? OF STRING?, propertyName :: STRING?, propertyTypes :: LIST? OF STRING?, mandatory :: BOOLEAN?)
| Mode
m| READ
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_db_schema_reltypeproperties]]
.db.schema.relTypeProperties()
[cols="<15s,<85"]
|===
| Description
a|
Show the derived property schema of the relationships in tabular form.
| Signature
m| db.schema.relTypeProperties() :: (relType :: STRING?, propertyName :: STRING?, propertyTypes :: LIST? OF STRING?, mandatory :: BOOLEAN?)
| Mode
m| READ
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_db_schema_visualization]]
.db.schema.visualization()
[cols="<15s,<85"]
|===
| Description
a|
Visualize the schema of the data.
| Signature
m| db.schema.visualization() :: (nodes :: LIST? OF NODE?, relationships :: LIST? OF RELATIONSHIP?)
| Mode
m| READ
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_db_schemastatements]]
.[deprecated]#db.schemaStatements()#
[cols="<15s,<85"]
|===
| Description
a|
List all statements for creating and dropping existing indexes and constraints.
| Signature
m| db.schemaStatements() :: (name :: STRING?, type :: STRING?, createStatement :: STRING?, dropStatement :: STRING?)
| Mode
m| READ
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_db_stats_clear]]
.db.stats.clear()
[cols="<15s,<85"]
|===
| Description
a|
Clear collected data of a given data section.

Valid sections are `'QUERIES'`
| Signature
m| db.stats.clear(section :: STRING?) :: (section :: STRING?, success :: BOOLEAN?, message :: STRING?)
| Mode
m| READ
| Default roles
m| admin
|===


[[procedure_db_stats_collect]]
.db.stats.collect()
[cols="<15s,<85"]
|===
| Description
a|
Start data collection of a given data section.

Valid sections are `'QUERIES'`
| Signature
m| db.stats.collect(section :: STRING?, config = {} :: MAP?) :: (section :: STRING?, success :: BOOLEAN?, message :: STRING?)
| Mode
m| READ
| Default roles
m| admin
|===


[[procedure_db_stats_retrieve]]
.db.stats.retrieve()
[cols="<15s,<85"]
|===
| Description
a|
Retrieve statistical data about the current database.

Valid sections are `'GRAPH COUNTS', 'TOKENS', 'QUERIES', 'META'`
| Signature
m| db.stats.retrieve(section :: STRING?, config = {} :: MAP?) :: (section :: STRING?, data :: MAP?)
| Mode
m| READ
| Default roles
m| admin
|===


[[procedure_db_stats_retrieveallanonymized]]
.db.stats.retrieveAllAnonymized()
[cols="<15s,<85"]
|===
| Description
a|
Retrieve all available statistical data about the current database, in an anonymized form.
| Signature
m| db.stats.retrieveAllAnonymized(graphToken :: STRING?, config = {} :: MAP?) :: (section :: STRING?, data :: MAP?)
| Mode
m| READ
| Default roles
m| admin
|===


[[procedure_db_stats_status]]
.db.stats.status()
[cols="<15s,<85"]
|===
| Description
a|
Retrieve the status of all available collector daemons, for this database.
| Signature
m| db.stats.status() :: (section :: STRING?, status :: STRING?, data :: MAP?)
| Mode
m| READ
| Default roles
m| admin
|===


[[procedure_db_stats_stop]]
.db.stats.stop()
[cols="<15s,<85"]
|===
| Description
a|
Stop data collection of a given data section.

Valid sections are `'QUERIES'`
| Signature
m| db.stats.stop(section :: STRING?) :: (section :: STRING?, success :: BOOLEAN?, message :: STRING?)
| Mode
m| READ
| Default roles
m| admin
|===


[[procedure_dbms_cluster_routing_getroutingtable]]
.dbms.cluster.routing.getRoutingTable()
[cols="<15s,<85"]
|===
| Description
a|
Returns endpoints of this instance.
| Signature
m| dbms.cluster.routing.getRoutingTable(context :: MAP?, database = null :: STRING?) :: (ttl :: INTEGER?, servers :: LIST? OF MAP?)
| Mode
m| DBMS
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_dbms_cluster_overview]]
.[enterprise-edition]#dbms.cluster.overview()#
[cols="<15s,<85"]
|===
| Description
a|
Overview of all currently accessible cluster members, their databases and roles.
| Signature
m| dbms.cluster.overview() :: (id :: STRING?, addresses :: LIST? OF STRING?, databases :: MAP?, groups :: LIST? OF STRING?)
| Mode
m| READ
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_dbms_cluster_protocols]]
.[enterprise-edition]#dbms.cluster.protocols()#
[cols="<15s,<85"]
|===
| Description
a|
Overview of installed protocols.

Note that this can only be executed on a cluster core member.
| Signature
m| dbms.cluster.protocols() :: (orientation :: STRING?, remoteAddress :: STRING?, applicationProtocol :: STRING?, applicationProtocolVersion :: INTEGER?, modifierProtocols :: STRING?)
| Mode
m| READ
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_dbms_cluster_quarantinedatabase]]
.[enterprise-edition]#dbms.cluster.quarantineDatabase()#
[cols="<15s,<85"]
|===
| Description
a|
Place a database into quarantine or remove from it.
| Signature
m| dbms.cluster.quarantineDatabase(databaseName :: STRING?, setStatus :: BOOLEAN?, reason = No reason given :: STRING?) :: (databaseName :: STRING?, quarantined :: BOOLEAN?, result :: STRING?)
| Mode
m| DBMS
| Default roles
m| admin
|===


[[procedure_dbms_cluster_readreplicatoggle]]
.[enterprise-edition]#dbms.cluster.readReplicaToggle()#
[cols="<15s,<85"]
|===
| Description
a|
The toggle can pause or resume the pulling of new transactions for a specific database.
If paused, the Read Replica does not pull new transactions from the other cluster members for the specific database.
The Read Replica is still available for reads, you can perform a backup, etc.

[TIP]
====
_What is it for?_

You can perform a point in time backup, as the backup will contain only the transactions up to the point where the transaction pulling was paused.

. Connect directly to the Read Replica cluster member. (Neo4j Driver use `bolt://` or use the HTTP API).
. Pause transaction pulling for the specified database.
. Create a point in time backup, see xref:backup-restore/online-backup.adoc[Back up an online database].

If connected directly to a Read Replica, Data Scientists can execute analysis on a specific database that is paused, the data will not unexpectedly change while performing the analysis.
====

[NOTE]
====
This procedure can only be executed on a Read Replica cluster member.
====

.Pause transaction pulling for database `neo4j`
[source, cypher, role="noheader"]
----
CALL dbms.cluster.readReplicaToggle("neo4j", true)
----

.Resume transaction pulling for database `neo4j`
[source, cypher, role="noheader"]
----
CALL dbms.cluster.readReplicaToggle("neo4j", false)
----

| Signature
m| dbms.cluster.readReplicaToggle(databaseName :: STRING?, pause :: BOOLEAN?) :: (state :: STRING?)
| Mode
m| READ
| Default roles
m| admin
|===


[[procedure_dbms_cluster_role]]
.[enterprise-edition]#dbms.cluster.role()#
[cols="<15s,<85"]
|===
| Description
a|
The role of this instance in the cluster for the specified database.
| Signature
m| dbms.cluster.role(database :: STRING?) :: (role :: STRING?)
| Mode
m| READ
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_dbms_cluster_setdefaultdatabase]]
.[enterprise-edition]#dbms.cluster.setDefaultDatabase()#
[cols="<15s,<85"]
|===
| Description
a|
Change the default database to the provided value.

The database must exist and the old default database must be stopped.

For more information see xref:manage-databases/causal-cluster.adoc#manage-databases-cc-default[Change the default database].

Note that this can only be executed on a cluster core member.
| Signature
m| dbms.cluster.setDefaultDatabase(databaseName :: STRING?) :: (result :: STRING?)
| Mode
m| WRITE
| Default roles
m| admin
|===


[[procedure_dbms_components]]
.dbms.components()
[cols="<15s,<85"]
|===
| Description
a|
List DBMS components and their versions.
| Signature
m| dbms.components() :: (name :: STRING?, versions :: LIST? OF STRING?, edition :: STRING?)
| Mode
m| DBMS
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_dbms_database_state]]
.dbms.database.state()
[cols="<15s,<85"]
|===
| Description
a|
The actual status of the database with the provided name on this neo4j instance.
| Signature
m| dbms.database.state(databaseName :: STRING?) :: (role :: STRING?, address :: STRING?, status :: STRING?, error :: STRING?)
| Mode
m| DBMS
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_dbms_functions]]
.dbms.functions()
[cols="<15s,<85"]
|===
| Description
a|
List all functions in the DBMS.
| Signature
m| dbms.functions() :: (name :: STRING?, signature :: STRING?, category :: STRING?, description :: STRING?, aggregating :: BOOLEAN?, defaultBuiltInRoles :: LIST? OF STRING?)
| Mode
m| DBMS
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_dbms_info]]
.dbms.info()
[cols="<15s,<85"]
|===
| Description
a|
Provides information regarding the DBMS.
| Signature
m| dbms.info() :: (id :: STRING?, name :: STRING?, creationDate :: STRING?)
| Mode
m| DBMS
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_dbms_killconnection]]
.dbms.killConnection()
[cols="<15s,<85"]
|===
| Description
a|
Kill network connection with the given connection id.
| Signature
m| dbms.killConnection(id :: STRING?) :: (connectionId :: STRING?, username :: STRING?, message :: STRING?)
| Mode
m| DBMS
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_dbms_killconnections]]
.dbms.killConnections()
[cols="<15s,<85"]
|===
| Description
a|
Kill all network connections with the given connection ids.
| Signature
m| dbms.killConnections(ids :: LIST? OF STRING?) :: (connectionId :: STRING?, username :: STRING?, message :: STRING?)
| Mode
m| DBMS
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_dbms_killqueries]]
.dbms.killQueries()
[cols="<15s,<85"]
|===
| Description
a|
Kill all transactions executing a query with any of the given query ids.
| Signature
m| dbms.killQueries(ids :: LIST? OF STRING?) :: (queryId :: STRING?, username :: STRING?, message :: STRING?)
| Mode
m| DBMS
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_dbms_killquery]]
.dbms.killQuery()
[cols="<15s,<85"]
|===
| Description
a|
Kill all transactions executing the query with the given query id.
| Signature
m| dbms.killQuery(id :: STRING?) :: (queryId :: STRING?, username :: STRING?, message :: STRING?)
| Mode
m| DBMS
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_dbms_killtransaction]]
.dbms.killTransaction()
[cols="<15s,<85"]
|===
| Description
a|
Kill transaction with provided id.
| Signature
m| dbms.killTransaction(id :: STRING?) :: (transactionId :: STRING?, username :: STRING?, message :: STRING?)
| Mode
m| DBMS
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_dbms_killtransactions]]
.dbms.killTransactions()
[cols="<15s,<85"]
|===
| Description
a|
Kill transactions with provided ids.
| Signature
m| dbms.killTransactions(ids :: LIST? OF STRING?) :: (transactionId :: STRING?, username :: STRING?, message :: STRING?)
| Mode
m| DBMS
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_dbms_listactivelocks]]
.[enterprise-edition]#dbms.listActiveLocks()#
[cols="<15s,<85"]
|===
| Description
a|
List the active lock requests granted for the transaction executing the query with the given query id.
| Signature
m| dbms.listActiveLocks(queryId :: STRING?) :: (mode :: STRING?, resourceType :: STRING?, resourceId :: INTEGER?)
| Mode
m| DBMS
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_dbms_listConfig]]
.dbms.listConfig()
[cols="<15s,<85"]
|===
| Description
a|
List the currently active config of Neo4j.
| Signature
m| dbms.listConfig(searchString =  :: STRING?) :: (name :: STRING?, description :: STRING?, value :: STRING?, dynamic :: BOOLEAN?)
| Mode
m| DBMS
| Default roles
m| admin
|===


[[procedure_dbms_listconnections]]
.dbms.listConnections()
[cols="<15s,<85"]
|===
| Description
a|
List all accepted network connections at this instance that are visible to the user.
| Signature
m| dbms.listConnections() :: (connectionId :: STRING?, connectTime :: STRING?, connector :: STRING?, username :: STRING?, userAgent :: STRING?, serverAddress :: STRING?, clientAddress :: STRING?)
| Mode
m| DBMS
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_dbms_listpools]]
.[enterprise-edition]#dbms.listPools()#
[cols="<15s,<85"]
|===
| Description
a|
List all memory pools, including sub pools, currently registered at this instance that are visible to the user.
| Signature
m| dbms.listPools() :: (pool :: STRING?, databaseName :: STRING?, heapMemoryUsed :: STRING?, heapMemoryUsedBytes :: STRING?, nativeMemoryUsed :: STRING?, nativeMemoryUsedBytes :: STRING?, freeMemory :: STRING?, freeMemoryBytes :: STRING?, totalPoolMemory :: STRING?, totalPoolMemoryBytes :: STRING?)
| Mode
m| DBMS
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_dbms_listqueries]]
.dbms.listQueries()
[cols="<15s,<85"]
|===
| Description
a|
List all queries currently executing at this instance that are visible to the user.
| Signature
m| dbms.listQueries() :: (queryId :: STRING?, username :: STRING?, metaData :: MAP?, query :: STRING?, parameters :: MAP?, planner :: STRING?, runtime :: STRING?, indexes :: LIST? OF MAP?, startTime :: STRING?, protocol :: STRING?, clientAddress :: STRING?, requestUri :: STRING?, status :: STRING?, resourceInformation :: MAP?, activeLockCount :: INTEGER?, elapsedTimeMillis :: INTEGER?, cpuTimeMillis :: INTEGER?, waitTimeMillis :: INTEGER?, idleTimeMillis :: INTEGER?, allocatedBytes :: INTEGER?, pageHits :: INTEGER?, pageFaults :: INTEGER?, connectionId :: STRING?, database :: STRING?)
| Mode
m| DBMS
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_dbms_listtransactions]]
.dbms.listTransactions()
[cols="<15s,<85"]
|===
| Description
a|
List all transactions currently executing at this instance that are visible to the user.
| Signature
m| dbms.listTransactions() :: (transactionId :: STRING?, username :: STRING?, metaData :: MAP?, startTime :: STRING?, protocol :: STRING?, clientAddress :: STRING?, requestUri :: STRING?, currentQueryId :: STRING?, currentQuery :: STRING?, activeLockCount :: INTEGER?, status :: STRING?, resourceInformation :: MAP?, elapsedTimeMillis :: INTEGER?, cpuTimeMillis :: INTEGER?, waitTimeMillis :: INTEGER?, idleTimeMillis :: INTEGER?, allocatedBytes :: INTEGER?, allocatedDirectBytes :: INTEGER?, pageHits :: INTEGER?, pageFaults :: INTEGER?, connectionId :: STRING?, initializationStackTrace :: STRING?, database :: STRING?, estimatedUsedHeapMemory :: INTEGER?)
| Mode
m| DBMS
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_dbms_procedures]]
.dbms.procedures()
[cols="<15s,<85"]
|===
| Description
a|
List all procedures in the DBMS.
| Signature
m| dbms.procedures() :: (name :: STRING?, signature :: STRING?, description :: STRING?, mode :: STRING?, defaultBuiltInRoles :: LIST? OF STRING?, worksOnSystem :: BOOLEAN?)
| Mode
m| DBMS
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_dbms_queryjmx]]
.dbms.queryJmx()
[cols="<15s,<85"]
|===
| Description
a|
Query JMX management data by domain and name.

Valid queries should use the syntax outlined in the link:https://docs.oracle.com/en/java/javase/11/docs/api/java.management/javax/management/ObjectName.html[javax.management.ObjectName API documentation]. +
For instance, use `+"*:*"+` to find all JMX beans.
| Signature
m| dbms.queryJmx(query :: STRING?) :: (name :: STRING?, description :: STRING?, attributes :: MAP?)
| Mode
m| DBMS
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_dbms_routing_getroutingtable]]
.dbms.routing.getRoutingTable()
[cols="<15s,<85"]
|===
| Description
a|
Returns endpoints of this instance.
| Signature
m| dbms.routing.getRoutingTable(context :: MAP?, database = null :: STRING?) :: (ttl :: INTEGER?, servers :: LIST? OF MAP?)
| Mode
m| DBMS
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_dbms_scheduler_failedjobs]]
.[enterprise-edition]#dbms.scheduler.failedJobs()#
[cols="<15s,<85"]
|===
| Description
a|
List failed job runs. There is a limit for amount of historical data.
| Signature
m| dbms.scheduler.failedJobs() :: (jobId :: STRING?, group :: STRING?, database :: STRING?, submitter :: STRING?, description :: STRING?, type :: STRING?, submitted :: STRING?, executionStart :: STRING?, failureTime :: STRING?, failureDescription :: STRING?)
| Mode
m| DBMS
| Default roles
m| admin
|===

[[procedure_dbms_scheduler_groups]]
.[enterprise-edition]#dbms.scheduler.groups()#
[cols="<15s,<85"]
|===
| Description
a|
List the job groups that are active in the database internal job scheduler.
| Signature
m| dbms.scheduler.groups() :: (group :: STRING?, threads :: INTEGER?)
| Mode
m| DBMS
| Default roles
m| admin
|===


[[procedure_dbms_scheduler_jobs]]
.[enterprise-edition]#dbms.scheduler.jobs()#
[cols="<15s,<85"]
|===
| Description
a|
List all jobs that are active in the database internal job scheduler.
| Signature
m| dbms.scheduler.jobs() :: (jobId :: STRING?, group :: STRING?, submitted :: STRING?, database :: STRING?, submitter :: STRING?, description :: STRING?, type :: STRING?, scheduledAt :: STRING?, period :: STRING?, state :: STRING?, currentStateDescription :: STRING?)
| Mode
m| DBMS
| Default roles
m| admin
|===


[[procedure_dbms_scheduler_profile]]
.[enterprise-edition]#dbms.scheduler.profile()#
[cols="<15s,<85"]
|===
| Description
a|
Begin profiling all threads within the given job group, for the specified duration.

Note that profiling incurs overhead to a system, and will slow it down.
| Signature
m| dbms.scheduler.profile(method :: STRING?, group :: STRING?, duration :: STRING?) :: (profile :: STRING?)
| Mode
m| DBMS
| Default roles
m| admin
|===


[[procedure_dbms_security_activateuser]]
.[enterprise-edition]#dbms.security.activateUser()# [deprecated]#&#32;#
[cols="<15s,<85"]
|===
| Description
a|
Activate a suspended user.
| Signature
m| dbms.security.activateUser(username :: STRING?, requirePasswordChange = true :: BOOLEAN?) :: VOID
| Mode
m| WRITE
| Default roles
m| admin
|===


[[procedure_dbms_security_addroletouser]]
.[enterprise-edition]#dbms.security.addRoleToUser()# [deprecated]#&#32;#
[cols="<15s,<85"]
|===
| Description
a|
Assign a role to the user.
| Signature
m| dbms.security.addRoleToUser(roleName :: STRING?, username :: STRING?) :: VOID
| Mode
m| WRITE
| Default roles
m| admin
|===


[[procedure_dbms_security_changepassword]]
.[deprecated]#dbms.security.changePassword()#
[cols="<15s,<85"]
|===
| Description
a|
Change the current user's password.
| Signature
m| dbms.security.changePassword(password :: STRING?, requirePasswordChange = false :: BOOLEAN?) :: VOID
| Mode
m| WRITE
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_dbms_security_changeuserpassword]]
.[enterprise-edition]#dbms.security.changeUserPassword()# [deprecated]#&#32;#
[cols="<15s,<85"]
|===
| Description
a|
Change the given user's password.
| Signature
m| dbms.security.changeUserPassword(username :: STRING?, newPassword :: STRING?, requirePasswordChange = true :: BOOLEAN?) :: VOID
| Mode
m| WRITE
| Default roles
m| admin
|===


[[procedure_dbms_security_clearauthcache]]
.[enterprise-edition]#dbms.security.clearAuthCache()#
[cols="<15s,<85"]
|===
| Description
a|
Clears authentication and authorization cache.
| Signature
m| dbms.security.clearAuthCache() :: VOID
| Mode
m| DBMS
| Default roles
m| admin
|===


[[procedure_dbms_security_createrole]]
.[enterprise-edition]#dbms.security.createRole()# [deprecated]#&#32;#
[cols="<15s,<85"]
|===
| Description
a|
Create a new role.
| Signature
m| dbms.security.createRole(roleName :: STRING?) :: VOID
| Mode
m| WRITE
| Default roles
m| admin
|===


[[procedure_dbms_security_createuser]]
.[deprecated]#dbms.security.createUser()#
[cols="<15s,<85"]
|===
| Description
a|
Create a new user.
| Signature
m| dbms.security.createUser(username :: STRING?, password :: STRING?, requirePasswordChange = true :: BOOLEAN?) :: VOID
| Mode
m| WRITE
| Default roles
m| admin
|===


[[procedure_dbms_security_deleterole]]
.[enterprise-edition]#dbms.security.deleteRole()# [deprecated]#&#32;#
[cols="<15s,<85"]
|===
| Description
a|
Delete the specified role.
Any role assignments will be removed.
| Signature
m| dbms.security.deleteRole(roleName :: STRING?) :: VOID
| Mode
m| WRITE
| Default roles
m| admin
|===


[[procedure_dbms_security_deleteuser]]
.[deprecated]#dbms.security.deleteUser()#
[cols="<15s,<85"]
|===
| Description
a|
Delete the specified user.
| Signature
m| dbms.security.deleteUser(username :: STRING?) :: VOID
| Mode
m| WRITE
| Default roles
m| admin
|===


[[procedure_dbms_security_listroles]]
.[enterprise-edition]#dbms.security.listRoles()# [deprecated]#&#32;#
[cols="<15s,<85"]
|===
| Description
a|
List all available roles.
| Signature
m| dbms.security.listRoles() :: (role :: STRING?, users :: LIST? OF STRING?)
| Mode
m| READ
| Default roles
m| admin
|===


[[procedure_dbms_security_listrolesforuser]]
.[enterprise-edition]#dbms.security.listRolesForUser()# [deprecated]#&#32;#
[cols="<15s,<85"]
|===
| Description
a|
List all roles assigned to the specified user.
| Signature
m| dbms.security.listRolesForUser(username :: STRING?) :: (value :: STRING?)
| Mode
m| READ
| Default roles
m| admin
|===


[[procedure_dbms_security_listusers]]
.[deprecated]#dbms.security.listUsers()#
[cols="<15s,<85"]
|===
| Description
a|
List all native users.
| Signature
m| dbms.security.listUsers() :: (username :: STRING?, roles :: LIST? OF STRING?, flags :: LIST? OF STRING?)
| Mode
m| READ
| Default roles
m| admin
|===


[[procedure_dbms_security_listusersforrole]]
.[enterprise-edition]#dbms.security.listUsersForRole()# [deprecated]#&#32;#
[cols="<15s,<85"]
|===
| Description
a|
List all users currently assigned the specified role.
| Signature
m| dbms.security.listUsersForRole(roleName :: STRING?) :: (value :: STRING?)
| Mode
m| READ
| Default roles
m| admin
|===


[[procedure_dbms_security_removerolefromuser]]
.[enterprise-edition]#dbms.security.removeRoleFromUser()# [deprecated]#&#32;#
[cols="<15s,<85"]
|===
| Description
a|
Unassign a role from the user.
| Signature
m| dbms.security.removeRoleFromUser(roleName :: STRING?, username :: STRING?) :: VOID
| Mode
m| WRITE
| Default roles
m| admin
|===


[[procedure_dbms_security_suspenduser]]
.[enterprise-edition]#dbms.security.suspendUser()# [deprecated]#&#32;#
[cols="<15s,<85"]
|===
| Description
a|
Suspend the specified user.
| Signature
m| dbms.security.suspendUser(username :: STRING?) :: VOID
| Mode
m| WRITE
| Default roles
m| admin
|===


[[procedure_dbms_setconfigvalue]]
.[enterprise-edition]#dbms.setConfigValue()#
[cols="<15s,<85"]
|===
| Description
a|
Update a given setting value.
Passing an empty value results in removing the configured value and falling back to the default value.
Changes do not persist and are lost if the server is restarted.
In a clustered environment, `dbms.setConfigValue` affects only the cluster member it is run against.
| Signature
m| dbms.setConfigValue(setting :: STRING?, value :: STRING?) :: VOID
| Mode
m| DBMS
| Default roles
m| admin
|===


[[procedure_dbms_showcurrentuser]]
.dbms.showCurrentUser()
[cols="<15s,<85"]
|===
| Description
a|
Show the current user.
| Signature
m| dbms.showCurrentUser() :: (username :: STRING?, roles :: LIST? OF STRING?, flags :: LIST? OF STRING?)
| Mode
m| DBMS
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_dbms_upgrade]]
.dbms.upgrade()
[cols="<15s,<85"]
|===
| Description
a|
Upgrade the system database schema if it is not the current schema.
| Signature
m| dbms.upgrade() :: (status :: STRING?, upgradeResult :: STRING?)
| Mode
m| WRITE
| Default roles
m| admin
|===


[[procedure_dbms_upgradestatus]]
.dbms.upgradeStatus()
[cols="<15s,<85"]
|===
| Description
a|
Report the current status of the system database sub-graph schema.
| Signature
m| dbms.upgradeStatus() :: (status :: STRING?, description :: STRING?, resolution :: STRING?)
| Mode
m| READ
| Default roles
m| admin
|===


[[procedure_tx_getmetadata]]
.tx.getMetaData()
[cols="<15s,<85"]
|===
| Description
a|
Provides attached transaction metadata.
| Signature
m| tx.getMetaData() :: (metadata :: MAP?)
| Mode
m| DBMS
| Default roles
m| reader, editor, publisher, architect, admin
|===


[[procedure_tx_setmetadata]]
.tx.setMetaData()
[cols="<15s,<85"]
|===
| Description
a|
Attaches a map of data to the transaction.
The data will be printed when listing queries, and inserted into the query log.
| Signature
m| tx.setMetaData(data :: MAP?) :: VOID
| Mode
m| DBMS
| Default roles
m| reader, editor, publisher, architect, admin
|===


// sources:
// neo4j-documentation/procedures/target/docs/procedure-reference-enterprise-edition.adoc
// neo4j-documentation/procedures/target/docs/procedure-reference-community-edition.adoc
// neo4j-documentation/procedures/target/docs/procedure-reference-complete.adoc

// sources .jar
// ~/.m2/repository/org/neo4j/doc/procedure-documentation/4.0.9-SNAPSHOT/procedure-documentation-4.0.9-SNAPSHOT.jar

// uncomment below to include the autogenereated sources
// include::{import-procedure-documentation-docs}/procedure-reference-enterprise-edition.adoc[]
// include::{import-procedure-documentation-docs}/procedure-reference-community-edition.adoc[]
