[[neo4j-procedures]]
= Procedures
:description: This page provides a complete reference to the Neo4j procedures.

:description: Reference for Neo4j procedures.

:stem:
:mathjax-tex-packages: ams

This page provides a complete reference to the Neo4j procedures.
Available procedures depend on the type of installation you have:

* Neo4j Enterprise Edition provides a larger set of procedures than Neo4j Community Edition.
* Cluster members have procedures that are not available in standalone mode.

To check which procedures are available in your Neo4j DBMS, use the Cypher command `SHOW PROCEDURES`:

.List available procedures
====
[source, cypher]
----
SHOW PROCEDURES
----
====

[NOTE]
====
Some procedures can only be run by users with `Admin` privileges.
Specifically, either the `EXECUTE ADMIN PROCEDURES` privilege or both the `EXECUTE PROCEDURES` and `EXECUTE BOOSTED PROCEDURES` privileges.
These procedures are labeled with label:admin-only[].

For more information, see xref:authentication-authorization/dbms-administration.adoc#access-control-dbms-administration-execute[the `EXECUTE` privileges section].
====

== List of procedures

.Neo4j procedures
[options=header,cols="3m,1,1,3"]
|===
| Name
| Community Edition
| Enterprise Edition
| Comment

| xref:reference/procedures.adoc#procedure_db_cdc_current[`db.cdc.current()`]
| label:no[]
| label:yes[]
| label:new[Introduced in 5.17] label:beta[]

| xref:reference/procedures.adoc#procedure_db_cdc_earliest[`db.cdc.earliest()`]
| label:no[]
| label:yes[]
| label:new[Introduced in 5.17] label:beta[]

| xref:reference/procedures.adoc#procedure_db_cdc_query[`db.cdc.query()`]
| label:no[]
| label:yes[]
| label:new[Introduced in 5.17] label:beta[] label:admin-only[]


| xref:reference/procedures.adoc#procedure_db_awaitindex[`db.awaitIndex()`]
| label:yes[]
| label:yes[]
|

| xref:reference/procedures.adoc#procedure_db_awaitindexes[`db.awaitIndexes()`]
| label:yes[]
| label:yes[]
|


| xref:reference/procedures.adoc#procedure_db_checkpoint[`db.checkpoint()`]
| label:no[]
| label:yes[]
|

| xref:reference/procedures.adoc#procedure_db_clearquerycaches[`db.clearQueryCaches()`]
| label:yes[]
| label:yes[]
| label:admin-only[]

| xref:reference/procedures.adoc#procedure_db_create_setNodeVectorProperty[`db.create.setNodeVectorProperty()`]
| label:yes[]
| label:yes[]
| label:new[Introduced in 5.13] label:beta[]

| xref:reference/procedures.adoc#procedure_db_createlabel[`db.createLabel()`]
| label:yes[]
| label:yes[]
|

| xref:reference/procedures.adoc#procedure_db_createproperty[`db.createProperty()`]
| label:yes[]
| label:yes[]
|

| xref:reference/procedures.adoc#procedure_db_createrelationshiptype[`db.createRelationshipType()`]
| label:yes[]
| label:yes[]
|

| xref:reference/procedures.adoc#procedure_db_index_fulltext_awaiteventuallyconsistentindexrefresh[`db.index.fulltext.awaitEventuallyConsistentIndexRefresh()`]
| label:yes[]
| label:yes[]
|

| xref:reference/procedures.adoc#procedure_db_index_fulltext_listavailableanalyzers[`db.index.fulltext.listAvailableAnalyzers()`]
| label:yes[]
| label:yes[]
|

| xref:reference/procedures.adoc#procedure_db_index_fulltext_querynodes[`db.index.fulltext.queryNodes()`]
| label:yes[]
| label:yes[]
| In 4.1, signature changed to `db.index.fulltext.queryNodes(indexName :: STRING, queryString :: STRING, options = {} :: MAP) :: (node :: NODE, score :: FLOAT)`.

| xref:reference/procedures.adoc#procedure_db_index_fulltext_queryrelationships[`db.index.fulltext.queryRelationships()`]
| label:yes[]
| label:yes[]
| In 4.1, signature changed to `db.index.fulltext.queryRelationships(indexName :: STRING, queryString :: STRING, options = {} :: MAP) :: (relationship :: RELATIONSHIP, score :: FLOAT)`.

| xref:reference/procedures.adoc#procedure_db_index_vector_createNodeIndex[`db.index.vector.createNodeIndex()`]
| label:yes[]
| label:yes[]
| label:new[Introduced in 5.11] label:beta[Beta until 5.13] Replaced by: `CREATE VECTOR INDEX ...`

| xref:reference/procedures.adoc#procedure_db_index_vector_queryNodes[`db.index.vector.queryNodes()`]
| label:yes[]
| label:yes[]
| label:new[Introduced in 5.11]  label:beta[Beta until 5.13]

| xref:reference/procedures.adoc#procedure_db_info[`db.info()`]
| label:yes[]
| label:yes[]
|

| xref:reference/procedures.adoc#procedure_db_labels[`db.labels()`]
| label:yes[]
| label:yes[]
|

| xref:reference/procedures.adoc#procedure_db_listlocks[`db.listLocks()`]
| label:no[]
| label:yes[]
| label:admin-only[] +
In 4.2, signature changed to `db.listLocks() :: (mode :: STRING, resourceType :: STRING, resourceId :: INTEGER, transactionId :: STRING)`.

| xref:reference/procedures.adoc#procedure_db_ping[`db.ping()`]
| label:yes[]
| label:yes[]
|

// Bugfix in 4.0
// Default users are: admin
| xref:reference/procedures.adoc#procedure_db_prepareforreplanning[`db.prepareForReplanning()`]
| label:yes[]
| label:yes[]
| label:admin-only[]

| xref:reference/procedures.adoc#procedure_db_propertykeys[`db.propertyKeys()`]
| label:yes[]
| label:yes[]
|

| xref:reference/procedures.adoc#procedure_db_relationshiptypes[`db.relationshipTypes()`]
| label:yes[]
| label:yes[]
|

| xref:reference/procedures.adoc#procedure_db_resampleindex[`db.resampleIndex()`]
| label:yes[]
| label:yes[]
|

| xref:reference/procedures.adoc#procedure_db_resampleoutdatedindexes[`db.resampleOutdatedIndexes()`]
| label:yes[]
| label:yes[]
|

| xref:reference/procedures.adoc#procedure_db_schema_nodetypeproperties[`db.schema.nodeTypeProperties()`]
| label:yes[]
| label:yes[]
|

| xref:reference/procedures.adoc#procedure_db_schema_reltypeproperties[`db.schema.relTypeProperties()`]
| label:yes[]
| label:yes[]
|

| xref:reference/procedures.adoc#procedure_db_schema_visualization[`db.schema.visualization()`]
| label:yes[]
| label:yes[]
|

// Bugfix in 4.0
// Default users are: admin
| xref:reference/procedures.adoc#procedure_db_stats_clear[`db.stats.clear()`]
| label:yes[]
| label:yes[]
| label:admin-only[]

// Bugfix in 4.0
// Default users are: admin
| xref:reference/procedures.adoc#procedure_db_stats_collect[`db.stats.collect()`]
| label:yes[]
| label:yes[]
| label:admin-only[]

// Bugfix in 4.0
// Default users are: admin
| xref:reference/procedures.adoc#procedure_db_stats_retrieve[`db.stats.retrieve()`]
| label:yes[]
| label:yes[]
| label:admin-only[]

// Bugfix in 4.0
// Default users are: admin
| xref:reference/procedures.adoc#procedure_db_stats_retrieveallanonymized[`db.stats.retrieveAllAnonymized()`]
| label:yes[]
| label:yes[]
| label:admin-only[]

// Bugfix in 4.0
// Default users are: admin
| xref:reference/procedures.adoc#procedure_db_stats_status[`db.stats.status()`]
| label:yes[]
| label:yes[]
| label:admin-only[]

// Bugfix in 4.0
// Default users are: admin
| xref:reference/procedures.adoc#procedure_db_stats_stop[`db.stats.stop()`]
| label:yes[]
| label:yes[]
| label:admin-only[]

// New in 5.0
// Only for admins
| xref:reference/procedures.adoc#procedure_dbms_checkconfigvalue[`dbms.checkConfigValue()`]
| label:no[]
| label:yes[]
| label:new[Introduced in 5.0]  label:admin-only[]

// New in 4.0
// Internal
// dbms.clientConfig()

| xref:reference/procedures.adoc#procedure_dbms_cluster_setAutomaticallyEnableFreeServers[`dbms.cluster.setAutomaticallyEnableFreeServers()`]
| label:no[]
| label:yes[]
| label:admin-only[]

| xref:reference/procedures.adoc#procedure_dbms_cluster_checkConnectivity[`dbms.cluster.checkConnectivity()`]
| label:no[]
| label:yes[]
| label:admin-only[]

| xref:reference/procedures.adoc#procedure_dbms_cluster_cordonServer[`dbms.cluster.cordonServer()`]
| label:no[]
| label:yes[]
| label:admin-only[]

// New in 4.0
// com.neo4j.causaulclustering.discovery.procedures.InstalledProtocolsProcedure
| xref:reference/procedures.adoc#procedure_dbms_cluster_protocols[`dbms.cluster.protocols()`]
| label:no[]
| label:yes[]
|

| xref:reference/procedures.adoc#procedure_dbms_cluster_secondaryreplicationdisable[`dbms.cluster.secondaryReplicationDisable()`]
| label:no[]
| label:yes[]
| label:admin-only[] label:new[Introduced in 5.6]

// Clustering is an Enterprise feature, the naming is weird.
// dbms.routing.getRoutingTable() does the same thing.
| xref:reference/procedures.adoc#procedure_dbms_cluster_routing_getroutingtable[`dbms.cluster.routing.getRoutingTable()`]
| label:yes[]
| label:yes[]
|

| xref:reference/procedures.adoc#procedure_dbms_cluster_uncordonServer[`dbms.cluster.uncordonServer()`]
| label:no[]
| label:yes[]
| label:admin-only[]

| xref:reference/procedures.adoc#procedure_dbms_components[`dbms.components()`]
| label:yes[]
| label:yes[]
|

| xref:reference/procedures.adoc#procedure_dbms_info[`dbms.info()`]
| label:yes[]
| label:yes[]
|

// Community Edition in 4.2
| xref:reference/procedures.adoc#procedure_dbms_killconnection[`dbms.killConnection()`]
| label:yes[]
| label:yes[]
|

// Community Edition in 4.2
| xref:reference/procedures.adoc#procedure_dbms_killconnections[`dbms.killConnections()`]
| label:yes[]
| label:yes[]
|

| xref:reference/procedures.adoc#procedure_dbms_listactivelocks[`dbms.listActiveLocks()`]
| label:yes[]
| label:yes[]
|

| xref:reference/procedures.adoc#procedure_dbms_listcapabilities[`dbms.listCapabilities()`]
| label:yes[]
| label:yes[]
|

| xref:reference/procedures.adoc#procedure_dbms_listconfig[`dbms.listConfig()`]
| label:yes[]
| label:yes[]
| label:admin-only[]

| xref:reference/procedures.adoc#procedure_dbms_listconnections[`dbms.listConnections()`]
| label:yes[]
| label:yes[]
|

// New in 4.1
| xref:reference/procedures.adoc#procedure_dbms_listpools[`dbms.listPools()`]
| label:no[]
| label:yes[]
|

// New in 4.3
| xref:reference/procedures.adoc#procedure_dbms_quarantineDatabase[`dbms.quarantineDatabase()`]
| label:no[]
| label:yes[]
| label:admin-only[]

| xref:reference/procedures.adoc#procedure_dbms_queryjmx[`dbms.queryJmx()`]
| label:yes[]
| label:yes[]
|

| xref:reference/procedures.adoc#procedure_dbms_routing_getroutingtable[`dbms.routing.getRoutingTable()`]
| label:yes[]
| label:yes[]
|

// New in 4.2
| xref:reference/procedures.adoc#procedure_dbms_scheduler_failedjobs[`dbms.scheduler.failedJobs()`]
| label:no[]
| label:yes[]
| label:admin-only[]

| xref:reference/procedures.adoc#procedure_dbms_scheduler_groups[`dbms.scheduler.groups()`]
| label:no[]
| label:yes[]
| label:admin-only[]

// New in 4.2
| xref:reference/procedures.adoc#procedure_dbms_scheduler_jobs[`dbms.scheduler.jobs()`]
| label:no[]
| label:yes[]
| label:admin-only[]

| xref:reference/procedures.adoc#procedure_dbms_security_clearauthcache[`dbms.security.clearAuthCache()`]
| label:no[]
| label:yes[]
| label:admin-only[]

| xref:reference/procedures.adoc#procedure_dbms_setconfigvalue[`dbms.setConfigValue()`]
| label:no[]
| label:yes[]
| label:admin-only[]

| xref:reference/procedures.adoc#procedure_dbms_setDatabaseAllocator[`dbms.setDatabaseAllocator()`]
| label:no[]
| label:yes[]
| label:admin-only[]

| xref:reference/procedures.adoc#procedure_dbms_setDefaultAllocationNumbers[`dbms.setDefaultAllocationNumbers()`]
| label:no[]
| label:yes[]
| label:admin-only[]

| xref:reference/procedures.adoc#procedure_dbms_setDefaultDatabase[`dbms.setDefaultDatabase()`]
| label:no[]
| label:yes[]
| label:admin-only[]


| xref:reference/procedures.adoc#procedure_dbms_showcurrentuser[`dbms.showCurrentUser()`]
| label:yes[]
| label:yes[]
|

| xref:reference/procedures.adoc#procedure_dbms_showTopologyGraphConfig[`dbms.showTopologyGraphConfig()`]
| label:no[]
| label:yes[]
| label:admin-only[]

// New in 5.16 but only on Aura
| xref:reference/procedures.adoc#procedure_genai_vector_encodeBatch[`genai.vector.encodeBatch()`]
| label:no[]
| label:no[]
| label:aura-only[Available only on Aura]

| xref:reference/procedures.adoc#procedure_tx_getmetadata[`tx.getMetaData()`]
| label:yes[]
| label:yes[]
|

| xref:reference/procedures.adoc#procedure_tx_setmetadata[`tx.setMetaData()`]
| label:yes[]
| label:yes[]
|

|===


== List of deprecated procedures

.Deprecated Neo4j procedures
[options=header, cols="3m,1,1,3"]
|===
| Name
| Community Edition
| Enterprise Edition
| Comment

| xref:reference/procedures.adoc#procedure_cdc_current[`cdc.current()`]
| label:no[]
| label:yes[]
| label:new[Introduced in 5.13] label:beta[] label:deprecated[Deprecated in 5.17]
Replaced by: xref:reference/procedures.adoc#procedure_db_cdc_current[`db.cdc.current()`]

| xref:reference/procedures.adoc#procedure_cdc_earliest[`cdc.earliest()`]
| label:no[]
| label:yes[]
| label:new[Introduced in 5.13] label:beta[] label:deprecated[Deprecated in 5.17]
Replaced by: xref:reference/procedures.adoc#procedure_db_cdc_earliest[`db.cdc.earliest()`]

| xref:reference/procedures.adoc#procedure_cdc_query[`cdc.query()`]
| label:no[]
| label:yes[]
| label:new[Introduced in 5.13] label:beta[] label:deprecated[Deprecated in 5.17] label:admin-only[]
Replaced by: xref:reference/procedures.adoc#procedure_db_cdc_query[`db.cdc.query()`]

| xref:reference/procedures.adoc#procedure_db_create_setVectorProperty[`db.create.setVectorProperty()`]
| label:yes[]
| label:yes[]
| label:new[Introduced in 5.11] label:beta[] label:deprecated[Deprecated in 5.13] Replaced by: xref:reference/procedures.adoc#procedure_db_create_setNodeVectorProperty[`db.create.setNodeVectorProperty()`]

// New in 4.2
// com.neo4j.causaulclustering.discovery.procedures.ReadReplicaToggleProcedure
| xref:reference/procedures.adoc#procedure_dbms_cluster_readreplicatoggle[`dbms.cluster.readReplicaToggle()`]
| label:no[]
| label:yes[]
| label:admin-only[] label:deprecated[Deprecated in 5.6]. +
Replaced by: xref:reference/procedures.adoc#procedure_dbms_cluster_secondaryreplicationdisable[`dbms.cluster.secondaryReplicationDisable()`].

// New in 4.1
| xref:reference/procedures.adoc#procedure_dbms_upgrade[`dbms.upgrade()`]
| label:yes[]
| label:yes[]
| label:admin-only[] label:deprecated[Deprecated in 5.9]

// New in 4.1
| xref:reference/procedures.adoc#procedure_dbms_upgradestatus[`dbms.upgradeStatus()`]
| label:yes[]
| label:yes[]
| label:admin-only[] label:deprecated[Deprecated in 5.9]

|===



== List of removed procedures


.Removed Neo4j procedures
[options=header,cols="3m,1,1,3"]
|===
| Name
| Community Edition
| Enterprise Edition
| Comment

| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_db_constraints[`db.constraints()`]
| label:yes[]
| label:yes[]
| label:removed[] +
Replaced by: `SHOW CONSTRAINTS`.

| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_db_createindex[`db.createIndex()`]
| label:yes[]
| label:yes[]
| label:removed[] +
Replaced by: `CREATE INDEX`.

| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_db_createnodekey[`db.createNodeKey()`]
| label:no[]
| label:yes[]
| label:removed[] +
Replaced by: `CREATE CONSTRAINT ... IS NODE KEY`.

| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_db_createuniquepropertyconstraint[`db.createUniquePropertyConstraint()`]
| label:yes[]
| label:yes[]
| label:removed[] +
Replaced by: `CREATE CONSTRAINT ... IS UNIQUE`.

| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_db_indexes[`db.indexes()`]
| label:yes[]
| label:yes[]
| label:removed[] +
Replaced by: `SHOW INDEXES`.

| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_db_indexdetails[`db.indexDetails()`]
| label:yes[]
| label:yes[]
| label:removed[] +
Replaced by: `SHOW INDEXES YIELD*`.

| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_db_index_fulltext_createnodeindex[`db.index.fulltext.createNodeIndex()`]
| label:yes[]
| label:yes[]
| label:removed[] +
Replaced by: `CREATE FULLTEXT INDEX ...`.

| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_db_index_fulltext_createrelationshipindex[`db.index.fulltext.createRelationshipIndex()`]
| label:yes[]
| label:yes[]
| label:removed[] +
Replaced by: `CREATE FULLTEXT INDEX ...`.

| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_db_index_fulltext_drop[`db.index.fulltext.drop()`]
| label:yes[]
| label:yes[]
| label:removed[] +
Replaced by: `DROP INDEX ...`.

| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_db_schemastatements[`db.schemaStatements()`]
| label:yes[]
| label:yes[]
| label:removed[] +
Replaced by: `SHOW INDEXES YIELD *` and `SHOW CONSTRAINTS YIELD *`.

// New in 4.0
// com.neo4j.causaulclustering.discovery.procedures.ClusterOverviewProcedure
| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_dbms_cluster_overview[`dbms.cluster.overview()`]
| label:no[]
| label:yes[]
| label:removed[] +
Replaced by: `SHOW SERVERS`.


// New in 4.2
// com.neo4j.dbms.procedures.QuarantineProcedure
| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_dbms_cluster_quarantinedatabase[`dbms.cluster.quarantineDatabase()`]
| label:no[]
| label:yes[]
| label:removed[] +
Replaced by: `dbms.quarantineDatabase()`.


// New in 4.0
// Removed in 5.0
// com.neo4j.causaulclustering.discovery.procedures.RoleProcedure
| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_dbms_cluster_role[`dbms.cluster.role()`]
| label:no[]
| label:yes[]
| label:removed[] +
Replaced by: `SHOW DATABASES`.

// New in 4.1
// Removed in 5.0
// com.neo4j.dbms.procedures.ClusterSetDefaultDatabaseProcedure
| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_dbms_cluster_setdefaultdatabase[`dbms.cluster.setDefaultDatabase()`]
| label:no[]
| label:yes[]
| label:removed[] +
Replaced by: `dbms.setDefaultDatabase`.

// Removed in 5.0
| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_dbms_database_state[`dbms.database.state()`]
| label:yes[]
| label:yes[]
| label:removed[] +
Replaced by: `SHOW DATABASES`.

| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_dbms_functions[`dbms.functions()`]
| label:yes[]
| label:yes[]
| label:removed[] +
Replaced by: `SHOW FUNCTIONS`.

| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_dbms_killqueries[`dbms.killQueries()`]
| label:yes[]
| label:yes[]
| label:removed[] +
Replaced by: `TERMINATE TRANSACTIONS`.

| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_dbms_killquery[`dbms.killQuery()`]
| label:yes[]
| label:yes[]
| label:removed[] +
Replaced by: `TERMINATE TRANSACTIONS`.

| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_dbms_killtransaction[`dbms.killTransaction()`]
| label:yes[]
| label:yes[]
| label:removed[] +
Replaced by: `TERMINATE TRANSACTIONS`.

| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_dbms_killtransactions[`dbms.killTransactions()`]
| label:yes[]
| label:yes[]
| label:removed[] +
Replaced by: `TERMINATE TRANSACTIONS`.

| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_dbms_listqueries[`dbms.listQueries()`]
| label:yes[]
| label:yes[]
| label:removed[] +
Replaced by: `SHOW TRANSACTIONS`.

| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_dbms_listtransactions[`dbms.listTransactions()`]
| label:yes[]
| label:yes[]
| label:removed[] +
Replaced by: `SHOW TRANSACTIONS`.


| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_dbms_procedures[`dbms.procedures()`]
| label:no[]
| label:yes[]
| label:removed[] +
Replaced by: `SHOW PROCEDURES`.

// Removed in 5.0
| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_dbms_security_activateuser[`dbms.security.activateUser()`]
| label:no[]
| label:yes[]
| label:removed[] label:admin-only[] +
In 4.1, mode changed to `write`. +
Replaced by: `ALTER USER`.

// Removed in 5.0
| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_dbms_security_addroletouser[`dbms.security.addRoleToUser()`]
| label:no[]
| label:yes[]
| label:removed[] label:admin-only[] +
In 4.1, mode changed to `write`. +
Replaced by: `GRANT ROLE TO USER`.

// Removed in 5.0
// newSet( READER, EDITOR, PUBLISHER, ARCHITECT, ADMIN )
| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_dbms_security_changepassword[`dbms.security.changePassword()`]
| label:yes[]
| label:yes[]
| label:removed[] label:admin-only[] +
In 4.1, mode changed to `write`. +
Replaced by: `ALTER CURRENT USER SET PASSWORD`.

// Removed in 5.0
| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_dbms_security_changeuserpassword[`dbms.security.changeUserPassword()`]
| label:no[]
| label:yes[]
| label:removed[] label:admin-only[] +
In 4.1, mode changed to `write`. +
Replaced by: `ALTER USER`.

// Removed in 5.0
| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_dbms_security_createrole[`dbms.security.createRole()`]
| label:no[]
| label:yes[]
| label:removed[] label:admin-only[] +
In 4.1, mode changed to `write`. +
Replaced by: `CREATE ROLE`.

// Removed in 5.0
| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_dbms_security_createuser[`dbms.security.createUser()`]
| label:yes[]
| label:yes[]
| label:removed[] label:admin-only[] +
In 4.1, mode changed to `write`. +
Replaced by: `CREATE USER`.

// Removed in 5.0
| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_dbms_security_deleterole[`dbms.security.deleteRole()`]
| label:no[]
| label:yes[]
| label:removed[] label:admin-only[] +
In 4.1, mode changed to `write`. +
Replaced by: `DROP ROLE`.

// Removed in 5.0
| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_dbms_security_deleteuser[`dbms.security.deleteUser()`]
| label:yes[]
| label:yes[]
| label:removed[] label:admin-only[] +
In 4.1, mode changed to `write`. +
Replaced by: `DROP USER`.

// Removed in 5.0
| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_dbms_security_listroles[`dbms.security.listRoles()`]
| label:yes[]
| label:yes[]
| label:removed[] label:admin-only[] +
In 4.1, mode changed to `read`. +
Replaced by: `SHOW ROLES`.

// Removed in 5.0
| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_dbms_security_listrolesforuser[`dbms.security.listRolesForUser()`]
| label:no[]
| label:yes[]
| label:removed[] +
In 4.1, mode changed to `read`. +
Replaced by: `SHOW USERS`.

// Removed in 5.0
| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_dbms_security_listusers[`dbms.security.listUsers()`]
| label:yes[]
| label:yes[]
| label:removed[] label:admin-only[] +
In 4.1, mode changed to `read`. +
Replaced by: `SHOW USERS`.

// Removed in 5.0
| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_dbms_security_listusersforrole[`dbms.security.listUsersForRole()`]
| label:no[]
| label:yes[]
| label:removed[] label:admin-only[] +
In 4.1, mode changed to `read`. +
Replaced by: `SHOW ROLES WITH USERS`.

// Removed in 5.0
| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_dbms_security_removerolefromuser[`dbms.security.removeRoleFromUser()`]
| label:no[]
| label:yes[]
| label:removed[] label:admin-only[] +
In 4.1, mode changed to `write`. +
Replaced by: `REVOKE ROLE FROM USER`.

// Removed in 5.0
| link:{neo4j-docs-base-uri}/operations-manual/4.4/reference/procedures/#procedure_dbms_security_suspenduser[`dbms.security.suspendUser()`]
| label:no[]
| label:yes[]
| label:removed[] label:admin-only[] +
In 4.1, mode changed to `write`. +
Replaced by: `ALTER USER`.

|===

== Procedure descriptions

[[procedure_cdc_current]]
.cdc.current() label:new[Introduced in 5.13] label:deprecated[Deprecated in 5.17]
[cols="<15s,<85"]
|===
| Description
a|
Returns the current change identifier that can be used to stream changes from.
| Signature
m|cdc.current() :: (id :: STRING)
| Mode
m|READ
| Replaced by
a|xref:reference/procedures.adoc#procedure_db_cdc_current[`db.cdc.current()`]
|===

[[procedure_cdc_earliest]]
.cdc.earliest() label:new[Introduced in 5.13] label:deprecated[Deprecated in 5.17]
[cols="<15s,<85"]
|===
| Description
a|
Returns the earliest change identifier that can be used to stream changes from.
| Signature
m|cdc.earliest() :: (id :: STRING)
| Mode
m|READ
| Replaced by
a|xref:reference/procedures.adoc#procedure_db_cdc_earliest[`db.cdc.earliest()`]
|===

[[procedure_cdc_query]]
.cdc.query() label:new[Introduced in 5.13] label:deprecated[Deprecated in 5.17] label:admin-only[]
[cols="<15s,<85"]
|===
| Description
a|
Query changes happened from the provided change identifier.
| Signature
m|cdc.query(from =  :: STRING, selectors = [] :: LIST<MAP>) :: (id :: STRING, txId :: INTEGER, seq :: INTEGER, metadata :: MAP, event :: MAP)
| Mode
m|READ
| Replaced by
a|xref:reference/procedures.adoc#procedure_db_cdc_query[`db.cdc.query()`]
|===

[[procedure_db_cdc_current]]
.db.cdc.current() label:new[Introduced in 5.17] label:beta[]
[cols="<15s,<85"]
|===
| Description
a|
Returns the current change identifier that can be used to stream changes from.
| Signature
m|cdc.current() :: (id :: STRING)
| Mode
m|READ
|===

[[procedure_db_cdc_earliest]]
.db.cdc.earliest() label:new[Introduced in 5.17] label:beta[]
[cols="<15s,<85"]
|===
| Description
a|
Returns the earliest change identifier that can be used to stream changes from.
| Signature
m|cdc.earliest() :: (id :: STRING)
| Mode
m|READ
|===

[[procedure_db_cdc_query]]
.db.cdc.query() label:new[Introduced in 5.17] label:beta[] label:admin-only[]
[cols="<15s,<85"]
|===
| Description
a|
Query changes happened from the provided change identifier.
| Signature
m|cdc.query(from =  :: STRING, selectors = [] :: LIST<MAP>) :: (id :: STRING, txId :: INTEGER, seq :: INTEGER, metadata :: MAP, event :: MAP)
| Mode
m|READ

|===

[[procedure_db_awaitindex]]
.db.awaitIndex()
[cols="<15s,<85"]
|===
| Description
a|
Wait for an index to come online (for example: `CALL db.awaitIndex("MyIndex", 300)`).
| Signature
m|db.awaitIndex(indexName :: STRING, timeOutSeconds = 300 :: INTEGER)
| Mode
m|READ
// | Default roles
// m|reader, editor, publisher, architect, admin
|===

[NOTE]
====
This procedure is not considered safe to run from multiple threads.
It is therefore not supported by the parallel runtime (introduced in Neo4j 5.13).
For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/planning-and-tuning/runtimes/concepts#runtimes-parallel-runtime[Cypher Manual -> Parallel runtime].
====

[[procedure_db_awaitindexes]]
.db.awaitIndexes()
[cols="<15s,<85"]
|===
| Description
a|
Wait for all indexes to come online (for example: `CALL db.awaitIndexes(300)`).
| Signature
m|db.awaitIndexes(timeOutSeconds = 300 :: INTEGER)
| Mode
m|READ
// | Default roles
// m|reader, editor, publisher, architect, admin
|===

[NOTE]
====
This procedure is not considered safe to run from multiple threads.
It is therefore not supported by the parallel runtime (introduced in Neo4j 5.13).
For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/planning-and-tuning/runtimes/concepts#runtimes-parallel-runtime[Cypher Manual -> Parallel runtime].
====

[[procedure_db_checkpoint]]
.db.checkpoint() label:enterprise-edition[]
[cols="<15s,<85"]
|===
| Description
a|
Initiate and wait for a new check point, or wait any already on-going check point to complete.

Note that this temporarily disables the `db.checkpoint.iops.limit` setting in order to make the check point complete faster.
This might cause transaction throughput to degrade slightly, due to increased IO load.
| Signature
m|db.checkpoint() :: (success :: BOOLEAN, message :: STRING)
| Mode
m|DBMS
// | Default roles
// m|reader, editor, publisher, architect, admin
|===

[NOTE]
====
This procedure is not considered safe to run from multiple threads.
It is therefore not supported by the parallel runtime (introduced in Neo4j 5.13).
For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/planning-and-tuning/runtimes/concepts#runtimes-parallel-runtime[Cypher Manual -> Parallel runtime].
====

[[procedure_db_clearquerycaches]]
.db.clearQueryCaches() label:admin-only[]
[cols="<15s,<85"]
|===
| Description
a|
Clears all query caches.
| Signature
m|db.clearQueryCaches() :: (value :: STRING)
| Mode
m|DBMS
// | Default roles
// m|admin
|===

[[procedure_db_create_setNodeVectorProperty]]
.db.create.setNodeVectorProperty() label:new[Introduced in 5.13] label:beta[]
[cols="<15s,<85"]
|===
| Description
a|
Set a vector property on a given node in a more space efficient representation than Cypher’s link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/clauses/set#set-set-a-property[`SET`].
| Signature
m| db.create.setNodeVectorProperty(node :: NODE, key :: STRING, vector :: LIST<FLOAT>)
| Mode
m|WRITE
|===

[[procedure_db_create_setVectorProperty]]
.db.create.setVectorProperty() label:new[Introduced in 5.11] label:beta[] label:deprecated[Deprecated in 5.13]
[cols="<15s,<85"]
|===
| Description
a|
Set a vector property on a given node in a more space efficient representation than Cypher’s link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/clauses/set#set-set-a-property[`SET`].
| Signature
m| db.create.setVectorProperty(node :: NODE, key :: STRING, vector :: LIST<FLOAT>) :: (node :: NODE)
| Mode
m|WRITE
| Replaced by
a|xref:reference/procedures.adoc#procedure_db_create_setNodeVectorProperty[`db.create.setNodeVectorProperty()`]
|===

[[procedure_db_createlabel]]
.db.createLabel()
[cols="<15s,<85"]
|===
| Description
a|
Create a label
| Signature
m|db.createLabel(newLabel :: STRING)
| Mode
m|WRITE
// | Default roles
// m|publisher, architect, admin
|===


[[procedure_db_createproperty]]
.db.createProperty()
[cols="<15s,<85"]
|===
| Description
a|
Create a Property
| Signature
m|db.createProperty(newProperty :: STRING)
| Mode
m|WRITE
// | Default roles
// m|publisher, architect, admin
|===


[[procedure_db_createrelationshiptype]]
.db.createRelationshipType()
[cols="<15s,<85"]
|===
| Description
a|
Create a RelationshipType
| Signature
m|db.createRelationshipType(newRelationshipType :: STRING)
| Mode
m|WRITE
// | Default roles
// m|publisher, architect, admin
|===


[[procedure_db_index_fulltext_awaiteventuallyconsistentindexrefresh]]
.db.index.fulltext.awaitEventuallyConsistentIndexRefresh()
[cols="<15s,<85"]
|===
| Description
a|
Wait for the updates from recently committed transactions to be applied to any eventually-consistent full-text indexes.
| Signature
m|db.index.fulltext.awaitEventuallyConsistentIndexRefresh()
| Mode
m|READ
// | Default roles
// m|reader, editor, publisher, architect, admin
|===


[[procedure_db_index_fulltext_listavailableanalyzers]]
.db.index.fulltext.listAvailableAnalyzers()
[cols="<15s,<85"]
|===
| Description
a|
List the available analyzers that the full-text indexes can be configured with.
| Signature
m|db.index.fulltext.listAvailableAnalyzers() :: (analyzer :: STRING, description :: STRING, stopwords :: LIST<STRING>)
| Mode
m|READ
// | Default roles
// m|reader, editor, publisher, architect, admin
|===


[[procedure_db_index_fulltext_querynodes]]
.db.index.fulltext.queryNodes()
[cols="<15s,<85"]
|===
| Description
a|
Query the given full-text index.
Returns the matching nodes and their Lucene query score, ordered by score.
Valid _key: value_ pairs for the `options` map are:

* `skip: <number>` -- to skip the top N results.
* `limit: <number>` -- to limit the number of results returned.
* `analyzer: <string>` -- to use the specified analyzer as a search analyzer for this query.

The `options` map and any of the keys are optional.
An example of the `options` map: `{skip: 30, limit: 10, analyzer: 'whitespace'}`
| Signature
m|db.index.fulltext.queryNodes(indexName :: STRING, queryString :: STRING, options = {} :: MAP) :: (node :: NODE, score :: FLOAT)
| Mode
m|READ
// | Default roles
// m|reader, editor, publisher, architect, admin
|===


[[procedure_db_index_fulltext_queryrelationships]]
.db.index.fulltext.queryRelationships()
[cols="<15s,<85"]
|===
| Description
a|
Query the given full-text index.
Returns the matching relationships and their Lucene query score, ordered by score.
Valid _key: value_ pairs for the `options` map are:

* `skip: <number>` -- to skip the top N results.
* `limit: <number>` -- to limit the number of results returned.
* `analyzer: <string>` -- to use the specified analyzer as a search analyzer for this query.

The `options` map and any of the keys are optional.
An example of the `options` map: `{skip: 30, limit: 10, analyzer: 'whitespace'}`
| Signature
m|db.index.fulltext.queryRelationships(indexName :: STRING, queryString :: STRING, options = {} :: MAP) :: (relationship :: RELATIONSHIP, score :: FLOAT)
| Mode
m|READ
// | Default roles
// m|reader, editor, publisher, architect, admin
|===

[[procedure_db_index_vector_createNodeIndex]]
.db.index.vector.createNodeIndex()  label:new[Introduced in 5.11] label:beta[Beta until 5.13]
[cols="<15s,<85"]
|===
| Description
a|
Create a named node vector index for the specified label and property with the given vector dimensionality using either the EUCLIDEAN or COSINE similarity function.
Both similarity functions are case-insensitive.
Use the `db.index.vector.queryNodes` procedure to query the named index.
| Signature
m| db.index.vector.createNodeIndex(indexName :: STRING, label :: STRING, propertyKey :: STRING, vectorDimension :: INTEGER, vectorSimilarityFunction :: STRING)
| Mode
m|SCHEMA
| Replaced by
m|CREATE VECTOR INDEX ...
|===

[[procedure_db_index_vector_queryNodes]]
.db.index.vector.queryNodes()  label:new[Introduced in 5.11] label:beta[Beta until 5.13]
[cols="<15s,<85"]
|===
| Description
a|
Query the given vector index.
Returns requested number of nearest neighbors to the provided query vector, and their similarity score to that query vector, based on the configured similarity function for the index.
The similarity score is a value between [0, 1]; where `0` indicates least similar, `1` most similar.
| Signature
m| db.index.vector.queryNodes(indexName :: STRING, numberOfNearestNeighbours :: INTEGER, query :: LIST<FLOAT>) :: (node :: NODE, score :: FLOAT)
| Mode
m|READ
|===

[[procedure_db_info]]
.db.info()
[cols="<15s,<85"]
|===
| Description
a|
Provides information regarding the database.
| Signature
m|db.info() :: (id :: STRING, name :: STRING, creationDate :: STRING)
| Mode
m|READ
// | Default roles
// m|reader, editor, publisher, architect, admin
|===

[NOTE]
====
This procedure is not considered safe to run from multiple threads.
It is therefore not supported by the parallel runtime (introduced in Neo4j 5.13).
For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/planning-and-tuning/runtimes/concepts#runtimes-parallel-runtime[Cypher Manual -> Parallel runtime].
====


[[procedure_db_labels]]
.db.labels()
[cols="<15s,<85"]
|===
| Description
a|
List all labels attached to nodes within a database according to the user's access rights.
The procedure returns empty results if the user is not authorized to view those labels.
| Signature
m|db.labels() :: (label :: STRING)
| Mode
m|READ
// | Default roles
// m|reader, editor, publisher, architect, admin
|===

[NOTE]
====
This procedure is not considered safe to run from multiple threads.
It is therefore not supported by the parallel runtime (introduced in Neo4j 5.13).
For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/planning-and-tuning/runtimes/concepts#runtimes-parallel-runtime[Cypher Manual -> Parallel runtime].
====


[[procedure_db_listlocks]]
.db.listLocks() label:enterprise-edition[] label:admin-only[]
[cols="<15s,<85"]
|===
| Description
a|
List all locks at this database.
| Signature
m|db.listLocks() :: (mode :: STRING, resourceType :: STRING, resourceId :: INTEGER, transactionId :: STRING)
| Mode
m|DBMS
// | Default roles
// m|admin
|===

[NOTE]
====
This procedure is not considered safe to run from multiple threads.
It is therefore not supported by the parallel runtime (introduced in Neo4j 5.13).
For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/planning-and-tuning/runtimes/concepts#runtimes-parallel-runtime[Cypher Manual -> Parallel runtime].
====


[[procedure_db_ping]]
.db.ping()
[cols="<15s,<85"]
|===
| Description
a|
This procedure can be used by client side tooling to test whether they are correctly connected to a database.
The procedure is available in all databases and always returns true.
A faulty connection can be detected by not being able to call this procedure.
| Signature
m|db.ping() :: (success :: BOOLEAN)
| Mode
m|READ
// | Default roles
// m|reader, editor, publisher, architect, admin
|===

[NOTE]
====
This procedure is not considered safe to run from multiple threads.
It is therefore not supported by the parallel runtime (introduced in Neo4j 5.13).
For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/planning-and-tuning/runtimes/concepts#runtimes-parallel-runtime[Cypher Manual -> Parallel runtime].
====

[[procedure_db_prepareforreplanning]]
.db.prepareForReplanning() label:admin-only[]
[cols="<15s,<85"]
|===
| Description
a|
Triggers an index resample and waits for it to complete, and after that clears query caches.
After this procedure has finished queries will be planned using the latest database statistics.
| Signature
m|db.prepareForReplanning(timeOutSeconds = 300 :: INTEGER)
| Mode
m|READ
// | Default roles
// m|admin
|===

[NOTE]
====
This procedure is not considered safe to run from multiple threads.
It is therefore not supported by the parallel runtime (introduced in Neo4j 5.13).
For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/planning-and-tuning/runtimes/concepts#runtimes-parallel-runtime[Cypher Manual -> Parallel runtime].
====

[[procedure_db_propertykeys]]
.db.propertyKeys()
[cols="<15s,<85"]
|===
| Description
a|
List all property keys in the database.
| Signature
m|db.propertyKeys() :: (propertyKey :: STRING)
| Mode
m|READ
// | Default roles
// m|reader, editor, publisher, architect, admin
|===

[NOTE]
====
This procedure is not considered safe to run from multiple threads.
It is therefore not supported by the parallel runtime (introduced in Neo4j 5.13).
For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/planning-and-tuning/runtimes/concepts#runtimes-parallel-runtime[Cypher Manual -> Parallel runtime].
====

[[procedure_db_relationshiptypes]]
.db.relationshipTypes()
[cols="<15s,<85"]
|===
| Description
a|
List all types attached to relationships within a database according to the user's access rights.
The procedure returns empty results if the user is not authorized to view those relationship types.
| Signature
m|db.relationshipTypes() :: (relationshipType :: STRING)
| Mode
m|READ
// | Default roles
// m|reader, editor, publisher, architect, admin
|===

[NOTE]
====
This procedure is not considered safe to run from multiple threads.
It is therefore not supported by the parallel runtime (introduced in Neo4j 5.13).
For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/planning-and-tuning/runtimes/concepts#runtimes-parallel-runtime[Cypher Manual -> Parallel runtime].
====

[[procedure_db_resampleindex]]
.db.resampleIndex()
[cols="<15s,<85"]
|===
| Description
a|
Schedule resampling of an index (for example: `CALL db.resampleIndex("MyIndex")`).
| Signature
m|db.resampleIndex(indexName :: STRING)
| Mode
m|READ
// | Default roles
// m|reader, editor, publisher, architect, admin
|===

[NOTE]
====
This procedure is not considered safe to run from multiple threads.
It is therefore not supported by the parallel runtime (introduced in Neo4j 5.13).
For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/planning-and-tuning/runtimes/concepts#runtimes-parallel-runtime[Cypher Manual -> Parallel runtime].
====

[[procedure_db_resampleoutdatedindexes]]
.db.resampleOutdatedIndexes()
[cols="<15s,<85"]
|===
| Description
a|
Schedule resampling of all outdated indexes.
| Signature
m|db.resampleOutdatedIndexes()
| Mode
m|READ
// | Default roles
// m|reader, editor, publisher, architect, admin
|===

[NOTE]
====
This procedure is not considered safe to run from multiple threads.
It is therefore not supported by the parallel runtime (introduced in Neo4j 5.13).
For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/planning-and-tuning/runtimes/concepts#runtimes-parallel-runtime[Cypher Manual -> Parallel runtime].
====


[[procedure_db_schema_nodetypeproperties]]
.db.schema.nodeTypeProperties()
[cols="<15s,<85"]
|===
| Description
a|
Show the derived property schema of the nodes in tabular form.
| Signature
m|db.schema.nodeTypeProperties() :: (nodeType :: STRING, nodeLabels :: LIST<STRING>, propertyName :: STRING, propertyTypes :: LIST<STRING>, mandatory :: BOOLEAN)
| Mode
m|READ
// | Default roles
// m|reader, editor, publisher, architect, admin
|===

[NOTE]
====
This procedure is not considered safe to run from multiple threads.
It is therefore not supported by the parallel runtime (introduced in Neo4j 5.13).
For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/planning-and-tuning/runtimes/concepts#runtimes-parallel-runtime[Cypher Manual -> Parallel runtime].
====

[[procedure_db_schema_reltypeproperties]]
.db.schema.relTypeProperties()
[cols="<15s,<85"]
|===
| Description
a|
Show the derived property schema of the relationships in tabular form.
| Signature
m|db.schema.relTypeProperties() :: (relType :: STRING, propertyName :: STRING, propertyTypes :: LIST<STRING>, mandatory :: BOOLEAN)
| Mode
m|READ
// | Default roles
// m|reader, editor, publisher, architect, admin
|===

[NOTE]
====
This procedure is not considered safe to run from multiple threads.
It is therefore not supported by the parallel runtime (introduced in Neo4j 5.13).
For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/planning-and-tuning/runtimes/concepts#runtimes-parallel-runtime[Cypher Manual -> Parallel runtime].
====

[[procedure_db_schema_visualization]]
.db.schema.visualization()
[cols="<15s,<85"]
|===
| Description
a|
Visualizes the schema of the data based on available statistics.
A new node is returned for each label.
The properties represented on the node include: name (label name), indexes (list of indexes), and constraints (list of constraints).
A relationship of a given type is returned for all possible combinations of start and end nodes.
The properties represented on the relationship include: name (type name).
Note that this may include additional relationships that do not exist in the data due to the information available in the count store.
| Signature
m|db.schema.visualization() :: (nodes :: LIST<NODE>, relationships :: LIST<RELATIONSHIP>)
| Mode
m|READ
// | Default roles
// m|reader, editor, publisher, architect, admin
|===

[NOTE]
====
This procedure is not considered safe to run from multiple threads.
It is therefore not supported by the parallel runtime (introduced in Neo4j 5.13).
For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/planning-and-tuning/runtimes/concepts#runtimes-parallel-runtime[Cypher Manual -> Parallel runtime].
====

[[procedure_db_stats_clear]]
.db.stats.clear() label:admin-only[]
[cols="<15s,<85"]
|===
| Description
a|
Clear collected data of a given data section.

Valid sections are `'QUERIES'`
| Signature
m|db.stats.clear(section :: STRING) :: (section :: STRING, success :: BOOLEAN, message :: STRING)
| Mode
m|READ
// | Default roles
// m|admin
|===


[[procedure_db_stats_collect]]
.db.stats.collect() label:admin-only[]
[cols="<15s,<85"]
|===
| Description
a|
Start data collection of a given data section.

Valid sections are `'QUERIES'`
| Signature
m|db.stats.collect(section :: STRING, config = {} :: MAP) :: (section :: STRING, success :: BOOLEAN, message :: STRING)
| Mode
m|READ
// | Default roles
// m|admin
|===


[[procedure_db_stats_retrieve]]
.db.stats.retrieve() label:admin-only[]
[cols="<15s,<85"]
|===
| Description
a|
Retrieve statistical data about the current database.

Valid sections are `'GRAPH COUNTS', 'TOKENS', 'QUERIES', 'META'`
| Signature
m|db.stats.retrieve(section :: STRING, config = {} :: MAP) :: (section :: STRING, data :: MAP)
| Mode
m|READ
// | Default roles
// m|admin
|===


[[procedure_db_stats_retrieveallanonymized]]
.db.stats.retrieveAllAnonymized() label:admin-only[]
[cols="<15s,<85"]
|===
| Description
a|
Retrieve all available statistical data about the current database, in an anonymized form.
| Signature
m|db.stats.retrieveAllAnonymized(graphToken :: STRING, config = {} :: MAP) :: (section :: STRING, data :: MAP)
| Mode
m|READ
// | Default roles
// m|admin
|===


[[procedure_db_stats_status]]
.db.stats.status() label:admin-only[]
[cols="<15s,<85"]
|===
| Description
a|
Retrieve the status of all available collector daemons, for this database.
| Signature
m|db.stats.status() :: (section :: STRING, status :: STRING, data :: MAP)
| Mode
m|READ
// | Default roles
// m|admin
|===


[[procedure_db_stats_stop]]
.db.stats.stop() label:admin-only[]
[cols="<15s,<85"]
|===
| Description
a|
Stop data collection of a given data section.

Valid sections are `'QUERIES'`
| Signature
m|db.stats.stop(section :: STRING) :: (section :: STRING, success :: BOOLEAN, message :: STRING)
| Mode
m|READ
// | Default roles
// m|admin
|===

[[procedure_dbms_checkconfigvalue]]
.dbms.checkConfigValue() label:admin-only[] label:enterprise-edition[]
[cols="<15s,<85"]
|===
| Description
a|
This procedure provides feedback about the validity of a setting value.
It does not change the setting.

The procedure returns:

* `valid`: if the value is valid.
A valid value for a non-dynamic setting requires a restart.
* `message`: a message describing the reason for the invalidity.
The message is empty if the value is `valid` and the setting is dynamic.

| Signature
m|dbms.checkConfigValue(setting :: STRING, value :: STRING) :: (valid :: BOOLEAN, message :: STRING)
| Mode
m|DBMS
// | Default roles
// m|admin
|===

[NOTE]
====
This procedure is not considered safe to run from multiple threads.
It is therefore not supported by the parallel runtime (introduced in Neo4j 5.13).
For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/planning-and-tuning/runtimes/concepts#runtimes-parallel-runtime[Cypher Manual -> Parallel runtime].
====

[[procedure_dbms_cluster_setAutomaticallyEnableFreeServers]]
.dbms.cluster.setAutomaticallyEnableFreeServers() label:enterprise-edition[] label:admin-only[]
[cols="<15s,<85"]
|===
| Description
a|
With this method you can set whether free servers are automatically enabled.
| Signature
m|dbms.cluster.setAutomaticallyEnableFreeServers(autoEnable :: BOOLEAN)
| Mode
m|WRITE
|===

[[procedure_dbms_cluster_checkConnectivity]]
.dbms.cluster.checkConnectivity() label:enterprise-edition[] label:admin-only[]
[cols="<15s,<85"]
|===
| Description
a|
Check the connectivity of this instance to other cluster members.
Not all ports are relevant to all members.
Valid values for 'port-name' are: [CLUSTER, RAFT].
| Signature
m|dbms.cluster.checkConnectivity(port-name = null :: STRING, server = null :: STRING) :: (serverId :: STRING, mode-constraint :: STRING, port-name :: STRING, port-address :: STRING, result :: STRING)
| Mode
m|DBMS
|===

[[procedure_dbms_cluster_cordonServer]]
.dbms.cluster.cordonServer() label:enterprise-edition[] label:admin-only[]
[cols="<15s,<85"]
|===
| Description
a|
Mark a server in the topology as not suitable for new allocations.
It will not force current allocations off the server.
This is useful when deallocating databases when you have multiple unavailable servers.
| Signature
m|dbms.cluster.cordonServer(server :: STRING)
| Mode
m|WRITE
|===


[[procedure_dbms_cluster_routing_getroutingtable]]
.dbms.cluster.routing.getRoutingTable()
[cols="<15s,<85"]
|===
| Description
a|
Returns the advertised bolt capable endpoints for a given database, divided by each endpoint’s capabilities.
For example, an endpoint may serve read queries, write queries, and/or future `getRoutingTable` requests.
| Signature
m|dbms.cluster.routing.getRoutingTable(context :: MAP, database = null :: STRING) :: (ttl :: INTEGER, servers :: LIST<MAP>)
| Mode
m|DBMS
// | Default roles
// m|reader, editor, publisher, architect, admin
|===

[[procedure_dbms_cluster_protocols]]
.dbms.cluster.protocols() label:enterprise-edition[]
[cols="<15s,<85"]
|===
| Description
a|
Overview of installed protocols.
| Signature
m|dbms.cluster.protocols() :: (orientation :: STRING, remoteAddress :: STRING, applicationProtocol :: STRING, applicationProtocolVersion :: INTEGER, modifierProtocols :: STRING)
| Mode
m|DBMS
// | Default roles
// m|reader, editor, publisher, architect, admin
|===

[[procedure_dbms_cluster_readreplicatoggle]]
.dbms.cluster.readReplicaToggle() label:enterprise-edition[] label:admin-only[] label:deprecated[Deprecated in 5.6]
[cols="<15s,<85"]
|===
| Description
a|
The toggle can pause or resume read replica (deprecated in favor of `dbms.cluster.secondaryReplicationDisable`)
| Signature
m|dbms.cluster.readReplicaToggle(databaseName :: STRING, pause :: BOOLEAN) :: (state :: STRING)
| Mode
m|DBMS
| Replaced by
a|xref:reference/procedures.adoc#procedure_dbms_cluster_secondaryreplicationdisable[`dbms.cluster.secondaryReplicationDisable()`]
// | Default roles
// m|admin
|===

[TIP]
====
_What is it for?_

You can perform a point-in-time backup, as the backup will contain only the transactions up to the point where the transaction pulling was paused.
Follow these steps to do so:

. Connect directly to the server hosting the database in secondary mode. (Neo4j Driver use `bolt://` or use the HTTP API).
. Pause transaction pulling for the specified database.
. Back up the database, see xref:backup-restore/online-backup.adoc[Back up an online database].

If connected directly to a server hosting a database in secondary mode, Data Scientists can execute analysis on a specific database that is paused, the data will not unexpectedly change while performing the analysis.
====

[NOTE]
====
This procedure can only be executed on a database that runs in a secondary role on the connected server.
====

.Pause transaction pulling for database `neo4j`
[source, cypher, role="noheader"]
----
CALL dbms.cluster.readReplicaToggle("neo4j", true)
----

.Resume transaction pulling for database `neo4j`
[source, cypher, role="noheader"]
----
CALL dbms.cluster.readReplicaToggle("neo4j", false)
----


[[procedure_dbms_cluster_secondaryreplicationdisable]]
.dbms.cluster.secondaryReplicationDisable() label:enterprise-edition[] label:admin-only[] label:new[Introduced in 5.6]
[cols="<15s,<85"]
|===
| Description
a|
The toggle can pause or resume the secondary replication process.
| Signature
m|dbms.cluster.secondaryReplicationDisable(databaseName :: STRING, pause :: BOOLEAN) :: (state :: STRING)
| Mode
m|DBMS
// | Default roles
// m|admin
|===

[TIP]
====
_What is it for?_

You can perform a point-in-time backup, as the backup will contain only the transactions up to the point where the transaction pulling was paused.
Follow these steps to do so:

. Connect directly to the server hosting the database in secondary mode. (Neo4j Driver use `bolt://` or use the HTTP API).
. Pause transaction pulling for the specified database.
. Back up the database, see xref:backup-restore/online-backup.adoc[Back up an online database].

If connected directly to a server hosting a database in secondary mode, Data Scientists can execute analysis on a specific database that is paused, the data will not unexpectedly change while performing the analysis.
====

[NOTE]
====
This procedure can only be executed on a database that runs in a secondary role on the connected server.
====

.Pause transaction pulling for database `neo4j`
[source, cypher, role="noheader"]
----
CALL dbms.cluster.secondaryReplicationDisable("neo4j", true)
----

.Resume transaction pulling for database `neo4j`
[source, cypher, role="noheader"]
----
CALL dbms.cluster.secondaryReplicationDisable("neo4j", false)
----

[[procedure_dbms_cluster_uncordonServer]]
.dbms.cluster.uncordonServer() label:enterprise-edition[] label:admin-only[]
[cols="<15s,<85"]
|===
| Description
a| Remove the cordon on a server, returning it to 'enabled'.
| Signature
m| dbms.cluster.uncordonServer(server :: STRING)
| Mode
m|WRITE
|===


[[procedure_dbms_components]]
.dbms.components()
[cols="<15s,<85"]
|===
| Description
a|
List DBMS components and their versions.
| Signature
m|dbms.components() :: (name :: STRING, versions :: LIST<STRING>, edition :: STRING)
| Mode
m|DBMS
// | Default roles
// m|reader, editor, publisher, architect, admin
|===

[[procedure_dbms_info]]
.dbms.info()
[cols="<15s,<85"]
|===
| Description
a|
Provides information regarding the DBMS.
| Signature
m|dbms.info() :: (id :: STRING, name :: STRING, creationDate :: STRING)
| Mode
m|DBMS
// | Default roles
// m|reader, editor, publisher, architect, admin
|===


[[procedure_dbms_killconnection]]
.dbms.killConnection()
[cols="<15s,<85"]
|===
| Description
a|
Kill network connection with the given connection id.
| Signature
m|dbms.killConnection(id :: STRING) :: (connectionId :: STRING, username :: STRING, message :: STRING)
| Mode
m|DBMS
// | Default roles
// m|reader, editor, publisher, architect, admin
|===


[[procedure_dbms_killconnections]]
.dbms.killConnections()
[cols="<15s,<85"]
|===
| Description
a|
Kill all network connections with the given connection ids.
| Signature
m|dbms.killConnections(ids :: LIST<STRING>) :: (connectionId :: STRING, username :: STRING, message :: STRING)
| Mode
m|DBMS
// | Default roles
// m|reader, editor, publisher, architect, admin
|===


[[procedure_dbms_listactivelocks]]
.dbms.listActiveLocks() label:enterprise-edition[]
[cols="<15s,<85"]
|===
| Description
a|
List the active lock requests granted for the transaction executing the query with the given query id.
| Signature
m|dbms.listActiveLocks(queryId :: STRING) :: (mode :: STRING, resourceType :: STRING, resourceId :: INTEGER)
| Mode
m|DBMS
// | Default roles
// m|reader, editor, publisher, architect, admin
|===

[NOTE]
====
This procedure is not considered safe to run from multiple threads.
It is therefore not supported by the parallel runtime (introduced in Neo4j 5.13).
For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/planning-and-tuning/runtimes/concepts#runtimes-parallel-runtime[Cypher Manual -> Parallel runtime].
====

[[procedure_dbms_listcapabilities]]
.dbms.listCapabilities()
[cols="<15s,<85"]
|===
| Description
a|
List capabilities.
| Signature
m|dbms.listCapabilities() :: (name :: STRING, description :: STRING, value :: ANY)
| Mode
m|DBMS
|===

[[procedure_dbms_listconfig]]
.dbms.listConfig() label:admin-only[]
[cols="<15s,<85"]
|===
| Description
a|
List the currently active configuration settings of Neo4j.
| Signature
m|dbms.listConfig(searchString =  :: STRING) :: (name :: STRING, description :: STRING, value :: STRING, dynamic :: BOOLEAN, defaultValue :: STRING, startupValue :: STRING, explicitlySet :: BOOLEAN, validValues :: STRING)
| Mode
m|DBMS
// | Default roles
// m|admin
|===

[[procedure_dbms_listconnections]]
.dbms.listConnections()
[cols="<15s,<85"]
|===
| Description
a|
List all accepted network connections at this instance that are visible to the user.
| Signature
m|dbms.listConnections() :: (connectionId :: STRING, connectTime :: STRING, connector :: STRING, username :: STRING, userAgent :: STRING, serverAddress :: STRING, clientAddress :: STRING)
| Mode
m|DBMS
// | Default roles
// m|reader, editor, publisher, architect, admin
|===

[[procedure_dbms_listpools]]
.dbms.listPools() label:enterprise-edition[]
[cols="<15s,<85"]
|===
| Description
a|
List all memory pools, including sub pools, currently registered at this instance that are visible to the user.
| Signature
m|dbms.listPools() :: (pool :: STRING, databaseName :: STRING, heapMemoryUsed :: STRING, heapMemoryUsedBytes :: STRING, nativeMemoryUsed :: STRING, nativeMemoryUsedBytes :: STRING, freeMemory :: STRING, freeMemoryBytes :: STRING, totalPoolMemory :: STRING, totalPoolMemoryBytes :: STRING)
| Mode
m|DBMS
// | Default roles
// m|reader, editor, publisher, architect, admin
|===

[NOTE]
====
This procedure is not considered safe to run from multiple threads.
It is therefore not supported by the parallel runtime (introduced in Neo4j 5.13).
For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/planning-and-tuning/runtimes/concepts#runtimes-parallel-runtime[Cypher Manual -> Parallel runtime].
====

[[procedure_dbms_quarantineDatabase]]
.dbms.quarantineDatabase() label:enterprise-edition[] label:admin-only[]
[cols="<15s,<85"]
|===
| Description
a|
Place a database into quarantine or remove it from it.
| Signature
m|dbms.quarantineDatabase(databaseName :: STRING, setStatus :: BOOLEAN, reason = No reason given :: STRING) :: (databaseName :: STRING, quarantined :: BOOLEAN, result :: STRING)
| Mode
m|DBMS
// | Default roles
// m|admin
|===

[[procedure_dbms_queryjmx]]
.dbms.queryJmx()
[cols="<15s,<85"]
|===
| Description
a|
Query JMX management data by domain and name. For instance, use `:` to find all JMX beans.
| Signature
m|dbms.queryJmx(query :: STRING) :: (name :: STRING, description :: STRING, attributes :: MAP)
| Mode
m|DBMS
// | Default roles
// m|reader, editor, publisher, architect, admin
|===


[[procedure_dbms_routing_getroutingtable]]
.dbms.routing.getRoutingTable()
[cols="<15s,<85"]
|===
| Description
a|
Returns the advertised bolt capable endpoints for a given database, divided by each endpoint’s capabilities.
For example an endpoint may serve read queries, write queries and/or future `getRoutingTable` requests.
| Signature
m|dbms.routing.getRoutingTable(context :: MAP, database = null :: STRING) :: (ttl :: INTEGER, servers :: LIST<MAP>)
| Mode
m|DBMS
// | Default roles
// m|reader, editor, publisher, architect, admin
|===

[[procedure_dbms_setDatabaseAllocator]]
.dbms.setDatabaseAllocator() label:enterprise-edition[] label:admin-only[]
[cols="<15s,<85"]
|===
| Description
a|
With this method, you can set the allocator that is responsible for selecting servers for hosting databases.
| Signature
m|dbms.setDatabaseAllocator(allocator :: STRING)
| Mode
a|WRITE
|===

[[procedure_dbms_setDefaultAllocationNumbers]]
.dbms.setDefaultAllocationNumbers() label:enterprise-edition[] label:admin-only[]
[cols="<15s,<85"]
|===
| Description
a| With this method you can set the default number of primaries and secondaries.
| Signature
m|dbms.setDefaultAllocationNumbers(primaries :: INTEGER, secondaries :: INTEGER)
| Mode
a|WRITE
|===

[[procedure_dbms_setDefaultDatabase]]
.dbms.setDefaultDatabase() label:enterprise-edition[] label:admin-only[]
[cols="<15s,<85"]
|===
| Description
a| Change the default database to the provided value.
The database must exist and the old default database must be stopped.
| Signature
m|dbms.setDefaultDatabase(databaseName :: STRING) :: (result :: STRING)
| Mode
a|WRITE
|===

[[procedure_dbms_scheduler_failedjobs]]
.dbms.scheduler.failedJobs() label:enterprise-edition[] label:admin-only[]
[cols="<15s,<85"]
|===
| Description
a|
List failed job runs. There is a limit for amount of historical data.
| Signature
m|dbms.scheduler.failedJobs() :: (jobId :: STRING, group :: STRING, database :: STRING, submitter :: STRING, description :: STRING, type :: STRING, submitted :: STRING, executionStart :: STRING, failureTime :: STRING, failureDescription :: STRING)
| Mode
m|DBMS
// | Default roles
// m|admin
|===

[NOTE]
====
This procedure is not considered safe to run from multiple threads.
It is therefore not supported by the parallel runtime (introduced in Neo4j 5.13).
For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/planning-and-tuning/runtimes/concepts#runtimes-parallel-runtime[Cypher Manual -> Parallel runtime].
====


[[procedure_dbms_scheduler_groups]]
.dbms.scheduler.groups() label:enterprise-edition[] label:admin-only[]
[cols="<15s,<85"]
|===
| Description
a|
List the job groups that are active in the database internal job scheduler.
| Signature
m|dbms.scheduler.groups() :: (group :: STRING, threads :: INTEGER)
| Mode
m|DBMS
// | Default roles
// m|admin
|===

[NOTE]
====
This procedure is not considered safe to run from multiple threads.
It is therefore not supported by the parallel runtime (introduced in Neo4j 5.13).
For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/planning-and-tuning/runtimes/concepts#runtimes-parallel-runtime[Cypher Manual -> Parallel runtime].
====

[[procedure_dbms_scheduler_jobs]]
.dbms.scheduler.jobs() label:enterprise-edition[] label:admin-only[]
[cols="<15s,<85"]
|===
| Description
a|
List all jobs that are active in the database internal job scheduler.
| Signature
m|dbms.scheduler.jobs() :: (jobId :: STRING, group :: STRING, submitted :: STRING, database :: STRING, submitter :: STRING, description :: STRING, type :: STRING, scheduledAt :: STRING, period :: STRING, state :: STRING, currentStateDescription :: STRING)
| Mode
m|DBMS
// | Default roles
// m|admin
|===

[NOTE]
====
This procedure is not considered safe to run from multiple threads.
It is therefore not supported by the parallel runtime (introduced in Neo4j 5.13).
For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/planning-and-tuning/runtimes/concepts#runtimes-parallel-runtime[Cypher Manual -> Parallel runtime].
====

[[procedure_dbms_security_clearauthcache]]
.dbms.security.clearAuthCache() label:enterprise-edition[] label:admin-only[]
[cols="<15s,<85"]
|===
| Description
a|
Clears authentication and authorization cache.
| Signature
m|dbms.security.clearAuthCache()
| Mode
m|DBMS
// | Default roles
// m|admin
|===

[[procedure_dbms_setconfigvalue]]
.dbms.setConfigValue() label:enterprise-edition[] label:admin-only[]
[cols="<15s,<85"]
|===
| Description
a|
Update a given setting value.
Passing an empty value results in removing the configured value and falling back to the default value.
Changes do not persist and are lost if the server is restarted.
In a clustered environment, `dbms.setConfigValue` affects only the cluster member it is run against.
| Signature
m|dbms.setConfigValue(setting :: STRING, value :: STRING)
| Mode
m|DBMS
// | Default roles
// m|admin
|===


[[procedure_dbms_showcurrentuser]]
.dbms.showCurrentUser()
[cols="<15s,<85"]
|===
| Description
a|
Show the current user.
| Signature
m|dbms.showCurrentUser() :: (username :: STRING, roles :: LIST<STRING>, flags :: LIST<STRING>)
| Mode
m|DBMS
// | Default roles
// m|reader, editor, publisher, architect, admin
|===

[[procedure_dbms_showTopologyGraphConfig]]
.dbms.showTopologyGraphConfig() label:enterprise-only[] label:admin-only[]
[cols="<15s,<85"]
|===
| Description
a| With this method the configuration of the Topology Graph can be displayed.
| Signature
m|dbms.showTopologyGraphConfig() :: (allocator :: STRING, defaultPrimariesCount :: INTEGER, defaultSecondariesCount :: INTEGER, defaultDatabase :: STRING, autoEnableFreeServers :: BOOLEAN)
| Mode
m|READ
|===

[[procedure_dbms_upgrade]]
.dbms.upgrade() label:admin-only[] label:deprecated[Deprecated in 5.9]
[cols="<15s,<85"]
|===
| Description
a|
Upgrade the system database schema if it is not the current schema.
| Signature
m|dbms.upgrade() :: (status :: STRING, upgradeResult :: STRING)
| Mode
m|WRITE
// | Default roles
// m|admin
|===

[NOTE]
====
This procedure is not considered safe to run from multiple threads.
It is therefore not supported by the parallel runtime (introduced in Neo4j 5.13).
For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/planning-and-tuning/runtimes/concepts#runtimes-parallel-runtime[Cypher Manual -> Parallel runtime].
====

[[procedure_dbms_upgradestatus]]
.dbms.upgradeStatus() label:admin-only[] label:deprecated[Deprecated in 5.9]
[cols="<15s,<85"]
|===
| Description
a|
Report the current status of the system database sub-graph schema.
| Signature
m|dbms.upgradeStatus() :: (status :: STRING, description :: STRING, resolution :: STRING)
| Mode
m|READ
// | Default roles
// m|admin
|===

[NOTE]
====
This procedure is not considered safe to run from multiple threads.
It is therefore not supported by the parallel runtime (introduced in Neo4j 5.13).
For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/planning-and-tuning/runtimes/concepts#runtimes-parallel-runtime[Cypher Manual -> Parallel runtime].
====

[[procedure_genai_vector_encodeBatch]]
.genai.vector.encodeBatch() label:aura-only[Available only on Aura]
[cols="<15s,<85"]
|===
| Description
a|
Encode a given batch of resources as vectors using the named provider.
For each element in the given resource LIST this returns:

* the corresponding 'index' within that LIST,
* the original 'resource' element itself,
* and the encoded 'vector'
| Signature
m|genai.vector.encodeBatch(resources :: LIST<STRING>, provider :: STRING, configuration :: MAP = {}) :: (index :: INTEGER, resource :: STRING, vector :: LIST<FLOAT>)
|===

For more information, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/genai-integrations/#multiple-embeddings[Cypher Manual -> Generating a batch of embeddings].

[[procedure_tx_getmetadata]]
.tx.getMetaData()
[cols="<15s,<85"]
|===
| Description
a|
Provides attached transaction metadata.
| Signature
m|tx.getMetaData() :: (metadata :: MAP)
| Mode
m|DBMS
// | Default roles
// m|reader, editor, publisher, architect, admin
|===


[[procedure_tx_setmetadata]]
.tx.setMetaData()
[cols="<15s,<85"]
|===
| Description
a|
Attaches a map of data to the transaction.
The data will be printed when listing queries, and inserted into the query log.
| Signature
m|tx.setMetaData(data :: MAP)
| Mode
m|DBMS
// | Default roles
// m|reader, editor, publisher, architect, admin
|===
