[[causal-cluster-gcp]]
= Causal Clusters (VM-based)
:description: This chapter describes how to deploy and run Neo4j Causal Cluster from the GCP Marketplace.

Neo4j Enterprise is registered in GCP Marketplace.


== Prerequisites

* You have a Neo4j Enterprise license.
* You are familiar with the xref:clustering/index.adoc[Causal Cluster architecture].
* You know how to access cloud-hosted Neo4j from your application. See the https://neo4j.com/docs/driver-manual/4.0/[Driver Manual].


== Deploy Neo4j via the GCP Marketplace

Deploy Neo4j Enterprise from the https://console.cloud.google.com/marketplace/product/neo4j/neo4j-enterprise-edition[Google Cloud Launcher console] following the interactive prompts.

Once the deploy finishes, save the URL, username, and password.


== Start using Neo4j Browser

Use your browser to access the cloud-based database URL, and log in with the initial username and password provided.
You may see an SSL warning screen because the out-of-the-box deployment uses an unsigned SSL certificate.
The initial password is set to a strong, random password and is saved as a metadata entry on the VMs.

To verify that the cluster has formed correctly, run the following Cypher statement:

[source, cypher]
--
CALL dbms.cluster.overview()
--

The result is one leader and minimum two followers.
The IP addresses and endpoints must be the same as the ones for your running instances, displayed by the Compute Engine.


== Access your instance via SSH

Cluster members are regular Google Compute Engine VMs.
Therefore, you can access any of them via SSH from the Deployment Manager screen, or by running the following command in the Google Cloud CLI:

[source, shell]
--
gcloud compute ssh my-cluster-deploy-vm-1
--

== Your cluster default configuration

The following notes are provided on your default cluster configuration.

* Ports `7687` (bolt) and `7473` (HTTPS access) are the only ports exposed to the entire internet.
Consider narrowing the access to these ports to only your needed networks.
External unencrypted HTTP access is disabled by default.
* Ports `5000`, `6000`, and `7000` are enabled only for internal network access (`10.0.0.8`), between the cluster nodes.
* Because cloud VMs can start and stop with different IP addresses, the configuration of these VMs is driven by a file in _/etc/neo4j/neo4j.template_.
Configuration changes must be made to the template, not to the _/etc/neo4j/neo4j.conf_ file, which is overwritten with the template substitutions at every startup.
The template allows you to configure aspects of the cluster with the VMs metadata.
The template’s behavior and layout match the usual _neo4j.conf_ file.


== What’s next

* Visit xref:clustering/index.adoc[Clustering] for more information on how to configure your cluster.
* Add users and change passwords as necessary.
* Consider creating DNS entries with Google to be able to address your cluster with client applications under a single hostname.


== Terminating the deployment

You can use the deployment manager to delete the deployment.
To ensure data safety, the disks that back the VMs are not removed when you delete the cluster deployment.
