# This is an example of the docs-pr.yml workflow available from the recrwplay org
name: "Verify Branch"

on:
  # push:
  #   branches:
  #     - dev
  workflow_dispatch:
    inputs:
      html:
        description: 'Generate HTML'
        type: boolean
        required: false
        default: true

jobs:

  docs-build:
    if: ${{ inputs.html || github.event_name == 'push' }}
    name: Generate HTML
    uses: neo4j/docs-tools/.github/workflows/reusable-docs-build.yml@v2
    with:
      package-script: verify:publish
      deploy-id: 0

  docs-verify:
    name: Verify HTML
    needs: docs-build
    uses: neo4j/docs-tools/.github/workflows/reusable-docs-verify.yml@v2
    with:
      failOnWarnings: true
