:description: This section describes how to perform batch imports of data into Neo4j using the `import` command of `neo4j-admin`.
[[import]]
= Import
:description: This section describes how to perform batch imports of data into Neo4j using the `import` command of `neo4j-admin`. 

[[import-tool]]
There are two ways to import data from CSV files into Neo4j: via `neo4j-admin import` or `LOAD CSV`.

If you want to do batch imports of large amounts of data into a Neo4j database from CSV files, use the `import` command of `neo4j-admin`.
This command can **only** be used to load data into a _previously unused database_ and can only be performed **once** per database.
By default, this database is set to `graph.db` but can be configured to other names and locations.

If you wish to import small to medium-sized CSV files into an existing database, use `LOAD CSV`.
`LOAD CSV` can be run as many times as needed and does not require an empty database.

However, using the `import` command of `neo4j-admin` is generally faster since it is run against a stopped and empty database.
This section describes the `neo4j-admin import` option.
For information on `LOAD CSV`, see the link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/clauses/load-csv[Cypher Manual -> `LOAD CSV`].

These are some things you will need to keep in mind when creating your input files:

* Fields are comma-separated by default, but a different delimiter can be specified.
* All files must use the same delimiter.
* Multiple data sources can be used for both nodes and relationships.
* A data source can optionally be provided using multiple files.
* A separate file with a header that provides information on the data fields, must be the first specified file of each data source.
* Fields without corresponding information in the header will not be read.
* UTF-8 encoding is used.
* By default, the importer will trim extra whitespace at the beginning and end of strings.
  Quote your data to preserve leading and trailing whitespaces.


[NOTE]
.Indexes and constraints
====
Indexes and constraints are not created during the import.
Instead, you will need to add these afterwards (see link:{neo4j-docs-base-uri}/cypher-manual/{page-version}/schema[Cypher Manual -> Schema]).
====


This chapter explains how to format the input data and use the import tool.
If you wish to see in-depth examples of using the import tool, refer to the xref:tutorial/import-tool.adoc[Import tutorial].

The following sections describe how to use the import tool:

* xref:tools/import/syntax.adoc[Syntax] - The syntax of the `neo4j-admin import` command.
* xref:tools/import/file-header-format.adoc[CSV header format] - How to construct the header row of each CSV file.
* xref:tools/import/options.adoc[Options] - The options available for use with `neo4j-admin import`.


